// # ═══════════════════════════════════════════════════════════════════════════
// # GRAMMAR PATTERNS — Extended Set 2: Expansions + Core Structures
// # ═══════════════════════════════════════════════════════════════════════════
// # All content is original and copyright-free.
// # This file expands existing categories (tenses, modals, passive, reported
// # speech, articles, relative clauses, advanced) and adds two new categories
// # (gerunds & infinitives, comparatives & superlatives).
// # Categories sharing an ID with grammar-data.ts are merged by the page.

import type { GrammarCategory } from './types'

export const GRAMMAR_CATEGORIES_2: GrammarCategory[] = [

  // # ═══════════════════════════════════════════════════════════════════
  // # TENSES — 4 missing tenses to complete all 12 + going-to
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'tenses',
    name: 'Tenses',
    description: 'All 12 English tenses — when to use each one and how to form them.',
    patterns: [
      { id: 'past-perfect-continuous', name: 'Past Perfect Continuous', category: 'tenses', level: 'B2', structure: 'Subject + had + been + verb-ing', meaning: 'Emphasises how long an action had been in progress before another past event.', context: 'Explaining cause-and-effect in narratives and emphasising duration before a past interruption.', example: 'She had been studying for three hours when the power went out.', explanation: 'Combines the "before another past event" idea of past perfect with the "duration" emphasis of continuous. Use it when you want to stress HOW LONG something was happening before it was interrupted. Compare: "I had waited for an hour" (past perfect — states the fact) vs "I had been waiting for an hour" (past perfect continuous — emphasises the long, tiring wait). Often explains why something happened: "He was tired because he had been running."', moreExamples: ['They had been living in Paris for five years before they moved to London.', 'It had been raining all morning, so the pitch was waterlogged.', 'How long had you been waiting before the taxi arrived?'], commonMistakes: ['Using with stative verbs: "I had been knowing him" — use "I had known him"', 'Confusing with past continuous: past perfect continuous = before ANOTHER past event; past continuous = background action at a past moment'] },
      { id: 'future-continuous', name: 'Future Continuous', category: 'tenses', level: 'B2', structure: 'Subject + will + be + verb-ing', meaning: 'Describes an action that will be in progress at a specific time in the future.', context: 'Talking about what you will be doing at a certain moment, polite enquiries, and parallel future actions.', example: 'This time tomorrow, I\'ll be flying to Tokyo.', explanation: 'Three uses: 1) Action in progress at a future time: "At 8 p.m. tonight, I\'ll be watching the match"; 2) Polite enquiry (softer than "will you"): "Will you be using the car this evening?" (= I\'d like to borrow it); 3) Events that will happen as a matter of course: "I\'ll be seeing John at work, so I\'ll pass on the message." It makes the future feel more vivid and real — like painting a picture of the moment.', moreExamples: ['Don\'t call between 2 and 4 — I\'ll be having a meeting.', 'Will you be joining us for dinner tonight?', 'This time next week, we\'ll be lying on a beach in Greece.'], commonMistakes: ['Using for planned events without the "in progress" meaning: "I\'ll be meeting him at 3" is fine (polite/matter-of-course), but "I\'m meeting him at 3" is more natural for arrangements', 'Forgetting "be": "I will flying" instead of "I will be flying"'] },
      { id: 'future-perfect', name: 'Future Perfect', category: 'tenses', level: 'B2', structure: 'Subject + will + have + past participle', meaning: 'Describes an action that will be completed before a specific point in the future.', context: 'Deadlines, milestones, and looking back from a future point in time.', example: 'By next June, she will have finished her degree.', explanation: 'The future perfect looks at the future from an even further future point — it tells you what will be DONE by then. Key time markers: by + future time (by tomorrow, by next year, by the time you arrive, by 2030). Common in professional contexts: "We will have completed the project by the end of Q3." Also for assumptions: "He\'ll have left by now" (= I assume he has already left).', moreExamples: ['By the time you read this, I will have already left the country.', 'They will have been married for 25 years next April.', 'Will you have finished the report by Friday?'], commonMistakes: ['Forgetting "have": "I will finished" instead of "I will have finished"', 'Using present perfect instead: "By next year, I have saved enough" — must be "I will have saved enough"'] },
      { id: 'future-perfect-continuous', name: 'Future Perfect Continuous', category: 'tenses', level: 'C1', structure: 'Subject + will + have + been + verb-ing', meaning: 'Emphasises how long an action will have been in progress by a specific future point.', context: 'Emphasising duration up to a future milestone — often with "for" or "by the time".', example: 'By December, I will have been working here for ten years.', explanation: 'The rarest tense in English, but powerful for emphasising impressive durations. Combines "completed before a future point" (future perfect) with "emphasis on duration" (continuous). Almost always used with "for" + duration or "by" + future time. Sounds impressive in CVs and speeches: "By the time I graduate, I will have been studying medicine for six years."', moreExamples: ['By 6 p.m., she will have been driving for eight hours straight.', 'Next month, they will have been living together for a year.', 'By the time the project launches, the team will have been developing it for two years.'], commonMistakes: ['Overusing it — this tense is rare; if duration isn\'t the point, use future perfect: "I will have finished" (result) vs "I will have been working" (duration)', 'Using with stative verbs: "I will have been knowing" — use "I will have known"'] },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # MODALS — 4 additional patterns
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'modals',
    name: 'Modal Verbs',
    description: 'Can, could, may, might, must, should, shall, will, would — and their functions.',
    patterns: [
      { id: 'would-habits', name: 'Would (Past Habits & Hypothetical)', category: 'modals', level: 'B1', structure: 'Subject + would + base verb (past habits) | Subject + would + base verb (hypothetical)', meaning: '"Would" for repeated past actions (like "used to") and for imagining unreal situations.', context: 'Reminiscing about the past, storytelling, and hypothetical scenarios.', example: 'When I was young, we would visit my grandparents every Sunday.', explanation: 'Two main uses beyond conditionals: 1) Past habits: "We would play in the garden for hours" — interchangeable with "used to" for ACTIONS, but NOT for states: "I used to live in Paris" (correct), "I would live in Paris" (wrong — "live" is a state). 2) Hypothetical: "I would love to travel the world" (= if I could). 3) Polite requests: "Would you mind helping me?" — softer than "will you."', moreExamples: ['She would always sing while she cooked dinner.', 'I would prefer the window seat, please.', 'What would you do in my situation?'], commonMistakes: ['Using "would" for past states: "I would be shy as a child" — use "I used to be shy" (states need "used to", not "would")', 'Confusing with "will": "would" = unreal/past/polite; "will" = real/future/direct'] },
      { id: 'modal-perfects', name: 'Modal Perfects (must have, should have, etc.)', category: 'modals', level: 'B2', structure: 'Modal + have + past participle', meaning: 'Expresses deductions, regrets, and criticisms about past events.', context: 'Speculating about what happened, expressing regret, and critiquing past decisions.', example: 'She must have forgotten about the meeting. / You should have told me earlier.', explanation: 'Each modal + have creates a different shade of meaning: 1) MUST HAVE = near-certain deduction: "He must have left" (= I\'m almost sure he left); 2) CAN\'T HAVE / COULDN\'T HAVE = near-certain negative: "She can\'t have said that" (= I don\'t believe it); 3) SHOULD HAVE / SHOULDN\'T HAVE = regret or criticism: "I should have studied harder" (= I didn\'t, and I regret it); 4) COULD HAVE = missed possibility: "You could have warned me" (= you had the chance but didn\'t); 5) MIGHT/MAY HAVE = uncertain deduction: "He might have missed the bus" (= it\'s possible).', moreExamples: ['The lights are off — they must have gone to bed.', 'I shouldn\'t have eaten so much cake.', 'She could have become a professional dancer, but she chose medicine.'], commonMistakes: ['Confusing "must have" (past deduction) with "had to" (past obligation): "I must have left early" (= I think I left) vs "I had to leave early" (= I was obliged to)', '"Should of" instead of "should have" — this is a spelling error from how "should\'ve" sounds'] },
      { id: 'need-dare', name: 'Need & Dare (Semi-modals)', category: 'modals', level: 'B2', structure: 'Need/Dare + base verb (modal use) OR Need to/Dare to + base verb (normal verb use)', meaning: '"Need" and "dare" can work as either modal verbs (no "to", no "-s") or normal verbs (with "to" and "-s").', context: 'Formal negatives, questions, and challenging statements.', example: 'You needn\'t worry about the exam. / How dare you speak to me like that!', explanation: 'As MODALS (mainly in negatives and questions, formal): "You needn\'t come" (= it\'s not necessary), "Need I remind you?" "Dare" as modal is mostly in fixed phrases: "How dare you!", "I daren\'t tell her", "Don\'t you dare!" As NORMAL VERBS (more common): "You don\'t need to come", "She needs to study", "He didn\'t dare to ask", "She dares to disagree." "Needn\'t have done" = you did it but it wasn\'t necessary: "You needn\'t have bought flowers" (= you bought them, but you didn\'t need to). Compare: "You didn\'t need to buy flowers" (= it wasn\'t necessary — maybe you bought them, maybe not).', moreExamples: ['You needn\'t have waited — I was only five minutes late.', 'I daren\'t ask my boss for a pay rise.', 'She didn\'t dare to open the letter.'], commonMistakes: ['Confusing "needn\'t have" (did it unnecessarily) with "didn\'t need to" (it wasn\'t necessary — outcome unclear)', 'Adding "-s" in modal use: "He needn\'t worries" — as a modal, no -s: "He needn\'t worry"'] },
      { id: 'phrasal-modals', name: 'Be able to / Be supposed to / Be about to', category: 'modals', level: 'B1', structure: 'Be + able to / supposed to / about to / allowed to / bound to + base verb', meaning: 'Phrasal alternatives to modal verbs — usable in tenses where modals cannot appear.', context: 'Filling gaps where pure modals have no form (future, perfect, infinitive).', example: 'I wasn\'t able to attend the meeting. / You\'re not supposed to park here.', explanation: 'Modals like "can" and "must" have no infinitive, no past participle, and no future form. Phrasal modals fill these gaps: 1) BE ABLE TO = can (but works everywhere): "I\'ll be able to help tomorrow", "I haven\'t been able to sleep"; 2) BE SUPPOSED TO = should/expected to: "You\'re supposed to wear a uniform"; 3) BE ABOUT TO = imminent future: "The train is about to leave"; 4) BE ALLOWED TO = may/can (permission): "Students are allowed to use calculators"; 5) BE BOUND TO = certain to: "She\'s bound to pass — she studied all week."', moreExamples: ['Will you be able to come to the party?', 'He\'s not supposed to eat sugar — doctor\'s orders.', 'We were about to leave when the phone rang.'], commonMistakes: ['Using "will can" instead of "will be able to": "I will can help" is wrong — say "I will be able to help"', 'Confusing "be used to" (= accustomed to) with "used to" (= past habit) — completely different grammar'] },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # PASSIVE — 2 additional patterns
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'passive',
    name: 'Passive Voice',
    description: 'How and when to use passive constructions across all tenses.',
    patterns: [
      { id: 'get-passive', name: 'Get Passive', category: 'passive', level: 'B2', structure: 'Subject + get + past participle', meaning: 'An informal alternative to "be" passive, often implying something unexpected or negative.', context: 'Informal speech, accidents, and unexpected events.', example: 'He got fired last week. / My phone got stolen on the bus.', explanation: 'The "get" passive is more informal than "be" passive and often carries a negative or unexpected connotation: "get fired", "get arrested", "get hurt", "get caught", "get robbed." It can also suggest the subject\'s involvement: "She got promoted" (implies she worked for it) vs "She was promoted" (neutral). In formal or academic writing, stick to "be" passive. Some "get" passives have become semi-fixed expressions: "get married", "get divorced", "get lost", "get dressed."', moreExamples: ['Two people got injured in the accident.', 'Don\'t get caught cheating — you\'ll be expelled.', 'We got delayed because of roadworks.'], commonMistakes: ['Using "get" passive in formal writing: "The results got published" sounds too informal — use "were published"', 'Confusing "get married" (passive — ceremony happened) with "be married" (state — currently married): "They got married in June" vs "They are married"'] },
      { id: 'have-get-done', name: 'Have / Get Something Done (Causative)', category: 'passive', level: 'B2', structure: 'Subject + have/get + object + past participle', meaning: 'Describes arranging for someone else to do something for you, or experiencing something (often negative).', context: 'Professional services, maintenance, and unfortunate events.', example: 'I had my hair cut yesterday. / She got her car repaired.', explanation: 'Two meanings: 1) ARRANGING a service: "I had my suit dry-cleaned" (= I paid someone to do it — I didn\'t do it myself). "Have" is slightly more formal; "get" is more informal. 2) EXPERIENCING something negative (no choice involved): "He had his wallet stolen" (= it happened to him). Common services: have/get your hair cut, teeth checked, house painted, car serviced, eyes tested, photo taken. The structure is always: have/get + OBJECT + PAST PARTICIPLE.', moreExamples: ['We\'re having the kitchen renovated next month.', 'You should get your eyes tested — you keep squinting.', 'They had their flight cancelled due to the storm.'], commonMistakes: ['Wrong word order: "I had cut my hair" means I cut it MYSELF — "I had my hair cut" means someone else did it', 'Using base form instead of past participle: "I had my car repair" — must be "repaired"'] },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # REPORTED SPEECH — 1 additional pattern
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'reported-speech',
    name: 'Reported Speech',
    description: 'How to report what someone said — tense changes, word order, and reporting verbs.',
    patterns: [
      { id: 'reporting-verbs', name: 'Reporting Verbs & Patterns', category: 'reported-speech', level: 'B2', structure: 'Verb + to-infinitive | Verb + gerund | Verb + that-clause | Verb + object + to-infinitive', meaning: 'Different reporting verbs require different grammatical patterns — not just "said" and "told".', context: 'Academic writing, storytelling, and formal reports.', example: 'She offered to help. / He admitted stealing the money. / They warned us not to go.', explanation: 'Four main patterns: 1) VERB + TO-INFINITIVE: agree, decide, offer, promise, refuse, threaten — "He promised to call"; 2) VERB + GERUND: admit, deny, recommend, suggest — "She denied cheating"; 3) VERB + THAT-CLAUSE: explain, complain, mention, point out — "He explained that he was late"; 4) VERB + OBJECT + TO-INFINITIVE: advise, encourage, invite, order, persuade, remind, warn — "She reminded me to lock the door." For negatives, "not" goes before the infinitive: "He told me NOT to worry."', moreExamples: ['The doctor advised him to rest for a week.', 'She threatened to call the police if it happened again.', 'He suggested going to the Italian restaurant.'], commonMistakes: ['Wrong pattern: "She suggested to go" — suggest takes gerund: "suggested going" or "suggested that we go"', '"He said me" — "say" doesn\'t take an indirect object; use "tell": "He told me"'] },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # ARTICLES — 1 additional pattern
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'articles',
    name: 'Articles & Determiners',
    description: 'A, an, the, and zero article — when to use each one.',
    patterns: [
      { id: 'zero-article', name: 'Zero Article (No Article)', category: 'articles', level: 'B1', structure: 'No article before uncountable nouns, plural generalisations, proper nouns, and certain fixed phrases', meaning: 'Many situations in English require NO article at all — knowing when to leave it out is as important as knowing when to use one.', context: 'General statements, abstract concepts, institutions, meals, sports, and languages.', example: 'Life is short. / She plays tennis every weekend. / I had lunch at noon.', explanation: 'Use NO article for: 1) General/abstract concepts: "Love is blind", "Education is important" (NOT "The education"); 2) Plural generalisations: "Dogs are loyal" (all dogs in general); 3) Meals: "I had breakfast" (NOT "the breakfast"); 4) Sports/games: "She plays chess"; 5) Languages: "He speaks French"; 6) Most countries: "I live in Japan" (NOT "the Japan"); 7) Academic subjects: "I study physics"; 8) Transport: "by bus/train/car" (NOT "by the bus"). Exceptions exist, but these rules cover 90% of cases.', moreExamples: ['Money doesn\'t buy happiness.', 'She goes to church on Sundays.', 'They went to bed early.'], commonMistakes: ['Adding "the" to general statements: "The life is beautiful" — just "Life is beautiful"', 'Adding "the" to meals: "I had the dinner at 7" — just "I had dinner at 7" (unless specifying: "The dinner at the Ritz was excellent")'] },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # RELATIVE CLAUSES — 1 additional pattern
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'relative-clauses',
    name: 'Relative Clauses',
    description: 'Who, which, that, whose, where, when — defining and non-defining clauses.',
    patterns: [
      { id: 'relative-where-when', name: 'Where / When / Why / Whose in Relative Clauses', category: 'relative-clauses', level: 'B1', structure: 'Noun + where/when/why/whose + clause', meaning: 'Relative adverbs and "whose" add information about place, time, reason, and possession.', context: 'Describing locations, time periods, reasons, and ownership.', example: 'That\'s the restaurant where we first met. / I remember the day when it all changed.', explanation: 'WHERE = place: "The hotel where we stayed was excellent." WHEN = time: "I\'ll never forget the moment when I heard the news." WHY = reason: "I don\'t know the reason why she left" (informally, "why" alone works: "I don\'t know why she left"). WHOSE = possession: "The woman whose car was stolen reported it to the police." "Whose" works for people AND things: "a country whose economy is growing" is correct.', moreExamples: ['This is the park where I used to play as a child.', 'There are times when I just want to be alone.', 'She\'s the colleague whose advice I trust most.'], commonMistakes: ['Using "which" instead of "where" for places: "The house which I grew up" — needs "where" or "in which"', 'Confusing "who\'s" (who is) with "whose" (possession): "The man who\'s car" — must be "whose car"'] },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # ADVANCED — 2 additional patterns
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'advanced',
    name: 'Advanced Structures',
    description: 'Inversion, cleft sentences, participle clauses, subjunctive, and ellipsis.',
    patterns: [
      { id: 'participle-clauses', name: 'Participle Clauses', category: 'advanced', level: 'C1', structure: 'Present participle (-ing) / Past participle (-ed) / Perfect participle (having + pp) + main clause', meaning: 'Shortens relative and adverbial clauses, making sentences more concise and elegant.', context: 'Academic and literary writing, formal reports, and advanced spoken English.', example: 'Having finished the report, she went home. / Seen from above, the city looks tiny.', explanation: 'Three types: 1) PRESENT PARTICIPLE: "Walking along the beach, I found a shell" (= While I was walking...); 2) PAST PARTICIPLE: "Written in 1605, the play is still performed today" (= The play, which was written in 1605...); 3) PERFECT PARTICIPLE: "Having lived in Japan for ten years, she speaks fluent Japanese" (= Because she has lived...). The subject of the participle clause MUST be the same as the main clause subject, or the sentence becomes a "dangling participle" error.', moreExamples: ['Not knowing what to say, he remained silent.', 'Exhausted after the marathon, the runners collapsed on the grass.', 'Having been warned about the traffic, we left early.'], commonMistakes: ['Dangling participle: "Walking to school, the rain started" — the rain wasn\'t walking! Correct: "Walking to school, I got caught in the rain"', 'Wrong time reference: use "having + pp" for an action BEFORE the main action, not "-ing"'] },
      { id: 'ellipsis-substitution', name: 'Ellipsis & Substitution', category: 'advanced', level: 'C1', structure: 'Omitting words that are understood from context, or replacing them with "so", "do", "one"', meaning: 'Avoids repetition by leaving out or replacing words the listener can infer.', context: 'Natural conversation, writing, and exam answers — makes English sound fluent and natural.', example: 'A: "Are you coming?" B: "I hope so." / "I can play guitar but my brother can\'t."', explanation: 'ELLIPSIS = leaving words out: "She can speak French and (she can speak) German" — the repeated words are understood. SUBSTITUTION = replacing with a shorter word: "so/not" replace clauses ("I think so" = I think that is true); "do/does/did" replace verbs ("She sings better than I do"); "one/ones" replace nouns ("I like the blue one"). Mastering these makes your English sound natural — without them, you sound robotic and repetitive.', moreExamples: ['"Would you like to come?" "I\'d love to." (= I\'d love to come)', '"She said she\'d help, and she did." (= she helped)', '"These shoes are too small. Do you have bigger ones?"'], commonMistakes: ['Adding unnecessary words: "She can speak French and she can speak German" — native speakers would say "French and German"', 'Wrong substitution: "I hope it" instead of "I hope so" — "so" replaces the whole clause, not just the noun'] },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # NEW CATEGORY: GERUNDS & INFINITIVES
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'gerunds-infinitives',
    name: 'Gerunds & Infinitives',
    description: 'When to use -ing forms vs to + verb — one of English\'s trickiest areas.',
    patterns: [
      { id: 'verb-gerund', name: 'Verb + Gerund (-ing)', category: 'gerunds-infinitives', level: 'B1', structure: 'Subject + verb + verb-ing', meaning: 'Certain verbs must be followed by the -ing form (gerund), never the infinitive.', context: 'Expressing enjoyment, completion, avoidance, and mental processes.', example: 'I enjoy reading before bed. / She avoided answering the question.', explanation: 'Key verbs followed by gerund: enjoy, finish, avoid, keep, mind, suggest, practise, consider, miss, deny, risk, admit, imagine, delay, can\'t help, give up, carry on, put off. Memory trick: if the action is already happening or has happened, use gerund. "I enjoy reading" = the reading happens while you enjoy it. "I finished writing" = the writing is complete.', moreExamples: ['He kept talking even after the bell rang.', 'Would you mind closing the window?', 'She denied stealing the money.'], commonMistakes: ['"I enjoy to read" — always "enjoy reading"', '"I suggest to go" — always "I suggest going" or "I suggest (that) we go"'] },
      { id: 'verb-infinitive', name: 'Verb + Infinitive (to + verb)', category: 'gerunds-infinitives', level: 'B1', structure: 'Subject + verb + to + base verb', meaning: 'Certain verbs must be followed by the to-infinitive, never the gerund.', context: 'Expressing future intentions, desires, decisions, and efforts.', example: 'She decided to study abroad. / I want to learn Japanese.', explanation: 'Key verbs followed by infinitive: want, need, decide, plan, hope, expect, agree, promise, refuse, offer, learn, manage, afford, arrange, fail, pretend, seem, appear, tend. Memory trick: if the action is future, potential, or unrealised, use infinitive. "I decided to go" = the going hasn\'t happened yet when you decided. "She hopes to win" = the winning is still in the future.', moreExamples: ['He agreed to help us with the project.', 'They can\'t afford to buy a new car.', 'She pretended to be asleep.'], commonMistakes: ['"I want going" — always "I want to go"', '"She decided going" — always "She decided to go"', '"I hope seeing you" — always "I hope to see you"'] },
      { id: 'gerund-infinitive-both', name: 'Verbs Taking Both (Different Meaning)', category: 'gerunds-infinitives', level: 'B2', structure: 'Verb + gerund = meaning A | Verb + to-infinitive = meaning B', meaning: 'Some verbs can take either form, but the meaning changes significantly.', context: 'Understanding nuance in everyday speech and avoiding miscommunication.', example: 'I stopped smoking. (= I quit) / I stopped to smoke. (= I paused in order to have a cigarette)', explanation: 'Key pairs: 1) STOP + gerund = quit ("I stopped eating meat"); STOP + infinitive = pause in order to ("I stopped to eat" = paused to have food); 2) REMEMBER/FORGET + gerund = about the past ("I remember meeting her"); + infinitive = about a future task ("Remember to lock the door"); 3) TRY + gerund = experiment with a method ("Try adding more salt"); + infinitive = attempt with effort ("I tried to open the door but it was locked"); 4) REGRET + gerund = regret about past ("I regret telling him"); + infinitive = formal announcement ("I regret to inform you").', moreExamples: ['I\'ll never forget visiting the Grand Canyon. (= it was memorable)', 'Don\'t forget to visit the Grand Canyon. (= make sure you go)', 'He tried calling her, but she didn\'t answer. (= he attempted calling as a method)'], commonMistakes: ['Mixing up "stop": "I stopped to smoke" means you paused to have a cigarette — NOT that you quit smoking', 'Confusing "remember": "I remember to lock the door" = I haven\'t done it yet; "I remember locking the door" = I already did it and I recall doing it'] },
      { id: 'preposition-gerund', name: 'Preposition + Gerund', category: 'gerunds-infinitives', level: 'B1', structure: 'Preposition + verb-ing (NEVER preposition + to + verb)', meaning: 'After any preposition, the verb must take the -ing form — no exceptions.', context: 'All contexts — this is a universal rule in English.', example: 'She\'s interested in learning Arabic. / He left without saying goodbye.', explanation: 'One of English\'s most reliable rules: after ANY preposition (in, on, at, by, for, about, of, without, before, after, despite), the verb takes -ing. This includes "to" when it functions as a PREPOSITION (not part of an infinitive): "I look forward to meeting you" (NOT "to meet"). Other tricky phrases where "to" is a preposition: be used to, be accustomed to, be committed to, object to, in addition to, be dedicated to. Test: if you can replace "to" with a noun, it\'s a preposition.', moreExamples: ['I\'m thinking about changing jobs.', 'She apologised for being late.', 'He\'s good at solving problems.'], commonMistakes: ['"I\'m interested in to learn" — must be "in learning"', '"I look forward to meet you" — "to" here is a preposition: "to meeting you"', '"Thank you for to help" — must be "for helping"'] },
      { id: 'gerund-subject-object', name: 'Gerund as Subject or Object', category: 'gerunds-infinitives', level: 'B2', structure: 'Verb-ing + verb (as subject) | Verb + verb-ing (as object/complement)', meaning: 'The gerund functions as a noun — it can be the subject, object, or complement of a sentence.', context: 'Formal statements, definitions, and expressing general truths.', example: 'Swimming is excellent exercise. / My hobby is painting landscapes.', explanation: 'When a gerund is the SUBJECT, the verb agrees with it as singular: "Running keeps you fit" (NOT "keep"). As subject complement (after "be"): "My biggest fear is flying." As object of a verb: "I love cooking." The infinitive can sometimes replace a gerund subject ("To swim is excellent exercise"), but the gerund sounds more natural and modern. In formal/academic English, gerund subjects are very common: "Implementing this policy requires careful planning."', moreExamples: ['Learning a language takes dedication and practice.', 'Smoking causes cancer — it is the leading preventable cause of death.', 'One of the biggest challenges of management is making difficult decisions.'], commonMistakes: ['Using plural verb: "Swimming are good for you" — gerund subjects take singular verbs: "is good"', 'Using base form as subject: "Swim is good exercise" — use "Swimming is..."'] },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # NEW CATEGORY: COMPARATIVES & SUPERLATIVES
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'comparatives',
    name: 'Comparatives & Superlatives',
    description: 'Comparing things — bigger, better, the most interesting, as tall as, and more.',
    patterns: [
      { id: 'comparative-adjectives', name: 'Comparative Adjectives', category: 'comparatives', level: 'A2', structure: 'Short adj + -er + than | more + long adj + than', meaning: 'Compares two things, showing which has more of a quality.', context: 'Making choices, describing differences, and persuasion.', example: 'She is taller than her brother. / This book is more interesting than that one.', explanation: 'SHORT adjectives (1 syllable, or 2 syllables ending in -y): add -er: tall→taller, happy→happier, big→bigger (double the consonant after short vowel). LONG adjectives (2+ syllables): use "more": more beautiful, more expensive, more intelligent. IRREGULAR forms you must memorise: good→better, bad→worse, far→farther/further, little→less, much/many→more. "Than" follows the comparative: "She is older than me" (informal) or "than I am" (formal).', moreExamples: ['London is more expensive than most European cities.', 'He\'s much better at maths than I am.', 'This exercise is easier than the last one.'], commonMistakes: ['Double comparative: "more bigger" — choose ONE form: either "bigger" or "more big" (but "bigger" is correct)', 'Wrong form: "importanter" — long adjectives use "more": "more important"', 'Forgetting to double consonant: "biger" — must be "bigger" (big → bigger)'] },
      { id: 'superlative-adjectives', name: 'Superlative Adjectives', category: 'comparatives', level: 'A2', structure: 'the + short adj + -est | the + most + long adj', meaning: 'Describes the extreme — the one with the MOST of a quality in a group.', context: 'Rankings, recommendations, and expressing extremes.', example: 'She is the tallest person in her family. / It\'s the most beautiful city I\'ve ever visited.', explanation: 'Same rules as comparatives but with -est / most: tall→the tallest, happy→the happiest, big→the biggest, beautiful→the most beautiful. ALWAYS use "the" before superlatives. IRREGULAR: good→the best, bad→the worst, far→the farthest/furthest. Often paired with present perfect: "It\'s the best film I\'ve ever seen" (NOT "I ever saw"). "In" for places/groups: "the tallest in the class"; "of" for a set: "the oldest of the three sisters."', moreExamples: ['That was the worst meal I\'ve ever had.', 'She\'s the most talented musician in the orchestra.', 'What\'s the longest river in the world?'], commonMistakes: ['Forgetting "the": "She is tallest in the class" — must be "the tallest"', 'Double superlative: "the most biggest" — choose one: "the biggest"', 'Using past simple: "the best I ever saw" — use present perfect: "I\'ve ever seen"'] },
      { id: 'as-as-comparison', name: 'As ... As (Equal Comparison)', category: 'comparatives', level: 'A2', structure: 'as + adjective/adverb + as', meaning: 'Shows two things are equal in some quality, or (with "not") that they are unequal.', context: 'Comparisons where things are similar, and similes.', example: 'She\'s as tall as her mother. / This version isn\'t as good as the original.', explanation: '"As...as" compares equally: "He runs as fast as his brother" (= same speed). Negative "not as...as" = less: "It\'s not as cold as yesterday" (= yesterday was colder). Common similes use this structure: "as white as snow", "as busy as a bee", "as easy as pie." You can modify with "just", "almost", "nearly", "not quite", "twice", "half": "She earns twice as much as I do."', moreExamples: ['The sequel wasn\'t as exciting as the first film.', 'He\'s not nearly as experienced as the other candidates.', 'She speaks French almost as fluently as a native speaker.'], commonMistakes: ['Using "so...as" in positives: "She is so tall as her mother" — in positive sentences, use "as...as"; "so...as" is only correct in negatives (and even then, "not as...as" is more common)', 'Mixing with comparatives: "She is as taller as" — just "as tall as" (base form)'] },
      { id: 'double-comparative', name: 'The More ... The More (Double Comparative)', category: 'comparatives', level: 'B1', structure: 'The + comparative, the + comparative', meaning: 'Shows that two things change together — as one increases, the other does too.', context: 'Expressing proportional relationships, cause-and-effect, and trends.', example: 'The more you practise, the better you get. / The harder he works, the more he earns.', explanation: 'This structure links two changes: when A increases, B also increases (or decreases). Both halves use comparatives. With short adjectives: "The older you get, the wiser you become." With longer adjectives: "The more expensive the restaurant, the better the service." Common fixed phrases: "The sooner, the better", "The more, the merrier." The clause can be reduced: "The bigger, the better" (no verb needed).', moreExamples: ['The more I learn about this topic, the more interesting it becomes.', 'The less sleep I get, the worse I feel the next day.', 'The earlier you book, the cheaper the tickets are.'], commonMistakes: ['Forgetting "the": "More you practise, better you get" — both "the"s are required', 'Using positive form: "The much you eat" — must be comparative: "The more you eat"'] },
      { id: 'modified-comparatives', name: 'Modifying Comparatives', category: 'comparatives', level: 'B1', structure: 'much/far/a lot/slightly/a bit/a little + comparative adjective', meaning: 'Adds intensity to comparisons — how MUCH bigger, better, or different something is.', context: 'Giving precise descriptions, softening criticism, and emphasising differences.', example: 'This restaurant is much better than the one we went to last time.', explanation: 'BIG difference: much, far, a lot, considerably, significantly + comparative: "This is far more difficult than I expected." SMALL difference: slightly, a bit, a little, marginally, somewhat + comparative: "Today is slightly warmer than yesterday." "Very" CANNOT modify comparatives: "very bigger" is wrong — use "much bigger." For emphasis with "the most": "by far the best", "easily the most talented."', moreExamples: ['The exam was a lot harder than I thought it would be.', 'She\'s slightly older than her husband.', 'This is by far the best pizza I\'ve ever had.'], commonMistakes: ['"Very bigger" — "very" doesn\'t work with comparatives; use "much" or "far"', '"More better" — "better" IS the comparative of "good"; don\'t add "more"', '"A lot more easier" — "easier" already includes the comparison; say "a lot easier"'] },
    ],
  },
]
