// # ═══════════════════════════════════════════════════════════════════════════
// # GRAMMAR PATTERNS REFERENCE — Complete English Grammar A1 to C2
// # ═══════════════════════════════════════════════════════════════════════════
// # All content is original and copyright-free.
// # Each pattern includes: structure, meaning, context, example, explanation,
// # additional examples, and common mistakes.

import type { GrammarCategory } from './types'

export const GRAMMAR_CATEGORIES: GrammarCategory[] = [

  // # ═══════════════════════════════════════════════════════════════════
  // # 1. TENSES
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'tenses',
    name: 'Tenses',
    description: 'All 12 English tenses — when to use each one and how to form them.',
    patterns: [
      { id: 'present-simple', name: 'Present Simple', category: 'tenses', level: 'A1', structure: 'Subject + base verb (+s/es for he/she/it)', meaning: 'Describes habits, facts, routines, and permanent states.', context: 'Daily routines, scientific facts, schedules, and general truths.', example: 'She works in a hospital. / Water boils at 100°C.', explanation: 'The present simple is NOT about "now" — it\'s about things that are generally or always true. For actions happening right now, use the present continuous. Add -s/-es for third person singular (he/she/it). Use "do/does" for questions and negatives.', moreExamples: ['I usually wake up at 7 a.m.', 'The train leaves at 9:15 every morning.', 'He doesn\'t like coffee.'], commonMistakes: ['Using present simple for actions happening now: "I eat lunch" instead of "I\'m eating lunch"', 'Forgetting the -s: "She work" instead of "She works"', 'Using -s with do/does: "Does she works?" instead of "Does she work?"'] },
      { id: 'present-continuous', name: 'Present Continuous', category: 'tenses', level: 'A1', structure: 'Subject + am/is/are + verb-ing', meaning: 'Describes actions happening right now, temporary situations, or future arrangements.', context: 'Current actions, temporary states, and planned future events.', example: 'I\'m studying English right now. / We\'re meeting at 6 tomorrow.', explanation: 'Three main uses: 1) Actions happening at the moment of speaking ("I\'m reading a book"); 2) Temporary situations ("I\'m living with my parents until I find a flat"); 3) Future arrangements with a fixed time ("We\'re flying to Paris on Friday"). Some verbs are rarely used in continuous form (stative verbs): know, believe, belong, want, like.', moreExamples: ['She\'s working from home this week.', 'They\'re building a new school near our house.', 'Are you coming to the party tonight?'], commonMistakes: ['Using continuous with stative verbs: "I\'m knowing the answer" instead of "I know the answer"', 'Forgetting the auxiliary: "She working" instead of "She is working"'] },
      { id: 'past-simple', name: 'Past Simple', category: 'tenses', level: 'A2', structure: 'Subject + verb-ed (regular) or irregular past form', meaning: 'Describes completed actions at a specific time in the past.', context: 'Telling stories, describing past events, and talking about finished periods.', example: 'I visited Paris last summer. / She didn\'t go to the meeting.', explanation: 'The past simple is used for actions that started and finished in the past, often with a time marker (yesterday, last week, in 2020). Regular verbs add -ed; irregular verbs have unique forms you must memorise (go→went, see→saw, buy→bought). Use "did" for questions and negatives: "Did you see that?" / "I didn\'t know."', moreExamples: ['We moved to London in 2019.', 'The film started at 8 and finished at 10.', 'Did you enjoy the concert?'], commonMistakes: ['Using past form after did: "Did you went?" instead of "Did you go?"', 'Confusing with present perfect: "I went there yesterday" (correct) vs "I have gone there yesterday" (wrong)'] },
      { id: 'past-continuous', name: 'Past Continuous', category: 'tenses', level: 'A2', structure: 'Subject + was/were + verb-ing', meaning: 'Describes actions in progress at a specific moment in the past, or background actions.', context: 'Setting the scene in stories, describing interrupted actions, and simultaneous past actions.', example: 'I was sleeping when the phone rang. / While she was cooking, he was cleaning.', explanation: 'Two main uses: 1) Background action interrupted by a shorter action: "I was walking home when it started to rain" (walking = long action, started = short interruption); 2) Two simultaneous actions: "While I was reading, she was watching TV." Often paired with past simple: the past continuous = the background, past simple = the event.', moreExamples: ['At 8 p.m. yesterday, we were having dinner.', 'They were arguing when the teacher walked in.', 'What were you doing at midnight?'], commonMistakes: ['Using past continuous for completed actions: "I was going to school yesterday" (wrong) vs "I went to school yesterday" (correct — completed action)'] },
      { id: 'present-perfect', name: 'Present Perfect', category: 'tenses', level: 'B1', structure: 'Subject + have/has + past participle', meaning: 'Connects the past to the present — for experiences, changes, unfinished actions, and recent events.', context: 'Life experiences, recent events, and situations that started in the past and continue now.', example: 'I have visited Japan three times. / She has lived here since 2015.', explanation: 'The most misunderstood English tense. Key rule: NEVER use it with a finished time (yesterday, last week, in 2020) — use past simple instead. Use present perfect for: 1) Experiences without saying when: "I\'ve tried sushi"; 2) Actions with present results: "I\'ve lost my keys" (= I don\'t have them now); 3) Actions from past to now: "I\'ve worked here for 5 years" (= I still work here).', moreExamples: ['Have you ever been to Australia?', 'They\'ve just arrived.', 'I haven\'t finished yet.'], commonMistakes: ['Using with past time: "I have seen him yesterday" instead of "I saw him yesterday"', 'Confusing for/since: "I\'ve lived here since 5 years" instead of "for 5 years" or "since 2020"'] },
      { id: 'present-perfect-continuous', name: 'Present Perfect Continuous', category: 'tenses', level: 'B1', structure: 'Subject + have/has + been + verb-ing', meaning: 'Emphasises the duration or ongoing nature of an action from the past to the present.', context: 'Activities that started in the past and are still happening, or have just stopped with visible results.', example: 'I\'ve been waiting for an hour. / She\'s been crying — her eyes are red.', explanation: 'Focuses on HOW LONG or the process itself, while present perfect focuses on the result. Compare: "I\'ve read 50 pages" (result — how many) vs "I\'ve been reading for two hours" (duration — how long). Used with for/since to emphasise duration. Also used when you can see evidence of a recent activity: "The ground is wet — it\'s been raining."', moreExamples: ['How long have you been learning English?', 'We\'ve been living here since January.', 'He\'s been working too hard lately.'], commonMistakes: ['Using with stative verbs: "I\'ve been knowing him" instead of "I\'ve known him"', 'Confusing with present perfect: use continuous for duration, simple for number/quantity'] },
      { id: 'past-perfect', name: 'Past Perfect', category: 'tenses', level: 'B2', structure: 'Subject + had + past participle', meaning: 'Describes an action completed before another action in the past.', context: 'Narratives, explaining sequences of past events, and reported speech.', example: 'By the time I arrived, the film had already started.', explanation: 'The "past of the past" — it creates a clear timeline when two past events are mentioned. Event 1 (earlier, past perfect): "the film had started." Event 2 (later, past simple): "I arrived." Also essential for reported speech: "She said she had finished" (direct: "I have finished"). And for third conditional: "If I had known, I would have helped."', moreExamples: ['She had never seen snow before she moved to Canada.', 'We couldn\'t get a table because we hadn\'t booked.', 'Had you met him before the conference?'], commonMistakes: ['Using when the sequence is already clear: "I woke up and had breakfast" is fine — no need for "I woke up and had had breakfast"', 'Overusing it — only needed when the time sequence might be confusing'] },
      { id: 'future-simple', name: 'Future Simple (will)', category: 'tenses', level: 'A2', structure: 'Subject + will + base verb', meaning: 'Predictions, spontaneous decisions, promises, and offers.', context: 'Making predictions, deciding something at the moment of speaking, and making promises.', example: 'I think it will rain tomorrow. / I\'ll help you with that.', explanation: '"Will" is NOT the only way to talk about the future. Use "will" for: 1) Predictions based on opinion: "I think she\'ll pass the exam"; 2) Spontaneous decisions: "The phone\'s ringing — I\'ll answer it"; 3) Promises: "I\'ll always love you"; 4) Offers: "I\'ll carry that for you." For planned future events, use "going to" or present continuous instead.', moreExamples: ['We won\'t be late, I promise.', 'Will you come to the party?', 'It will probably snow tonight.'], commonMistakes: ['Using "will" for planned events: "I will meet John at 3" (= you just decided) vs "I\'m meeting John at 3" (= it\'s arranged)', 'Using "will" after "if" in first conditional: "If it will rain" instead of "If it rains"'] },
      { id: 'future-going-to', name: 'Future: Going To', category: 'tenses', level: 'A2', structure: 'Subject + am/is/are + going to + base verb', meaning: 'Plans decided before speaking, and predictions based on present evidence.', context: 'Talking about intentions and evidence-based predictions.', example: 'I\'m going to start a business next year. / Look at those clouds — it\'s going to rain.', explanation: 'Two main uses: 1) Plans/intentions decided BEFORE speaking: "I\'m going to learn Spanish" (I\'ve already decided); 2) Predictions based on what you can see/evidence: "She\'s going to have a baby" (you can see she\'s pregnant). Compare with "will": "will" = prediction based on opinion; "going to" = prediction based on evidence.', moreExamples: ['We\'re going to move to a bigger house.', 'He\'s going to be late — he\'s still in a meeting.', 'What are you going to do after university?'], commonMistakes: ['Confusing with "will": "I will study medicine" (just decided now) vs "I\'m going to study medicine" (already planned)', 'Saying "I\'m going to go" — grammatically correct but sounds awkward; often shortened to "I\'m going"'] },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 2. CONDITIONALS
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'conditionals',
    name: 'Conditionals',
    description: 'Zero through third conditional, plus mixed conditionals.',
    patterns: [
      { id: 'zero-conditional', name: 'Zero Conditional', category: 'conditionals', level: 'A2', structure: 'If + present simple, present simple', meaning: 'Describes facts, scientific truths, and things that are always true.', context: 'Scientific facts, general rules, and instructions.', example: 'If you heat water to 100°C, it boils.', explanation: 'The zero conditional is for things that are ALWAYS true — not for hypothetical or possible situations. Both clauses use present simple. You can replace "if" with "when" without changing the meaning: "When you mix red and blue, you get purple." It\'s basically a cause-and-effect statement disguised as a conditional.', moreExamples: ['If you press this button, the machine starts.', 'Plants die if they don\'t get enough water.', 'If I eat too much chocolate, I feel sick.'], commonMistakes: ['Using "will" in the result clause: "If you heat water, it will boil" — this changes it to a first conditional (a specific prediction), losing the "always true" meaning'] },
      { id: 'first-conditional', name: 'First Conditional', category: 'conditionals', level: 'B1', structure: 'If + present simple, will + base verb', meaning: 'Describes possible and likely future situations and their results.', context: 'Talking about realistic future possibilities, promises, and warnings.', example: 'If it rains tomorrow, we\'ll stay at home.', explanation: 'For situations the speaker thinks are POSSIBLE or LIKELY. The if-clause uses present simple (NOT will), the result clause uses "will". You can also use "might", "may", "can", or "should" instead of "will" for different levels of certainty: "If you study hard, you might pass" (= possible but not certain).', moreExamples: ['If you don\'t hurry, you\'ll miss the train.', 'I\'ll call you if I need help.', 'What will you do if you get the job?'], commonMistakes: ['Using "will" in the if-clause: "If it will rain" instead of "If it rains"', 'Confusing with zero conditional: first = specific future; zero = general truth'] },
      { id: 'second-conditional', name: 'Second Conditional', category: 'conditionals', level: 'B1', structure: 'If + past simple, would + base verb', meaning: 'Describes hypothetical or unlikely present/future situations.', context: 'Imagining different situations, giving advice, and dreaming.', example: 'If I won the lottery, I would buy a house in the countryside.', explanation: 'For situations that are UNLIKELY, IMAGINARY, or CONTRARY TO REALITY. The past simple doesn\'t refer to the past — it creates distance from reality. "If I were you" (not "if I was") is the traditional form for giving advice, though "was" is increasingly accepted in informal English. "Would" can be replaced by "could" or "might".', moreExamples: ['If I were you, I\'d accept the offer.', 'What would you do if you could fly?', 'If we had more time, we could visit the museum.'], commonMistakes: ['Using "would" in the if-clause: "If I would win" instead of "If I won"', 'Confusing with first conditional: "If I win" (possible) vs "If I won" (unlikely/imaginary)'] },
      { id: 'third-conditional', name: 'Third Conditional', category: 'conditionals', level: 'B2', structure: 'If + past perfect, would have + past participle', meaning: 'Describes hypothetical past situations and their imagined results.', context: 'Expressing regret, reflecting on past decisions, and analysing what could have been different.', example: 'If I had studied harder, I would have passed the exam.', explanation: 'For situations that DID NOT HAPPEN in the past. It\'s about imagining a different past and its consequences. Both the condition and the result are unreal/impossible because the past cannot be changed. Often used to express regret. "Would have" can be replaced by "could have" or "might have".', moreExamples: ['If we had left earlier, we wouldn\'t have missed the flight.', 'She would have helped if you had asked her.', 'If they hadn\'t invented the internet, communication would have been very different.'], commonMistakes: ['Using "would have" in the if-clause: "If I would have known" instead of "If I had known"', 'Mixing with second conditional: "If I studied harder, I would have passed" — this is a mixed conditional (valid but different meaning)'] },
      { id: 'mixed-conditional', name: 'Mixed Conditionals', category: 'conditionals', level: 'C1', structure: 'Type 1: If + past perfect, would + base verb | Type 2: If + past simple, would have + past participle', meaning: 'Connects a past condition to a present result, or a present condition to a past result.', context: 'Complex hypothetical reasoning about how the past affects the present (or vice versa).', example: 'If I had taken that job, I would be living in New York now. (past → present)', explanation: 'Two types: 1) PAST condition → PRESENT result: "If I had been born in France, I would speak French" (I wasn\'t born there → I don\'t speak it now). Uses if + past perfect, would + base verb. 2) PRESENT condition → PAST result: "If she weren\'t so shy, she would have asked for a raise" (she IS shy now → she DIDN\'T ask in the past). Uses if + past simple, would have + past participle.', moreExamples: ['If we hadn\'t missed the train, we would be there by now.', 'If I were more confident, I would have applied for that role.', 'If he hadn\'t broken his leg, he would be playing in the match today.'], commonMistakes: ['Confusing the time references — always check: which part is about the past and which is about the present?', 'Using the wrong tense combination — the if-clause tense determines when the condition exists'] },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 3. MODALS
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'modals',
    name: 'Modal Verbs',
    description: 'Can, could, may, might, must, should, shall, will, would — and their functions.',
    patterns: [
      { id: 'can-could-ability', name: 'Can / Could (Ability)', category: 'modals', level: 'A1', structure: 'Subject + can/could + base verb', meaning: '"Can" = present ability. "Could" = past ability or polite requests.', context: 'Describing abilities, asking for permission, and making requests.', example: 'I can swim. / She could read when she was four.', explanation: '"Can" for present ability, "could" for past ability. For future ability, use "will be able to" (NOT "will can"). "Could" is also more polite than "can" for requests: "Could you help me?" sounds better than "Can you help me?" in formal situations. Negative: "can\'t" / "couldn\'t" (or "cannot" / "could not" in formal writing).', moreExamples: ['Can you speak any other languages?', 'I couldn\'t sleep last night.', 'Could you pass the salt, please?'], commonMistakes: ['"Will can" does not exist — use "will be able to"', '"I can to swim" — no "to" after modal verbs'] },
      { id: 'must-have-to', name: 'Must / Have to (Obligation)', category: 'modals', level: 'B1', structure: 'Subject + must / have to + base verb', meaning: '"Must" = strong internal obligation or speaker\'s authority. "Have to" = external obligation or rules.', context: 'Rules, laws, strong advice, and logical deductions.', example: 'You must wear a seatbelt. / I have to work on Saturdays.', explanation: 'Subtle difference: "must" = the speaker imposes the obligation ("You must try this cake" = I strongly recommend it). "Have to" = external rules or circumstances force it ("I have to wear a uniform" = my employer requires it). In practice, they\'re often interchangeable. BUT the negatives are very different: "mustn\'t" = it\'s forbidden, "don\'t have to" = it\'s not necessary (your choice).', moreExamples: ['Students must submit essays by Friday.', 'You don\'t have to come if you\'re busy.', 'You mustn\'t touch the exhibits.'], commonMistakes: ['Confusing "mustn\'t" (forbidden) with "don\'t have to" (not necessary) — this is one of the most common mistakes in English', '"Must" has no past form — use "had to": "I had to leave early" (NOT "I musted")'] },
      { id: 'should-ought-to', name: 'Should / Ought to (Advice)', category: 'modals', level: 'A2', structure: 'Subject + should / ought to + base verb', meaning: 'Gives advice, recommendations, or expresses what is right or expected.', context: 'Giving advice, expressing opinions about correct behaviour, and making suggestions.', example: 'You should see a doctor about that cough. / You ought to apologise.', explanation: '"Should" and "ought to" are almost identical in meaning — both give advice. "Should" is far more common. "Ought to" sounds slightly more formal and is rarely used in questions or negatives. "Should have + past participle" expresses regret about the past: "I should have studied harder" (= I didn\'t study enough and I regret it).', moreExamples: ['You shouldn\'t eat so much sugar.', 'You should have told me earlier.', 'What should I do?'], commonMistakes: ['"Should" for past regret needs "have": "I should studied" instead of "I should have studied"', 'Confusing "should" (advice) with "must" (obligation) — "should" is a recommendation, "must" is a requirement'] },
      { id: 'may-might-possibility', name: 'May / Might (Possibility)', category: 'modals', level: 'B1', structure: 'Subject + may/might + base verb', meaning: 'Expresses possibility — something that is perhaps true or could happen.', context: 'Uncertainty, speculation, and hedging in academic writing.', example: 'It might rain later. / She may be at home — I\'m not sure.', explanation: '"May" and "might" both express possibility. "May" is slightly more likely than "might", but the difference is small. For past possibility, use "may/might have + past participle": "He might have missed the bus" (= it\'s possible he missed it). "May" is also used for formal permission: "May I sit here?" "Might" is NOT used for permission.', moreExamples: ['This might be the wrong address.', 'She may not come to the party.', 'They might have already left.'], commonMistakes: ['Using "might" for permission — only "may" works: "May I go?" not "Might I go?" (though this exists in very formal British English)', '"May" in the negative: "may not" (NOT "mayn\'t" — this form doesn\'t exist in modern English)'] },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 4. PASSIVE VOICE
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'passive',
    name: 'Passive Voice',
    description: 'How and when to use passive constructions across all tenses.',
    patterns: [
      { id: 'passive-formation', name: 'Passive Formation', category: 'passive', level: 'B2', structure: 'Subject + be (conjugated) + past participle (+ by agent)', meaning: 'Emphasises the action or the receiver rather than the doer.', context: 'Academic writing, news reports, scientific descriptions, and formal documents.', example: 'The Mona Lisa was painted by Leonardo da Vinci. / The bridge is being repaired.', explanation: 'Use passive when: 1) The doer is unknown: "My car was stolen"; 2) The doer is obvious: "The suspect was arrested" (by police — obvious); 3) The action matters more than the doer: "The vaccine was developed in 2020"; 4) Academic/scientific writing: "The samples were analysed." Passive works in all tenses by changing the "be" form: is painted, was painted, has been painted, will be painted, is being painted.', moreExamples: ['English is spoken in over 50 countries.', 'The results will be published next month.', 'The building is being demolished.'], commonMistakes: ['Overusing passive in everyday speech — it sounds unnatural: "A good time was had by us" instead of "We had a good time"', 'Forgetting the past participle: "The book was write" instead of "was written"'] },
      { id: 'passive-reporting', name: 'Passive Reporting Structures', category: 'passive', level: 'C1', structure: 'It is said/believed/thought that... OR Subject + is said/believed + to + infinitive', meaning: 'Reports information from an unnamed source, creating distance from the claim.', context: 'News writing, academic papers, and formal reports.', example: 'It is believed that the company will merge. / The company is believed to be planning a merger.', explanation: 'Two structures with the same meaning: 1) "It is said/believed/reported/thought/known that + clause"; 2) "Subject + is said/believed + to + infinitive." For past reference, use the perfect infinitive: "He is thought to have left the country" (= People think he left). This structure is essential for IELTS Writing Task 1 and academic essays — it sounds more objective than "People say..."', moreExamples: ['It is estimated that 8 million tonnes of plastic enter the oceans each year.', 'The suspect is reported to have fled abroad.', 'It was thought that the ruins dated from the 3rd century.'], commonMistakes: ['Mixing up the structure: "It is believed to be..." should be "He is believed to be..." or "It is believed that he is..."'] },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 5. REPORTED SPEECH
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'reported-speech',
    name: 'Reported Speech',
    description: 'How to report what someone said — tense changes, word order, and reporting verbs.',
    patterns: [
      { id: 'reported-statements', name: 'Reported Statements', category: 'reported-speech', level: 'B2', structure: 'Subject + said/told + (that) + tense shift back', meaning: 'Reports what someone said without using their exact words.', context: 'Retelling conversations, news reporting, and academic citations.', example: 'Direct: "I love this city." → Reported: She said (that) she loved that city.', explanation: 'Key changes: 1) Tense shifts back one step (present→past, past→past perfect, will→would); 2) Pronouns change (I→she/he); 3) Time/place words change (today→that day, here→there, this→that). "Said" doesn\'t need an indirect object: "She said she was tired." "Told" NEEDS one: "She told me she was tired" (NOT "She told she was tired").', moreExamples: ['"I will help you" → He said he would help me.', '"We are leaving" → They told us they were leaving.', '"I have finished" → She said she had finished.'], commonMistakes: ['"She told that she was happy" — "told" needs an object: "She told me that..."', 'Not shifting the tense: "She said she is tired" — should be "was tired" (though present is acceptable if still true)'] },
      { id: 'reported-questions', name: 'Reported Questions', category: 'reported-speech', level: 'B2', structure: 'Subject + asked + if/whether (yes/no) or wh-word + statement word order', meaning: 'Reports a question someone asked without using the question form.', context: 'Retelling conversations involving questions.', example: 'Direct: "Where do you live?" → Reported: She asked where I lived.', explanation: 'Two types: 1) Yes/No questions use "if" or "whether": "Do you like coffee?" → She asked if I liked coffee. 2) Wh- questions keep the question word: "Where is the station?" → He asked where the station was. CRUCIAL: reported questions use STATEMENT word order (subject before verb), NOT question word order. No "do/does/did" in reported questions.', moreExamples: ['"Are you coming?" → He asked if I was coming.', '"What time does it start?" → She asked what time it started.', '"Have you been here before?" → They asked whether I had been there before.'], commonMistakes: ['Keeping question word order: "She asked where did I live" instead of "where I lived"', 'Using a question mark: reported questions are statements, so end with a full stop'] },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 6. ARTICLES & DETERMINERS
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'articles',
    name: 'Articles & Determiners',
    description: 'A, an, the, and zero article — when to use each one.',
    patterns: [
      { id: 'definite-article', name: 'The (Definite Article)', category: 'articles', level: 'A1', structure: 'the + noun', meaning: 'Refers to a specific thing that both speaker and listener know about.', context: 'Referring to specific, known, or unique items.', example: 'The book on the table is mine. / The sun rises in the east.', explanation: 'Use "the" when: 1) Both people know which one: "Pass me the salt" (the one on the table); 2) It\'s unique: "the sun", "the internet", "the government"; 3) Already mentioned: "I saw a dog. The dog was black"; 4) Superlatives: "the best", "the tallest"; 5) With ordinals: "the first", "the second". DON\'T use "the" with: most country names, meals, sports, or general plurals ("Dogs are loyal" NOT "The dogs are loyal").', moreExamples: ['The weather is lovely today.', 'She\'s the best student in the class.', 'We went to the cinema last night.'], commonMistakes: ['Using "the" with general statements: "The life is short" instead of "Life is short"', 'Missing "the" with superlatives: "She is best" instead of "She is the best"', 'Using "the" with most countries: "the France" — just "France" (exceptions: the UK, the USA, the Netherlands)'] },
      { id: 'indefinite-article', name: 'A / An (Indefinite Article)', category: 'articles', level: 'A1', structure: 'a/an + singular countable noun', meaning: 'Refers to something non-specific, mentioned for the first time, or one of many.', context: 'Introducing new information, describing jobs, and classifying.', example: 'She\'s a doctor. / I need an umbrella.', explanation: '"A" before consonant SOUNDS: a book, a university (starts with /j/). "An" before vowel SOUNDS: an apple, an hour (silent h). Use a/an for: 1) First mention: "I saw a man"; 2) Jobs: "She\'s a teacher"; 3) One of many: "Can I have a glass of water?"; 4) With "what" exclamations: "What a beautiful day!" Cannot be used with uncountable nouns ("an information" is wrong) or plurals ("a books" is wrong).', moreExamples: ['He\'s an engineer.', 'I\'d like a coffee, please.', 'There\'s a problem with the printer.'], commonMistakes: ['"An university" — wrong because "university" starts with a /j/ sound: "a university"', '"An" before "h": "an hotel" is old-fashioned; modern English uses "a hotel" because the h is pronounced', 'Using with uncountable nouns: "an advice" — say "a piece of advice"'] },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 7. RELATIVE CLAUSES
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'relative-clauses',
    name: 'Relative Clauses',
    description: 'Who, which, that, whose, where, when — defining and non-defining clauses.',
    patterns: [
      { id: 'defining-relative', name: 'Defining Relative Clauses', category: 'relative-clauses', level: 'B1', structure: 'Noun + who/which/that + verb (no commas)', meaning: 'Identifies exactly which person or thing is being talked about — essential information.', context: 'Specifying and distinguishing between people or things.', example: 'The woman who lives next door is a teacher. / The book that I bought yesterday is excellent.', explanation: 'Defining clauses are ESSENTIAL — remove them and the sentence loses its meaning. "The man who called you" — without "who called you", we don\'t know which man. Use "who" for people, "which" for things, "that" for both (informal). You can omit the relative pronoun when it\'s the object: "The book (that) I bought" but NOT "The man (who) lives here" (who = subject, can\'t omit).', moreExamples: ['Students who study regularly get better results.', 'The restaurant that we visited was amazing.', 'Is this the key which opens the back door?'], commonMistakes: ['Using commas: defining clauses have NO commas', 'Using "what" instead of "that/which": "The thing what I need" — wrong; use "that" or "which"'] },
      { id: 'non-defining-relative', name: 'Non-Defining Relative Clauses', category: 'relative-clauses', level: 'B2', structure: 'Noun + , who/which + verb , (with commas)', meaning: 'Adds extra information about something already identified — not essential.', context: 'Adding interesting or supplementary details about a known subject.', example: 'My sister, who lives in London, is visiting next week.', explanation: 'Non-defining clauses add EXTRA information — remove them and the sentence still makes sense: "My sister is visiting next week." MUST use commas. CANNOT use "that" — only "who" (people) and "which" (things). Cannot omit the pronoun. "Which" can also refer to a whole clause: "He passed the exam, which surprised everyone" (= the fact that he passed surprised everyone).', moreExamples: ['Paris, which is the capital of France, attracts millions of tourists.', 'My manager, who has worked here for 20 years, is retiring.', 'The project was completed on time, which pleased the client.'], commonMistakes: ['Forgetting commas: "My mother who is 65 has retired" needs commas if you only have one mother', 'Using "that" instead of "who/which": "My sister, that lives in London" — wrong in non-defining clauses'] },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 8. ADVANCED STRUCTURES (C1–C2)
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'advanced',
    name: 'Advanced Structures',
    description: 'Inversion, cleft sentences, participle clauses, subjunctive, and ellipsis.',
    patterns: [
      { id: 'inversion-negative', name: 'Inversion after Negative Adverbials', category: 'advanced', level: 'C1', structure: 'Negative adverbial + auxiliary + subject + main verb', meaning: 'Emphasises the negative element by placing it first, creating a dramatic or formal effect.', context: 'Formal writing, speeches, and literary prose.', example: 'Never have I seen such a beautiful sunset. / Rarely does she complain.', explanation: 'When a negative adverbial moves to the front, the subject and auxiliary verb swap (like a question). Common triggers: never, rarely, seldom, hardly, scarcely, barely, not only, at no time, under no circumstances, no sooner...than. If there\'s no auxiliary, add "do/does/did": "Rarely does he eat breakfast." This is a hallmark of advanced English — using it correctly in IELTS/CAE writing impresses examiners.', moreExamples: ['Not only did she win the race, but she also broke the record.', 'At no time should passengers open the emergency doors.', 'Seldom have we experienced such demand for our products.'], commonMistakes: ['Forgetting to invert: "Never I have seen" instead of "Never have I seen"', 'Using with non-negative adverbials: "Always have I loved music" — inversion is only for negative/restrictive adverbials'] },
      { id: 'cleft-sentences', name: 'Cleft Sentences', category: 'advanced', level: 'C1', structure: 'It-cleft: It + was/is + focus + that/who... | Wh-cleft: What + clause + is/was + focus', meaning: 'Highlights a specific piece of information by restructuring the sentence.', context: 'Academic writing, presentations, and emphasising key points.', example: 'It was John who broke the window. / What I need is a good night\'s sleep.', explanation: 'Two types: 1) It-cleft puts the focus after "It was/is": "It was in 2019 that we first met" (emphasises when); 2) Wh-cleft puts the focus at the end: "What surprised me was his honesty" (emphasises what). Useful in essays to control emphasis: "It is the government\'s responsibility to..." or "What the research suggests is that..."', moreExamples: ['It wasn\'t the price that bothered me — it was the quality.', 'What we need is more investment in education.', 'It is this policy that has caused the most controversy.'], commonMistakes: ['Overusing cleft sentences — one or two per essay is enough; more feels forced'] },
      { id: 'subjunctive', name: 'Subjunctive Mood', category: 'advanced', level: 'C2', structure: 'Verb of demand/suggestion + that + subject + base verb (no -s, no "to")', meaning: 'Expresses wishes, demands, suggestions, or hypothetical situations using the base form of the verb.', context: 'Formal proposals, legal language, and literary writing.', example: 'The committee recommended that he resign immediately.', explanation: 'The subjunctive uses the BASE form of the verb regardless of subject: "that he resign" (NOT "resigns"), "that she be informed" (NOT "is informed"), "that it be noted" (NOT "is noted"). Triggered by verbs like: demand, suggest, recommend, insist, propose, request, require. Also in fixed phrases: "if need be", "come what may", "God save the Queen", "be that as it may". British English often uses "should" instead: "I suggest that he should resign."', moreExamples: ['It is essential that every student be given equal opportunities.', 'The doctor insisted that the patient remain in bed.', 'I propose that the meeting be postponed.'], commonMistakes: ['Adding -s: "I suggest that she studies" — should be "study"', 'Using "is/are" instead of "be": "It is vital that he is present" — should be "be present"'] },
    ],
  },
]
