// # ═══════════════════════════════════════════════════════════════════════════
// # GRAMMAR PATTERNS — Extended Set 4: Sentence Building & Usage
// # ═══════════════════════════════════════════════════════════════════════════
// # All content is original and copyright-free.
// # Categories: Used to & Habitual Past, Causative Structures,
// # Question Formation, Word Order, Emphasis & Focus, Pronouns & Possessives.

import type { GrammarCategory } from './types'

export const GRAMMAR_CATEGORIES_4: GrammarCategory[] = [

  // # ═══════════════════════════════════════════════════════════════════
  // # 1. USED TO & HABITUAL PAST
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'used-to',
    name: 'Used to & Habitual Past',
    description: 'Three easily confused structures — used to, would, and be/get used to — with completely different meanings.',
    patterns: [
      { id: 'used-to-habit', name: 'Used to + Infinitive (Past Habit/State)', category: 'used-to', level: 'A2', structure: 'Subject + used to + base verb', meaning: 'Describes habits or states that were true in the past but are no longer true now.', context: 'Reminiscing about childhood, comparing past and present, and describing change.', example: 'I used to live in Paris. / She used to smoke, but she quit last year.', explanation: '"Used to" always implies CHANGE — the situation was true before but is NOT true now. It works for both HABITS ("I used to walk to school") and STATES ("I used to be shy"). Negative: "I didn\'t use to like coffee" (note: "use to" without "d" after "didn\'t"). Question: "Did you use to play sports?" "Used to" has no present form — for current habits, use the present simple: "I walk to school" (NOT "I use to walk to school").', moreExamples: ['We used to have a dog when I was growing up.', 'There used to be a cinema here, but they knocked it down.', 'Did you use to enjoy school?'], commonMistakes: ['"I use to live in Paris" (present) — "used to" has NO present form; use "I live in Paris"', '"I didn\'t used to" — after "didn\'t", drop the "d": "I didn\'t use to"', 'Confusing with "be used to": "I used to the cold" should be "I\'m used to the cold" (= accustomed to)'] },
      { id: 'would-past-habit', name: 'Would (Past Repeated Actions)', category: 'used-to', level: 'B1', structure: 'Subject + would + base verb (for past repeated actions only, not states)', meaning: 'Describes repeated actions in the past — interchangeable with "used to" for ACTIONS only.', context: 'Storytelling, nostalgic narratives, and literary writing.', example: 'Every summer, we would drive to the coast and spend a week by the sea.', explanation: '"Would" for past habits works ONLY for repeated ACTIONS, never for states. You can say: "We would play football every Saturday" (= action, fine). But NOT: "I would be shy as a child" (= state, wrong — use "I used to be shy"). "Would" sounds more literary and nostalgic than "used to" — common in memoirs and storytelling. It needs a past context to be established first: "When I was young, we would visit my grandparents every Sunday" (the "when" clause sets the context).', moreExamples: ['She would always bring homemade cake to the office on Fridays.', 'After dinner, my grandfather would sit by the fire and tell us stories.', 'In the old days, people would walk miles to fetch water.'], commonMistakes: ['Using for states: "I would have a dog" (wrong for past possession) — use "I used to have a dog"', 'Using for single events: "I would go to Paris last year" — "would" is for REPEATED actions; use "I went to Paris last year"', 'Using without context: "I would play football" — needs a time reference: "When I was ten, I would play football"'] },
      { id: 'be-get-used-to', name: 'Be Used to / Get Used to + Gerund', category: 'used-to', level: 'B2', structure: 'be used to + noun/gerund (= accustomed) | get used to + noun/gerund (= become accustomed)', meaning: 'Being accustomed to something (be used to) or the process of becoming accustomed (get used to) — NOT about the past.', context: 'Adapting to new situations, cultural adjustment, and changes in routine.', example: 'I\'m used to waking up early — I\'ve done it for years. / She\'s getting used to her new job.', explanation: 'Completely different from "used to + infinitive"! BE USED TO = already accustomed (state): "I\'m used to the noise" (= it doesn\'t bother me anymore). GET USED TO = becoming accustomed (process): "I\'m getting used to the noise" (= it still bothers me a bit, but less than before). Both are followed by a NOUN or GERUND (never infinitive): "used to driving" (NOT "used to drive" — that\'s a different structure entirely). Can be used in any tense: "I wasn\'t used to the heat", "She\'ll get used to it."', moreExamples: ['He\'s not used to working such long hours.', 'It took me months to get used to the cold weather in Scotland.', 'Are you used to living alone yet?'], commonMistakes: ['Infinitive after "be used to": "I\'m used to wake up early" — must be "used to waking up" (gerund)', 'Confusing the three structures: "used to + infinitive" (past habit) ≠ "be used to + gerund" (accustomed) ≠ "get used to + gerund" (becoming accustomed)'] },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 2. CAUSATIVE STRUCTURES
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'causative',
    name: 'Causative Structures',
    description: 'Make, let, have, get — structures for causing, allowing, or arranging actions.',
    patterns: [
      { id: 'make-let-have', name: 'Make / Let / Have + Object + Bare Infinitive', category: 'causative', level: 'B1', structure: 'make/let/have + object + base verb (no "to")', meaning: '"Make" = force/cause. "Let" = allow/permit. "Have" = ask/arrange (less forceful than "make").', context: 'Rules, permissions, instructions, and describing influence.', example: 'The teacher made us rewrite the essay. / My parents let me stay out until midnight.', explanation: 'MAKE = force or cause: "The film made me cry", "Don\'t make me laugh." Passive form uses "to": "We were made to rewrite the essay." LET = allow: "Let me help you", "She let the children play outside." Passive uses "be allowed to": "We were allowed to leave early." HAVE = instruct or arrange (neutral): "I\'ll have my assistant send you the report." All three use the BARE infinitive (no "to"): "made me GO" (NOT "made me to go").', moreExamples: ['He made everyone wait for an hour.', 'The bouncer wouldn\'t let us in without ID.', 'I\'ll have someone fix the printer this afternoon.'], commonMistakes: ['Adding "to": "She made me to do it" — must be "made me do it" (bare infinitive)', 'Passive of "make" without "to": "I was made do it" — passive needs "to": "I was made TO do it"', 'Using "make" when "let" is appropriate: "make" implies force; "let" implies permission'] },
      { id: 'get-to-infinitive', name: 'Get + Object + To-infinitive / Past Participle', category: 'causative', level: 'B2', structure: 'get + object + to-infinitive (persuade) | get + object + past participle (arrange)', meaning: '"Get someone to do" = persuade. "Get something done" = arrange for it to be done.', context: 'Persuasion, professional services, and informal instructions.', example: 'I got my friend to help me move house. / I need to get my watch repaired.', explanation: 'Two patterns: 1) GET + person + TO-INFINITIVE = persuade/convince: "I got him to agree" (= I persuaded him). Unlike "make" (force) or "have" (instruct), "get" implies effort or persuasion. 2) GET + thing + PAST PARTICIPLE = arrange for a service (same as "have something done" but more informal): "I need to get my car fixed" = "I need to have my car fixed." Also describes experiencing something: "She got her purse stolen" (= it happened to her — negative experience).', moreExamples: ['How did you get the boss to approve the budget?', 'You should get your eyes tested — you keep squinting.', 'We got the house repainted before selling it.'], commonMistakes: ['Confusing patterns: "I got him help me" — needs "to": "I got him TO help me"', 'Wrong participle: "I got my car fix" — must be past participle: "got my car fixed"'] },
      { id: 'help-enable', name: 'Help / Enable / Allow / Force / Encourage', category: 'causative', level: 'B1', structure: 'help + object + (to) infinitive | enable/allow/force/encourage + object + to-infinitive', meaning: 'Verbs that describe causing, enabling, or encouraging someone to do something.', context: 'Education, management, parenting, and describing influence.', example: 'She helped me (to) carry the boxes. / The scholarship enabled her to study abroad.', explanation: 'HELP is unique — it can take either bare infinitive OR to-infinitive: "Help me carry this" = "Help me to carry this" (both correct). ENABLE, ALLOW, PERMIT + object + to-infinitive: "The grant allowed us to hire more staff." FORCE, COMPEL, OBLIGE + object + to-infinitive: "They forced him to resign." ENCOURAGE, PERSUADE, CONVINCE + object + to-infinitive: "She encouraged me to apply." PREVENT, STOP + object + FROM + gerund: "The rain prevented us from playing" (different pattern — uses "from + gerund").', moreExamples: ['The new software will enable employees to work more efficiently.', 'Nobody forced you to come — you chose to.', 'His parents encouraged him to pursue his passion for music.'], commonMistakes: ['Using bare infinitive with "allow": "She allowed me go" — must be "allowed me TO go"', '"Prevent me to go" — "prevent" uses "from + gerund": "prevented me from going"'] },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 3. QUESTION FORMATION
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'question-formation',
    name: 'Question Formation',
    description: 'How to form yes/no questions, wh- questions, indirect questions, and question tags.',
    patterns: [
      { id: 'yes-no-questions', name: 'Yes/No Questions', category: 'question-formation', level: 'A1', structure: 'Auxiliary verb + subject + main verb...?', meaning: 'Questions that can be answered with "yes" or "no" — formed by inverting the subject and auxiliary.', context: 'All everyday conversations — the most basic question type.', example: 'Do you speak English? / Is she coming to the party? / Have you finished?', explanation: 'The rule: move the AUXILIARY verb before the subject. If there IS an auxiliary (is/are/was/were/have/has/had/will/would/can/could/etc.): "She IS coming" → "IS she coming?" If there is NO auxiliary, add do/does/did: "You speak English" → "DO you speak English?" "He likes coffee" → "DOES he like coffee?" (note: the -s moves to "does"). With "be" as the main verb: "She is happy" → "Is she happy?" (no "do" needed — "be" acts as its own auxiliary).', moreExamples: ['Can you help me with this?', 'Did they enjoy the concert?', 'Would you like some more tea?'], commonMistakes: ['"You speak English?" — rising intonation alone works in informal speech, but formal questions need inversion: "Do you speak English?"', '"Does she likes?" — the -s is already on "does"; the verb stays base form: "Does she like?"'] },
      { id: 'wh-questions', name: 'Wh- Questions', category: 'question-formation', level: 'A1', structure: 'Wh-word + auxiliary + subject + main verb...?', meaning: 'Questions beginning with who, what, where, when, why, how, which, whose — asking for specific information.', context: 'All contexts — getting specific details.', example: 'Where do you live? / What time does the train leave? / How much does it cost?', explanation: 'Wh-words: WHO (person), WHAT (thing), WHERE (place), WHEN (time), WHY (reason), HOW (manner), WHICH (choice from options), WHOSE (possession). After the wh-word, use the same inversion as yes/no questions: "What DO you want?" "Where IS she?" BUT when "who" or "what" IS the subject, NO inversion needed: "Who called you?" (who = subject) vs "Who did you call?" (who = object). Compare: "What happened?" (what = subject, no "did") vs "What did you do?" (you = subject).', moreExamples: ['Whose jacket is this?', 'How long have you been waiting?', 'Which platform does the London train leave from?'], commonMistakes: ['Adding "do" when the wh-word is subject: "Who did call you?" — just "Who called you?"', '"What means this word?" — must be "What does this word mean?"', 'Wrong word order: "Where she is going?" — must be "Where is she going?"'] },
      { id: 'indirect-questions', name: 'Indirect Questions', category: 'question-formation', level: 'B1', structure: 'Polite opener + wh-word/if/whether + subject + verb (statement word order)', meaning: 'Softer, more polite questions embedded inside a statement — no inversion, no question mark (sometimes).', context: 'Formal situations, professional communication, and polite enquiries.', example: 'Could you tell me where the station is? / I was wondering if you could help me.', explanation: 'Indirect questions use STATEMENT word order (subject before verb) after a polite opener. Common openers: "Could you tell me...", "Do you know...", "I wonder...", "I\'d like to know...", "I was wondering...", "Would you mind telling me..." For yes/no questions, add "if" or "whether": "Is it open?" → "Do you know if it\'s open?" For wh-questions, keep the wh-word: "Where is the bank?" → "Could you tell me where the bank is?" (NOT "where is the bank"). If the opener IS a question, end with "?"; if not, end with ".": "Do you know where she is?" vs "I wonder where she is."', moreExamples: ['I\'d like to know what time the meeting starts.', 'Do you happen to know whether the shop is open on Sundays?', 'I was wondering if you could recommend a good restaurant.'], commonMistakes: ['Keeping question word order: "Could you tell me where is the station?" — must be "where the station is" (statement order)', 'Adding "do/does": "Do you know what does she want?" — must be "what she wants"'] },
      { id: 'question-tags', name: 'Question Tags', category: 'question-formation', level: 'B1', structure: 'Positive statement + , + negative tag? | Negative statement + , + positive tag?', meaning: 'Short questions added to the end of a statement to confirm information or invite agreement.', context: 'Conversation, seeking confirmation, and social interaction.', example: 'You\'re coming tonight, aren\'t you? / She doesn\'t like coffee, does she?', explanation: 'The rule: positive statement → negative tag; negative statement → positive tag. Use the same auxiliary as the statement: "She IS happy, ISN\'T she?" "You HAVE finished, HAVEN\'T you?" "He CAN swim, CAN\'T he?" If no auxiliary, use do/does/did: "You like pizza, DON\'T you?" "He went home, DIDN\'T he?" Special cases: "I am" → "aren\'t I?" (NOT "amn\'t I"); "Let\'s go" → "shall we?"; "Don\'t touch that" → "will you?" Rising intonation = genuine question (unsure). Falling intonation = expecting agreement.', moreExamples: ['It\'s a lovely day, isn\'t it?', 'They haven\'t left yet, have they?', 'You won\'t forget, will you?'], commonMistakes: ['"You are coming, are you?" — must be OPPOSITE: "aren\'t you?"', '"She like pizza, doesn\'t she?" — the statement needs correct grammar too: "She likes pizza, doesn\'t she?"', '"I am right, amn\'t I?" — use "aren\'t I?" (the only accepted form)'] },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 4. WORD ORDER & SENTENCE STRUCTURE
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'word-order',
    name: 'Word Order & Sentence Structure',
    description: 'How to arrange words correctly — SVO order, adjective order, adverb placement, and there is/are.',
    patterns: [
      { id: 'basic-svo', name: 'Basic Word Order (SVO) & Variations', category: 'word-order', level: 'A1', structure: 'Subject + Verb + Object (+ Manner + Place + Time)', meaning: 'English follows a strict Subject-Verb-Object order, with manner, place, and time adverbs at the end.', context: 'All communication — this is the foundation of every English sentence.', example: 'She (S) reads (V) books (O) quietly (manner) at home (place) every evening (time).', explanation: 'English is an SVO language — the word order carries meaning (unlike languages with case endings). "The dog bit the man" ≠ "The man bit the dog." When multiple adverbials appear at the end, the typical order is MANNER → PLACE → TIME (MPT): "She sang beautifully (M) at the concert (P) last night (T)." Short time expressions can move to the front for emphasis: "Yesterday, I saw something strange." The subject MUST come before the verb in statements (exceptions: inversion after negative adverbials, questions).', moreExamples: ['I met my friend at the café this morning.', 'They played football in the park yesterday.', 'Last week, we visited a museum in the city centre.'], commonMistakes: ['Wrong order: "I yesterday went to the shop" — adverbs of time usually go at the end: "I went to the shop yesterday"', 'Missing subject: "Is raining" — English requires a subject: "It is raining"'] },
      { id: 'adjective-order', name: 'Order of Adjectives', category: 'word-order', level: 'B1', structure: 'Opinion → Size → Age → Shape → Colour → Origin → Material → Purpose + noun', meaning: 'When multiple adjectives describe the same noun, they follow a specific order that native speakers instinctively know.', context: 'Descriptive writing, product descriptions, and everyday descriptions.', example: 'A beautiful large old rectangular brown Italian wooden dining table.', explanation: 'The order (remembered as OSASCOMP): 1) OPINION: beautiful, lovely, ugly, nice; 2) SIZE: big, small, tall, tiny; 3) AGE: old, new, young, ancient; 4) SHAPE: round, square, flat; 5) COLOUR: red, blue, dark; 6) ORIGIN: French, Japanese, northern; 7) MATERIAL: wooden, metal, silk; 8) PURPOSE: cooking, sleeping, writing. You rarely need all categories at once! Usually 2-3 adjectives: "a nice old house" (opinion + age), "a small red car" (size + colour). The rule feels unbreakable to native speakers: "a red big car" sounds deeply wrong.', moreExamples: ['She wore a stunning long black evening dress.', 'They live in a charming little old stone cottage.', 'He drives a powerful new German sports car.'], commonMistakes: ['Reversing opinion and fact: "a wooden beautiful table" — opinion comes first: "a beautiful wooden table"', 'Too many adjectives in speech — in conversation, 2-3 is the natural maximum'] },
      { id: 'adverb-frequency', name: 'Position of Adverbs of Frequency', category: 'word-order', level: 'A2', structure: 'Subject + adverb + main verb | Subject + be + adverb', meaning: 'Adverbs like always, usually, often, sometimes, never go in a specific position — between subject and verb, or after "be".', context: 'Describing habits, routines, and how often things happen.', example: 'I usually wake up at 7. / She is always late. / He has never been to Japan.', explanation: 'The rule: adverbs of frequency go BEFORE the main verb but AFTER "be" and after the first auxiliary. BEFORE main verb: "I always drink coffee" (NOT "I drink always coffee"). AFTER "be": "She is often tired" (NOT "She often is tired"). AFTER first auxiliary: "I have never been there", "She can usually help." Frequency scale: always (100%) → usually (~80%) → often (~60%) → sometimes (~40%) → rarely/seldom (~10%) → never (0%). "Sometimes" and "usually" can also go at the start or end: "Sometimes I walk to work" / "I walk to work sometimes."', moreExamples: ['We often eat out on Fridays.', 'The bus is rarely on time.', 'I have always wanted to visit Japan.'], commonMistakes: ['After the verb: "I go often to the gym" — must be "I often go to the gym"', 'Before "be": "She always is happy" — must be "She is always happy"', '"I never don\'t eat meat" — double negative; just "I never eat meat"'] },
      { id: 'there-is-are', name: 'There Is / There Are (Existential)', category: 'word-order', level: 'A1', structure: 'There + is/are/was/were/will be + noun (+ place/time)', meaning: 'Introduces the existence of something — says that something exists or is present.', context: 'Describing locations, situations, and stating what exists.', example: 'There is a bank on the corner. / There are 30 students in the class.', explanation: '"There" in this structure is a DUMMY SUBJECT — it doesn\'t mean "that place." It simply introduces existence. Use "is" for singular/uncountable: "There is a problem", "There is some water." Use "are" for plural: "There are many options." Works in all tenses: "There was a time when...", "There have been several complaints", "There will be a meeting tomorrow." In informal speech, "there\'s" is used even with plurals: "There\'s two people outside" (grammatically wrong but extremely common).', moreExamples: ['There are no tickets left for the concert.', 'There has been an accident on the motorway.', 'Is there anything I can help you with?'], commonMistakes: ['"It has a bank on the corner" — use "There is" for existence, not "It has"', '"There is many people" — plural needs "are": "There are many people"', 'Confusing with "they are": "There are happy" should be "They are happy" (different meaning entirely)'] },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 5. EMPHASIS & FOCUS
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'emphasis',
    name: 'Emphasis & Focus',
    description: 'Do/Did for emphasis, so/such for intensifying, too/enough for degree, and exclamatory structures.',
    patterns: [
      { id: 'do-emphasis', name: 'Do / Did for Emphasis', category: 'emphasis', level: 'B1', structure: 'Subject + DO/DOES/DID + base verb', meaning: 'Adds "do/does/did" to a positive sentence to strongly emphasise or insist that something is true.', context: 'Contradicting, insisting, expressing surprise, and persuading.', example: 'I DO understand your point — I just disagree. / She DID lock the door, I saw her.', explanation: 'Normally "do/does/did" only appear in negatives and questions. In positive sentences, they add strong emphasis. Uses: 1) Contradicting: "You don\'t care!" → "I DO care!"; 2) Insisting: "She did finish the report — check your email"; 3) Polite emphasis: "Do sit down" (= please sit down); 4) Surprise: "She DOES speak good English!" (= I\'m impressed). The stressed auxiliary carries the emphasis in speech — in writing, it\'s often capitalised or italicised.', moreExamples: ['I do apologise for the delay — it won\'t happen again.', 'Do come in — make yourself at home.', 'He does work hard, I\'ll give him that.'], commonMistakes: ['Adding -s to the verb after "does": "She does likes it" — the verb stays base form: "She DOES like it"', 'Using in negatives (redundant): "I don\'t DO understand" — "do" for emphasis only works in positive sentences'] },
      { id: 'so-such', name: 'So / Such (Intensifiers)', category: 'emphasis', level: 'B1', structure: 'so + adjective/adverb (+ that...) | such + (a/an) + (adjective) + noun (+ that...)', meaning: '"So" intensifies adjectives and adverbs. "Such" intensifies nouns (with or without adjectives).', context: 'Expressing strong feelings, reactions, and consequences.', example: 'The film was so boring that I fell asleep. / It was such a beautiful day that we went to the beach.', explanation: 'SO + adjective/adverb: "so tired", "so quickly", "so much", "so many." SUCH + (a/an) + noun phrase: "such a good idea", "such beautiful weather", "such nice people." Both can be followed by "that" for consequences: "It was so cold that the pipes froze" = "It was such cold weather that the pipes froze." Key difference: SO modifies adjectives/adverbs directly; SUCH modifies nouns. "So much/many" for quantity: "There were so many people!"', moreExamples: ['She\'s such a talented musician!', 'I\'ve never seen so many stars in the sky.', 'He spoke so quietly that nobody could hear him.'], commonMistakes: ['"It was so a good film" — with a noun, use "such": "It was such a good film"', '"Such beautiful" (without a noun) — use "so": "So beautiful" (adjective alone = "so")'] },
      { id: 'too-enough', name: 'Too / Enough', category: 'emphasis', level: 'A2', structure: 'too + adjective/adverb (+ to-infinitive) | adjective/adverb + enough (+ to-infinitive)', meaning: '"Too" = more than is good or necessary (negative). "Enough" = sufficient (positive or neutral).', context: 'Expressing excess, sufficiency, and suitability.', example: 'The coffee is too hot to drink. / She\'s old enough to drive.', explanation: 'TOO goes BEFORE the adjective: "too expensive", "too difficult", "too fast." It always implies a problem — something is excessive. ENOUGH goes AFTER the adjective: "big enough", "good enough", "fast enough." It means sufficient — no problem. Both can be followed by "to-infinitive": "too tired to cook" (= so tired that I can\'t), "strong enough to lift it" (= sufficiently strong). With nouns, "enough" goes BEFORE: "enough money", "enough time." "Too much/many" for quantity: "too much noise", "too many mistakes."', moreExamples: ['This suitcase is too heavy to carry.', 'Is the water warm enough to swim in?', 'We don\'t have enough chairs for everyone.'], commonMistakes: ['Wrong position: "enough big" — must be "big enough" (after the adjective)', '"Too" meaning "very": "The food was too delicious" — "too" implies a problem; use "very" or "really" for praise', '"It\'s too much expensive" — just "too expensive" (no "much" with adjectives)'] },
      { id: 'exclamatory', name: 'Exclamatory Sentences (What / How)', category: 'emphasis', level: 'B1', structure: 'What + (a/an) + (adjective) + noun! | How + adjective/adverb + subject + verb!', meaning: 'Express strong feelings — surprise, admiration, shock, or delight — using "what" or "how".', context: 'Reactions, compliments, expressions of surprise, and emotional responses.', example: 'What a beautiful sunset! / How kind of you!', explanation: 'WHAT + noun phrase: "What a lovely day!", "What beautiful weather!" (no "a" with uncountable/plural), "What nonsense!" HOW + adjective/adverb: "How interesting!", "How well she sings!" In formal/literary style, "how" can be followed by subject + verb: "How quickly time flies!" In everyday speech, the short form is more common: "What a mess!", "How strange!" These are NOT questions — they end with exclamation marks, not question marks, and use statement word order.', moreExamples: ['What an incredible performance!', 'How time flies when you\'re having fun!', 'What a coincidence — I was just thinking about you!'], commonMistakes: ['Confusing "what" and "how": "How a beautiful day!" — with nouns, use "What": "What a beautiful day!"', 'Using question word order: "How is she beautiful!" — use statement order: "How beautiful she is!"'] },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 6. PRONOUNS & POSSESSIVES
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'pronouns',
    name: 'Pronouns & Possessives',
    description: 'Subject, object, possessive, reflexive, and reciprocal pronouns — and when to use each.',
    patterns: [
      { id: 'personal-pronouns', name: 'Subject vs Object Pronouns', category: 'pronouns', level: 'A1', structure: 'Subject (I/you/he/she/it/we/they) + verb + object (me/you/him/her/it/us/them)', meaning: 'Subject pronouns do the action. Object pronouns receive the action. Using the wrong one is a basic error.', context: 'All communication — one of the first grammar points learners study.', example: 'I love her. / She told them the news. / He gave it to us.', explanation: 'SUBJECT pronouns (before the verb): I, you, he, she, it, we, they. OBJECT pronouns (after the verb or preposition): me, you, him, her, it, us, them. After prepositions always use object form: "for me" (NOT "for I"), "between you and me" (NOT "between you and I" — this is one of the most common mistakes even native speakers make). After "be" in formal English: "It is I" (formal) / "It\'s me" (normal). "It" and "you" are the same in both forms.', moreExamples: ['She invited him and me to the party.', 'Could you help us with this project?', 'This is between you and me — don\'t tell anyone.'], commonMistakes: ['"Between you and I" — must be "between you and me" (after a preposition, use object form)', '"Me and John went to the shop" — in formal English: "John and I went" (subject form)', '"Her and me went shopping" — "She and I went shopping" (subject pronouns as subject)'] },
      { id: 'possessives', name: 'Possessive Adjectives, Pronouns & \'s', category: 'pronouns', level: 'A1', structure: 'Possessive adjective + noun (my book) | Possessive pronoun alone (mine) | Noun + \'s (John\'s book)', meaning: 'Three ways to show ownership — adjectives go before nouns, pronouns stand alone, and \'s attaches to the owner.', context: 'Talking about ownership, relationships, and belonging.', example: 'That\'s my car. / That car is mine. / That\'s John\'s car.', explanation: 'POSSESSIVE ADJECTIVES (before noun): my, your, his, her, its, our, their. POSSESSIVE PRONOUNS (standalone): mine, yours, his, hers, (no "its"), ours, theirs. "Whose is this?" → "It\'s mine." APOSTROPHE + S: singular nouns add \'s: "the dog\'s bone", "James\'s car" (or "James\' car"). Plural nouns ending in s just add \': "the students\' books." Irregular plurals add \'s: "the children\'s toys." For things, "of" is often preferred: "the door of the car" (or "the car door" — compound noun).', moreExamples: ['Is this your pen or hers?', 'Our house is bigger than theirs.', 'My sister\'s husband works in finance.'], commonMistakes: ['"It\'s" vs "its": "The dog wagged it\'s tail" — WRONG. "It\'s" = "it is." "Its" (no apostrophe) = possession: "its tail"', '"Your" vs "you\'re": "Your welcome" — WRONG. "You\'re" = "you are." "Your" = possession', '"Theirs" never has an apostrophe: "their\'s" does not exist'] },
      { id: 'reflexive-pronouns', name: 'Reflexive Pronouns', category: 'pronouns', level: 'B1', structure: 'Subject + verb + myself/yourself/himself/herself/itself/ourselves/yourselves/themselves', meaning: 'Used when the subject and object are the same person — the action reflects back on the doer.', context: 'Actions done to oneself, emphasis, and indicating solo effort.', example: 'She cut herself while cooking. / I taught myself to play guitar.', explanation: 'REFLEXIVE use (subject = object): "He hurt himself" (= he was both the hurter and the hurt). EMPHATIC use (= alone, without help): "I\'ll do it myself" (= without anyone\'s help), "She painted the house herself." "By myself/yourself" = alone: "I live by myself." Common reflexive verbs: enjoy yourself, help yourself, behave yourself, introduce yourself, blame yourself, express yourself. Some verbs are reflexive in other languages but NOT in English: "I feel well" (NOT "I feel myself well").', moreExamples: ['Make yourself at home.', 'The children can dress themselves.', 'The door opened by itself. (= nobody opened it)'], commonMistakes: ['Adding reflexive when not needed: "I feel myself tired" — just "I feel tired" (feel is not reflexive in English)', '"Theirselves" — does not exist; the correct form is "themselves"', 'Using object pronoun instead: "She hurt her" means she hurt another woman; "herself" means she hurt the same person (herself)'] },
      { id: 'reciprocal-pronouns', name: 'Each Other / One Another (Reciprocal)', category: 'pronouns', level: 'B1', structure: 'Subject (plural) + verb + each other / one another', meaning: 'Describes an action done mutually — A does something to B, and B does the same to A.', context: 'Relationships, teamwork, and mutual actions.', example: 'They love each other. / We help one another during exams.', explanation: '"Each other" and "one another" are interchangeable in modern English (traditionally, "each other" = two people, "one another" = more than two, but this distinction is largely ignored today). Compare REFLEXIVE vs RECIPROCAL: "They introduced themselves" (= each person said their own name) vs "They introduced each other" (= A introduced B, and B introduced A). Possessive form: "each other\'s": "They read each other\'s essays." Cannot be a subject — only an object: "Each other helped" is wrong; "They helped each other" is correct.', moreExamples: ['The two teams respect each other.', 'My neighbours and I look after one another\'s houses when we\'re away.', 'We email each other every week.'], commonMistakes: ['Confusing with reflexive: "They hurt themselves" (each person hurt their own self) vs "They hurt each other" (person A hurt person B and vice versa)', 'Using as subject: "Each other are helping" — must be object: "They are helping each other"'] },
    ],
  },
]
