// # ═══════════════════════════════════════════════════════════════════════════
// # GRAMMAR PATTERNS — Extended Set 5: Advanced Clause Structures
// # ═══════════════════════════════════════════════════════════════════════════
// # All content is original and copyright-free.
// # Categories: Noun Clauses, Adverbial Clauses, Subject-Verb Agreement,
// # Discourse Markers & Cohesion.

import type { GrammarCategory } from './types'

export const GRAMMAR_CATEGORIES_5: GrammarCategory[] = [

  // # ═══════════════════════════════════════════════════════════════════
  // # 1. NOUN CLAUSES
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'noun-clauses',
    name: 'Noun Clauses',
    description: 'Clauses that function as nouns — as subjects, objects, or complements of sentences.',
    patterns: [
      { id: 'that-clause', name: 'That-clauses', category: 'noun-clauses', level: 'B1', structure: 'Subject + verb + (that) + subject + verb | (That) + subject + verb + main verb', meaning: 'A clause beginning with "that" which acts as the object (or sometimes subject) of a sentence.', context: 'Expressing beliefs, opinions, reports, and emotions.', example: 'I think (that) she\'s right. / It\'s clear that we need more time.', explanation: 'AS OBJECT (most common): follows verbs of thinking, saying, feeling, knowing: "I believe (that) he\'s honest", "She said (that) she was tired", "I hope (that) you\'re well." "That" is often DROPPED in informal English: "I think she\'s right" = "I think that she\'s right." AS SUBJECT: usually begins with "It is...that": "It is important that everyone attends" (less natural: "That everyone attends is important"). After adjectives of emotion: "I\'m glad (that) you came", "She was surprised (that) he agreed."', moreExamples: ['The problem is that we don\'t have enough staff.', 'It\'s obvious that something has gone wrong.', 'I\'m sorry that I missed your call.'], commonMistakes: ['Using "what" instead of "that": "I think what she\'s right" — should be "I think (that) she\'s right"', 'Forgetting to shift tense in reported speech: "She said that she is tired" — in formal English: "She said that she was tired"'] },
      { id: 'wh-noun-clause', name: 'Wh-clauses (Embedded Questions)', category: 'noun-clauses', level: 'B2', structure: 'Main verb + wh-word + subject + verb (statement order)', meaning: 'A question word (what, who, where, when, why, how) introduces a clause that acts as a noun — using statement word order, NOT question order.', context: 'Reporting questions, expressing uncertainty, and discussing what is known or unknown.', example: 'I don\'t know where she lives. / What he said surprised everyone.', explanation: 'These are NOT questions — they are STATEMENTS containing a question word. AS OBJECT: "I wonder why he left", "She asked how much it cost", "I can\'t remember what his name is." AS SUBJECT: "What you said was very kind", "Where we go depends on the weather", "How she did it remains a mystery." CRITICAL: use STATEMENT word order (subject + verb): "I know where he IS" (NOT "where is he"). The word order changes only when the clause IS the direct question: "Where is he?" (question) vs "I don\'t know where he is" (noun clause).', moreExamples: ['Nobody knows who wrote that letter.', 'How the pyramids were built is still debated.', 'Tell me what you think.'], commonMistakes: ['Using question order: "I don\'t know where is she" — must be "where she is" (statement order)', 'Adding "do/does/did": "I wonder what does she want" — must be "what she wants"'] },
      { id: 'whether-if-clause', name: 'Whether / If Clauses', category: 'noun-clauses', level: 'B1', structure: 'Main verb + whether/if + subject + verb (+ or not)', meaning: 'Introduces a yes/no question as a noun clause — "whether" is more formal; "if" is more informal.', context: 'Expressing doubt, reporting yes/no questions, and discussing alternatives.', example: 'I don\'t know if she\'s coming. / Whether he\'ll agree is uncertain.', explanation: '"Whether" and "if" are interchangeable after most verbs: "I wonder whether/if he\'ll call." BUT only "whether" works: 1) As subject: "Whether he agrees is irrelevant" (NOT "if he agrees is irrelevant"); 2) After prepositions: "It depends on whether we get funding" (NOT "on if"); 3) With "or not" directly after: "whether or not he comes" (NOT "if or not"). "If or not" at the END of the clause is acceptable: "I don\'t know if he\'s coming or not." In formal writing, prefer "whether" — it\'s always correct.', moreExamples: ['I\'m not sure whether this is the right address.', 'Whether or not it rains, the event will go ahead.', 'The question is whether we can afford it.'], commonMistakes: ['"If" as subject: "If he agrees is irrelevant" — must be "Whether he agrees is irrelevant"', '"If or not" directly: "I wonder if or not" — say "whether or not" or "if... or not" at the end'] },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 2. ADVERBIAL CLAUSES
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'adverbial-clauses',
    name: 'Adverbial Clauses',
    description: 'Clauses that function as adverbs — showing time, reason, purpose, result, and concession.',
    patterns: [
      { id: 'time-clauses', name: 'Time Clauses', category: 'adverbial-clauses', level: 'B1', structure: 'When/While/Before/After/Until/As soon as/By the time + subject + present verb (for future meaning)', meaning: 'Describe when an action happens — critically, they use present tense for future events.', context: 'Planning, storytelling, giving instructions, and describing sequences.', example: 'I\'ll call you when I arrive. / She always reads before she goes to sleep.', explanation: 'Key connectors: WHEN (at the time), WHILE (during), BEFORE (earlier), AFTER (later), UNTIL/TILL (up to the point when), AS SOON AS (immediately after), BY THE TIME (before the time). CRITICAL RULE: in time clauses about the FUTURE, use present simple (NOT "will"): "I\'ll leave when she ARRIVES" (NOT "when she will arrive"). "By the time" + present simple → main clause uses future perfect: "By the time you get here, I\'ll have finished." With past tense for completed sequences: "After he had eaten, he went to bed."', moreExamples: ['As soon as I hear from them, I\'ll let you know.', 'Don\'t open the door until I tell you to.', 'By the time we arrived, the show had already started.'], commonMistakes: ['"I\'ll call you when I will arrive" — NO "will" in time clauses: "when I arrive"', 'Confusing "when" (a specific point) and "while" (during): "While I arrived" should be "When I arrived"'] },
      { id: 'reason-clauses', name: 'Reason / Cause Clauses', category: 'adverbial-clauses', level: 'B1', structure: 'because/since/as + clause | due to/owing to + noun/gerund', meaning: 'Explain WHY something happens — ranging from informal to formal register.', context: 'Justifications, explanations, academic writing, and persuasive communication.', example: 'I stayed home because I was feeling ill. / Since you\'re here, can you help me?', explanation: 'BECAUSE = strongest and most common: "I left because I was bored." Always clear about cause-effect. SINCE/AS = lighter reason, often when the reason is already known: "Since you already know, I won\'t explain again" (implies shared knowledge). Note: "since" and "as" also have other meanings (time and comparison), so "because" is safest when clarity matters. FORMAL alternatives: "due to" + noun: "The match was cancelled due to rain"; "owing to" + noun: "Owing to budget cuts, recruitment has been frozen." "As a result of" = formal consequence.', moreExamples: ['As it was getting late, we decided to leave.', 'She succeeded because she never gave up.', 'Due to unforeseen circumstances, the event has been postponed.'], commonMistakes: ['"The reason is because" — redundant. Use "The reason is that..." or just "because"', '"Due to" with a verb: "Due to it rained" — needs a noun: "Due to the rain"'] },
      { id: 'purpose-clauses', name: 'Purpose Clauses', category: 'adverbial-clauses', level: 'B2', structure: 'to / in order to / so as to + infinitive | so that + subject + can/will/could/would + verb', meaning: 'Explain the PURPOSE or goal of an action — why someone does something.', context: 'Explaining intentions, justifying actions, and describing goals.', example: 'She whispered so as not to wake the baby. / I\'m saving money so that I can buy a car.', explanation: 'INFORMAL: "to" + infinitive: "I went to the shop to buy milk." FORMAL: "in order to" + infinitive: "In order to qualify, you must pass all exams." NEGATIVE purpose: "so as not to" / "in order not to" (NOT "for not to"): "She spoke quietly so as not to disturb anyone." WITH A CLAUSE (different subject): "so that" + can/will/could/would: "I\'ll text you so that you know I\'ve arrived." Past: "so that" + could/would: "He left early so that he could catch the train." "For" + gerund describes what something is used FOR: "a bag for carrying books."', moreExamples: ['I took a taxi in order not to be late.', 'She studied hard so that she could get a scholarship.', 'They moved to the countryside to have a quieter life.'], commonMistakes: ['"For to buy" — wrong in modern English; just "to buy" or "in order to buy"', '"So that" without modal: "I\'m studying so that I pass" — usually needs "can/will": "so that I can pass"'] },
      { id: 'result-clauses', name: 'Result / Consequence Clauses', category: 'adverbial-clauses', level: 'B2', structure: 'so + adjective/adverb + that | such + (a/an) + noun + that | therefore/consequently', meaning: 'Show the RESULT or consequence of something — what happened because of a cause.', context: 'Describing cause-and-effect, narrating outcomes, and academic analysis.', example: 'It was so cold that the river froze. / She spoke such fluent French that everyone assumed she was Parisian.', explanation: 'SO...THAT + adjective/adverb: "He ran so fast that he won easily." SUCH...THAT + noun phrase: "It was such a boring lecture that half the audience left." (Use "such" with nouns, "so" with adjectives/adverbs.) SO MUCH/MANY...THAT: "There were so many people that we couldn\'t get in." Sentence-level connectors (between sentences): "therefore", "consequently", "as a result", "hence": "The factory closed. Consequently, 200 people lost their jobs." (These are adverbs, not conjunctions — use a full stop or semicolon, not a comma.)', moreExamples: ['She\'s such a good cook that she could open a restaurant.', 'I was so tired that I fell asleep on the bus.', 'The evidence was overwhelming. As a result, he was found guilty.'], commonMistakes: ['Mixing up so/such: "It was so a good day" — with a noun, use "such": "such a good day"', 'Comma splice with "therefore": "It rained, therefore we stayed in" — use a full stop or semicolon: "It rained. Therefore, we stayed in."'] },
      { id: 'concession-clauses', name: 'Concession Clauses', category: 'adverbial-clauses', level: 'B2', structure: 'although/though/even though + clause | despite/in spite of + noun/gerund | however/nevertheless', meaning: 'Express contrast — something is true DESPITE an opposing fact. Shows unexpected results.', context: 'Balanced arguments, academic essays, and describing surprising situations.', example: 'Although it was raining, we enjoyed the walk. / Despite his age, he\'s incredibly fit.', explanation: 'CONJUNCTIONS (join clauses): although, though, even though (strongest). "Although" = formal, "though" = informal, "even though" = emphatic. "Even though she was tired, she kept working." PREPOSITIONS (+ noun/gerund): despite, in spite of. "Despite the rain, we went out" = "In spite of the rain, we went out." NEVER say "despite of" — just "despite." ADVERBS (between sentences): however, nevertheless, nonetheless. "It was raining. However, we still went out." These three levels of formality give you flexibility: conversation → "though", essays → "although"/"despite", formal reports → "nevertheless."', moreExamples: ['Even though he studied all night, he still failed the exam.', 'In spite of being exhausted, she finished the marathon.', 'The hotel was expensive. Nevertheless, the service was outstanding.'], commonMistakes: ['"Despite of" — WRONG. Just "despite" (no "of"), or "in spite OF"', '"Although" + "but" together: "Although it rained, but we went out" — choose one: "Although it rained, we went out" OR "It rained, but we went out"', 'Comma splice with "however": "It rained, however we went" — use full stop or semicolon'] },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 3. SUBJECT-VERB AGREEMENT
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'subject-verb-agreement',
    name: 'Subject-Verb Agreement',
    description: 'Making sure the verb matches the subject — singular subjects need singular verbs, and vice versa.',
    patterns: [
      { id: 'basic-agreement', name: 'Basic Agreement Rules', category: 'subject-verb-agreement', level: 'A1', structure: 'Singular subject + singular verb (he goes) | Plural subject + plural verb (they go)', meaning: 'The verb must agree with the subject in number — this is the foundation of correct English sentences.', context: 'All written and spoken English — errors here undermine credibility.', example: 'She walks to school. (singular) / They walk to school. (plural)', explanation: 'In present simple, only third person singular (he/she/it) adds -s to the verb: "I walk", "You walk", "He walkS", "We walk", "They walk." "Be" has three forms: "I am", "he/she/it is", "you/we/they are." The subject determines the verb, NOT any noun between them: "The box OF CHOCOLATES is on the table" (subject = box, singular). "One OF THE students IS absent" (subject = one, singular). Sentences starting with "there": "There IS a problem" (singular) / "There ARE problems" (plural).', moreExamples: ['The price of these items has increased.', 'Each of the students has a textbook.', 'The news is shocking. (news = singular)'], commonMistakes: ['"The results of the experiment shows" — subject is "results" (plural): "show"', '"One of the students are absent" — subject is "one" (singular): "is absent"', '"There is many people" — "people" is plural: "There are many people"'] },
      { id: 'collective-nouns', name: 'Collective Nouns', category: 'subject-verb-agreement', level: 'B1', structure: 'Collective noun + singular verb (as a unit) | Collective noun + plural verb (as individuals — BrE)', meaning: 'Nouns like team, family, government, staff, audience — can they be singular or plural?', context: 'News, sports, business, and formal writing.', example: 'The team is playing well. (AmE / as one unit) / The team are arguing among themselves. (BrE / as individuals)', explanation: 'AMERICAN ENGLISH: collective nouns are almost always SINGULAR: "The government is", "The team is", "The family is." BRITISH ENGLISH: depends on meaning — SINGULAR when acting as one unit: "The committee has decided"; PLURAL when acting as individuals: "The committee have disagreed among themselves." Words that are ALWAYS plural (even without -s): people, police, cattle. Words that look plural but are SINGULAR: news, mathematics, physics, economics, politics (as a subject). "Staff" is usually plural in BrE: "The staff are on holiday."', moreExamples: ['The audience was impressed by the performance. (one reaction)', 'The audience were leaving at different times. (individual actions)', 'The police are investigating the case. (always plural)'], commonMistakes: ['"The police is" — always plural: "The police are"', '"Mathematics are difficult" — singular: "Mathematics is difficult"', 'In formal writing, be consistent: don\'t switch between singular and plural for the same collective noun in one paragraph'] },
      { id: 'complex-subjects', name: 'Complex & Compound Subjects', category: 'subject-verb-agreement', level: 'B2', structure: 'Subject + and + subject (plural) | Either/Neither + subject + or/nor + subject (nearest)', meaning: 'When subjects are joined by "and", "or", "nor", "either...or", "neither...nor" — which form of the verb?', context: 'Writing complex sentences accurately in formal and academic contexts.', example: 'Tom and Jerry are friends. / Neither the students nor the teacher was prepared.', explanation: 'AND = plural: "Bread and butter ARE on the table." (But: "Bread and butter IS my favourite breakfast" — treated as ONE thing.) OR/NOR = verb agrees with the NEAREST subject: "Either he or his parents ARE coming." "Neither the students nor the teacher WAS aware." (Teacher = nearest, singular.) EACH/EVERY before compound subjects = singular: "Every student and teacher HAS a badge." Subjects with "as well as", "along with", "together with" = verb agrees with the FIRST subject only: "The president, along with his advisors, IS attending" (subject = president, singular).', moreExamples: ['Fish and chips is my favourite dish. (one dish, singular)', 'Neither the manager nor the employees were satisfied.', 'The teacher, as well as the students, was surprised by the news.'], commonMistakes: ['"Neither A nor B are" when B is singular — verb matches NEAREST subject: "Neither A nor B is"', '"The boss along with his team are coming" — verb matches "boss": "is coming"', 'Treating "each" as plural: "Each boy and girl have" — must be "has"'] },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 4. DISCOURSE MARKERS & COHESION
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'discourse-markers',
    name: 'Discourse Markers & Cohesion',
    description: 'Words and phrases that organise speech and writing — signposting, hedging, summarising, and transitioning.',
    patterns: [
      { id: 'spoken-markers', name: 'Spoken Discourse Markers', category: 'discourse-markers', level: 'B1', structure: 'well / you know / I mean / actually / basically / right / so / anyway', meaning: 'Small words that organise spoken language — they signal turns, shifts, corrections, and hesitation.', context: 'Natural conversation, presentations, and spoken English exams (IELTS, PTE, OET).', example: 'Well, I think it depends on the situation. / So, what happened next?', explanation: 'These make speech sound natural and fluent: WELL = pause before answering, especially a difficult question: "Well, it\'s complicated." ACTUALLY = correction or unexpected information: "Actually, I\'m not from London — I\'m from Manchester." I MEAN = self-correction: "She\'s 30... I mean, 31." BASICALLY = simplifying: "Basically, we need more money." SO = introducing result or new topic: "So, shall we go?" ANYWAY = returning to the main point: "Anyway, as I was saying..." RIGHT/OK = checking understanding or signalling a transition.', moreExamples: ['You know, I\'ve been thinking about changing jobs.', 'Anyway, let\'s get back to the main topic.', 'Right, let\'s start the meeting.'], commonMistakes: ['Overusing "like" and "you know" — one or two per sentence sounds natural; every other word sounds uneducated', 'Using spoken markers in formal writing: "Basically, the experiment showed..." — too informal for essays'] },
      { id: 'hedging-language', name: 'Hedging & Cautious Language', category: 'discourse-markers', level: 'B2', structure: 'It seems/appears that | tend to | may/might/could | to some extent | arguably', meaning: 'Language that softens claims and avoids absolute statements — essential in academic and professional English.', context: 'Academic writing, research, professional communication, and diplomatic speech.', example: 'The data suggests that there may be a correlation. / It could be argued that this approach is more effective.', explanation: 'Hedging makes claims more defensible and less aggressive. VERBS: seem, appear, suggest, indicate, tend to: "The evidence suggests a link" (not "proves"). MODALS: may, might, could, would: "This could explain the decline." ADVERBS: perhaps, possibly, probably, arguably, apparently, relatively, somewhat: "The results are somewhat surprising." PHRASES: to some extent, in some cases, it is possible that, it could be argued that, one might suggest that. Academic writing REQUIRES hedging: "Pollution causes cancer" → "Pollution may contribute to an increased risk of certain cancers."', moreExamples: ['It appears that the policy has had limited success.', 'This approach tends to produce better outcomes in most cases.', 'It could be argued that social media does more harm than good.'], commonMistakes: ['Too much hedging: "It might possibly perhaps be somewhat true" — sounds weak; pick ONE hedging device per claim', 'No hedging at all: "This proves that X causes Y" — academic writing rarely says "proves"; use "suggests" or "indicates"'] },
      { id: 'signposting-writing', name: 'Signposting in Academic Writing', category: 'discourse-markers', level: 'B2', structure: 'Firstly | In addition | On the other hand | In conclusion | As mentioned above', meaning: 'Phrases that guide the reader through your argument — like road signs telling them what\'s coming next.', context: 'IELTS Writing, university essays, business reports, and formal documents.', example: 'Firstly, I will examine the causes. Secondly, I will discuss the effects. Finally, I will propose solutions.', explanation: 'INTRODUCTION: This essay will examine..., The purpose of this report is to..., In this essay, I will argue that... ADDING POINTS: Furthermore, Moreover, In addition, What is more. CONTRASTING: However, On the other hand, In contrast, Conversely, Nevertheless. GIVING EXAMPLES: For instance, For example, Such as, In particular, Namely. CAUSE/EFFECT: Therefore, Consequently, As a result, Hence. CONCLUDING: In conclusion, To sum up, Overall, In summary, On balance. Use these to create clear, logical flow — but don\'t overuse them. One or two per paragraph is usually enough.', moreExamples: ['Furthermore, the study found a significant difference between the two groups.', 'On the other hand, some researchers argue that the link is merely coincidental.', 'In conclusion, the evidence strongly supports the hypothesis.'], commonMistakes: ['Starting every sentence with a connector: "Moreover... Furthermore... In addition..." — this reads like a list, not an essay', '"On the other hand" without "on one hand" — this is actually fine; you don\'t need both', 'Using informal markers in essays: "Plus..." or "Also..." at the start — use "Furthermore" or "In addition"'] },
      { id: 'referencing-cohesion', name: 'Reference & Cohesion (this, that, such, the former)', category: 'discourse-markers', level: 'C1', structure: 'this/that/these/those + noun | such + noun | the former/the latter | the above/the following', meaning: 'Words and phrases that link back to something already mentioned — creating smooth, connected text.', context: 'Academic essays, reports, and any sustained writing that needs to flow logically.', example: 'The company launched a new product. This move surprised analysts. / Two solutions were proposed: the former was accepted.', explanation: 'DEMONSTRATIVE reference: "this/that/these/those" + noun referring back: "Several factors contributed to the crisis. These factors include..." Using "this" alone ("This is important") is vague — add a noun: "This finding is important." SUCH reference: "such" + noun: "Low interest rates encourage borrowing. Such conditions also fuel inflation." THE FORMER / THE LATTER: refers to the first/second of two items: "Tea and coffee are popular. The former is preferred in Asia; the latter in the Americas." LEXICAL cohesion: using synonyms to avoid repetition: "The study... The research... The investigation..."', moreExamples: ['Global temperatures are rising. This trend is expected to continue.', 'Applicants need experience and qualifications. The latter is particularly important.', 'Such measures have proved effective in other countries.'], commonMistakes: ['Vague "this": "This is a problem" — add a noun: "This issue is a problem" (clearer what "this" refers to)', 'Using "the former/the latter" with more than two items — only works with exactly two'] },
    ],
  },
]
