// # ═══════════════════════════════════════════════════════════════════════════
// # GRAMMAR PATTERNS — Extended Set 3: Determiners, Prepositions, Connectors
// # ═══════════════════════════════════════════════════════════════════════════
// # All content is original and copyright-free.
// # Categories: Quantifiers, Countable/Uncountable, Prepositions,
// # Conjunctions, Wish & If Only.

import type { GrammarCategory } from './types'

export const GRAMMAR_CATEGORIES_3: GrammarCategory[] = [

  // # ═══════════════════════════════════════════════════════════════════
  // # 1. QUANTIFIERS & DETERMINERS
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'quantifiers',
    name: 'Quantifiers & Determiners',
    description: 'Some, any, much, many, few, little, all, every, each, both, neither, either — choosing the right one.',
    patterns: [
      { id: 'some-any', name: 'Some / Any', category: 'quantifiers', level: 'A1', structure: 'some + uncountable/plural (positive) | any + uncountable/plural (negative/question)', meaning: '"Some" for positive statements and offers/requests. "Any" for negatives and most questions.', context: 'Everyday conversations about quantities — food, shopping, availability.', example: 'There are some biscuits in the cupboard. / Is there any milk left?', explanation: 'Basic rule: SOME in positives ("I have some money"), ANY in negatives and questions ("I don\'t have any money", "Do you have any questions?"). BUT use SOME in questions when you expect "yes" or you\'re offering: "Would you like some tea?" (offer), "Can I have some water?" (request). ANY in positives means "it doesn\'t matter which": "Any seat is fine" (= I don\'t mind which one). Compounds follow the same rules: something/anything, someone/anyone, somewhere/anywhere.', moreExamples: ['I need some help with this exercise.', 'There aren\'t any shops open on Sunday.', 'Would you like some cake? (offering — expecting yes)'], commonMistakes: ['Using "any" for offers: "Would you like any tea?" — use "some" when offering', 'Using "some" in negatives: "I don\'t have some money" — must be "any"'] },
      { id: 'much-many-lot', name: 'Much / Many / A lot of', category: 'quantifiers', level: 'A1', structure: 'much + uncountable | many + countable plural | a lot of + both', meaning: '"Much" for uncountable, "many" for countable, "a lot of" works with both.', context: 'Talking about large quantities — food, time, money, people.', example: 'We don\'t have much time. / There are many reasons to be optimistic.', explanation: '"Much" = uncountable (much water, much money, much time). "Many" = countable plural (many people, many books, many problems). "A lot of" = both (a lot of water, a lot of people) — more informal, works in positives. In POSITIVE statements, "a lot of" is more natural: "I have a lot of friends" sounds better than "I have many friends." "Much" and "many" are more natural in NEGATIVES and QUESTIONS: "I don\'t have much time", "Are there many people?" In formal writing, "many" and "much" are fine in positives.', moreExamples: ['How much does this cost?', 'How many languages do you speak?', 'She doesn\'t have a lot of experience in this area.'], commonMistakes: ['Using "much" with countable: "much people" — must be "many people"', 'Using "many" with uncountable: "many water" — must be "much water"', '"A lots of" — no "s" on "lot": "a lot of"'] },
      { id: 'few-little', name: 'Few / Little vs A Few / A Little', category: 'quantifiers', level: 'B1', structure: 'few + countable plural | little + uncountable | a few + countable | a little + uncountable', meaning: '"Few" and "little" (without "a") = not enough, negative. "A few" and "a little" (with "a") = some, enough, positive.', context: 'Expressing satisfaction or dissatisfaction with quantities.', example: 'Few people came to the meeting. (= not many, disappointing) / A few people came. (= some, enough)', explanation: 'This tiny word "a" completely changes the meaning: FEW (no "a") = not many, almost none — NEGATIVE feeling: "He has few friends" (= he\'s lonely). A FEW (with "a") = some, a small number — POSITIVE: "He has a few friends" (= he\'s not alone). Same for uncountable: LITTLE = not much, not enough: "There\'s little hope" (= almost no hope). A LITTLE = some, enough: "There\'s a little hope" (= some hope remains). "Very few" and "very little" emphasise the negative: "Very few students passed."', moreExamples: ['I speak a little French — enough to order food.', 'Very few people understand quantum physics.', 'We have a few minutes before the meeting — let\'s grab a coffee.'], commonMistakes: ['Ignoring the difference: "few" ≠ "a few" — they have opposite emotional meanings', 'Using "few" with uncountable: "few money" — must be "little money"', 'Using "little" with countable: "little books" — must be "few books"'] },
      { id: 'each-every-all', name: 'Each / Every / All / Both / Neither / Either', category: 'quantifiers', level: 'B1', structure: 'each/every + singular | all + plural/uncountable | both/neither/either + two items', meaning: 'Distributive determiners — talking about items individually, as a whole, or in pairs.', context: 'Rules, distributions, choices between options, and generalisations.', example: 'Each student received a certificate. / Both options are acceptable.', explanation: 'EACH = items individually, one by one: "Each room has a TV" (focus on individual rooms). EVERY = all items as a group: "Every room has a TV" (focus on the whole hotel). ALL = the entire group: "All students passed" (plural verb). BOTH = two items, inclusive: "Both answers are correct." NEITHER = two items, exclusive (negative): "Neither answer is correct." EITHER = two items, any one: "Either answer is acceptable." Each/every take SINGULAR verbs; all/both take PLURAL verbs.', moreExamples: ['Every child deserves a good education.', 'I go to the gym every other day. (= Monday, Wednesday, Friday...)', 'Neither of the candidates was suitable for the role.'], commonMistakes: ['Plural after every/each: "Every students" — must be "Every student" (singular)', 'Double negative: "Neither of them didn\'t come" — "neither" is already negative: "Neither of them came"', 'Confusing "either" (any one of two) with "both" (the two together)'] },
      { id: 'no-none', name: 'No / None / Not any / Nothing', category: 'quantifiers', level: 'B1', structure: 'no + noun | none + of | nothing/nobody/nowhere (standalone)', meaning: 'Different ways to express zero quantity — all mean the same thing but fit different sentence positions.', context: 'Expressing absence, denial, and empty sets.', example: 'There is no milk in the fridge. / None of the students failed. / I have nothing to say.', explanation: '"No" goes before a noun: "There are no seats available" (= There aren\'t any seats). "None" stands alone or uses "of": "None of my friends came", "How much is left?" "None." "Nothing/nobody/nowhere/no one" are pronouns — they replace the noun entirely: "I saw nothing" (= I didn\'t see anything). IMPORTANT: these are all NEGATIVE, so don\'t add another negative: "I don\'t have nothing" is a double negative — say "I don\'t have anything" or "I have nothing."', moreExamples: ['No smoking is allowed in this building.', 'None of the answers were correct.', 'There\'s nowhere to park around here.'], commonMistakes: ['Double negative: "I don\'t know nobody" — say "I don\'t know anybody" OR "I know nobody"', '"None" with wrong verb: "None of them have" or "None of them has"? Both are acceptable, but "has" (singular) is more formal'] },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 2. COUNTABLE & UNCOUNTABLE NOUNS
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'countable-uncountable',
    name: 'Countable & Uncountable Nouns',
    description: 'Which nouns can be counted (a book, two books) and which cannot (information, money) — and why it matters.',
    patterns: [
      { id: 'countable-rules', name: 'Countable Nouns', category: 'countable-uncountable', level: 'A1', structure: 'a/an + singular | number + plural | many/few + plural', meaning: 'Nouns you can count: they have singular and plural forms and use a/an.', context: 'Everyday descriptions, shopping, and quantities.', example: 'I bought a book. / She has three cats. / There are many chairs in the room.', explanation: 'Countable nouns have: 1) A singular form: "a chair", "one idea"; 2) A plural form: "chairs", "ideas"; 3) Can use a/an: "a car", "an apple"; 4) Can use numbers: "two cars", "five apples"; 5) Use "many/few" for quantity: "many students", "few options." Most concrete objects are countable: books, cups, people, houses, dogs. Regular plurals add -s/-es. Irregular plurals: child→children, person→people, mouse→mice, tooth→teeth, man→men.', moreExamples: ['How many eggs do we need?', 'She has a lot of good ideas.', 'There are fewer students in the class this year.'], commonMistakes: ['Wrong plural: "childs" — must be "children"; "peoples" — "people" IS the plural of "person"', 'Forgetting the article: "I need book" — must be "a book" or "books"'] },
      { id: 'uncountable-rules', name: 'Uncountable Nouns', category: 'countable-uncountable', level: 'A1', structure: 'No a/an | no plural | much/little + noun | use "some" or a partitive', meaning: 'Nouns that cannot be counted individually — they represent masses, concepts, or materials.', context: 'Abstract ideas, substances, academic subjects, and natural phenomena.', example: 'I need some information. / Water is essential for life. / She gave me good advice.', explanation: 'Uncountable nouns: 1) NO article "a/an": NOT "an information"; 2) NO plural: NOT "informations"; 3) Use "much/little": "much traffic", "little progress"; 4) Always singular verb: "The news IS good." Common uncountables that learners often get wrong: information, advice, news, research, furniture, equipment, luggage/baggage, accommodation, weather, traffic, work (= employment), homework, knowledge, progress, evidence, behaviour. To count them, use partitives: "a piece of advice", "a item of furniture", "a piece of news."', moreExamples: ['Can you give me some advice?', 'The furniture in this room is very old.', 'We don\'t have much luggage — just one suitcase each.'], commonMistakes: ['"An advice" / "advices" — uncountable: "some advice" or "a piece of advice"', '"An information" / "informations" — say "some information" or "a piece of information"', '"The news are good" — "news" is singular: "The news IS good"'] },
      { id: 'both-countable-uncountable', name: 'Nouns That Can Be Both', category: 'countable-uncountable', level: 'B1', structure: 'Same noun, different meaning when countable vs uncountable', meaning: 'Some nouns change meaning depending on whether they are treated as countable or uncountable.', context: 'Understanding subtle differences in meaning based on usage.', example: 'I love chocolate. (uncountable = the substance) / Would you like a chocolate? (countable = one piece)', explanation: 'Many nouns work both ways with different meanings: PAPER (U) = material vs A PAPER (C) = a newspaper/document. GLASS (U) = material vs A GLASS (C) = a drinking vessel. LIGHT (U) = illumination vs A LIGHT (C) = a lamp. ROOM (U) = space vs A ROOM (C) = a part of a building. EXPERIENCE (U) = knowledge gained vs AN EXPERIENCE (C) = an event. COFFEE (U) = the drink in general vs A COFFEE (C) = a cup of coffee. HAIR (U) = all the hair on your head vs A HAIR (C) = a single strand.', moreExamples: ['I don\'t have much time. (U) / I\'ve been there three times. (C)', 'She has beautiful hair. (U) / There\'s a hair in my soup! (C)', 'He has a lot of experience in marketing. (U) / It was an unforgettable experience. (C)'], commonMistakes: ['Not recognising the shift: "I found a hair" (one strand) is very different from "I like your hair" (all of it)', 'Treating always as one type: "She has a beautiful hair" (should be uncountable here: "beautiful hair")'] },
      { id: 'partitives', name: 'Partitives & Containers', category: 'countable-uncountable', level: 'B1', structure: 'a + container/unit/piece + of + uncountable noun', meaning: 'Makes uncountable nouns countable by adding a unit of measurement, container, or piece.', context: 'Shopping, cooking, ordering food, and being specific about quantities.', example: 'Can I have a glass of water? / I need two pieces of information.', explanation: 'Since uncountable nouns can\'t use numbers directly, partitives let you count them: CONTAINERS: a cup of tea, a bottle of wine, a glass of water, a bowl of soup, a jar of honey. PIECES/PARTS: a piece of cake/advice/furniture/information/news, a slice of bread/pizza, a lump of sugar, a sheet of paper, a drop of rain, a grain of sand/rice. GROUPS: a bunch of flowers, a set of keys. ABSTRACT: a bit of luck, a stroke of genius, an act of kindness.', moreExamples: ['She bought two loaves of bread and a carton of milk.', 'He ate three slices of pizza.', 'I need a few sheets of paper for the printer.'], commonMistakes: ['Wrong partitive: "a glass of bread" — bread uses "a slice of" or "a loaf of"', 'Forgetting "of": "a piece information" — must be "a piece OF information"'] },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 3. PREPOSITIONS
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'prepositions',
    name: 'Prepositions',
    description: 'Prepositions of time, place, and movement — plus dependent and complex prepositions.',
    patterns: [
      { id: 'prepositions-time', name: 'Prepositions of Time (at, on, in)', category: 'prepositions', level: 'A1', structure: 'at + clock time/festivals | on + days/dates | in + months/years/seasons/periods', meaning: 'Three basic prepositions for different time scales — the most common source of errors for learners.', context: 'Scheduling, storytelling, and describing when events happen.', example: 'The meeting is at 3 p.m. on Monday. / She was born in March 1995.', explanation: 'AT = specific times and points: at 3 o\'clock, at noon, at midnight, at the weekend (BrE), at Christmas, at the moment. ON = specific days and dates: on Monday, on 25th December, on my birthday, on New Year\'s Eve. IN = longer periods: in January, in 2024, in spring, in the morning/afternoon/evening (BUT "at night"). NO preposition with: today, tomorrow, yesterday, last/next/this/every + time: "I\'ll see you next week" (NOT "in next week").', moreExamples: ['I usually wake up at 6:30 in the morning.', 'We\'re going on holiday in August.', 'The project started on the 1st of September.'], commonMistakes: ['"In Monday" — days use "on": "on Monday"', '"At the morning" — use "in the morning" (but "at night")', '"In next week" — no preposition with next/last/this/every: "next week"'] },
      { id: 'prepositions-place', name: 'Prepositions of Place (at, on, in)', category: 'prepositions', level: 'A1', structure: 'at + specific point/address | on + surface/line | in + enclosed space/area', meaning: 'The same three prepositions describe different spatial relationships.', context: 'Giving directions, describing locations, and talking about where things are.', example: 'She\'s at the bus stop. / The book is on the table. / He lives in London.', explanation: 'AT = a specific point or location: at the door, at the bus stop, at home, at work, at school, at the airport, at 42 Oak Street. ON = touching a surface or along a line: on the table, on the wall, on the floor, on the left, on the second floor, on the bus/train/plane (public transport). IN = inside an enclosed space or area: in the room, in the car (private vehicle), in London, in England, in a queue, in the garden, in bed. Think of scale: AT (a point) → ON (a surface/line) → IN (an area/volume).', moreExamples: ['There\'s someone at the door.', 'I saw your photo on the wall.', 'She\'s in the kitchen making dinner.'], commonMistakes: ['"In the bus" — public transport uses "on": "on the bus" (but "in the car" for private vehicles)', '"On home" — use "at home" (no article either: NOT "at the home")', '"I arrived at London" — cities use "in": "I arrived in London" (but "at the airport")'] },
      { id: 'prepositions-movement', name: 'Prepositions of Movement', category: 'prepositions', level: 'A2', structure: 'to/towards/into/out of/through/across/along/over/under/past + noun', meaning: 'Describe direction and trajectory — where something is going, not where it is.', context: 'Giving directions, describing journeys, and narrating actions.', example: 'She walked across the bridge. / The cat jumped over the fence.', explanation: 'TO = destination: "I\'m going to the office." TOWARDS = direction (may not arrive): "He walked towards the exit." INTO = entering enclosed space: "She went into the building." OUT OF = leaving enclosed space: "He came out of the house." THROUGH = from one side to the other (inside): "We drove through the tunnel." ACROSS = from one side to the other (surface): "She swam across the river." ALONG = following a line: "Walk along this road." OVER = above and across: "The plane flew over the city." PAST = passing by: "She walked past me without saying hello."', moreExamples: ['The children ran into the garden.', 'We drove through the village without stopping.', 'She walked along the river for about a mile.'], commonMistakes: ['"I went to home" — no preposition needed: "I went home"', '"I arrived to London" — use "in" for cities: "I arrived in London" (use "at" for buildings: "arrived at the hotel")', 'Confusing "in" (static) with "into" (movement): "She walked in the room" should be "into the room" (movement)'] },
      { id: 'dependent-prepositions', name: 'Dependent Prepositions', category: 'prepositions', level: 'B2', structure: 'adjective/verb/noun + specific preposition (must be memorised)', meaning: 'Many adjectives, verbs, and nouns are always followed by a specific preposition — these must be learned as fixed pairs.', context: 'All contexts — these combinations appear constantly in natural English.', example: 'She\'s interested in history. / I apologised for being late. / There\'s a solution to the problem.', explanation: 'ADJECTIVES + preposition: interested IN, afraid OF, responsible FOR, different FROM, good AT, keen ON, worried ABOUT, proud OF, similar TO, tired OF. VERBS + preposition: depend ON, believe IN, apologise FOR, agree WITH, apply FOR, belong TO, succeed IN, suffer FROM, result IN, insist ON. NOUNS + preposition: solution TO, reason FOR, increase IN, advantage OF, effect ON, answer TO, demand FOR. There is no reliable rule — these must be memorised as combinations.', moreExamples: ['The answer depends on several factors.', 'She\'s very good at languages.', 'We need to find a solution to this problem.'], commonMistakes: ['"Interested for" — must be "interested IN"', '"Different to" — traditional grammar says "different FROM" (though "different to/than" is increasingly accepted)', '"The reason of" — must be "the reason FOR"'] },
      { id: 'complex-prepositions', name: 'Complex Prepositions', category: 'prepositions', level: 'B2', structure: 'Multi-word prepositions: due to, in spite of, according to, instead of, etc.', meaning: 'Phrases that function as a single preposition — essential for formal writing and linking ideas.', context: 'Academic writing, reports, formal speech, and IELTS/CAE essays.', example: 'Due to the bad weather, the match was cancelled. / In spite of the rain, we enjoyed the walk.', explanation: 'Common complex prepositions: DUE TO / OWING TO = because of (+ noun): "Due to heavy traffic, I was late." IN SPITE OF / DESPITE = although (+ noun/gerund): "Despite being tired, she kept working." ACCORDING TO = as stated by: "According to the report, sales have increased." INSTEAD OF = as an alternative to: "Instead of driving, we took the train." IN ADDITION TO = as well as: "In addition to English, she speaks French." AS WELL AS = and also: "As well as teaching, he does research." BY MEANS OF = using (formal): "They communicate by means of sign language."', moreExamples: ['In addition to the fine, he lost his driving licence.', 'According to the forecast, it will rain all week.', 'Instead of complaining, why not try to find a solution?'], commonMistakes: ['"Despite of" — wrong; "despite" alone OR "in spite of": "Despite the rain" = "In spite of the rain"', '"According to me" — this means "as I stated"; for your opinion, say "In my opinion" or "I think"', '"Due to" with a clause: "Due to it rained" — must be followed by a noun/gerund: "Due to the rain" or "Due to it raining"'] },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 4. CONJUNCTIONS & LINKING WORDS
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'conjunctions',
    name: 'Conjunctions & Linking Words',
    description: 'Connecting ideas within and between sentences — from basic (and, but) to advanced (nevertheless, furthermore).',
    patterns: [
      { id: 'coordinating', name: 'Coordinating Conjunctions (FANBOYS)', category: 'conjunctions', level: 'A1', structure: 'Clause + , + for/and/nor/but/or/yet/so + clause', meaning: 'Connect two equal (independent) clauses or words — the seven basic connectors.', context: 'All spoken and written English — the most fundamental connectors.', example: 'I was tired, but I kept working. / She likes tea and coffee.', explanation: 'The 7 coordinating conjunctions (FANBOYS): FOR (= because, formal), AND (addition), NOR (negative addition), BUT (contrast), OR (alternative), YET (contrast, = but), SO (result). They join two EQUAL things: word + word ("hot and cold"), phrase + phrase ("in the morning or in the evening"), clause + clause ("She called, but nobody answered"). Use a comma before the conjunction when joining two independent clauses: "I was tired, so I went to bed." No comma for short phrases: "bread and butter."', moreExamples: ['I didn\'t have my phone, nor did I have any cash.', 'She studied hard, yet she still failed the exam.', 'Hurry up, or we\'ll miss the train.'], commonMistakes: ['Starting formal sentences with "And" or "But" — increasingly accepted, but some teachers mark it as wrong', 'Missing comma before clause: "She called but nobody answered" — add comma: "She called, but nobody answered"'] },
      { id: 'subordinating', name: 'Subordinating Conjunctions', category: 'conjunctions', level: 'B1', structure: 'Main clause + subordinating conjunction + dependent clause (or reversed)', meaning: 'Connect a main clause to a dependent clause — showing time, reason, condition, or contrast.', context: 'Complex sentences in all contexts — essential for B1+ writing.', example: 'I\'ll wait here until you get back. / Although it was raining, we went for a walk.', explanation: 'TIME: when, while, before, after, until, as soon as, since, by the time. REASON: because, since, as. CONDITION: if, unless, provided that, as long as. CONTRAST: although, though, even though, whereas, while. PURPOSE: so that, in order that. RESULT: so...that, such...that. When the dependent clause comes FIRST, use a comma: "Because it was late, we went home." When it comes second, no comma: "We went home because it was late."', moreExamples: ['As soon as I arrive, I\'ll call you.', 'Even though he apologised, she was still angry.', 'I\'ll lend you the book provided that you return it by Friday.'], commonMistakes: ['Using "because" and "so" together: "Because it rained, so we stayed inside" — choose one: "Because it rained, we stayed inside" OR "It rained, so we stayed inside"', 'Comma after second-position dependent clause: "We left because it was late," — no comma needed there'] },
      { id: 'correlative', name: 'Correlative Conjunctions', category: 'conjunctions', level: 'B2', structure: 'both...and | either...or | neither...nor | not only...but also | whether...or', meaning: 'Paired conjunctions that work together to connect balanced elements.', context: 'Formal writing, balanced arguments, and emphasising pairs.', example: 'She speaks both French and German. / Not only did he apologise, but he also offered to pay.', explanation: 'BOTH...AND = inclusive pair: "Both the food and the service were excellent." EITHER...OR = one of two options: "Either you apologise or I\'m leaving." NEITHER...NOR = not one and not the other: "Neither the teacher nor the students knew the answer." NOT ONLY...BUT ALSO = addition with emphasis: "Not only is she smart, but she\'s also very kind." (note inversion after "not only" at start). WHETHER...OR = two possibilities: "I can\'t decide whether to stay or go." Parallel structure is key: what follows each pair should be grammatically identical.', moreExamples: ['You can either call me or send an email.', 'Neither the hotel nor the restaurant met our expectations.', 'Not only did she win the award, but she also broke the record.'], commonMistakes: ['Broken parallelism: "Both to read and writing" — must match: "Both reading and writing" or "both to read and to write"', 'Subject-verb agreement with "neither...nor": the verb agrees with the NEAREST subject: "Neither he nor his friends WERE there"'] },
      { id: 'discourse-connectors', name: 'Formal Linking Words (however, moreover, therefore)', category: 'conjunctions', level: 'B2', structure: 'Sentence. + However/Moreover/Therefore/Furthermore/Nevertheless, + sentence.', meaning: 'Connect ideas between sentences — essential for essays, reports, and formal communication.', context: 'Academic writing, IELTS essays, business reports, and formal speeches.', example: 'The experiment failed. However, the results provided valuable data.', explanation: 'CONTRAST: however, nevertheless, nonetheless, on the other hand, in contrast, conversely. ADDITION: moreover, furthermore, in addition, besides, what is more. RESULT: therefore, consequently, as a result, hence, thus, accordingly. EXAMPLE: for instance, for example, in particular, specifically. SUMMARY: in conclusion, to sum up, overall, in short. These are ADVERBS, not conjunctions — they CANNOT join clauses with just a comma. Use a full stop or semicolon: "It rained. However, we went out." NOT "It rained, however we went out."', moreExamples: ['The price is reasonable. Moreover, the quality is excellent.', 'He didn\'t study. Consequently, he failed the exam.', 'The city is crowded. Nevertheless, I love living here.'], commonMistakes: ['Comma splice: "It rained, however we went out" — WRONG. Use: "It rained. However, we went out." or "It rained; however, we went out."', 'Confusing "however" (= but) with "how ever" (= how on earth): "However did you manage?" = "How on earth did you manage?"'] },
      { id: 'time-connectors', name: 'Time Connectors & Sequencing', category: 'conjunctions', level: 'B1', structure: 'Time connector + clause/phrase', meaning: 'Show the order and timing of events — essential for narratives, processes, and instructions.', context: 'Storytelling, process descriptions, instructions, and presentations.', example: 'First, preheat the oven. Then, mix the ingredients. Finally, bake for 30 minutes.', explanation: 'SEQUENCE: first/firstly, second/secondly, then, next, after that, finally, lastly, in the end, eventually. SIMULTANEOUS: meanwhile, in the meantime, at the same time, while. BEFORE: before, prior to, previously, earlier, beforehand. AFTER: after, afterwards, subsequently, later, following that. IMMEDIATE: as soon as, the moment, immediately, no sooner...than, hardly...when. Use present tense (not "will") in time clauses about the future: "I\'ll call you as soon as I arrive" (NOT "as soon as I will arrive").', moreExamples: ['Meanwhile, the sauce should be simmering on low heat.', 'Eventually, after three hours of negotiation, they reached an agreement.', 'No sooner had we arrived than it started to rain.'], commonMistakes: ['Using "will" in time clauses: "When I will arrive" — must be "When I arrive"', 'Confusing "in the end" (finally/eventually) with "at the end" (at the final point): "At the end of the film" vs "In the end, everything worked out"'] },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 5. WISH & IF ONLY
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'wish-if-only',
    name: 'Wish & If Only',
    description: 'Expressing wishes about the present, past, and future — what you want to be different.',
    patterns: [
      { id: 'wish-present', name: 'Wish + Past Simple (Present Wishes)', category: 'wish-if-only', level: 'B1', structure: 'Subject + wish/wishes + (that) + subject + past simple', meaning: 'Expresses a wish for the present to be different from reality — the situation is unreal or unlikely.', context: 'Talking about dissatisfaction with current situations and imagining alternatives.', example: 'I wish I had more free time. / She wishes she lived closer to her family.', explanation: 'Like the second conditional, "wish + past simple" does NOT refer to the past — it refers to the present. "I wish I had a car" = I don\'t have a car now, and I want one. "I wish" works like "if only" (but "if only" is more dramatic/emotional). For "be", use "were" for all subjects (formal): "I wish I were taller" (though "was" is acceptable in informal English). This is the subjunctive mood applied to wishes.', moreExamples: ['I wish I knew the answer, but I don\'t.', 'He wishes he were better at cooking.', 'We wish we didn\'t have to work tomorrow.'], commonMistakes: ['Using present tense: "I wish I have more time" — must be "had" (past simple for unreal present)', 'Thinking it\'s about the past: "I wish I had a dog" = I DON\'T have a dog NOW'] },
      { id: 'wish-past', name: 'Wish + Past Perfect (Past Regrets)', category: 'wish-if-only', level: 'B2', structure: 'Subject + wish/wishes + (that) + subject + past perfect (had + past participle)', meaning: 'Expresses regret about something that happened (or didn\'t happen) in the past — it cannot be changed.', context: 'Expressing regret, reflecting on missed opportunities, and lamenting past decisions.', example: 'I wish I had studied harder at university. / She wishes she hadn\'t said that.', explanation: 'Like the third conditional, this is about changing an unchangeable past. "I wish I had gone to the party" = I didn\'t go, and I regret it. "I wish I hadn\'t eaten so much" = I ate too much, and I regret it. The past is fixed — this structure expresses how you FEEL about it, not what actually happened. Compare with "wish + past simple" (present): "I wish I spoke French" (present wish) vs "I wish I had studied French at school" (past regret).', moreExamples: ['He wishes he hadn\'t dropped out of university.', 'I wish I had taken that job offer when I had the chance.', 'She wishes she had been kinder to her grandmother.'], commonMistakes: ['Using past simple for regrets: "I wish I studied harder" — this is a present wish; for past regret, use "had studied"', 'Confusing with "should have": "I should have studied harder" (criticism/advice) vs "I wish I had studied harder" (emotional regret)'] },
      { id: 'wish-would', name: 'Wish + Would (Complaints & Requests)', category: 'wish-if-only', level: 'B2', structure: 'Subject + wish + (that) + another subject + would/wouldn\'t + base verb', meaning: 'Expresses annoyance about other people\'s behaviour or situations you want to change but can\'t control.', context: 'Complaints about habits, frustrations with others, and polite requests for change.', example: 'I wish you would stop making so much noise. / She wishes it would stop raining.', explanation: 'This is for things OTHER PEOPLE (or external forces) do that annoy you. You CANNOT use "wish + would" about yourself: "I wish I would be taller" is wrong — use "I wish I were taller." The subject before "wish" and after "would" must be DIFFERENT. It implies: 1) Complaint: "I wish he would tidy his room" (= he never does, and it annoys me); 2) Request: "I wish you would listen to me" (= please listen); 3) Uncontrollable situations: "I wish it would stop snowing" (= I can\'t control it).', moreExamples: ['I wish the neighbours would turn their music down.', 'She wishes her boss would give her more responsibility.', 'I wish people wouldn\'t drop litter in the park.'], commonMistakes: ['Using about yourself: "I wish I would be taller" — WRONG. Use "I wish I were taller" (wish + past simple for yourself)', 'Same subject: "She wishes she would study more" — WRONG. Use "She wishes she studied more" (or an external subject: "She wishes her son would study more")'] },
      { id: 'if-only', name: 'If Only (Stronger Wish)', category: 'wish-if-only', level: 'B2', structure: 'If only + past simple (present) | If only + past perfect (past) | If only + would (complaint)', meaning: 'Works exactly like "wish" but is more emotional, dramatic, and emphatic — often used with exclamation marks.', context: 'Expressing strong feelings of regret, longing, or frustration.', example: 'If only I could fly! / If only we had left earlier! / If only it would stop raining!', explanation: '"If only" follows the exact same grammar as "wish" — past simple for present wishes, past perfect for past regrets, "would" for complaints. The ONLY difference is intensity: "If only" is more emotional and dramatic. Often used alone as an exclamation: "If only!" (= I really wish things were different). Common in literature and film for dramatic effect. In everyday speech, "I wish" is more common; "if only" adds weight.', moreExamples: ['If only I had listened to my parents\' advice!', 'If only we lived by the sea — I\'d go swimming every day.', 'If only she would forgive me.'], commonMistakes: ['Treating "if only" as a real conditional: "If only I study harder, I\'ll pass" — WRONG. It\'s a wish, not a condition. Use: "If only I studied harder" or "If I study harder, I\'ll pass"', 'Same grammar mistakes as with "wish" — all rules about tenses apply identically'] },
    ],
  },
]
