// # ═══════════════════════════════════════════════════════════════════════════
// # LESSON DATA — Part 13: Speaking Lessons A1 + A2 (47 lessons)
// # ═══════════════════════════════════════════════════════════════════════════

import type { LessonCategory } from './types'

export const LESSON_CATEGORIES_13: LessonCategory[] = [
  {
    id: 'a1-speaking',
    name: 'A1: Speaking Skills',
    description: 'Build confidence in basic spoken English — greetings, introductions, and everyday conversations.',
    icon: '🗣️',
    lessons: [
      // # ─── Lesson 1: Greetings & Introductions ───
      { id: 'a1-speaking-greetings', title: 'Greetings & Introductions', description: 'Say hello, introduce yourself, and meet new people with confidence.',
        skill: 'speaking', level: 'A1', duration: 8,
        objectives: ['Use formal and informal greetings', 'Introduce yourself with name and nationality', 'Ask someone their name'],
        sections: [
          { title: 'Formal vs Informal Greetings', type: 'rule', content: 'Formal (strangers, work, older people): "Good morning." "Good afternoon." "Good evening." "Hello, my name is..." "How do you do?" Informal (friends, family, young people): "Hi!" "Hey!" "What\'s up?" "How\'s it going?" Match the greeting to the situation — saying "What\'s up?" to your boss on day one is too casual.' },
          { title: 'Introduction Formula', type: 'tip', content: 'The basic introduction follows a simple pattern: "Hi, I\'m [name]. I\'m from [country/city]. Nice to meet you." Then ask the other person: "What\'s your name?" or "Where are you from?" Always say "Nice to meet you" when meeting someone for the first time. It makes a great impression.' },
          { title: 'Practice: Introduce Yourself', type: 'exercise', question: 'Imagine you meet someone at a language class. Introduce yourself (name, country, why you are learning English).', answer: '"Hi, I\'m Maria. I\'m from Brazil. I\'m learning English because I want to travel. Nice to meet you! What\'s your name?"', answerExplanation: 'Simple, friendly, includes name + country + reason. Ends with a question to keep the conversation going. This is the perfect A1 introduction.' },
        ],
        keyTakeaways: ['Use "Good morning/afternoon" for formal, "Hi/Hey" for informal', 'Always say "Nice to meet you" when meeting someone new', 'End your introduction with a question to keep talking'],
      },
      // # ─── Lesson 2: Saying Your Name, Age & Country ───
      { id: 'a1-speaking-personal-info', title: 'Sharing Personal Information', description: 'Talk about yourself — name, age, country, and language.',
        skill: 'speaking', level: 'A1', duration: 8,
        objectives: ['Say your name, age, and nationality', 'Ask others for their personal information', 'Use "I am" and "I speak" correctly'],
        sections: [
          { title: 'Key Phrases', type: 'rule', content: 'My name is... / I\'m... (name). I\'m [number] years old. (age). I\'m from [country]. (nationality). I speak [language]. I live in [city]. I\'m a [job/student]. Questions to ask: "What\'s your name?" "How old are you?" "Where are you from?" "What do you do?" "What languages do you speak?"' },
          { title: 'Age Is Optional', type: 'tip', content: 'In many English-speaking countries, asking "How old are you?" can be rude, especially with adults. It is fine between young people and in language classes. If someone asks YOU, it\'s OK to answer. But don\'t ask older people their age — it can be uncomfortable.' },
          { title: 'Answer These Questions', type: 'exercise', question: 'Answer about yourself: What\'s your name? Where are you from? What languages do you speak?', answer: '"My name is Kenji. I\'m from Japan, from Tokyo. I speak Japanese and a little English."', answerExplanation: '"a little English" is honest and natural — native speakers appreciate it. You don\'t need to say "I can speak" — "I speak" is simpler and correct.' },
        ],
        keyTakeaways: ['I\'m from [country]. I speak [language]. I live in [city].', 'Don\'t ask adults "How old are you?" — it can be rude', '"I speak a little English" is a useful honest phrase'],
      },
      // # ─── Lesson 3: Asking & Answering Simple Questions ───
      { id: 'a1-speaking-simple-questions', title: 'Asking & Answering Simple Questions', description: 'Master the basic question patterns that power every conversation.',
        skill: 'speaking', level: 'A1', duration: 10,
        objectives: ['Form yes/no questions with "do" and "are"', 'Form WH-questions (what, where, when, who, how)', 'Give short and full answers'],
        sections: [
          { title: 'Yes/No Questions', type: 'rule', content: 'With "be": "Are you a student?" → "Yes, I am." / "No, I\'m not." "Is she from Spain?" → "Yes, she is." / "No, she isn\'t." With "do": "Do you like coffee?" → "Yes, I do." / "No, I don\'t." "Does he work here?" → "Yes, he does." / "No, he doesn\'t." Pattern: Do/Does/Are/Is + subject + verb/adjective?' },
          { title: 'WH-Questions', type: 'rule', content: 'What = thing: "What is your name?" "What do you do?" Where = place: "Where are you from?" "Where do you live?" When = time: "When is your birthday?" "When do you start work?" Who = person: "Who is your teacher?" "Who do you live with?" How = way/method: "How are you?" "How do you get to work?" Pattern: WH-word + do/does/is/are + subject + verb?' },
          { title: 'Ask Questions', type: 'exercise', question: 'Your new classmate is called Tom. Ask him 3 questions to learn about him.', answer: '"Where are you from, Tom?" "What do you do?" "Do you like this city?"', answerExplanation: 'Three different question types: where (place), what (information), do you (yes/no). All are friendly and appropriate for a first conversation.' },
        ],
        keyTakeaways: ['Yes/No: Do you...? / Are you...? → Yes, I do. / No, I don\'t.', 'WH: What/Where/When/Who/How + do/is + subject + verb', 'Short answers are natural: "Yes, I do" (you don\'t need "Yes, I do like coffee")'],
      },
      // # ─── Lesson 4: Numbers, Counting & Prices ───
      { id: 'a1-speaking-numbers', title: 'Numbers, Counting & Prices', description: 'Say numbers clearly — for shopping, phone numbers, and addresses.',
        skill: 'speaking', level: 'A1', duration: 8,
        objectives: ['Count from 1 to 100 clearly', 'Say prices and phone numbers', 'Understand numbers when you hear them'],
        sections: [
          { title: 'Tricky Numbers', type: 'rule', content: 'Numbers that sound similar: 13 (thirteen) vs 30 (thirty). 14 (fourteen) vs 40 (forty). 15 (fifteen) vs 50 (fifty). The stress is different: thirTEEN (stress on -teen) vs THIRty (stress on first syllable). Phone numbers: say each digit separately: 0-7-7-4-5-5-3-2-1-0. "Oh" is common for zero: "oh-seven-seven..." Prices: £3.50 = "three pounds fifty" or "three fifty". $12.99 = "twelve ninety-nine" or "twelve dollars and ninety-nine cents."' },
          { title: 'Double Numbers', type: 'tip', content: 'When a number repeats: 77 = "double seven" or "seven seven". 55 = "double five". 000 = "triple oh". This is common in phone numbers and room numbers. "My room number is four-oh-three" (403). "My phone number is oh-seven-seven, double five, three-two-one-oh."' },
          { title: 'Say These Out Loud', type: 'exercise', question: 'Say these: (a) Your phone costs £599. (b) Phone number: 0771 553 210. (c) The shirt is $14.50.', answer: '(a) "five hundred and ninety-nine pounds" or "five ninety-nine" (b) "oh-seven-seven-one, double five, three-two-one-oh" (c) "fourteen dollars fifty" or "fourteen fifty"', answerExplanation: 'For prices, both the full form and the short form are correct. For phone numbers, each digit is said separately, with "double" for repeated digits.' },
        ],
        keyTakeaways: ['thirTEEN vs THIRty — stress position changes the meaning', 'Phone numbers: say each digit; use "double" for repeats', 'Prices: "three fifty" is shorter and more natural than "three pounds fifty pence"'],
      },
      // # ─── Lesson 5: Days, Months & Dates ───
      { id: 'a1-speaking-days-months', title: 'Days, Months & Dates', description: 'Talk about days of the week, months, and important dates.',
        skill: 'speaking', level: 'A1', duration: 8,
        objectives: ['Say all days and months correctly', 'Ask and answer "When is...?" questions', 'Say dates in spoken English'],
        sections: [
          { title: 'How to Say Dates', type: 'rule', content: 'Written: 5th March / March 5th. Spoken: "the fifth of March" (British) or "March fifth" (American). Ordinal numbers for dates: 1st = first, 2nd = second, 3rd = third, 4th = fourth, 5th = fifth... 21st = twenty-first, 22nd = twenty-second, 30th = thirtieth, 31st = thirty-first. Years: 2026 = "twenty twenty-six" or "two thousand and twenty-six."' },
          { title: 'Prepositions of Time', type: 'tip', content: 'ON + days and dates: "on Monday", "on the 5th of March", "on my birthday". IN + months, seasons, years: "in March", "in summer", "in 2026". AT + specific times: "at 3 o\'clock", "at noon", "at night". Common mistake: "in Monday" ✗ → "on Monday" ✓. "at March" ✗ → "in March" ✓.' },
          { title: 'Answer About Dates', type: 'exercise', question: 'When is your birthday? What day is it today? What month do you like best?', answer: '"My birthday is on the 15th of June." "Today is Thursday." "I like October best because the weather is cool."', answerExplanation: 'ON the 15th (day/date = on). Today IS Thursday (no preposition needed). IN October would be used if saying "in October the weather is cool."' },
        ],
        keyTakeaways: ['ON days/dates, IN months/years, AT times', 'Say dates with ordinals: "the fifth of March" not "the five of March"', '2026 = "twenty twenty-six"'],
      },
      // # ─── Lesson 6: Telling the Time ───
      { id: 'a1-speaking-telling-time', title: 'Telling the Time', description: 'Ask and tell the time in everyday conversations.',
        skill: 'speaking', level: 'A1', duration: 8,
        objectives: ['Ask "What time is it?" naturally', 'Say times using "past", "to", and "o\'clock"', 'Understand 12-hour and 24-hour formats'],
        sections: [
          { title: 'Saying the Time', type: 'rule', content: '3:00 = "three o\'clock". 3:05 = "five past three". 3:15 = "quarter past three". 3:30 = "half past three". 3:45 = "quarter to four". 3:55 = "five to four". The digital way is also fine: 3:15 = "three fifteen". 3:45 = "three forty-five". In everyday speech, you can say: "It\'s about three" (approximate) or "It\'s just after three" or "It\'s nearly four."' },
          { title: 'How to Ask', type: 'tip', content: 'Polite ways to ask: "Excuse me, what time is it?" "Do you have the time?" "Could you tell me the time, please?" Casual: "What time is it?" "What\'s the time?" Don\'t say: "What time is it now?" (the "now" is unnecessary — it\'s always "now"). Don\'t say: "How much time is it?" (this is a common mistake).' },
          { title: 'Say These Times', type: 'exercise', question: 'Say in words: (a) 9:00 (b) 6:30 (c) 11:45 (d) 2:10', answer: '(a) "nine o\'clock" (b) "half past six" or "six thirty" (c) "quarter to twelve" or "eleven forty-five" (d) "ten past two" or "two ten"', answerExplanation: 'Both traditional (past/to) and digital (numbers only) are correct. Traditional sounds more natural in conversation; digital is common with screens and schedules.' },
        ],
        keyTakeaways: ['"Past" for minutes after the hour, "to" for minutes before the next hour', '"Quarter past", "half past", "quarter to" are the most common', '"Do you have the time?" is the most natural way to ask'],
      },
      // # ─── Lesson 7: Ordering Food & Drinks ───
      { id: 'a1-speaking-ordering-food', title: 'Ordering Food & Drinks', description: 'Order confidently at cafés, restaurants, and fast-food places.',
        skill: 'speaking', level: 'A1', duration: 10,
        objectives: ['Order food and drinks politely', 'Ask about the menu', 'Handle common waiter/customer exchanges'],
        sections: [
          { title: 'Ordering Phrases', type: 'rule', content: 'Polite ordering: "I\'d like a coffee, please." "Can I have a sandwich, please?" "Could I get a glass of water?" Asking about food: "What do you recommend?" "Is this spicy?" "Does this have nuts?" "What\'s the soup of the day?" Paying: "Can I have the bill, please?" (British) / "Can I get the check?" (American). "Can I pay by card?"' },
          { title: 'Don\'t Say "I Want"', type: 'tip', content: '"I want a coffee" is grammatically correct but sounds demanding. Use instead: "I\'d like..." (most polite). "Can I have...?" (polite). "I\'ll have..." (confident, common). "Could I get...?" (polite, informal). All of these sound much more natural and friendly than "I want."' },
          { title: 'Role-Play: At a Café', type: 'exercise', question: 'You\'re at a café. Order a latte and a chocolate cake. Ask if they have soy milk.', answer: '"Hi! I\'d like a latte, please. Do you have soy milk? Great, with soy milk then. And could I also have a slice of chocolate cake? Thanks!"', answerExplanation: 'Uses "I\'d like" (polite), asks a question naturally (Do you have...?), adds "please" and "thanks". This is exactly how native speakers order.' },
        ],
        keyTakeaways: ['Use "I\'d like..." or "Can I have..." — not "I want"', 'Always add "please" when ordering', '"Can I have the bill?" (UK) or "Can I get the check?" (US)'],
      },
      // # ─── Lesson 8: Shopping — Asking Prices ───
      { id: 'a1-speaking-shopping', title: 'Shopping — Asking Prices & Sizes', description: 'Ask about prices, sizes, and colours when shopping.',
        skill: 'speaking', level: 'A1', duration: 8,
        objectives: ['Ask "How much is this?" naturally', 'Ask about sizes, colours, and availability', 'Say "I\'ll take it" or "No, thank you"'],
        sections: [
          { title: 'Shopping Phrases', type: 'rule', content: 'Asking about products: "How much is this?" "How much are these shoes?" "Do you have this in a medium?" "Do you have this in blue?" "Can I try this on?" "Where is the fitting room?" Buying: "I\'ll take it." "I\'ll take these." Not buying: "I\'m just looking, thanks." "It\'s a bit too expensive." "I\'ll think about it."' },
          { title: 'Browsing Without Pressure', type: 'tip', content: 'When a shop assistant says "Can I help you?" and you\'re just browsing: "I\'m just looking, thanks." — This is perfectly polite and they will leave you alone. "I\'m looking for a gift for my friend." — This invites their help. "No, thanks." — Short but fine. Never feel pressured to buy just because someone helped you.' },
          { title: 'Shopping Dialogue', type: 'exercise', question: 'You want to buy a T-shirt. Ask about the price, if they have it in large, and decide to buy it.', answer: '"Excuse me, how much is this T-shirt?" "Do you have it in a large?" "Yes, I\'ll take it. Can I pay by card?"', answerExplanation: 'Three natural exchanges: price question, size question, purchase decision. "I\'ll take it" is the standard way to say you want to buy something.' },
        ],
        keyTakeaways: ['"How much is this?" for price, "Do you have this in...?" for size/colour', '"I\'m just looking, thanks" when you don\'t want help', '"I\'ll take it" to buy, "I\'ll think about it" to politely decline'],
      },
      // # ─── Lesson 9: Asking for & Giving Directions ───
      { id: 'a1-speaking-directions', title: 'Asking for & Giving Directions', description: 'Find your way around — ask where things are and understand simple directions.',
        skill: 'speaking', level: 'A1', duration: 10,
        objectives: ['Ask where something is politely', 'Understand basic direction words', 'Give simple directions'],
        sections: [
          { title: 'Direction Words', type: 'rule', content: 'Go straight / Go straight ahead. Turn left / Turn right. It\'s on the left / It\'s on the right. It\'s next to [the bank]. It\'s opposite [the station]. It\'s between [the café] and [the shop]. It\'s on the corner. Go past the supermarket. Take the first/second/third street on the left/right.' },
          { title: 'How to Ask', type: 'tip', content: 'Polite: "Excuse me, could you tell me where the station is?" "Excuse me, is there a pharmacy near here?" "Excuse me, how do I get to the museum?" Always start with "Excuse me" — walking up to a stranger and saying "Where is the bank?" can sound rude. If you don\'t understand: "Sorry, could you repeat that?" "Sorry, more slowly please?"' },
          { title: 'Give Directions', type: 'exercise', question: 'Someone asks: "Excuse me, how do I get to the post office?" It\'s two streets away, turn left, then right. Give directions.', answer: '"Sure! Go straight ahead. Take the second street on the left. Then turn right, and the post office is on your right. It\'s next to the bookshop."', answerExplanation: 'Starts with "Sure!" (friendly), gives step-by-step directions, adds a landmark ("next to the bookshop") to help them confirm they\'re in the right place.' },
        ],
        keyTakeaways: ['Always start with "Excuse me" when asking a stranger', 'Go straight, turn left/right, it\'s on the left/right', 'Add landmarks: "It\'s next to..." "It\'s opposite..."'],
      },
      // # ─── Lesson 10: Talking About Your Family ───
      { id: 'a1-speaking-family', title: 'Talking About Your Family', description: 'Describe your family members — who they are and what they do.',
        skill: 'speaking', level: 'A1', duration: 8,
        objectives: ['Name family members in English', 'Describe family members simply', 'Ask about someone\'s family'],
        sections: [
          { title: 'Family Words', type: 'rule', content: 'Parents: mother/mum, father/dad. Siblings: sister, brother. Children: son, daughter. Grandparents: grandmother/grandma, grandfather/grandpa. Others: uncle, aunt, cousin, nephew, niece. In-laws: mother-in-law, father-in-law, brother-in-law, sister-in-law. "Mum" and "Dad" are used when talking about YOUR parents. "Mother" and "Father" are more formal.' },
          { title: 'Describing Family', type: 'tip', content: 'Simple patterns: "I have one brother and two sisters." "My brother is 25. He\'s a teacher." "My mum works in a hospital." "My dad is retired." "I\'m the youngest/oldest in my family." "We are a big/small family." "I\'m an only child." (= no brothers or sisters). Don\'t say: "We are four people in my family." Say: "There are four people in my family."' },
          { title: 'Describe Your Family', type: 'exercise', question: 'Tell someone about your family (how many people, who they are, one detail about each).', answer: '"There are five people in my family — my parents, my two sisters, and me. My dad is a bus driver. My mum works in a school. My older sister is 28 and she lives in London. My younger sister is 19 and she\'s a university student."', answerExplanation: 'Gives the number, names each person, adds one interesting detail per person. This is the perfect family description at A1 level.' },
        ],
        keyTakeaways: ['Mum/Dad (casual) vs Mother/Father (formal)', '"There are [number] people in my family"', '"I\'m an only child" = no brothers or sisters'],
      },
      // # ─── Lesson 11: Describing Your Home ───
      { id: 'a1-speaking-home', title: 'Describing Your Home', description: 'Talk about where you live — rooms, furniture, and your neighbourhood.',
        skill: 'speaking', level: 'A1', duration: 8,
        objectives: ['Name rooms and common furniture', 'Use "there is/there are" to describe your home', 'Describe your neighbourhood simply'],
        sections: [
          { title: 'There Is / There Are', type: 'rule', content: 'Singular: "There is a kitchen." "There\'s a balcony." Plural: "There are two bedrooms." "There are three chairs." Negative: "There isn\'t a garden." "There aren\'t any windows." Question: "Is there a lift?" "Are there any shops nearby?" Rooms: kitchen, living room, bedroom, bathroom, dining room, hallway, balcony, garden.' },
          { title: 'Useful Descriptions', type: 'tip', content: '"I live in a flat/apartment." (not a house). "I live on the third floor." "It\'s small but cosy." "It\'s big and modern." "My favourite room is the kitchen because I love cooking." "The living room has a big sofa and a TV." "My neighbourhood is quiet/noisy/friendly."' },
          { title: 'Describe Your Home', type: 'exercise', question: 'Describe your home to a new friend — what type, how many rooms, your favourite room.', answer: '"I live in a small flat in the city centre. There are four rooms — a bedroom, a living room, a kitchen, and a bathroom. My favourite room is the living room because there\'s a big window with a nice view. It\'s small but I like it."', answerExplanation: 'Uses "there are" correctly, names rooms, gives a reason for the favourite, adds a positive ending. Natural and conversational.' },
        ],
        keyTakeaways: ['"There is" (singular) / "There are" (plural)', 'Flat (British) = Apartment (American)', 'Add opinions: "It\'s small but cosy" / "I like it because..."'],
      },
      // # ─── Lesson 12: Talking About Daily Routines ───
      { id: 'a1-speaking-daily-routine', title: 'Talking About Daily Routines', description: 'Describe what you do every day — from morning to night.',
        skill: 'speaking', level: 'A1', duration: 8,
        objectives: ['Use present simple for habits and routines', 'Use time expressions (every day, usually, always)', 'Describe a typical day'],
        sections: [
          { title: 'Routine Verbs', type: 'rule', content: 'Morning: wake up, get up, have a shower, get dressed, have breakfast, leave home. Day: go to work/school, start work, have lunch, finish work. Evening: get home, cook dinner, watch TV, read a book, go to bed. Time words: always, usually, often, sometimes, rarely, never. "I usually wake up at 7." "I always have coffee for breakfast." "I sometimes go to the gym."' },
          { title: 'Frequency Order', type: 'tip', content: 'Always (100%) → Usually (90%) → Often (70%) → Sometimes (50%) → Rarely (10%) → Never (0%). These go BEFORE the main verb: "I usually eat lunch at 12." But AFTER "be": "I am always tired on Mondays." "She is never late."' },
          { title: 'Describe Your Morning', type: 'exercise', question: 'Describe your typical morning from waking up to leaving home.', answer: '"I usually wake up at 6:30. I have a shower and get dressed. Then I have breakfast — usually toast and coffee. I sometimes check my phone while I eat. I leave home at about 7:45."', answerExplanation: 'Uses present simple for routines, includes frequency words (usually, sometimes), gives specific times, uses natural connectors (then, while).' },
        ],
        keyTakeaways: ['Present simple for habits: "I wake up at 7" (not "I am waking up")','Frequency words go before the verb but after "be"', '"Have breakfast/lunch/dinner" — not "take" or "eat" (though "eat" is also OK)'],
      },
      // # ─── Lesson 13: Hobbies & Free Time ───
      { id: 'a1-speaking-hobbies', title: 'Hobbies & Free Time', description: 'Talk about what you enjoy doing in your spare time.',
        skill: 'speaking', level: 'A1', duration: 8,
        objectives: ['Use "I like/love/enjoy + -ing"', 'Ask others about their hobbies', 'Describe how often you do activities'],
        sections: [
          { title: 'Like + -ing', type: 'rule', content: '"I like swimming." "I love cooking." "I enjoy reading." "I don\'t like running." "I hate waking up early." Like/love/enjoy/hate + verb-ING. Questions: "What do you like doing in your free time?" "Do you have any hobbies?" "What do you do at weekends?" Answers: "I like playing football." "I enjoy watching movies." "I go swimming twice a week."' },
          { title: 'How Often?', type: 'tip', content: 'Every day. Twice a week. Three times a month. At weekends (British) / On weekends (American). In my free time. After work/school. "I play tennis twice a week." "I go to the cinema about once a month." "I read every night before bed."' },
          { title: 'Talk About Your Hobbies', type: 'exercise', question: 'Tell someone about 3 things you do in your free time and how often.', answer: '"In my free time, I like playing video games — I play every day after work. I also enjoy cooking. I try new recipes at weekends. And I go running about twice a week, usually in the morning."', answerExplanation: 'Three hobbies with frequency: every day, at weekends, twice a week. Uses "I like + -ing" and "I enjoy + -ing" naturally.' },
        ],
        keyTakeaways: ['Like/love/enjoy/hate + verb-ING: "I like swimming"', '"What do you like doing in your free time?" is the standard question', 'Add frequency: every day, twice a week, at weekends'],
      },
      // # ─── Lesson 14: Weather Conversations ───
      { id: 'a1-speaking-weather', title: 'Weather Conversations', description: 'Talk about the weather — the world\'s favourite small talk topic.',
        skill: 'speaking', level: 'A1', duration: 8,
        objectives: ['Describe today\'s weather', 'Use weather adjectives correctly', 'Start conversations with weather small talk'],
        sections: [
          { title: 'Weather Words', type: 'rule', content: 'It\'s sunny / cloudy / rainy / windy / snowy / foggy / stormy. It\'s hot / warm / cool / cold / freezing. "It\'s raining." "It\'s snowing." Temperature: "It\'s 25 degrees." "It\'s minus 5." Asking: "What\'s the weather like today?" "Is it going to rain?" "What\'s the forecast?" Don\'t say: "How is the weather?" Say: "What\'s the weather like?"' },
          { title: 'Weather as Small Talk', type: 'tip', content: 'In English-speaking countries (especially the UK!), weather is the #1 conversation starter: "Lovely day, isn\'t it?" "Terrible weather we\'re having!" "I can\'t believe how hot it is!" Weather small talk is NOT about weather — it\'s about being friendly. You don\'t need a deep conversation. Just agree and smile.' },
          { title: 'Respond to Weather Small Talk', type: 'exercise', question: 'Someone says: "Beautiful day today, isn\'t it?" How do you respond?', answer: '"Yes, it really is! It\'s so nice and sunny. I hope it stays like this for the weekend."', answerExplanation: 'Agrees with enthusiasm, adds a small detail (sunny), looks forward (weekend). This keeps the small talk going naturally. Even "Yes, lovely!" on its own would be fine.' },
        ],
        keyTakeaways: ['"What\'s the weather like?" — not "How is the weather?"', 'Weather small talk = being friendly, not actually discussing weather', 'It\'s + adjective: "It\'s sunny." It\'s + -ing: "It\'s raining."'],
      },
      // # ─── Lesson 15: At the Doctor ───
      { id: 'a1-speaking-doctor', title: 'At the Doctor', description: 'Describe symptoms, ask questions, and understand basic medical advice.',
        skill: 'speaking', level: 'A1', duration: 10,
        objectives: ['Describe simple health problems', 'Use "I have" and "I feel" for symptoms', 'Understand common doctor phrases'],
        sections: [
          { title: 'Describing Symptoms', type: 'rule', content: 'I have: a headache, a stomachache, a sore throat, a cough, a cold, a fever, a temperature, a toothache. I feel: sick, dizzy, tired, weak. My [body part] hurts: "My back hurts." "My leg hurts." It hurts here. (point to the place). "I\'ve been sick for two days." "It started yesterday." "I think I have a cold."' },
          { title: 'Making an Appointment', type: 'tip', content: '"I\'d like to make an appointment, please." "I need to see a doctor." "Is it possible to see someone today?" "It\'s urgent / It\'s not urgent." At the pharmacy: "Do you have anything for a headache?" "Can I buy this without a prescription?" In emergencies: Call 999 (UK), 911 (US), 000 (Australia) or go to A&E (Accident & Emergency) / ER (Emergency Room).' },
          { title: 'Describe Your Problem', type: 'exercise', question: 'You have a bad headache and feel dizzy. It started this morning. Tell the doctor.', answer: '"I have a really bad headache and I feel dizzy. It started this morning when I woke up. I also feel a bit sick. I\'ve taken some paracetamol but it hasn\'t helped."', answerExplanation: 'Describes symptoms clearly (headache, dizzy, sick), says when it started (this morning), mentions what you\'ve tried (paracetamol). This helps the doctor understand your situation quickly.' },
        ],
        keyTakeaways: ['"I have a headache" — not "I am headache"', '"My [body part] hurts" or "I have a pain in my [body part]"', 'Tell the doctor: what, when it started, what you\'ve tried'],
      },
      // # ─── Lesson 16: Making Phone Calls ───
      { id: 'a1-speaking-phone-calls', title: 'Making Phone Calls', description: 'Answer the phone, leave messages, and handle simple calls.',
        skill: 'speaking', level: 'A1', duration: 8,
        objectives: ['Answer the phone politely', 'Ask to speak to someone', 'Leave a simple message'],
        sections: [
          { title: 'Phone Phrases', type: 'rule', content: 'Answering: "Hello?" (informal) "Good morning, [company name], how can I help?" (formal). Asking for someone: "Can I speak to [name], please?" "Is [name] there?" (informal). Person not available: "I\'m sorry, she\'s not here right now." "Can I take a message?" "Can I leave a message?" Leaving a message: "Could you tell her that [your name] called?" "Could you ask him to call me back?" "My number is..."' },
          { title: 'Phone ≠ Face-to-Face', type: 'tip', content: 'Phone calls are harder than face-to-face conversation because: you can\'t see body language or lip movements, connections can be bad, people speak faster on the phone. Tips: speak slowly and clearly. Don\'t be afraid to say: "Sorry, could you repeat that?" "Sorry, I didn\'t catch that." "Could you speak more slowly, please?" "Could you spell that for me?" These are 100% normal — even native speakers say them.' },
          { title: 'Leave a Message', type: 'exercise', question: 'You call your doctor\'s office. Dr Smith isn\'t available. Leave a message to call you back.', answer: '"Oh, OK. Could I leave a message, please? Could you ask Dr Smith to call me back? My name is Anna Lee. My number is 07745 321 098. Thank you very much."', answerExplanation: 'Polite (Could I... Could you...), gives full name and number clearly, says thank you. Clear and complete — the receptionist has everything they need.' },
        ],
        keyTakeaways: ['"Can I speak to [name], please?" to ask for someone', '"Could you repeat that?" is always OK — phone calls are hard', 'When leaving a message: your name + your number + what you need'],
      },
      // # ─── Lesson 17: Classroom Language ───
      { id: 'a1-speaking-classroom', title: 'Classroom Language', description: 'Participate in class — ask questions, request help, and work with classmates.',
        skill: 'speaking', level: 'A1', duration: 8,
        objectives: ['Ask your teacher for help', 'Ask classmates to work together', 'Use polite classroom phrases'],
        sections: [
          { title: 'Asking Your Teacher', type: 'rule', content: '"Excuse me, could you repeat that, please?" "Sorry, I don\'t understand." "What does [word] mean?" "How do you spell [word]?" "How do you pronounce this?" "Can I go to the bathroom/toilet?" "Could you speak more slowly, please?" "Is this correct?" "What page are we on?"' },
          { title: 'Working With Classmates', type: 'tip', content: '"Shall we work together?" "What do you think?" "I agree." / "I disagree." "I\'m not sure." "How about you?" "Do you want to go first?" "It\'s your turn." "Sorry, what did you say?" Remember: making mistakes is OK. Every mistake is a learning opportunity. Don\'t be embarrassed — be curious.' },
          { title: 'Ask for Help', type: 'exercise', question: 'Your teacher said a word you don\'t understand. How do you ask?', answer: '"Excuse me, I\'m sorry, but what does \'procrastinate\' mean? Could you explain it, please?"', answerExplanation: 'Polite opening (Excuse me), admits confusion (I\'m sorry but...), specific question (what does X mean), adds please. Teachers love when students ask — it shows you\'re paying attention.' },
        ],
        keyTakeaways: ['"What does [word] mean?" to learn new vocabulary', '"Could you repeat that?" and "Could you speak more slowly?" are always OK', 'Asking questions shows you\'re learning — never be embarrassed'],
      },
      // # ─── Lesson 18: Talking About Your Job ───
      { id: 'a1-speaking-job', title: 'Talking About Your Job', description: 'Describe what you do for work — or what you study.',
        skill: 'speaking', level: 'A1', duration: 8,
        objectives: ['Say what your job is', 'Describe basic work activities', 'Ask others about their work'],
        sections: [
          { title: 'Job Phrases', type: 'rule', content: '"I\'m a teacher / nurse / engineer / student / chef / driver." "I work in a hospital / an office / a school / a restaurant." "I work for [company name]." "I work with computers / children / animals." Questions: "What do you do?" (= What is your job?) "Where do you work?" "Do you like your job?" Don\'t say: "I am teacher." Say: "I am A teacher." (always use a/an before jobs).' },
          { title: 'Describing Work', type: 'tip', content: '"I start work at 9 and finish at 5." "I work Monday to Friday." "I work shifts / I work nights." "I\'m self-employed." (= I work for myself) "I\'m looking for a job." "I\'m between jobs." (= polite way to say unemployed). "I\'m retired." For students: "I\'m studying [subject] at [university]." "I\'m in my second year."' },
          { title: 'Describe Your Work', type: 'exercise', question: 'Tell someone about your job or studies: what you do, where, and if you like it.', answer: '"I\'m a software developer. I work for a small company in the city centre. I write code for mobile apps. I work from home three days a week. I really like my job because every day is different."', answerExplanation: 'Job title, company, what you do, where, opinion. Natural and conversational with good detail for A1 level.' },
        ],
        keyTakeaways: ['"I\'m A teacher" — always use a/an before job titles', '"What do you do?" means "What is your job?"', '"I\'m between jobs" is a polite way to say unemployed'],
      },
      // # ─── Lesson 19: Describing People ───
      { id: 'a1-speaking-describing-people', title: 'Describing People', description: 'Describe how people look and their personality — for friends, family, or finding someone.',
        skill: 'speaking', level: 'A1', duration: 8,
        objectives: ['Describe physical appearance', 'Describe personality with simple adjectives', 'Use "has" and "is" correctly for descriptions'],
        sections: [
          { title: 'Appearance: Has vs Is', type: 'rule', content: 'Use IS for: height, build, general appearance. "She is tall / short / medium height." "He is thin / slim / overweight." "She is beautiful / handsome / good-looking." Use HAS for: features. "She has long hair / short hair / curly hair / straight hair." "He has blue eyes / brown eyes / green eyes." "She has glasses." "He has a beard / a moustache."' },
          { title: 'Personality', type: 'tip', content: 'Positive: kind, friendly, funny, smart, creative, generous, patient, honest, hard-working. Negative (be careful!): shy, quiet, lazy, stubborn, impatient. "He\'s really friendly." "She\'s very kind." "He can be a bit stubborn sometimes." When describing someone to their face, use positive words! Use negative words only when talking ABOUT someone (and even then, be kind).' },
          { title: 'Describe Someone', type: 'exercise', question: 'Describe your best friend — what do they look like and what are they like as a person?', answer: '"My best friend is called Sam. He\'s tall and has short dark hair and brown eyes. He wears glasses. He\'s really funny — he always makes me laugh. He\'s also very kind and generous. He\'s a bit shy with people he doesn\'t know, but when you know him, he\'s great."', answerExplanation: 'Uses IS for general (tall), HAS for features (hair, eyes), personality adjectives (funny, kind, generous, shy), softener "a bit" for the negative trait.' },
        ],
        keyTakeaways: ['IS for height/build: "She is tall." HAS for features: "She has blue eyes."', 'Use positive adjectives freely; soften negatives with "a bit"', '"What does she look like?" = appearance. "What is she like?" = personality.'],
      },
      // # ─── Lesson 20: Expressing Feelings & Emotions ───
      { id: 'a1-speaking-feelings', title: 'Expressing Feelings & Emotions', description: 'Say how you feel and ask others about their feelings.',
        skill: 'speaking', level: 'A1', duration: 8,
        objectives: ['Use "I feel" and "I am" with emotions', 'Name common feelings', 'Respond when someone shares their feelings'],
        sections: [
          { title: 'Feeling Words', type: 'rule', content: 'Positive: happy, excited, grateful, proud, relaxed, confident, loved. Negative: sad, angry, worried, scared, nervous, lonely, stressed, bored, tired, disappointed. "I\'m happy." = "I feel happy." Both are correct. "I\'m a bit nervous about the exam." "I feel really tired today." "I\'m so excited about the trip!"' },
          { title: 'Responding to Feelings', type: 'tip', content: 'Happy news: "That\'s great!" "I\'m so happy for you!" "Congratulations!" Sad news: "I\'m sorry to hear that." "That\'s terrible." "Are you OK?" Worried: "Don\'t worry, it\'ll be fine." "I\'m sure everything will be OK." Never say: "You shouldn\'t feel that way." Let people feel what they feel. Listening is more important than giving advice.' },
          { title: 'Respond to These', type: 'exercise', question: 'Your friend says: (a) "I got the job!" (b) "My dog is very sick." How do you respond?', answer: '(a) "Oh, that\'s amazing! Congratulations! I\'m so happy for you! When do you start?" (b) "Oh no, I\'m really sorry to hear that. Are you OK? I hope your dog gets better soon."', answerExplanation: '(a) shows genuine excitement and asks a follow-up question. (b) shows empathy, checks on the friend, and offers hope. Both responses focus on the friend, not yourself.' },
        ],
        keyTakeaways: ['"I\'m happy" and "I feel happy" both work', 'Good news → "That\'s great!" Bad news → "I\'m sorry to hear that"', 'Listening is more important than giving advice'],
      },
      // # ─── Lesson 21: Making Plans & Arrangements ───
      { id: 'a1-speaking-making-plans', title: 'Making Plans & Arrangements', description: 'Suggest activities, agree on times, and make plans with friends.',
        skill: 'speaking', level: 'A1', duration: 8,
        objectives: ['Suggest activities using "Shall we...?" and "Let\'s..."', 'Agree and disagree with suggestions', 'Arrange a time and place'],
        sections: [
          { title: 'Suggesting', type: 'rule', content: '"Shall we go to the cinema?" "Let\'s have lunch together." "Do you want to go for a walk?" "How about meeting on Saturday?" "What about trying that new restaurant?" Agreeing: "Yes, great idea!" "Sounds good!" "Sure, why not?" "I\'d love to!" Disagreeing: "Sorry, I can\'t on Saturday." "I\'m busy that day." "How about Sunday instead?"' },
          { title: 'Confirming Plans', type: 'tip', content: 'Always confirm: time + place + how to get there. "So, Saturday at 2pm at the café near the station?" "I\'ll meet you there." "See you at 2!" "Let me know if anything changes." "I\'ll text you when I\'m leaving." These confirmations prevent confusion and show you\'re reliable.' },
          { title: 'Make a Plan', type: 'exercise', question: 'Invite a friend to do something this weekend. Agree on a time and place.', answer: '"Hey, are you free this weekend? Do you want to go for coffee on Saturday? How about that new café on King Street — they have amazing cake! Shall we say 11 o\'clock? Great, see you there!"', answerExplanation: 'Checks availability (are you free?), suggests activity (coffee), place (new café), time (11 o\'clock), confirms (see you there). Natural and complete.' },
        ],
        keyTakeaways: ['"Let\'s..." "Shall we...?" "Do you want to...?" to suggest', '"Sounds good!" to agree. "Sorry, I can\'t" to decline politely.', 'Always confirm: time + place + "See you there!"'],
      },
      // # ─── Lesson 22: At a Restaurant ───
      { id: 'a1-speaking-restaurant', title: 'At a Restaurant', description: 'Handle the full restaurant experience — from booking to paying.',
        skill: 'speaking', level: 'A1', duration: 10,
        objectives: ['Book a table by phone', 'Order a full meal (starter, main, dessert)', 'Handle special requests and the bill'],
        sections: [
          { title: 'Restaurant Phrases', type: 'rule', content: 'Booking: "I\'d like to book a table for two, please." "For Saturday evening at 7 o\'clock." Arriving: "We have a reservation under [name]." "A table for two, please." Ordering: "Could we see the menu, please?" "I\'ll have the chicken, please." "What would you recommend?" Special requests: "I\'m vegetarian / vegan." "I\'m allergic to nuts." "No onions, please." "Could I have it without cheese?"' },
          { title: 'Dealing with Problems', type: 'tip', content: 'Polite complaints: "Excuse me, this isn\'t what I ordered." "I\'m sorry, but this is cold." "Could I have a clean fork, please?" Don\'t say: "This is terrible!" Instead: "I\'m sorry, but I\'m not happy with this. Could you help?" Being polite gets better results than being angry. In the UK, many people don\'t complain at all — they just never go back!' },
          { title: 'Order a Meal', type: 'exercise', question: 'You\'re at a restaurant with a friend. Order a starter, main, and ask about dessert.', answer: '"For starters, I\'ll have the tomato soup, please. And for my main, could I have the grilled salmon with vegetables? And could we see the dessert menu later? Thank you."', answerExplanation: 'Organised (starter, main, dessert request), polite (please, could I, thank you), natural (I\'ll have, could I have). Exactly what a native speaker would say.' },
        ],
        keyTakeaways: ['"I\'ll have the..." is the most natural way to order', 'Mention allergies clearly: "I\'m allergic to..."', '"Could we have the bill, please?" when you\'re finished'],
      },
      // # ─── Lesson 23: Saying Goodbye & Thank You ───
      { id: 'a1-speaking-goodbye', title: 'Saying Goodbye & Thank You', description: 'End conversations naturally — with the right goodbye for the right situation.',
        skill: 'speaking', level: 'A1', duration: 8,
        objectives: ['Use formal and informal goodbyes', 'Thank people in different ways', 'End conversations naturally without being abrupt'],
        sections: [
          { title: 'Goodbye Phrases', type: 'rule', content: 'Formal: "Goodbye." "It was nice meeting you." "Have a good day." "Take care." Informal: "Bye!" "See you later!" "See you soon!" "Catch you later!" "Take it easy!" Specific: "See you on Monday!" "See you tomorrow!" "Have a good weekend!" "Good night!" (only when going to bed or leaving at night).' },
          { title: 'Thank You Levels', type: 'tip', content: 'Casual: "Thanks!" "Cheers!" (British). Standard: "Thank you." "Thank you very much." Strong: "Thank you so much, I really appreciate it." "That\'s so kind of you." Responding to thanks: "You\'re welcome." "No problem." "Don\'t mention it." "My pleasure." "Any time." "No worries." (Australian/British informal).' },
          { title: 'End a Conversation', type: 'exercise', question: 'You\'ve been chatting with a new colleague. It\'s time to go back to work. End the conversation naturally.', answer: '"Well, it was really nice talking to you! I should probably get back to work. Let\'s have coffee sometime! See you around!"', answerExplanation: 'Positive comment (nice talking to you), reason for leaving (get back to work), future suggestion (coffee sometime), friendly goodbye (see you around). Not abrupt — wraps up warmly.' },
        ],
        keyTakeaways: ['"See you later" is the most common informal goodbye', '"Thank you so much" for strong gratitude', 'End conversations with a positive comment before the goodbye'],
      },
    ],
  },
  {
    id: 'a2-speaking',
    name: 'A2: Speaking Skills',
    description: 'Handle everyday conversations with growing confidence — tell stories, give opinions, and solve problems.',
    icon: '🗣️',
    lessons: [
      // # ─── Lesson 1: Telling a Story in the Past ───
      { id: 'a2-speaking-past-stories', title: 'Telling a Story in the Past', description: 'Tell simple stories about things that happened — holidays, funny moments, experiences.',
        skill: 'speaking', level: 'A2', duration: 10,
        objectives: ['Use past simple to tell stories', 'Sequence events with time words', 'Add details to make stories interesting'],
        sections: [
          { title: 'Story Structure', type: 'rule', content: 'Setting: "Last summer, I went to Italy with my friend." Events: "We visited Rome and Florence. We ate amazing pizza. One day, we got lost in the old town." Highlight: "We found a tiny restaurant where nobody spoke English. The food was the best I\'ve ever had!" Ending: "It was an amazing trip. I want to go back next year." Time connectors: first, then, after that, later, finally, in the end.' },
          { title: 'Making Stories Interesting', type: 'tip', content: 'Add reactions: "I was so surprised!" "It was hilarious!" "I couldn\'t believe it!" Add details: not "We ate food" but "We ate the most amazing fresh pasta." Use direct speech: "My friend said: \'Let\'s go this way!\' I said: \'Are you sure?\'" Speed up exciting parts, slow down for the important moment.' },
          { title: 'Tell a Story', type: 'exercise', question: 'Tell a short story about something funny or surprising that happened to you.', answer: '"Last month, I was cooking dinner for my friends. I wanted to make curry, so I added some chilli. But I added WAY too much! When my friends tasted it, their faces went completely red. My friend said: \'Are you trying to kill us?\' We all laughed and ordered pizza instead. It was hilarious!"', answerExplanation: 'Has all the elements: setting (last month, cooking), event sequence, highlight (too much chilli), direct speech (Are you trying to kill us?), reaction (hilarious), resolution (ordered pizza).' },
        ],
        keyTakeaways: ['Structure: setting → events → highlight → ending', 'Time words connect events: first, then, after that, finally', 'Add reactions and details to make stories come alive'],
      },
      // # ─── Lesson 2: Making Suggestions ───
      { id: 'a2-speaking-suggestions', title: 'Making Suggestions', description: 'Suggest ideas, activities, and solutions naturally.',
        skill: 'speaking', level: 'A2', duration: 8,
        objectives: ['Use different structures to suggest ideas', 'Respond to suggestions positively and negatively', 'Make alternative suggestions when declining'],
        sections: [
          { title: 'Suggestion Phrases', type: 'rule', content: '"Why don\'t we go to the beach?" "How about going to the cinema?" "What about trying that new restaurant?" "We could visit the museum." "Let\'s go for a walk." "Have you thought about taking the bus?" "Maybe we should leave earlier." "I suggest we book in advance." Stronger: "I think we should..." "I really think you should..."' },
          { title: 'Responding', type: 'tip', content: 'Accepting: "That\'s a great idea!" "Sounds perfect!" "Yes, let\'s do that!" "Good thinking!" Declining politely: "That sounds nice, but I\'d rather..." "I\'m not sure about that. How about... instead?" "Maybe, but what about...?" NEVER just say "No." Always offer an alternative or a reason. "I\'d rather stay in tonight — I\'m really tired. How about tomorrow?"' },
          { title: 'Suggest & Respond', type: 'exercise', question: 'Your friend suggests going hiking on Saturday, but it\'s going to rain. Decline politely and suggest something else.', answer: '"That sounds fun, but I checked the weather and it\'s going to rain all day on Saturday. How about we go to that new escape room in town instead? Or we could go hiking on Sunday — the forecast looks much better!"', answerExplanation: 'Acknowledges the suggestion (sounds fun), gives a reason (rain), offers two alternatives (escape room / Sunday hike). Polite, helpful, and natural.' },
        ],
        keyTakeaways: ['"How about...?" "Why don\'t we...?" "We could..." for suggestions', 'Always give a reason AND an alternative when declining', '"That sounds nice, but..." is a polite way to disagree'],
      },
      // # ─── Lesson 3: Agreeing & Disagreeing Politely ───
      { id: 'a2-speaking-agreeing-disagreeing', title: 'Agreeing & Disagreeing Politely', description: 'Share your view without starting an argument — the art of polite English.',
        skill: 'speaking', level: 'A2', duration: 10,
        objectives: ['Agree with enthusiasm and sincerity', 'Disagree politely without offending', 'Partially agree to show nuance'],
        sections: [
          { title: 'Agreement Phrases', type: 'rule', content: 'Strong agreement: "Absolutely!" "Exactly!" "I couldn\'t agree more." "You\'re absolutely right." Agreement: "I agree." "I think so too." "That\'s true." "Good point." Partial agreement: "I see what you mean, but..." "You have a point, but..." "That\'s partly true, but..." "I agree up to a point, but..."' },
          { title: 'Polite Disagreement', type: 'rule', content: 'Soft: "I\'m not sure I agree." "I see it differently." "I\'m not so sure about that." Medium: "I understand what you mean, but I think..." "That\'s one way to look at it, but..." "I take your point, but..." Avoid: "You\'re wrong." "That\'s stupid." "No!" (too direct and rude in English). Always start with something positive before disagreeing.' },
          { title: 'Respond to This', type: 'exercise', question: 'Someone says: "I think English is the easiest language to learn." You partially disagree. Respond.', answer: '"I see what you mean — English grammar is quite simple compared to some languages. But I think pronunciation is really difficult because the spelling and the sounds are so different. And there are SO many phrasal verbs! So I\'d say it\'s easy to start, but hard to master."', answerExplanation: 'Acknowledges their point (grammar is simple), gives reasons for disagreeing (pronunciation, spelling, phrasal verbs), reaches a balanced conclusion (easy to start, hard to master). Nobody\'s feelings are hurt.' },
        ],
        keyTakeaways: ['"I see what you mean, but..." is the perfect partial disagreement', 'Never say "You\'re wrong" — always start with something positive', 'Give reasons for your disagreement, not just "I disagree"'],
      },
      // # ─── Lesson 4: Describing Experiences ───
      { id: 'a2-speaking-experiences', title: 'Describing Experiences', description: 'Talk about things you\'ve done — travel, work, life events.',
        skill: 'speaking', level: 'A2', duration: 10,
        objectives: ['Use present perfect for experiences ("Have you ever...?")', 'Describe experiences with details and opinions', 'Ask follow-up questions about experiences'],
        sections: [
          { title: 'Have You Ever...?', type: 'rule', content: 'Present perfect for life experiences: "Have you ever been to Japan?" → "Yes, I have." / "No, I haven\'t." "Have you ever tried sushi?" "Have you ever met a famous person?" "Have you ever lived abroad?" After "yes", switch to past simple for details: "Yes, I went to Japan last year. I visited Tokyo and Kyoto. It was amazing!"' },
          { title: 'Adding Colour', type: 'tip', content: 'Don\'t just say "Yes, I have." Add the story: "Yes! I went bungee jumping in New Zealand. I was absolutely terrified but it was the best thing I\'ve ever done." Useful phrases: "It was the best/worst thing I\'ve ever done." "I\'ll never forget it." "I\'d love to do it again." "I wouldn\'t do it again — once was enough!"' },
          { title: 'Have You Ever...?', type: 'exercise', question: 'Answer with details: "Have you ever been lost in a foreign country?"', answer: '"Yes, I have! I got lost in Barcelona a few years ago. I was trying to find my hotel but my phone died. I walked around for about an hour. Finally, I asked someone for help and they walked me all the way to my hotel. They were so kind! I\'ll never forget it."', answerExplanation: 'Starts with present perfect (I have), switches to past simple for the story (got lost, walked, asked), adds emotion (so kind), memorable ending (I\'ll never forget it).' },
        ],
        keyTakeaways: ['"Have you ever...?" + past participle for experiences', 'Answer "Yes, I have" then switch to past simple for details', 'Add feelings and opinions to make experiences come alive'],
      },
      // # ─── Lesson 5: Making Comparisons in Speech ───
      { id: 'a2-speaking-comparisons', title: 'Making Comparisons in Speech', description: 'Compare people, places, things, and experiences in conversation.',
        skill: 'speaking', level: 'A2', duration: 8,
        objectives: ['Use comparatives and superlatives naturally', 'Compare with "as...as" and "not as...as"', 'Give opinions using comparisons'],
        sections: [
          { title: 'Comparison Patterns', type: 'rule', content: 'Comparative (-er / more): "Tokyo is bigger than London." "The film was more interesting than the book." Superlative (-est / most): "That was the best meal I\'ve ever had." "She\'s the most talented person I know." Equal: "The test was as hard as I expected." Not equal: "The sequel wasn\'t as good as the original."' },
          { title: 'Natural Comparison Phrases', type: 'tip', content: '"much/far/a lot" for big differences: "Tokyo is much bigger than my city." "a bit/slightly/a little" for small differences: "This coffee is slightly better than yesterday\'s." Idiomatic comparisons: "It\'s nothing like what I expected." "It\'s way better than I thought." "There\'s no comparison — this one is clearly better."' },
          { title: 'Compare These', type: 'exercise', question: 'Compare two cities you know — which is better to live in and why?', answer: '"I think Bangkok is more exciting than my hometown because there\'s so much to do. The food is much cheaper and way more delicious. But my hometown is quieter and safer, and the air is a lot cleaner. For young people, Bangkok is definitely better, but for families, I\'d say my hometown is more suitable."', answerExplanation: 'Uses comparatives (more exciting, cheaper, quieter, safer, cleaner), intensifiers (much, way, a lot, definitely), balanced view (both have advantages).' },
        ],
        keyTakeaways: ['Add "much/a lot" for big differences, "a bit/slightly" for small ones', '"Not as good as" is softer than "worse than"', 'Good comparisons are balanced — show both sides'],
      },
      // # ─── Lesson 6: Giving & Asking for Opinions ───
      { id: 'a2-speaking-opinions', title: 'Giving & Asking for Opinions', description: 'Share what you think and ask others what they think.',
        skill: 'speaking', level: 'A2', duration: 8,
        objectives: ['Express opinions with "I think/believe/feel"', 'Ask for other people\'s opinions', 'Support opinions with reasons'],
        sections: [
          { title: 'Opinion Phrases', type: 'rule', content: 'Giving: "I think..." "I believe..." "In my opinion,..." "I feel that..." "If you ask me,..." "Personally, I think..." "As far as I\'m concerned,..." Asking: "What do you think?" "What\'s your opinion on...?" "How do you feel about...?" "Do you agree?" "What do you reckon?" (British informal)' },
          { title: 'Opinions Need Reasons', type: 'tip', content: 'Weak: "I think dogs are better than cats." Strong: "I think dogs are better than cats because they\'re more loyal, they encourage you to exercise, and they\'re always happy to see you." Pattern: opinion + because + reason 1 + reason 2. Hedging (making it softer): "I could be wrong, but..." "I\'m not an expert, but I think..." "It seems to me that..."' },
          { title: 'Give Your Opinion', type: 'exercise', question: 'What do you think about social media? Give your opinion with 2 reasons.', answer: '"Personally, I think social media has good and bad sides. On one hand, it\'s great for staying in touch with friends, especially if they live far away. On the other hand, I feel that people spend too much time scrolling instead of talking face to face. So I think it\'s good in moderation."', answerExplanation: 'Balanced opinion (good and bad), structured (on one hand/other hand), two reasons (staying in touch/too much time), conclusion (good in moderation). Thoughtful and natural.' },
        ],
        keyTakeaways: ['"I think..." + reason is the most common pattern', '"What do you think?" to ask others — not "What is your thinking?"', 'Always give reasons — unsupported opinions sound weak'],
      },
      // # ─── Lesson 7: Making Polite Requests ───
      { id: 'a2-speaking-polite-requests', title: 'Making Polite Requests', description: 'Ask for things politely — from small favours to big requests.',
        skill: 'speaking', level: 'A2', duration: 8,
        objectives: ['Use "could you", "would you mind", and "I was wondering"', 'Match politeness level to the situation', 'Respond to requests appropriately'],
        sections: [
          { title: 'Politeness Scale', type: 'rule', content: 'Direct (close friends): "Pass me the salt." "Open the window." Polite (colleagues, strangers): "Could you pass the salt, please?" "Would you mind opening the window?" Very polite (big requests, authority): "I was wondering if you could help me." "Would it be possible to change my appointment?" "I\'d really appreciate it if you could..." The bigger the request, the more polite you should be.' },
          { title: 'Would You Mind...?', type: 'tip', content: '"Would you mind + -ing?" = very polite request. "Would you mind closing the door?" "Would you mind helping me with this?" CAREFUL with answers: "Would you mind...?" → "No, not at all." (= yes, I will do it). "No, of course not." "Would you mind...?" → "Actually, I\'m a bit busy right now." (= polite refusal). Don\'t say "Yes" to agree — it means "Yes, I DO mind" = refusal!' },
          { title: 'Make These Requests', type: 'exercise', question: 'Make polite requests: (a) Ask a colleague to help you move a desk. (b) Ask your teacher for an extension on your homework.', answer: '(a) "Hi, I was wondering if you could help me move this desk? It\'s a bit too heavy for one person. I\'d really appreciate it." (b) "Excuse me, would it be possible to get an extension on the homework? I\'ve been ill this week and I haven\'t been able to finish it. I\'m sorry for the inconvenience."', answerExplanation: '(a) uses "I was wondering" for politeness, gives a reason (too heavy), adds appreciation. (b) uses "would it be possible" for a bigger request, gives a genuine reason (illness), apologises.' },
        ],
        keyTakeaways: ['Bigger request = more polite language needed', '"Would you mind...?" — answer "No, not at all" to AGREE', '"I was wondering if you could..." is the most polite request form'],
      },
      // # ─── Lesson 8: Talking About Future Plans ───
      { id: 'a2-speaking-future-plans', title: 'Talking About Future Plans', description: 'Discuss what you\'re going to do — tonight, this weekend, next year.',
        skill: 'speaking', level: 'A2', duration: 8,
        objectives: ['Use "going to" for plans and intentions', 'Use "will" for decisions and predictions', 'Talk about arranged future events'],
        sections: [
          { title: 'Going To vs Will', type: 'rule', content: 'Going to (planned before speaking): "I\'m going to visit my parents this weekend." "She\'s going to start a new job in September." Will (decided NOW, predictions, offers): "I\'ll have the chicken, please." (decision now) "I think it\'ll rain tomorrow." (prediction) "I\'ll help you carry that." (offer). Present continuous (arranged/booked): "I\'m meeting Tom at 3." "We\'re flying to Paris on Friday." (tickets bought)' },
          { title: 'Talking About Your Plans', type: 'tip', content: 'Short-term: "What are you doing tonight?" "I\'m going to watch a movie." Medium-term: "What are you doing this summer?" "I\'m going to travel around Europe." Long-term: "What are your plans for the future?" "I\'m going to study engineering." "I want to start my own business one day." Uncertain: "I might go to the beach." "I\'m not sure yet — maybe I\'ll stay home."' },
          { title: 'Discuss Your Plans', type: 'exercise', question: 'Tell someone about your plans for: (a) this evening (b) next month (c) the future.', answer: '(a) "This evening I\'m going to cook dinner and watch Netflix. Nothing exciting!" (b) "Next month I\'m going on holiday to Vietnam. I\'ve already booked the flights." (c) "In the future, I want to move to another country and learn a new language. Maybe Japan — I\'ve always wanted to live there."', answerExplanation: 'Uses going to (planned), present continuous with booked flights (arranged), want to + might (uncertain future). Natural mix of tenses for different certainty levels.' },
        ],
        keyTakeaways: ['Going to = already planned. Will = decided now or predictions.', 'Present continuous for confirmed arrangements: "I\'m meeting Tom at 3"', '"I might..." for uncertain plans, "I\'m going to..." for definite ones'],
      },
      // # ─── Lesson 9: Describing a Place ───
      { id: 'a2-speaking-describing-places', title: 'Describing a Place', description: 'Describe cities, towns, countries, and favourite places vividly.',
        skill: 'speaking', level: 'A2', duration: 8,
        objectives: ['Describe what a place looks like', 'Talk about what you can do there', 'Give opinions about places'],
        sections: [
          { title: 'Place Descriptions', type: 'rule', content: 'Size: big/huge/small/tiny. Atmosphere: lively/quiet/peaceful/busy/crowded/charming. Weather: sunny/hot/cold/tropical/mild. Famous for: "It\'s famous for its food/beaches/history." What to do: "You can visit temples, try street food, and go to night markets." "There\'s a beautiful park in the centre." Recommendation: "You should definitely visit." "I highly recommend it."' },
          { title: 'Organise Your Description', type: 'tip', content: 'Follow this order: 1. Location: "It\'s in the south of Thailand." 2. Size/type: "It\'s a small island." 3. What it looks like: "It has white sand beaches and crystal-clear water." 4. What to do: "You can go snorkelling, hiking, and try amazing seafood." 5. Your opinion: "It\'s the most beautiful place I\'ve ever been to."' },
          { title: 'Describe Your Favourite Place', type: 'exercise', question: 'Describe a place you love — where it is, what it looks like, and why you love it.', answer: '"My favourite place is a small town called Pai in northern Thailand. It\'s in the mountains, about 3 hours from Chiang Mai. It\'s really peaceful and surrounded by green hills and rice fields. There are cute cafés, night markets, and natural hot springs nearby. I love it because it\'s so relaxed — the opposite of a busy city. I always feel happy there."', answerExplanation: 'Location (northern Thailand), size (small town), description (peaceful, green hills), activities (cafés, markets, hot springs), opinion with reason (relaxed, always feel happy). Complete and vivid.' },
        ],
        keyTakeaways: ['Location → Size → Description → Activities → Opinion', '"It\'s famous for..." "You can..." "I recommend..."', 'Add sensory details: what it looks like, sounds like, feels like'],
      },
      // # ─── Lesson 10: At the Hotel ───
      { id: 'a2-speaking-hotel', title: 'At the Hotel', description: 'Check in, ask about facilities, and handle problems at hotels.',
        skill: 'speaking', level: 'A2', duration: 8,
        objectives: ['Check in and check out smoothly', 'Ask about hotel facilities and services', 'Report problems politely'],
        sections: [
          { title: 'Hotel Phrases', type: 'rule', content: 'Check in: "I have a reservation under the name [your name]." "I\'d like to check in, please." Questions: "What time is breakfast?" "Is there Wi-Fi?" "What\'s the Wi-Fi password?" "Is there a gym/pool/restaurant?" "What time is checkout?" Problems: "The air conditioning isn\'t working." "There\'s no hot water." "The room is very noisy." "Could I change rooms, please?"' },
          { title: 'Making Special Requests', type: 'tip', content: '"Could I have a room with a view?" "Is it possible to get a late checkout?" "Could I have an extra pillow/blanket?" "Is there a quiet room available?" "Could I have a room on a higher floor?" Most hotels want to help — just ask politely. The worst they can say is "I\'m sorry, we\'re fully booked" or "I\'m afraid that\'s not possible."' },
          { title: 'Report a Problem', type: 'exercise', question: 'Your hotel room\'s air conditioning is broken and it\'s very hot. Call reception.', answer: '"Hello, I\'m calling from room 412. I\'m sorry to bother you, but the air conditioning in my room doesn\'t seem to be working. It\'s very hot in here. Would it be possible to send someone to fix it? Or if not, could I move to a different room? Thank you."', answerExplanation: 'Identifies room number, polite opening (sorry to bother you), describes problem clearly, offers two solutions (fix or move), thanks. Professional and friendly.' },
        ],
        keyTakeaways: ['"I have a reservation under [name]" to check in', '"I\'m sorry to bother you, but..." to start a complaint politely', 'Always offer a solution: "Could you fix it?" or "Could I change rooms?"'],
      },
      // # ─── Lesson 11: At the Airport ───
      { id: 'a2-speaking-airport', title: 'At the Airport', description: 'Navigate the airport in English — check-in, security, boarding, and emergencies.',
        skill: 'speaking', level: 'A2', duration: 10,
        objectives: ['Handle check-in conversations', 'Understand security and boarding announcements', 'Ask for help with flight problems'],
        sections: [
          { title: 'Airport Vocabulary', type: 'rule', content: 'Check-in: "I\'d like to check in for flight BA247 to London." "Window seat or aisle seat?" "I\'d like a window seat, please." "How many bags are you checking in?" "Just one." "Can I take this as hand luggage?" Security: "Please remove your laptop and liquids." Boarding: "Flight BA247 is now boarding at gate 15." "This is the final call for flight BA247."' },
          { title: 'Problem Phrases', type: 'tip', content: 'Delayed: "Excuse me, my flight is delayed. How long will we have to wait?" "Is there an update on flight BA247?" Missed connection: "I\'ve missed my connecting flight because of the delay. Can you help me?" "I need to rebook my connection." Lost luggage: "My luggage hasn\'t arrived." "I\'d like to report missing luggage." Stay calm and polite — airport staff deal with stressed passengers all day. Being kind gets better help.' },
          { title: 'Handle a Problem', type: 'exercise', question: 'Your flight is delayed by 3 hours. Ask the airline staff for information and help.', answer: '"Excuse me, I\'ve just seen that flight BA247 is delayed. Could you tell me how long we\'ll have to wait? I have a connecting flight in London at 6pm — will I make it? If not, is it possible to rebook my connection? I\'d really appreciate your help."', answerExplanation: 'Calm and polite, asks specific questions (how long, will I make my connection), requests solution (rebook), shows gratitude. Much more effective than being angry.' },
        ],
        keyTakeaways: ['"Window or aisle?" — know your preference before check-in', '"My luggage hasn\'t arrived" for lost bags — go to the arrivals desk', 'Stay calm and polite with staff — it gets better results'],
      },
      // # ─── Lesson 12: Talking About Health & Fitness ───
      { id: 'a2-speaking-health-fitness', title: 'Talking About Health & Fitness', description: 'Discuss exercise, diet, and healthy habits in conversation.',
        skill: 'speaking', level: 'A2', duration: 8,
        objectives: ['Talk about exercise and fitness routines', 'Discuss healthy and unhealthy habits', 'Give and receive health advice'],
        sections: [
          { title: 'Health Talk', type: 'rule', content: 'Exercise: "I go to the gym three times a week." "I run in the park every morning." "I do yoga / I play football / I swim." Diet: "I try to eat healthy." "I\'ve been eating more vegetables." "I\'ve cut down on sugar." "I\'m trying to drink more water." Habits: "I get about 7 hours of sleep." "I walk to work instead of driving." "I try to avoid processed food."' },
          { title: 'Giving Health Advice', type: 'tip', content: 'Gentle advice: "You should try to get more sleep." "Why don\'t you try yoga?" "Have you thought about walking more?" "Maybe you could cut down on coffee." Avoid being pushy — nobody likes being told what to eat or how to exercise. If someone hasn\'t asked for advice, don\'t give it. "You should lose weight" is NEVER appropriate to say.' },
          { title: 'Talk About Your Habits', type: 'exercise', question: 'Describe your health and fitness habits — good ones and ones you want to improve.', answer: '"I try to stay active — I go running about twice a week and I walk to work most days. I eat quite well during the week, but at weekends I eat a lot of junk food! I know I should drink more water — I mostly drink coffee. And I want to start going to bed earlier because I\'m always tired in the morning."', answerExplanation: 'Honest mix of good and bad habits, uses "I try to", "I know I should", "I want to start" — all natural ways to discuss health without being unrealistic.' },
        ],
        keyTakeaways: ['"I try to..." and "I want to start..." for health goals', 'Don\'t give health advice unless someone asks', '"Cut down on" = reduce. "Give up" = stop completely.'],
      },
      // # ─── Lesson 13: Talking About Traditions & Celebrations ───
      { id: 'a2-speaking-traditions', title: 'Talking About Traditions & Celebrations', description: 'Share your culture — festivals, holidays, and special customs.',
        skill: 'speaking', level: 'A2', duration: 10,
        objectives: ['Describe cultural festivals and holidays', 'Explain traditions to someone from another culture', 'Ask about other people\'s traditions'],
        sections: [
          { title: 'Describing Traditions', type: 'rule', content: 'When: "We celebrate [festival] in [month]." "It\'s usually in December." What: "People usually..." "We traditionally..." "It\'s a time for family / food / giving gifts." "Everyone wears..." How: "First, we... Then, we... After that, we..." "The most important part is..." Why: "We celebrate because..." "It\'s to remember..."' },
          { title: 'Explaining to Foreigners', type: 'tip', content: 'Don\'t assume they know anything. Explain simply: "Songkran is the Thai New Year. It\'s in April. People throw water at each other in the streets! It\'s really fun. The water symbolises washing away bad luck. Everyone gets completely wet — you can\'t escape it!" Compare to something they might know: "It\'s a bit like Christmas in terms of family gatherings, but instead of presents, there\'s water fights!"' },
          { title: 'Describe a Festival', type: 'exercise', question: 'Describe a festival or tradition from your culture to someone who knows nothing about it.', answer: '"In my country, we celebrate Lunar New Year. It\'s usually in January or February — the date changes every year. Families get together for a big dinner on New Year\'s Eve. We eat special foods like dumplings, which symbolise wealth. Children receive red envelopes with money inside — that\'s the best part if you\'re a kid! There are also fireworks and lion dances in the streets. It\'s the most important holiday of the year."', answerExplanation: 'Explains when, what happens, special foods, customs (red envelopes), atmosphere (fireworks, lion dances), and significance (most important holiday). Clear enough for someone with zero knowledge.' },
        ],
        keyTakeaways: ['Explain when, what, how, and why', 'Don\'t assume knowledge — explain everything simply', 'Compare to familiar concepts: "It\'s a bit like..."'],
      },
      // # ─── Lesson 14: Giving Instructions & Explaining How ───
      { id: 'a2-speaking-giving-instructions', title: 'Giving Instructions & Explaining How', description: 'Explain how to do something — step by step, clearly.',
        skill: 'speaking', level: 'A2', duration: 8,
        objectives: ['Give clear step-by-step instructions', 'Use sequence words: first, then, next, finally', 'Check understanding as you explain'],
        sections: [
          { title: 'Instruction Language', type: 'rule', content: 'Sequence: "First,..." "Then,..." "Next,..." "After that,..." "Finally,..." Imperatives: "Open the app." "Click on settings." "Type your password." "Press enter." "Wait for it to load." Adding detail: "Make sure you..." "Don\'t forget to..." "Be careful not to..." "The important thing is..."' },
          { title: 'Checking Understanding', type: 'tip', content: 'As you explain: "Does that make sense so far?" "Are you with me?" "Got it?" "Shall I show you again?" Don\'t say: "Do you understand?" (can sound patronising). Better: "Is that clear?" or "Any questions so far?" If someone looks confused, slow down and repeat — don\'t just keep going.' },
          { title: 'Explain How', type: 'exercise', question: 'Explain to someone how to make a cup of tea (the proper way!).', answer: '"OK, so first, fill the kettle with fresh water and turn it on. While you\'re waiting for it to boil, put a teabag in a mug. When the water boils, pour it over the teabag. Then let it brew for about 3 to 5 minutes — don\'t take the bag out too early! After that, remove the teabag and add milk if you want it. Finally, add sugar if you like it sweet. The important thing is not to put the milk in first — that\'s a crime in England!"', answerExplanation: 'Clear sequence words (first, while, when, then, after that, finally), specific details (3-5 minutes), warnings (don\'t take it out too early), humour (crime in England). Easy to follow.' },
        ],
        keyTakeaways: ['First → Then → Next → After that → Finally', '"Make sure you..." and "Don\'t forget to..." for important steps', '"Does that make sense so far?" to check understanding'],
      },
      // # ─── Lesson 15: Making & Responding to Invitations ───
      { id: 'a2-speaking-invitations', title: 'Making & Responding to Invitations', description: 'Invite people to events, accept gracefully, and decline without guilt.',
        skill: 'speaking', level: 'A2', duration: 8,
        objectives: ['Invite someone to an event or activity', 'Accept invitations enthusiastically', 'Decline invitations without offending'],
        sections: [
          { title: 'Inviting', type: 'rule', content: 'Casual: "Do you want to come to my party?" "Fancy a coffee?" (British informal) "Are you free on Saturday?" Polite: "I\'d like to invite you to..." "Would you like to join us for dinner?" "We\'re having a barbecue — you\'re welcome to come!" Formal: "We would be delighted if you could attend..." "You are cordially invited to..."' },
          { title: 'Accepting & Declining', type: 'tip', content: 'Accepting: "I\'d love to!" "Sounds great, count me in!" "Yes, please! What time?" "That sounds lovely, thank you." Declining: "I\'d love to, but I can\'t — I\'m working that day." "That sounds great, but unfortunately I already have plans." "I wish I could, but..." "Maybe next time?" Always give a reason when declining AND suggest an alternative. "Rain check?" = let\'s do it another time.' },
          { title: 'Invite and Decline', type: 'exercise', question: 'Invite your friend to a concert. They can\'t come. Write both sides.', answer: 'You: "Hey! I\'ve got two tickets for the Arctic Monkeys concert on Friday night. Do you want to come? It\'s going to be amazing!"\n\nFriend: "Oh wow, I\'d absolutely love to, but I\'m so sorry — I\'m away that weekend visiting my parents. I\'m gutted! Could you ask me next time? Or if you hear about any other gigs, let me know!"', answerExplanation: 'Invitation is enthusiastic with details (band, day). Decline shows genuine disappointment (gutted), gives a reason (visiting parents), suggests future plans (ask me next time). Nobody feels bad.' },
        ],
        keyTakeaways: ['"Would you like to...?" is polite. "Do you want to...?" is casual.', 'When declining: reason + apology + alternative', '"Rain check?" = let\'s do it another time'],
      },
      // # ─── Lesson 16: Describing Photos ───
      { id: 'a2-speaking-describing-photos', title: 'Describing Photos', description: 'Describe what you see in a photo — people, places, actions, and atmosphere.',
        skill: 'speaking', level: 'A2', duration: 8,
        objectives: ['Describe what\'s in a photo systematically', 'Use "It looks like..." and "It seems like..."', 'Speculate about what\'s happening'],
        sections: [
          { title: 'Photo Description Framework', type: 'rule', content: 'Overview: "In this photo, I can see..." / "This photo shows..." Where: "It looks like it was taken in a park / at a beach / indoors." Who: "There\'s a woman / a group of people / two children." What they\'re doing: "They\'re having a picnic / playing football / talking." Details: "In the background, there\'s..." "On the left/right, you can see..." Atmosphere: "It looks like a sunny day." "Everyone seems happy." "It looks quite cold."' },
          { title: 'Useful Speculation Language', type: 'tip', content: '"It looks like they\'re friends." "They seem to be enjoying themselves." "I think this was taken in summer." "It might be a birthday party." "He could be about 30 years old." "It appears to be a family gathering." Don\'t state things as facts when you\'re guessing — use "looks like", "seems", "might be", "could be".' },
          { title: 'Describe a Photo', type: 'exercise', question: 'Describe this scene: A family of four is eating together at an outdoor restaurant by the sea. The sun is setting.', answer: '"In this photo, I can see a family of four — it looks like two parents and two children. They\'re having dinner at an outdoor restaurant right by the sea. In the background, you can see a beautiful sunset — the sky is orange and pink. Everyone seems really happy and relaxed. They\'re laughing about something. It looks like a holiday — maybe somewhere Mediterranean. It\'s a really lovely, warm scene."', answerExplanation: 'Overview (family of four), location (outdoor restaurant by the sea), background (sunset), atmosphere (happy, relaxed), speculation (holiday, Mediterranean). Systematic and vivid.' },
        ],
        keyTakeaways: ['Start with overview → people → actions → background → atmosphere', '"It looks like..." and "It seems like..." for speculation', 'Don\'t state guesses as facts — use "might be", "could be"'],
      },
      // # ─── Lesson 17: Problem-Solving Conversations ───
      { id: 'a2-speaking-problem-solving', title: 'Problem-Solving Conversations', description: 'Discuss problems and work out solutions together.',
        skill: 'speaking', level: 'A2', duration: 10,
        objectives: ['Describe a problem clearly', 'Suggest solutions collaboratively', 'Evaluate options and agree on a plan'],
        sections: [
          { title: 'Describing Problems', type: 'rule', content: '"The problem is that..." "The issue is..." "We\'ve got a problem with..." "The thing is,..." "Here\'s the situation:..." "What happened is..." Showing impact: "This means that..." "Because of this,..." "If we don\'t fix it,..."' },
          { title: 'Suggesting Solutions', type: 'tip', content: '"I think we should..." "How about if we...?" "One option is to..." "What if we tried...?" "Maybe we could..." "The best thing to do would be..." Evaluating: "That might work, but..." "The problem with that is..." "That sounds good in theory, but..." "I think that\'s the best option because..."' },
          { title: 'Solve a Problem', type: 'exercise', question: 'Problem: Your team has a deadline on Friday but two people are sick. Discuss solutions with your colleague.', answer: '"OK, so the problem is that we have the deadline on Friday and two people are off sick. I think we have a few options. One, we could ask the manager for an extension — maybe until Monday? Two, we could divide the extra work between us. Or three, we could ask another team to help. Personally, I think we should ask for a short extension AND split the work. What do you think? Is there anything else we could try?"', answerExplanation: 'States problem clearly, offers three numbered options, gives a recommendation (extension + split), asks for input (What do you think?). Collaborative and structured.' },
        ],
        keyTakeaways: ['"The problem is that..." to state the issue clearly', 'Offer multiple solutions — numbered lists help', 'Ask "What do you think?" to keep it collaborative'],
      },
      // # ─── Lesson 18: Small Talk ───
      { id: 'a2-speaking-small-talk', title: 'Small Talk', description: 'Master the art of light conversation — the social glue of English-speaking cultures.',
        skill: 'speaking', level: 'A2', duration: 10,
        objectives: ['Start conversations with appropriate small talk', 'Keep small talk going with follow-up questions', 'Know which topics are safe and which to avoid'],
        sections: [
          { title: 'Safe Topics', type: 'rule', content: 'Good small talk topics: weather, weekend plans, holidays, travel, food, sports, entertainment (films, TV, music), work (general), hobbies. Avoid: politics, religion, money/salary, weight/appearance, age, relationship status, health problems (in detail). These rules are for England/US/Australia. Different cultures have different rules — in some cultures, asking about salary is completely normal!' },
          { title: 'Keeping It Going', type: 'tip', content: 'The secret to small talk: follow-up questions. "Did you have a good weekend?" → "Yes, I went to a concert." → "Oh nice! Who did you see?" → "Ed Sheeran." → "I love Ed Sheeran! Have you seen him before?" Questions keep conversation alive. Statements kill it. If you only say "That\'s nice" and don\'t ask a question, the conversation dies.' },
          { title: 'Start Small Talk', type: 'exercise', question: 'You\'re waiting for a meeting to start. Make small talk with the person next to you.', answer: '"Hi! I don\'t think we\'ve met — I\'m Alex from the marketing team. Have you been waiting long? ... Oh, not too bad then. Did you have a good weekend? ... Oh, that sounds lovely! I love Thai food. Where did you go? ... I\'ll have to try that place. Have you been to the new Italian place on the corner? They do amazing pizza."', answerExplanation: 'Introduction, rapport question, weekend question, follow-up questions, recommendation. Natural flow that could go on for minutes. Each response leads to another question.' },
        ],
        keyTakeaways: ['Safe: weather, weekends, food, travel. Avoid: money, politics, religion.', 'Follow-up questions keep conversation alive', 'Small talk isn\'t about deep conversation — it\'s about building rapport'],
      },
      // # ─── Lesson 19: Talking About the News ───
      { id: 'a2-speaking-news', title: 'Talking About the News', description: 'Discuss current events and news stories in English.',
        skill: 'speaking', level: 'A2', duration: 8,
        objectives: ['Report a news story simply', 'Give your opinion on current events', 'Ask others about news they\'ve heard'],
        sections: [
          { title: 'News Phrases', type: 'rule', content: 'Starting: "Did you hear about...?" "Have you seen the news about...?" "I read that..." "Apparently,..." Reporting: "It said that..." "According to the news,..." "They say that..." Opinion: "I think it\'s terrible / great / surprising / scary." "I can\'t believe that..." "It\'s shocking that..." "It makes me angry / sad / worried."' },
          { title: 'Being Careful', type: 'tip', content: 'News can be political and sensitive. Be careful: "I think..." (this is my opinion, not fact). "I read that..." (this is what I heard, not confirmed). "I might be wrong, but..." (I\'m not sure). Avoid: "This is definitely true." "Anyone who disagrees is stupid." Listen to others\' views even if you disagree. News discussions are a chance to practise speaking, not to start arguments.' },
          { title: 'Discuss a News Story', type: 'exercise', question: 'Report this news: "Scientists have discovered a new species of fish in the deep ocean." Give your opinion.', answer: '"Did you hear about the new fish they found? Apparently, scientists have discovered a completely new species in the deep ocean — really deep, like 5,000 metres down. I think it\'s amazing that we\'re still finding new species in 2026. It makes you wonder what else is down there that we haven\'t found yet. Have you seen any photos of it?"', answerExplanation: 'Reports the story (Did you hear..., Apparently...), adds detail (5,000 metres), gives opinion (amazing), reflects (makes you wonder), asks for engagement (Have you seen?). Conversational and interesting.' },
        ],
        keyTakeaways: ['"Did you hear about...?" to start a news discussion', 'Use "I think" and "Apparently" — don\'t state opinions as facts', 'End with a question to keep the discussion going'],
      },
      // # ─── Lesson 20: Basic Job Interview Skills ───
      { id: 'a2-speaking-job-interview', title: 'Basic Job Interview Skills', description: 'Prepare for common interview questions and make a great impression.',
        skill: 'speaking', level: 'A2', duration: 12,
        objectives: ['Answer "Tell me about yourself"', 'Discuss your strengths and experience', 'Ask good questions at the end'],
        sections: [
          { title: 'Common Questions', type: 'rule', content: '"Tell me about yourself." → Focus on: education + experience + why this job. Keep it under 2 minutes. "Why do you want this job?" → Show you researched the company. "What are your strengths?" → Give examples, not just adjectives. "What is your biggest weakness?" → Be honest but show you\'re working on it. "Where do you see yourself in 5 years?" → Show ambition but be realistic.' },
          { title: 'STAR Method for Examples', type: 'tip', content: 'When they say "Give me an example of..." use STAR: Situation: "In my last job, we had a tight deadline..." Task: "I was responsible for..." Action: "I decided to..." / "I organised..." Result: "We finished on time and the client was very happy." Always give SPECIFIC examples, not general statements. "I\'m a team player" is weak. "At my last job, I helped train three new staff members, and two of them got promoted within a year" is strong.' },
          { title: 'Tell Me About Yourself', type: 'exercise', question: 'You\'re applying for a marketing assistant job. Answer: "Tell me about yourself."', answer: '"Sure! I graduated from university last year with a degree in Business Studies. During university, I did a 6-month internship at a marketing agency where I helped manage social media accounts and create content. I really enjoyed the creative side of marketing. I\'m looking for a role where I can develop my skills further, and I\'m really excited about this position because your company is known for innovative campaigns."', answerExplanation: 'Education (graduated, Business Studies), experience (internship, social media, content), enthusiasm (really enjoyed), why this company (innovative campaigns). Under 2 minutes, focused, and ends on a positive note.' },
        ],
        keyTakeaways: ['Tell me about yourself: education + experience + why this job (under 2 mins)', 'Use the STAR method: Situation → Task → Action → Result', 'Always prepare 2-3 questions to ask THEM at the end'],
      },
      // # ─── Lesson 21: Describing Food & Cooking ───
      { id: 'a2-speaking-food', title: 'Describing Food & Cooking', description: 'Talk about food, recipes, and eating habits — everyone\'s favourite topic!',
        skill: 'speaking', level: 'A2', duration: 8,
        objectives: ['Describe tastes and textures', 'Explain how to cook a simple dish', 'Discuss food preferences and dietary needs'],
        sections: [
          { title: 'Food Adjectives', type: 'rule', content: 'Taste: sweet, salty, sour, bitter, spicy, bland, rich, light, savoury. Texture: crispy, crunchy, soft, chewy, creamy, smooth, juicy, tough, tender. Temperature: hot, warm, cold, frozen, chilled. Opinion: delicious, tasty, disgusting, horrible, amazing, OK, not bad. "The curry is really spicy and the rice is perfectly fluffy." "This steak is so tender and juicy."' },
          { title: 'Cooking Verbs', type: 'tip', content: 'Boil (water, eggs, pasta). Fry (eggs, onions). Bake (cake, bread). Roast (chicken, vegetables). Grill (steak, fish). Chop (onions, garlic). Slice (bread, tomatoes). Mix/Stir (ingredients, sauce). Add (salt, spices). Pour (water, sauce). "First, chop the onions and fry them in oil for 5 minutes. Then add the garlic and stir for 1 minute."' },
          { title: 'Describe a Dish', type: 'exercise', question: 'Describe your favourite dish — what it is, what\'s in it, and why you love it.', answer: '"My favourite dish is pad thai. It\'s a Thai stir-fried noodle dish. It has rice noodles, prawns or chicken, egg, beansprouts, and peanuts. The sauce is sweet and sour and a little bit salty — it\'s really well balanced. I love it because it\'s quick to cook, the textures are amazing — soft noodles with crunchy peanuts — and it reminds me of my holiday in Thailand."', answerExplanation: 'Names the dish, explains what it is, lists ingredients, describes taste (sweet, sour, salty), textures (soft, crunchy), and personal connection (holiday). Makes you hungry!' },
        ],
        keyTakeaways: ['Taste: sweet/salty/sour/spicy. Texture: crispy/soft/creamy/crunchy.', 'Cooking verbs: boil, fry, bake, roast, grill, chop, slice, stir', 'Describe food with taste + texture + opinion for vivid descriptions'],
      },
      // # ─── Lesson 22: Talking About Travel ───
      { id: 'a2-speaking-travel', title: 'Talking About Travel', description: 'Share travel stories, recommend destinations, and discuss travel plans.',
        skill: 'speaking', level: 'A2', duration: 10,
        objectives: ['Talk about past trips with interesting details', 'Recommend places to visit', 'Discuss travel preferences'],
        sections: [
          { title: 'Travel Vocabulary', type: 'rule', content: 'Types: backpacking, package holiday, road trip, city break, cruise, gap year. Accommodation: hotel, hostel, Airbnb, camping, resort. Activities: sightseeing, hiking, snorkelling, trying local food, visiting museums, relaxing on the beach. Problems: jet lag, lost luggage, missed flights, getting sick, bad weather, tourist traps.' },
          { title: 'Recommending Places', type: 'tip', content: '"You should definitely visit [place]." "If you go, make sure you visit [specific thing]." "Don\'t miss [attraction]." "The best time to go is [month]." "I\'d recommend staying in [area] because..." "One thing I wish I\'d known is..." "The only downside is..." Honest recommendations are better than "everything was perfect" — people trust you more if you mention one negative.' },
          { title: 'Recommend a Trip', type: 'exercise', question: 'A friend is planning a trip to a country you\'ve visited. Recommend it.', answer: '"Oh, you have to go to Portugal! I went last year and it was incredible. If you go, make sure you visit Lisbon — the old town is beautiful and the food is amazing. Try the pastel de nata — it\'s a kind of custard tart and it\'s everywhere. I\'d recommend going in spring because summer is really hot and crowded. The only downside is that the hills in Lisbon are exhausting to walk up! But honestly, it\'s one of my favourite trips ever."', answerExplanation: 'Enthusiastic opening, specific recommendation (Lisbon, old town), food tip (pastel de nata), practical advice (spring), honest negative (hills), overall opinion (favourite trip). Trustworthy and helpful.' },
        ],
        keyTakeaways: ['"You should definitely visit..." to recommend strongly', 'Include practical tips: best time, what to eat, where to stay', 'Mention one honest negative — it makes your recommendation more trustworthy'],
      },
      // # ─── Lesson 23: Expressing Preferences ───
      { id: 'a2-speaking-preferences', title: 'Expressing Preferences', description: 'Say what you prefer and why — from simple choices to lifestyle decisions.',
        skill: 'speaking', level: 'A2', duration: 8,
        objectives: ['Use "prefer", "would rather", and "I\'d rather"', 'Explain preferences with reasons', 'Ask others about their preferences'],
        sections: [
          { title: 'Preference Structures', type: 'rule', content: '"I prefer tea to coffee." (prefer X to Y). "I\'d rather stay in than go out." (would rather X than Y). "I like swimming more than running." (like X more than Y). "I\'d prefer to take the train." "Given the choice, I\'d choose..." "If I had to choose, I\'d go with..." Questions: "Which do you prefer?" "Would you rather...or...?" "What would you choose?"' },
          { title: 'Would Rather + Base Verb', type: 'tip', content: '"I\'d rather" is followed by the base verb (no "to"): "I\'d rather stay home." ✓ "I\'d rather to stay home." ✗ "I\'d rather not go out tonight." (negative). "Would you rather eat in or eat out?" For comparing: "I\'d rather have pizza than pasta." "I\'d rather watch a film than go to a party."' },
          { title: 'Express Preferences', type: 'exercise', question: 'Answer: "Would you rather live in a big city or a small town? Why?"', answer: '"I\'d rather live in a big city, definitely. I prefer the energy and the variety — there\'s always something to do. I like having lots of restaurants, cinemas, and events to choose from. I know small towns are quieter and more peaceful, and I can see the appeal, but I think I\'d get bored quite quickly. I need the buzz of a city around me."', answerExplanation: 'Clear preference (big city), reasons (energy, variety, things to do), acknowledges the alternative (small towns are quieter), personal connection (I need the buzz). Well-argued preference with personality.' },
        ],
        keyTakeaways: ['"I prefer X to Y" / "I\'d rather X than Y"', '"Would rather" + base verb (no "to")', 'Always give reasons — preferences without reasons are boring'],
      },
      // # ─── Lesson 24: Telephone English — Beyond Basics ───
      { id: 'a2-speaking-telephone', title: 'Telephone English — Beyond Basics', description: 'Handle business calls, appointments, and complaints on the phone.',
        skill: 'speaking', level: 'A2', duration: 10,
        objectives: ['Make appointments and bookings by phone', 'Handle misunderstandings on the phone', 'Leave detailed voice messages'],
        sections: [
          { title: 'Making Appointments', type: 'rule', content: '"I\'d like to make an appointment, please." "I\'d like to book a table / a room / a ticket." "Is [date/time] available?" "What times do you have on Tuesday?" "Could I reschedule my appointment?" "I need to cancel my booking." Confirming: "So that\'s Tuesday the 5th at 2pm?" "Can I get a confirmation email?" "Let me just check I\'ve got that right..."' },
          { title: 'Handling Phone Difficulties', type: 'tip', content: 'Bad connection: "Sorry, I\'m losing you. Could you say that again?" "You\'re breaking up — can you hear me?" Wrong number: "Sorry, I think you\'ve got the wrong number." "I\'m sorry, there\'s nobody here by that name." Spelling: "Could you spell that for me?" Use the NATO alphabet: "M for Mike, A for Alpha..." Or simply: "M for Mother, A for Apple..." — whatever works!' },
          { title: 'Make an Appointment', type: 'exercise', question: 'Call a dentist to make an appointment. You want a check-up next week.', answer: '"Hello, I\'d like to make an appointment for a check-up, please. I was hoping to come in sometime next week. ... Tuesday at 10:30? That\'s perfect. Could I just confirm — that\'s Tuesday the 12th at 10:30? And the address is 15 High Street? Great. My name is Sarah Chen, that\'s C-H-E-N. Thank you very much. See you on Tuesday!"', answerExplanation: 'Polite request, flexible timing (sometime next week), confirms details (date, time, address), spells surname, thanks and confirms. Complete and professional.' },
        ],
        keyTakeaways: ['Always confirm details: date, time, address, spelling', '"I\'m losing you" / "You\'re breaking up" for bad connections', 'Spell names using simple words: "C for Charlie, H for Hotel"'],
      },
    ],
  },
]
