// # ═══════════════════════════════════════════════════════════════════════════
// # LESSON DATA — Part 10: Writing Lessons A1 + A2 (50 lessons)
// # ═══════════════════════════════════════════════════════════════════════════

import type { LessonCategory } from './types'

export const LESSON_CATEGORIES_10: LessonCategory[] = [
  {
    id: 'a1-writing',
    name: 'A1: Writing Skills',
    description: 'Learn to write simple sentences, messages, and personal information.',
    icon: '✏️',
    lessons: [
      { id: 'a1-writing-simple-sentences', title: 'Writing Simple Sentences', description: 'Build sentences with Subject + Verb + Object — the foundation of all English writing.',
        skill: 'writing', level: 'A1', duration: 8,
        objectives: ['Write basic SVO sentences', 'Use capital letters and full stops', 'Join two ideas with "and"'],
        sections: [
          { title: 'The Basic Pattern', type: 'rule', content: 'Every English sentence needs a subject (who) and a verb (action). Most add an object (what). Pattern: Subject + Verb + Object. "I like coffee." "She reads books." "They play football." Always start with a capital letter. Always end with a full stop (.). One idea = one sentence.' },
          { title: 'See It in Action', type: 'example', examples: ['I eat breakfast every morning.', 'He plays guitar after school.', 'We watch TV at night.', 'She drinks water.'], analysis: 'Each sentence follows S+V+O. The subject tells us WHO. The verb tells us WHAT THEY DO. The object tells us WHAT.' },
          { title: 'Your Turn', type: 'exercise', question: 'Write three sentences about things you do every day.', answer: 'I drink coffee. She cooks dinner. We clean the house.', answerExplanation: 'Each has all three parts: subject (I/She/We), verb (drink/cooks/clean), object (coffee/dinner/house).' },
        ],
        keyTakeaways: ['S + V + O is the basic English sentence pattern', 'Capital letter at start, full stop at end', 'Keep sentences short and clear at A1'],
      },
      { id: 'a1-writing-capitals-punctuation', title: 'Capital Letters & Punctuation', description: 'Know exactly when to use capital letters and which punctuation mark to choose.',
        skill: 'writing', level: 'A1', duration: 8,
        objectives: ['Use capital letters for names, places, and sentence starts', 'Choose between full stops, question marks, and exclamation marks', 'Avoid common capitalisation mistakes'],
        sections: [
          { title: 'Capital Letter Rules', type: 'rule', content: 'Use a capital letter for: the first word of a sentence ("The cat is black."), names of people ("Maria", "John"), names of places ("London", "Thailand"), days and months ("Monday", "January"), the word "I" (always capital), nationalities and languages ("English", "Thai"). Do NOT capitalise: ordinary nouns ("cat", "table"), adjectives ("big", "happy") unless at the start of a sentence.' },
          { title: 'Punctuation Marks', type: 'rule', content: 'Full stop (.) = end of a statement: "I am happy." Question mark (?) = end of a question: "Are you happy?" Exclamation mark (!) = strong emotion or surprise: "Wow!" "Help!" Comma (,) = pause in a sentence or between list items: "I like tea, coffee, and juice."' },
          { title: 'Fix the Mistakes', type: 'exercise', question: 'Correct this sentence: "my friend maria lives in bangkok she is from thailand"', answer: 'My friend Maria lives in Bangkok. She is from Thailand.', answerExplanation: 'Capital: My (sentence start), Maria (name), Bangkok (place), She (sentence start), Thailand (country). Added full stop between the two sentences.' },
        ],
        keyTakeaways: ['Capitalise: sentence starts, names, places, days, months, I', 'Full stop = statement. Question mark = question.', 'Commas separate items in a list'],
      },
      { id: 'a1-writing-personal-info', title: 'Writing Personal Information', description: 'Write about yourself — name, age, nationality, job, and where you live.',
        skill: 'writing', level: 'A1', duration: 8,
        objectives: ['Write sentences about yourself', 'Use "I am", "I live", "I work"', 'Organise personal information clearly'],
        sections: [
          { title: 'Key Phrases', type: 'rule', content: 'My name is [name]. I am [age] years old. I am from [country]. I live in [city]. I am [nationality]. I speak [language(s)]. I am a [job]. I work at [place]. My phone number is [number]. My email is [email].' },
          { title: 'Example Paragraph', type: 'example', examples: ['My name is Maria. I am 28 years old. I am from Brazil. I live in London. I am Brazilian. I speak Portuguese and English. I am a teacher. I work at a primary school.'], analysis: 'Notice how each sentence gives one piece of information. Short, clear, and easy to read.' },
          { title: 'Write About Yourself', type: 'exercise', question: 'Write 5 sentences about yourself using the phrases above.', answer: 'My name is Alex. I am 25 years old. I am from Thailand. I live in Bangkok. I am a student.', answerExplanation: 'Each sentence gives one fact. Uses "I am" and "I live" correctly. Capital letters for names and places.' },
        ],
        keyTakeaways: ['"I am" for age, nationality, job', '"I live in" for location', 'One fact per sentence keeps writing clear'],
      },
      { id: 'a1-writing-numbers-dates', title: 'Writing Numbers, Days & Dates', description: 'Write times, days of the week, months, and dates correctly in English.',
        skill: 'writing', level: 'A1', duration: 8,
        objectives: ['Write days of the week and months', 'Write dates in British and American format', 'Write times using numbers and words'],
        sections: [
          { title: 'Days, Months & Dates', type: 'rule', content: 'Days: Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday (always capital). Months: January, February, March, April, May, June, July, August, September, October, November, December (always capital). British date: day/month/year — 5th March 2026 or 05/03/2026. American date: month/day/year — March 5, 2026 or 03/05/2026.' },
          { title: 'Writing Times', type: 'rule', content: 'Use numbers: 9:00, 10:30, 2:15. Use words: nine o\'clock, half past ten, quarter past two. AM = morning (12:00 midnight to 11:59). PM = afternoon/evening (12:00 noon to 11:59). "The class starts at 9:00 AM." "I finish work at 5:30 PM."' },
          { title: 'Practice', type: 'exercise', question: 'Write today\'s date in British format and write what time you woke up.', answer: '7th August 2026. I woke up at 7:00 AM.', answerExplanation: 'British format: day + month + year. Time with AM/PM.' },
        ],
        keyTakeaways: ['Days and months always start with a capital letter', 'British: day/month/year. American: month/day/year.', 'Use AM for morning, PM for afternoon/evening'],
      },
      { id: 'a1-writing-forms', title: 'Filling in Simple Forms', description: 'Complete registration forms, booking forms, and application forms accurately.',
        skill: 'writing', level: 'A1', duration: 8,
        objectives: ['Understand common form fields', 'Write information in the correct format', 'Know abbreviations like DOB, Mr/Mrs/Ms'],
        sections: [
          { title: 'Common Form Fields', type: 'rule', content: 'First name / Given name = your personal name (Maria). Surname / Last name / Family name = your family name (Silva). DOB / Date of birth = when you were born. Address = where you live (house number + street + city + country). Postcode / Zip code = area code for your address. Nationality = your country (Brazilian, Thai, British). Occupation / Job title = what you do (teacher, engineer, student). Title: Mr (man), Mrs (married woman), Ms (any woman), Miss (young/unmarried woman).' },
          { title: 'Tips for Forms', type: 'tip', content: 'Write clearly — use BLOCK CAPITALS if the form asks. Use the format the form shows (DD/MM/YYYY or MM/DD/YYYY). Phone numbers: include country code (+44, +66). Email: double-check spelling. If a field does not apply, write "N/A" (not applicable). Read ALL fields before you start writing.' },
          { title: 'Practice', type: 'exercise', question: 'Fill in: First name: ___ Surname: ___ DOB: ___ Nationality: ___ Occupation: ___', answer: 'First name: Maria. Surname: Silva. DOB: 15/03/1998. Nationality: Brazilian. Occupation: Teacher.', answerExplanation: 'Each field has one clear answer. Date in DD/MM/YYYY format. Nationality is an adjective (Brazilian, not Brazil).' },
        ],
        keyTakeaways: ['First name = personal name, Surname = family name', 'DOB = Date of Birth, N/A = Not Applicable', 'Always read the format the form wants before writing'],
      },
      { id: 'a1-writing-shopping-list', title: 'Writing a Shopping List', description: 'Organise items you need to buy — a practical, everyday writing skill.',
        skill: 'writing', level: 'A1', duration: 6,
        objectives: ['Write food and household items', 'Use quantities (a, some, two, a bottle of)', 'Organise a list by category'],
        sections: [
          { title: 'Quantities', type: 'rule', content: 'a/an + singular: a banana, an apple, an egg. some + plural/uncountable: some tomatoes, some milk, some bread. Numbers: 2 onions, 6 eggs, 3 bananas. Containers: a bottle of water, a bag of rice, a box of cereal, a tin of beans, a packet of biscuits, a carton of juice.' },
          { title: 'Organised List Example', type: 'example', examples: ['Fruit: 3 bananas, some apples, a bag of oranges', 'Dairy: a bottle of milk, some cheese, 6 eggs', 'Other: a loaf of bread, some rice, a tin of beans'], analysis: 'Grouping by category (fruit, dairy, other) makes shopping faster. Each item has a quantity.' },
          { title: 'Write Your List', type: 'exercise', question: 'Write a shopping list for making breakfast. Include at least 6 items with quantities.', answer: '6 eggs, a loaf of bread, a bottle of milk, some butter, a packet of cereal, some orange juice.', answerExplanation: 'Each item has a quantity or container word. All are breakfast foods.' },
        ],
        keyTakeaways: ['Use a/an for single items, some for plural/uncountable', 'Container words: bottle, bag, box, tin, packet, carton', 'Organise by category for clarity'],
      },
      { id: 'a1-writing-text-messages', title: 'Writing Short Text Messages', description: 'Write clear, friendly text messages — making plans, asking questions, sharing news.',
        skill: 'writing', level: 'A1', duration: 8,
        objectives: ['Write short informal messages', 'Use common texting abbreviations', 'Make plans and respond to messages'],
        sections: [
          { title: 'Message Structure', type: 'rule', content: 'A simple text message has: Greeting (optional): Hi! / Hey! / Hello! Message: one or two short sentences. Question or action: a question or next step. Example: "Hi! Are you free on Saturday? Let\'s go to the park." Reply: "Hi! Yes, I am free. Sounds good! What time?" Keep it short. Use simple words.' },
          { title: 'Common Phrases', type: 'tip', content: 'Making plans: "Are you free on [day]?" "Let\'s meet at [time]." "Where shall we go?" Responding: "Sounds good!" "Great idea!" "Sorry, I can\'t." "I\'m busy on [day]." Confirming: "See you at [time]!" "OK, see you there!" "Perfect!"' },
          { title: 'Reply to This Message', type: 'exercise', question: '"Hi! Do you want to go to the cinema on Friday evening?"', answer: '"Hi! Yes, I\'d love to! What time? And which cinema?"', answerExplanation: 'Friendly greeting, positive response, follow-up questions to get details.' },
        ],
        keyTakeaways: ['Keep texts short: 1-3 sentences', '"Are you free on...?" to suggest plans', '"Sounds good!" / "Sorry, I can\'t" to respond'],
      },
      { id: 'a1-writing-postcard', title: 'Writing a Postcard', description: 'Write a short, friendly postcard from a holiday or trip.',
        skill: 'writing', level: 'A1', duration: 8,
        objectives: ['Use the standard postcard format', 'Describe a place simply', 'Write about what you are doing on holiday'],
        sections: [
          { title: 'Postcard Format', type: 'rule', content: 'Greeting: "Dear [name]," / "Hi [name]!" Body (3-5 sentences): Where you are. What it is like. What you are doing. What you like about it. Closing: "See you soon!" / "Wish you were here!" / "Love, [your name]"' },
          { title: 'Example Postcard', type: 'example', examples: ['Dear Maria,', 'I am in Barcelona! The weather is hot and sunny. I am staying in a nice hotel near the beach. Yesterday I visited the Sagrada Familia — it is beautiful! The food here is delicious. I love the paella!', 'Wish you were here!', 'Love, Alex'], analysis: 'Short sentences. Present simple and continuous. Positive adjectives (hot, sunny, nice, beautiful, delicious).' },
          { title: 'Write a Postcard', type: 'exercise', question: 'Write a postcard to a friend from a beach holiday (4-5 sentences).', answer: 'Hi Tom! I am on holiday in Phuket. The beach is amazing and the water is warm. I am swimming every day. The Thai food is so delicious! See you next week! Love, Sara', answerExplanation: 'Follows the format: greeting, location, description, activities, food, closing.' },
        ],
        keyTakeaways: ['Postcards are short: 3-5 sentences', 'Use positive adjectives to describe the place', 'Include: where, weather, activities, food'],
      },
      { id: 'a1-writing-about-family', title: 'Writing About Your Family', description: 'Describe your family members — who they are, how old they are, what they do.',
        skill: 'writing', level: 'A1', duration: 8,
        objectives: ['Use family vocabulary correctly', 'Write about people using he/she/they', 'Describe age, job, and appearance'],
        sections: [
          { title: 'Family Vocabulary', type: 'rule', content: 'Parents: mother/mum, father/dad. Siblings: brother, sister. Children: son, daughter. Others: grandmother/grandma, grandfather/grandpa, uncle, aunt, cousin. Describing: "My mother is 55 years old." "She is a nurse." "My brother is tall." "He has brown hair." "I have two sisters."' },
          { title: 'Example Paragraph', type: 'example', examples: ['I have a small family. My father is 58 years old. He is an engineer. My mother is 55. She is a teacher. I have one brother. His name is Tom. He is 22 years old. He is a university student. We live in Bangkok.'], analysis: 'Each sentence gives one fact. Uses he/she/his/her correctly. Simple and clear.' },
          { title: 'Write About Your Family', type: 'exercise', question: 'Write 5 sentences about your family. Include names, ages, and jobs.', answer: 'I have a big family. My father is 60 years old. He is a doctor. My mother is 57. She works in a shop. I have two brothers and one sister.', answerExplanation: 'Uses family vocabulary, ages, jobs. He/she pronouns match correctly.' },
        ],
        keyTakeaways: ['Use "I have" for siblings/children', 'He/his for males, she/her for females', 'One fact per sentence keeps it clear'],
      },
      { id: 'a1-writing-about-home', title: 'Writing About Your Home', description: 'Describe where you live — rooms, furniture, and what you like about it.',
        skill: 'writing', level: 'A1', duration: 8,
        objectives: ['Describe rooms and furniture', 'Use "there is/there are"', 'Use prepositions of place (in, on, next to)'],
        sections: [
          { title: 'Home Vocabulary', type: 'rule', content: 'Types: house, flat/apartment, studio. Rooms: bedroom, bathroom, kitchen, living room, dining room, garden. Furniture: bed, table, chair, sofa, desk, wardrobe, fridge, cooker. "I live in a flat." "There are two bedrooms." "There is a big kitchen." "My bedroom has a bed and a desk." "The sofa is in the living room."' },
          { title: 'Location Words', type: 'tip', content: 'in = inside: "The TV is in the living room." on = on top of: "The book is on the table." next to = beside: "The sofa is next to the window." between = in the middle: "The table is between two chairs." under = below: "The cat is under the bed."' },
          { title: 'Describe Your Home', type: 'exercise', question: 'Write 4 sentences about where you live. Use "there is/are" and location words.', answer: 'I live in a small flat. There are two bedrooms and one bathroom. There is a big TV in the living room. My desk is next to the window.', answerExplanation: 'Uses "there is" (singular) and "there are" (plural). Location words: in, next to.' },
        ],
        keyTakeaways: ['"There is" + singular, "there are" + plural', 'Prepositions: in, on, next to, between, under', 'Describe type, rooms, furniture, and what you like'],
      },
      { id: 'a1-writing-daily-routine', title: 'Writing About Your Day', description: 'Describe your daily routine from morning to night using time expressions.',
        skill: 'writing', level: 'A1', duration: 8,
        objectives: ['Use present simple for routines', 'Add time expressions (at, in the, every)', 'Sequence events with then, after that'],
        sections: [
          { title: 'Time Expressions', type: 'rule', content: 'at + time: "at 7 o\'clock", "at noon", "at midnight". in the + part of day: "in the morning", "in the afternoon", "in the evening". at night (no "the"). every + day: "every day", "every Monday". Sequencing: first, then, after that, next, finally.' },
          { title: 'Example Routine', type: 'example', examples: ['I wake up at 7 o\'clock. First, I take a shower. Then I eat breakfast. I go to work at 8:30. I have lunch at noon. After that, I work until 5 PM. In the evening, I cook dinner. I watch TV and go to bed at 11.'], analysis: 'Follows time order. Uses "first, then, after that" to connect. Simple present tense for routines.' },
          { title: 'Write Your Routine', type: 'exercise', question: 'Write 5 sentences about your morning routine. Use time expressions and sequencing words.', answer: 'I wake up at 6:30 AM. First, I brush my teeth. Then I have coffee and toast. After that, I get dressed. I leave home at 7:45.', answerExplanation: 'Time order from earliest to latest. Uses first/then/after that. Present simple for habits.' },
        ],
        keyTakeaways: ['Present simple for daily routines', 'at + exact time, in the + morning/afternoon/evening', 'First, then, after that, finally for sequence'],
      },
      { id: 'a1-writing-food-drink', title: 'Writing About Food & Drink', description: 'Describe food you like and dislike, meals, and what you eat every day.',
        skill: 'writing', level: 'A1', duration: 8,
        objectives: ['Use "I like / I don\'t like / I love / I hate"', 'Describe meals (breakfast, lunch, dinner)', 'Write about favourite food and drink'],
        sections: [
          { title: 'Talking About Preferences', type: 'rule', content: 'Love > like > don\'t mind > don\'t like > hate. "I love pizza." "I like rice." "I don\'t mind salad." "I don\'t like fish." "I hate mushrooms." For drinks: "I drink coffee every morning." "My favourite drink is orange juice." For meals: "For breakfast, I eat toast and eggs." "I usually have rice for lunch."' },
          { title: 'Example', type: 'example', examples: ['I love Thai food. My favourite dish is pad thai. For breakfast, I usually eat rice and eggs. I drink coffee every morning. I don\'t like milk. For lunch, I have noodles or rice with vegetables. I hate mushrooms!'], analysis: 'Uses like/love/hate. Describes each meal. Mentions favourite food and drink.' },
          { title: 'Write About Your Food', type: 'exercise', question: 'Write about your favourite food, a food you hate, and what you eat for breakfast.', answer: 'I love pasta. It is my favourite food. I hate onions — they taste bad! For breakfast, I eat cereal with milk and drink tea.', answerExplanation: 'Uses love/hate with reasons. Describes breakfast with "for breakfast, I eat..."' },
        ],
        keyTakeaways: ['Love > like > don\'t mind > don\'t like > hate', '"For breakfast/lunch/dinner, I eat..."', '"My favourite food/drink is..."'],
      },
      { id: 'a1-writing-hobbies', title: 'Writing About Your Hobbies', description: 'Tell people what you enjoy doing in your free time.',
        skill: 'writing', level: 'A1', duration: 8,
        objectives: ['Use "I like + -ing" for hobbies', 'Write about frequency (always, sometimes, never)', 'Describe why you enjoy something'],
        sections: [
          { title: 'Hobby Phrases', type: 'rule', content: '"I like swimming." "I enjoy reading books." "I love playing football." "In my free time, I watch movies." "My hobby is cooking." "I am interested in photography." Frequency: "I always play tennis on Saturday." "I sometimes go to the gym." "I often read before bed." "I never play video games."' },
          { title: 'Example', type: 'example', examples: ['I have many hobbies. I love playing guitar. I play every evening after work. I also like reading. My favourite books are thrillers. At the weekend, I sometimes go hiking with my friends. I never watch TV — I prefer YouTube!'], analysis: 'Uses like/love + -ing. Includes frequency words. Says why/when for each hobby.' },
          { title: 'Your Hobbies', type: 'exercise', question: 'Write about two hobbies. Say what you do, when you do it, and why you like it.', answer: 'I like cooking. I cook every evening. It is relaxing and fun. I also enjoy swimming. I go to the pool on Saturdays. It is good for my health.', answerExplanation: 'Two hobbies with when (every evening, Saturdays) and why (relaxing, good for health).' },
        ],
        keyTakeaways: ['"I like/enjoy/love + verb-ing" for hobbies', 'Add when (every day, on weekends) and why', 'Frequency words: always, often, sometimes, never'],
      },
      { id: 'a1-writing-and-but-or', title: 'Using And, But & Or', description: 'Connect ideas in your writing with the three most important joining words.',
        skill: 'writing', level: 'A1', duration: 8,
        objectives: ['Use "and" to add information', 'Use "but" to show contrast', 'Use "or" to show alternatives'],
        sections: [
          { title: 'Three Connectors', type: 'rule', content: 'AND = adds more (same direction): "I like tea and coffee." "She is tall and thin." BUT = shows contrast (opposite direction): "I like tea but I don\'t like coffee." "He is rich but unhappy." OR = shows choice (alternatives): "Do you want tea or coffee?" "We can go today or tomorrow."' },
          { title: 'Examples', type: 'example', examples: ['I speak English and Thai.', 'She is smart but lazy.', 'Do you want rice or noodles?', 'I like the city but I live in the countryside.', 'He plays football and basketball.'], analysis: 'And = adding. But = contrasting. Or = choosing. Each joins two ideas into one sentence.' },
          { title: 'Join These Sentences', type: 'exercise', question: 'Join with and/but/or: (1) "I like dogs. I like cats." (2) "He is tall. He is not strong." (3) "We can eat Thai food. We can eat Italian food."', answer: '(1) I like dogs and cats. (2) He is tall but not strong. (3) We can eat Thai or Italian food.', answerExplanation: '(1) and = adding similar ideas. (2) but = contrast. (3) or = choice between two.' },
        ],
        keyTakeaways: ['And = addition, But = contrast, Or = choice', 'They join two ideas into one sentence', 'Use a comma before but in longer sentences'],
      },
      { id: 'a1-writing-questions', title: 'Writing Simple Questions', description: 'Ask questions in writing using do/does, is/are, and question words.',
        skill: 'writing', level: 'A1', duration: 8,
        objectives: ['Write yes/no questions with do/does and is/are', 'Write wh-questions (what, where, when, who, why, how)', 'Use question marks correctly'],
        sections: [
          { title: 'Question Structures', type: 'rule', content: 'Yes/No questions: "Do you like coffee?" "Does she speak English?" "Is he a teacher?" "Are they from Japan?" Wh-questions: What = thing: "What is your name?" Where = place: "Where do you live?" When = time: "When is the meeting?" Who = person: "Who is your teacher?" Why = reason: "Why are you late?" How = way/manner: "How do you go to work?"' },
          { title: 'Common Mistakes', type: 'tip', content: 'Wrong: "Where you live?" → Right: "Where do you live?" (need "do"). Wrong: "What means this?" → Right: "What does this mean?" Wrong: "You are a student?" → Better: "Are you a student?" Always end with a question mark (?), not a full stop.' },
          { title: 'Write Questions', type: 'exercise', question: 'Write questions to find out: (1) someone\'s job, (2) where they live, (3) if they like sport.', answer: '(1) What do you do? / What is your job? (2) Where do you live? (3) Do you like sport?', answerExplanation: 'Wh-questions use what/where + do/does. Yes/no questions start with do/does/is/are.' },
        ],
        keyTakeaways: ['Yes/No: Do/Does/Is/Are + subject + verb?', 'Wh-questions: What/Where/When/Who/Why/How + do/does?', 'Always use a question mark (?)'],
      },
      { id: 'a1-writing-weather', title: 'Writing About the Weather', description: 'Describe today\'s weather and typical weather in your country.',
        skill: 'writing', level: 'A1', duration: 6,
        objectives: ['Use weather vocabulary (sunny, rainy, cloudy, hot, cold)', 'Write "It is..." for current weather', 'Describe typical weather with present simple'],
        sections: [
          { title: 'Weather Words', type: 'rule', content: 'Temperature: hot, warm, cool, cold, freezing. Sky: sunny, cloudy, foggy, clear. Rain/snow: rainy, snowy, stormy, windy. "It is sunny today." "It is very hot." "It is raining." (right now) "It rains a lot in November." (general/typical)' },
          { title: 'Example', type: 'example', examples: ['The weather is nice today. It is sunny and warm. The temperature is about 30 degrees. In my country, it is usually hot in summer. In winter, it is cool but not very cold. It rains a lot from June to October.'], analysis: 'Uses "It is" for today\'s weather. Present simple for typical weather. Includes temperature and seasons.' },
          { title: 'Describe the Weather', type: 'exercise', question: 'Write 3 sentences about today\'s weather and 2 about typical weather where you live.', answer: 'Today it is cloudy and cool. It is not raining but it is windy. The temperature is about 22 degrees. In summer, it is usually hot and sunny. In winter, it is cold and it sometimes snows.', answerExplanation: 'Today = present continuous/simple. Typical = present simple with usually/sometimes.' },
        ],
        keyTakeaways: ['"It is + adjective" for weather: It is sunny/cold/rainy', 'Present continuous for right now: "It is raining"', 'Present simple for typical weather: "It rains a lot in July"'],
      },
      { id: 'a1-writing-my-town', title: 'Writing About Your Town or City', description: 'Describe where you live — what is there, what you can do, what you like about it.',
        skill: 'writing', level: 'A1', duration: 8,
        objectives: ['Use "there is/are" to describe places', 'Describe what you can do in your town', 'Use basic adjectives (big, small, old, modern, quiet, busy)'],
        sections: [
          { title: 'Useful Phrases', type: 'rule', content: '"I live in [city]. It is a [big/small] city in [country]." "There is a park / market / hospital." "There are many shops / restaurants / schools." "You can visit the temple / go shopping / swim at the beach." "My favourite place is the park." "I like my city because it is friendly."' },
          { title: 'Example', type: 'example', examples: ['I live in Chiang Mai. It is a beautiful city in the north of Thailand. It is not very big but it is very popular with tourists. There are many temples and markets. There is a famous night market where you can buy food and souvenirs. I love Chiang Mai because the people are friendly and the food is delicious.'], analysis: 'Starts with location, describes size, mentions key places, says why they like it.' },
          { title: 'Describe Your Town', type: 'exercise', question: 'Write 5 sentences about where you live. Include what there is and what you like.', answer: 'I live in a small town. There are a few shops and one school. There is a nice park near my house. You can play football in the park. I like my town because it is quiet and safe.', answerExplanation: 'Uses there is/are, describes places, gives opinion with "because".' },
        ],
        keyTakeaways: ['"There is" + singular place, "there are" + plural places', '"You can + verb" to describe activities', 'Give your opinion: "I like it because..."'],
      },
      { id: 'a1-writing-simple-email', title: 'Writing a Simple Email', description: 'Write basic emails — to a friend, a teacher, or a colleague.',
        skill: 'writing', level: 'A1', duration: 10,
        objectives: ['Use email format: greeting, body, closing', 'Write informal emails to friends', 'Write semi-formal emails to teachers/colleagues'],
        sections: [
          { title: 'Email Format', type: 'rule', content: 'Subject line: short summary ("Meeting on Friday" / "Hello from Maria"). Greeting: Informal: "Hi [name]!" Semi-formal: "Dear [name],". Body: 2-4 short sentences. Closing: Informal: "See you soon!" / "Bye!" Semi-formal: "Best regards," / "Kind regards,". Sign off: Your name.' },
          { title: 'Examples', type: 'example', examples: ['Subject: Party on Saturday', 'Hi Tom!', 'I am having a party on Saturday at 7 PM. It is at my house. Can you come? Please bring some drinks!', 'See you soon!', 'Maria'], analysis: 'Informal email: Hi + name, short body with key details (when, where, what), friendly closing.' },
          { title: 'Write an Email', type: 'exercise', question: 'Write an email to your teacher. Tell them you cannot come to class tomorrow and say why.', answer: 'Subject: Absent tomorrow\nDear Mr Johnson,\nI am writing to tell you that I cannot come to class tomorrow. I have a doctor\'s appointment in the morning. I am sorry. I will come to the next class.\nKind regards,\nMaria', answerExplanation: 'Semi-formal: Dear + title + surname, polite language, Kind regards, full name.' },
        ],
        keyTakeaways: ['Every email needs: greeting, body, closing, name', 'Informal = Hi + first name. Formal = Dear + Mr/Ms + surname', 'Keep the body short: 2-4 sentences'],
      },
      { id: 'a1-writing-job-school', title: 'Writing About Your Job or School', description: 'Describe what you do, where you work or study, and what you like about it.',
        skill: 'writing', level: 'A1', duration: 8,
        objectives: ['Describe your job or studies', 'Use present simple for work routines', 'Express likes and dislikes about work/school'],
        sections: [
          { title: 'Key Phrases', type: 'rule', content: 'Job: "I am a [job]. I work at [place]. I work from [time] to [time]. I work with [people]. My job is [adjective]." School: "I am a student at [school/university]. I study [subject]. My classes are from [time] to [time]. My favourite subject is [subject]."' },
          { title: 'Example', type: 'example', examples: ['I am an engineer. I work at a construction company in Bangkok. I start work at 8 AM and finish at 5 PM. I work with a team of 10 people. I like my job because it is interesting, but sometimes it is very busy.'], analysis: 'Covers: job title, workplace, hours, colleagues, opinion. Uses present simple throughout.' },
          { title: 'Your Turn', type: 'exercise', question: 'Write 5 sentences about your job or studies.', answer: 'I am a student at the university. I study business. My classes are from 9 AM to 3 PM. I like my course because the teachers are good. My favourite subject is marketing.', answerExplanation: 'Covers what, where, when, opinion, and favourite aspect.' },
        ],
        keyTakeaways: ['"I am a [job]" or "I am a student at [school]"', 'Present simple for routines: "I work/study from... to..."', 'Give an opinion: "I like it because..."'],
      },
      { id: 'a1-writing-describe-people', title: 'Describing People\'s Appearance', description: 'Write about what people look like — hair, eyes, height, build, clothes.',
        skill: 'writing', level: 'A1', duration: 8,
        objectives: ['Use "has/have" for features and "is/are" for build', 'Describe hair, eyes, height, and build', 'Describe what someone is wearing'],
        sections: [
          { title: 'Appearance Vocabulary', type: 'rule', content: 'Height: tall, short, medium height. Build: thin, slim, medium build, big, overweight. Hair: long/short, straight/curly/wavy, black/brown/blonde/red/grey. Eyes: blue, brown, green, grey. "He is tall." (is = build/height). "She has long brown hair." (has = features). "He is wearing a blue shirt." (wearing = clothes right now).' },
          { title: 'Order of Adjectives', type: 'tip', content: 'For hair, the order is: length + shape + colour. "She has long straight black hair." (NOT "She has black long straight hair.") For people: height/build first, then features. "He is tall and thin. He has short brown hair and blue eyes."' },
          { title: 'Describe Someone', type: 'exercise', question: 'Describe a friend or family member. Include height, hair, eyes, and what they usually wear.', answer: 'My friend Sara is medium height and slim. She has long curly brown hair and green eyes. She usually wears jeans and a T-shirt.', answerExplanation: 'Uses is (height/build), has (features), wears (clothes). Correct adjective order for hair.' },
        ],
        keyTakeaways: ['"Is" for height/build, "has" for features', 'Hair order: length + shape + colour', '"Is wearing" for now, "usually wears" for typical'],
      },
      { id: 'a1-writing-weekend', title: 'Writing About Your Weekend', description: 'Tell someone what you did last weekend or what you do every weekend.',
        skill: 'writing', level: 'A1', duration: 8,
        objectives: ['Describe past weekend activities', 'Use simple past for completed actions', 'Use present simple for regular weekend habits'],
        sections: [
          { title: 'Past vs Regular Weekends', type: 'rule', content: 'Last weekend (past simple): "I went to the park." "We watched a movie." "I cooked dinner." Every weekend (present simple): "I usually go to the park." "We often watch movies." "I always cook on Sunday." Time words: "On Saturday morning..." "On Sunday afternoon..." "In the evening..." "Last weekend..."' },
          { title: 'Example', type: 'example', examples: ['Last weekend was great! On Saturday morning, I went to the gym. After that, I had lunch with my friends at a Thai restaurant. In the afternoon, we went shopping. On Sunday, I stayed at home and watched Netflix. I also cooked a nice dinner. It was a relaxing weekend.'], analysis: 'Uses past simple (went, had, stayed, cooked). Time phrases give structure. Opinion at end.' },
          { title: 'Your Weekend', type: 'exercise', question: 'Write about what you did last weekend. Include Saturday and Sunday with at least 5 activities.', answer: 'On Saturday, I woke up late. I had breakfast at 10 AM. Then I cleaned my flat. In the afternoon, I met my friend and we went to a café. On Sunday, I did some shopping and cooked a big dinner.', answerExplanation: 'Past simple verbs (woke, had, cleaned, met, went, did, cooked). Clear time structure.' },
        ],
        keyTakeaways: ['Past simple for last weekend: went, ate, watched, played', 'Present simple for every weekend: go, eat, watch, play', 'Use time phrases: On Saturday, In the morning, After that'],
      },
      { id: 'a1-writing-instructions', title: 'Writing Simple Instructions', description: 'Write clear step-by-step instructions — recipes, directions, how to do something.',
        skill: 'writing', level: 'A1', duration: 8,
        objectives: ['Use imperative verbs (put, add, turn, open)', 'Number steps or use sequence words', 'Write a simple recipe or set of instructions'],
        sections: [
          { title: 'Imperatives', type: 'rule', content: 'Instructions use the base verb (no subject): "Open the door." "Turn left." "Add the sugar." "Wait 5 minutes." "Don\'t touch the screen." Sequence: "First, ... Then, ... Next, ... After that, ... Finally, ..."' },
          { title: 'Example Recipe', type: 'example', examples: ['How to Make Toast:', '1. Take two slices of bread.', '2. Put them in the toaster.', '3. Wait 2 minutes.', '4. Take the toast out carefully.', '5. Put butter on the toast.', '6. Enjoy!'], analysis: 'Numbered steps. Each starts with an imperative verb. Short, clear sentences. No "you" needed.' },
          { title: 'Write Instructions', type: 'exercise', question: 'Write 5-step instructions for making a cup of tea.', answer: '1. Boil some water. 2. Put a tea bag in a cup. 3. Pour the hot water into the cup. 4. Wait 3 minutes. 5. Remove the tea bag and add milk or sugar.', answerExplanation: 'Each step starts with an imperative. Numbered for clarity. Short and clear.' },
        ],
        keyTakeaways: ['Imperatives: base verb with no subject (Open, Add, Turn)', 'Number your steps or use First/Then/Next/Finally', 'One action per step keeps instructions clear'],
      },
      { id: 'a1-writing-invitation', title: 'Writing an Invitation', description: 'Invite someone to a party, dinner, event, or outing in writing.',
        skill: 'writing', level: 'A1', duration: 8,
        objectives: ['Include all key details (what, when, where)', 'Use friendly, inviting language', 'Ask for a reply (RSVP)'],
        sections: [
          { title: 'Invitation Essentials', type: 'rule', content: 'Every invitation needs: WHAT: "a birthday party" / "dinner" / "a picnic". WHEN: day + date + time. WHERE: address or place name. Extra info: "Please bring..." / "The theme is..." / "Food and drinks provided." RSVP: "Please let me know by Friday." / "Can you come?"' },
          { title: 'Example', type: 'example', examples: ['Hi everyone!', 'You are invited to my birthday party!', 'Date: Saturday 15th August', 'Time: 7:00 PM', 'Place: My house — 42 Park Road', 'There will be food, drinks, and music!', 'Please let me know if you can come.', 'See you there! — Maria'], analysis: 'Clear format with all key details. Friendly tone. Asks for confirmation.' },
          { title: 'Write an Invitation', type: 'exercise', question: 'Write an invitation to a dinner at your house on Saturday evening.', answer: 'Hi friends! You are invited to dinner at my house this Saturday. Date: Saturday 10th August. Time: 7:30 PM. Place: My flat, 15 River Road. I am cooking Italian food! Please tell me if you can come by Thursday. See you there!', answerExplanation: 'Has what (dinner), when (Saturday 7:30 PM), where (address), extra info (Italian food), RSVP (by Thursday).' },
        ],
        keyTakeaways: ['Always include: what, when, where', 'Use friendly language: "You are invited!"', 'Ask people to reply: "Please let me know if you can come"'],
      },
      { id: 'a1-writing-abilities', title: 'Writing About What You Can Do', description: 'Describe your skills and abilities using can and can\'t.',
        skill: 'writing', level: 'A1', duration: 8,
        objectives: ['Use "can" for abilities and "can\'t" for things you cannot do', 'Write about skills, languages, and talents', 'Use "well", "a little", "quite well"'],
        sections: [
          { title: 'Can and Can\'t', type: 'rule', content: '"I can swim." "I can\'t drive." "She can speak three languages." "He can\'t cook." Adding degree: well = good level: "I can swim well." quite well = OK level: "I can cook quite well." a little = low level: "I can speak French a little." very well = high level: "She can sing very well."' },
          { title: 'Example', type: 'example', examples: ['I can speak Thai and English very well. I can also speak a little Japanese. I can cook quite well — I make good fried rice! I can swim but I can\'t surf. I can drive a car but I can\'t ride a motorbike. I can play guitar a little.'], analysis: 'Uses can/can\'t with different degree words. Shows range of abilities.' },
          { title: 'Your Abilities', type: 'exercise', question: 'Write about 3 things you can do (with degree words) and 2 things you can\'t do.', answer: 'I can speak English quite well. I can cook very well. I can play tennis a little. I can\'t drive a car. I can\'t play any musical instrument.', answerExplanation: 'Can + degree (quite well, very well, a little). Can\'t for things you cannot do.' },
        ],
        keyTakeaways: ['Can + base verb for abilities', 'Degree words: a little < quite well < well < very well', 'Can\'t = cannot (one word in informal writing)'],
      },
      { id: 'a1-writing-spelling', title: 'Spelling Rules for Beginners', description: 'Avoid the most common spelling mistakes with these simple rules.',
        skill: 'writing', level: 'A1', duration: 10,
        objectives: ['Apply basic English spelling rules', 'Avoid common spelling mistakes', 'Know tricky words that don\'t follow rules'],
        sections: [
          { title: 'Key Spelling Rules', type: 'rule', content: 'Plurals: add -s (cats, dogs), add -es after s/sh/ch/x (buses, dishes, watches, boxes), change y to -ies (city→cities, baby→babies BUT boy→boys, day→days — keep y after a vowel). Doubling: big→bigger, hot→hotter, run→running (short vowel + one consonant = double). Silent e: make→making, write→writing (drop the e before -ing). ie/ei: i before e except after c: believe, receive.' },
          { title: 'Tricky Words', type: 'tip', content: 'These words are often spelled wrong: because (NOT becuase), beautiful (NOT beautifull), different (NOT diffrent), Wednesday (silent d), February (silent r), friend (ie not ei), their/there/they\'re (three different words!), your/you\'re (two different words!). Tip: read a lot — your brain learns spelling patterns from reading.' },
          { title: 'Fix the Spelling', type: 'exercise', question: 'Correct: "I have two beautifull babys. Thier names are diffrent — one is Anna and the other is becuase I like that name."', answer: '"I have two beautiful babies. Their names are different — one is Anna and the other is Maria because I like that name."', answerExplanation: 'beautifull→beautiful, babys→babies (y→ies), Thier→Their, diffrent→different, becuase→because.' },
        ],
        keyTakeaways: ['Plurals: -s, -es (after s/sh/ch/x), y→ies (after consonant)', 'Drop silent e before -ing: make→making', 'Learn tricky words by heart: because, beautiful, different'],
      },
    ],
  },
  {
    id: 'a2-writing',
    name: 'A2: Writing Skills',
    description: 'Write paragraphs, past experiences, letters, reviews, and short stories.',
    icon: '✏️',
    lessons: [
      { id: 'a2-writing-paragraphs', title: 'Writing Paragraphs', description: 'Move from single sentences to structured paragraphs with a topic sentence.',
        skill: 'writing', level: 'A2', duration: 10,
        objectives: ['Write a paragraph with a topic sentence', 'Add 3-4 supporting sentences', 'End with a concluding sentence'],
        sections: [
          { title: 'Paragraph Structure', type: 'rule', content: 'A paragraph has 3 parts: Topic sentence = the main idea (first sentence): "My favourite season is summer." Supporting sentences = details, reasons, examples (middle): "The weather is warm and sunny. I can go swimming. I don\'t have school in summer." Concluding sentence = summary or final thought (last): "Summer always makes me happy."' },
          { title: 'Example Paragraph', type: 'example', examples: ['Bangkok is an exciting city to visit. There are many beautiful temples, like Wat Phra Kaew. The street food is delicious and very cheap. You can also go shopping at big markets like Chatuchak. The nightlife is fun too. Bangkok has something for everyone.'], analysis: 'Topic sentence (exciting city), 4 supporting sentences (temples, food, shopping, nightlife), concluding sentence (something for everyone).' },
          { title: 'Write a Paragraph', type: 'exercise', question: 'Write a paragraph about your favourite hobby. Include a topic sentence, 3 supporting sentences, and a concluding sentence.', answer: 'My favourite hobby is photography. I take photos of nature and city streets. I use my phone camera because it is easy to carry. I share my best photos on Instagram. Photography helps me see the world differently.', answerExplanation: 'Topic sentence (photography), 3 supports (what, equipment, sharing), conclusion (world differently).' },
        ],
        keyTakeaways: ['Every paragraph needs a topic sentence first', '3-4 supporting sentences give details and examples', 'A concluding sentence wraps up the main idea'],
      },
      { id: 'a2-writing-past-tense', title: 'Writing in the Past Tense', description: 'Tell stories about things that happened — yesterday, last week, last year.',
        skill: 'writing', level: 'A2', duration: 10,
        objectives: ['Use regular past forms (-ed) in writing', 'Use common irregular past forms correctly', 'Avoid mixing present and past tense'],
        sections: [
          { title: 'Past Simple in Writing', type: 'rule', content: 'Regular: add -ed: walk→walked, play→played, cook→cooked. Spelling changes: live→lived (just +d), stop→stopped (double consonant), study→studied (y→ied). Common irregulars: go→went, have→had, see→saw, eat→ate, make→made, come→came, take→took, buy→bought, get→got, do→did, say→said, think→thought, give→gave, find→found, know→knew.' },
          { title: 'Stay Consistent', type: 'tip', content: 'Common mistake: mixing tenses in one story. Wrong: "I went to the shop and I buy some bread." Right: "I went to the shop and bought some bread." Rule: if you start a story in the past, keep ALL verbs in the past. Time words: yesterday, last week/month/year, ago, in 2020, when I was young.' },
          { title: 'Write a Story', type: 'exercise', question: 'Write 5 sentences about something you did last weekend. Use past simple throughout.', answer: 'Last Saturday, I went to a market with my friend. We walked around and looked at the stalls. I bought a new T-shirt. Then we ate lunch at a noodle shop. It was a fun day.', answerExplanation: 'All verbs in past simple: went, walked, looked, bought, ate, was. No present tense mixed in.' },
        ],
        keyTakeaways: ['Regular past: +ed (walked, played, cooked)', 'Irregular past: must memorise (go→went, eat→ate)', 'Don\'t mix tenses: keep the whole story in past simple'],
      },
      { id: 'a2-writing-past-experiences', title: 'Writing About Past Experiences', description: 'Share memorable experiences — holidays, achievements, important days.',
        skill: 'writing', level: 'A2', duration: 10,
        objectives: ['Structure a personal experience narrative', 'Use time sequencing (first, then, after that)', 'Add feelings and opinions'],
        sections: [
          { title: 'Experience Structure', type: 'rule', content: 'When: "Last summer..." / "In 2024..." / "When I was 18..." Where: "I went to..." / "I was in..." What happened: Use past simple + sequence words. Feelings: "I felt happy/excited/nervous/surprised." "It was amazing/scary/unforgettable." Opinion: "It was the best day of my life." "I will never forget it."' },
          { title: 'Example', type: 'example', examples: ['Last year, I went to Japan for the first time. First, I flew to Tokyo. It was a very long flight! I stayed in a small hotel in Shinjuku. The next day, I visited the temples in Asakusa. Then I tried sushi at a local restaurant — it was delicious! After three days in Tokyo, I took the bullet train to Kyoto. I felt so excited! It was the best holiday I have ever had.'], analysis: 'Clear time sequence. Past simple throughout. Includes feelings (excited) and opinion (best holiday).' },
          { title: 'Share an Experience', type: 'exercise', question: 'Write about a memorable day in your life (6-8 sentences). Include when, where, what happened, and how you felt.', answer: 'Two years ago, I graduated from university. The ceremony was at the main hall. First, we listened to speeches. Then they called our names one by one. I felt very proud when I walked on stage. My parents took many photos. After that, we had a big dinner together. It was one of the happiest days of my life.', answerExplanation: 'When (two years ago), where (main hall), events in order (speeches, names, stage), feelings (proud, happiest).' },
        ],
        keyTakeaways: ['Structure: when → where → what happened → how you felt', 'Use sequence words: first, then, after that, finally', 'End with feelings or an opinion to make it personal'],
      },
      { id: 'a2-writing-diary', title: 'Writing a Diary Entry', description: 'Record your day, thoughts, and feelings in a personal diary.',
        skill: 'writing', level: 'A2', duration: 8,
        objectives: ['Use diary format (date, greeting)', 'Write about events and feelings', 'Use informal, personal language'],
        sections: [
          { title: 'Diary Format', type: 'rule', content: 'Date: Monday 5th August 2026. Opening: "Dear Diary," or just start writing. Content: what happened, how you felt, what you thought. Closing: optional — "Good night" or just end. Style: personal, informal, use "I" a lot, short sentences OK, express emotions freely.' },
          { title: 'Example Entry', type: 'example', examples: ['Tuesday 6th August 2026', 'Dear Diary,', 'Today was a strange day. I had a job interview in the morning. I was so nervous! I think it went well — the interviewer smiled a lot. After the interview, I had coffee with my friend Nok. She made me feel better. I hope I get the job! I will know by Friday. Fingers crossed!'], analysis: 'Personal tone. Mix of events (interview, coffee) and emotions (nervous, hope). Uses exclamation marks for emphasis.' },
          { title: 'Write an Entry', type: 'exercise', question: 'Write a diary entry about today. Include at least one event and one feeling.', answer: 'Wednesday 7th August 2026\nDear Diary,\nToday was a good day. I studied English for two hours in the morning. I learned new vocabulary about travel. In the afternoon, I went for a walk in the park. The weather was perfect. I feel happy because I am making progress with my English. Tomorrow I want to practise speaking!', answerExplanation: 'Has date, greeting, events (studied, walked), feelings (happy, making progress), future plan.' },
        ],
        keyTakeaways: ['Start with the date and "Dear Diary"', 'Mix events with feelings and thoughts', 'Informal style: contractions, exclamation marks, personal language'],
      },
      { id: 'a2-writing-informal-letter', title: 'Writing a Short Informal Letter', description: 'Write a friendly letter to someone you know — thank you, catch up, or congratulations.',
        skill: 'writing', level: 'A2', duration: 10,
        objectives: ['Use informal letter format', 'Open and close a letter appropriately', 'Write about news, thanks, or congratulations'],
        sections: [
          { title: 'Informal Letter Format', type: 'rule', content: 'Your address: top right corner (optional in modern letters). Date: below address. Greeting: "Dear [first name]," / "Hi [name]!" Opening line: "How are you?" / "Thanks for your letter!" / "Sorry I haven\'t written for a while." Body: your news, questions, etc. Closing line: "Write back soon!" / "Hope to hear from you!" Sign off: "Love," / "Best wishes," / "Take care," + your first name.' },
          { title: 'Example', type: 'example', examples: ['Dear Tom,', 'Thanks for your email! It was great to hear from you. Congratulations on your new job — that\'s amazing news!', 'I\'m doing well. I started a new English course last month. The teacher is really good. I\'m also learning to cook Thai food — it\'s harder than it looks!', 'How is your family? Are you still playing football at the weekend?', 'Write back soon!', 'Best wishes,', 'Maria'], analysis: 'Responds to Tom\'s news, shares own news, asks questions back. Warm, friendly tone.' },
          { title: 'Write a Letter', type: 'exercise', question: 'Write a letter to a friend who has just moved to a new city. Ask how they are and share some of your news.', answer: 'Hi Sarah!\nHow are you? How is the new city? I hope you like it there!\nThings are good here. Last week I got a new job at a café. The people are really nice. I also adopted a cat — her name is Luna!\nDo you like your new flat? Have you made any friends yet? I miss you! Let\'s video call soon.\nLove,\nAlex', answerExplanation: 'Asks about friend, shares own news (job, cat), asks questions, suggests catching up. Warm tone.' },
        ],
        keyTakeaways: ['Greeting: "Dear/Hi" + first name', 'Ask about them, share your news, ask questions', 'Close warmly: "Write back soon!" + "Love/Best wishes"'],
      },
      { id: 'a2-writing-future-plans', title: 'Writing About Future Plans', description: 'Describe what you are going to do — plans, goals, and dreams.',
        skill: 'writing', level: 'A2', duration: 8,
        objectives: ['Use "going to" for planned future', 'Use "want to" and "hope to" for wishes', 'Write about short-term and long-term plans'],
        sections: [
          { title: 'Future Phrases', type: 'rule', content: 'Planned/decided: "I am going to study medicine." "I am going to travel to Japan next year." Hopes/wishes: "I want to learn French." "I hope to get a good job." "I would like to live abroad." Predictions: "I think I will be a doctor." Short-term: "This weekend, I am going to visit my parents." Long-term: "In five years, I hope to have my own business."' },
          { title: 'Example', type: 'example', examples: ['I have many plans for the future. Next month, I am going to start a new English course. I want to get an IELTS score of 7. After that, I am going to apply to universities in Australia. I hope to study computer science. In five years, I would like to work at a tech company. I think it will be difficult but I am excited!'], analysis: 'Mix of going to (decided plans), want/hope/would like (wishes), will (predictions). Short and long-term.' },
          { title: 'Your Future Plans', type: 'exercise', question: 'Write about your plans: one for next week, one for next year, one for 5 years from now.', answer: 'Next week, I am going to clean my apartment and start exercising. Next year, I want to travel to Europe with my friends. In five years, I hope to have a good career and buy my own flat.', answerExplanation: 'Uses going to (next week plan), want to (next year wish), hope to (long-term dream).' },
        ],
        keyTakeaways: ['"Going to" for decided plans', '"Want to / hope to / would like to" for wishes', 'Include short-term AND long-term plans'],
      },
      { id: 'a2-writing-describe-place', title: 'Describing a Place in Detail', description: 'Write vivid descriptions of places — cities, buildings, natural areas, and rooms.',
        skill: 'writing', level: 'A2', duration: 10,
        objectives: ['Use adjectives before nouns correctly', 'Describe using the five senses', 'Organise description by location (left, right, in the centre)'],
        sections: [
          { title: 'Description Techniques', type: 'rule', content: 'Adjective order: size + age + colour + material. "A big old red brick building." Location: "On the left, there is... In the centre, you can see... On the right, there is..." Senses: See: "The beach is white and the water is blue." Hear: "You can hear the birds singing." Smell: "The market smells of fresh bread." Feel: "The sand is warm under your feet."' },
          { title: 'Example', type: 'example', examples: ['Chatuchak Market is one of the biggest markets in the world. It is in Bangkok, Thailand. When you arrive, the first thing you notice is the noise — hundreds of people talking and laughing. On the left, there are stalls selling clothes and bags. In the centre, you can find delicious street food. The smell of grilled meat fills the air. On the right, there are shops with plants, pets, and home decorations. It is a colourful, exciting, and sometimes overwhelming place!'], analysis: 'Uses location words (left, centre, right), senses (noise, smell), adjectives (biggest, colourful, exciting).' },
          { title: 'Describe a Place', type: 'exercise', question: 'Describe a place you know well (a park, market, beach, or building) in 5-6 sentences using senses and location words.', answer: 'The park near my house is beautiful and quiet. In the centre, there is a large lake with small boats. On the left, there are tall trees and a path for joggers. You can hear birds singing in the morning. The air smells fresh and clean. It is my favourite place to relax.', answerExplanation: 'Uses location (centre, left), senses (hear birds, smell fresh air), adjectives (beautiful, quiet, large, tall).' },
        ],
        keyTakeaways: ['Use location words: on the left/right, in the centre', 'Describe using senses: see, hear, smell, feel', 'Adjectives make descriptions vivid: big, old, colourful'],
      },
      { id: 'a2-writing-short-story', title: 'Writing a Short Story', description: 'Create a simple story with a beginning, middle, and end.',
        skill: 'writing', level: 'A2', duration: 12,
        objectives: ['Structure a story: beginning, middle, end', 'Use past simple throughout', 'Add direct speech and feelings'],
        sections: [
          { title: 'Story Structure', type: 'rule', content: 'Beginning: introduce characters and setting: "One day, Maria was walking to work." "Last summer, two friends decided to go camping." Middle: the main events (what happened): "Suddenly, it started to rain." "They found a strange door in the wall." End: how it finished: "Finally, they arrived home safely." "In the end, everything was OK."' },
          { title: 'Example', type: 'example', examples: ['One rainy afternoon, Tom was walking home from school. Suddenly, he heard a strange noise behind him. He turned around but nobody was there. He walked faster. Then he heard it again — a small cry. He looked down and saw a tiny kitten hiding under a car. It was wet and cold. Tom picked it up carefully and put it inside his jacket. He took it home and gave it some milk. His mum said, "Can we keep it?" Tom smiled. "I\'ve already named her — Lucky!"'], analysis: 'Beginning (walking home), middle (strange noise, found kitten), end (took home, named Lucky). Uses past simple, direct speech, and feelings.' },
          { title: 'Start a Story', type: 'exercise', question: 'Write the beginning and middle of a story that starts with: "Last Friday, I got a very strange phone call..."', answer: 'Last Friday, I got a very strange phone call. A man said, "Come to the old library at 3 PM. I have something for you." I was confused but also curious. I went to the library and found a small box on the front step. Inside, there was a gold key and a note that said, "Use this wisely."', answerExplanation: 'Introduces the mystery (phone call), builds tension (confused, curious), develops plot (box, key, note).' },
        ],
        keyTakeaways: ['Beginning: characters + setting. Middle: events. End: resolution.', 'Past simple for the main events', 'Add feelings and dialogue to make it interesting'],
      },
      { id: 'a2-writing-comparing', title: 'Comparing Two Things in Writing', description: 'Write about similarities and differences using comparatives.',
        skill: 'writing', level: 'A2', duration: 10,
        objectives: ['Use comparatives: bigger, more expensive, better', 'Use "both", "but", "while", "however"', 'Structure a comparison paragraph'],
        sections: [
          { title: 'Comparison Language', type: 'rule', content: 'Comparatives: short adj + -er: "Tokyo is bigger than Bangkok." long adj: more + adj: "Tokyo is more expensive than Bangkok." Similarities: "Both cities have good public transport." "Tokyo and Bangkok are both exciting." Differences: "Tokyo is cleaner, but Bangkok is friendlier." "While Tokyo has trains, Bangkok has boats." "However, Bangkok is much cheaper."' },
          { title: 'Structure', type: 'tip', content: 'Option 1 — Block: describe A completely, then B completely. Option 2 — Point by point: compare one aspect at a time (size, cost, food, transport). Point by point is usually clearer: "For transport, Tokyo has an excellent train system. Bangkok also has a train but it is smaller. However, Bangkok has tuk-tuks and river boats, which are fun."' },
          { title: 'Compare Two Things', type: 'exercise', question: 'Compare two cities, foods, or activities you know. Use at least 2 comparatives and 1 similarity.', answer: 'Thai food and Italian food are both delicious. However, Thai food is spicier than Italian food. Italian food uses more cheese and bread. Both use fresh ingredients. Thai food is usually cheaper than Italian food in restaurants. I prefer Thai food because I love spicy dishes!', answerExplanation: 'Uses comparatives (spicier, cheaper, more cheese), similarity (both delicious, both fresh), contrast (however).' },
        ],
        keyTakeaways: ['Short adjectives: + er (bigger, cheaper, faster)', 'Long adjectives: more + adj (more expensive, more interesting)', '"Both" for similarities, "however/but/while" for differences'],
      },
      { id: 'a2-writing-informal-email', title: 'Writing Informal Emails', description: 'Write casual emails to friends — catching up, making plans, sharing news.',
        skill: 'writing', level: 'A2', duration: 8,
        objectives: ['Use informal email conventions', 'Structure: greeting, reason, details, closing', 'Use contractions and friendly language'],
        sections: [
          { title: 'Informal Email Style', type: 'rule', content: 'Subject: short and clear ("Catch up!", "This weekend?", "Great news!"). Greeting: "Hi [name]!" / "Hey!" Opening: "How are you?" / "How\'s it going?" / "Long time no see!" Use contractions: I\'m, I\'ve, don\'t, can\'t, it\'s. Use exclamation marks for enthusiasm! Ask questions: show you care about the other person. Closing: "Speak soon!" / "Can\'t wait to hear from you!" / "Bye for now!"' },
          { title: 'Example', type: 'example', examples: ['Subject: Weekend plans?', 'Hey Lisa!', 'How\'s it going? I haven\'t seen you in ages!', 'I\'m planning a picnic in the park this Saturday. Do you want to come? I\'m going to bring sandwiches and cake. Tom and Sara are coming too.', 'Let me know if you\'re free!', 'Bye for now,', 'Anna'], analysis: 'Casual greeting, reason for writing (picnic), details (when, what, who), question (want to come?), friendly closing.' },
          { title: 'Write an Email', type: 'exercise', question: 'Write an informal email to a friend suggesting a movie night at your place.', answer: 'Subject: Movie night!\nHey Jake!\nHow are you? I was thinking — do you want to come over for a movie night on Friday? I\'ve got some new films and I\'ll make popcorn! Maybe around 7 PM?\nLet me know if you\'re free.\nCheers,\nAlex', answerExplanation: 'Casual tone, contractions (I\'ve, I\'ll), suggestion with details (Friday, 7 PM, popcorn), asks for response.' },
        ],
        keyTakeaways: ['Use contractions (I\'m, don\'t) for a casual tone', 'Ask questions to show interest in the other person', 'Keep it short and friendly — emails aren\'t essays'],
      },
      { id: 'a2-writing-directions', title: 'Giving Written Directions', description: 'Write clear directions to help someone find a place.',
        skill: 'writing', level: 'A2', duration: 8,
        objectives: ['Use direction verbs (turn, go, walk, cross)', 'Use landmarks as reference points', 'Write step-by-step directions'],
        sections: [
          { title: 'Direction Language', type: 'rule', content: 'Verbs: go straight (on), turn left/right, walk past, cross (the road/bridge), take the first/second/third turning. Landmarks: "Go past the bank." "You will see a church on your left." "It is opposite the park." "It is next to the supermarket." "It is on the corner of Main Street and Park Road." Distance: "Walk for about 5 minutes." "It is 200 metres on the right."' },
          { title: 'Example', type: 'example', examples: ['From the train station, go straight on Park Road. Walk past the bank and the pharmacy. Take the second turning on the right — that is Hill Street. Walk along Hill Street for about 3 minutes. You will see a large church on your left. My house is opposite the church — number 42. It has a red door. You can\'t miss it!'], analysis: 'Step by step. Uses landmarks (bank, pharmacy, church). Gives distance (3 minutes). Ends with identifying feature (red door).' },
          { title: 'Write Directions', type: 'exercise', question: 'Write directions from a bus stop to your home (or an imaginary home). Use at least 4 direction words.', answer: 'From the bus stop, turn right and go straight for 2 minutes. Walk past the convenience store. Turn left at the traffic lights. My building is on the right, next to the park. It is the tall white building — apartment 5B on the 5th floor.', answerExplanation: 'Uses turn right, go straight, walk past, turn left. Landmarks: convenience store, traffic lights, park. Identifying detail: tall white building.' },
        ],
        keyTakeaways: ['Go straight, turn left/right, walk past, cross', 'Use landmarks: "opposite the park", "next to the bank"', 'End with an identifying feature so they know they\'re there'],
      },
      { id: 'a2-writing-celebrations', title: 'Writing About Celebrations & Festivals', description: 'Describe holidays, festivals, and special occasions in your culture.',
        skill: 'writing', level: 'A2', duration: 10,
        objectives: ['Describe when, where, and how people celebrate', 'Use present simple for customs', 'Use vocabulary for celebrations (decorate, gather, celebrate)'],
        sections: [
          { title: 'Celebration Vocabulary', type: 'rule', content: 'Events: festival, holiday, ceremony, parade, feast. Actions: celebrate, decorate, gather (come together), exchange (gifts), prepare, wear (traditional clothes), light (candles/fireworks). "People celebrate Songkran in April." "We decorate our houses with lights." "Families gather for a big meal." "Children wear traditional clothes." "At midnight, there are fireworks."' },
          { title: 'Example', type: 'example', examples: ['Songkran is the Thai New Year. People celebrate it from 13th to 15th April every year. It is also called the Water Festival because people throw water at each other! Before Songkran, families clean their houses and prepare special food. On the first day, people go to temples and pray. Then the water fights begin! Everyone goes outside with water guns and buckets. It is the most fun holiday in Thailand.'], analysis: 'Covers: what (Thai New Year), when (April 13-15), preparations (clean, cook), customs (temples, water fights), opinion (most fun).' },
          { title: 'Describe a Festival', type: 'exercise', question: 'Write about a celebration in your country. Include when it happens, what people do, and why it is special.', answer: 'Christmas is celebrated on 25th December in the UK. Before Christmas, people decorate their houses with lights and put up a Christmas tree. On Christmas Day, families gather for a big lunch with turkey, vegetables, and Christmas pudding. People exchange gifts in the morning. Children believe that Santa Claus brings the presents at night. It is a special time for being with family.', answerExplanation: 'Covers when (25th Dec), preparations (decorate, tree), customs (lunch, gifts, Santa), why special (family time).' },
        ],
        keyTakeaways: ['Cover: when, preparations, customs, why it matters', 'Present simple for things that happen every year', 'Celebration verbs: celebrate, decorate, gather, exchange, prepare'],
      },
      { id: 'a2-writing-describe-photo', title: 'Describing a Photo or Picture', description: 'Describe what you see in an image — people, places, actions, and atmosphere.',
        skill: 'writing', level: 'A2', duration: 10,
        objectives: ['Use present continuous for actions in a photo', 'Describe position (in the foreground, background)', 'Speculate: "I think...", "Maybe...", "It looks like..."'],
        sections: [
          { title: 'Photo Description Language', type: 'rule', content: 'Position: "In the foreground / background / centre..." "On the left / right..." "At the top / bottom..." Actions: "A man is sitting on a bench." "Two children are playing." "A woman is walking her dog." Speculation: "I think it is summer because..." "It looks like a park." "They seem happy." "Maybe they are on holiday."' },
          { title: 'Example', type: 'example', examples: ['In this photo, I can see a beach scene. In the foreground, a family is sitting on the sand. The mother is reading a book and the father is building a sandcastle with two children. In the background, you can see the blue sea and some boats. On the right, there is a beach bar with colourful umbrellas. I think it is summer because the sky is clear and everyone is wearing swimwear. It looks like a happy, relaxing day.'], analysis: 'Position words (foreground, background, right). Present continuous (is reading, is building). Speculation (I think, it looks like).' },
          { title: 'Describe a Scene', type: 'exercise', question: 'Imagine a busy café scene. Describe what you "see" using position words and present continuous.', answer: 'In this photo, I can see a busy café. In the foreground, a young woman is drinking coffee and looking at her phone. On the left, two men are talking and laughing. In the background, a waiter is carrying plates of food. It looks like a popular place because every table is full.', answerExplanation: 'Uses position (foreground, left, background), present continuous (is drinking, are talking, is carrying), speculation (it looks like).' },
        ],
        keyTakeaways: ['Present continuous for actions in photos: "She is reading"', 'Position: foreground, background, left, right, centre', '"I think..." and "It looks like..." for guessing'],
      },
      { id: 'a2-writing-review', title: 'Writing a Review', description: 'Write a review of a restaurant, hotel, film, or product.',
        skill: 'writing', level: 'A2', duration: 10,
        objectives: ['Structure a review: what, experience, opinion, recommendation', 'Use opinion adjectives (excellent, terrible, average)', 'Give a star rating and summary'],
        sections: [
          { title: 'Review Structure', type: 'rule', content: 'What: name, type, location. Experience: what you did/had/saw. Positive: "The food was delicious." "The staff were friendly." "The room was clean and comfortable." Negative: "The service was slow." "It was too expensive." "The noise from the street was annoying." Recommendation: "I highly recommend it." "I would not go again." "It is worth visiting if you are in the area." Star rating: ★★★★★ (1-5 stars).' },
          { title: 'Example', type: 'example', examples: ['★★★★☆ — Mango Tree Restaurant, Bangkok', 'I visited Mango Tree last Saturday evening with friends. The restaurant is in a beautiful old building near the river. We ordered pad thai, green curry, and mango sticky rice. The food was absolutely delicious — some of the best Thai food I have ever had! The service was a little slow, but the waiters were friendly and helpful. Prices are average for the area. I highly recommend this restaurant for a special dinner!'], analysis: 'Star rating, name and location, what they had, positive (delicious, friendly), negative (slow), recommendation.' },
          { title: 'Write a Review', type: 'exercise', question: 'Write a review of a restaurant or café you have been to (positive or negative).', answer: '★★★☆☆ — City Café, Main Street\nI went to City Café last week for lunch. The café is small and modern with nice decoration. I ordered a chicken sandwich and a coffee. The sandwich was OK but not very big for the price. The coffee was good. The staff were friendly but I waited 20 minutes for my food. It is an OK place for a quick coffee but I would not go for a full meal.', answerExplanation: 'Star rating, name, what they ordered, positives (modern, friendly), negatives (small portion, slow), balanced recommendation.' },
        ],
        keyTakeaways: ['Structure: what + experience + good + bad + recommendation', 'Balance positive and negative points', 'End with a clear recommendation'],
      },
      { id: 'a2-writing-health', title: 'Writing About Health & Fitness', description: 'Describe health habits, fitness routines, and common illnesses.',
        skill: 'writing', level: 'A2', duration: 8,
        objectives: ['Use health and body vocabulary', 'Describe healthy and unhealthy habits', 'Write about illness: symptoms and advice'],
        sections: [
          { title: 'Health Phrases', type: 'rule', content: 'Healthy habits: "I exercise three times a week." "I eat a balanced diet." "I drink two litres of water a day." "I get eight hours of sleep." Unhealthy habits: "I eat too much junk food." "I don\'t exercise enough." "I stay up too late." Illness: "I have a headache / stomachache / cold / fever / cough / sore throat." "I feel tired / dizzy / sick." "I should see a doctor."' },
          { title: 'Example', type: 'example', examples: ['I try to be healthy but it is not always easy. I go to the gym twice a week and I walk to work every day. I eat a lot of vegetables and fruit. However, I also love chocolate and I eat too much of it! I usually sleep about 7 hours a night, but sometimes I stay up late watching TV. I think my health is OK, but I should drink more water and eat less sugar.'], analysis: 'Mix of healthy and unhealthy habits. Honest and personal. Uses "should" for improvement goals.' },
          { title: 'Your Health Habits', type: 'exercise', question: 'Write about your health: 3 good habits and 2 things you should improve.', answer: 'I eat breakfast every morning and I cook my own food most days. I walk to the office, which takes about 20 minutes. However, I don\'t exercise enough — I should go to the gym more often. I also drink too much coffee. I should replace some coffee with water.', answerExplanation: 'Good habits (breakfast, cooking, walking), things to improve (exercise, coffee). Uses should for advice to self.' },
        ],
        keyTakeaways: ['Present simple for habits: "I exercise", "I eat"', '"Too much/many" for excess, "not enough" for lack', '"I should..." for giving advice (to yourself or others)'],
      },
      { id: 'a2-writing-sequence-words', title: 'Ordering Ideas with Sequence Words', description: 'Use time words to organise your writing clearly: first, then, after that, finally.',
        skill: 'writing', level: 'A2', duration: 8,
        objectives: ['Use sequence words to organise events', 'Choose between first/then/next/after that/finally', 'Use time clauses (before, after, when, while)'],
        sections: [
          { title: 'Sequence Words', type: 'rule', content: 'For ordering steps: first, then/next, after that, finally/lastly. For time relationships: before = earlier: "Before I left, I checked my bag." after = later: "After dinner, we watched TV." when = at that moment: "When I arrived, everyone was there." while = at the same time: "While I was cooking, he was cleaning." as soon as = immediately after: "As soon as I got home, I called my mum."' },
          { title: 'Example', type: 'example', examples: ['Yesterday I had a very busy morning. First, I woke up early and took a shower. Then I had a quick breakfast. After that, I walked to the bus stop. While I was waiting, I checked my emails on my phone. When the bus arrived, it was very crowded. Finally, I got to work at 9 AM — just in time!'], analysis: 'Clear time sequence: first → then → after that → while → when → finally. Each sentence is connected to the one before.' },
          { title: 'Reorder and Connect', type: 'exercise', question: 'Put in order and add sequence words: (a) ate dinner (b) got home (c) watched TV (d) cooked pasta (e) had a shower', answer: 'First, I got home from work. Then I had a shower. After that, I cooked pasta. Next, I ate dinner. Finally, I watched TV and went to bed.', answerExplanation: 'Logical order: arrive → shower → cook → eat → relax. Connected with first/then/after that/next/finally.' },
        ],
        keyTakeaways: ['First → Then → After that → Next → Finally', 'Before/after for time relationships', 'While for two actions at the same time'],
      },
      { id: 'a2-writing-time-expressions', title: 'Using Time Expressions in Writing', description: 'Make your writing precise with time words: ago, last, in, for, since, until.',
        skill: 'writing', level: 'A2', duration: 8,
        objectives: ['Use past time expressions: ago, last, in + year', 'Use future time expressions: next, in + time, tomorrow', 'Use duration: for + period, from...to...'],
        sections: [
          { title: 'Time Expressions', type: 'rule', content: 'Past: "two days ago", "last week/month/year", "in 2020", "yesterday", "the day before yesterday". Future: "tomorrow", "next week/month/year", "in three days", "the day after tomorrow", "soon". Duration: "for two hours/days/years", "from 9 to 5", "from Monday to Friday", "until Friday" (= up to that point). Frequency: "every day/week/month", "once/twice a week", "three times a month".' },
          { title: 'Position in Sentence', type: 'tip', content: 'Usually at the start or end of a sentence: "Last week, I went to the cinema." = "I went to the cinema last week." (both correct). Frequency adverbs go before the main verb: "I always eat breakfast." "She never watches TV." "We sometimes play tennis." But after "be": "He is always late." "They are never bored."' },
          { title: 'Add Time Expressions', type: 'exercise', question: 'Rewrite these sentences with appropriate time expressions: (1) "I started learning English." (2) "I will visit Japan." (3) "I go swimming."', answer: '(1) I started learning English three years ago. (2) I will visit Japan next summer. (3) I go swimming twice a week.', answerExplanation: 'Added: ago (past), next (future), twice a week (frequency). Each makes the sentence more specific.' },
        ],
        keyTakeaways: ['Past: ago, last, in + year. Future: next, in + time, tomorrow.', 'Duration: for + period. Until = up to that point.', 'Frequency adverbs before main verb, after "be"'],
      },
      { id: 'a2-writing-travel', title: 'Writing About Travel Experiences', description: 'Share a trip you took — where, when, what you did, and whether you enjoyed it.',
        skill: 'writing', level: 'A2', duration: 10,
        objectives: ['Describe a trip in past simple', 'Include transport, accommodation, activities, food', 'Give your opinion and recommend'],
        sections: [
          { title: 'Travel Writing Checklist', type: 'rule', content: 'Include: Where: "I went to Phuket, Thailand." When: "Last December, for one week." Transport: "I flew from Bangkok." / "We drove for 3 hours." Accommodation: "I stayed at a hotel / hostel / Airbnb." Activities: "I visited... I swam... I tried..." Food: "I ate... The food was..." Opinion: "It was amazing / relaxing / disappointing." Recommend: "I would definitely go back!" / "I recommend it for families."' },
          { title: 'Example', type: 'example', examples: ['Last summer, I went to Bali with my girlfriend. We flew from Bangkok to Denpasar — the flight took about 4 hours. We stayed at a small hotel near Ubud. It was cheap and very clean. During the week, we visited rice terraces, went snorkelling, and explored old temples. The food was incredible — we ate nasi goreng every day! I loved the sunset at Tanah Lot temple. Bali is a beautiful place and I would definitely go back.'], analysis: 'Covers all checklist items: where, when, who with, transport, accommodation, activities, food, opinion, recommendation.' },
          { title: 'Write About a Trip', type: 'exercise', question: 'Write about a trip you took (real or imaginary). Cover at least 5 items from the checklist.', answer: 'Last year, I went to Tokyo for a week. I took the plane from my city — it was a long flight! I stayed in a capsule hotel, which was a very interesting experience. I visited Shibuya, Asakusa, and Akihabara. I tried ramen and sushi — the food was amazing. Tokyo is an exciting city and I hope to go back soon.', answerExplanation: 'Covers: where (Tokyo), when (last year), transport (plane), accommodation (capsule hotel), activities (Shibuya, etc.), food (ramen, sushi), opinion (exciting), hope to return.' },
        ],
        keyTakeaways: ['Cover: where, when, transport, hotel, activities, food', 'Past simple throughout for completed trips', 'End with opinion and recommendation'],
      },
      { id: 'a2-writing-thank-you', title: 'Writing Thank You Notes', description: 'Express gratitude in writing — for gifts, help, hospitality, or kindness.',
        skill: 'writing', level: 'A2', duration: 6,
        objectives: ['Write sincere thank you messages', 'Say what you are thanking them for', 'Add a personal touch'],
        sections: [
          { title: 'Thank You Structure', type: 'rule', content: 'What: "Thank you for the birthday gift / dinner / your help / having us." Specific: "I love the book you gave me — it is exactly what I wanted!" How it helped: "Your advice really helped me with my interview." Personal touch: "It was so kind of you." / "I really appreciate it." / "It meant a lot to me." Looking forward: "I hope to see you again soon." / "Let\'s meet up for coffee!"' },
          { title: 'Example', type: 'example', examples: ['Dear Mr and Mrs Chen,', 'Thank you so much for having us for dinner last Saturday. The food was absolutely delicious — especially the dumplings! It was wonderful to meet your family. Tom and I had a lovely evening. Thank you again for your kindness and hospitality. We would love to have you at our place next time!', 'Warm regards,', 'Sarah and Tom'], analysis: 'Specific (dinner, dumplings), personal (lovely evening), reciprocal (have you at our place).' },
          { title: 'Write a Thank You', type: 'exercise', question: 'Write a thank you note to someone who helped you move house.', answer: 'Hi Jake! I just wanted to say a huge thank you for helping me move last weekend. I could not have done it without you! You carried so many heavy boxes — I really appreciate it. The new flat is great and I\'m almost unpacked. Let me buy you dinner to say thanks properly! Are you free on Saturday?', answerExplanation: 'Specific thanks (helping move, carrying boxes), personal (couldn\'t have done it without you, appreciate it), offer to reciprocate (dinner).' },
        ],
        keyTakeaways: ['Be specific: say WHAT you are thanking them for', 'Add a personal touch: "It meant a lot"', 'Offer to reciprocate: "Let me buy you dinner"'],
      },
      { id: 'a2-writing-problems-solutions', title: 'Writing About Problems & Solutions', description: 'Describe a problem clearly and suggest possible solutions.',
        skill: 'writing', level: 'A2', duration: 10,
        objectives: ['Describe a problem with clear details', 'Suggest solutions using should/could/need to', 'Structure: problem → effect → solution'],
        sections: [
          { title: 'Problem-Solution Structure', type: 'rule', content: 'Problem: "The problem is..." / "One issue is..." / "Many people have trouble with..." Effect: "This means that..." / "Because of this..." / "As a result..." Solution: "We should..." / "One solution is to..." / "The government could..." / "People need to..."' },
          { title: 'Example', type: 'example', examples: ['Traffic is a big problem in our city. Every morning, the roads are full of cars and buses. People spend more than an hour driving to work. Because of this, they arrive tired and stressed. There are several solutions. First, the government should build more train lines. Second, companies could allow people to work from home some days. Finally, more people could ride bicycles — it is healthy and good for the environment.'], analysis: 'Problem (traffic), effect (tired, stressed), three solutions (trains, WFH, bicycles). Uses should/could for suggestions.' },
          { title: 'Describe a Problem', type: 'exercise', question: 'Choose a problem (pollution, noise, expensive rent, etc.) and write a problem-solution paragraph.', answer: 'Plastic pollution is a serious problem in our oceans. Every year, millions of tonnes of plastic end up in the sea. This kills fish, turtles, and birds. One solution is for shops to stop using plastic bags. People should also recycle more and use reusable water bottles. The government could ban single-use plastics. We all need to take action.', answerExplanation: 'Problem (plastic pollution), effect (kills animals), solutions (no plastic bags, recycle, ban plastics). Uses should/could/need to.' },
        ],
        keyTakeaways: ['Structure: problem → effect → solution(s)', '"Should" for strong advice, "could" for suggestions', 'Give 2-3 different solutions for a balanced answer'],
      },
      { id: 'a2-writing-recipe', title: 'Writing Simple Instructions & Recipes', description: 'Write clear, step-by-step recipes and how-to guides.',
        skill: 'writing', level: 'A2', duration: 8,
        objectives: ['List ingredients with quantities', 'Write numbered steps using imperatives', 'Use cooking verbs (chop, fry, boil, stir, add)'],
        sections: [
          { title: 'Recipe Format', type: 'rule', content: 'Title: name of the dish. Serves: number of people. Prep time / Cook time. Ingredients: list with quantities. Method/Instructions: numbered steps. Cooking verbs: chop/cut, peel, wash, mix/stir, add, pour, boil, fry, bake, grill, serve.' },
          { title: 'Example Recipe', type: 'example', examples: ['Egg Fried Rice (Serves 2)', 'Ingredients: 2 cups cooked rice, 2 eggs, 1 tablespoon oil, 2 tablespoons soy sauce, 1 spring onion (chopped)', '1. Heat the oil in a large pan. 2. Crack the eggs into the pan and scramble them. 3. Add the cooked rice and mix well. 4. Pour in the soy sauce and stir for 2 minutes. 5. Add the spring onion and stir. 6. Serve hot. Enjoy!'], analysis: 'Clear ingredients list with quantities. Each step starts with an imperative verb. Short sentences.' },
          { title: 'Write a Recipe', type: 'exercise', question: 'Write a recipe for a simple dish you know how to make (toast, salad, sandwich, etc.).', answer: 'Simple Green Salad (Serves 2)\nIngredients: 1 lettuce, 2 tomatoes, 1 cucumber, olive oil, salt, pepper\n1. Wash the lettuce, tomatoes, and cucumber.\n2. Chop the lettuce into small pieces.\n3. Cut the tomatoes and cucumber into slices.\n4. Put everything in a large bowl.\n5. Add olive oil, salt, and pepper.\n6. Mix well and serve.', answerExplanation: 'Format: title, serves, ingredients with quantities, numbered steps with imperative verbs (wash, chop, cut, put, add, mix).' },
        ],
        keyTakeaways: ['Ingredients: item + quantity', 'Steps: number + imperative verb', 'Cooking verbs: chop, fry, boil, stir, add, pour, bake, serve'],
      },
      { id: 'a2-writing-advertisement', title: 'Writing a Short Advertisement', description: 'Write persuasive ads — selling, renting, promoting events or services.',
        skill: 'writing', level: 'A2', duration: 8,
        objectives: ['Use persuasive adjectives (amazing, perfect, best)', 'Include key selling points', 'Add a call to action'],
        sections: [
          { title: 'Ad Structure', type: 'rule', content: 'Headline: grab attention: "Beautiful 2-bedroom flat for rent!" Key features: what makes it special (3-5 bullet points). Details: price, location, availability. Call to action: "Call now!" "Visit our website!" "Don\'t miss out!" Persuasive words: amazing, perfect, beautiful, excellent, best, free, new, special, limited, exclusive, great value.' },
          { title: 'Example', type: 'example', examples: ['FOR SALE: iPhone 14 Pro — Excellent Condition!', '• 256GB storage • Space Black colour • Battery health 95% • Comes with case and charger • No scratches or damage', 'Price: £400 (negotiable)', 'Location: Central London — can meet in person', 'Contact: 07700 123456 or message me on this site.', 'Grab it before it\'s gone!'], analysis: 'Attention-grabbing headline, bullet point features, price + location, contact details, call to action.' },
          { title: 'Write an Ad', type: 'exercise', question: 'Write an advertisement for renting a room in your flat.', answer: 'Room Available in Shared Flat — Great Location!\n• Large, sunny double room\n• Modern kitchen and bathroom\n• 5 minutes from the train station\n• Quiet, friendly flatmates\n• WiFi and bills included\nRent: £650/month. Available from 1st September.\nContact: anna@email.com\nDon\'t miss this opportunity!', answerExplanation: 'Headline grabs attention, bullet points list features, price and date, contact info, call to action.' },
        ],
        keyTakeaways: ['Headline: grab attention with key selling point', 'Bullet points for features — easy to scan', 'End with a call to action: "Contact us!" "Don\'t miss out!"'],
      },
      { id: 'a2-writing-rules', title: 'Writing About Rules & Regulations', description: 'Explain rules using must, mustn\'t, have to, can\'t, and allowed to.',
        skill: 'writing', level: 'A2', duration: 8,
        objectives: ['Use must/mustn\'t for rules', 'Use can/can\'t for permissions', 'Write rules for a place or situation'],
        sections: [
          { title: 'Rules Language', type: 'rule', content: 'Obligation: "You must wear a seatbelt." "You have to show your ticket." Prohibition: "You mustn\'t smoke here." "You can\'t take photos." Permission: "You can bring food." "You are allowed to park here." No permission: "You are not allowed to use phones." "Visitors cannot enter after 6 PM."' },
          { title: 'Example', type: 'example', examples: ['Swimming Pool Rules:', '1. You must shower before entering the pool.', '2. You mustn\'t run near the pool.', '3. Children under 12 must be with an adult.', '4. You can\'t bring food or glass bottles.', '5. You are allowed to use the changing rooms for free.', '6. You must leave by 9 PM.'], analysis: 'Uses must (obligation), mustn\'t (prohibition), can\'t (not permitted), allowed to (permission). Clear, numbered rules.' },
          { title: 'Write Rules', type: 'exercise', question: 'Write 5 rules for a library.', answer: '1. You must be quiet at all times.\n2. You mustn\'t eat or drink in the library.\n3. You can borrow up to 5 books.\n4. You must return books within 2 weeks.\n5. You are not allowed to use your phone.', answerExplanation: 'Uses must (quiet, return), mustn\'t (eat/drink), can (borrow), not allowed to (phone). Appropriate for a library.' },
        ],
        keyTakeaways: ['Must/have to = you need to do this (obligation)', 'Mustn\'t/can\'t = you are not allowed (prohibition)', 'Can / allowed to = it is OK (permission)'],
      },
      { id: 'a2-writing-biography', title: 'Writing a Short Biography', description: 'Write about a person\'s life — key events, achievements, and personality.',
        skill: 'writing', level: 'A2', duration: 10,
        objectives: ['Use past simple for life events', 'Include key biographical information', 'Structure chronologically (birth to present/death)'],
        sections: [
          { title: 'Biography Essentials', type: 'rule', content: 'Include: Born: "She was born in 1990 in Seoul." Early life: "He grew up in a small village." Education: "She studied medicine at Oxford." Career: "He worked as a teacher for 10 years." Achievements: "She won the Nobel Prize in 2020." Personal life: "He married Maria in 2015. They have two children." Personality: "She was kind and hardworking."' },
          { title: 'Example', type: 'example', examples: ['Marie Curie was born in Warsaw, Poland, in 1867. She grew up in a large family and loved science from a young age. In 1891, she moved to Paris to study physics at the Sorbonne. There she met Pierre Curie, and they married in 1895. Together, they discovered two new elements: polonium and radium. In 1903, Marie became the first woman to win a Nobel Prize. She won a second Nobel Prize in 1911 — the only person to win in two different sciences. She died in 1934. Marie Curie changed science forever.'], analysis: 'Chronological: birth → childhood → education → marriage → career → achievements → death. Past simple throughout.' },
          { title: 'Write a Biography', type: 'exercise', question: 'Write a short biography (5-7 sentences) about a famous person or someone in your family.', answer: 'My grandmother was born in 1945 in a small village in the north. She grew up on a rice farm with six brothers and sisters. She did not go to university but she was very intelligent. She married my grandfather in 1965 and they had four children. She worked as a market seller for 30 years. She was the kindest person I have ever known. She passed away in 2018 and I miss her very much.', answerExplanation: 'Chronological order: birth → childhood → education → marriage → career → personality → death. Past simple throughout.' },
        ],
        keyTakeaways: ['Chronological order: birth → childhood → education → career → achievements', 'Past simple for all life events', '"Was born in [year] in [place]" to start'],
      },
      { id: 'a2-writing-summary', title: 'Writing a Summary', description: 'Summarise a text by finding the main ideas and writing them in your own words.',
        skill: 'writing', level: 'A2', duration: 10,
        objectives: ['Identify main ideas vs details', 'Write shorter versions of longer texts', 'Use your own words (paraphrase)'],
        sections: [
          { title: 'How to Summarise', type: 'rule', content: 'Step 1: Read the text carefully. Step 2: Underline the main ideas (not details or examples). Step 3: Write the main ideas in YOUR OWN words. Step 4: Keep it SHORT — a summary should be about 1/3 of the original. Do NOT: copy sentences from the original, add your opinion, include examples or minor details.' },
          { title: 'Example', type: 'example', examples: ['Original (80 words): "Dogs are the most popular pets in the UK. About 12 million households have a dog. People like dogs because they are loyal, friendly, and fun to be around. Walking a dog also helps people stay healthy and active. However, dogs need a lot of care. They need food, exercise, vet visits, and attention every day. Some breeds need more exercise than others. Having a dog is a big responsibility."', 'Summary (30 words): "Dogs are very popular pets in the UK. People love them for their loyalty and companionship. However, dogs require daily care including food, exercise, and vet visits."'], analysis: 'Main ideas kept: popular, why liked, care needed. Details removed: 12 million, breeds, big responsibility.' },
          { title: 'Summarise This', type: 'exercise', question: 'Summarise in 2-3 sentences: "Social media has changed the way people communicate. Billions of people use platforms like Instagram and TikTok every day. It helps people stay in touch with friends and family around the world. It is also used for news and entertainment. However, social media can be addictive. Many people spend hours scrolling instead of sleeping or exercising. Some studies show it can increase anxiety and depression, especially in young people."', answer: 'Social media is used by billions for communication and entertainment. However, it can be addictive and may cause anxiety and depression, particularly among young people.', answerExplanation: 'Main ideas: widely used + risks (addictive, mental health). Removed: specific platforms, staying in touch, scrolling instead of sleeping (these are details/examples).' },
        ],
        keyTakeaways: ['Find main ideas, ignore details and examples', 'Use your OWN words — don\'t copy sentences', 'A summary should be about 1/3 of the original length'],
      },
    ],
  },
]
