// # ═══════════════════════════════════════════════════════════════════════════
// # LESSON DATA — Part 26: Final Gap Fill — Grammar C2 (1) + Reading C2 (2)
// # ═══════════════════════════════════════════════════════════════════════════

import type { LessonCategory } from './types'

export const LESSON_CATEGORIES_26: LessonCategory[] = [
  {
    id: 'c2-mastery',
    name: 'C2: Mastery Grammar',
    description: 'Native-like precision — the subtle structures that separate fluent from flawless.',
    icon: '📐',
    lessons: [
      { id: 'c2-garden-path', title: 'Garden Path Sentences & Syntactic Ambiguity', description: 'Understand sentences that trick the reader into the wrong interpretation — and why they matter.',
        skill: 'grammar', level: 'C2', duration: 12,
        objectives: ['Recognise structurally ambiguous sentences', 'Understand how parsing works in real time', 'Use punctuation and word order to prevent ambiguity'],
        sections: [
          { title: 'What Are Garden Path Sentences?', type: 'rule', content: 'A GARDEN PATH sentence leads you to interpret it one way, then forces you to reparse:\n\n"The horse raced past the barn fell."\nFirst reading: The horse raced past the barn... fell? (doesn\'t make sense)\nCorrect: The horse [that was] raced past the barn fell. (reduced relative clause — the horse fell)\n\n"The old man the boats."\nFirst reading: The old man... the boats? (noun + noun?)\nCorrect: The old [people] man [= operate] the boats. ("old" = noun, "man" = verb)\n\n"Time flies like an arrow. Fruit flies like a banana."\nFirst reading: fruit flies [insects] like a banana.\nAlternative: fruit [noun] flies [verb] like [= the way] a banana [does].\n\nThese sentences reveal how our brains parse language in real time — we commit to one structure and have to backtrack when it fails.' },
          { title: 'Preventing Ambiguity', type: 'tip', content: 'Good writers PREVENT garden-path readings:\n\nAMBIGUOUS: "I saw the man with the telescope."\n(Did you use a telescope to see him? Or did he have a telescope?)\n\nCLEAR: "Using my telescope, I saw the man." or "I saw the man who was carrying a telescope."\n\nAMBIGUOUS: "Flying planes can be dangerous."\n(The act of flying? Or planes that are flying?)\n\nCLEAR: "Flying a plane can be dangerous." or "Planes in flight can be dangerous."\n\nTools for clarity: commas, relative pronouns (who/which/that), rephrasing, word order changes. In legal and technical writing, eliminating ambiguity is critical — a misread contract clause can cost millions.' },
          { title: 'Parse This Sentence', type: 'exercise', question: '"The complex houses married and single soldiers and their families."', answer: 'GARDEN PATH: "The complex houses..." — you read "complex" as an adjective and "houses" as a noun. Then "married" doesn\'t fit.\n\nCORRECT PARSE: "The complex [noun = housing facility] houses [verb = accommodates] married and single soldiers and their families."\n\n"Complex" = the noun (a housing complex). "Houses" = the verb (provides housing for). "Married and single" = adjectives modifying "soldiers."\n\nThe sentence means: The military housing complex accommodates both married and single soldiers, as well as their families.', answerExplanation: 'Garden path sentences show that English relies heavily on word order and context for meaning. The same word can be a noun, verb, or adjective depending on position. "Houses" is a noun in "the houses" but a verb in "the complex houses soldiers." Context resolves the ambiguity — but only on the second reading.' },
        ],
        keyTakeaways: ['Garden path sentences exploit structural ambiguity — the reader commits to a wrong parse', 'The same word can be noun/verb/adjective: "houses" (buildings) vs "houses" (accommodates)', 'Prevent ambiguity with commas, relative pronouns, and clear word order'],
      },
    ],
  },
  {
    id: 'c2-reading',
    name: 'C2: Mastery Reading',
    description: 'Process any English text at near-native depth — literary, academic, legal, or journalistic.',
    icon: '📖',
    lessons: [
      { id: 'c2-reading-translation-comparison', title: 'Reading Translations: What Changes & Why', description: 'Compare translated texts with originals to understand how language shapes meaning across cultures.',
        skill: 'reading', level: 'C2', duration: 12,
        objectives: ['Understand what is lost and gained in translation', 'Recognise cultural adaptation vs literal translation', 'Appreciate untranslatable concepts and how translators handle them'],
        sections: [
          { title: 'Translation Choices', type: 'rule', content: 'Every translation involves CHOICES:\n\nLITERAL (word-for-word): preserves form, may lose naturalness.\n"Il pleut des cordes" (French) → literally "It rains ropes" → natural English: "It\'s raining cats and dogs."\n\nDYNAMIC (meaning-for-meaning): preserves effect, may change form.\nA joke that relies on a French pun is replaced with an English pun that gets the same laugh.\n\nCULTURAL ADAPTATION: replacing unfamiliar references.\nA Japanese text\'s reference to "cherry blossom season" might become "springtime" for a Western audience.\n\nUNTRANSLATABLE CONCEPTS:\nGerman: "Schadenfreude" (pleasure in others\' misfortune)\nJapanese: "Wabi-sabi" (beauty of imperfection)\nDanish: "Hygge" (cosy togetherness)\nThese require explanation, not translation.' },
          { title: 'Reading Translated Literature', type: 'tip', content: 'When reading a translated novel:\n\n1. The translator is a CO-AUTHOR. Their style shapes your experience.\n2. Compare translations if possible — different translators create different books.\n3. Footnotes and translator notes explain cultural context.\n4. Some works resist translation: poetry (rhythm + meaning), humour (cultural references), wordplay.\n\nWhy it matters for English learners:\n- Reading translations helps you understand how languages THINK differently.\n- English word order (SVO) shapes how English speakers perceive events.\n- Languages without articles (Japanese, Russian) think about specificity differently.\n- Understanding translation gives you deeper insight into how YOUR first language shapes your thinking in English.' },
          { title: 'Analyse the Translation Choice', type: 'exercise', question: 'Original (Japanese proverb): "Nana korobi, ya oki" (literally: "Seven falls, eight rises"). Published translation: "Fall seven times, stand up eight." Why not translate it literally?', answer: 'The literal version ("Seven falls, eight rises") is grammatically awkward in English — it sounds like a mathematical statement, not a proverb. The published translation restructures it as an imperative ("Fall... stand up") which gives it the punchy, motivational quality that proverbs have in English. It also adds "stand up" instead of just "rises" — "stand up" has connotations of resilience and defiance in English that "rise" alone lacks. The MEANING (resilience, perseverance) is preserved while the FORM changes to fit English proverb conventions.', answerExplanation: 'Good translation prioritises the FUNCTION of the text. A proverb should sound like a proverb. A joke should be funny. A poem should have rhythm. Literal accuracy that destroys the function is a worse translation than a restructured version that preserves it.' },
        ],
        keyTakeaways: ['Translation = choices between form (literal) and function (dynamic)', 'Untranslatable words reveal how languages think differently', 'The translator is a co-author — different translators create different books'],
      },
      { id: 'c2-reading-metacognitive', title: 'Metacognitive Reading: Monitoring Your Own Comprehension', description: 'Develop awareness of your own reading process — know when you understand, when you don\'t, and what to do about it.',
        skill: 'reading', level: 'C2', duration: 12,
        objectives: ['Monitor comprehension in real time', 'Deploy repair strategies when comprehension breaks down', 'Set reading goals and adapt strategy accordingly'],
        sections: [
          { title: 'Metacognitive Strategies', type: 'rule', content: 'Metacognition = thinking about your own thinking. In reading:\n\nBEFORE READING:\n- Set a PURPOSE: "I\'m reading this to find the author\'s main argument."\n- PREVIEW: scan headings, abstract, introduction, conclusion.\n- ACTIVATE PRIOR KNOWLEDGE: "What do I already know about this topic?"\n\nDURING READING:\n- MONITOR: "Do I understand this paragraph? Could I summarise it?"\n- FLAG confusion: "I don\'t understand this sentence — I\'ll come back to it."\n- CONNECT: "This relates to what I read in paragraph 2."\n- QUESTION: "Why does the author include this example?"\n\nAFTER READING:\n- SUMMARISE: "The main argument was..."\n- EVALUATE: "Was the argument convincing? What was missing?"\n- APPLY: "How does this change my understanding of the topic?"' },
          { title: 'Repair Strategies', type: 'tip', content: 'When comprehension breaks down, skilled readers have REPAIR strategies:\n\n1. RE-READ the sentence slowly.\n2. READ AHEAD — sometimes the next sentence clarifies.\n3. PARAPHRASE — try to say it in your own words.\n4. LOOK UP key vocabulary — but only if the word is blocking comprehension.\n5. BREAK LONG SENTENCES into chunks.\n6. IDENTIFY THE SUBJECT AND VERB — in complex sentences, find who does what.\n7. USE CONTEXT — surrounding sentences often explain the difficult one.\n8. ASK: "Do I NEED to understand this sentence?" Sometimes you don\'t — skip and continue.\n\nThe key difference between C1 and C2 readers: C2 readers know WHEN they\'ve stopped understanding and immediately deploy a repair strategy. C1 readers sometimes keep reading without realising they\'ve lost the thread.' },
          { title: 'Self-Assessment', type: 'exercise', question: 'You\'re reading a dense academic article and realise you\'ve read an entire page without absorbing anything. What do you do?', answer: 'METACOGNITIVE RESPONSE:\n1. ACKNOWLEDGE: "I wasn\'t actually reading — I was just moving my eyes over words."\n2. DIAGNOSE: Why? Too tired? Topic too unfamiliar? Language too dense? Distracted?\n3. RESET PURPOSE: "What am I looking for in this article?"\n4. CHANGE STRATEGY: Instead of reading every word, skim for the relevant section first. Read topic sentences only. Find the thesis.\n5. RE-ENGAGE: Go back to where you last understood, not to the beginning of the page.\n6. If the problem is fatigue: take a break. Forcing comprehension when tired wastes time.\n\nThis is not a failure — it happens to everyone, including native speakers. The skill is noticing quickly and adapting.', answerExplanation: 'Metacognitive reading is what separates competent from expert readers. Experts constantly monitor: "Am I understanding? Is this relevant? Should I slow down or speed up?" This self-awareness is the single most powerful reading skill — and it can be deliberately practiced.' },
        ],
        keyTakeaways: ['Before: set purpose + preview. During: monitor + flag confusion. After: summarise + evaluate.', 'Repair strategies: re-read, read ahead, paraphrase, chunk, find subject/verb', 'The key C2 skill: knowing WHEN you\'ve stopped understanding and fixing it immediately'],
      },
    ],
  },
]
