// # ═══════════════════════════════════════════════════════════════════════════
// # LESSON DATA — Part 18: Reading Lessons C1 + C2 (45 lessons)
// # ═══════════════════════════════════════════════════════════════════════════

import type { LessonCategory } from './types'

export const LESSON_CATEGORIES_18: LessonCategory[] = [
  {
    id: 'c1-reading',
    name: 'C1: Reading Skills',
    description: 'Engage critically with complex texts — academic papers, literary analysis, investigative journalism, and philosophical argument.',
    icon: '📖',
    lessons: [
      // # ─── Lesson 1: Deconstructing Complex Sentence Structures ───
      { id: 'c1-reading-complex-sentences', title: 'Deconstructing Complex Sentence Structures', description: 'Parse long, multi-clause sentences found in academic writing, legal texts, and quality journalism.',
        skill: 'reading', level: 'C1', duration: 12,
        objectives: ['Identify the main clause in sentences with multiple subordinate clauses', 'Understand embedded clauses and parenthetical asides', 'Maintain comprehension across 40+ word sentences'],
        sections: [
          { title: 'Sentence Architecture', type: 'rule', content: 'Complex academic sentences use: EMBEDDED CLAUSES: "The policy, which was introduced despite widespread opposition from trade unions and employers\' organisations alike, has failed to achieve its stated objective of reducing unemployment." Main clause: The policy has failed. Everything between the commas is an embedded clause (extra information). FRONT-LOADED SUBORDINATION: "Although the evidence suggests that early intervention is effective, and despite growing consensus among researchers, policy-makers remain reluctant to commit funding." Main clause: policy-makers remain reluctant. Everything before the comma is setup. Strategy: find the SUBJECT and MAIN VERB first. Everything else is modification.' },
          { title: 'The Stripping Method', type: 'tip', content: 'When a sentence overwhelms you, STRIP it: (1) Remove everything between commas, dashes, or brackets. (2) Remove "which/who/that" clauses. (3) Remove "although/despite/while" clauses. (4) What remains is the core sentence. Example: "The researchers, who had been studying the phenomenon for over a decade and had published extensively on the subject, concluded that the correlation, while statistically significant, did not imply causation." Strip: "The researchers concluded that the correlation did not imply causation." — that is the core message. Now re-read the stripped parts to add nuance: they studied it for 10+ years (credibility), the correlation IS significant (concession), but it\'s not causal (conclusion).' },
          { title: 'Strip This Sentence', type: 'exercise', question: '"The government\'s decision to increase infrastructure spending, which economists had long advocated as a means of stimulating growth during periods of recession, was ultimately undermined by a series of implementation failures that, according to the National Audit Office, resulted in cost overruns exceeding £3 billion."', answer: 'Core: "The government\'s decision to increase infrastructure spending was undermined by implementation failures." Details: (1) Economists had long advocated this spending (credibility/context). (2) It was meant to stimulate growth during recession (purpose). (3) The NAO found cost overruns exceeding £3 billion (evidence of failure). (4) The word "ultimately" suggests a gradual deterioration, not a sudden collapse. The full sentence is 45 words. The core is 13 words. Understanding the core first makes the details manageable.', answerExplanation: 'Academic and government writing frequently uses these long, qualified sentences. They are not poorly written — they are precisely written, packing context, attribution, and nuance into a single sentence. The stripping method lets you process them in layers: core meaning first, then nuance. This is essential for C1 academic reading.' },
        ],
        keyTakeaways: ['Find the SUBJECT and MAIN VERB first — everything else is modification', 'Strip: remove commas/dashes/brackets → remove which/who → remove although/despite → core remains', 'Long sentences are precisely written — process them in layers, not all at once'],
      },
      // # ─── Lesson 2: Critical Evaluation of Arguments ───
      { id: 'c1-reading-argument-evaluation', title: 'Critical Evaluation of Arguments', description: 'Identify logical fallacies, evaluate evidence quality, and assess argument validity.',
        skill: 'reading', level: 'C1', duration: 14,
        objectives: ['Identify common logical fallacies in published texts', 'Distinguish between valid arguments and persuasive arguments', 'Evaluate evidence chains for logical gaps'],
        sections: [
          { title: 'Common Logical Fallacies', type: 'rule', content: 'AD HOMINEM: attacking the person, not the argument. "You can\'t trust her opinion on climate — she\'s not a scientist." (Her argument might still be valid.) STRAW MAN: misrepresenting the opponent\'s position. "Vegetarians want everyone to eat nothing but lettuce." FALSE DICHOTOMY: presenting only two options when more exist. "You\'re either with us or against us." SLIPPERY SLOPE: claiming one step inevitably leads to an extreme outcome. "If we allow X, next they\'ll demand Y, and before long Z." APPEAL TO POPULARITY: "Everyone agrees, so it must be true." CIRCULAR REASONING: "This is true because it is correct." POST HOC: "After X happened, Y happened, therefore X caused Y."' },
          { title: 'Valid vs Persuasive', type: 'tip', content: 'A VALID argument follows logically from its premises. Premise: All mammals breathe air. Premise: Whales are mammals. Conclusion: Whales breathe air. (Valid AND true.) A PERSUASIVE argument FEELS convincing but may not be logically valid. "This product is natural, so it must be safe." (Arsenic is natural and deadly — this is an appeal to nature fallacy.) At C1, you distinguish between: "Does this argument feel right?" (persuasiveness) and "Does this argument logically follow from the evidence?" (validity). These are different questions, and a skilled reader checks both.' },
          { title: 'Find the Fallacy', type: 'exercise', question: '(a) "Professor Smith\'s research on climate change should be dismissed — he was arrested for speeding last year." (b) "If we let students use AI for homework, they\'ll never learn to think, universities will become meaningless, and civilisation will collapse." (c) "85% of dentists recommend this toothpaste, so it must be the best."', answer: '(a) Ad hominem — attacking the person (speeding) not the research. His driving record is irrelevant to climate science. (b) Slippery slope — jumps from "AI for homework" to "civilisation will collapse" through an unlikely chain of escalating consequences with no evidence. (c) Appeal to popularity/authority — 85% of dentists recommend it, but: recommending ≠ "the best," they might recommend MANY brands, and who funded the survey? (Probably the toothpaste company.) All three arguments FEEL persuasive to many people. None is logically valid.', answerExplanation: 'Fallacies are common in journalism, politics, advertising, and everyday conversation. The challenge at C1 is recognising them in POLISHED writing where they are harder to spot than in these clear examples. In a 3,000-word article, a single straw man or false dichotomy can undermine an otherwise strong argument. Training yourself to notice fallacies makes you a much more rigorous reader.' },
        ],
        keyTakeaways: ['Ad hominem = attack the person. Straw man = misrepresent the argument. Slippery slope = exaggerated chain.', 'Valid ≠ persuasive. An argument can feel convincing but be logically flawed.', 'In polished writing, fallacies are subtle — read for logical gaps, not just emotional impact'],
      },
      // # ─── Lesson 3: Reading Implicit Ideology ───
      { id: 'c1-reading-ideology', title: 'Reading Implicit Ideology', description: 'Detect the worldview and ideological assumptions embedded in texts — even ones that appear neutral.',
        skill: 'reading', level: 'C1', duration: 12,
        objectives: ['Identify ideological framing in "neutral" texts', 'Understand how word choice reveals political positioning', 'Read the same event through different ideological lenses'],
        sections: [
          { title: 'No Text Is Neutral', type: 'rule', content: 'Every text makes assumptions about how the world works: WORD CHOICE reveals position: "Illegal immigrants" vs "undocumented migrants" vs "asylum seekers" — three terms for the same people, each carrying different assumptions about legality, sympathy, and rights. "Economic reform" vs "austerity" vs "cuts" — same policy, different framing. WHAT IS INCLUDED reveals priority: a story about a company\'s profits that doesn\'t mention working conditions tells you what the writer considers important. WHAT IS NORMALISED reveals ideology: "The market decided" treats the economy as a natural force. "Governments chose these policies" treats it as a human decision. Neither is wrong — but each reveals a different ideological lens.' },
          { title: 'Detecting the Lens', type: 'tip', content: 'Every publication has a lens, even "objective" ones: MARKET-ORIENTED lens: frames issues as supply/demand, incentives, efficiency. "How will this affect growth?" RIGHTS-BASED lens: frames issues as justice, equality, fairness. "How will this affect vulnerable groups?" NATIONAL INTEREST lens: frames issues as security, sovereignty, identity. "How will this affect our country?" INDIVIDUAL lens: frames issues as personal choice, freedom, responsibility. "How will this affect you?" SYSTEMIC lens: frames issues as institutional power, structure, inequality. "How does this system create this outcome?" Identifying the lens doesn\'t make the text wrong — it helps you understand WHICH aspects are emphasised and which are invisible. Read across lenses for a complete picture.' },
          { title: 'Compare the Framing', type: 'exercise', question: 'Same event, two headlines: (A) "Tech giant creates 5,000 new jobs in expansion" (B) "Tech giant expansion raises housing costs and displaces local businesses" What worldview does each reflect?', answer: '(A) ECONOMIC GROWTH lens: jobs = good. Expansion = progress. The community should welcome economic activity. Workers and GDP are the priority. (B) COMMUNITY IMPACT lens: growth has costs. Housing displacement harms existing residents. Local businesses are threatened by corporate power. Livability is the priority. Neither is wrong — both are true simultaneously. The 5,000 jobs ARE real. The housing pressure IS real. But each headline shows ONE truth while hiding the other. A reader who only reads (A) thinks expansion is pure good. A reader who only reads (B) thinks it\'s pure harm. Reality is both.', answerExplanation: 'This is C1 critical reading: not "which headline is right?" but "what does each headline CHOOSE to show and hide?" The same event supports multiple true stories. Ideological reading means recognising that every "angle" is a choice, and no single angle shows the whole picture. Reading across publications with different lenses gives the most complete understanding.' },
        ],
        keyTakeaways: ['Every text has an ideological lens — even "objective" reporting', 'Word choice reveals position: "illegal immigrants" vs "undocumented migrants" vs "asylum seekers"', 'Ask: "What does this text CHOOSE to show? What does it hide?"'],
      },
      // # ─── Lesson 4: Academic Register & Hedging ───
      { id: 'c1-reading-academic-register', title: 'Academic Register & Hedging', description: 'Understand the cautious, precise language of academic writing — and why it sounds the way it does.',
        skill: 'reading', level: 'C1', duration: 12,
        objectives: ['Decode hedging language (might, could, tends to, appears to)', 'Understand why academics avoid absolute claims', 'Read confidence levels from language choices'],
        sections: [
          { title: 'The Hedging Scale', type: 'rule', content: 'Academic writers HEDGE — they avoid absolute claims because science is uncertain: STRONG CLAIM: "X causes Y." (Only used when overwhelming evidence exists.) HEDGED CLAIM: "X appears to cause Y." "X may contribute to Y." "The evidence suggests X is associated with Y." "X tends to correlate with Y." "It is plausible that X influences Y." WEAK CLAIM: "It is conceivable that X might have some effect on Y." Each step down reduces certainty. "Causes" = proven. "May contribute to" = possible but unproven. "It is conceivable" = barely a claim. Reading the hedge tells you HOW CONFIDENT the author is.' },
          { title: 'Why Hedging Matters', type: 'tip', content: 'Hedging is NOT weakness or evasion. It is intellectual honesty. When a researcher writes "The data suggest that..." they are saying: "I believe this based on evidence, but I cannot prove it absolutely, and future research might change the picture." This is MORE trustworthy than a writer who says "X definitely causes Y" without qualification. Warning: POPULAR MEDIA removes hedging. Research paper: "Coffee consumption may be associated with reduced cardiovascular risk in certain populations." Newspaper headline: "COFFEE PREVENTS HEART ATTACKS!" The hedging was the most important part, and the journalist removed it. Always check the original source.' },
          { title: 'Read the Confidence Level', type: 'exercise', question: 'Rank from most to least confident: (a) "The results indicate that sleep deprivation impairs cognitive function." (b) "It is possible that sleep deprivation may affect some aspects of cognitive performance." (c) "Sleep deprivation impairs cognitive function." (d) "The findings suggest a potential link between sleep patterns and cognitive outcomes."', answer: 'Most → Least confident: (c) "impairs" — no hedge at all. Direct causal claim. Strongest. (a) "indicate" — strong but hedged. "Indicate" is confident. (d) "suggest a potential link" — double hedge. "Suggest" AND "potential" AND "link" (not "cause"). (b) "possible... may... some aspects" — triple hedge. Very cautious. Author is barely committing to the claim. Notice: (c) would be inappropriate in most academic writing without extraordinary evidence. (a) is the standard academic register for strong findings. (d) and (b) are appropriate for preliminary or inconclusive results.', answerExplanation: 'Counting hedges is a practical reading skill. One hedge = cautious. Two hedges = quite uncertain. Three hedges = the author is barely making a claim. When journalists remove ALL hedges, they fundamentally change the meaning. "May affect some aspects" is NOT the same as "impairs." Reading the hedge is reading the actual claim.' },
        ],
        keyTakeaways: ['"Causes" (certain) → "suggests" (probable) → "may" (possible) → "is conceivable" (barely a claim)', 'More hedges = less confidence. Count them to read the real claim.', 'Journalists remove hedging — always check the original source for the actual claim'],
      },
      // # ─── Lesson 5: Intertextuality — Texts in Conversation ───
      { id: 'c1-reading-intertextuality', title: 'Intertextuality — How Texts Reference Other Texts', description: 'Recognise allusions, references, and how texts build on or respond to earlier works.',
        skill: 'reading', level: 'C1', duration: 12,
        objectives: ['Identify literary and cultural allusions', 'Understand how texts respond to, extend, or challenge other texts', 'Recognise when a text assumes knowledge of another work'],
        sections: [
          { title: 'What Is Intertextuality?', type: 'rule', content: 'No text exists in isolation. Texts reference other texts through: DIRECT ALLUSION: "He was no Romeo" — references Shakespeare to mean he was not romantic. STRUCTURAL ECHO: a modern novel that follows the plot of a Greek myth. COUNTER-ARGUMENT: a paper that begins "Contrary to Smith\'s 2020 findings..." GENRE CONVENTIONS: detective fiction follows patterns established by Conan Doyle and Christie. QUOTATION AND EPIGRAPH: a novel that opens with a line from another work. PARODY: a text that imitates and mocks another text\'s style. Missing the reference means missing part of the meaning. "All animals are equal, but some animals are more equal than others" loses power if you don\'t know Orwell.' },
          { title: 'Recognising Allusions', type: 'tip', content: 'Clues that a text is referencing something else: a phrase in quotation marks or italics that seems imported from elsewhere, a phrase that sounds deliberately old-fashioned or out of place, a structure that mirrors a well-known story (rags to riches, fall from grace), a name that echoes mythology or literature (a character named Icarus who aims too high), a phrase that "everyone knows" — "to be or not to be," "Big Brother," "catch-22," "the elephant in the room." When you suspect an allusion but don\'t recognise it, note it. Understanding comes from reading widely over time. The more you read, the more allusions you catch — this is cumulative cultural literacy.' },
          { title: 'Find the Intertextuality', type: 'exercise', question: '"The startup\'s founder promised his employees a paradise — unlimited holidays, free food, no hierarchy. Three years later, the company collapsed under debt, lawsuits, and a toxic culture. Some paradises turn out to be built on quicksand. As Gatsby learned, the green light is always farther away than it seems."', answer: 'References: (1) "Paradise" → Garden of Eden / utopia — the startup is compared to a perfect world that turns out to be an illusion. (2) "Built on quicksand" → biblical allusion (house built on sand vs rock) — suggests the foundation was unstable. (3) "Gatsby" and "green light" → The Great Gatsby by F. Scott Fitzgerald — Gatsby\'s green light represents an impossible dream that always stays out of reach. The writer is saying: this startup, like Gatsby, chased an unreachable ideal. The "American Dream" of the perfect company was always an illusion.', answerExplanation: 'Without knowing The Great Gatsby, the "green light" reference is meaningless. Without the biblical allusion, "built on quicksand" is just a cliché. With them, the text gains layers: the startup is not just a failed business — it represents the recurring human pattern of chasing utopias that cannot exist. Intertextuality turns a business article into a commentary on human nature. This is why wide reading matters — each book you read makes every future text richer.' },
        ],
        keyTakeaways: ['Allusions (Gatsby, Orwell, Greek myths) add layers of meaning — missing them means missing the point', 'Clues: imported phrases, deliberate echoes, names from mythology/literature', 'Wide reading builds cultural literacy — each book makes future texts richer'],
      },
      // # ─── Lesson 6: Reading Extended Academic Prose ───
      { id: 'c1-reading-extended-academic', title: 'Reading Extended Academic Prose', description: 'Sustain comprehension across 3,000+ word academic texts with dense argumentation.',
        skill: 'reading', level: 'C1', duration: 14,
        objectives: ['Track an argument across 10+ paragraphs', 'Handle multiple competing theories within one text', 'Take effective reading notes for academic purposes'],
        sections: [
          { title: 'The SQ3R Method', type: 'rule', content: 'For extended academic texts, use SQ3R: SURVEY (2-3 min): scan title, abstract, headings, figures, conclusion. Get the overall structure. QUESTION: turn each heading into a question. "Social Factors" → "What social factors are discussed? How do they relate to the thesis?" READ: read one section at a time, looking for answers to your questions. RECITE: after each section, close the text and say (or write) the main points in your own words. If you cannot, re-read. REVIEW: after finishing, look back at your notes. Connect the sections. How do the parts build the whole argument? SQ3R is slow — but for academic reading, comprehension matters more than speed.' },
          { title: 'Handling Multiple Theories', type: 'tip', content: 'Academic texts often present competing explanations: "Theory A proposes that... However, Theory B challenges this by... A third perspective, Theory C, attempts to reconcile..." Track each theory with: (1) What does it claim? (2) What evidence supports it? (3) What are its weaknesses? (4) Does the author favour one? The author\'s position is often revealed through: which theory gets the most space, which evidence is presented last (recency effect), hedge words ("Theory A suggests..." vs "Theory B demonstrates..."), and the conclusion. At C1, you must follow the author\'s navigation through theories without losing track of which claims belong to which theory.' },
          { title: 'Track the Theories', type: 'exercise', question: '"Three explanations for declining voter turnout have been proposed. Rational choice theory suggests voters calculate the costs and benefits of voting, and abstain when the perceived impact is low. Social capital theory argues that declining community bonds reduce civic participation. Political alienation theory contends that voters disengage because they believe the political system does not represent their interests. While all three capture part of the phenomenon, the growing body of evidence on institutional distrust most strongly supports the alienation perspective."', answer: 'Theory A (Rational choice): Voters calculate costs vs benefits → abstain when impact seems low. Strength: explains low turnout in safe seats. Theory B (Social capital): Declining community bonds → less civic participation. Strength: explains correlation between community decline and turnout. Theory C (Political alienation): Voters believe the system doesn\'t represent them → they disengage. Strength: supported by "the growing body of evidence on institutional distrust." Author favours: Theory C (alienation). Signal: "most strongly supports" = the author\'s verdict. The phrase "while all three capture part" is a concession to A and B before favouring C.', answerExplanation: 'The author presents three theories fairly but ultimately favours Theory C. The giveaway is "most strongly supports" — this is the author\'s evaluative voice, not a neutral description. "While all three capture part" acknowledges A and B but positions them as incomplete. At C1, identifying the author\'s favoured position within a multi-theory discussion is a key reading skill.' },
        ],
        keyTakeaways: ['SQ3R: Survey → Question → Read → Recite → Review — slow but effective for academic texts', 'Track competing theories by: claim, evidence, weaknesses, and whether the author favours one', '"Most strongly supports" and "demonstrates" signal the author\'s preferred theory'],
      },
      // # ─── Lesson 7: Metadiscourse — Writers Talking About Their Own Text ───
      { id: 'c1-reading-metadiscourse', title: 'Metadiscourse — Writers Talking About Their Own Text', description: 'Understand how writers guide you through their argument using self-referential language.',
        skill: 'reading', level: 'C1', duration: 10,
        objectives: ['Recognise metadiscourse markers that structure the argument', 'Distinguish between textual metadiscourse (organisation) and interpersonal metadiscourse (attitude)', 'Use metadiscourse as a reading aid for complex texts'],
        sections: [
          { title: 'Types of Metadiscourse', type: 'rule', content: 'Metadiscourse = the writer talking about their own text. TEXTUAL (organisational): "This paper will argue that..." "As discussed in Section 3..." "The following section examines..." "To summarise the preceding analysis..." "Turning now to the question of..." These are SIGNPOSTS — they tell you where the argument is going. INTERPERSONAL (attitude): "It is important to note that..." "Remarkably, the data show..." "Unfortunately, this approach fails to..." "Crucially, this distinction matters because..." These reveal HOW the writer feels about what they are presenting.' },
          { title: 'Metadiscourse as Navigation', type: 'tip', content: 'In a dense academic text, metadiscourse is your GPS: "This paper first examines X, then considers Y, before arguing Z." → you now have a roadmap. "Having established that A is true, we can now turn to its implications." → the author considers A proven and is moving on. "It would be a mistake to conclude that..." → the author is about to correct a likely misinterpretation. "The significance of this finding cannot be overstated." → the author considers this the most important point. When you feel lost in an academic text, scan for metadiscourse markers — they tell you where you are in the argument and what the author considers important.' },
          { title: 'Find the Navigation', type: 'exercise', question: '"This article has examined three theories of motivation. While each contributes valuable insights, none adequately accounts for cross-cultural variation. In the final section, I propose a framework that integrates the strengths of all three approaches while addressing their limitations. It is essential to note that this framework remains preliminary and requires empirical validation."', answer: 'Metadiscourse mapping: "This article has examined" → textual marker: summarising what came before. "While each contributes... none adequately accounts" → interpersonal: the author\'s evaluation (partial credit but ultimately insufficient). "In the final section, I propose" → textual: signposting what comes next. "It is essential to note" → interpersonal: flagging an important caveat. "Remains preliminary and requires empirical validation" → interpersonal: honest hedging about limitations. Navigation: You know (1) the theory review is DONE, (2) the author found them ALL inadequate, (3) a new framework is coming, and (4) the author considers it preliminary. You are perfectly positioned to read the next section critically.', answerExplanation: 'Without understanding metadiscourse, this paragraph reads as generic text. WITH understanding, it is a precise navigation aid: the author is transitioning from review to proposal, signalling their evaluation (none adequate), and pre-emptively hedging their new contribution (preliminary). C1 readers use metadiscourse to read faster and more accurately — it tells you where the argument IS, where it\'s GOING, and how the author FEELS about it.' },
        ],
        keyTakeaways: ['"This paper argues / examines / proposes" = textual metadiscourse (structural signpost)', '"Crucially / remarkably / unfortunately" = interpersonal metadiscourse (author\'s attitude)', 'When lost in a dense text, scan for metadiscourse — it\'s your navigation system'],
      },
      // # ─── Lesson 8: Reading Philosophy & Abstract Argument ───
      { id: 'c1-reading-philosophy', title: 'Reading Philosophy & Abstract Argument', description: 'Engage with abstract reasoning — ethical dilemmas, thought experiments, and conceptual analysis.',
        skill: 'reading', level: 'C1', duration: 14,
        objectives: ['Follow chains of abstract reasoning', 'Understand thought experiments and their purpose', 'Evaluate the coherence of philosophical arguments'],
        sections: [
          { title: 'How Philosophical Arguments Work', type: 'rule', content: 'Philosophical writing builds arguments through: DEFINITIONS: "By \'justice\' I mean..." — precise definitions are essential because everyday words carry different meanings in philosophy. THOUGHT EXPERIMENTS: "Imagine a society where..." — hypothetical scenarios that test intuitions and reveal assumptions. PREMISES AND CONCLUSIONS: "If we accept A and B, then C necessarily follows." OBJECTIONS AND REPLIES: "One might object that... However, this objection fails because..." DISTINCTIONS: "There is a crucial difference between knowing X and believing X." At C1, you don\'t need to agree — you need to FOLLOW the logic. Ask: "Does the conclusion follow from the premises? Are the premises true?"' },
          { title: 'Engaging with Abstraction', type: 'tip', content: 'Philosophical texts are abstract by design — they strip away specific details to examine PRINCIPLES. "Is it ever right to lie?" is not about any specific lie — it\'s about the principle of honesty. Strategies: (1) CONCRETE EXAMPLES: when a concept is abstract, create your own example. "Utilitarianism maximises total happiness" → what would this mean for a doctor with one organ and five dying patients? (2) PLAY DEVIL\'S ADVOCATE: argue against the text. What would the strongest objection be? (3) IDENTIFY ASSUMPTIONS: what does the author take for granted? "All humans are rational" is an assumption, not a fact. (4) RE-READ: philosophical texts are meant to be read multiple times. Each reading reveals something new.' },
          { title: 'Follow This Argument', type: 'exercise', question: '"Some argue that privacy is a right that should never be violated. However, consider: if a person possesses information that could prevent a terrorist attack, is respecting their privacy more important than saving thousands of lives? This does not mean privacy has no value — only that it must be weighed against other values. Absolute rights, by definition, permit no exceptions. If we accept even one exception, the right is no longer absolute but conditional. The question then becomes: under what conditions may privacy be overridden?"', answer: 'Argument structure: Premise 1: Privacy is claimed as an absolute right. Challenge: A thought experiment (terrorist attack) shows a scenario where most people would accept violating privacy. Key distinction: Absolute rights (no exceptions ever) vs conditional rights (can be overridden under certain conditions). Conclusion: If we accept even one exception, privacy becomes conditional, and the real debate shifts to WHEN it can be overridden. Author\'s technique: Uses a thought experiment to force the reader to confront their own intuitions. If you agree privacy should be violated to prevent terrorism, you have already accepted it is not absolute — and must now define the conditions.', answerExplanation: 'The author does not argue that privacy doesn\'t matter. They argue that it is conditional, not absolute. The thought experiment (terrorist attack) is designed to find the edge case where even strong privacy advocates might agree to an exception. Once that exception is admitted, the logical structure changes from "Should privacy be violated?" (never/always) to "Under what conditions?" (when/how). This is how philosophical arguments reshape the question itself.' },
        ],
        keyTakeaways: ['Philosophical arguments use thought experiments to test principles at their limits', 'Absolute rights permit NO exceptions — one exception makes a right conditional', 'The goal is not to agree but to FOLLOW THE LOGIC — ask: "Does the conclusion follow?"'],
      },
      // # ─── Lesson 9: Reading Political & Policy Texts ───
      { id: 'c1-reading-political-texts', title: 'Reading Political & Policy Texts', description: 'Decode manifestos, policy papers, diplomatic language, and political rhetoric.',
        skill: 'reading', level: 'C1', duration: 12,
        objectives: ['Decode euphemism and diplomatic language', 'Identify hidden agendas and stakeholder interests', 'Read policy documents for both stated and unstated implications'],
        sections: [
          { title: 'Political Language Decoded', type: 'rule', content: 'Political writing uses euphemism and calculated vagueness: "Restructuring" = redundancies / job losses. "Revenue enhancement" = tax increases. "Collateral damage" = civilian deaths. "Right-sizing the workforce" = mass layoffs. "Enhanced interrogation" = torture. "Robust debate" = fierce argument. "The minister misspoke" = the minister lied. "Going forward" = let\'s stop talking about what went wrong. "Lessons have been learned" = we made mistakes but won\'t say what they were. "All options are on the table" = military action is possible. Diplomatic language: "frank and open discussion" = serious disagreement.' },
          { title: 'Reading Policy for Implications', type: 'tip', content: 'Policy documents tell you: STATED GOAL: "To improve educational outcomes." MECHANISM: "By introducing standardised testing at ages 7, 11, and 14." UNSTATED IMPLICATIONS: teachers will teach to the test, creative subjects will be deprioritised, schools will be ranked and funded based on results. To find unstated implications, ask: (1) WHO benefits from this policy? (teachers? students? businesses? government?) (2) WHO is harmed? (whose interests are not mentioned?) (3) What BEHAVIOUR will this policy incentivise? (gaming metrics, narrowing focus?) (4) What is NOT addressed? (the gaps are often deliberate.) (5) What words are ABSENT? (if a health policy never mentions "funding," the writer may be avoiding the cost question.)' },
          { title: 'Decode This Statement', type: 'exercise', question: '"Following a comprehensive review, the Department has decided to streamline service delivery by consolidating regional offices into three national centres. This transformation will enhance efficiency and provide a more consistent customer experience. Affected staff will be offered redeployment opportunities where possible."', answer: 'Decoded: "Comprehensive review" = they studied it (gives authority). "Streamline" = cut costs by reducing offices. "Consolidating" = closing regional offices. "Three national centres" = most people will have to travel further or use phone/online services. "Transformation" = a positive word for a disruptive change. "Enhance efficiency" = save money (not necessarily improve service). "More consistent" = the same everywhere (could mean worse in areas that currently have good local service). "Affected staff" = people who will lose their jobs. "Redeployment opportunities where possible" = some will be moved, many will be redundant ("where possible" = not guaranteed).', answerExplanation: 'Every word in this statement was chosen carefully. "Streamline," "enhance," and "transformation" are positive framing for what is essentially: closing offices, reducing access, and cutting jobs. "Where possible" is the most important phrase — it means not everyone will get a new role. A critical reader looks past the positive framing to the practical reality: fewer offices, less local access, job losses with uncertain outcomes.' },
        ],
        keyTakeaways: ['"Restructuring" = job cuts. "Revenue enhancement" = tax rises. "Misspoke" = lied.', 'Ask: WHO benefits? WHO is harmed? What behaviour does this INCENTIVISE?', '"Where possible" in policy language = not guaranteed — a critical qualifier hidden in positive framing'],
      },
      // # ─── Lesson 10: Narrative Technique in Fiction ───
      { id: 'c1-reading-narrative-technique', title: 'Narrative Technique in Fiction', description: 'Analyse how authors construct narratives — point of view, pacing, flashback, and free indirect discourse.',
        skill: 'reading', level: 'C1', duration: 12,
        objectives: ['Identify narrative point of view and its effects', 'Understand free indirect discourse', 'Analyse how pacing and structure create meaning'],
        sections: [
          { title: 'Point of View', type: 'rule', content: 'FIRST PERSON ("I"): intimate, subjective. The reader only knows what the narrator knows. Unreliable narrators are possible. "I didn\'t steal the money. At least, I don\'t think I did." THIRD PERSON LIMITED: follows one character. "She felt the weight of the decision." — we access HER thoughts, not others\'. THIRD PERSON OMNISCIENT: knows everything. "She felt afraid. He, however, was perfectly calm. Neither knew what would happen next." — the narrator sees all. FREE INDIRECT DISCOURSE: the narrator blends with the character\'s thoughts WITHOUT quotation marks or "she thought." "She stared at the letter. God, what had he done now? She couldn\'t face another crisis." — the second sentence is her thought, presented as narration. This is the most subtle and powerful technique.' },
          { title: 'Pacing & Structure', type: 'tip', content: 'Authors control TIME: SCENE: real-time action. "She opened the door. \'Who are you?\' she asked." (Slow, detailed, important moment.) SUMMARY: condensed time. "The next three years were uneventful." (Fast, unimportant period.) PAUSE: time stops for description or reflection. "The garden was overgrown, wild, beautiful in its abandonment." FLASHBACK: jumps to the past. "Twenty years ago, this garden had been immaculate." ELLIPSIS: time is skipped entirely. "***" or a chapter break. Slow scenes = important moments. Fast summaries = transitions. Long pauses = atmosphere or significance. When a writer slows down, pay attention — something important is happening.' },
          { title: 'Analyse the Technique', type: 'exercise', question: '"She sat in the waiting room, reading the same sentence for the fourth time. The clock ticked. A child cried somewhere down the corridor. She thought of her mother — the way she had always held her hand at the doctor\'s, the warmth of her palm, the quiet reassurance. Her mother was gone now. The nurse appeared. \'Ms Carter?\' She stood."', answer: 'Techniques: (1) PACING — very slow. Short sentences create tension ("The clock ticked." "She stood."). Each sentence is a beat. (2) POINT OF VIEW — third person limited. We only know HER thoughts and perceptions. (3) FLASHBACK — "She thought of her mother" briefly jumps to the past, adding emotional depth. (4) SENSORY DETAIL — "the warmth of her palm" — physical memory. (5) FREE INDIRECT DISCOURSE — "Her mother was gone now." Is this narration or her thought? It blends both. (6) ELLIPSIS — "The nurse appeared" skips an unknown amount of waiting time. The slow pacing tells us this moment is emotionally significant. The flashback to her mother suggests she is facing something alone that she used to face with support.', answerExplanation: 'Every choice the writer made serves the story: short sentences = tension. Flashback = loneliness. "Her mother was gone now" = grief stated as fact, which is more powerful than "She missed her mother." The passage never says she is scared — but the re-reading, the clock, the child crying, and the memory of comfort all IMPLY fear. This is C1 literary reading: understanding HOW the text creates its emotional effect, not just WHAT happens.' },
        ],
        keyTakeaways: ['Free indirect discourse = character\'s thoughts presented as narration, without "she thought"', 'When a writer slows down (short sentences, sensory details), something important is happening', 'Point of view determines what we know — first person can lie, omniscient sees all'],
      },
      // # ─── Lesson 11: Reading Across Disciplines ───
      { id: 'c1-reading-across-disciplines', title: 'Reading Across Disciplines', description: 'Adapt your reading approach for science, humanities, social science, and law.',
        skill: 'reading', level: 'C1', duration: 12,
        objectives: ['Recognise discipline-specific conventions and assumptions', 'Adjust reading strategies for different academic fields', 'Transfer reading skills across unfamiliar domains'],
        sections: [
          { title: 'How Disciplines Differ', type: 'rule', content: 'SCIENCES (physics, biology, chemistry): data-driven. Evidence = experiments, measurements, statistics. Structure: hypothesis → method → results → discussion. Read for: methodology quality, sample size, replication. HUMANITIES (literature, philosophy, history): interpretation-driven. Evidence = texts, arguments, historical records. Structure: thesis → evidence → counter-argument → conclusion. Read for: quality of argument, textual evidence, originality. SOCIAL SCIENCES (psychology, economics, sociology): mixed methods. Evidence = surveys, experiments, case studies, statistics. Structure: varies — often lit review → methods → findings → implications. Read for: both data quality AND interpretive framework. LAW: precedent-driven. Evidence = statutes, case law, legal reasoning. Structure: issue → rule → application → conclusion (IRAC). Read for: precise definitions, exceptions, binding vs persuasive authority.' },
          { title: 'Transferable Reading Skills', type: 'tip', content: 'Regardless of discipline, always: (1) Identify the CLAIM (what is being argued). (2) Evaluate the EVIDENCE (is it strong for THIS field?). (3) Check the METHODOLOGY (how was the evidence obtained?). (4) Look for COUNTER-ARGUMENTS (does the author address them?). (5) Assess the LIMITATIONS (what does the author admit they can\'t prove?). What changes by discipline is the TYPE of evidence considered strong: lab experiments in science, close reading in literature, case law in legal studies. The critical thinking framework transfers — only the content changes.' },
          { title: 'Identify the Discipline', type: 'exercise', question: '(a) "The defendant\'s actions satisfy all three elements of the statute; however, the precedent set in R v Smith [2019] suggests a narrower interpretation may apply." (b) "Analysis of 2,400 survey responses revealed a statistically significant correlation (r=0.42, p<0.01) between screen time and reported anxiety levels." (c) "Austen\'s use of free indirect discourse in Emma creates a deliberate ambiguity between narrator and character, inviting the reader to question their own assumptions."', answer: '(a) LAW — "defendant," "statute," "precedent," case citation [R v Smith], IRAC structure. Read for: precise legal definitions, which precedent applies, whether the interpretation is binding. (b) SOCIAL SCIENCE (psychology/statistics) — survey data, correlation coefficient (r=0.42), p-value, quantitative methods. Read for: sample size, correlation vs causation, self-reported data limitations. (c) HUMANITIES (literary criticism) — "free indirect discourse," "deliberate ambiguity," close reading of a specific text. Read for: quality of textual interpretation, originality of argument, evidence from the text itself.', answerExplanation: 'Each discipline has its own vocabulary, evidence standards, and argument structure. A C1 reader can switch between them — knowing that "precedent" in law, "p-value" in social science, and "free indirect discourse" in literature are each central to their field\'s way of making knowledge. This cross-disciplinary fluency is what distinguishes advanced academic reading.' },
        ],
        keyTakeaways: ['Sciences value experiments, humanities value interpretation, law values precedent', 'The critical framework transfers: claim → evidence → methodology → counter-arguments → limitations', 'Each discipline has its own vocabulary for "strong evidence" — learn the field\'s standards'],
      },
      // # ─── Lesson 12: C1 Reading Review ───
      { id: 'c1-reading-review', title: 'C1 Reading Review: Critical Mastery', description: 'Consolidate all C1 reading skills and prepare for C2-level engagement.',
        skill: 'reading', level: 'C1', duration: 14,
        objectives: ['Demonstrate integrated C1 reading competencies', 'Self-assess advanced critical reading skills', 'Identify areas for C2 development'],
        sections: [
          { title: 'C1 Reading Competencies', type: 'rule', content: 'At C1, you can: ✓ Deconstruct complex, multi-clause sentences. ✓ Identify logical fallacies in published texts. ✓ Detect implicit ideology and hidden framing. ✓ Read academic hedging and gauge confidence levels. ✓ Recognise intertextual references and allusions. ✓ Track arguments across extended academic prose. ✓ Use metadiscourse as a navigation tool. ✓ Follow philosophical and abstract reasoning. ✓ Decode political euphemism and policy language. ✓ Analyse narrative technique in literary fiction. ✓ Adapt reading strategies across disciplines. You are now a CRITICAL reader — you evaluate not just WHAT a text says but HOW it constructs its claims and WHY.' },
          { title: 'C1 → C2 Bridge', type: 'tip', content: 'C2 reading goes beyond criticism to CONSTRUCTION: you don\'t just evaluate arguments — you generate alternative interpretations. You engage with the most complex texts in English: dense philosophy, archaic literary language, cutting-edge research with novel methodology. C2 readers notice what is ABSENT from a text as fluently as what is present. They read genre-defying texts that blend fiction and criticism, science and rhetoric. The transition from C1 to C2 is less about new techniques and more about DEPTH — applying everything you know to increasingly challenging material with greater nuance and insight.' },
          { title: 'Integrated C1 Exercise', type: 'exercise', question: '"The growing consensus among educational researchers — though not without notable dissenters — is that standardised testing, while providing administratively convenient metrics, may inadvertently narrow curriculum and incentivise teaching to the test, a phenomenon that, paradoxically, could undermine the very educational outcomes the tests purport to measure." Analyse: sentence structure, hedging, argument, and implicit ideology.', answer: 'Sentence structure: One 50-word sentence with multiple embedded clauses. Core: "The consensus is that standardised testing may narrow curriculum and undermine educational outcomes." Hedging: "growing consensus" (not universal), "though not without dissenters" (acknowledges opposition), "may inadvertently" (double hedge — possible + unintended), "could undermine" (another hedge). The author is very cautious. Argument: Standardised testing → narrower curriculum → teaching to the test → worse educational outcomes. Paradox: the tool meant to MEASURE quality actually REDUCES quality. Implicit ideology: The text assumes education should be broad, not metric-driven. "Administratively convenient" implies the tests serve bureaucrats, not students. This is a progressive/humanistic educational perspective — a market-oriented lens might frame the same tests as "accountability measures that ensure standards."', answerExplanation: 'This single sentence demonstrates every C1 skill: parsing complex structure, counting hedges, mapping the argument, and identifying the ideological lens. A reader who can do all four simultaneously has mastered C1 reading. The paradox (the measurement tool undermining what it measures) is the central insight — this is Goodhart\'s Law ("when a measure becomes a target, it ceases to be a good measure") applied to education.' },
        ],
        keyTakeaways: ['C1 = critical evaluation of HOW texts construct claims and WHY', 'Hedging, structure, argument logic, and ideology work together — analyse all four', 'C2 goes further: generating alternative interpretations and reading what is ABSENT'],
      },
    ],
  },
  {
    id: 'c2-reading',
    name: 'C2: Reading Skills',
    description: 'Master-level reading — engage with the most complex texts in English, generate original interpretations, and read with scholarly depth.',
    icon: '📖',
    lessons: [
      // # ─── Lesson 1: Reading Ambiguity & Multiple Interpretations ───
      { id: 'c2-reading-ambiguity', title: 'Reading Ambiguity & Multiple Interpretations', description: 'Engage with texts that deliberately resist single interpretations — and thrive in that uncertainty.',
        skill: 'reading', level: 'C2', duration: 14,
        objectives: ['Embrace productive ambiguity rather than resolving it prematurely', 'Generate multiple valid interpretations of the same text', 'Evaluate which interpretations are best supported by evidence'],
        sections: [
          { title: 'Productive Ambiguity', type: 'rule', content: 'At C2, you encounter texts that DELIBERATELY resist simple interpretation. LITERARY AMBIGUITY: "She left the letter on the table." Did she leave it intentionally for someone to find, or forget it? Both readings change the entire story. PHILOSOPHICAL AMBIGUITY: "Freedom is the recognition of necessity." This statement means different things depending on your framework (existentialist, Marxist, Stoic). RHETORICAL AMBIGUITY: "The government\'s response was unprecedented." Positive (never been so strong) or negative (never been so inadequate)? The author may have chosen ambiguity deliberately. Premature resolution (forcing a single meaning) misses the point. The TENSION between interpretations IS the meaning.' },
          { title: 'The Interpretation Spectrum', type: 'tip', content: 'Not all interpretations are equal. Rank by: TEXTUAL SUPPORT: does the text provide evidence for this reading? The strongest interpretations are anchored in specific words, phrases, or structural choices. COHERENCE: does the interpretation make sense of the WHOLE text, not just one part? A reading that explains everything is stronger than one that only explains a paragraph. CONTEXT: does the interpretation fit the historical, cultural, or authorial context? ORIGINALITY: does the interpretation reveal something new? But originality without evidence is speculation, not interpretation. The goal is not "what do I think it means?" but "what does the text support?" — then choose the reading with the strongest evidence and greatest explanatory power.' },
          { title: 'Generate Interpretations', type: 'exercise', question: '"He stood at the edge of the cliff, the wind pulling at his coat. Below, the sea was enormous, indifferent. He had come here to make a decision. He turned around and walked home." What possible interpretations exist? Which is strongest?', answer: 'Interpretations: (1) SUICIDAL CONTEMPLATION → CHOOSING LIFE: He came to the cliff considering suicide but chose to live. Evidence: "edge of the cliff" + "make a decision" + "turned around." (2) METAPHORICAL CROSSROADS: The cliff represents a life decision (career, relationship, identity). He chose the safe path. Evidence: "decision" is never specified — any major choice fits. (3) NATURE\'S INDIFFERENCE: The sea is "indifferent" — whatever his crisis, the universe doesn\'t care. His decision to walk home is accepting insignificance. (4) LITERAL: A man goes for a walk, enjoys the view, goes home. Ranking: (1) is strongest — "edge of the cliff" + "decision" + "turned around" is a recognisable narrative pattern. (2) is valid but less specific. (4) is possible but ignores the loaded language. (3) is sophisticated but requires reading "indifferent" as thematic rather than descriptive. All are defensible — the text supports multiple readings.', answerExplanation: 'A C2 reader holds multiple interpretations simultaneously, evaluates which are best supported, and recognises that the TENSION between readings is part of the text\'s power. If the author wanted to be clear, they would have written "He had come to jump." The ambiguity is intentional — it makes you an active participant in creating meaning.' },
        ],
        keyTakeaways: ['Ambiguity is often deliberate — premature resolution misses the point', 'Rank interpretations by: textual support, coherence, context, and originality', 'The tension BETWEEN interpretations is itself meaningful'],
      },
      // # ─── Lesson 2: Epistemology in Reading — How Texts Create Knowledge ───
      { id: 'c2-reading-epistemology', title: 'Epistemology in Reading — How Texts Create Knowledge', description: 'Examine how different text types construct claims to truth and authority.',
        skill: 'reading', level: 'C2', duration: 14,
        objectives: ['Understand how different genres claim authority differently', 'Question the epistemological assumptions of any text', 'Recognise the limits of textual knowledge'],
        sections: [
          { title: 'How Texts Claim Truth', type: 'rule', content: 'Different texts establish truth differently: SCIENCE: truth through replicable observation and peer review. "We measured X and found Y. Others can verify." HISTORY: truth through archival evidence and interpretation. "The documents suggest..." (but archives are incomplete and selective). LAW: truth through precedent and procedural rules. "The court held that..." (legal truth ≠ factual truth — a verdict is procedural). JOURNALISM: truth through eyewitness accounts, sources, and fact-checking. "According to three independent sources..." LITERATURE: truth through emotional resonance and recognition. A novel can be "true" without being factual — it captures human experience. PHILOSOPHY: truth through logical argument. If premises are accepted, conclusion follows. Each has LIMITS: science can\'t prove values, law can\'t guarantee justice, history can\'t recover lost voices, literature can\'t be verified.' },
          { title: 'Questioning Knowledge Claims', type: 'tip', content: 'At C2, read every text asking: (1) HOW does this text claim to know what it claims? (2) What would it take to DISPROVE this claim? (3) What types of evidence does this text value — and what does it exclude? (4) Whose PERSPECTIVE is represented and whose is absent? (5) Is this knowledge CONSTRUCTED (shaped by who made it) or DISCOVERED (exists independently)? Science tends toward "discovered." Literary criticism tends toward "constructed." Most knowledge is both — constructed by human methods that aim at something real. A C2 reader is comfortable with this tension rather than collapsing it into simple answers.' },
          { title: 'Compare Knowledge Claims', type: 'exercise', question: 'Three texts about the same event (a factory fire that killed 30 workers): (A) A safety inspector\'s report: "The fire was caused by faulty electrical wiring. The building lacked adequate fire exits." (B) A journalist\'s investigation: "Workers had complained about unsafe conditions for months. Management ignored their concerns to save money." (C) A novelist\'s fictional account based on the event: "She could smell the smoke before she saw it. Her hands trembled as she pushed against a door that would not open." How does each construct truth?', answer: '(A) TECHNICAL TRUTH: the inspector establishes physical cause (wiring) and regulatory failure (exits). Truth through measurement and standards. What it misses: human decision-making, corporate responsibility, workers\' experience. (B) NARRATIVE TRUTH: the journalist establishes systemic failure (ignored complaints) and moral responsibility (management prioritised money). Truth through testimony and investigation. What it misses: technical specifics, legal precision. (C) EXPERIENTIAL TRUTH: the novelist recreates what it FELT LIKE — the fear, the trapped body, the physical reality of dying. Truth through empathy and imagination. What it misses: facts, causes, accountability. Combined: the fire was caused by faulty wiring (A), enabled by corporate negligence (B), and experienced as terror (C). No single text captures the full truth.', answerExplanation: 'A C2 reader recognises that "truth" is constructed differently by each genre, and no single genre captures everything. The inspector, journalist, and novelist are all RIGHT — about different things. The inspector\'s report can\'t make you feel the terror. The novel can\'t identify the wiring fault. The journalist connects them morally but can\'t do either. Full understanding requires reading across genres — each provides a different KIND of truth.' },
        ],
        keyTakeaways: ['Different genres claim truth differently: science (observation), law (precedent), literature (resonance)', 'No single text captures full truth — each genre reveals and hides different aspects', 'At C2, ask: "HOW does this text claim to know? What types of evidence does it value and exclude?"'],
      },
      // # ─── Lesson 3: Reading the Canon — Engaging with Foundational Texts ───
      { id: 'c2-reading-canonical', title: 'Reading the Canon — Engaging with Foundational Texts', description: 'Read texts that have shaped English-language thought — and understand why they still matter.',
        skill: 'reading', level: 'C2', duration: 14,
        objectives: ['Approach historically important texts with appropriate context', 'Read archaic language without losing comprehension', 'Evaluate canonical texts critically — neither worshipping nor dismissing'],
        sections: [
          { title: 'What Is the Canon?', type: 'rule', content: 'The literary and intellectual "canon" = texts considered foundational: LITERATURE: Shakespeare, Austen, Dickens, Orwell, Woolf, Morrison. PHILOSOPHY: Plato, Aristotle, Locke, Mill, Wollstonecraft. SCIENCE: Darwin, Newton, Einstein. POLITICAL THOUGHT: Paine, Marx, King. These texts matter because: they CREATED concepts we still use (Orwell\'s "Big Brother," Shakespeare\'s "star-crossed lovers"), they established GENRES and CONVENTIONS still in use, they are REFERENCED everywhere — missing the reference means missing meaning, and they represent HISTORICAL turning points in how people think. Reading the canon is not about agreeing with it — it\'s about understanding the conversation that shaped modern English-language culture.' },
          { title: 'Reading Old Language', type: 'tip', content: 'Strategies for archaic texts: MODERNISE mentally: "Shall I compare thee to a summer\'s day?" = "Should I compare you to a beautiful summer day?" CONTEXT over WORDS: if a specific word is unclear, get the sentence\'s meaning from the surrounding context. "Forsooth" = indeed. "Hitherto" = until now. "Wherefore" = why (NOT "where"). RHYTHM: older texts, especially poetry, are meant to be read aloud. The rhythm carries meaning. FOOTNOTES: scholarly editions have notes explaining difficult references. Use them. READ SLOWLY: a 200-year-old text requires 50% more time than a modern one. That\'s normal. DON\'T PRETEND: if you don\'t understand, that\'s fine. Note it and return to it. No one understands Shakespeare fully on the first read.' },
          { title: 'Engage with This Text', type: 'exercise', question: '"It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife." — Jane Austen, Pride and Prejudice (1813). What makes this sentence famous? What is Austen actually saying?', answer: 'Surface: A rich single man must want a wife. This sounds like a simple statement of fact. Depth: Austen is being IRONIC. The sentence claims this is "universally acknowledged" — but the novel shows it is actually the FAMILIES WITH DAUGHTERS who want HIM, not the other way around. The "truth" is inverted: it is not that rich men want wives, but that families with unmarried daughters want rich men. Why it\'s famous: (1) It encapsulates the entire novel\'s theme (marriage and money) in one sentence. (2) The irony is invisible on first reading — you only see it after reading the novel. (3) It has become a template: "It is a truth universally acknowledged that X must be in want of Y" is parodied everywhere. (4) It demonstrates Austen\'s technique: appearing to agree with social convention while actually criticising it.', answerExplanation: 'This is perhaps the most famous opening sentence in English literature. Its genius lies in the gap between what it says (rich men want wives) and what it means (society reduces marriage to economics). Austen never says "I disagree with this" — she lets the irony do the work. Reading the canon teaches you to detect these layers. If you read the sentence literally, you miss everything Austen is doing. If you read it critically, you see a brilliant satirist dismantling her society\'s values in a single sentence.' },
        ],
        keyTakeaways: ['Canonical texts created concepts we still use — "Big Brother," "catch-22," "star-crossed"', '"Wherefore" = why (not where). "Forsooth" = indeed. Read archaic text slowly.', 'Austen, Shakespeare, and Orwell often mean the OPPOSITE of what they appear to say — irony is their primary tool'],
      },
      // # ─── Lesson 4: Deconstructionist Reading ───
      { id: 'c2-reading-deconstruction', title: 'Deconstructionist Reading', description: 'Examine how texts undermine their own claims through internal contradictions and unstable meanings.',
        skill: 'reading', level: 'C2', duration: 14,
        objectives: ['Find internal tensions and contradictions within a text', 'Understand how binary oppositions structure meaning', 'Read for what a text suppresses or marginalises'],
        sections: [
          { title: 'What Is Deconstruction?', type: 'rule', content: 'Deconstruction (Derrida) examines how texts are built on BINARY OPPOSITIONS that privilege one term over the other: nature/culture, male/female, reason/emotion, speech/writing, presence/absence. The privileged term is presented as natural, original, or superior. Deconstruction: (1) IDENTIFIES the binary. (2) Shows how the text RELIES on the subordinate term even while dismissing it. (3) Reveals that the binary is UNSTABLE — the boundaries break down under scrutiny. Example: a text praising "natural food" over "processed food" relies on a nature/culture binary. But ALL farming is cultural intervention — "natural" food doesn\'t exist without human cultivation. The binary collapses.' },
          { title: 'Reading the Margins', type: 'tip', content: 'Deconstruction reads what is pushed to the MARGINS: FOOTNOTES: sometimes the most important information is buried in footnotes because it complicates the main argument. QUALIFICATIONS: "This applies in most cases" — what about the exceptions? Those exceptions might undermine the rule. ASSUMED READER: who is the text written FOR? Who is excluded? A "universal" claim that only applies to one culture is not truly universal. SILENCES: what does the text NOT discuss? A history of a city that doesn\'t mention its Indigenous inhabitants tells you about the historian\'s perspective, not reality. Deconstruction doesn\'t destroy texts — it reveals their hidden complexity and limitations.' },
          { title: 'Deconstruct This Text', type: 'exercise', question: '"Science gives us objective facts about the world. Unlike subjective opinions, scientific knowledge is value-free and universal. It transcends culture and personal bias, revealing the world as it truly is."', answer: 'Binary: objective/subjective, fact/opinion, universal/cultural, science/bias. The text privileges: science, objectivity, universality. Deconstruction: (1) "Value-free" — what gets studied is shaped by funding, politics, and values. Climate research gets funded differently under different governments. Science chooses its questions. (2) "Universal" — scientific priorities differ by culture. Western medicine prioritises pharmaceuticals; other traditions prioritise holistic approaches. Both "work" within their frameworks. (3) "Reveals the world as it truly is" — science uses MODELS of reality (quantum mechanics, evolution). Models are useful representations, not direct access to "truth." (4) The text itself is an ARGUMENT (subjective) for objectivity — it uses rhetoric to persuade, undermining its own claim to be above rhetoric. The binary collapses: science is powerful and reliable, but it is not "above" culture, values, or perspective. It is a CULTURAL practice that aspires to objectivity — which is more honest and more interesting than claiming it already has it.', answerExplanation: 'Deconstruction does not argue that science is wrong or useless. It argues that the CLAIM to be value-free and universal is itself a position — a rhetorical move that hides the human choices behind scientific practice. A C2 reader can hold BOTH: "science is the most reliable method we have" AND "science is shaped by the culture that produces it." These are not contradictions — they are the complex reality that the simple binary (objective/subjective) hides.' },
        ],
        keyTakeaways: ['Texts are built on binary oppositions (nature/culture, objective/subjective) that privilege one term', 'Deconstruction shows how the privileged term depends on what it dismisses', 'Margins, footnotes, silences, and qualifications often contain the text\'s hidden complexity'],
      },
      // # ─── Lesson 5: Reading as a Scholar ───
      { id: 'c2-reading-as-scholar', title: 'Reading as a Scholar — Positioning Yourself in Academic Discourse', description: 'Read not just to understand but to contribute — engaging with texts as a participant in ongoing intellectual conversations.',
        skill: 'reading', level: 'C2', duration: 14,
        objectives: ['Read to identify gaps in existing research', 'Position your own thinking in relation to published work', 'Construct original readings that advance the field'],
        sections: [
          { title: 'From Reader to Participant', type: 'rule', content: 'At C2, you stop being a passive consumer of texts and become an active participant in intellectual discourse: IDENTIFYING GAPS: "This paper addresses X and Y, but does not consider Z." "The methodology accounts for A but not B." "This argument works in context C but not in context D." EXTENDING: "Building on Smith\'s framework, I propose..." "If we apply this theory to a different context..." CHALLENGING: "While the evidence supports the author\'s claim about X, their inference about Y does not follow because..." SYNTHESISING: "Combining insights from fields A and B reveals a pattern neither discipline has identified alone." Academic reading at C2 is GENERATIVE — you read to create new knowledge, not just absorb existing knowledge.' },
          { title: 'The Literature Review Mindset', type: 'tip', content: 'When reading at C2, maintain a running mental map: WHAT do we know? (established findings) WHAT don\'t we know? (gaps and limitations) WHAT is contested? (ongoing debates) WHERE do I fit? (your position) Every text you read updates this map. You are not reading to agree or disagree — you are reading to UNDERSTAND THE CONVERSATION and find where YOUR contribution adds value. Questions to ask every text: "What question does this answer?" "What question does it FAIL to answer?" "What would the strongest counter-argument be?" "How does this connect to other things I\'ve read?" "Where is the space for me?"' },
          { title: 'Find the Gap', type: 'exercise', question: '"Three studies have examined the impact of remote work on productivity: Study A (2022) found a 15% increase in self-reported output. Study B (2023) found no significant difference using objective metrics. Study C (2024) found improvements only in knowledge workers, not in customer-facing roles. All three studied US companies."', answer: 'What we know: Remote work may increase self-reported productivity (A) but objective metrics show no clear difference (B). The effect may depend on job type — knowledge workers benefit, customer-facing roles don\'t (C). What we don\'t know / GAPS: (1) Non-US contexts — all studies are US-based. Cultural, infrastructural, and regulatory differences could change results. (2) Long-term effects — the studies cover 1-2 years. What about 5 years? (3) Team-level vs individual productivity — individual output may rise while collaboration suffers. (4) Self-reported vs objective discrepancy (A vs B) is unresolved — which is more valid? (5) Hybrid models — none study part-remote, part-office arrangements. Original contribution space: a non-US study using objective metrics across job types with a hybrid model. This would address multiple gaps simultaneously.', answerExplanation: 'A C2 reader doesn\'t just summarise three studies — they see the GAPS between them and identify where new research would be most valuable. The US-only focus, the self-report vs objective contradiction, and the absence of hybrid models are all spaces for original contribution. This is how literature reviews work in academic writing: you read existing work to find where YOUR work fits. Reading becomes the foundation for creation.' },
        ],
        keyTakeaways: ['C2 reading is GENERATIVE — read to find gaps and create, not just to understand', 'Map: what do we know? What don\'t we? What\'s contested? Where do I fit?', 'Every text you read updates your map of the intellectual conversation — read to participate, not just to observe'],
      },
      // # ─── Lesson 6: Reading Genre-Defying Texts ───
      { id: 'c2-reading-genre-defying', title: 'Reading Genre-Defying Texts', description: 'Engage with texts that blur boundaries — autofiction, essay-novels, literary journalism, and hybrid forms.',
        skill: 'reading', level: 'C2', duration: 12,
        objectives: ['Navigate texts that mix genres (fiction + essay, journalism + memoir)', 'Understand why writers break genre conventions', 'Develop reading strategies for unfamiliar forms'],
        sections: [
          { title: 'Genre-Defying Forms', type: 'rule', content: 'Some of the most important contemporary writing resists categorisation: AUTOFICTION: fiction that uses real elements of the author\'s life. Is it true? Partly. (Knausgård, Sheila Heti) ESSAY-NOVEL: a novel built from essays rather than chapters with plot. (Claudia Rankine, Maggie Nelson) LITERARY JOURNALISM / CREATIVE NON-FICTION: factual reporting with fictional techniques — scene-setting, dialogue, character development. (Joan Didion, Gay Talese) PROSE POETRY: poetry that looks like paragraphs, not verses. Rhythmic, image-dense, compact. FRAGMENTED NARRATIVE: stories told in disconnected pieces. The reader assembles the meaning. (Jenny Offill, Anne Carson) These forms challenge your reading habits. If you expect a novel, autofiction confuses you. If you expect journalism, literary non-fiction surprises you. The first skill is: let the text teach you HOW to read it.' },
          { title: 'Letting the Text Teach You', type: 'tip', content: 'When a text doesn\'t fit your expectations: (1) SUSPEND expectations for the first 10-20 pages. Don\'t impose a template. (2) Notice PATTERNS: is it chronological? Thematic? Associative? Fragmented? (3) Ask: what RULES is this text creating? Every text establishes its own logic. (4) Pay attention to what CONFUSES you — confusion often marks where the text is doing something new. (5) Re-read the opening after you\'ve finished — it usually makes more sense in retrospect. The writer chose this form deliberately. Your job is to figure out WHY this story needed THIS form. A fragmented narrative about trauma might BE fragmented because that\'s how trauma is experienced — the form mirrors the content.' },
          { title: 'What Is This Text Doing?', type: 'exercise', question: '"I am writing this on a Tuesday. My mother called this morning. She asked if I was eating well. I said yes. This is a lie. In 1987, the Brundtland Commission defined sustainable development as development that \'meets the needs of the present without compromising the ability of future generations to meet their own needs.\' My mother has always worried about the future. I have never learned to cook."', answer: 'This text is genre-defying — it blends: personal memoir (mother\'s phone call, lying about eating, not cooking), academic citation (Brundtland Commission, 1987, definition of sustainability), and thematic association (the concept of "meeting needs" links the mother\'s concern with the policy definition). Form: fragmented, associative. Sentences jump between personal and political without transition. WHY this form: the writer is exploring how PERSONAL failures (not eating well, not cooking) connect to SYSTEMIC questions (sustainability, meeting needs). The juxtaposition IS the argument. The mother and the UN report are asking the same question: "Are you taking care of the future?" The writer\'s answer to both is implicitly: no.', answerExplanation: 'A C2 reader recognises that the jump from "my mother" to "the Brundtland Commission" is not random — it is an ASSOCIATIVE link. The word "needs" connects them. The form itself creates meaning: the lack of transitions mirrors the writer\'s inability to connect personal habits with global responsibility. This is how genre-defying texts work — the form IS part of the content. Reading it as either "memoir" or "essay" misses the point. It is both, and the power comes from the collision between them.' },
        ],
        keyTakeaways: ['When a text doesn\'t fit expectations, let the text teach you HOW to read it', 'The form IS content — fragmented narratives about trauma are fragmented for a reason', 'Confusion marks where the text is doing something new — pay attention to it, don\'t resist it'],
      },
      // # ─── Lesson 7: The Ethics of Reading ───
      { id: 'c2-reading-ethics', title: 'The Ethics of Reading', description: 'Consider the responsibilities of the reader — how we engage with difficult, offensive, or ideologically distant texts.',
        skill: 'reading', level: 'C2', duration: 12,
        objectives: ['Engage with historically problematic texts without endorsing their values', 'Understand the difference between understanding and agreeing', 'Develop an ethical reading practice'],
        sections: [
          { title: 'Reading Difficult Texts', type: 'rule', content: 'Many important texts contain values we reject today: HISTORICAL PREJUDICE: canonical texts with racism, sexism, colonialism. PROPAGANDA: understanding how persuasion works requires reading persuasive texts. IDEOLOGICAL OPPOSITION: reading texts you disagree with — political, religious, philosophical. The reader\'s dilemma: to understand these texts, you must temporarily enter their worldview. But entering ≠ endorsing. Reading Mein Kampf to understand how fascism worked is scholarship. Agreeing with it is not. The ethical question: can you engage deeply enough to understand while maintaining critical distance?' },
          { title: 'An Ethical Reading Framework', type: 'tip', content: 'When reading difficult texts: (1) CONTEXTUALISE: when and where was this written? What was normal then? (2) SEPARATE craft from values: a text can be beautifully written AND morally repugnant. (3) LISTEN for ABSENT voices: who cannot speak in this text? Whose perspective is silenced? (4) READ with, THEN against: first understand the text on its own terms, then evaluate it from your perspective. (5) CONSIDER the harm: some texts caused real harm. Acknowledging this is part of ethical reading. (6) REFUSE to sanitise: don\'t pretend problematic texts are unproblematic. Don\'t explain away the racism in a beloved novel — name it. Understanding WHY someone wrote something is not the same as excusing it. Both are important. Neither is sufficient alone.' },
          { title: 'Engage Ethically', type: 'exercise', question: 'A 19th-century novel you are studying is beautifully written and deeply insightful about human nature, but its portrayal of colonised people is dehumanising. How do you read it ethically?', answer: 'Ethical approach: (1) Acknowledge the contradiction: the novel IS both brilliant and harmful. Don\'t resolve this tension by choosing one side. (2) Read for craft: analyse the prose, structure, and psychological insight. Learn from its strengths. (3) Read for ideology: examine HOW it dehumanises — what language, assumptions, and narrative choices construct this portrayal? (4) Listen for absent voices: the colonised people in this novel are WRITTEN ABOUT, not WRITING. What would their version of this story be? (5) Read alongside counter-texts: pair it with postcolonial writing that responds to or challenges this perspective (Chinua Achebe responding to Joseph Conrad, for example). (6) Contextualise without excusing: understand that these views were common in the 19th century. But "common" ≠ "acceptable" — people in that era also criticised colonialism. The author had choices. This is mature reading: holding complexity rather than collapsing it into "good" or "bad."', answerExplanation: 'Ethical reading refuses both uncritical worship (ignoring the harm) and dismissal (ignoring the value). The most intellectually honest position is BOTH: this novel teaches me about prose and psychology AND this novel teaches me about how racism was normalised in literature. A C2 reader holds both truths simultaneously. Achebe\'s famous essay on Conrad ("An Image of Africa") is the model: he criticises Heart of Darkness for its racism while engaging deeply with its literary techniques. That is ethical reading in practice.' },
        ],
        keyTakeaways: ['Understanding a text ≠ endorsing its values. Both understanding and critique are necessary.', 'Read WITH the text first (understand it on its own terms), then AGAINST it (evaluate critically)', 'Listen for absent voices — who is WRITTEN ABOUT but not WRITING?'],
      },
      // # ─── Lesson 8: C2 Reading Mastery — Integration & Reflection ───
      { id: 'c2-reading-mastery', title: 'C2 Reading Mastery — Integration & Reflection', description: 'Consolidate all reading skills into an integrated, reflective reading practice.',
        skill: 'reading', level: 'C2', duration: 14,
        objectives: ['Integrate all reading strategies into a flexible, adaptive practice', 'Reflect on your own reading processes and biases', 'Read any text in English with confidence, depth, and criticality'],
        sections: [
          { title: 'The C2 Reader', type: 'rule', content: 'At C2, you are not just a reader — you are a THINKER who uses texts as material for understanding the world. You can: ✓ Parse any sentence structure, no matter how complex. ✓ Detect ideology, framing, and hidden assumptions. ✓ Evaluate evidence, methodology, and logical validity. ✓ Generate multiple interpretations and evaluate them. ✓ Read across genres, disciplines, and cultures. ✓ Engage ethically with difficult and historical texts. ✓ Synthesise multiple sources into original understanding. ✓ Read what is ABSENT as fluently as what is present. ✓ Participate in academic discourse as a contributor, not just a consumer. ✓ Let unfamiliar texts teach you new ways of reading. You don\'t just understand what texts say — you understand what they DO, HOW they do it, and WHY.' },
          { title: 'Metacognitive Reading', type: 'tip', content: 'The highest reading skill is METACOGNITION — thinking about your own thinking while reading: "Why did I assume that?" "What in my background made me interpret it this way?" "If I were from a different culture, would I read this differently?" "Am I resisting this text because it\'s wrong, or because it challenges my assumptions?" "What am I bringing to this text that isn\'t actually in the text?" Your reading is shaped by YOUR experiences, biases, and cultural background. A C2 reader is aware of this — and adjusts for it. This is not about eliminating bias (impossible) but about KNOWING your biases so you can read past them when necessary.' },
          { title: 'Final Reflection', type: 'exercise', question: 'Think about a text that changed how you think — a book, article, essay, or poem. Why did it affect you? What reading skills did you need to engage with it fully? How would you read it differently now compared to when you first encountered it?', answer: 'There is no single correct answer — this is a reflective exercise. A strong C2 response would: (1) Name a specific text and explain its impact. (2) Identify which reading skills were essential (inference, cultural context, intertextuality, critical evaluation). (3) Recognise how their reading has EVOLVED — "When I first read it, I took it at face value. Now I can see the ideology beneath the surface / the literary techniques that created the emotional effect / the gaps in its argument." (4) Show metacognitive awareness — "I was affected because of my own experiences with X, which the text mirrored." The ultimate C2 reading skill is SELF-AWARENESS about how you read and why texts affect you the way they do.', answerExplanation: 'This final exercise has no model answer because C2 reading is personal and generative. The point is not to demonstrate knowledge but to demonstrate INTEGRATION — bringing together every skill you\'ve developed (from A1 sign-reading to C2 deconstruction) into a reflective practice. A C2 reader reads the world, not just the page. Every text is an opportunity to understand something about language, culture, power, and yourself.' },
        ],
        keyTakeaways: ['C2 reading = understanding what texts DO and HOW, not just what they SAY', 'Metacognition (thinking about your thinking) is the highest reading skill', 'Reading is never finished — every re-reading reveals something new because YOU have changed'],
      },
    ],
  },
]
