// # ═══════════════════════════════════════════════════════════════════════════
// # PHRASAL VERBS — Extended Set 2: New Fields + Expansions
// # ═══════════════════════════════════════════════════════════════════════════
// # All content is original and copyright-free.
// # This file adds entries to existing fields (same IDs merge in the page)
// # and introduces 8 new fields: Daily Life, Emotions, Food, Sports,
// # Environment, Communication, Driving, Housing.

import type { PhrasalVerbField } from './types'

export const PHRASAL_VERB_FIELDS_2: PhrasalVerbField[] = [

  // # ═══════════════════════════════════════════════════════════════════
  // # EXPANSIONS TO EXISTING FIELDS (merge by ID)
  // # ═══════════════════════════════════════════════════════════════════

  {
    id: 'business',
    name: 'Business & Work',
    description: 'Phrasal verbs used in meetings, emails, negotiations, and professional settings.',
    icon: '💼',
    entries: [
      { phrasalVerb: 'lay off', meaning: 'To dismiss employees, usually because there is not enough work or money.', level: 'B2', context: 'Redundancies, restructuring, and economic downturns.', example: 'The factory laid off 200 workers when orders dropped by 40%.', explanation: '"Lay off" specifically means dismissal due to business reasons (not misconduct). The noun is "layoff" (or "lay-off"): "mass layoffs", "a round of layoffs." Different from "fire" (= dismiss for poor performance/misconduct) and "make redundant" (British formal term). Can also mean "stop bothering/criticising": "Lay off — I\'m doing my best!"', separable: true, formalEquivalent: 'make redundant / dismiss' },
      { phrasalVerb: 'step down', meaning: 'To resign voluntarily from a position of authority.', level: 'B2', context: 'Leadership changes, political resignations, and board exits.', example: 'The CEO stepped down after 15 years to pursue personal interests.', explanation: '"Step down" implies a voluntary, often graceful departure — it\'s not being fired. Common collocations: "step down as CEO/chairman/president", "step down from the board." Similar: "stand down" (British English, same meaning). Opposite: "step up" (= take on more responsibility): "She stepped up to lead the team."', separable: false, formalEquivalent: 'resign / relinquish one\'s position' },
      { phrasalVerb: 'scale up', meaning: 'To increase the size, amount, or scope of something significantly.', level: 'B2', context: 'Business growth, production expansion, and technology deployment.', example: 'After the successful pilot, we need to scale up production to meet demand.', explanation: '"Scale up" implies growing in a structured way — not just getting bigger, but doing so efficiently. Opposite: "scale down" or "scale back" (= reduce). Very common in tech/startup language: "scale up the infrastructure", "scale up operations." The adjective "scalable" describes something designed to grow: "a scalable business model."', separable: true, formalEquivalent: 'expand / increase capacity' },
    ],
  },

  {
    id: 'medical',
    name: 'Medical & Healthcare',
    description: 'Phrasal verbs used by doctors, nurses, and patients in clinical settings.',
    icon: '🏥',
    entries: [
      { phrasalVerb: 'break out', meaning: 'To suddenly appear or develop on the skin (rash, spots, sweat).', level: 'B1', context: 'Describing sudden onset of skin conditions or symptoms.', example: 'She broke out in a rash after eating shellfish.', explanation: 'In medical contexts, "break out" describes sudden skin reactions: "break out in a rash/hives/spots/sweat/blisters." The noun is "breakout": "an acne breakout." Different from the general meaning "break out" = escape ("break out of prison") or suddenly start ("war broke out").', separable: false, formalEquivalent: 'develop / erupt' },
      { phrasalVerb: 'pull through', meaning: 'To survive a serious illness, operation, or crisis.', level: 'B2', context: 'Hospitals, critical care, and recovery from serious conditions.', example: 'The doctors weren\'t sure he would pull through, but he made a full recovery.', explanation: '"Pull through" implies surviving something life-threatening — it carries hope and relief. Often used by families and medical staff: "We\'re hoping she\'ll pull through." Can also be used figuratively: "The company pulled through the financial crisis." Similar: "come through" (= survive/recover).', separable: false, formalEquivalent: 'survive / recover' },
      { phrasalVerb: 'wear off', meaning: 'To gradually lose effect or disappear (medication, anaesthetic, pain).', level: 'B1', context: 'Pain management, post-surgery, and describing fading effects.', example: 'The anaesthetic is starting to wear off — I can feel tingling in my fingers.', explanation: '"Wear off" = effect slowly diminishes over time. Common with: anaesthetic, painkiller, medication, sedative, caffeine, novelty, excitement. "The initial excitement wore off after a few weeks." Opposite of "kick in" (= start working): "Wait for the painkiller to kick in, and when it wears off, take another one."', separable: false, formalEquivalent: 'diminish / dissipate' },
    ],
  },

  {
    id: 'academic',
    name: 'Academic & Education',
    description: 'Phrasal verbs for studying, research, and academic writing.',
    icon: '🎓',
    entries: [
      { phrasalVerb: 'read up on', meaning: 'To study a topic thoroughly by reading about it, especially in preparation.', level: 'B2', context: 'Exam preparation, interview prep, and researching unfamiliar topics.', example: 'I need to read up on the company before my interview tomorrow.', explanation: '"Read up on" implies deliberate, focused reading to gain knowledge about a specific topic. Different from just "reading" — it has purpose and intensity. "I\'ve been reading up on climate change for my essay." Often used before something important: "Read up on the topic before the meeting."', separable: false, formalEquivalent: 'research / study thoroughly' },
      { phrasalVerb: 'brush up on', meaning: 'To refresh or improve knowledge or skills that have become rusty.', level: 'B2', context: 'Returning to a skill after a gap, exam revision, and professional development.', example: 'I need to brush up on my French before the trip to Paris.', explanation: '"Brush up on" implies you ONCE had the skill/knowledge but it has faded from lack of use. You brush up ON something you already partly know — it\'s refreshing, not learning from scratch. Common: "brush up on your grammar/maths/cooking skills." Without "on": "She needs to brush up before the exam."', separable: false, formalEquivalent: 'revise / refresh one\'s knowledge' },
      { phrasalVerb: 'sum up', meaning: 'To give a brief summary of the main points.', level: 'B1', context: 'Presentations, essays, meetings, and discussions.', example: 'To sum up, the project was a success despite the initial challenges.', explanation: '"Sum up" = condense the key points into a short statement. Used at the end of presentations, essays, and discussions: "To sum up...", "Let me sum up the main findings." A "summary" or "summing-up" is the noun. Can also mean to assess quickly: "She summed him up in seconds" (= formed a quick opinion about him).', separable: true, formalEquivalent: 'summarise / recapitulate' },
    ],
  },

  {
    id: 'travel',
    name: 'Travel & Hospitality',
    description: 'Phrasal verbs for airports, hotels, transport, and sightseeing.',
    icon: '✈️',
    entries: [
      { phrasalVerb: 'see off', meaning: 'To go to the departure point (airport, station) to say goodbye to someone.', level: 'B1', context: 'Farewells at airports, train stations, and ports.', example: 'Her whole family came to the airport to see her off.', explanation: '"See someone off" = accompany them to their departure point and say goodbye. Emotional and caring — it shows you care enough to make the trip. "We went to the station to see them off." Also has a completely different meaning: "see off a threat/intruder" (= repel/defeat): "The dog saw off the burglar."', separable: true, formalEquivalent: 'bid farewell to' },
      { phrasalVerb: 'drop off', meaning: 'To take someone or something to a place and leave them there, usually by car.', level: 'A2', context: 'School runs, taxi rides, and delivering items.', example: 'I\'ll drop you off at the station on my way to work.', explanation: '"Drop off" = deliver by car without staying. Very common for daily routines: "drop the kids off at school", "drop off the parcel." The noun is "drop-off": "the drop-off point", "airport drop-off." Also means to fall asleep: "I dropped off during the film" (= fell asleep unintentionally). And to decrease: "Sales have dropped off recently."', separable: true, formalEquivalent: 'deliver / deposit' },
      { phrasalVerb: 'put up', meaning: 'To provide accommodation for someone; to let someone stay in your home.', level: 'B2', context: 'Hosting visitors, informal accommodation, and hospitality.', example: 'We can put you up for the night if you don\'t want to drive home in the dark.', explanation: '"Put someone up" = give them a place to sleep, usually temporarily and informally. "Can you put me up for the weekend?" = Can I stay at your place? Different from "put up with" (= tolerate): "I can\'t put up with this noise anymore." Also: "put up" = erect/build: "put up a tent/shelf/poster."', separable: true, formalEquivalent: 'accommodate / provide lodging for' },
    ],
  },

  {
    id: 'technology',
    name: 'Technology & IT',
    description: 'Phrasal verbs for computing, software, troubleshooting, and digital communication.',
    icon: '💻',
    entries: [
      { phrasalVerb: 'plug in', meaning: 'To connect a device to a power source or port.', level: 'A2', context: 'Setting up devices, charging, and hardware connections.', example: 'My phone is dead — I need to plug it in and charge it.', explanation: '"Plug in" = connect to power or another device via a cable. Opposite: "unplug" or "plug out." The noun is "plug-in" (or "plugin"): software add-ons are called "plugins" (e.g., browser extensions). "Plug into" = connect to a system: "The printer plugs into the USB port."', separable: true, formalEquivalent: 'connect / attach' },
      { phrasalVerb: 'scroll through', meaning: 'To move through digital content by swiping or using a scroll wheel.', level: 'B1', context: 'Social media, websites, documents, and mobile apps.', example: 'I spent an hour scrolling through my social media feed before realising it.', explanation: '"Scroll through" is one of the defining actions of modern life — moving through content on a screen. "Scroll through your emails", "scroll through Instagram." "Scroll down" = move down the page; "scroll up" = move up. "Doomscrolling" = compulsively scrolling through bad news. The term comes from physical scrolls of paper.', separable: false, formalEquivalent: 'browse / navigate through' },
      { phrasalVerb: 'phase out', meaning: 'To gradually stop using or producing something over a period of time.', level: 'B2', context: 'Technology transitions, policy changes, and product discontinuation.', example: 'The company is phasing out its older software and replacing it with a cloud-based system.', explanation: '"Phase out" implies a gradual, planned removal — not sudden. Common: "phase out old technology/products/policies." Opposite: "phase in" (= introduce gradually): "The new system will be phased in over six months." The noun is "phase-out": "the phase-out of leaded petrol."', separable: true, formalEquivalent: 'discontinue gradually / withdraw' },
    ],
  },

  {
    id: 'finance',
    name: 'Finance & Banking',
    description: 'Phrasal verbs for banking, investing, budgeting, and financial planning.',
    icon: '📊',
    entries: [
      { phrasalVerb: 'bail out', meaning: 'To provide financial help to save a person, company, or economy from failure.', level: 'B2', context: 'Government rescues, corporate finance, and personal loans.', example: 'The government bailed out the banks during the financial crisis.', explanation: '"Bail out" in finance = rescue with money. The noun is "bailout": "a $700 billion bailout." Controversial because it often means taxpayers fund the rescue: "Why should we bail out companies that took bad risks?" Also means to jump out of a plane with a parachute, or to escape a bad situation: "I bailed out of the project before it collapsed."', separable: true, formalEquivalent: 'provide financial rescue / subsidise' },
      { phrasalVerb: 'shell out', meaning: 'To pay a large amount of money, often reluctantly.', level: 'B2', context: 'Unexpected expenses, large purchases, and complaints about costs.', example: 'We had to shell out £3,000 for emergency roof repairs.', explanation: '"Shell out" implies the amount feels large and the payment is reluctant or painful. Always informal: "I don\'t want to shell out £200 for a concert ticket." You shell out FOR something: "shell out for a new laptop." Similar: "fork out" (= pay reluctantly, British informal): "I had to fork out £500 for car repairs."', separable: false, formalEquivalent: 'expend / disburse' },
      { phrasalVerb: 'rip off', meaning: 'To charge someone far too much; to cheat or swindle financially.', level: 'B1', context: 'Consumer complaints, tourist traps, and unfair pricing.', example: 'That restaurant totally ripped us off — £25 for a sandwich and a drink!', explanation: '"Rip off" = overcharge or cheat. The noun is "rip-off": "What a rip-off!" (= that\'s too expensive). "A rip-off artist" = someone who habitually cheats people. Also means to copy/steal ideas: "That film is a rip-off of the original." Very informal and strong — implies deliberate dishonesty or extreme unfairness.', separable: true, formalEquivalent: 'overcharge / swindle' },
    ],
  },

  {
    id: 'relationships',
    name: 'Relationships & Social Life',
    description: 'Phrasal verbs for friendships, dating, family, and social interactions.',
    icon: '❤️',
    entries: [
      { phrasalVerb: 'drift apart', meaning: 'To gradually become less close to someone over time, without a specific argument.', level: 'B2', context: 'Long-term friendships, post-school relationships, and life changes.', example: 'We were best friends at university, but we drifted apart after graduation.', explanation: '"Drift apart" describes a slow, natural process — not a dramatic falling out. People drift apart when they move to different cities, develop different interests, or simply grow in different directions. The image is of two boats slowly floating away from each other. "They didn\'t argue — they just drifted apart over the years."', separable: false, formalEquivalent: 'become estranged gradually' },
      { phrasalVerb: 'look up to', meaning: 'To admire and respect someone, often as a role model.', level: 'B1', context: 'Family relationships, mentoring, and describing role models.', example: 'I\'ve always looked up to my older sister — she\'s incredibly brave and kind.', explanation: '"Look up to" = admire from a position of respect. Often used for parents, teachers, and public figures: "Children look up to their parents." Opposite: "look down on" (= feel superior to, disrespect): "She looks down on people who didn\'t go to university." "Look up to" is always positive; "look down on" is always negative.', separable: false, formalEquivalent: 'admire / respect' },
      { phrasalVerb: 'put up with', meaning: 'To tolerate something unpleasant or annoying without complaining.', level: 'B2', context: 'Difficult situations, annoying people, and endurance.', example: 'I don\'t know how she puts up with his constant complaining.', explanation: '"Put up with" = tolerate reluctantly. It implies you DON\'T like the situation but you accept it: "I can put up with the noise during the day, but not at night." Common in complaints: "I\'m not going to put up with this any longer!" Always inseparable: "put up with it" (NOT "put it up with"). Similar: "bear" (formal), "stand" (informal): "I can\'t stand/bear this heat."', separable: false, formalEquivalent: 'tolerate / endure' },
    ],
  },

  {
    id: 'legal',
    name: 'Legal & Law Enforcement',
    description: 'Phrasal verbs used in courts, policing, contracts, and legal proceedings.',
    icon: '⚖️',
    entries: [
      { phrasalVerb: 'cover up', meaning: 'To hide the truth about something wrong or illegal.', level: 'B2', context: 'Scandals, investigations, and whistleblowing.', example: 'The company tried to cover up the environmental damage caused by the chemical spill.', explanation: '"Cover up" = deliberately conceal wrongdoing. The noun is "cover-up": "a government cover-up", "the Watergate cover-up." It implies active deception — not just not telling, but hiding evidence, lying, or misleading. "Cover up" also has a literal meaning: "Cover up the stain with paint" (= physically hide).', separable: true, formalEquivalent: 'conceal / suppress evidence' },
      { phrasalVerb: 'hand over', meaning: 'To give something to someone in authority, or to transfer control.', level: 'B1', context: 'Surrendering evidence, transferring control, and delivering items.', example: 'The suspect was ordered to hand over his passport to the police.', explanation: '"Hand over" = give to someone, often reluctantly or by obligation. Common in legal/police contexts: "hand over evidence/documents/weapons/keys." Also for transfers of power: "The outgoing president handed over power to the new leader." Can be used as a demand: "Hand it over!" (= give it to me now).', separable: true, formalEquivalent: 'surrender / relinquish' },
      { phrasalVerb: 'lock up', meaning: 'To put someone in prison; to secure a building by locking all doors.', level: 'B1', context: 'Criminal sentencing, building security, and safety.', example: 'The judge ordered the criminal to be locked up for ten years.', explanation: 'Two meanings: 1) IMPRISON: "They locked him up and threw away the key" (= imprisoned for a very long time). "Lockup" (noun) = a prison cell, especially temporary: "spent the night in the lockup." 2) SECURE a building: "Make sure you lock up before you leave." "Lock up the shop" = close and secure it.', separable: true, formalEquivalent: 'imprison / incarcerate' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # NEW FIELDS
  // # ═══════════════════════════════════════════════════════════════════

  {
    id: 'daily-life',
    name: 'Daily Life & Home',
    description: 'Phrasal verbs for everyday routines — waking up, cleaning, shopping, and getting through the day.',
    icon: '🏠',
    entries: [
      { phrasalVerb: 'wake up', meaning: 'To stop sleeping; to become conscious after sleep.', level: 'A1', context: 'Morning routines, alarm clocks, and daily schedules.', example: 'I usually wake up at 6:30, but on weekends I sleep until 9.', explanation: '"Wake up" can be used with or without an object: "I woke up early" (no object — you woke yourself) or "The noise woke me up" (transitive — something else woke you). Different from "get up" (= leave your bed): you might "wake up" at 7 but not "get up" until 7:30. "Wake-up call" = a phone call to wake you (hotel), or figuratively: "a wake-up call" = an event that makes you realise something important.', separable: true, formalEquivalent: 'awaken / rouse' },
      { phrasalVerb: 'tidy up', meaning: 'To make a place neat and organised by putting things where they belong.', level: 'A2', context: 'Housework, preparing for visitors, and maintaining order.', example: 'Can you tidy up the living room before the guests arrive?', explanation: '"Tidy up" is mainly British English — American English prefers "clean up" or "straighten up." You tidy up a ROOM or SPACE, or tidy up without an object: "I spent Saturday morning tidying up." Different from "clean" (which implies removing dirt) — "tidy" means putting things in order. "Tidy away" = put things back where they belong: "Tidy away your toys."', separable: true, formalEquivalent: 'organise / neaten' },
      { phrasalVerb: 'throw away', meaning: 'To put something in the rubbish because you no longer want or need it.', level: 'A2', context: 'Decluttering, waste disposal, and making decisions about possessions.', example: 'Don\'t throw away those old photos — they might be valuable one day.', explanation: '"Throw away" = discard, dispose of. Synonym: "throw out." "Throw away" can also be figurative: "throw away an opportunity" (= waste it), "throw away money" (= spend wastefully). A "throwaway" (adjective) = designed to be discarded: "throwaway cups", "a throwaway society" (= a society that wastes too much). "Throwaway remark" = casual comment (not meant seriously).', separable: true, formalEquivalent: 'discard / dispose of' },
      { phrasalVerb: 'put away', meaning: 'To return something to its correct storage place.', level: 'A2', context: 'Housekeeping, cooking, and teaching children to be tidy.', example: 'Please put your clothes away — don\'t just leave them on the floor.', explanation: '"Put away" = place in the correct position for storage. Different from "throw away" (discard): "put away" means you\'re KEEPING it, just storing it properly. "Put away the dishes" = return to cupboard. "Put your phone away" = stop using it and store it. Also informal: "put away food" = eat a lot: "He can really put it away!" And: "put away" = imprison (informal): "He was put away for five years."', separable: true, formalEquivalent: 'store / return to its place' },
      { phrasalVerb: 'run out of', meaning: 'To use all of something so that none is left.', level: 'B1', context: 'Shopping, cooking, resources, and time management.', example: 'We\'ve run out of milk — could you pick some up on your way home?', explanation: '"Run out of" = exhaust your supply. You run out of: milk, petrol, money, time, patience, ideas, options. Without "of" for the thing itself: "The milk has run out" (= there\'s none left). "Time is running out" = we need to hurry. "My patience is running out" = I\'m about to lose my temper. The adjective "run-down" (from "run down") = tired/neglected: "a run-down building."', separable: false, formalEquivalent: 'exhaust / deplete' },
      { phrasalVerb: 'sort out', meaning: 'To organise, resolve, or fix something; to deal with a problem.', level: 'B1', context: 'Problem-solving, organisation, and conflict resolution.', example: 'I need to sort out my finances — I have no idea how much I\'m spending.', explanation: '"Sort out" has two main meanings: 1) ORGANISE: "sort out your desk/files/wardrobe" (= put in order); 2) RESOLVE a problem: "We need to sort out this misunderstanding" (= fix it). "Sort yourself out" = get your act together: "You need to sort yourself out before the interview." British English uses "sort" heavily: "Get it sorted!" = fix it, deal with it.', separable: true, formalEquivalent: 'resolve / organise' },
      { phrasalVerb: 'get by', meaning: 'To manage to survive or cope, especially with limited resources.', level: 'B2', context: 'Financial struggles, language survival, and managing difficult situations.', example: 'It\'s difficult, but we get by on my salary alone.', explanation: '"Get by" = manage, but only just — it implies things are tight but you\'re surviving. "I can get by in Spanish" (= I know enough to manage basic communication, but I\'m not fluent). "They get by on very little money." Similar to "make do" (= manage with what you have): "We\'ll have to make do with what we\'ve got."', separable: false, formalEquivalent: 'manage / cope with limited means' },
      { phrasalVerb: 'catch up on', meaning: 'To do something that you should have done earlier, or to find out what you missed.', level: 'B1', context: 'Work after absence, watching missed episodes, and reconnecting with news.', example: 'I need to catch up on all the emails I missed while I was on holiday.', explanation: '"Catch up on" = do belatedly what you missed or fell behind on. You catch up on: sleep, work, emails, news, a TV series. "Catch up" (without "on") = reach the same level as others: "I missed two weeks of class and now I\'m trying to catch up." "Catch up with someone" = meet socially after a gap: "Let\'s meet for coffee and catch up."', separable: false, formalEquivalent: 'address arrears / attend to overdue matters' },
    ],
  },

  {
    id: 'emotions',
    name: 'Emotions & Feelings',
    description: 'Phrasal verbs for expressing, managing, and describing emotional states.',
    icon: '😊',
    entries: [
      { phrasalVerb: 'cheer up', meaning: 'To become happier, or to make someone feel happier.', level: 'A2', context: 'Comforting someone, overcoming sadness, and encouragement.', example: 'Cheer up! Things will get better soon.', explanation: '"Cheer up" works both ways: "She cheered up when she heard the good news" (became happy), "He brought her flowers to cheer her up" (made her happy). Common as an imperative: "Cheer up!" (= stop being sad). Can sound dismissive if someone has genuine problems — be careful with tone.', separable: true, formalEquivalent: 'become more cheerful / console' },
      { phrasalVerb: 'calm down', meaning: 'To become less angry, excited, or anxious; to make someone less agitated.', level: 'A2', context: 'Arguments, panic, anxiety, and overexcitement.', example: 'Just calm down and tell me what happened.', explanation: '"Calm down" = reduce emotional intensity. Works for anger, panic, and excitement. As an imperative, "Calm down!" can actually make people MORE angry — it feels dismissive. Better: "Take a deep breath" or "Let\'s talk about this calmly." Self-directed: "I need to calm down before I say something I\'ll regret."', separable: true, formalEquivalent: 'compose oneself / become tranquil' },
      { phrasalVerb: 'freak out', meaning: 'To become extremely anxious, frightened, or excited; to panic.', level: 'B1', context: 'Unexpected events, stressful situations, and strong reactions.', example: 'She completely freaked out when she saw a spider in the bathroom.', explanation: 'Informal and expressive. "Freak out" = extreme emotional reaction — can be negative (panic, terror) or positive (extreme excitement): "I freaked out when I met my favourite singer!" Transitive: "The loud bang freaked me out" (= scared me). A "freak-out" is the noun: "She had a total freak-out over the exam results."', separable: true, formalEquivalent: 'panic / become extremely agitated' },
      { phrasalVerb: 'bottle up', meaning: 'To suppress or hide emotions instead of expressing them.', level: 'B2', context: 'Emotional health, therapy, and interpersonal communication.', example: 'He tends to bottle up his feelings, which isn\'t healthy in the long run.', explanation: '"Bottle up" = keep emotions inside like liquid in a bottle. Always implies this is UNHEALTHY: "Don\'t bottle up your anger — talk to someone about it." The image is that eventually the bottle will overflow or explode. "Bottled-up emotions" = feelings that have been suppressed for too long.', separable: true, formalEquivalent: 'suppress / repress' },
      { phrasalVerb: 'let down', meaning: 'To disappoint someone by failing to do what they expected or needed.', level: 'B1', context: 'Broken promises, failed expectations, and trust.', example: 'I\'m sorry I let you down — I should have been there when you needed me.', explanation: '"Let down" = disappoint, fail someone\'s expectations. "I feel let down" = I\'m disappointed in someone. "She let the team down by not preparing." The noun is "letdown" (or "let-down"): "The film was a real letdown after all the hype." Not the same as "let down your hair" (= relax and be informal) or "let down a hem" (= make clothing longer).', separable: true, formalEquivalent: 'disappoint / fail' },
      { phrasalVerb: 'wind up', meaning: 'To deliberately annoy or tease someone, often as a joke.', level: 'B2', context: 'Banter, teasing, pranks, and sibling relationships.', example: 'Stop winding me up — I know you\'re joking.', explanation: 'British English informal. "Wind someone up" = tease, provoke, or annoy them (often playfully). "Are you winding me up?" = Are you joking/teasing me? A "wind-up" is a joke or trick: "It was just a wind-up — relax!" Different from "wind up" meaning to end: "The meeting wound up at 5 p.m." and "wind up" meaning to arrive in a situation: "If you keep drinking, you\'ll wind up in hospital."', separable: true, formalEquivalent: 'provoke / tease' },
      { phrasalVerb: 'open up', meaning: 'To start sharing personal feelings or thoughts that you normally keep private.', level: 'B2', context: 'Therapy, close friendships, and emotional vulnerability.', example: 'It took months before he felt comfortable enough to open up about his childhood.', explanation: '"Open up" emotionally = become vulnerable and share feelings. "She found it hard to open up to people" = she\'s guarded about her emotions. Often used with "about": "open up about your feelings/problems/past." Requires trust: "He only opens up to people he really trusts." Also literal: "open up a shop/business" (= start operating) or "open up!" (= open the door, police command).', separable: false, formalEquivalent: 'confide / become emotionally accessible' },
      { phrasalVerb: 'lighten up', meaning: 'To become less serious, tense, or strict; to relax and have fun.', level: 'B2', context: 'Responding to someone who is being too serious or strict.', example: 'Oh, lighten up — it was just a joke! No need to take everything so seriously.', explanation: '"Lighten up" is almost always used as an imperative directed at someone else: "Lighten up!" = "Don\'t be so serious!" Can sound rude if the person has a genuine reason to be upset. "Lighten the mood" = make a tense situation less serious (not the same phrasal verb, but related). "He needs to lighten up a bit — he\'s always so intense."', separable: false, formalEquivalent: 'relax / become less earnest' },
    ],
  },

  {
    id: 'food-cooking',
    name: 'Food & Cooking',
    description: 'Phrasal verbs used in the kitchen, at restaurants, and when talking about food.',
    icon: '🍳',
    entries: [
      { phrasalVerb: 'heat up', meaning: 'To make food warm or hot, especially leftovers or pre-made food.', level: 'A2', context: 'Kitchens, microwaves, and reheating food.', example: 'Just heat up the soup in the microwave for two minutes.', explanation: '"Heat up" = warm food that has cooled or is pre-cooked. "Warm up" means the same. Different from "cook" — "heat up" implies the food is already prepared and just needs to be made hot again. "The oven takes a while to heat up" = reach the right temperature (also: "preheat").', separable: true, formalEquivalent: 'reheat / warm' },
      { phrasalVerb: 'cut up', meaning: 'To divide food into smaller pieces using a knife.', level: 'A2', context: 'Food preparation, cooking, and feeding children.', example: 'Cut up the vegetables into small cubes before adding them to the pan.', explanation: '"Cut up" = chop into pieces. Can be informal for criticism too: "The critics really cut up his new film" (= criticised harshly). For children: "Shall I cut up your meat for you?" Synonyms in cooking: "chop up", "dice" (into cubes), "slice" (into flat pieces), "mince" (into tiny pieces).', separable: true, formalEquivalent: 'chop / dice' },
      { phrasalVerb: 'eat out', meaning: 'To have a meal at a restaurant rather than at home.', level: 'A2', context: 'Social dining, lifestyle, and food culture.', example: 'We usually eat out on Friday evenings — it\'s a nice way to end the week.', explanation: '"Eat out" = dine at a restaurant or café. Opposite: "eat in" (= eat at home). "Shall we eat out or eat in tonight?" "Eating out" is also a noun phrase: "We spend too much money on eating out." Related: "dine out" (more formal), "go out to eat" (more casual), "grab a bite" (quick informal meal).', separable: false, formalEquivalent: 'dine at a restaurant' },
      { phrasalVerb: 'live on', meaning: 'To eat mainly one type of food as your primary diet.', level: 'B1', context: 'Student life, survival, and dietary habits.', example: 'As a student, I basically lived on instant noodles and toast for three years.', explanation: '"Live on" = survive eating mainly one thing. Often implies the diet is poor or limited: "You can\'t live on pizza alone — you need vegetables." Also means to survive financially: "She lives on £800 a month" (= that\'s her entire budget). And: "live on" = continue to exist after death: "Her music lives on" (= is still remembered and played).', separable: false, formalEquivalent: 'subsist on' },
      { phrasalVerb: 'pig out', meaning: 'To eat a very large amount of food, especially in an uncontrolled way.', level: 'B2', context: 'Parties, comfort eating, and describing overeating.', example: 'We pigged out on pizza and ice cream while watching films all Saturday.', explanation: 'Very informal. "Pig out" = eat excessively and without restraint. Not used in polite company. "Pig out on" + specific food: "We pigged out on chocolate." A "pig-out" is the noun: "We had a massive pig-out at the buffet." The image comes from the way pigs eat — enthusiastically and messily.', separable: false, formalEquivalent: 'overeat / gorge' },
      { phrasalVerb: 'whip up', meaning: 'To prepare food quickly and easily.', level: 'B2', context: 'Improvised cooking, quick meals, and culinary skill.', example: 'She can whip up a delicious pasta dish in under 15 minutes.', explanation: '"Whip up" implies speed, skill, and often improvisation — grabbing whatever is available and making something good from it. "I\'ll whip up some lunch" = I\'ll make something quickly. Also figurative: "whip up enthusiasm/support/a crowd" (= generate quickly): "The politician whipped up anger against the tax increase."', separable: true, formalEquivalent: 'prepare rapidly / improvise a meal' },
    ],
  },

  {
    id: 'sports',
    name: 'Sports & Fitness',
    description: 'Phrasal verbs for exercise, competition, training, and physical activity.',
    icon: '🏃',
    entries: [
      { phrasalVerb: 'work out', meaning: 'To exercise, especially at a gym; also to calculate or solve.', level: 'B1', context: 'Gym, fitness routines, and physical training.', example: 'I work out at the gym three times a week to stay in shape.', explanation: '"Work out" has several meanings: 1) EXERCISE: "She works out every morning before work." A "workout" (noun) = an exercise session: "a tough workout." 2) CALCULATE: "Can you work out the total?" 3) SUCCEED: "Things didn\'t work out between them" (= the relationship failed). 4) UNDERSTAND: "I can\'t work out why she left" (= figure out).', separable: true, formalEquivalent: 'exercise / train' },
      { phrasalVerb: 'warm up', meaning: 'To do light exercises before intense physical activity to prevent injury.', level: 'A2', context: 'Pre-exercise preparation, pre-match routines, and injury prevention.', example: 'Always warm up for at least ten minutes before running to avoid pulling a muscle.', explanation: '"Warm up" = prepare your body for exercise through gentle movement and stretching. The noun is "warm-up": "a five-minute warm-up." Opposite: "cool down" (= gentle exercise after intense activity to gradually reduce heart rate). Also used for performers: "The comedian warmed up the audience" (= got them excited before the main act).', separable: true, formalEquivalent: 'perform preparatory exercises' },
      { phrasalVerb: 'keep up', meaning: 'To maintain the same speed or level as someone else; to continue without falling behind.', level: 'B1', context: 'Running, competition, and maintaining standards.', example: 'She runs so fast — I can\'t keep up with her!', explanation: '"Keep up with" = match someone\'s pace. Physical: "Keep up! You\'re falling behind." Intellectual: "I can\'t keep up with all the new technology." "Keep up" without "with" = continue: "Keep up the good work!" "Keep it up!" = continue doing well. "Keep up with the Joneses" = try to have the same lifestyle as your neighbours (idiom, usually negative).', separable: false, formalEquivalent: 'maintain pace with' },
      { phrasalVerb: 'give up', meaning: 'To stop trying; to quit an activity or habit.', level: 'A2', context: 'Challenges, bad habits, and competitive situations.', example: 'He gave up smoking five years ago and hasn\'t looked back.', explanation: '"Give up" is one of the most common phrasal verbs. Two uses: 1) STOP TRYING: "Don\'t give up — you can do this!"; 2) QUIT a habit: "give up smoking/drinking/sugar." "I give up!" = I can\'t solve this, I surrender. In games: "I give up — what\'s the answer?" "Give up on someone" = stop believing they\'ll improve: "Don\'t give up on him."', separable: true, formalEquivalent: 'abandon / cease / relinquish' },
      { phrasalVerb: 'knock out', meaning: 'To defeat an opponent and eliminate them from a competition; to render unconscious.', level: 'B1', context: 'Boxing, tournament sports, and elimination rounds.', example: 'Brazil were knocked out of the World Cup in the quarter-finals.', explanation: '"Knock out" in sport = eliminate from a competition. A "knockout" (noun) in boxing = when a fighter is rendered unconscious and can\'t continue. Figurative: "The news knocked me out" (= shocked/overwhelmed me). "Knockout" as adjective = stunningly attractive: "She looked like an absolute knockout." "Knock-out round" = elimination stage of a tournament.', separable: true, formalEquivalent: 'eliminate / render unconscious' },
      { phrasalVerb: 'pull out', meaning: 'To withdraw from a competition, event, or agreement, usually due to injury or changed circumstances.', level: 'B2', context: 'Injury withdrawals, business deals, and cancelled appearances.', example: 'The defending champion had to pull out of the tournament due to a knee injury.', explanation: '"Pull out of" = withdraw. Common in sports: athletes "pull out" due to injury, fatigue, or personal reasons. Also in business: "The investor pulled out of the deal at the last minute." And in driving: "pull out" = move from a parked position into traffic. "Pullout" (noun) = a withdrawal: "a military pullout."', separable: false, formalEquivalent: 'withdraw / retire from' },
    ],
  },

  {
    id: 'environment',
    name: 'Environment & Nature',
    description: 'Phrasal verbs for ecology, conservation, pollution, and the natural world.',
    icon: '🌍',
    entries: [
      { phrasalVerb: 'clean up', meaning: 'To remove pollution, waste, or mess from an area.', level: 'B1', context: 'Environmental restoration, community projects, and disaster response.', example: 'Volunteers helped clean up the beach after the oil spill.', explanation: '"Clean up" = remove pollution or mess. A "cleanup" (noun) = the process: "a beach cleanup", "an environmental cleanup." "Clean up your act" = improve your behaviour (idiom). Also: "clean up" = make a lot of money (informal): "He really cleaned up on that property deal."', separable: true, formalEquivalent: 'decontaminate / remediate' },
      { phrasalVerb: 'cut down', meaning: 'To fell trees; also to reduce consumption.', level: 'B1', context: 'Deforestation, conservation, and lifestyle changes.', example: 'Millions of trees are cut down every year to make way for farming.', explanation: '"Cut down" has two main meanings: 1) FELL trees: "They cut down the ancient oak tree to build a road." 2) REDUCE: "I\'m trying to cut down on plastic." In environmental contexts, both meanings are relevant: cutting down trees (deforestation) and cutting down on emissions/waste/plastic (conservation). "Cut down on" + noun = reduce: "cut down on sugar."', separable: true, formalEquivalent: 'fell / reduce' },
      { phrasalVerb: 'die out', meaning: 'To become extinct — to stop existing completely as a species or tradition.', level: 'B2', context: 'Species extinction, cultural loss, and disappearing traditions.', example: 'If we don\'t protect their habitats, many more species will die out.', explanation: '"Die out" = become completely extinct. Used for: species ("The dodo died out in the 17th century"), languages ("Many indigenous languages are dying out"), traditions ("The art of handwriting is dying out"). Different from "die off" (= members of a group dying gradually): "The older generation is dying off."', separable: false, formalEquivalent: 'become extinct / disappear entirely' },
      { phrasalVerb: 'use up', meaning: 'To consume or exhaust something completely so none remains.', level: 'B1', context: 'Resource depletion, waste, and sustainability.', example: 'We\'re using up the earth\'s natural resources faster than they can be replenished.', explanation: '"Use up" = consume entirely. More emphatic than "use": "use" = employ; "use up" = exhaust completely. "We\'ve used up all the paper." "The energy was used up in the first few miles of the race." Related to sustainability: "We\'re using up fossil fuels at an alarming rate."', separable: true, formalEquivalent: 'exhaust / deplete entirely' },
      { phrasalVerb: 'break down', meaning: 'To decompose — to be broken into smaller components by natural processes.', level: 'B2', context: 'Waste management, composting, and pollution.', example: 'Plastic takes hundreds of years to break down in the environment.', explanation: 'In environmental contexts, "break down" = decompose naturally. "Biodegradable" = able to break down: "This packaging breaks down in 90 days." Different from the mechanical meaning: "The car broke down" (= stopped working), the emotional meaning: "She broke down in tears" (= started crying), and the analytical meaning: "break down the data" (= analyse in parts).', separable: false, formalEquivalent: 'decompose / biodegrade' },
      { phrasalVerb: 'wipe out', meaning: 'To destroy completely; to eliminate an entire population or ecosystem.', level: 'B2', context: 'Mass extinction, natural disasters, and catastrophic events.', example: 'The asteroid that hit Earth 66 million years ago wiped out the dinosaurs.', explanation: '"Wipe out" = total destruction. Stronger than "destroy" — implies nothing is left. "Wipe out a species/population/civilisation/village." Also informal: "I was completely wiped out after the marathon" (= exhausted). In surfing: "wipe out" = fall off your board dramatically. A "wipeout" (noun) = a complete failure or fall.', separable: true, formalEquivalent: 'annihilate / eradicate' },
    ],
  },

  {
    id: 'communication',
    name: 'Phone & Communication',
    description: 'Phrasal verbs for phone calls, messaging, and verbal communication.',
    icon: '📱',
    entries: [
      { phrasalVerb: 'hang up', meaning: 'To end a phone call by disconnecting.', level: 'A2', context: 'Phone conversations and telephone etiquette.', example: 'She was so angry that she hung up on me without saying goodbye.', explanation: '"Hang up" = end a phone call. "Hang up on someone" = end the call rudely while they\'re still talking. The term comes from old telephones where you literally hung the receiver on a hook. "Don\'t hang up — I need to tell you something!" "Hang up" can also mean to stop pursuing something: "He hung up his boxing gloves" (= retired from boxing).', separable: true, formalEquivalent: 'terminate the call / disconnect' },
      { phrasalVerb: 'put through', meaning: 'To connect a phone call to the right person or department.', level: 'B1', context: 'Business calls, receptions, and customer service.', example: 'Could you put me through to the accounts department, please?', explanation: '"Put through" = connect a caller. Used by receptionists and operators: "I\'ll put you through to Dr Smith now." "Putting you through" = transferring the call. Also means to cause someone to experience something difficult: "She was put through a gruelling interview" and "He put his family through a lot" (= caused them hardship).', separable: true, formalEquivalent: 'connect / transfer a call' },
      { phrasalVerb: 'get through', meaning: 'To successfully reach someone by phone; to make contact.', level: 'B1', context: 'Busy phone lines, technical difficulties, and persistence.', example: 'I\'ve been trying to get through to the doctor\'s surgery all morning, but the line is always busy.', explanation: '"Get through" = successfully make contact by phone. "I can\'t get through" = the line is busy or nobody answers. Also means: "get through to someone" (= make them understand): "I can\'t get through to him — he just won\'t listen." And: "get through" = finish/survive: "I don\'t know how I got through the exam."', separable: false, formalEquivalent: 'reach / establish contact' },
      { phrasalVerb: 'call back', meaning: 'To return a phone call to someone who called you earlier.', level: 'A2', context: 'Phone etiquette, messages, and professional communication.', example: 'I missed your call — I\'ll call you back in ten minutes.', explanation: '"Call back" = return a call. "Can I call you back?" = I can\'t talk now, I\'ll phone later. A "callback" (noun) = a return call: "I\'m waiting for a callback from the mechanic." In entertainment, a "callback" = a second audition. In programming, a "callback" = a function called after an operation completes.', separable: true, formalEquivalent: 'return a telephone call' },
      { phrasalVerb: 'speak up', meaning: 'To talk louder so people can hear; to express your opinion boldly.', level: 'B1', context: 'Meetings, discussions, and standing up for yourself.', example: 'Could you speak up, please? I can\'t hear you at the back.', explanation: 'Two meanings: 1) VOLUME: "Speak up — we can\'t hear you!" = talk louder. 2) EXPRESS OPINION: "If you disagree, you should speak up" = say what you think, don\'t stay silent. "Speak up for someone" = advocate: "She always speaks up for the underdog." "Speak up against" = voice opposition: "Citizens are speaking up against the new law."', separable: false, formalEquivalent: 'raise one\'s voice / voice one\'s opinion' },
      { phrasalVerb: 'come across', meaning: 'To give a particular impression; to seem or appear a certain way to others.', level: 'B2', context: 'Interviews, first impressions, and communication style.', example: 'She comes across as very confident, but she\'s actually quite shy.', explanation: '"Come across as" = give the impression of being: "He came across as arrogant" (= people perceived him as arrogant, whether or not he actually is). Important in interviews: "How did I come across?" = What impression did I give? Different from "come across" meaning to find unexpectedly: "I came across an old photo in my drawer" (= found by chance).', separable: false, formalEquivalent: 'be perceived as / convey an impression of' },
    ],
  },

  {
    id: 'driving',
    name: 'Driving & Transport',
    description: 'Phrasal verbs used on the road — driving, parking, breakdowns, and traffic.',
    icon: '🚗',
    entries: [
      { phrasalVerb: 'slow down', meaning: 'To reduce speed; to become or make something less fast.', level: 'A2', context: 'Driving, walking, speaking, and life pace.', example: 'Slow down! You\'re driving way too fast for this road.', explanation: '"Slow down" works literally (reduce speed) and figuratively (reduce pace of life). On the road: "Slow down — there\'s a speed camera ahead." In life: "You need to slow down before you burn out." Opposite: "speed up" (= go faster). "A slowdown" (noun) = a reduction in speed or activity: "an economic slowdown."', separable: true, formalEquivalent: 'decelerate / reduce speed' },
      { phrasalVerb: 'pull over', meaning: 'To stop a vehicle at the side of the road.', level: 'B1', context: 'Police stops, emergencies, and roadside breaks.', example: 'The police officer signalled for us to pull over.', explanation: '"Pull over" = drive to the side of the road and stop. Often associated with police: "Pull over!" is what police say when they want you to stop. Also voluntary: "Let\'s pull over and check the map" or "I need to pull over — I feel carsick." "Pull over" is always about moving to the SIDE, not just stopping.', separable: false, formalEquivalent: 'draw to the roadside / stop at the kerb' },
      { phrasalVerb: 'break down', meaning: 'To stop working due to a mechanical failure (vehicles and machines).', level: 'B1', context: 'Vehicle failures, roadside assistance, and mechanical problems.', example: 'Our car broke down on the motorway and we had to wait two hours for a tow truck.', explanation: 'When a vehicle or machine "breaks down", it stops functioning. A "breakdown" (noun) = the event: "We had a breakdown on the M25." "Breakdown cover/service" = roadside assistance: "Do you have breakdown cover?" The mechanical meaning is different from emotional ("She broke down crying"), analytical ("break down the data"), and chemical ("The substance breaks down over time").', separable: false, formalEquivalent: 'malfunction / suffer mechanical failure' },
      { phrasalVerb: 'run over', meaning: 'To hit a person or animal with a vehicle.', level: 'B2', context: 'Road accidents, pedestrian safety, and animal welfare.', example: 'Be careful crossing the road — you could get run over.', explanation: '"Run over" = strike with a vehicle. Very serious: "A child was run over outside the school." "Get run over" = be hit by a vehicle (passive): "He nearly got run over by a bus." Also means to exceed a time limit: "The meeting ran over by 30 minutes" (= went beyond the scheduled end time). And to review quickly: "Let me run over the main points."', separable: true, formalEquivalent: 'strike with a vehicle' },
      { phrasalVerb: 'fill up', meaning: 'To add fuel to a vehicle until the tank is full.', level: 'A2', context: 'Petrol stations, road trips, and fuel management.', example: 'We need to fill up before we get on the motorway — the tank is nearly empty.', explanation: '"Fill up" = refuel completely. "Fill up the car/tank." "Fill it up" is what you say at a petrol station when you want a full tank. Also general: "fill up a container/glass/form." "I\'m full/filled up" = I\'ve eaten enough. "Fill up on bread" = eat a lot of bread (so you\'re not hungry for other food).', separable: true, formalEquivalent: 'refuel / replenish the fuel tank' },
      { phrasalVerb: 'back up', meaning: 'To reverse a vehicle; also for traffic to become congested.', level: 'A2', context: 'Parking, manoeuvring, and traffic jams.', example: 'Can you back up a bit? You\'re too close to the car behind.', explanation: '"Back up" in driving = reverse: "Back up into the parking space." "Traffic is backed up for miles" = there\'s a long queue of stationary vehicles. A "backup" = a traffic jam: "There\'s a huge backup on the A1." Different from "back up" = support ("My team backed me up") and "back up" = make a copy ("back up your files").', separable: true, formalEquivalent: 'reverse / become congested' },
    ],
  },

  {
    id: 'housing',
    name: 'Housing & Property',
    description: 'Phrasal verbs for renting, buying, renovating, and living in a home.',
    icon: '🏡',
    entries: [
      { phrasalVerb: 'move in', meaning: 'To begin living in a new home; to bring your belongings to a new place.', level: 'A2', context: 'Relocating, renting, and starting a new chapter.', example: 'We moved in last Saturday and we\'re still unpacking boxes.', explanation: '"Move in" = start living somewhere new. "Move in with someone" = start living together: "They moved in together after dating for a year." Opposite: "move out" (= leave a home). "Move in" day for students = the day they arrive at university accommodation. "Move-in ready" = a property that needs no work before you can live in it.', separable: false, formalEquivalent: 'take up residence / occupy' },
      { phrasalVerb: 'move out', meaning: 'To leave a home permanently; to take your belongings and go.', level: 'A2', context: 'End of tenancy, leaving home, and relationship changes.', example: 'She moved out of her parents\' house when she turned 18.', explanation: '"Move out" = leave a home. Often marks a life transition: "He moved out after the divorce." "Move out" of your parents\' house = become independent. Landlords can "ask tenants to move out" or "give notice to quit." "Moving out" involves packing, hiring removal vans, and often emotional goodbyes.', separable: false, formalEquivalent: 'vacate / depart from a residence' },
      { phrasalVerb: 'do up', meaning: 'To renovate, repair, or redecorate a building or room.', level: 'B2', context: 'Property renovation, home improvement, and real estate.', example: 'They bought an old farmhouse and spent two years doing it up.', explanation: '"Do up" = renovate/redecorate. Very common in British English property discussions: "We\'re doing up the bathroom", "The house needs doing up." A "do-up" or "doer-upper" (informal) = a property that needs renovation: "It\'s a doer-upper but it has great potential." Also: "do up your coat/zip/buttons" (= fasten/close).', separable: true, formalEquivalent: 'renovate / refurbish' },
      { phrasalVerb: 'knock down', meaning: 'To demolish a building or structure.', level: 'B2', context: 'Urban development, renovation, and construction.', example: 'They knocked down the old factory and built flats on the site.', explanation: '"Knock down" = demolish. Common in property and urban planning: "knock down a wall/building/house." "Knocked-down price" = greatly reduced price (different meaning). "Knock-down, rebuild" = demolish and build from scratch. Can also mean to reduce a price in negotiation: "I knocked them down to £500" (= negotiated a lower price).', separable: true, formalEquivalent: 'demolish / raze' },
      { phrasalVerb: 'put up', meaning: 'To build or erect a structure, wall, or fence.', level: 'B2', context: 'Construction, fencing, shelving, and hanging decorations.', example: 'The neighbours have put up a new fence between our gardens.', explanation: '"Put up" = build/erect. You put up: a fence, a shelf, a tent, a building, a wall, a notice, decorations, curtains. "Put up" has many other meanings: "put up with" (tolerate), "put someone up" (accommodate), "put up a fight" (resist), "put up prices" (increase). Context determines the meaning.', separable: true, formalEquivalent: 'erect / construct' },
      { phrasalVerb: 'sell off', meaning: 'To sell property or assets quickly, often at a reduced price.', level: 'B2', context: 'Property disposal, business liquidation, and clearance sales.', example: 'The council sold off several public buildings to private developers.', explanation: '"Sell off" implies selling quickly, often below market value — there\'s urgency or a desire to get rid of something. "A sell-off" (noun) = a mass sale: "a stock market sell-off" (= many people selling shares), "an asset sell-off." Different from just "selling" — "sell off" carries a sense of disposal, liquidation, or clearing.', separable: true, formalEquivalent: 'liquidate / dispose of at a discount' },
    ],
  },
]
