// # ═══════════════════════════════════════════════════════════════════════════
// # PHRASAL VERBS REFERENCE — Organised by Field / Profession
// # ═══════════════════════════════════════════════════════════════════════════
// # All content is original and copyright-free.
// # Each entry includes: meaning, context, example, explanation,
// # separability, and formal equivalent.

import type { PhrasalVerbField } from './types'

export const PHRASAL_VERB_FIELDS: PhrasalVerbField[] = [

  // # ═══════════════════════════════════════════════════════════════════
  // # 1. BUSINESS & WORK
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'business',
    name: 'Business & Work',
    description: 'Phrasal verbs used in meetings, emails, negotiations, and professional settings.',
    icon: '💼',
    entries: [
      { phrasalVerb: 'carry out', meaning: 'To perform or complete a task, plan, or investigation.', level: 'B2', context: 'Reports, research, and project management.', example: 'The team carried out a thorough analysis of the market data.', explanation: '"Carry out" is the phrasal verb equivalent of "conduct" or "execute". Very common in business and academic English. You carry out: research, a survey, an investigation, a plan, instructions, repairs. It implies completing something that was planned.', separable: true, formalEquivalent: 'conduct / execute' },
      { phrasalVerb: 'set up', meaning: 'To establish, arrange, or create something new.', level: 'B1', context: 'Starting businesses, organising meetings, installing equipment.', example: 'She set up her own consulting firm after leaving the corporate world.', explanation: '"Set up" has several related meanings: 1) Establish a business/organisation: "set up a company"; 2) Arrange: "set up a meeting/appointment"; 3) Install: "set up the projector"; 4) Create conditions: "set up a system/process". The noun is "setup" (one word): "the IT setup".', separable: true, formalEquivalent: 'establish / arrange' },
      { phrasalVerb: 'bring up', meaning: 'To introduce a topic for discussion.', level: 'B2', context: 'Meetings, conversations, and negotiations.', example: 'She brought up the issue of overtime pay during the staff meeting.', explanation: 'In business, "bring up" means to raise a topic. Don\'t confuse with the other meaning: "bring up children" (= raise/rear children). In meetings: "I\'d like to bring up the matter of budget cuts." More formal synonym: "raise" — "She raised the issue of overtime."', separable: true, formalEquivalent: 'raise / mention' },
      { phrasalVerb: 'turn down', meaning: 'To reject or refuse an offer, proposal, or request.', level: 'B2', context: 'Job offers, proposals, applications, and requests.', example: 'He turned down the promotion because it required relocating.', explanation: '"Turn down" is more conversational than "reject" or "decline". Common objects: an offer, a proposal, a request, an application, an invitation. Also means to reduce volume/heat: "Turn down the music." Context makes the meaning clear.', separable: true, formalEquivalent: 'decline / reject' },
      { phrasalVerb: 'take over', meaning: 'To assume control or responsibility for something.', level: 'B2', context: 'Leadership changes, business acquisitions, and shift handovers.', example: 'The new CEO took over the company in January.', explanation: '"Take over" can be about: 1) Business: a company takes over another (= acquisition); 2) Roles: someone takes over from a predecessor; 3) Dominance: "Technology has taken over our lives." The noun is "takeover": "a hostile takeover" (buying a company against its will).', separable: true, formalEquivalent: 'assume control of / acquire' },
      { phrasalVerb: 'draw up', meaning: 'To prepare a written document, plan, or agreement.', level: 'C1', context: 'Legal documents, contracts, business plans, and proposals.', example: 'The lawyers drew up the contract and sent it for review.', explanation: 'Used for formal documents that require careful preparation. Common objects: a contract, a plan, a list, a proposal, a budget, an agreement. "Draw up" implies the creation process, not just writing: it involves thinking, structuring, and finalising.', separable: true, formalEquivalent: 'prepare / draft' },
      { phrasalVerb: 'cut back on', meaning: 'To reduce the amount or level of something, especially spending.', level: 'B2', context: 'Budget discussions, cost reduction, and lifestyle changes.', example: 'The company had to cut back on staff training due to budget constraints.', explanation: '"Cut back on" emphasises reduction for financial or practical reasons. You cut back on: spending, costs, staff, production, consumption. The noun is "cutback": "budget cutbacks". Slightly softer than "cut" (which can mean eliminate entirely). "Cut back" without "on" can also mean to prune plants.', separable: false, formalEquivalent: 'reduce / decrease' },
      { phrasalVerb: 'follow up', meaning: 'To take further action after an initial contact or event.', level: 'B2', context: 'Emails, sales, customer service, and job applications.', example: 'I\'ll follow up with the client next week to check if they received our proposal.', explanation: '"Follow up" is essential in business communication. It means to check progress, send a reminder, or continue a conversation. The noun is "follow-up" (hyphenated): "a follow-up email", "a follow-up meeting", "a follow-up call". "Follow up on" = pursue further: "Let me follow up on that point."', separable: false, formalEquivalent: 'pursue / check on' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 2. MEDICAL & HEALTHCARE
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'medical',
    name: 'Medical & Healthcare',
    description: 'Phrasal verbs used by doctors, nurses, and patients in clinical settings.',
    icon: '🏥',
    entries: [
      { phrasalVerb: 'come down with', meaning: 'To become ill with a particular disease or sickness.', level: 'B1', context: 'Describing the onset of illness in casual conversation.', example: 'I think I\'m coming down with the flu — I\'ve had a sore throat all day.', explanation: 'Informal and conversational — used by patients, not in medical reports. Usually followed by common illnesses: a cold, the flu, a stomach bug, a fever. You wouldn\'t use it for serious diseases: "come down with cancer" sounds wrong — use "be diagnosed with" instead.', separable: false, formalEquivalent: 'contract / develop' },
      { phrasalVerb: 'pass out', meaning: 'To lose consciousness suddenly; to faint.', level: 'B1', context: 'Emergency situations, first aid, and medical histories.', example: 'She passed out from the heat and had to be taken to hospital.', explanation: 'More casual than "faint" or "lose consciousness". Medical professionals use "lose consciousness" in reports but "pass out" in conversation with patients. Also has a completely different meaning: "pass out copies" = distribute. Context makes the meaning clear.', separable: false, formalEquivalent: 'faint / lose consciousness' },
      { phrasalVerb: 'get over', meaning: 'To recover from an illness, shock, or emotional experience.', level: 'B1', context: 'Recovery from illness, breakups, or difficult experiences.', example: 'It took her two weeks to get over the chest infection.', explanation: '"Get over" implies full recovery. Common with: colds, flu, surgery, breakups, shock, disappointment. "Get over it" (imperative) is sometimes used rudely to tell someone to stop being upset. Don\'t confuse with "get over" meaning to cross/pass: "get over a fence."', separable: false, formalEquivalent: 'recover from' },
      { phrasalVerb: 'flare up', meaning: 'To suddenly become worse (of a medical condition or pain).', level: 'B2', context: 'Chronic conditions, allergies, and recurring symptoms.', example: 'My asthma flares up whenever the air quality is poor.', explanation: 'Used for conditions that are normally under control but suddenly worsen. Common with: arthritis, asthma, eczema, allergies, old injuries, inflammation. The noun is "flare-up": "She had a flare-up of her back pain." Comes from the image of a fire suddenly burning brighter.', separable: false, formalEquivalent: 'exacerbate / recur' },
      { phrasalVerb: 'cut down on', meaning: 'To reduce the amount of something you consume or do, especially for health reasons.', level: 'B1', context: 'Health advice, lifestyle changes, and diet.', example: 'The doctor advised him to cut down on sugar and processed foods.', explanation: 'Very common in health contexts. Doctors say "cut down on" rather than "reduce your intake of" when speaking informally with patients. Common objects: sugar, salt, alcohol, smoking, caffeine, red meat, screen time. "Cut down on" = reduce; "cut out" = eliminate completely.', separable: false, formalEquivalent: 'reduce intake of' },
      { phrasalVerb: 'check up on', meaning: 'To examine or visit someone to make sure they are well or safe.', level: 'B1', context: 'Patient monitoring, elderly care, and post-treatment follow-up.', example: 'The nurse checks up on the patient every two hours.', explanation: 'Two related meanings: 1) Medical: visit/examine a patient; 2) General: make sure someone is okay: "I just called to check up on you." The noun is "check-up" (or "checkup"): "a routine check-up", "a dental check-up", "a health check-up".', separable: false, formalEquivalent: 'monitor / examine' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 3. ACADEMIC & EDUCATION
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'academic',
    name: 'Academic & Education',
    description: 'Phrasal verbs for studying, research, and academic writing.',
    icon: '🎓',
    entries: [
      { phrasalVerb: 'look up', meaning: 'To search for information in a reference source.', level: 'A2', context: 'Using dictionaries, databases, and search engines.', example: 'If you don\'t know a word, look it up in the dictionary.', explanation: 'The most basic research phrasal verb. You look up: words (in a dictionary), information (online), phone numbers (in a directory), facts (in a database). Separable: "look it up" or "look up the word" — both correct. Also means "to improve": "Things are looking up" (= getting better).', separable: true, formalEquivalent: 'search for / consult' },
      { phrasalVerb: 'hand in', meaning: 'To submit work to a teacher, professor, or authority.', level: 'A2', context: 'Submitting assignments, essays, and forms.', example: 'Students must hand in their essays by Friday.', explanation: 'British English prefers "hand in"; American English often uses "turn in" (same meaning). You hand in: homework, assignments, essays, reports, forms, your notice/resignation. Separable: "hand in your essay" or "hand your essay in".', separable: true, formalEquivalent: 'submit' },
      { phrasalVerb: 'figure out', meaning: 'To understand something after thinking about it; to solve a problem.', level: 'B1', context: 'Problem-solving, research, and understanding complex topics.', example: 'It took me hours to figure out how to use the new software.', explanation: '"Figure out" implies mental effort — you didn\'t understand at first, but after thinking, you found the answer. More informal than "determine" or "ascertain". Common patterns: "figure out how/why/what/where", "figure out the answer/problem/solution", "I can\'t figure it out" (= I don\'t understand).', separable: true, formalEquivalent: 'determine / work out' },
      { phrasalVerb: 'go over', meaning: 'To review or examine something carefully.', level: 'B1', context: 'Revising for exams, reviewing work, and checking details.', example: 'Let\'s go over the main points before the exam.', explanation: '"Go over" = review systematically. Common objects: notes, a report, the details, the plan, your work. Also used by teachers: "We\'ll go over the answers in class tomorrow." Slightly different from "look over" (= check quickly/superficially) — "go over" implies more thoroughness.', separable: false, formalEquivalent: 'review / examine' },
      { phrasalVerb: 'drop out', meaning: 'To leave a course, school, or programme before finishing it.', level: 'B1', context: 'Education, training programmes, and competitions.', example: 'He dropped out of university in his second year to start a business.', explanation: 'The noun is "dropout": "a university dropout", "a high school dropout". Usually implies leaving without completing: "drop out of school/university/a course/the race/the competition." Can also mean to withdraw from society: "He dropped out and went to live in the mountains."', separable: false, formalEquivalent: 'withdraw from' },
      { phrasalVerb: 'point out', meaning: 'To draw attention to something; to indicate or highlight.', level: 'B1', context: 'Academic discussions, essays, and presentations.', example: 'The professor pointed out several flaws in the methodology.', explanation: 'Very useful in academic writing: "It should be pointed out that..." or "As Smith (2020) points out..." You point out: a fact, a problem, a mistake, an interesting detail. Different from "point at" (physically pointing your finger at something).', separable: true, formalEquivalent: 'indicate / highlight' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 4. TRAVEL & HOSPITALITY
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'travel',
    name: 'Travel & Hospitality',
    description: 'Phrasal verbs for airports, hotels, transport, and sightseeing.',
    icon: '✈️',
    entries: [
      { phrasalVerb: 'check in', meaning: 'To register your arrival at a hotel, airport, or event.', level: 'A2', context: 'Hotels, airports, and conferences.', example: 'We checked in at the hotel and went straight to our room.', explanation: 'At a hotel: "check in" (arrive and register) vs "check out" (leave and pay). At an airport: "check in" = show your ticket and get your boarding pass. The noun is "check-in": "online check-in", "the check-in desk/counter", "check-in time". Can also mean to contact someone briefly: "I\'ll check in with you tomorrow."', separable: false, formalEquivalent: 'register' },
      { phrasalVerb: 'set off', meaning: 'To begin a journey; to depart.', level: 'B1', context: 'Starting road trips, hikes, or any travel.', example: 'We set off at dawn to avoid the traffic.', explanation: '"Set off" emphasises the beginning of a journey. Synonyms: "set out", "head off", "depart". Collocations: "set off early/late", "set off on a journey/trip/adventure". Also has a completely different meaning: "set off an alarm/explosion" (= trigger/activate).', separable: false, formalEquivalent: 'depart' },
      { phrasalVerb: 'pick up', meaning: 'To collect someone from a location, usually by car.', level: 'A2', context: 'Airport transfers, giving someone a lift, collecting items.', example: 'I\'ll pick you up from the airport at 3 p.m.', explanation: 'One of the most versatile phrasal verbs. In travel: collect someone by car. Other meanings: "pick up a language" (= learn informally), "pick up speed" (= accelerate), "pick up the phone" (= answer), "pick up the bill" (= pay). Separable: "pick you up" or "pick up the passengers".', separable: true, formalEquivalent: 'collect' },
      { phrasalVerb: 'get around', meaning: 'To travel from place to place within an area; to find a way to navigate.', level: 'B1', context: 'Local transport, exploring a city, and avoiding obstacles.', example: 'The easiest way to get around Bangkok is by BTS Skytrain.', explanation: '"Get around" = move from place to place within a city/area. "How do you get around?" = "What transport do you use?" Also means to spread (of news): "Word got around quickly." And to avoid a rule/problem: "There\'s no way to get around the regulation."', separable: false, formalEquivalent: 'navigate / travel within' },
      { phrasalVerb: 'stop over', meaning: 'To break a long journey by staying somewhere temporarily.', level: 'B1', context: 'Long-distance flights and road trips.', example: 'We stopped over in Dubai for two nights on our way to Australia.', explanation: 'Specifically about breaking a journey — not just stopping briefly. The noun is "stopover" (one word): "a 24-hour stopover in Singapore." Different from "stop by" (= visit briefly without a plan): "I\'ll stop by your office later." Airline jargon: a "layover" is similar but usually refers to waiting time at an airport between connecting flights.', separable: false, formalEquivalent: 'make a stopover' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 5. TECHNOLOGY & IT
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'technology',
    name: 'Technology & IT',
    description: 'Phrasal verbs for computing, software, troubleshooting, and digital communication.',
    icon: '💻',
    entries: [
      { phrasalVerb: 'log in / log on', meaning: 'To enter your credentials to access a system, website, or app.', level: 'A2', context: 'Accessing accounts, systems, and platforms.', example: 'You need to log in with your username and password.', explanation: '"Log in" and "log on" are interchangeable. The opposite is "log out" / "log off". The noun is "login": "your login details", "the login page." "Sign in / sign out" is increasingly common (used by Google, Microsoft). "Log" originally referred to a ship\'s logbook where entries were recorded.', separable: false, formalEquivalent: 'authenticate / access' },
      { phrasalVerb: 'back up', meaning: 'To make a copy of digital data for safety.', level: 'B1', context: 'Data protection, IT maintenance, and file management.', example: 'Make sure you back up your files before updating the operating system.', explanation: 'Essential IT vocabulary. "Back up" = create a safety copy. The noun is "backup" (one word): "a backup copy", "automatic backup", "cloud backup." Also means to support: "My colleagues backed me up in the meeting" (= supported my position). And to reverse a vehicle: "back up the car."', separable: true, formalEquivalent: 'create a copy / archive' },
      { phrasalVerb: 'shut down', meaning: 'To turn off a computer, system, or machine completely.', level: 'A2', context: 'Ending computer sessions, closing systems, and power management.', example: 'Please shut down your computer before leaving the office.', explanation: '"Shut down" = complete power off (vs "restart" = off then on again, "sleep" = low-power mode). The noun is "shutdown": "a system shutdown", "an emergency shutdown." Also used figuratively: "The factory was shut down due to safety violations" (= closed permanently or temporarily).', separable: true, formalEquivalent: 'power off / deactivate' },
      { phrasalVerb: 'set up', meaning: 'To install and configure software, hardware, or a system.', level: 'B1', context: 'Installing new systems, configuring devices, and initialising software.', example: 'The IT department set up the new email system over the weekend.', explanation: 'In technology, "set up" specifically means to install AND configure — not just install. You set up: a server, a network, an email account, a printer, a database, a new laptop. "Setup" (noun): "the initial setup took about an hour", "setup wizard" (the guided installation process).', separable: true, formalEquivalent: 'install and configure' },
      { phrasalVerb: 'opt in / opt out', meaning: 'To choose to participate in (opt in) or withdraw from (opt out) something.', level: 'B2', context: 'Privacy settings, email subscriptions, and consent.', example: 'Users must opt in to receive marketing emails under GDPR regulations.', explanation: 'Critical in privacy and data protection. "Opt in" = actively choose to participate (requires a positive action). "Opt out" = choose to stop or not participate. GDPR made these terms mainstream. Nouns: "opt-in" and "opt-out" (hyphenated): "an opt-in policy", "an opt-out mechanism."', separable: false, formalEquivalent: 'subscribe / unsubscribe' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 6. FINANCE & BANKING
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'finance',
    name: 'Finance & Banking',
    description: 'Phrasal verbs for banking, investing, budgeting, and financial planning.',
    icon: '📊',
    entries: [
      { phrasalVerb: 'pay off', meaning: 'To finish paying all the money owed; also: to be worth the effort.', level: 'B1', context: 'Loans, mortgages, debts, and describing successful investments.', example: 'It took them 20 years to pay off their mortgage.', explanation: 'Two meanings: 1) Complete debt payment: "pay off a loan/mortgage/credit card/debt"; 2) Produce good results: "All that hard work finally paid off" (= was worthwhile). Don\'t confuse with "pay back" (= return borrowed money to a person): "I\'ll pay you back next week."', separable: true, formalEquivalent: 'settle / repay in full' },
      { phrasalVerb: 'save up', meaning: 'To accumulate money over time for a specific purpose.', level: 'A2', context: 'Personal finance, goal-setting, and budgeting.', example: 'We\'re saving up for a deposit on a house.', explanation: '"Save up" emphasises gradually collecting money over time for a goal. Different from just "save" (which can mean general saving without a specific purpose). Collocations: "save up for a holiday/car/house/wedding." "Savings" (noun, usually plural): "my savings account", "I\'ve used all my savings."', separable: false, formalEquivalent: 'accumulate funds' },
      { phrasalVerb: 'take out', meaning: 'To obtain a financial product from a bank or institution.', level: 'B1', context: 'Banking, insurance, and financial services.', example: 'They took out a loan to renovate their kitchen.', explanation: 'In finance, you "take out": a loan, a mortgage, insurance, a subscription. It means to enter into a financial agreement. Different from the physical meaning: "take out the rubbish" (= remove), "take someone out" (= invite someone on a date), "take out food" (= buy to eat elsewhere).', separable: true, formalEquivalent: 'obtain / acquire' },
      { phrasalVerb: 'put aside', meaning: 'To save money regularly for future use.', level: 'B1', context: 'Budgeting and financial planning.', example: 'She puts aside £200 every month for emergencies.', explanation: '"Put aside" suggests setting money apart from your regular spending — keeping it separate. More disciplined than "save" because it implies a regular, planned action. Also used figuratively: "Let\'s put aside our differences" (= temporarily ignore disagreements). "Set aside" is a synonym.', separable: true, formalEquivalent: 'reserve / allocate' },
      { phrasalVerb: 'write off', meaning: 'To accept a loss by removing a debt or asset from accounts; to dismiss as worthless.', level: 'C1', context: 'Accounting, insurance claims, and evaluating investments.', example: 'The bank wrote off £2 million in bad debts last quarter.', explanation: 'In finance: "write off" = accept that money will not be recovered. A "write-off" (noun) in insurance means a vehicle or item is too damaged to repair — its value is zero. Also informal: "Don\'t write him off yet" (= don\'t dismiss/underestimate him). In tax: "write off expenses" = deduct business costs from taxable income.', separable: true, formalEquivalent: 'deduct / cancel a debt' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 7. RELATIONSHIPS & SOCIAL LIFE
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'relationships',
    name: 'Relationships & Social Life',
    description: 'Phrasal verbs for friendships, dating, family, and social interactions.',
    icon: '❤️',
    entries: [
      { phrasalVerb: 'get along (with)', meaning: 'To have a friendly relationship with someone.', level: 'B1', context: 'Describing relationships with colleagues, neighbours, and family.', example: 'I get along really well with my new flatmates.', explanation: '"Get along with" (British) and "get along with" / "get on with" (also British) are interchangeable. Used to describe the quality of a relationship. "We get along" = our relationship is good. "We don\'t get along" = we often disagree. Also: "How are you getting along?" = "How are things going?"', separable: false, formalEquivalent: 'have a good relationship with' },
      { phrasalVerb: 'break up', meaning: 'To end a romantic relationship.', level: 'B1', context: 'Romantic relationships and partnerships.', example: 'They broke up after five years together.', explanation: '"Break up" = the relationship ends. "Break up with someone" = end the relationship (you initiate). A "breakup" (noun) is the event. Also means: to disperse/scatter: "The police broke up the crowd"; to lose signal: "You\'re breaking up — I can\'t hear you" (phone); to break into pieces: "Break up the chocolate."', separable: false, formalEquivalent: 'end a relationship / separate' },
      { phrasalVerb: 'make up', meaning: 'To become friends again after an argument; to reconcile.', level: 'B1', context: 'Resolving conflicts in relationships.', example: 'They had a terrible argument but made up the next day.', explanation: '"Make up" after a fight = reconcile and restore the relationship. Different meanings: "make up a story" (= invent/fabricate), "make up your mind" (= decide), "make up for" (= compensate). "Make-up" (noun, hyphenated) = cosmetics. "Make up" as reconciliation is almost always used without an object.', separable: false, formalEquivalent: 'reconcile' },
      { phrasalVerb: 'look after', meaning: 'To take care of someone or something.', level: 'A2', context: 'Childcare, eldercare, pet care, and property management.', example: 'My grandmother looks after the children while we\'re at work.', explanation: 'British English strongly prefers "look after" while American English uses "take care of". Common objects: children, elderly parents, pets, a house, someone\'s belongings. "Look after yourself" is a common farewell meaning "take care." Not separable: "look after the children" (NOT "look the children after").', separable: false, formalEquivalent: 'care for / tend to' },
      { phrasalVerb: 'grow up', meaning: 'To develop from a child into an adult; to mature.', level: 'A2', context: 'Talking about childhood, hometown, and personal development.', example: 'I grew up in a small village in the north of England.', explanation: '"Grow up" = the process of becoming an adult. Common questions: "Where did you grow up?" A "grown-up" (noun, hyphenated) = an adult (from a child\'s perspective). "Grow up!" (imperative) = "Stop being childish!" "Upbringing" (noun) = the way you were raised: "She had a strict upbringing."', separable: false, formalEquivalent: 'mature / be raised' },
      { phrasalVerb: 'fall out (with)', meaning: 'To have a serious argument that damages a relationship.', level: 'B2', context: 'Conflicts between friends, family members, or colleagues.', example: 'She fell out with her best friend over a misunderstanding about money.', explanation: '"Fall out with someone" = stop being friends because of a disagreement. Stronger than "argue" — it implies the relationship is damaged, possibly permanently. A "falling-out" (noun): "They had a falling-out over politics." British English mainly — American English prefers "have a fight" or "stop speaking to."', separable: false, formalEquivalent: 'quarrel / become estranged' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 8. LEGAL & LAW ENFORCEMENT
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'legal',
    name: 'Legal & Law Enforcement',
    description: 'Phrasal verbs used in courts, policing, contracts, and legal proceedings.',
    icon: '⚖️',
    entries: [
      { phrasalVerb: 'break into', meaning: 'To enter a building illegally by force.', level: 'B1', context: 'Crime reports, security, and news.', example: 'Thieves broke into the warehouse and stole electronic equipment.', explanation: '"Break into" = force entry for theft or crime. The noun is "break-in": "There was a break-in at the office last night." Also used figuratively: "break into a market/industry" (= enter for the first time), "break into a smile/laugh" (= suddenly start smiling/laughing).', separable: false, formalEquivalent: 'burgle / forcibly enter' },
      { phrasalVerb: 'turn in', meaning: 'To report someone to the authorities, or to hand over evidence.', level: 'B2', context: 'Criminal investigations and police work.', example: 'The suspect turned himself in to the police after seeing his photo on the news.', explanation: '"Turn in" can be: 1) Report to authorities: "turn someone in" or "turn yourself in" (surrender); 2) Submit: "turn in your badge" (= resign from police/military). Also: "turn in" = go to bed (informal): "I\'m going to turn in early tonight."', separable: true, formalEquivalent: 'surrender / report' },
      { phrasalVerb: 'crack down on', meaning: 'To take strict action against illegal or undesirable behaviour.', level: 'B2', context: 'Law enforcement, government policy, and regulation.', example: 'The government is cracking down on tax evasion.', explanation: '"Crack down on" implies becoming stricter and more aggressive in enforcement. Common objects: crime, corruption, tax evasion, speeding, drug dealing, illegal parking. The noun is "crackdown": "a police crackdown on gangs." Implies a sudden increase in enforcement that was previously relaxed.', separable: false, formalEquivalent: 'enforce strictly / clamp down on' },
      { phrasalVerb: 'let off', meaning: 'To not punish someone, or to give a lighter punishment than expected.', level: 'B2', context: 'Courts, schools, and parental discipline.', example: 'The judge let him off with a warning because it was his first offence.', explanation: '"Let off" = forgive or reduce punishment. "Let someone off" or "let someone off with (a warning/fine)". Also: "let someone off the hook" (idiom) = free from obligation or blame. Different from "let off" meaning to fire/explode: "let off fireworks."', separable: true, formalEquivalent: 'acquit / pardon' },
      { phrasalVerb: 'rule out', meaning: 'To exclude something as a possibility.', level: 'B2', context: 'Investigations, diagnosis, and decision-making.', example: 'Police have ruled out suicide — they believe the death was accidental.', explanation: '"Rule out" = eliminate from consideration. Used widely: police "rule out suspects", doctors "rule out diseases", investigators "rule out causes." The opposite is "rule in" (= include as a possibility), but this is less common. "I wouldn\'t rule it out" = it\'s still possible.', separable: true, formalEquivalent: 'exclude / eliminate' },
    ],
  },
]
