// # ═══════════════════════════════════════════════════════════════════════════
// # VOCABULARY REFERENCE DATA — Part 8: Expansion for Part 3 categories
// # ═══════════════════════════════════════════════════════════════════════════
// # Uses the SAME field IDs as vocabulary-data-3.ts to merge via page.tsx.
// # Brings each data-3 category to 50+ words (body-appearance already at 55+).

import type { VocabField } from './types'

export const VOCAB_FIELDS_8: VocabField[] = [

  // # ═══════════════════════════════════════════════════════════════════
  // # 1. CRIME & SAFETY — Expansion (need 16+ more)
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'crime-safety',
    name: 'Crime & Safety',
    description: 'Vocabulary for crime, law enforcement, personal safety, and security measures.',
    icon: '🔒',
    entries: [
      { word: 'accomplice', wordClass: 'noun', level: 'B2', meaning: 'A person who helps someone else commit a crime.', context: 'Criminal partnership and joint offending.', example: 'The robber had an accomplice who drove the getaway car while he entered the bank.', explanation: 'Collocations: "an accomplice to murder/robbery/fraud", "act as an accomplice". In law, an accomplice faces the same charges as the main offender. "Accessory" is similar: "accessory after the fact" = helped after the crime.' },
      { word: 'alibi', wordClass: 'noun', level: 'B2', meaning: 'Evidence or a claim that a person was elsewhere when a crime was committed.', context: 'Criminal defence and police investigation.', example: 'The suspect had a solid alibi — she was at a restaurant with friends at the time of the robbery.', explanation: 'From Latin: "alibi" = "elsewhere". Collocations: "have/provide/establish an alibi", "solid/watertight alibi", "check/verify an alibi", "an alibi for the night". "Watertight alibi" = one that cannot be challenged.' },
      { word: 'culprit', wordClass: 'noun', level: 'B2', meaning: 'A person who is responsible for committing a crime or causing a problem.', context: 'Identifying criminals and causes of problems.', example: 'Police have not yet identified the culprit behind the series of break-ins.', explanation: 'Collocations: "identify/catch/find the culprit", "the main/likely/real culprit". Also figurative: "Sugar is the main culprit behind tooth decay" (= the main cause). "Culpable" (adjective) = deserving blame: "culpable negligence".' },
      { word: 'hostage', wordClass: 'noun', level: 'B2', meaning: 'A person seized or held as security for the fulfilment of a demand.', context: 'Kidnapping and crisis situations.', example: 'The bank robbers took three employees hostage during the failed robbery.', explanation: 'Collocations: "take/hold/release hostages", "hostage situation/crisis/negotiator", "held hostage". "Hostage negotiator" = a trained specialist who communicates with hostage-takers. "Ransom" = money demanded for releasing a hostage.' },
      { word: 'smuggle', wordClass: 'verb', level: 'B2', verbForms: { v1: 'smuggle', v2: 'smuggled', v3: 'smuggled' }, meaning: 'To move goods or people illegally into or out of a country.', context: 'Border crime and illegal trade.', example: 'Customs officers seized drugs that were being smuggled into the country in shipping containers.', explanation: 'The person is a "smuggler" and the activity is "smuggling". Collocations: "smuggle drugs/weapons/goods/people", "smuggling ring/operation/route". "People smuggling" = illegally moving people across borders (different from "human trafficking" which involves exploitation).' },
      { word: 'counterfeit', wordClass: 'verb', level: 'B2', verbForms: { v1: 'counterfeit', v2: 'counterfeited', v3: 'counterfeited' }, meaning: 'To make a fake copy of something valuable with intent to deceive.', context: 'Fraud and forgery.', example: 'The gang counterfeited £20 notes that were almost impossible to tell from real ones.', explanation: 'Also an adjective and noun. Collocations: "counterfeit money/goods/products/documents", "counterfeiter" (the person). "Forge" is similar: "forged signature/document/passport". "Fake" is the informal equivalent. Counterfeiting is a serious crime — UK penalty up to 10 years in prison.' },
      { word: 'prosecute', wordClass: 'verb', level: 'B2', verbForms: { v1: 'prosecute', v2: 'prosecuted', v3: 'prosecuted' }, meaning: 'To bring legal proceedings against someone in court for a criminal offence.', context: 'Criminal justice process and legal action.', example: 'The company was prosecuted for illegally dumping toxic waste in the river.', explanation: 'The noun is "prosecution" and the person is the "prosecutor". Collocations: "prosecute someone for", "face prosecution", "Crown Prosecution Service (CPS)" (UK body that decides whether to prosecute). Opposite role: "defence" — the side representing the accused.' },
      { word: 'apprehend', wordClass: 'verb', level: 'C1', verbForms: { v1: 'apprehend', v2: 'apprehended', v3: 'apprehended' }, meaning: 'To arrest or catch a criminal suspect.', context: 'Police operations and suspect capture.', example: 'Police apprehended the suspect after a 30-minute car chase through the city centre.', explanation: 'More formal than "arrest" or "catch". Collocations: "apprehend a suspect/fugitive", "apprehension" (noun). "Apprehend" also means "to understand" (formal): "I don\'t fully apprehend the situation." "Apprehensive" = anxious — different meaning from the verb.' },
      { word: 'incriminate', wordClass: 'verb', level: 'C1', verbForms: { v1: 'incriminate', v2: 'incriminated', v3: 'incriminated' }, meaning: 'To make someone appear guilty of a crime; to provide evidence of wrongdoing.', context: 'Evidence and self-defence in court.', example: 'The CCTV footage incriminated him — it clearly showed him entering the building at midnight.', explanation: 'Collocations: "incriminating evidence/documents/footage", "self-incrimination" (= admitting your own guilt). Legal right: "You have the right to remain silent" — to avoid self-incrimination. "The Fifth Amendment" (US) protects against self-incrimination.' },
      { word: 'premeditated', wordClass: 'adjective', level: 'C1', meaning: 'Planned in advance; thought about and intended before being carried out.', context: 'Classifying the severity of criminal acts.', example: 'The prosecution argued that the killing was premeditated — not an impulsive act of violence.', explanation: 'Collocations: "premeditated murder/attack/crime". "Premeditation" (noun). In law: "premeditated murder" (planned) carries a heavier sentence than "manslaughter" (unplanned killing). "With malice aforethought" (legal) = premeditated intent to cause harm.' },
      { word: 'notorious', wordClass: 'adjective', level: 'B2', meaning: 'Famous for something bad; widely known for negative reasons.', context: 'Describing well-known criminals and dangerous places.', example: 'The neighbourhood is notorious for car crime and antisocial behaviour.', explanation: 'Collocations: "notorious criminal/gang/area", "notorious for". "Notoriety" (noun) = fame for something bad. Different from "famous" (positive or neutral) — "notorious" is always negative. "Infamous" is similar but slightly more formal.' },
      { word: 'stringent', wordClass: 'adjective', level: 'B2', meaning: 'Strict, precise, and demanding in terms of rules and requirements.', context: 'Security measures and regulatory controls.', example: 'Airports have implemented stringent security measures since the terrorist attacks.', explanation: 'Collocations: "stringent rules/regulations/measures/requirements/standards", "stringent security/checks". More emphatic than "strict" — implies no flexibility. "Stringently enforced" = applied without exception.' },
      { word: 'illicit', wordClass: 'adjective', level: 'B2', meaning: 'Forbidden by law, rules, or custom; illegal or disapproved of.', context: 'Illegal activities and prohibited substances.', example: 'The police operation targeted the illicit trade in counterfeit luxury goods.', explanation: 'Collocations: "illicit drugs/trade/activity/affair/gains". Don\'t confuse with "elicit" (verb = to draw out a response: "elicit information"). "Illicit" is always about something forbidden. "Illicit affair" = a secret romantic relationship, especially one involving infidelity.' },
      { word: 'covertly', wordClass: 'adverb', level: 'C1', meaning: 'In a secret or hidden way; without being openly acknowledged.', context: 'Undercover operations and surveillance.', example: 'The police covertly monitored the suspect\'s phone calls for three months.', explanation: 'The adjective is "covert": "covert operation/surveillance/agent". Opposite: "overtly" / "overt" (= openly, not hidden). Collocations: "covertly record/monitor/operate", "covert investigation". "Undercover" is similar: "an undercover police officer".' },
      { word: 'deterrent', wordClass: 'noun', level: 'B2', meaning: 'Something that discourages or prevents someone from doing something.', context: 'Crime prevention and punishment philosophy.', example: 'CCTV cameras act as a deterrent — criminals are less likely to act when they know they are being filmed.', explanation: 'The verb is "deter": "The heavy fine should deter others from littering." Collocations: "act as a deterrent", "effective deterrent", "nuclear deterrent" (= weapons that prevent attack by threatening retaliation). "Deterrence" (noun) = the philosophy that punishment prevents crime.' },
      { word: 'vulnerable', wordClass: 'adjective', level: 'B2', meaning: 'At risk of harm, attack, or exploitation; lacking protection.', context: 'Victim protection and risk assessment.', example: 'Elderly people living alone are particularly vulnerable to phone scams and doorstep fraud.', explanation: 'Collocations: "vulnerable people/groups/individuals/communities", "vulnerable to attack/exploitation/fraud". "Vulnerability" (noun). In safeguarding: "vulnerable adult/child" = someone who needs extra protection. The police have a duty to protect vulnerable members of the community.' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 2. SOCIAL ISSUES — Expansion (need 22+ more)
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'social-issues',
    name: 'Social Issues & Society',
    description: 'Vocabulary for social problems, inequality, activism, and community topics.',
    icon: '🌍',
    entries: [
      { word: 'stereotype', wordClass: 'noun', level: 'B2', meaning: 'An oversimplified, fixed idea about a particular group of people.', context: 'Prejudice and social assumptions.', example: 'The media often reinforces harmful stereotypes about ethnic minorities.', explanation: 'Also a verb: "Don\'t stereotype people based on their appearance." Collocations: "gender/racial/cultural stereotype", "reinforce/challenge/break stereotypes", "stereotypical" (adjective). "Stereotyping" is considered harmful because it ignores individual differences.' },
      { word: 'stigma', wordClass: 'noun', level: 'B2', meaning: 'A mark of disgrace or shame associated with a particular quality, circumstance, or person.', context: 'Mental health awareness and social acceptance.', example: 'There is still a significant stigma around mental health issues that prevents people from seeking help.', explanation: 'Collocations: "social stigma", "stigma attached to/around/of", "reduce/tackle/overcome stigma", "stigmatise" (verb = to treat with stigma). "Destigmatise" = to remove the shame associated with something. Mental health stigma is one of the most discussed social issues today.' },
      { word: 'marginalised', wordClass: 'adjective', level: 'B2', meaning: 'Treated as insignificant or pushed to the edge of society; excluded from mainstream opportunities.', context: 'Social exclusion and disadvantaged communities.', example: 'The charity works to improve opportunities for marginalised communities in inner cities.', explanation: 'The verb is "marginalise" and the noun is "marginalisation". Collocations: "marginalised communities/groups/voices/populations". "Marginalised" implies systemic exclusion — not just being poor, but being pushed out of power, services, and opportunities. Related: "disenfranchised" = deprived of rights.' },
      { word: 'advocacy', wordClass: 'noun', level: 'B2', meaning: 'Public support, recommendation, or argument for a cause, policy, or group.', context: 'Social campaigns and political lobbying.', example: 'Her advocacy for children\'s rights led to significant changes in government policy.', explanation: 'The person is an "advocate" (also a verb: "advocate for change"). Collocations: "advocacy group/campaign/work", "advocate for/against". "Self-advocacy" = speaking up for your own rights and needs. "Patient advocate" = someone who helps patients navigate the healthcare system.' },
      { word: 'disparity', wordClass: 'noun', level: 'C1', meaning: 'A great difference or inequality between things.', context: 'Income gaps and unequal access to services.', example: 'There is a growing disparity in income between the richest and poorest members of society.', explanation: 'Collocations: "income/wealth/health/gender/racial disparity", "growing/widening disparity". Similar to "gap" or "inequality" but more formal. "Health disparities" = differences in health outcomes between groups. "The gender pay gap" = a specific type of income disparity.' },
      { word: 'empower', wordClass: 'verb', level: 'B2', verbForms: { v1: 'empower', v2: 'empowered', v3: 'empowered' }, meaning: 'To give someone the authority, confidence, or means to do something; to make stronger.', context: 'Social development and capacity building.', example: 'The programme empowers young women through education, mentoring, and career training.', explanation: 'The noun is "empowerment". Collocations: "empower people/communities/women/youth", "empowerment programme", "women\'s empowerment". Key concept in social development — giving people the tools and confidence to improve their own lives rather than creating dependency.' },
      { word: 'segregate', wordClass: 'verb', level: 'B2', verbForms: { v1: 'segregate', v2: 'segregated', v3: 'segregated' }, meaning: 'To separate or divide people based on race, religion, gender, or other characteristics.', context: 'Historical discrimination and social division.', example: 'Until the 1960s, many American states legally segregated Black and white people in schools and public spaces.', explanation: 'The noun is "segregation". Collocations: "racial/gender segregation", "segregated schools/communities", "desegregation" (= ending segregation). Historical: "apartheid" (South Africa) and "Jim Crow laws" (US) were systems of legal segregation.' },
      { word: 'rehabilitate', wordClass: 'verb', level: 'B2', verbForms: { v1: 'rehabilitate', v2: 'rehabilitated', v3: 'rehabilitated' }, meaning: 'To help someone return to a normal, productive life after prison, addiction, or illness.', context: 'Criminal justice reform and social support.', example: 'The programme rehabilitates former prisoners by providing housing, job training, and counselling.', explanation: 'The noun is "rehabilitation" (often "rehab"). Collocations: "rehabilitate offenders/addicts", "rehabilitation programme/centre". The debate: "punishment vs rehabilitation" — should prison punish or prepare people for re-entry into society? Recidivism rates are lower with rehabilitation.' },
      { word: 'homelessness', wordClass: 'noun', level: 'B1', meaning: 'The state of having no home; living on the streets or in temporary shelters.', context: 'Housing crisis and social welfare.', example: 'Homelessness in the UK has risen by 40% in the last decade.', explanation: 'Collocations: "tackle/reduce/address homelessness", "homelessness crisis", "rough sleeping" (= sleeping on the streets), "homeless shelter/hostel". Causes: poverty, relationship breakdown, mental health issues, addiction, lack of affordable housing. "Hidden homelessness" = people staying temporarily with friends/family.' },
      { word: 'xenophobia', wordClass: 'noun', level: 'C1', meaning: 'Fear, hatred, or prejudice against people from other countries or cultures.', context: 'Immigration debates and hate crime.', example: 'Rising xenophobia has led to an increase in hate crimes against foreign-born residents.', explanation: 'From Greek: "xenos" (foreigner) + "phobos" (fear). The adjective is "xenophobic": "xenophobic attitudes/rhetoric". Collocations: "rise in xenophobia", "xenophobic violence/attacks". Related: "racism" (prejudice based on race), "Islamophobia" (prejudice against Muslims), "antisemitism" (prejudice against Jewish people).' },
      { word: 'affluent', wordClass: 'adjective', level: 'B2', meaning: 'Having a lot of money; wealthy.', context: 'Social class and economic inequality.', example: 'Children from affluent families tend to have better educational outcomes than those from poorer backgrounds.', explanation: 'The noun is "affluence". More formal than "rich". Collocations: "affluent area/neighbourhood/society/family". "The affluent" = wealthy people. Used in social analysis to discuss inequality. Opposite: "deprived" (= lacking resources and opportunities).' },
      { word: 'grassroots', wordClass: 'adjective', level: 'B2', meaning: 'Involving or relating to ordinary people in society rather than political leaders or organisations.', context: 'Community activism and bottom-up change.', example: 'The environmental campaign started as a grassroots movement led by local residents.', explanation: 'Also a noun: "at the grassroots" or "at grassroots level". Collocations: "grassroots movement/campaign/organisation/support/level". Opposite: "top-down" (= imposed by leaders). "Grassroots" implies authentic, community-driven action rather than institutional or corporate effort.' },
      { word: 'deprived', wordClass: 'adjective', level: 'B2', meaning: 'Lacking the basic necessities or advantages that most people enjoy; disadvantaged.', context: 'Poverty and social disadvantage.', example: 'Children growing up in deprived areas are more likely to experience poor health and lower educational achievement.', explanation: 'Collocations: "deprived area/community/neighbourhood/background", "socially/economically deprived". "Deprivation" (noun): "poverty and deprivation", "sleep deprivation". The UK government publishes an "Index of Multiple Deprivation" ranking areas by poverty, health, education, and crime.' },
      { word: 'inclusive', wordClass: 'adjective', level: 'B2', meaning: 'Open to everyone regardless of background, ability, or identity; welcoming diversity.', context: 'Diversity policies and accessible design.', example: 'The company has adopted inclusive hiring practices to attract candidates from all backgrounds.', explanation: 'The noun is "inclusion" and the opposite is "exclusive/exclusion". Collocations: "inclusive environment/society/education/language/design", "diversity and inclusion (D&I)". "Inclusive language" avoids terms that exclude or marginalise people.' },
      { word: 'disproportionately', wordClass: 'adverb', level: 'B2', meaning: 'To an extent that is too large or too small in comparison with something else.', context: 'Analysing inequality and unfair impacts.', example: 'Ethnic minorities are disproportionately affected by poverty and unemployment.', explanation: 'The adjective is "disproportionate". Collocations: "disproportionately affected/represented/impacted", "disproportionate number/amount/force". Key word in social justice — identifies where impacts are unfairly distributed across groups.' },
      { word: 'systematically', wordClass: 'adverb', level: 'B2', meaning: 'In a deliberate, methodical, and organised way; built into a system.', context: 'Describing patterns of discrimination and organised efforts.', example: 'The report found that certain groups were systematically excluded from employment opportunities.', explanation: 'The adjective is "systematic" and "systemic": "systemic racism/inequality" (= built into the structures of society). Collocations: "systematically discriminated/excluded/denied". "Systemic" is stronger than "systematic" — it implies the problem is embedded in the system itself, not just done in an organised way.' },
      { word: 'equitably', wordClass: 'adverb', level: 'C1', meaning: 'In a fair and just way that gives everyone what they need.', context: 'Resource distribution and fair treatment.', example: 'Resources should be distributed equitably so that the most disadvantaged communities receive the most support.', explanation: 'The adjective is "equitable" and the noun is "equity". Different from "equally" (everyone gets the same) — "equitably" means everyone gets what they NEED, which may be different amounts. "Equity vs equality": equality gives everyone the same; equity gives everyone what they need to succeed.' },
      { word: 'pervasive', wordClass: 'adjective', level: 'C1', meaning: 'Spreading widely throughout an area or group of people; present everywhere.', context: 'Describing widespread social problems.', example: 'Racism is a pervasive problem that affects every aspect of society.', explanation: 'Collocations: "pervasive influence/problem/culture/inequality", "pervasively" (adverb). Stronger than "widespread" — implies something that has deeply penetrated every part of a system. "Pervade" (verb): "A sense of fear pervaded the community."' },
      { word: 'egalitarian', wordClass: 'adjective', level: 'C1', meaning: 'Believing in or based on the principle that all people are equal and deserve equal rights.', context: 'Political philosophy and social ideals.', example: 'Scandinavian countries are often held up as examples of egalitarian societies with strong social welfare.', explanation: 'The noun is "egalitarianism". Collocations: "egalitarian society/values/principles/approach". From French "égalitaire" (equal). "Egalitarian" describes an ideal where everyone has equal opportunities regardless of gender, race, or wealth. Opposite: "hierarchical" (= structured by rank).' },
      { word: 'philanthropy', wordClass: 'noun', level: 'C1', meaning: 'The desire to promote the welfare of others, expressed by generous donations of money to good causes.', context: 'Charitable giving and social responsibility.', example: 'Bill Gates has devoted billions of dollars to philanthropy through the Gates Foundation.', explanation: 'The person is a "philanthropist" and the adjective is "philanthropic". From Greek: "philos" (loving) + "anthropos" (human). Collocations: "philanthropic efforts/donations/foundation", "corporate philanthropy". Different from "charity" (giving to those in need) — "philanthropy" implies strategic, large-scale giving to address root causes.' },
      { word: 'accountability', wordClass: 'noun', level: 'B2', meaning: 'The obligation to explain and take responsibility for one\'s actions and decisions.', context: 'Government transparency and institutional reform.', example: 'There needs to be greater accountability in how public money is spent by local councils.', explanation: 'The adjective is "accountable": "hold someone accountable". Collocations: "accountability for/in/of", "public/corporate accountability", "lack of accountability", "transparency and accountability". Key concept in governance — institutions must answer to the people they serve.' },
      { word: 'bureaucracy', wordClass: 'noun', level: 'B2', meaning: 'A system of government or management with complex rules and procedures; excessive red tape.', context: 'Government efficiency and administrative barriers.', example: 'The application process involves so much bureaucracy that it takes months to get approval.', explanation: 'The adjective is "bureaucratic". Collocations: "government/state bureaucracy", "bureaucratic red tape/process/delays". Usually negative — implies excessive paperwork and slow processes. "Red tape" = excessive bureaucracy. "Cut through the red tape" = bypass unnecessary procedures.' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 3. ANIMALS & NATURE — Expansion (need 21+ more)
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'animals-nature',
    name: 'Animals & Nature',
    description: 'Vocabulary for wildlife, pets, ecosystems, and the natural world.',
    icon: '🦁',
    entries: [
      { word: 'predator', wordClass: 'noun', level: 'B2', meaning: 'An animal that hunts and kills other animals for food.', context: 'Food chains and wildlife behaviour.', example: 'Lions are apex predators — they sit at the top of the food chain with no natural enemies.', explanation: 'Collocations: "apex/top predator", "natural predator", "predator-prey relationship". "Predatory" (adjective): "predatory behaviour" (also figurative: "predatory lending" = exploitative). The prey is the animal being hunted. "Apex predator" = no other animal hunts it.' },
      { word: 'habitat', wordClass: 'noun', level: 'B1', meaning: 'The natural home or environment where an animal or plant lives and grows.', context: 'Conservation and ecosystem protection.', example: 'Deforestation is destroying the natural habitat of orangutans in Borneo and Sumatra.', explanation: 'Collocations: "natural/wildlife habitat", "habitat loss/destruction/fragmentation", "protect/preserve habitats". "Habitat fragmentation" = when habitats are split into smaller, isolated pieces by roads, farms, or buildings — one of the biggest threats to biodiversity.' },
      { word: 'camouflage', wordClass: 'noun', level: 'B2', meaning: 'Natural colouring or patterns that help an animal blend in with its surroundings to avoid detection.', context: 'Animal adaptation and survival strategies.', example: 'The chameleon uses camouflage to change colour and blend in with its environment.', explanation: 'Also a verb: "The moth camouflages itself against the bark." Collocations: "natural camouflage", "camouflage pattern/clothing" (military), "camouflaged" (adjective). Types: colour-matching (leaf insects), countershading (sharks), mimicry (harmless animals looking dangerous).' },
      { word: 'parasite', wordClass: 'noun', level: 'B2', meaning: 'An organism that lives on or inside another organism and benefits at the host\'s expense.', context: 'Biology and animal health.', example: 'Ticks are parasites that attach to the skin of animals and feed on their blood.', explanation: 'The adjective is "parasitic". Collocations: "parasitic infection/worm/disease", "host and parasite". Examples: ticks, tapeworms, fleas, malaria parasites. "Symbiosis" (opposite) = a relationship where both organisms benefit. Also figurative (negative): "He\'s a parasite who lives off other people."' },
      { word: 'nocturnal', wordClass: 'adjective', level: 'B2', meaning: 'Active during the night rather than the day.', context: 'Animal behaviour patterns and ecology.', example: 'Owls are nocturnal birds that hunt for mice and other small animals after dark.', explanation: 'Opposite: "diurnal" (= active during the day). Collocations: "nocturnal animal/bird/creature", "nocturnal habits/activity". Nocturnal animals have adaptations: large eyes (owls), echolocation (bats), enhanced hearing (foxes). "Crepuscular" = active at dawn and dusk (rabbits, deer).' },
      { word: 'hibernate', wordClass: 'verb', level: 'B2', verbForms: { v1: 'hibernate', v2: 'hibernated', v3: 'hibernated' }, meaning: 'To spend the winter in a deep sleep-like state to conserve energy.', context: 'Seasonal animal behaviour.', example: 'Bears hibernate through the winter months, living off stored body fat.', explanation: 'The noun is "hibernation". Collocations: "hibernate during winter", "go into hibernation", "hibernating animals". Animals that hibernate: bears, hedgehogs, bats, dormice, tortoises. Body temperature and heart rate drop dramatically. "Aestivation" = the summer equivalent (some animals sleep through hot, dry periods).' },
      { word: 'forage', wordClass: 'verb', level: 'B2', verbForms: { v1: 'forage', v2: 'foraged', v3: 'foraged' }, meaning: 'To search widely for food, typically in the wild.', context: 'Animal feeding behaviour and wild food gathering.', example: 'Squirrels forage for nuts and seeds in autumn, burying them to eat during winter.', explanation: 'Also a noun: "a foraging expedition". Collocations: "forage for food/berries/nuts", "foraging behaviour/trip". "Foraging" is also a human activity — gathering wild food (mushrooms, berries, herbs) is a growing trend in food culture.' },
      { word: 'breed', wordClass: 'verb', level: 'B1', verbForms: { v1: 'breed', v2: 'bred', v3: 'bred' }, meaning: 'To produce offspring; to keep animals for the purpose of producing young.', context: 'Animal reproduction and conservation.', example: 'Pandas are notoriously difficult to breed in captivity — many zoos have tried and failed.', explanation: 'Also a noun: "a breed of dog" (= a type: Labrador, Poodle, Bulldog). Collocations: "breed in captivity/the wild", "breeding programme/season/pair", "rare breed", "pedigree" (= a purebred animal with documented ancestry). "Breeding ground" = a place where animals reproduce, or figurative: "a breeding ground for crime".' },
      { word: 'domesticated', wordClass: 'adjective', level: 'B2', meaning: 'Tamed and kept by humans as a pet or for farming purposes.', context: 'Animal-human relationship history.', example: 'Dogs were first domesticated from wolves around 15,000 years ago.', explanation: 'The verb is "domesticate". Collocations: "domesticated animal/cat/dog", "domestication of animals". Domesticated vs "tame": domesticated = genetically adapted over generations for human use; tame = an individual wild animal trained to be calm around humans. Wild, tame, domesticated are different states.' },
      { word: 'venomous', wordClass: 'adjective', level: 'B2', meaning: 'Capable of injecting venom through a bite or sting.', context: 'Dangerous animals and safety warnings.', example: 'Australia is home to some of the world\'s most venomous snakes and spiders.', explanation: 'Different from "poisonous": "venomous" = injects venom actively (snakes, spiders, scorpions); "poisonous" = harmful if eaten or touched (certain frogs, mushrooms, plants). "If it bites you and you die, it\'s venomous. If you bite it and you die, it\'s poisonous." "Venom" = the toxic substance.' },
      { word: 'biodiversity', wordClass: 'noun', level: 'B2', meaning: 'The variety of plant and animal life in a particular habitat or on Earth as a whole.', context: 'Conservation and ecosystem health.', example: 'Tropical rainforests contain the greatest biodiversity on Earth — millions of species in one ecosystem.', explanation: 'Collocations: "biodiversity loss/crisis/hotspot/conservation", "rich/high biodiversity". A "biodiversity hotspot" = a region with exceptionally high species diversity under threat. The current "biodiversity crisis" refers to the rapid extinction of species due to human activity.' },
      { word: 'migratory', wordClass: 'adjective', level: 'B2', meaning: 'Relating to or characterised by seasonal movement from one region to another.', context: 'Bird watching and animal movement patterns.', example: 'Migratory birds like swallows travel thousands of miles between Europe and Africa each year.', explanation: 'The noun is "migration" and the verb is "migrate". Collocations: "migratory birds/species/patterns/route", "bird migration". Famous migrations: wildebeest in Africa (1.5 million animals), monarch butterflies (4,000 miles), Arctic terns (71,000 km round trip — the longest migration of any animal).' },
      { word: 'instinctive', wordClass: 'adjective', level: 'B2', meaning: 'Arising naturally and automatically without being learned; innate behaviour.', context: 'Animal behaviour and natural responses.', example: 'The bird\'s instinctive fear of the predator caused it to freeze and remain silent.', explanation: 'Collocations: "instinctive behaviour/reaction/response/fear", "instinctively" (adverb). "Instinct" (noun): "survival/maternal/hunting instinct". Instinctive behaviour doesn\'t need to be learned — it\'s hardwired. "Learned behaviour" is the opposite — taught by parents or experience.' },
      { word: 'territorial', wordClass: 'adjective', level: 'B2', meaning: 'Relating to an animal\'s tendency to claim and defend a particular area.', context: 'Animal behaviour and dominance patterns.', example: 'Male robins are highly territorial and will aggressively defend their patch from rivals.', explanation: 'Collocations: "territorial behaviour/dispute/marking", "territorial animal/bird". "Territory" (noun). Animals mark territory with: scent (dogs, cats), song (birds), physical displays (gorillas). Also figurative: "He\'s very territorial about his desk" = possessive about his space.' },
      { word: 'extinct', wordClass: 'adjective', level: 'B1', meaning: 'No longer existing; having died out completely as a species.', context: 'Conservation and species loss.', example: 'The dodo became extinct in the 17th century after humans and invasive species destroyed its habitat.', explanation: 'The noun is "extinction". Collocations: "become/go extinct", "mass extinction", "extinction event", "functionally extinct" (= too few individuals left to reproduce). "Endangered" = at risk of becoming extinct. "Critically endangered" = very high risk of extinction. "De-extinction" = using technology to bring back extinct species.' },
      { word: 'aquatic', wordClass: 'adjective', level: 'B2', meaning: 'Relating to or living in water.', context: 'Marine and freshwater ecosystems.', example: 'Dolphins are aquatic mammals that breathe air but spend their entire lives in the ocean.', explanation: 'Collocations: "aquatic animal/plant/ecosystem/habitat/life". Types: "marine" (saltwater/ocean), "freshwater" (rivers, lakes), "aquatic" (both). "Aquarium" = a glass tank for keeping fish, or a public facility displaying aquatic life. "Aquaculture" = farming fish and other aquatic organisms.' },
      { word: 'flourish', wordClass: 'verb', level: 'B2', verbForms: { v1: 'flourish', v2: 'flourished', v3: 'flourished' }, meaning: 'To grow and develop in a healthy or vigorous way; to thrive.', context: 'Ecosystem health and species success.', example: 'Wildlife flourishes in the protected national park where hunting is strictly forbidden.', explanation: 'Collocations: "flourish in/under", "flourishing ecosystem/community/business". Stronger than "grow" — implies thriving with vigour and vitality. "Flourishing" (adjective): "a flourishing garden/economy". Opposite: "wither" or "decline".' },
      { word: 'ecosytem', wordClass: 'noun', level: 'B2', meaning: 'A community of living organisms interacting with each other and their environment as a system.', context: 'Ecology and environmental science.', example: 'Coral reefs are among the most diverse ecosystems on the planet, supporting thousands of species.', explanation: 'Collocations: "marine/forest/freshwater/fragile ecosystem", "ecosystem services" (= benefits humans get from nature: clean air, water, pollination). "Ecosystem collapse" = when an ecosystem stops functioning. Also figurative: "the startup ecosystem" = the network of startups, investors, and support services.' },
      { word: 'symbiotic', wordClass: 'adjective', level: 'C1', meaning: 'Relating to a relationship between two organisms where at least one benefits.', context: 'Biological partnerships and mutual dependence.', example: 'Clownfish and sea anemones have a symbiotic relationship — the fish gets protection while the anemone gets food scraps.', explanation: 'The noun is "symbiosis". Types: "mutualism" (both benefit — clownfish/anemone), "commensalism" (one benefits, other unaffected — barnacles on whales), "parasitism" (one benefits, other harmed — ticks on dogs). Also figurative: "a symbiotic business relationship".' },
      { word: 'resilient', wordClass: 'adjective', level: 'B2', meaning: 'Able to recover quickly from difficult conditions or damage.', context: 'Species adaptation and ecosystem recovery.', example: 'Cockroaches are remarkably resilient creatures that can survive extreme conditions.', explanation: 'The noun is "resilience". Collocations: "resilient species/ecosystem/community", "remarkably/incredibly resilient". Some ecosystems are more resilient than others — diverse ecosystems recover faster because different species can fill gaps. "Ecological resilience" = an ecosystem\'s ability to absorb disturbance.' },
      { word: 'abundantly', wordClass: 'adverb', level: 'B2', meaning: 'In large quantities; plentifully.', context: 'Describing plentiful natural resources and wildlife.', example: 'Wildflowers grow abundantly in the meadows during spring and early summer.', explanation: 'The adjective is "abundant": "abundant wildlife/resources/rainfall". The noun is "abundance": "an abundance of wildlife". Collocations: "grow/found abundantly", "abundantly clear" (figurative = very obvious). Opposite: "scarcely" / "scarce" (= in short supply).' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 4. COMMUNICATION — Expansion (need 24+ more)
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'communication',
    name: 'Communication & Language',
    description: 'Vocabulary for speaking, writing, body language, media, and digital communication.',
    icon: '💬',
    entries: [
      { word: 'dialect', wordClass: 'noun', level: 'B2', meaning: 'A regional form of a language with distinct vocabulary, grammar, and pronunciation.', context: 'Language variation and regional identity.', example: 'Scottish English is a dialect with unique words like "wee" (small) and "aye" (yes).', explanation: 'Different from "accent" (pronunciation only) — a "dialect" includes different vocabulary and grammar too. Collocations: "regional/local dialect", "dialect words/features". "Slang" = very informal words used by specific groups, not a whole dialect. All dialects are equally valid linguistically.' },
      { word: 'jargon', wordClass: 'noun', level: 'B2', meaning: 'Specialised technical language used by a particular profession or group that is hard for outsiders to understand.', context: 'Professional communication and plain language.', example: 'The contract was full of legal jargon that was impossible for non-lawyers to understand.', explanation: 'Usually negative — implies unnecessary complexity. Collocations: "technical/legal/medical/business jargon", "jargon-free" (= written in plain language). "Plain English" campaigns encourage clear writing without jargon. "Gobbledygook" (informal) = confusing, meaningless jargon.' },
      { word: 'rhetoric', wordClass: 'noun', level: 'B2', meaning: 'The art of effective or persuasive speaking or writing; language designed to persuade rather than inform.', context: 'Political speech and persuasion techniques.', example: 'The politician\'s speech was full of powerful rhetoric but offered few concrete solutions.', explanation: 'The adjective is "rhetorical": "a rhetorical question" (= a question asked for effect, not expecting an answer: "Who knows?"). Collocations: "political/empty/inflammatory rhetoric", "rhetorical device/skill/question". Can be admiring (skilful persuasion) or critical (empty words without substance).' },
      { word: 'nuance', wordClass: 'noun', level: 'B2', meaning: 'A subtle difference in meaning, expression, sound, or opinion.', context: 'Careful communication and critical thinking.', example: 'The translation missed many of the nuances of the original poem.', explanation: 'The adjective is "nuanced": "a nuanced argument/understanding". Collocations: "subtle nuance", "capture/miss the nuances", "nuanced view/debate". Very important in academic and cross-cultural communication — missing nuances can lead to misunderstanding. "A nuanced position" = one that considers complexity, not just black and white.' },
      { word: 'anecdote', wordClass: 'noun', level: 'B2', meaning: 'A short, interesting personal story, often used to illustrate a point.', context: 'Storytelling and public speaking.', example: 'He began his speech with a funny anecdote about his first day at work.', explanation: 'The adjective is "anecdotal": "anecdotal evidence" (= based on personal stories, not scientific data). Collocations: "tell/share an anecdote", "amusing/personal/relevant anecdote". Good speakers use anecdotes to make their message memorable and relatable.' },
      { word: 'paraphrase', wordClass: 'verb', level: 'B2', verbForms: { v1: 'paraphrase', v2: 'paraphrased', v3: 'paraphrased' }, meaning: 'To express the meaning of something using different words, especially to achieve clearer understanding.', context: 'Academic writing and communication skills.', example: 'Let me paraphrase what you just said to make sure I understood correctly.', explanation: 'Also a noun: "to put it in a paraphrase". Collocations: "paraphrase a quote/text/passage", "to paraphrase" (= to put it another way). Essential academic skill — you must paraphrase sources rather than copying them directly (plagiarism). Different from "summarise" (= shorten) — "paraphrase" is restating in your own words at similar length.' },
      { word: 'articulate', wordClass: 'verb', level: 'B2', verbForms: { v1: 'articulate', v2: 'articulated', v3: 'articulated' }, meaning: 'To express thoughts, ideas, or feelings clearly and effectively in words.', context: 'Clear communication and expression.', example: 'She articulated her concerns about the project in a clear, well-structured email.', explanation: 'Also an adjective: "an articulate speaker" (= someone who expresses ideas clearly). Collocations: "articulate your views/concerns/ideas", "clearly articulated", "articulate person/speaker". Pronunciation differs: verb = ar-TIK-yoo-late; adjective = ar-TIK-yoo-lit.' },
      { word: 'elaborate', wordClass: 'verb', level: 'B2', verbForms: { v1: 'elaborate', v2: 'elaborated', v3: 'elaborated' }, meaning: 'To add more detail and information to something already said.', context: 'Expanding on ideas in conversation and writing.', example: 'Could you elaborate on your proposal? I\'d like to understand the details better.', explanation: 'Collocations: "elaborate on a point/idea/plan", "please elaborate", "elaborate further". Also an adjective: "an elaborate plan/design/scheme" (= complex, detailed, and carefully planned). "Elaboration" (noun). "Could you elaborate?" is a polite way to ask someone to explain more.' },
      { word: 'convey', wordClass: 'verb', level: 'B2', verbForms: { v1: 'convey', v2: 'conveyed', v3: 'conveyed' }, meaning: 'To communicate or express a message, meaning, or feeling.', context: 'Transmitting meaning and emotion.', example: 'Her facial expression conveyed more than her words ever could.', explanation: 'Collocations: "convey a message/meaning/feeling/idea/impression", "convey information". More formal than "communicate" or "express". "Conveyor belt" = a moving belt for transporting objects (different meaning but same root — carrying something from one place to another).' },
      { word: 'interrupt', wordClass: 'verb', level: 'B1', verbForms: { v1: 'interrupt', v2: 'interrupted', v3: 'interrupted' }, meaning: 'To stop someone while they are speaking by saying or doing something.', context: 'Conversational manners and turn-taking.', example: 'Please don\'t interrupt me — let me finish what I was saying.', explanation: 'The noun is "interruption". Collocations: "interrupt someone/a conversation/a meeting", "sorry to interrupt", "constant interruptions". Considered rude in most English-speaking cultures. In meetings: "Sorry to jump in, but..." is a polite way to interrupt.' },
      { word: 'misleading', wordClass: 'adjective', level: 'B2', meaning: 'Giving the wrong idea or impression; likely to make someone believe something untrue.', context: 'Media accuracy and advertising standards.', example: 'The advertisement was banned for making misleading claims about the product\'s effectiveness.', explanation: 'The verb is "mislead" (mislead → misled → misled). Collocations: "misleading information/advertising/headline/statement", "deliberately/potentially misleading". Different from "lying" (intentionally false) — "misleading" can be technically true but gives a false impression.' },
      { word: 'bilingual', wordClass: 'adjective', level: 'B1', meaning: 'Able to speak two languages fluently.', context: 'Language ability and multilingual societies.', example: 'Growing up in Brussels, she became bilingual in French and Dutch.', explanation: 'Collocations: "bilingual education/school/dictionary/person", "fully bilingual". "Monolingual" = one language. "Multilingual" = three or more languages. "Polyglot" = someone who speaks many languages. "Bilingualism" offers cognitive benefits — bilingual children often perform better on certain cognitive tasks.' },
      { word: 'coherent', wordClass: 'adjective', level: 'B2', meaning: 'Logically connected and easy to understand; making sense as a whole.', context: 'Clear writing and logical argumentation.', example: 'The essay was well-researched but lacked a coherent structure — the ideas jumped around.', explanation: 'The noun is "coherence". Opposite: "incoherent" (= not making sense, rambling). Collocations: "coherent argument/plan/strategy/narrative/policy", "logically coherent". In academic writing, coherence means ideas flow logically from one to the next. "Cohesion" (related) = how sentences connect together using linking words.' },
      { word: 'assertive', wordClass: 'adjective', level: 'B2', meaning: 'Confident and direct in claiming one\'s rights or expressing opinions without being aggressive.', context: 'Communication styles and confidence building.', example: 'She learned to be more assertive at work, clearly stating her opinions in meetings.', explanation: 'The noun is "assertiveness". Collocations: "assertive behaviour/communication/person", "assertiveness training". Communication styles: passive (avoids conflict) → assertive (confident and respectful) → aggressive (dominating and disrespectful). Assertive is the ideal — direct but not rude.' },
      { word: 'ambiguous', wordClass: 'adjective', level: 'B2', meaning: 'Having more than one possible meaning or interpretation; unclear.', context: 'Confusing messages and unclear instructions.', example: 'The instructions were ambiguous — "press any key" could mean literally any key or a specific one.', explanation: 'The noun is "ambiguity". Collocations: "ambiguous statement/message/wording/meaning", "deliberately ambiguous". Opposite: "unambiguous" (= completely clear). "Ambiguity" can be a problem in legal documents, instructions, and exam questions. In literature, ambiguity can be a deliberate artistic choice.' },
      { word: 'diplomatically', wordClass: 'adverb', level: 'B2', meaning: 'In a tactful and sensitive way that avoids causing offence.', context: 'Handling difficult conversations and giving feedback.', example: 'She diplomatically pointed out the errors in his work without making him feel embarrassed.', explanation: 'The adjective is "diplomatic": "a diplomatic response/answer/person". Collocations: "handle/respond diplomatically", "diplomatic language/solution". "Tact" (noun) = sensitivity in dealing with people: "She handled the situation with great tact." "Tactful" = "diplomatic".' },
      { word: 'succinctly', wordClass: 'adverb', level: 'B2', meaning: 'In a brief, clear, and concise way that expresses the essential points.', context: 'Efficient communication and clear writing.', example: 'She succinctly summarised the 50-page report in just three bullet points.', explanation: 'The adjective is "succinct": "a succinct summary/answer/response". Collocations: "put it succinctly", "succinctly stated/expressed". Implies clarity AND brevity — not just short, but effectively short. "Brevity is the soul of wit" (Shakespeare) = the best communication is concise.' },
      { word: 'emphatically', wordClass: 'adverb', level: 'B2', meaning: 'In a forceful and clear way that leaves no doubt about the speaker\'s meaning.', context: 'Strong statements and definitive communication.', example: 'She emphatically denied any involvement in the scandal.', explanation: 'The adjective is "emphatic": "an emphatic denial/victory/statement". Collocations: "emphatically state/deny/reject/agree", "emphatic about". "Emphasis" (noun): "put emphasis on" = stress the importance of. "Emphasise" (verb): "I want to emphasise that this is urgent."' },
      { word: 'verbatim', wordClass: 'adverb', level: 'C1', meaning: 'In exactly the same words as were originally used; word-for-word.', context: 'Quoting and accurate reporting.', example: 'She repeated his instructions verbatim to make sure she hadn\'t misunderstood anything.', explanation: 'Also an adjective: "a verbatim transcript/quote/record". Collocations: "repeat/quote verbatim", "verbatim record/transcript/account". From Latin "verbum" (word). "Verbatim" transcripts record every word spoken — used in courts, parliament, and journalism. Different from "paraphrase" (= restating in different words).' },
      { word: 'colloquial', wordClass: 'adjective', level: 'C1', meaning: 'Used in ordinary, informal, everyday conversation rather than formal speech or writing.', context: 'Register and formality levels in language.', example: '"Gonna" and "wanna" are colloquial contractions of "going to" and "want to".', explanation: 'The noun is "colloquialism": a colloquial word or expression. Collocations: "colloquial language/expression/speech/English". "Colloquial" is between "formal" and "slang" — it\'s normal spoken English that you wouldn\'t use in an essay. Examples: "loads of" (= lots of), "hang on" (= wait), "I reckon" (= I think).' },
      { word: 'infer', wordClass: 'verb', level: 'B2', verbForms: { v1: 'infer', v2: 'inferred', v3: 'inferred' }, meaning: 'To conclude or deduce something from evidence and reasoning rather than from explicit statements.', context: 'Reading comprehension and critical thinking.', example: 'From the tone of her email, I inferred that she was unhappy with the decision.', explanation: 'The noun is "inference". Don\'t confuse with "imply" (= to suggest indirectly): the SPEAKER implies; the LISTENER infers. "What are you implying?" vs "What can we infer from this?" IELTS reading often tests inference: "What can you infer from paragraph 3?"' },
      { word: 'figuratively', wordClass: 'adverb', level: 'B2', meaning: 'In a metaphorical rather than literal way; not meant to be taken at face value.', context: 'Understanding metaphor and non-literal language.', example: 'When I said "I\'m dying of hunger," I meant it figuratively, not literally!', explanation: 'Opposite: "literally" (= exactly as stated). The adjective is "figurative": "figurative language" (= metaphors, similes, idioms). Collocations: "figuratively speaking", "figurative meaning/sense/language". "Figurative language" is essential in English — idioms like "break the ice", "spill the beans", "kick the bucket" are figurative, not literal.' },
      { word: 'eloquent', wordClass: 'adjective', level: 'B2', meaning: 'Fluent, expressive, and persuasive in speaking or writing.', context: 'Describing powerful communication and public speaking.', example: 'Martin Luther King Jr. was one of the most eloquent speakers in American history.', explanation: 'The noun is "eloquence". Collocations: "eloquent speech/speaker/writer/argument/tribute", "eloquently expressed". Implies beauty and power of expression — not just clear, but moving and persuasive. "An eloquent silence" = a silence that communicates powerfully without words.' },
      { word: 'concisely', wordClass: 'adverb', level: 'B2', meaning: 'In a way that expresses much in few words; briefly but completely.', context: 'Academic writing and efficient communication.', example: 'The abstract concisely summarises the key findings of the 30-page research paper.', explanation: 'The adjective is "concise": "a concise summary/report/answer". Collocations: "state/express/write concisely", "concise and clear". "Concision" or "conciseness" (noun). IELTS writing tip: being concise (saying more with fewer words) scores higher than being wordy. "Be concise" = remove unnecessary words.' },
    ],
  },
]
