// # ═══════════════════════════════════════════════════════════════════════════
// # VOCABULARY REFERENCE DATA — Organised by field/area of life
// # ═══════════════════════════════════════════════════════════════════════════
// # All content is original and copyright-free.
// # Each field contains nouns, verbs (V1/V2/V3), adjectives, and adverbs
// # with meaning, context, example usage, and full explanation.

import type { VocabField } from './types'

export const VOCAB_FIELDS: VocabField[] = [

  // # ═══════════════════════════════════════════════════════════════════
  // # 1. DAILY LIFE & HOME
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'daily-life',
    name: 'Daily Life & Home',
    description: 'Essential vocabulary for everyday routines, household items, and domestic life.',
    icon: '🏠',
    entries: [
      { word: 'routine', wordClass: 'noun', level: 'A2', meaning: 'A regular series of actions done in a fixed order.', context: 'Describing daily habits and schedules.', example: 'My morning routine includes coffee, a shower, and checking emails.', explanation: 'A "routine" is a set pattern you follow regularly. It comes from the French word "route" (path). We say "daily routine", "morning routine", or "exercise routine". It can also be used as an adjective: "a routine check-up" means a standard, regular check-up.' },
      { word: 'chore', wordClass: 'noun', level: 'A2', meaning: 'A regular task around the house, often boring but necessary.', context: 'Talking about housework and responsibilities.', example: 'Doing the laundry is my least favourite chore.', explanation: '"Chore" specifically implies a task that is unpleasant or tedious. Common collocations: "household chores", "do chores", "share the chores". Don\'t confuse with "task" which is more neutral — a chore always has a slightly negative feeling.' },
      { word: 'appliance', wordClass: 'noun', level: 'B1', meaning: 'A machine designed for a specific task in the home.', context: 'Discussing kitchen or household equipment.', example: 'The kitchen has all the modern appliances: a dishwasher, microwave, and blender.', explanation: '"Appliance" refers to electrical devices used at home — washing machine, fridge, toaster. It\'s more specific than "device" (which includes phones, tablets). Collocations: "kitchen appliance", "household appliance", "electrical appliance".' },
      { word: 'tidy', wordClass: 'verb', level: 'A2', verbForms: { v1: 'tidy', v2: 'tidied', v3: 'tidied' }, meaning: 'To make a place neat and organised by putting things in order.', context: 'Cleaning up spaces in the home.', example: 'Could you tidy your room before the guests arrive?', explanation: '"Tidy" can be a verb ("tidy the room"), an adjective ("a tidy desk"), or part of phrasal verbs ("tidy up" = the same meaning but slightly more informal). British English prefers "tidy up" while American English may use "clean up" or "straighten up".' },
      { word: 'maintain', wordClass: 'verb', level: 'B1', verbForms: { v1: 'maintain', v2: 'maintained', v3: 'maintained' }, meaning: 'To keep something in good condition through regular care.', context: 'Taking care of property, health, or relationships.', example: 'It\'s important to maintain your car by getting regular oil changes.', explanation: '"Maintain" is more formal than "look after" or "keep up". The noun form is "maintenance". Collocations: "maintain a healthy lifestyle", "maintain a building", "maintain good relationships". In academic English, "maintain" also means "to state firmly" — "She maintained that she was innocent."' },
      { word: 'spacious', wordClass: 'adjective', level: 'B1', meaning: 'Having a lot of space; large and roomy.', context: 'Describing rooms, houses, or apartments.', example: 'The apartment is surprisingly spacious for a city-centre flat.', explanation: '"Spacious" is more sophisticated than "big" or "large" when describing living spaces. It emphasises comfort and openness. The opposite is "cramped" (too small and uncomfortable). Estate agents often use "spacious" in property descriptions.' },
      { word: 'cosy', wordClass: 'adjective', level: 'A2', meaning: 'Warm, comfortable, and giving a feeling of relaxation.', context: 'Describing pleasant, warm indoor spaces.', example: 'We spent the evening in the cosy living room by the fireplace.', explanation: '"Cosy" (British) or "cozy" (American) describes a small but comfortable space. Unlike "spacious", it suggests warmth and intimacy. Collocations: "a cosy corner", "a cosy café", "cosy atmosphere". It\'s always positive — a small room can be "cosy" (pleasant) or "cramped" (unpleasant).' },
      { word: 'thoroughly', wordClass: 'adverb', level: 'B1', meaning: 'In a complete and careful way, paying attention to every detail.', context: 'Describing how you clean, check, or do something.', example: 'Make sure you clean the kitchen thoroughly before cooking.', explanation: '"Thoroughly" means completely and carefully. It\'s stronger than "well" or "carefully". Collocations: "thoroughly clean", "thoroughly enjoy" (= really enjoy), "thoroughly investigate". The adjective form is "thorough": "a thorough inspection".' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 2. WORK & BUSINESS
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'work-business',
    name: 'Work & Business',
    description: 'Professional vocabulary for the workplace, meetings, and career development.',
    icon: '💼',
    entries: [
      { word: 'deadline', wordClass: 'noun', level: 'B1', meaning: 'The latest time by which something must be completed.', context: 'Project management and work schedules.', example: 'The deadline for the report is Friday at 5 p.m.', explanation: '"Deadline" comes from a literal line in prisons that prisoners could not cross. Today it means a time limit. Collocations: "meet a deadline" (finish on time), "miss a deadline" (finish late), "tight deadline" (very little time), "extend a deadline" (give more time).' },
      { word: 'revenue', wordClass: 'noun', level: 'B2', meaning: 'The total income a business earns from selling goods or services.', context: 'Financial discussions and business reports.', example: 'The company\'s annual revenue exceeded £10 million for the first time.', explanation: '"Revenue" is the total money coming in, before expenses are subtracted. Don\'t confuse with "profit" (revenue minus costs) or "income" (which can be personal). Collocations: "generate revenue", "annual revenue", "revenue growth", "revenue stream" (a source of income).' },
      { word: 'collaborate', wordClass: 'verb', level: 'B2', verbForms: { v1: 'collaborate', v2: 'collaborated', v3: 'collaborated' }, meaning: 'To work together with others to achieve a shared goal.', context: 'Team projects, partnerships, and joint efforts.', example: 'The two departments collaborated on the product launch.', explanation: '"Collaborate" is more formal than "work together". The noun is "collaboration", the person is "collaborator". Collocations: "collaborate with", "collaborate on a project", "close collaboration". In some historical contexts, "collaborator" has a negative meaning (someone who helped an enemy).' },
      { word: 'negotiate', wordClass: 'verb', level: 'B2', verbForms: { v1: 'negotiate', v2: 'negotiated', v3: 'negotiated' }, meaning: 'To discuss terms to reach an agreement acceptable to all parties.', context: 'Business deals, contracts, and salary discussions.', example: 'She negotiated a 15% salary increase during her performance review.', explanation: 'The noun is "negotiation" (the process) and "negotiator" (the person). Collocations: "negotiate a deal/contract/price", "negotiate with someone", "skilled negotiator". "Negotiate" also means to successfully navigate something difficult: "negotiate a sharp bend in the road".' },
      { word: 'implement', wordClass: 'verb', level: 'B2', verbForms: { v1: 'implement', v2: 'implemented', v3: 'implemented' }, meaning: 'To put a plan, decision, or policy into action.', context: 'Executing strategies, changes, or new systems.', example: 'The company implemented a new remote working policy last month.', explanation: '"Implement" is formal — in casual speech you might say "put into practice" or "carry out". The noun is "implementation". Collocations: "implement a strategy/plan/policy", "implement changes", "successful implementation". Don\'t confuse with "imply" (suggest indirectly) or "implicate" (involve in something negative).' },
      { word: 'efficient', wordClass: 'adjective', level: 'B1', meaning: 'Achieving maximum results with minimum waste of time, effort, or resources.', context: 'Evaluating processes, systems, or people\'s work.', example: 'The new software makes the ordering process much more efficient.', explanation: '"Efficient" focuses on doing things with minimal waste. Compare: "effective" = producing the desired result (it works), "efficient" = producing results with minimal waste (it works well and quickly). A process can be effective but not efficient. The noun is "efficiency". Adverb: "efficiently".' },
      { word: 'competitive', wordClass: 'adjective', level: 'B2', meaning: 'Having a strong desire to win; offering equal or better value than rivals.', context: 'Business markets, pricing, and personal ambition.', example: 'We offer competitive salaries and excellent benefits.', explanation: '"Competitive" has two main uses: 1) about people — "She\'s very competitive" (wants to win); 2) about business — "competitive prices" (as good as or better than others). Noun: "competition" (the event or rivalry), "competitor" (a rival company or person). Adverb: "competitively".' },
      { word: 'consistently', wordClass: 'adverb', level: 'B2', meaning: 'In a way that does not change over time; regularly and reliably.', context: 'Evaluating performance and reliability.', example: 'She has consistently exceeded her sales targets for three years.', explanation: '"Consistently" means doing something the same way every time — usually positive. The adjective is "consistent" (opposite: "inconsistent"). Collocations: "consistently high/good/poor", "consistently deliver", "consistent performance". In academic writing: "The findings are consistent with previous research."' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 3. HEALTH & MEDICINE
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'health-medicine',
    name: 'Health & Medicine',
    description: 'Medical vocabulary for doctor visits, symptoms, treatments, and wellbeing.',
    icon: '🏥',
    entries: [
      { word: 'symptom', wordClass: 'noun', level: 'B1', meaning: 'A physical or mental sign that indicates a disease or condition.', context: 'Describing health problems to a doctor.', example: 'Common symptoms of the flu include fever, body aches, and fatigue.', explanation: 'A "symptom" is what the patient feels or notices (headache, nausea). A "sign" is what the doctor observes (high temperature, swelling). Collocations: "develop symptoms", "common symptoms", "mild/severe symptoms", "symptoms of". The adjective is "symptomatic" — "symptomatic treatment" treats the symptoms, not the cause.' },
      { word: 'diagnosis', wordClass: 'noun', level: 'B2', meaning: 'The identification of a disease or condition based on examination.', context: 'Medical consultations and test results.', example: 'After several tests, the doctor confirmed a diagnosis of type 2 diabetes.', explanation: 'Plural: "diagnoses" (pronunciation changes: die-ag-NO-sis → die-ag-NO-seez). The verb is "diagnose": "She was diagnosed with asthma." Collocations: "make/give a diagnosis", "receive a diagnosis", "early diagnosis" (finding it quickly), "accurate diagnosis".' },
      { word: 'prescribe', wordClass: 'verb', level: 'B1', verbForms: { v1: 'prescribe', v2: 'prescribed', v3: 'prescribed' }, meaning: 'To authorise the use of a medicine or treatment for a patient.', context: 'Doctor-patient interactions about medication.', example: 'The doctor prescribed antibiotics for the chest infection.', explanation: 'Only qualified doctors can "prescribe" medicine. The document they write is a "prescription". Don\'t confuse with "proscribe" (to forbid — almost the opposite). Collocations: "prescribe medication/antibiotics/painkillers", "prescribed dose" (the amount to take).' },
      { word: 'recover', wordClass: 'verb', level: 'B1', verbForms: { v1: 'recover', v2: 'recovered', v3: 'recovered' }, meaning: 'To return to normal health after an illness or injury.', context: 'Discussing healing and getting better.', example: 'It took her six weeks to fully recover from the surgery.', explanation: 'The noun is "recovery". Collocations: "make a full recovery", "recover from an illness/operation/injury", "recovery time/period". "Recover" also means to get something back: "recover stolen goods", "recover lost data". The adjective is "recovered" — "a recovered patient".' },
      { word: 'chronic', wordClass: 'adjective', level: 'B2', meaning: 'Lasting for a long time or recurring frequently (of an illness).', context: 'Describing long-term health conditions.', example: 'Chronic back pain affects millions of people worldwide.', explanation: '"Chronic" means long-lasting — the opposite is "acute" (sudden and severe but short). A "chronic condition" lasts months or years (diabetes, asthma). Don\'t confuse with the informal British slang "chronic" = "very bad". Collocations: "chronic pain/disease/illness/fatigue", "chronic condition".' },
      { word: 'contagious', wordClass: 'adjective', level: 'B2', meaning: 'Able to spread from one person to another through contact.', context: 'Discussing infectious diseases and prevention.', example: 'The patient is no longer contagious after completing the treatment.', explanation: '"Contagious" = spreads by direct contact (flu, cold). "Infectious" is broader — it includes diseases that spread through air, water, or insects. All contagious diseases are infectious, but not all infectious diseases are contagious. Collocations: "highly contagious", "contagious disease", "contagious laughter/enthusiasm" (figurative).' },
      { word: 'gradually', wordClass: 'adverb', level: 'B1', meaning: 'Slowly and steadily over a period of time, not suddenly.', context: 'Describing the pace of recovery or changes in health.', example: 'The patient\'s condition gradually improved over several weeks.', explanation: 'The adjective is "gradual" (opposite: "sudden" or "abrupt"). Collocations: "gradually increase/decrease/improve", "a gradual change/recovery". In academic writing, "gradually" is preferred over "slowly" because it emphasises the step-by-step nature, not just the speed.' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 4. TRAVEL & TOURISM
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'travel-tourism',
    name: 'Travel & Tourism',
    description: 'Vocabulary for airports, accommodation, sightseeing, and travel planning.',
    icon: '✈️',
    entries: [
      { word: 'itinerary', wordClass: 'noun', level: 'B2', meaning: 'A detailed plan or schedule for a journey.', context: 'Organising and discussing travel plans.', example: 'Our itinerary includes three days in Rome and two days in Florence.', explanation: 'An "itinerary" lists where you go, when, and what you do — more detailed than a "plan". Collocations: "travel itinerary", "plan an itinerary", "packed itinerary" (very full schedule), "flexible itinerary" (can be changed). Pronunciation: eye-TIN-er-ary.' },
      { word: 'destination', wordClass: 'noun', level: 'B1', meaning: 'The place where someone is going or where something is sent.', context: 'Choosing where to travel or ship goods.', example: 'Bangkok is one of the most popular tourist destinations in the world.', explanation: 'Collocations: "tourist/holiday/travel destination", "popular destination", "final destination" (the last stop), "destination wedding" (a wedding abroad). Used in transport: "The train\'s final destination is Edinburgh."' },
      { word: 'accommodate', wordClass: 'verb', level: 'B2', verbForms: { v1: 'accommodate', v2: 'accommodated', v3: 'accommodated' }, meaning: 'To provide lodging or space for someone; to adjust to someone\'s needs.', context: 'Hotel bookings, making arrangements, being flexible.', example: 'The hotel can accommodate up to 200 guests.', explanation: 'Two main meanings: 1) Provide a place to stay — "The resort accommodates 500 visitors"; 2) Adapt or adjust — "We can accommodate your dietary requirements." The noun is "accommodation" (British: always uncountable — NOT "accommodations"). Common spelling mistake: two c\'s, two m\'s.' },
      { word: 'explore', wordClass: 'verb', level: 'A2', verbForms: { v1: 'explore', v2: 'explored', v3: 'explored' }, meaning: 'To travel through an unfamiliar area to learn about it.', context: 'Sightseeing and discovering new places.', example: 'We spent the afternoon exploring the old town and its narrow streets.', explanation: 'Used both literally (physically visiting places) and figuratively ("explore options/ideas/possibilities"). The noun is "exploration", the person is "explorer". Collocations: "explore a city/country/area", "explore the possibility of", "explore further".' },
      { word: 'scenic', wordClass: 'adjective', level: 'B1', meaning: 'Having beautiful natural views and landscapes.', context: 'Describing attractive routes, places, and views.', example: 'We took the scenic route along the coast instead of the motorway.', explanation: '"Scenic" always relates to natural beauty — mountains, coastlines, countryside. Collocations: "scenic route/drive/view/spot", "scenic beauty". The noun is "scenery" (uncountable): "The scenery in Switzerland is breathtaking." Don\'t confuse "scenery" (natural views) with "scene" (a specific view or situation).' },
      { word: 'abroad', wordClass: 'adverb', level: 'A2', meaning: 'In or to a foreign country.', context: 'Talking about international travel or living overseas.', example: 'She lived abroad for five years, mostly in Japan and South Korea.', explanation: '"Abroad" is an adverb, so it doesn\'t need a preposition — say "go abroad" NOT "go to abroad". Collocations: "live/work/study/travel abroad", "from abroad" (from another country), "overseas" is a synonym but specifically means across the sea.' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 5. TECHNOLOGY & DIGITAL
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'technology',
    name: 'Technology & Digital',
    description: 'Vocabulary for computing, the internet, software, and digital communication.',
    icon: '💻',
    entries: [
      { word: 'algorithm', wordClass: 'noun', level: 'B2', meaning: 'A set of rules or steps followed by a computer to solve a problem.', context: 'Software development, social media, search engines.', example: 'Social media algorithms decide which posts appear in your feed.', explanation: 'Originally a mathematical term, now widely used in tech. Collocations: "search algorithm", "recommendation algorithm", "complex/simple algorithm". The adjective is "algorithmic". In everyday use: "The YouTube algorithm keeps recommending cat videos" — meaning the automated system that makes decisions.' },
      { word: 'database', wordClass: 'noun', level: 'B1', meaning: 'An organised collection of data stored and accessed electronically.', context: 'IT systems, software development, data management.', example: 'All customer information is stored in a secure database.', explanation: 'A database organises data into tables, rows, and columns for efficient searching. Collocations: "database management", "search the database", "update the database", "relational database". Pronounced: DAY-tuh-base (British) or DAT-uh-base (American).' },
      { word: 'encrypt', wordClass: 'verb', level: 'B2', verbForms: { v1: 'encrypt', v2: 'encrypted', v3: 'encrypted' }, meaning: 'To convert data into a coded format to prevent unauthorised access.', context: 'Cybersecurity and data protection.', example: 'All messages on this app are end-to-end encrypted.', explanation: 'The opposite is "decrypt" (convert back to readable form). The noun is "encryption". Collocations: "encrypted data/messages/files", "encryption key", "256-bit encryption". In everyday terms: encryption scrambles information so only the intended recipient can read it.' },
      { word: 'download', wordClass: 'verb', level: 'A2', verbForms: { v1: 'download', v2: 'downloaded', v3: 'downloaded' }, meaning: 'To transfer data from the internet or another computer to your device.', context: 'Getting files, apps, or media from the internet.', example: 'You can download the app for free from the official website.', explanation: 'The opposite is "upload" (send from your device to the internet). "Download" is also a noun: "The download took 10 minutes." Collocations: "download a file/app/update", "free download", "download speed". "Stream" is different — streaming plays content without saving it permanently.' },
      { word: 'compatible', wordClass: 'adjective', level: 'B2', meaning: 'Able to work together without conflict or problems.', context: 'Software, hardware, and device interoperability.', example: 'Check that the software is compatible with your operating system before installing.', explanation: 'Used in technology and relationships. Tech: "compatible devices/software/formats". Relationships: "They\'re very compatible" (they get along well). The opposite is "incompatible". The noun is "compatibility". Collocations: "backward compatible" (works with older versions), "fully compatible".' },
      { word: 'virtually', wordClass: 'adverb', level: 'B2', meaning: 'Almost entirely; also: by means of a computer or online.', context: 'Describing things done online or almost complete states.', example: 'The meeting was held virtually due to travel restrictions.', explanation: 'Two meanings: 1) "almost" — "It\'s virtually impossible" (nearly impossible); 2) "online/digitally" — "We met virtually" (via video call). The adjective is "virtual": "virtual reality", "virtual meeting", "virtual assistant". The second meaning became much more common after 2020.' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 6. EDUCATION & LEARNING
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'education',
    name: 'Education & Learning',
    description: 'Academic vocabulary for schools, universities, exams, and lifelong learning.',
    icon: '🎓',
    entries: [
      { word: 'curriculum', wordClass: 'noun', level: 'B2', meaning: 'The subjects and content taught in a school or course.', context: 'Educational planning and course design.', example: 'The new curriculum places greater emphasis on critical thinking skills.', explanation: 'Plural: "curricula" (Latin) or "curriculums" (English). Collocations: "national curriculum", "school curriculum", "curriculum design", "curriculum vitae" (CV — literally "course of life"). Don\'t confuse with "syllabus" (the specific content of one course), while "curriculum" covers all subjects.' },
      { word: 'scholarship', wordClass: 'noun', level: 'B1', meaning: 'A financial award given to a student to help pay for their education.', context: 'University applications and financial aid.', example: 'She won a full scholarship to study engineering at the University of Melbourne.', explanation: 'A "scholarship" is usually based on academic merit or talent. A "bursary" or "grant" is typically based on financial need. Collocations: "win/receive/award a scholarship", "full/partial scholarship", "scholarship application", "scholarship fund". "Scholar" also means a learned person.' },
      { word: 'assess', wordClass: 'verb', level: 'B2', verbForms: { v1: 'assess', v2: 'assessed', v3: 'assessed' }, meaning: 'To evaluate or judge the quality, ability, or importance of something.', context: 'Exams, performance reviews, and project evaluation.', example: 'Students are assessed through a combination of coursework and examinations.', explanation: 'More formal than "test" or "check". The noun is "assessment" (the process or the test itself). Collocations: "assess performance/progress/risk/damage", "continuous assessment" (ongoing evaluation, not just one exam), "assessment criteria".' },
      { word: 'enrol', wordClass: 'verb', level: 'B1', verbForms: { v1: 'enrol', v2: 'enrolled', v3: 'enrolled' }, meaning: 'To officially register or sign up for a course or institution.', context: 'Starting a new course, school, or programme.', example: 'Over 500 students enrolled in the online course within the first week.', explanation: 'British spelling: "enrol" (one l). American: "enroll" (two l\'s). Both double the l for "enrolled/enrolling". The noun is "enrolment" (British) / "enrollment" (American). Collocations: "enrol in/on a course", "enrol at a university", "enrolment deadline".' },
      { word: 'comprehensive', wordClass: 'adjective', level: 'B2', meaning: 'Including all or nearly all elements or aspects; thorough.', context: 'Describing complete coverage of a topic or thorough preparation.', example: 'The textbook provides a comprehensive overview of modern European history.', explanation: '"Comprehensive" means nothing important is left out. Collocations: "comprehensive guide/report/review", "comprehensive coverage", "comprehensive exam" (covering everything). In British education, a "comprehensive school" is a non-selective state school open to all abilities.' },
      { word: 'academically', wordClass: 'adverb', level: 'B2', meaning: 'In a way that relates to education and scholarly study.', context: 'Discussing educational performance and standards.', example: 'She performed academically well but struggled with the practical components.', explanation: 'The adjective is "academic". Collocations: "academically gifted/talented", "academically rigorous", "academic year/journal/research". "Academic" can also mean "theoretical rather than practical" — "The argument is purely academic" means it has no practical importance.' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 7. ENVIRONMENT & NATURE
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'environment',
    name: 'Environment & Nature',
    description: 'Vocabulary for climate, wildlife, conservation, and environmental issues.',
    icon: '🌍',
    entries: [
      { word: 'ecosystem', wordClass: 'noun', level: 'B2', meaning: 'A community of living organisms interacting with their physical environment.', context: 'Biology, environmental science, and conservation.', example: 'Coral reefs are among the most diverse ecosystems on the planet.', explanation: '"Eco-" comes from Greek "oikos" (home/house). An ecosystem includes all living things (plants, animals, microorganisms) and non-living things (water, soil, sunlight) in an area. Collocations: "marine/forest/desert ecosystem", "fragile ecosystem", "ecosystem services" (benefits nature provides to humans).' },
      { word: 'emissions', wordClass: 'noun', level: 'B2', meaning: 'Gases or substances released into the atmosphere, especially pollutants.', context: 'Climate change discussions and environmental policy.', example: 'The government aims to reduce carbon emissions by 50% before 2030.', explanation: 'Usually plural in environmental context. The verb is "emit". Collocations: "carbon/greenhouse gas emissions", "reduce/cut emissions", "zero emissions", "emission standards". "Emissions" almost always refers to harmful gases in environmental discussions.' },
      { word: 'conserve', wordClass: 'verb', level: 'B2', verbForms: { v1: 'conserve', v2: 'conserved', v3: 'conserved' }, meaning: 'To protect something from harm, loss, or waste.', context: 'Environmental protection and resource management.', example: 'National parks were established to conserve wildlife and natural habitats.', explanation: 'The noun is "conservation" (protecting nature) — different from "conservatism" (political ideology). A "conservationist" protects nature; a "conservative" holds traditional political views. Collocations: "conserve energy/water/resources", "wildlife conservation", "conservation area".' },
      { word: 'deplete', wordClass: 'verb', level: 'C1', verbForms: { v1: 'deplete', v2: 'depleted', v3: 'depleted' }, meaning: 'To use up or reduce the quantity of a resource significantly.', context: 'Resource scarcity and environmental damage.', example: 'Overfishing has severely depleted fish stocks in the North Sea.', explanation: '"Deplete" is stronger than "reduce" — it suggests using up something until very little remains. The noun is "depletion". Collocations: "deplete resources/reserves/stocks", "ozone depletion", "depleted uranium". The adjective "depleted" means almost used up: "depleted supplies".' },
      { word: 'renewable', wordClass: 'adjective', level: 'B2', meaning: 'Able to be replaced naturally and not used up permanently.', context: 'Energy sources and sustainable development.', example: 'Solar and wind power are examples of renewable energy sources.', explanation: 'The opposite is "non-renewable" (fossil fuels like oil, coal, gas). Collocations: "renewable energy/resources", "renewable sources", "100% renewable". "Sustainable" is related but broader — it means something that can continue long-term without causing damage. All renewable energy is sustainable, but not everything sustainable involves energy.' },
      { word: 'sustainably', wordClass: 'adverb', level: 'B2', meaning: 'In a way that can continue over time without causing environmental damage.', context: 'Discussing responsible practices in business and daily life.', example: 'The farm produces food sustainably, without using chemical pesticides.', explanation: 'The adjective is "sustainable" (opposite: "unsustainable"). The noun is "sustainability". Collocations: "sustainably sourced/produced/managed", "sustainable development" (meeting present needs without compromising future generations), "sustainability report". One of the most important words in modern environmental and business English.' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 8. LAW & JUSTICE
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'law-justice',
    name: 'Law & Justice',
    description: 'Legal vocabulary for courts, rights, contracts, and the justice system.',
    icon: '⚖️',
    entries: [
      { word: 'legislation', wordClass: 'noun', level: 'C1', meaning: 'A law or set of laws made by a government or parliament.', context: 'Political and legal discussions about new laws.', example: 'New legislation was introduced to protect consumers from unfair practices.', explanation: '"Legislation" is uncountable — say "a piece of legislation", not "a legislation". Related words: "legislate" (verb — to make laws), "legislature" (the body that makes laws, e.g. parliament), "legislative" (adjective). Collocations: "introduce/pass/draft legislation", "existing legislation", "anti-discrimination legislation".' },
      { word: 'verdict', wordClass: 'noun', level: 'B2', meaning: 'The decision made by a jury or judge in a court case.', context: 'Criminal and civil court proceedings.', example: 'The jury reached a verdict of not guilty after three days of deliberation.', explanation: 'From Latin "vere dictum" (truly said). Collocations: "reach/deliver/return a verdict", "guilty/not guilty verdict", "unanimous verdict" (everyone agrees), "majority verdict" (most agree). Informally, "verdict" also means any opinion or judgement: "What\'s your verdict on the new restaurant?"' },
      { word: 'prosecute', wordClass: 'verb', level: 'C1', verbForms: { v1: 'prosecute', v2: 'prosecuted', v3: 'prosecuted' }, meaning: 'To bring criminal charges against someone in a court of law.', context: 'Criminal justice and legal proceedings.', example: 'The company was prosecuted for violating health and safety regulations.', explanation: 'The "prosecution" is the side that brings charges (opposite: "defence"). The "prosecutor" is the lawyer who accuses. Don\'t confuse with "persecute" (to treat someone cruelly because of their beliefs). Collocations: "prosecute someone for a crime", "the Crown Prosecution Service" (UK).' },
      { word: 'comply', wordClass: 'verb', level: 'B2', verbForms: { v1: 'comply', v2: 'complied', v3: 'complied' }, meaning: 'To act in accordance with a rule, law, or request.', context: 'Legal requirements, regulations, and workplace rules.', example: 'All businesses must comply with data protection regulations.', explanation: 'Always followed by "with": "comply with the law/rules/regulations". The noun is "compliance" (the state of following rules). An officer who checks this is a "compliance officer". Collocations: "comply with regulations", "full compliance", "non-compliance" (not following the rules), "compliance requirements".' },
      { word: 'legitimate', wordClass: 'adjective', level: 'C1', meaning: 'Conforming to the law or rules; reasonable and justified.', context: 'Evaluating whether actions, claims, or businesses are lawful.', example: 'The company has a legitimate right to protect its intellectual property.', explanation: 'Two pronunciations: leh-JIT-ih-mut (adjective) and leh-JIT-ih-mate (verb, meaning to make lawful). The noun is "legitimacy". The opposite is "illegitimate". Collocations: "legitimate concern/claim/business", "legitimate interest", "perfectly legitimate" (completely acceptable).' },
      { word: 'allegedly', wordClass: 'adverb', level: 'C1', meaning: 'According to what has been claimed but not yet proven.', context: 'News reports and legal discussions about unproven accusations.', example: 'The suspect allegedly fled the country before the warrant was issued.', explanation: '"Allegedly" is essential in legal and news English — it protects the speaker from making unproven claims. The adjective is "alleged" (pronounced uh-LEJD). The verb is "allege" (to claim without proof). Collocations: "allegedly committed/stole/attacked", "the alleged victim/perpetrator". Using "allegedly" correctly shows awareness of legal caution.' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 9. FINANCE & ECONOMICS
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'finance',
    name: 'Finance & Economics',
    description: 'Financial vocabulary for banking, investing, budgets, and economic concepts.',
    icon: '📊',
    entries: [
      { word: 'inflation', wordClass: 'noun', level: 'B2', meaning: 'A general increase in prices and fall in the purchasing power of money.', context: 'Economics, news, and discussions about the cost of living.', example: 'Inflation reached 8% last year, making everyday essentials more expensive.', explanation: 'The opposite is "deflation" (falling prices). Related: "inflationary" (adjective). Collocations: "rate of inflation", "high/low inflation", "inflation rate", "inflation-adjusted" (accounting for price increases), "hyperinflation" (extremely rapid inflation). Central banks try to keep inflation around 2%.' },
      { word: 'mortgage', wordClass: 'noun', level: 'B2', meaning: 'A loan from a bank to buy a property, repaid over many years with interest.', context: 'Home buying and property investment.', example: 'They took out a 25-year mortgage to buy their first house.', explanation: 'From French "mort" (death) + "gage" (pledge) — the pledge "dies" when the debt is paid. Collocations: "take out/apply for/pay off a mortgage", "mortgage rate" (interest rate), "mortgage payment", "fixed-rate mortgage" (interest stays the same), "variable-rate mortgage" (interest can change).' },
      { word: 'invest', wordClass: 'verb', level: 'B1', verbForms: { v1: 'invest', v2: 'invested', v3: 'invested' }, meaning: 'To put money into something with the expectation of profit or benefit.', context: 'Financial planning, business, and personal finance.', example: 'She invested £10,000 in technology stocks five years ago.', explanation: 'The noun is "investment" (the money or the act), "investor" (the person). Collocations: "invest in shares/property/education", "invest heavily/wisely", "return on investment" (ROI — how much profit you make). Figurative use: "invest time/effort in something" = dedicate significant time/effort.' },
      { word: 'fluctuate', wordClass: 'verb', level: 'C1', verbForms: { v1: 'fluctuate', v2: 'fluctuated', v3: 'fluctuated' }, meaning: 'To rise and fall irregularly in number, amount, or level.', context: 'Describing changing prices, temperatures, or exchange rates.', example: 'Oil prices fluctuate depending on global supply and demand.', explanation: '"Fluctuate" implies irregular, unpredictable movement up and down. The noun is "fluctuation". Collocations: "prices/temperatures/rates fluctuate", "fluctuate between X and Y", "market fluctuations", "currency fluctuation". More formal than "go up and down".' },
      { word: 'lucrative', wordClass: 'adjective', level: 'C1', meaning: 'Producing a great deal of profit; financially rewarding.', context: 'Describing profitable businesses, deals, or careers.', example: 'Consulting can be a highly lucrative career for experienced professionals.', explanation: 'More formal and specific than "profitable". "Lucrative" emphasises that something makes a LOT of money, not just some. Collocations: "lucrative deal/contract/market/career", "highly/extremely lucrative". It has a slightly materialistic tone — you wouldn\'t usually call charity work "lucrative".' },
      { word: 'financially', wordClass: 'adverb', level: 'B2', meaning: 'In a way that relates to money or the management of money.', context: 'Discussing someone\'s economic situation or business health.', example: 'The company is financially stable despite the economic downturn.', explanation: 'The adjective is "financial". Collocations: "financially stable/independent/viable", "financially responsible", "financial advisor/planning/crisis". "Fiscal" is similar but specifically relates to government finances and taxes: "fiscal policy", "fiscal year".' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 10. SCIENCE & RESEARCH
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'science-research',
    name: 'Science & Research',
    description: 'Scientific vocabulary for experiments, discoveries, data analysis, and academic research.',
    icon: '🔬',
    entries: [
      { word: 'hypothesis', wordClass: 'noun', level: 'B2', meaning: 'A proposed explanation for something that can be tested through experiments.', context: 'Scientific research and academic writing.', example: 'The researcher\'s hypothesis was that sleep deprivation impairs decision-making.', explanation: 'Plural: "hypotheses" (hi-POTH-eh-seez). A hypothesis is an educated guess before testing. If testing supports it, it may become a "theory" (a well-supported explanation). Collocations: "test/prove/support/reject a hypothesis", "null hypothesis" (the assumption that there is no effect — statisticians try to reject this).' },
      { word: 'variable', wordClass: 'noun', level: 'B2', meaning: 'A factor that can change in an experiment or situation.', context: 'Experimental design and data analysis.', example: 'The independent variable was the amount of light, and the dependent variable was plant growth.', explanation: 'In experiments: "independent variable" (what you change), "dependent variable" (what you measure), "controlled variable" (what you keep the same). Also an adjective meaning "likely to change": "variable weather". Collocations: "control a variable", "key variable", "variable rate".' },
      { word: 'analyse', wordClass: 'verb', level: 'B2', verbForms: { v1: 'analyse', v2: 'analysed', v3: 'analysed' }, meaning: 'To examine something in detail to understand it or discover its meaning.', context: 'Scientific research, data examination, and critical thinking.', example: 'Researchers analysed data from over 10,000 participants.', explanation: 'British spelling: "analyse". American: "analyze". The noun is "analysis" (plural: "analyses"). A person who analyses is an "analyst". Collocations: "analyse data/results/trends", "in-depth analysis", "statistical analysis", "critically analyse" (in academic writing — examine with judgement).' },
      { word: 'correlate', wordClass: 'verb', level: 'C1', verbForms: { v1: 'correlate', v2: 'correlated', v3: 'correlated' }, meaning: 'To have a mutual relationship or connection where one thing affects another.', context: 'Statistics, research findings, and pattern identification.', example: 'Higher levels of education correlate with higher lifetime earnings.', explanation: 'The noun is "correlation". CRUCIAL distinction: "correlation does not imply causation" — just because two things happen together doesn\'t mean one causes the other. Collocations: "positively/negatively correlated", "strong/weak correlation", "correlate with" (not "to"). "Positive correlation" = both increase together. "Negative correlation" = one increases while the other decreases.' },
      { word: 'empirical', wordClass: 'adjective', level: 'C1', meaning: 'Based on observation and experiment rather than theory alone.', context: 'Discussing evidence-based findings in academic research.', example: 'There is strong empirical evidence that regular exercise improves mental health.', explanation: '"Empirical" means you\'ve actually observed or measured something, not just theorised about it. It\'s one of the most important words in academic English. Collocations: "empirical evidence/data/research/study", "empirically tested/supported". The adverb is "empirically": "This claim has not been empirically verified."' },
      { word: 'conclusively', wordClass: 'adverb', level: 'C1', meaning: 'In a way that settles a matter definitively; beyond doubt.', context: 'Presenting research findings and evidence.', example: 'The study conclusively demonstrated that the treatment was effective.', explanation: 'The adjective is "conclusive" (opposite: "inconclusive" = not settling the matter). Collocations: "conclusively prove/demonstrate/show", "conclusive evidence", "inconclusive results" (not enough to decide). In academic writing, be careful — very few things are "conclusively" proven; hedging language is usually more appropriate.' },
    ],
  },
]
