// # ═══════════════════════════════════════════════════════════════════════════
// # VOCABULARY REFERENCE DATA — Part 3: New Diverse Categories
// # ═══════════════════════════════════════════════════════════════════════════
// # 5 brand-new categories with 50 words each — topics not covered in Parts 1–2.

import type { VocabField } from './types'

export const VOCAB_FIELDS_3: VocabField[] = [

  // # ═══════════════════════════════════════════════════════════════════
  // # 21. BODY & PHYSICAL DESCRIPTION
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'body-appearance',
    name: 'Body & Physical Description',
    description: 'Body parts, physical appearance, gestures, posture, and describing people.',
    icon: '🧍',
    entries: [
      // # ── Nouns ──
      { word: 'forehead', wordClass: 'noun', level: 'A2', meaning: 'The flat area of your face above the eyebrows and below the hairline.', context: 'Describing faces, expressions, and temperature checks.', example: 'She wiped the sweat from her forehead after the run.', explanation: 'Pronunciation: FOR-id (British) or FOR-hed (American). Collocations: "broad/high/wrinkled forehead", "touch/wipe your forehead".' },
      { word: 'eyebrow', wordClass: 'noun', level: 'A2', meaning: 'The strip of hair growing above each eye.', context: 'Facial expressions and beauty routines.', example: 'He raised an eyebrow in surprise when he heard the news.', explanation: 'Collocations: "raise/arch an eyebrow" (show surprise or doubt), "thick/thin eyebrows", "pluck/shape eyebrows". Idiom: "raise eyebrows" = cause surprise or disapproval.' },
      { word: 'eyelash', wordClass: 'noun', level: 'B1', meaning: 'One of the short hairs growing on the edge of the eyelid.', context: 'Beauty, cosmetics, and physical descriptions.', example: 'She has naturally long, dark eyelashes.', explanation: 'Usually plural: "eyelashes". "False eyelashes" / "eyelash extensions" = artificial lashes glued on. "Mascara" = the cosmetic applied to eyelashes. "Bat your eyelashes" = flutter them flirtatiously.' },
      { word: 'jaw', wordClass: 'noun', level: 'B1', meaning: 'The lower part of the face; the bone structure that holds the teeth.', context: 'Physical descriptions and dental contexts.', example: 'He has a strong, square jaw that gives his face a masculine look.', explanation: 'Collocations: "strong/square/clenched jaw", "jaw dropped" (= was very surprised), "jaw-dropping" (= astonishingly impressive). "Jawline" = the outline of the lower face.' },
      { word: 'chin', wordClass: 'noun', level: 'A2', meaning: 'The lowest part of the face, below the mouth.', context: 'Describing faces and expressions.', example: 'She rested her chin on her hand while she was thinking.', explanation: 'Collocations: "double chin" (fold of flesh under the chin), "pointed/square chin". Idioms: "keep your chin up" = stay cheerful in difficulty; "take it on the chin" = accept bad news bravely.' },
      { word: 'cheek', wordClass: 'noun', level: 'A2', meaning: 'The soft side of the face between the eye and the jaw.', context: 'Physical descriptions, expressions, and affection.', example: 'Her cheeks turned red with embarrassment.', explanation: 'Collocations: "rosy/chubby/hollow cheeks", "cheekbone" (the bone beneath the eye), "kiss on the cheek". Also means rudeness (British informal): "What a cheek!" = How rude! "Cheeky" = playfully rude.' },
      { word: 'wrist', wordClass: 'noun', level: 'A2', meaning: 'The joint connecting the hand to the arm.', context: 'Jewellery, injuries, and physical descriptions.', example: 'She wore a silver bracelet on her left wrist.', explanation: 'Collocations: "wristwatch", "wrist injury/pain", "flick of the wrist" (a quick hand movement). "Wristband" = a band worn on the wrist (for events or fitness trackers).' },
      { word: 'elbow', wordClass: 'noun', level: 'A2', meaning: 'The joint in the middle of the arm where it bends.', context: 'Body movements, injuries, and space descriptions.', example: 'He accidentally knocked his elbow on the table.', explanation: 'Collocations: "elbow room" (enough space to move), "elbow grease" (hard physical effort), "rub elbows with" (socialise with important people). Verb use: "elbow your way through" = push through a crowd using elbows.' },
      { word: 'ankle', wordClass: 'noun', level: 'A2', meaning: 'The joint connecting the foot to the leg.', context: 'Sports injuries, footwear, and physical descriptions.', example: 'She twisted her ankle while running on the uneven path.', explanation: 'Collocations: "sprained/twisted/broken ankle", "ankle boots" (boots reaching the ankle), "ankle bracelet/anklet" (jewellery). One of the most commonly injured joints in sport.' },
      { word: 'spine', wordClass: 'noun', level: 'B2', meaning: 'The column of bones running down the centre of the back; the backbone.', context: 'Medical contexts, posture, and figurative courage.', example: 'Poor posture can cause long-term damage to the spine.', explanation: 'Also called "backbone" or "spinal column". Collocations: "spinal cord" (nerves inside the spine), "spinal injury". Figurative: "spine-chilling" (terrifying), "spineless" (cowardly, no backbone).' },
      { word: 'palm', wordClass: 'noun', level: 'B1', meaning: 'The flat inner surface of the hand between the wrist and fingers.', context: 'Gestures, fortune-telling, and physical descriptions.', example: 'He held the small bird carefully in the palm of his hand.', explanation: 'Collocations: "sweaty palms" (sign of nervousness), "palm reading" (fortune-telling from hand lines). Don\'t confuse with "palm tree". Idiom: "have someone in the palm of your hand" = have complete control over them.' },
      { word: 'fist', wordClass: 'noun', level: 'B1', meaning: 'A hand with the fingers curled tightly into the palm.', context: 'Anger, fighting, and gestures of determination.', example: 'He clenched his fists in anger but managed to walk away.', explanation: 'Collocations: "clench/make a fist", "punch with your fist", "fist bump" (greeting where two fists touch), "iron fist" (ruling harshly). Verb: "fist pump" = raise your fist in celebration.' },
      { word: 'hip', wordClass: 'noun', level: 'B1', meaning: 'The joint and area where the leg meets the torso on each side of the body.', context: 'Dancing, injuries, and body shape descriptions.', example: 'She stood with her hands on her hips, looking impatient.', explanation: 'Collocations: "hip replacement" (surgery), "hip bone", "hands on hips" (a posture showing impatience or confidence), "hip-width apart" (exercise instruction). Also means trendy (informal): "a hip neighbourhood".' },
      { word: 'thigh', wordClass: 'noun', level: 'B1', meaning: 'The upper part of the leg between the hip and the knee.', context: 'Exercise, body descriptions, and cooking (chicken thigh).', example: 'Squats are great for strengthening the thigh muscles.', explanation: 'Pronunciation: like "thy" + silent "gh". Collocations: "inner/outer thigh", "thigh muscle/bone (femur)", "chicken thigh" (a cut of meat). "Thunder thighs" is offensive slang — avoid using it.' },
      { word: 'waist', wordClass: 'noun', level: 'A2', meaning: 'The narrow part of the body between the ribs and the hips.', context: 'Clothing measurements, body descriptions, and fitness.', example: 'The dress cinches at the waist and flares out at the bottom.', explanation: 'Don\'t confuse with "waste" (rubbish) — same pronunciation but different spelling. Collocations: "slim/narrow/thick waist", "waistline", "waistband" (the strip at the top of trousers), "waist measurement".' },
      { word: 'complexion', wordClass: 'noun', level: 'B2', meaning: 'The natural colour and appearance of the skin on a person\'s face.', context: 'Beauty, skincare, and literary character descriptions.', example: 'She has a clear, olive complexion that tans easily in the sun.', explanation: 'Collocations: "fair/dark/olive/clear/healthy complexion", "complexion problems" (acne, blemishes). More formal than "skin colour". Also figurative: "That puts a different complexion on things" = changes how we see the situation.' },
      { word: 'posture', wordClass: 'noun', level: 'B2', meaning: 'The way a person holds their body when standing, sitting, or walking.', context: 'Health, ergonomics, and body language.', example: 'Sitting at a desk all day can lead to poor posture and back pain.', explanation: 'Collocations: "good/bad/poor posture", "improve your posture", "upright posture". Also means attitude (formal): "the government\'s posture on climate change". "Postural" (adjective): "postural problems".' },
      { word: 'physique', wordClass: 'noun', level: 'B2', meaning: 'The shape and size of a person\'s body, especially when strong or attractive.', context: 'Fitness, athletics, and physical descriptions.', example: 'Years of swimming gave him an impressive, lean physique.', explanation: 'From French — pronounced fiz-EEK. Usually implies a well-built body. Collocations: "athletic/muscular/powerful/lean physique", "build up your physique". Different from "figure" (can apply to anyone) — "physique" usually implies strength or fitness.' },
      { word: 'wrinkle', wordClass: 'noun', level: 'B2', meaning: 'A line or crease in the skin, especially one caused by ageing.', context: 'Ageing, skincare, and fabric descriptions.', example: 'Laughter lines are wrinkles around the eyes that appear when you smile.', explanation: 'Collocations: "fine wrinkles", "wrinkle cream" (anti-ageing product), "iron out the wrinkles" (literally for clothes, figuratively for problems). Adjective: "wrinkled" (skin or clothes). "Wrinkle-free" = no creases.' },
      { word: 'scar', wordClass: 'noun', level: 'B1', meaning: 'A permanent mark left on the skin after a wound has healed.', context: 'Injuries, surgery, and emotional trauma (figurative).', example: 'He has a small scar on his chin from a childhood accident.', explanation: 'Also a verb: "The accident scarred him for life" (physically or emotionally). Collocations: "deep/faint/surgical scar", "emotional scars" (lasting psychological damage), "scarred tissue". "Scarring" can be physical or emotional.' },
      { word: 'freckle', wordClass: 'noun', level: 'B1', meaning: 'A small light-brown spot on the skin, often appearing in sun-exposed areas.', context: 'Physical descriptions and skin types.', example: 'She has a scattering of freckles across her nose and cheeks.', explanation: 'Usually plural: "freckles". More common in fair-skinned people. Collocations: "covered in freckles", "freckled face/skin". Different from "mole" (a raised dark spot) and "birthmark" (a coloured mark present from birth).' },
      { word: 'limb', wordClass: 'noun', level: 'B1', meaning: 'An arm or leg of a person or animal.', context: 'Medical reports, physical descriptions, and tree parts.', example: 'The accident left him with injuries to his lower limbs.', explanation: 'Collocations: "upper/lower limbs" (arms/legs), "artificial/prosthetic limb", "limb by limb". Also means a large branch of a tree. Idiom: "go out on a limb" = take a risk or say something controversial.' },
      { word: 'skull', wordClass: 'noun', level: 'B2', meaning: 'The bone structure of the head that protects the brain.', context: 'Anatomy, injuries, and danger symbols.', example: 'The cyclist was lucky — the helmet protected her skull in the crash.', explanation: 'Collocations: "fractured skull", "skull and crossbones" (the pirate/poison symbol), "thick skull" (informal — a slow thinker). Different from "skeleton" (all bones) — "skull" is specifically the head bones.' },
      { word: 'muscle', wordClass: 'noun', level: 'A2', meaning: 'Tissue in the body that can contract to produce movement.', context: 'Exercise, anatomy, and strength descriptions.', example: 'You need to warm up properly to avoid pulling a muscle.', explanation: 'Collocations: "muscle pain/strain/cramp", "build muscle", "muscle memory" (body remembers repeated movements). "Muscular" (adjective). "Flex your muscles" = show off your strength (literally or figuratively).' },
      { word: 'nerve', wordClass: 'noun', level: 'B1', meaning: 'A fibre that carries signals between the brain and other parts of the body.', context: 'Medicine, emotions, and courage.', example: 'The dentist gave her an injection to numb the nerve before the filling.', explanation: 'Collocations: "nerve damage/endings/pain", "hit a nerve" (= upset someone), "nerve-racking/wracking" (= making you very anxious), "nerves of steel" (= extremely calm under pressure). "Nervous" = anxious, but "nerve" = courage: "He had the nerve to complain!"' },
      // # ── Verbs ──
      { word: 'blink', wordClass: 'verb', level: 'A2', verbForms: { v1: 'blink', v2: 'blinked', v3: 'blinked' }, meaning: 'To open and close your eyes very quickly, usually involuntarily.', context: 'Eye movements, surprise, and rapid actions.', example: 'She blinked several times, trying to adjust to the bright light.', explanation: 'Collocations: "blink rapidly", "without blinking" (= without showing surprise), "in the blink of an eye" (= extremely quickly). "Not blink" can mean to stay calm under pressure.' },
      { word: 'yawn', wordClass: 'verb', level: 'A2', verbForms: { v1: 'yawn', v2: 'yawned', v3: 'yawned' }, meaning: 'To open the mouth wide and breathe in deeply, usually when tired or bored.', context: 'Tiredness, boredom, and uncontrollable reflexes.', example: 'He yawned loudly during the meeting, which was quite embarrassing.', explanation: 'Also a noun: "a big yawn". Yawning is famously contagious — seeing someone yawn makes you want to yawn too. Figurative: "The lecture was a real yawn" (= extremely boring).' },
      { word: 'shiver', wordClass: 'verb', level: 'B1', verbForms: { v1: 'shiver', v2: 'shivered', v3: 'shivered' }, meaning: 'To shake slightly because of cold, fear, or excitement.', context: 'Cold weather, fear, and physical reactions.', example: 'She shivered in the icy wind as she waited for the bus.', explanation: 'Also a noun: "a shiver ran down her spine" (a common literary expression for fear). Different from "shudder" (a sudden, more violent shake, usually from disgust or horror) and "tremble" (continuous shaking from weakness or emotion).' },
      { word: 'sweat', wordClass: 'verb', level: 'B1', verbForms: { v1: 'sweat', v2: 'sweated', v3: 'sweated' }, meaning: 'To produce moisture through the skin, usually from heat or exercise.', context: 'Exercise, hot weather, and nervousness.', example: 'After running for an hour, he was sweating heavily.', explanation: 'Also a noun: "covered in sweat". Past tense: "sweated" (British) or "sweat" (American). Collocations: "sweat profusely", "break into a sweat" (start sweating suddenly), "cold sweat" (sweating from fear, not heat). "No sweat!" (informal) = no problem!' },
      { word: 'frown', wordClass: 'verb', level: 'B1', verbForms: { v1: 'frown', v2: 'frowned', v3: 'frowned' }, meaning: 'To bring your eyebrows together and wrinkle your forehead, showing displeasure or concentration.', context: 'Facial expressions showing confusion, disapproval, or deep thought.', example: 'She frowned at the confusing instructions on the form.', explanation: 'Also a noun: "a deep frown". Opposite of "smile". Collocations: "frown at/upon something" (= disapprove of it), "frown of concentration/disapproval". "Frowned upon" = socially disapproved: "Smoking indoors is frowned upon."' },
      { word: 'squint', wordClass: 'verb', level: 'B2', verbForms: { v1: 'squint', v2: 'squinted', v3: 'squinted' }, meaning: 'To partially close the eyes to see better in bright light or at a distance.', context: 'Bright conditions, poor vision, and trying to read small text.', example: 'He squinted at the sign, trying to read it from across the road.', explanation: 'Also a noun: "She had a slight squint" (= eyes not perfectly aligned — a medical condition). Collocations: "squint at/into", "squint in the sunlight". Different from "wink" (closing one eye deliberately).' },
      { word: 'nod', wordClass: 'verb', level: 'A2', verbForms: { v1: 'nod', v2: 'nodded', v3: 'nodded' }, meaning: 'To move the head up and down to show agreement, understanding, or greeting.', context: 'Conversations, greetings, and non-verbal communication.', example: 'She nodded in agreement when asked if she understood the instructions.', explanation: 'Note: double "d" — "nodded", "nodding". Opposite gesture: "shake your head" (= no). Collocations: "nod in agreement/approval", "nod off" (= fall asleep), "a nod of the head". In some cultures, nodding means "no" (e.g., Bulgaria).' },
      { word: 'shrug', wordClass: 'verb', level: 'B1', verbForms: { v1: 'shrug', v2: 'shrugged', v3: 'shrugged' }, meaning: 'To raise and lower your shoulders to show you don\'t know or don\'t care.', context: 'Expressing uncertainty, indifference, or helplessness.', example: '"I have no idea," he said, shrugging his shoulders.', explanation: 'Also a noun: "She gave a shrug." Collocations: "shrug your shoulders", "shrug off" (= dismiss as unimportant: "He shrugged off the criticism"). The emoji 🤷 represents a shrug.' },
      { word: 'tremble', wordClass: 'verb', level: 'B2', verbForms: { v1: 'tremble', v2: 'trembled', v3: 'trembled' }, meaning: 'To shake involuntarily from fear, cold, weakness, or strong emotion.', context: 'Fear, cold, emotional moments, and physical weakness.', example: 'Her hands trembled as she opened the letter with the exam results.', explanation: 'More literary/emotional than "shake". Collocations: "tremble with fear/anger/excitement", "trembling voice/hands/lips". "Tremble" implies vulnerability. A "tremor" is a slight earthquake or an involuntary muscle shake.' },
      { word: 'limp', wordClass: 'verb', level: 'B1', verbForms: { v1: 'limp', v2: 'limped', v3: 'limped' }, meaning: 'To walk with difficulty because one leg or foot is injured.', context: 'Injuries, sports, and physical difficulties.', example: 'He limped off the football pitch after twisting his knee.', explanation: 'Also a noun: "walk with a limp". Also an adjective meaning "lacking firmness": "a limp handshake" (= weak, floppy). Collocations: "limp away/off/along", "noticeable limp". "Limp" as adjective: "limp lettuce" (= wilted, not crisp).' },
      { word: 'kneel', wordClass: 'verb', level: 'B1', verbForms: { v1: 'kneel', v2: 'knelt', v3: 'knelt' }, meaning: 'To go down on one or both knees.', context: 'Prayer, proposals, gardening, and respect.', example: 'He knelt down to tie his shoelace.', explanation: 'Past tense: "knelt" (British) or "kneeled" (American). Collocations: "kneel down", "kneel before someone" (show respect), "kneeling position". Cultural: kneeling to propose marriage; kneeling in prayer; kneeling as protest (taking a knee).' },
      { word: 'stare', wordClass: 'verb', level: 'A2', verbForms: { v1: 'stare', v2: 'stared', v3: 'stared' }, meaning: 'To look at something or someone fixedly for a long time.', context: 'Surprise, rudeness, and intense observation.', example: 'It\'s rude to stare at people, especially strangers.', explanation: 'Stronger and longer than "look" or "gaze". "Stare" often implies rudeness or intensity. Collocations: "stare at", "blank stare" (= expressionless look), "stare into space" (= look at nothing, lost in thought). "Gaze" is more romantic/positive than "stare".' },
      { word: 'clench', wordClass: 'verb', level: 'B2', verbForms: { v1: 'clench', v2: 'clenched', v3: 'clenched' }, meaning: 'To close or squeeze tightly, especially fists, teeth, or jaw.', context: 'Anger, determination, and physical tension.', example: 'She clenched her teeth to stop herself from saying something she\'d regret.', explanation: 'Collocations: "clench your fist/teeth/jaw", "clenched fist" (symbol of protest or determination). Different from "clutch" (= grab and hold tightly) and "grasp" (= take hold firmly). "Clench" implies internal tension.' },
      { word: 'flex', wordClass: 'verb', level: 'B2', verbForms: { v1: 'flex', v2: 'flexed', v3: 'flexed' }, meaning: 'To bend or tighten a muscle to show strength or test movement.', context: 'Gym culture, showing off, and rehabilitation.', example: 'He flexed his biceps in front of the mirror after his workout.', explanation: 'Modern slang: "flex" = show off, boast: "Stop flexing on social media." Collocations: "flex your muscles" (literal or figurative), "flexible" (= able to bend easily). "Flexibility" is the noun for how bendy you are.' },
      { word: 'stumble', wordClass: 'verb', level: 'B1', verbForms: { v1: 'stumble', v2: 'stumbled', v3: 'stumbled' }, meaning: 'To trip or lose balance while walking; to make a mistake in speech.', context: 'Walking on uneven ground and speech difficulties.', example: 'She stumbled on the uneven pavement and nearly fell.', explanation: 'Collocations: "stumble over/on" (physically trip), "stumble over words" (speak clumsily), "stumble across/upon" (= find by accident — a very useful meaning). "Stumbling block" = an obstacle preventing progress.' },
      { word: 'crouch', wordClass: 'verb', level: 'B2', verbForms: { v1: 'crouch', v2: 'crouched', v3: 'crouched' }, meaning: 'To bend your knees and lower your body close to the ground.', context: 'Hiding, photography, sports, and approaching animals.', example: 'She crouched behind the wall to hide from the children during the game.', explanation: 'Different from "kneel" (knees on ground) and "squat" (similar but a gym exercise). Collocations: "crouch down", "crouching position". "Crouch" implies trying to make yourself smaller, often to hide or get close to something.' },
      { word: 'breathe', wordClass: 'verb', level: 'A2', verbForms: { v1: 'breathe', v2: 'breathed', v3: 'breathed' }, meaning: 'To take air into the lungs and let it out again.', context: 'Relaxation, exercise, and life itself.', example: 'Take a deep breath and try to relax before the presentation.', explanation: 'Note spelling: "breathe" (verb, rhymes with "seethe") vs "breath" (noun, rhymes with "death"). Collocations: "breathe in/out", "breathe deeply", "breathe a sigh of relief", "breathtaking" (= amazingly beautiful). "Breathless" = out of breath.' },
      // # ── Adjectives ──
      { word: 'slim', wordClass: 'adjective', level: 'A2', meaning: 'Thin in an attractive and healthy-looking way.', context: 'Describing body shape positively.', example: 'She\'s tall and slim with long dark hair.', explanation: 'Positive — unlike "skinny" (too thin, negative) or "thin" (neutral). Scale: skinny → slim/slender → average → plump → overweight → obese. Collocations: "slim figure/build/chance" (also figurative: "a slim chance" = small probability).' },
      { word: 'muscular', wordClass: 'adjective', level: 'B1', meaning: 'Having well-developed muscles; strong and physically powerful.', context: 'Describing athletes, bodybuilders, and physically strong people.', example: 'He\'s quite muscular from years of weight training.', explanation: 'Collocations: "muscular build/arms/body", "muscular dystrophy" (a medical condition). More specific than "strong" — "muscular" implies visible muscles. Similar: "toned" (defined muscles without bulk), "buff" (informal — very muscular).' },
      { word: 'pale', wordClass: 'adjective', level: 'A2', meaning: 'Light in colour; having less colour than usual, often from illness or shock.', context: 'Describing skin colour, illness, and emotional reactions.', example: 'You look very pale — are you feeling all right?', explanation: 'Can describe skin or colours: "pale skin" (light), "pale blue" (light blue). "Turn/go pale" = suddenly lose colour (from shock or illness). Opposite: "flushed" (red-faced), "tanned" (brown from sun). Collocations: "deathly pale", "pale complexion".' },
      { word: 'tanned', wordClass: 'adjective', level: 'B1', meaning: 'Having darker skin from exposure to the sun.', context: 'After holidays, outdoor work, and beauty standards.', example: 'She came back from her beach holiday looking beautifully tanned.', explanation: 'The verb is "tan": "I tan easily" / "I burn easily." The noun is "suntan" or just "tan". Collocations: "deeply/lightly tanned", "fake tan" (artificial tanning product), "tanning bed/salon". Cultural note: tanning attitudes vary worldwide.' },
      { word: 'plump', wordClass: 'adjective', level: 'B1', meaning: 'Having a full, rounded body shape; slightly fat in a pleasant way.', context: 'Describing body shape, babies, and food.', example: 'The baby had plump little cheeks that everyone wanted to pinch.', explanation: 'Usually softer and less offensive than "fat". Often positive for babies and food: "plump tomatoes/cushions/lips". "Plump up" = make fuller. For adults, use carefully — some may find it patronising. "Chubby" is similar but more informal.' },
      { word: 'slender', wordClass: 'adjective', level: 'B2', meaning: 'Gracefully thin; slim and elegant.', context: 'Literary descriptions and elegant body types.', example: 'She had slender fingers that were perfect for playing the piano.', explanation: 'More elegant and literary than "slim" or "thin". Collocations: "slender build/figure/frame/fingers", "long and slender". "Slender" is always positive. Also figurative: "a slender margin/lead/hope" = very small.' },
      { word: 'frail', wordClass: 'adjective', level: 'B2', meaning: 'Weak, delicate, and lacking physical strength, especially due to age or illness.', context: 'Elderly care, recovering patients, and vulnerability.', example: 'My grandmother has become very frail since her hip operation.', explanation: 'Implies vulnerability and needing care. Collocations: "frail and elderly", "frail health", "physically frail". The noun is "frailty": "the frailty of old age." Different from "fragile" (easily broken — used more for objects and emotions).' },
      { word: 'athletic', wordClass: 'adjective', level: 'B1', meaning: 'Having a strong, fit body suited for physical exercise and sport.', context: 'Describing sporty people and body types.', example: 'She has an athletic build — broad shoulders and strong legs.', explanation: 'Collocations: "athletic build/body/figure", "athletic ability", "athletic scholarship" (university place awarded for sports skill). "An athlete" = a person who does sport. "Athletics" (British) = track and field events.' },
      { word: 'graceful', wordClass: 'adjective', level: 'B2', meaning: 'Moving in a smooth, controlled, and attractive way; elegant.', context: 'Dance, movement, and elegant behaviour.', example: 'Ballet dancers make even the most difficult movements look graceful.', explanation: 'Collocations: "graceful movement/dancer", "graceful ageing" (growing old elegantly). Opposite: "clumsy" (awkward, likely to drop things), "ungainly" (awkward-looking in movement). "Gracefully" (adverb): "She gracefully accepted the criticism."' },
      { word: 'broad', wordClass: 'adjective', level: 'B1', meaning: 'Wide across; having a large distance from side to side.', context: 'Describing shoulders, smiles, and general width.', example: 'He\'s a tall man with broad shoulders and a friendly smile.', explanation: 'Collocations: "broad shoulders/chest/smile/accent" (a strong regional accent), "broad daylight" (full daytime — "attacked in broad daylight"). Different from "wide" — "broad" often implies impressiveness. "Broadly" (adverb): "broadly speaking" = in general.' },
      { word: 'petite', wordClass: 'adjective', level: 'B2', meaning: 'Small and attractively proportioned (used mainly for women).', context: 'Fashion, body descriptions, and clothing sizes.', example: 'She\'s quite petite, so she always shops in the petite section.', explanation: 'From French — always positive, implying attractive smallness. "Petite" clothing = designed for shorter women (usually under 5\'3"/160cm). Gender note: traditionally used only for women. For men: "small build" or "slight". "Petite" is a dress size category in many fashion brands.' },
      // # ── Adverbs ──
      { word: 'upright', wordClass: 'adverb', level: 'B1', meaning: 'In a straight, vertical position; with the back straight.', context: 'Posture, seating positions, and correct body alignment.', example: 'The doctor advised him to sit upright to ease his back pain.', explanation: 'Also an adjective: "an upright position/posture/piano" (a tall piano, not a grand). Collocations: "sit/stand upright", "bolt upright" (suddenly very straight, from surprise or alarm). "Upright citizen" = an honest, morally correct person.' },
      { word: 'briskly', wordClass: 'adverb', level: 'B2', meaning: 'In a quick, energetic, and purposeful way.', context: 'Walking speed, business manner, and exercise.', example: 'She walked briskly through the park, arms swinging at her sides.', explanation: 'The adjective is "brisk": "a brisk walk/pace/wind/trade". Collocations: "walk/move briskly", "brisk morning/wind" (fresh and cold). "Brisk business/trade" = lots of buying and selling. Different from "quickly" — "briskly" implies energy and purpose, not just speed.' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 22. CRIME, SAFETY & EMERGENCY
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'crime-safety',
    name: 'Crime, Safety & Emergency',
    description: 'Vocabulary for crimes, law enforcement, safety measures, and emergency situations.',
    icon: '🚨',
    entries: [
      // # ── Nouns ──
      { word: 'suspect', wordClass: 'noun', level: 'B1', meaning: 'A person believed to have committed a crime but not yet proven guilty.', context: 'Police investigations and news reports.', example: 'The police have identified a suspect in the robbery case.', explanation: 'Stress: noun = SUS-pect, verb = sus-PECT. "A suspect" = a person. "To suspect" = to believe something is true. "Suspected" (adjective): "a suspected criminal". Different from "accused" (formally charged) or "convict" (found guilty).' },
      { word: 'witness', wordClass: 'noun', level: 'B1', meaning: 'A person who sees an event happen, especially a crime or accident.', context: 'Court cases, accidents, and police statements.', example: 'Three witnesses saw the car run the red light before the accident.', explanation: 'Also a verb: "I witnessed the whole incident." Collocations: "eyewitness" (= saw it directly), "key/star witness" (most important one), "witness statement" (written account), "witness stand/box" (where witnesses testify in court).' },
      { word: 'victim', wordClass: 'noun', level: 'B1', meaning: 'A person who suffers harm, injury, or loss as a result of a crime or event.', context: 'Crime reports, disasters, and support services.', example: 'The victims of the fraud lost thousands of pounds each.', explanation: 'Collocations: "crime/fraud/accident victim", "victim support" (organisation helping victims), "fall victim to" (= become a victim of), "victimise" (= treat someone unfairly). Can also be used more broadly: "a victim of circumstance/their own success".' },
      { word: 'evidence', wordClass: 'noun', level: 'B1', meaning: 'Facts, objects, or signs that prove something is true or has happened.', context: 'Court cases, scientific research, and investigations.', example: 'The DNA evidence proved that the suspect was at the crime scene.', explanation: 'Uncountable — "evidence" not "an evidence" or "evidences". Collocations: "strong/circumstantial/forensic evidence", "gather/collect/present evidence", "evidence suggests/shows that...", "a piece/body of evidence".' },
      { word: 'robbery', wordClass: 'noun', level: 'B1', meaning: 'The crime of stealing from a person or place using force or threats.', context: 'Bank crimes, street crime, and insurance claims.', example: 'An armed robbery took place at the jewellery shop last night.', explanation: 'Different from "theft" (stealing without force), "burglary" (breaking into a building to steal), and "mugging" (robbing someone on the street). Collocations: "armed robbery", "bank/highway robbery". "Daylight robbery" (British) = an outrageously high price.' },
      { word: 'burglary', wordClass: 'noun', level: 'B1', meaning: 'The crime of entering a building illegally to steal.', context: 'Home security, insurance, and police reports.', example: 'There have been several burglaries in the neighbourhood recently.', explanation: 'The person is a "burglar". Different from "robbery" (uses force against people) — "burglary" involves breaking into a property, often when nobody is home. Collocations: "home burglary", "attempted burglary", "break-in" (informal synonym).' },
      { word: 'fraud', wordClass: 'noun', level: 'B2', meaning: 'The crime of deceiving people to gain money or advantage illegally.', context: 'Financial crime, identity theft, and online scams.', example: 'Credit card fraud costs banks billions of pounds every year.', explanation: 'Collocations: "commit fraud", "credit card/identity/tax fraud", "fraud prevention", "fraudulent" (adjective — "fraudulent activity/claim"), "fraudster" (the person who commits fraud). Online fraud is one of the fastest-growing crimes globally.' },
      { word: 'assault', wordClass: 'noun', level: 'B2', meaning: 'A physical attack on another person.', context: 'Criminal charges, violent crime, and personal safety.', example: 'He was charged with assault after the fight outside the bar.', explanation: 'Also a verb: "He assaulted the officer." Legal distinctions: "common assault" (threat or minor contact), "actual bodily harm (ABH)" (causing injury), "grievous bodily harm (GBH)" (serious injury). "Sexual assault" is a specific legal category.' },
      { word: 'arson', wordClass: 'noun', level: 'C1', meaning: 'The crime of deliberately setting fire to property.', context: 'Fire investigations, insurance fraud, and criminal cases.', example: 'Police believe the warehouse fire was an act of arson.', explanation: 'Uncountable — "commit arson" not "an arson" (though "an arson attack" is common). The person is an "arsonist". Collocations: "suspected arson", "arson attack/investigation", "commit arson". Often linked to insurance fraud (burning your own property to claim insurance).' },
      { word: 'vandalism', wordClass: 'noun', level: 'B2', meaning: 'The deliberate destruction or damage of public or private property.', context: 'Neighbourhood crime, public spaces, and youth behaviour.', example: 'The park benches were destroyed in an act of vandalism.', explanation: 'The person is a "vandal". The verb is "vandalise": "Someone vandalised the bus shelter." Collocations: "act of vandalism", "anti-vandalism measures". From the "Vandals" — a Germanic tribe that sacked Rome in 455 AD.' },
      { word: 'surveillance', wordClass: 'noun', level: 'B2', meaning: 'Close observation of a person or place, especially by police or security cameras.', context: 'Security, privacy debates, and police operations.', example: 'The building is under 24-hour surveillance with CCTV cameras.', explanation: 'From French — pronunciation: ser-VAY-lance. Collocations: "under surveillance", "surveillance camera/footage/system", "CCTV surveillance", "mass surveillance" (monitoring entire populations — a privacy concern). "Surveillance state" = a government that heavily monitors citizens.' },
      { word: 'alibi', wordClass: 'noun', level: 'B2', meaning: 'Evidence that a person was somewhere else when a crime was committed.', context: 'Criminal investigations and detective stories.', example: 'The suspect claims he was at a restaurant at the time — the waiter confirmed his alibi.', explanation: 'From Latin "alibi" = "elsewhere". Collocations: "provide/have/check an alibi", "solid/watertight alibi" (= one that can\'t be questioned), "alibi witness" (someone who confirms the alibi). A "false alibi" = a made-up story about where you were.' },
      { word: 'motive', wordClass: 'noun', level: 'B2', meaning: 'A reason for doing something, especially a crime.', context: 'Detective investigations and understanding criminal behaviour.', example: 'The police couldn\'t identify a clear motive for the attack.', explanation: 'Collocations: "motive for murder/the crime", "clear/ulterior motive" (an ulterior motive = a hidden, often selfish reason), "political/financial motive". In detective stories, the classic question: "What was the motive?" = Why did they do it?' },
      { word: 'detective', wordClass: 'noun', level: 'B1', meaning: 'A person whose job is to investigate crimes and find evidence.', context: 'Police work, crime fiction, and investigations.', example: 'A team of detectives was assigned to investigate the murder case.', explanation: 'Collocations: "private detective" (hired by individuals, not police), "detective story/novel/series", "detective work" (= careful investigation — also used figuratively). Famous fictional detectives: Sherlock Holmes, Hercule Poirot, Inspector Morse.' },
      { word: 'penalty', wordClass: 'noun', level: 'B1', meaning: 'A punishment imposed for breaking a law or rule.', context: 'Legal sentencing, sports, and regulations.', example: 'The penalty for speeding can be a fine, points on your licence, or both.', explanation: 'Collocations: "death penalty" (execution), "penalty fine/kick/shootout" (sports), "severe/maximum penalty", "pay the penalty" (= suffer consequences). "Penalise" (verb): "The company was penalised for late filing."' },
      { word: 'custody', wordClass: 'noun', level: 'B2', meaning: 'The state of being kept in prison or police care, especially before trial.', context: 'Arrests, child arrangements, and legal proceedings.', example: 'The suspect was taken into police custody for questioning.', explanation: 'Two main uses: 1) Legal: "in custody" = being held by police; "remanded in custody" = kept in prison until trial; 2) Family: "child custody" = legal right to care for a child after divorce. Collocations: "police/protective custody", "custody battle" (parents fighting for the child).' },
      // # ── Verbs ──
      { word: 'arrest', wordClass: 'verb', level: 'B1', verbForms: { v1: 'arrest', v2: 'arrested', v3: 'arrested' }, meaning: 'To officially take someone into police custody for a suspected crime.', context: 'Law enforcement and crime reports.', example: 'The police arrested two men in connection with the bank robbery.', explanation: 'Also a noun: "to make an arrest", "under arrest". Collocations: "arrest someone for/on suspicion of", "you\'re under arrest" (the official phrase), "arrest warrant" (legal document authorising arrest). "House arrest" = confined to your home instead of prison.' },
      { word: 'investigate', wordClass: 'verb', level: 'B1', verbForms: { v1: 'investigate', v2: 'investigated', v3: 'investigated' }, meaning: 'To examine a crime, problem, or situation carefully to discover the truth.', context: 'Police work, journalism, and academic research.', example: 'Police are investigating the cause of the fire at the factory.', explanation: 'The noun is "investigation" and the person is an "investigator". Collocations: "investigate a crime/complaint/allegation", "criminal/police investigation", "under investigation" (= being examined). "Investigative journalism" = reporting that uncovers wrongdoing.' },
      { word: 'confess', wordClass: 'verb', level: 'B2', verbForms: { v1: 'confess', v2: 'confessed', v3: 'confessed' }, meaning: 'To admit to committing a crime or doing something wrong.', context: 'Criminal proceedings, religious practice, and personal admissions.', example: 'After hours of questioning, the suspect confessed to the robbery.', explanation: 'The noun is "confession". Collocations: "confess to a crime/murder", "forced/false confession", "I must confess" (= I have to admit). Also religious: "go to confession" (Catholic practice of admitting sins to a priest).' },
      { word: 'convict', wordClass: 'verb', level: 'B2', verbForms: { v1: 'convict', v2: 'convicted', v3: 'convicted' }, meaning: 'To find someone guilty of a criminal offence in a court of law.', context: 'Court verdicts and criminal justice outcomes.', example: 'He was convicted of fraud and sentenced to three years in prison.', explanation: 'Stress: verb = con-VICT, noun = CON-vict (a person found guilty). Collocations: "convicted of a crime", "convicted criminal", "prior convictions" (past guilty verdicts). Opposite: "acquit" (= find not guilty). "Conviction" = the guilty verdict.' },
      { word: 'sentence', wordClass: 'verb', level: 'B2', verbForms: { v1: 'sentence', v2: 'sentenced', v3: 'sentenced' }, meaning: 'To officially declare the punishment for someone found guilty of a crime.', context: 'Court verdicts and criminal justice.', example: 'The judge sentenced the defendant to five years in prison.', explanation: 'Also a noun: "a prison/life/death sentence", "serve a sentence" (= complete the punishment). Collocations: "sentence someone to X years", "suspended sentence" (not carried out unless they reoffend), "harsh/lenient sentence". Different meaning: a sentence in grammar.' },
      { word: 'flee', wordClass: 'verb', level: 'B2', verbForms: { v1: 'flee', v2: 'fled', v3: 'fled' }, meaning: 'To run away from a dangerous or unpleasant situation.', context: 'Escaping crime scenes, wars, and natural disasters.', example: 'The robbers fled the scene before police arrived.', explanation: 'More formal than "run away". Past tense: "fled" (not "fleed"). Collocations: "flee the country/scene", "flee from danger/persecution". Refugees "flee" war or persecution. "Flight" (noun) can mean the act of fleeing: "flight from danger".' },
      { word: 'rescue', wordClass: 'verb', level: 'A2', verbForms: { v1: 'rescue', v2: 'rescued', v3: 'rescued' }, meaning: 'To save someone from a dangerous or difficult situation.', context: 'Emergencies, disasters, and urgent help.', example: 'Firefighters rescued three people trapped in the burning building.', explanation: 'Also a noun: "a dramatic rescue", "rescue team/mission/helicopter". Collocations: "come to the rescue" (= arrive to help), "mountain/sea rescue", "rescue operation/effort". A "rescuer" is the person who saves others.' },
      { word: 'evacuate', wordClass: 'verb', level: 'B2', verbForms: { v1: 'evacuate', v2: 'evacuated', v3: 'evacuated' }, meaning: 'To move people away from a dangerous area to a safe place.', context: 'Natural disasters, bomb threats, and building fires.', example: 'All residents were evacuated from the area ahead of the approaching hurricane.', explanation: 'The noun is "evacuation". Collocations: "evacuate a building/area/city", "evacuation plan/route/drill", "emergency evacuation". Can refer to people ("They evacuated the residents") or places ("They evacuated the building" — meaning they emptied it of people).' },
      { word: 'testify', wordClass: 'verb', level: 'B2', verbForms: { v1: 'testify', v2: 'testified', v3: 'testified' }, meaning: 'To give evidence as a witness in a court of law.', context: 'Court proceedings and legal cases.', example: 'She was called to testify against her former employer in the fraud trial.', explanation: 'The noun is "testimony". Collocations: "testify in court", "testify against/for someone", "testify under oath" (= legally sworn to tell the truth). "Perjury" = the crime of lying while testifying under oath.' },
      // # ── Adjectives ──
      { word: 'suspicious', wordClass: 'adjective', level: 'B1', meaning: 'Causing a feeling that something is wrong or illegal; distrustful.', context: 'Reporting concerns and describing doubtful behaviour.', example: 'If you see anything suspicious, please report it to security immediately.', explanation: 'Two uses: 1) "Suspicious behaviour/package" = looks wrong; 2) "I\'m suspicious of his motives" = I don\'t trust him. Collocations: "suspicious activity/circumstances", "look/act suspicious", "suspiciously" (adverb). The noun is "suspicion": "aroused suspicion".' },
      { word: 'guilty', wordClass: 'adjective', level: 'B1', meaning: 'Responsible for committing a crime or wrongdoing; feeling remorse.', context: 'Court verdicts and personal feelings of remorse.', example: 'The jury found the defendant guilty on all charges.', explanation: 'Two uses: 1) Legal: "found guilty" (= convicted); 2) Emotional: "I feel guilty about forgetting her birthday." Collocations: "plead guilty/not guilty", "guilty conscience" (= feeling of remorse), "guilty pleasure" (= something you enjoy but feel you shouldn\'t).' },
      { word: 'innocent', wordClass: 'adjective', level: 'B1', meaning: 'Not guilty of a crime; having done nothing wrong.', context: 'Court defences, wrongful convictions, and children.', example: 'He maintained his innocence throughout the trial and was eventually found not guilty.', explanation: 'Legal note: courts don\'t find people "innocent" — they find them "not guilty" (subtly different). "Innocent" also means naive/harmless: "an innocent remark" (= not intended to offend), "innocent bystander" (= uninvolved person caught up in events). Noun: "innocence".' },
      { word: 'forensic', wordClass: 'adjective', level: 'B2', meaning: 'Relating to scientific methods used to investigate crimes.', context: 'Crime scene investigation and evidence analysis.', example: 'Forensic experts examined the crime scene for fingerprints and DNA.', explanation: 'Collocations: "forensic science/evidence/analysis/pathologist", "forensic accounting" (investigating financial crimes), "forensic medicine" (determining cause of death). "Forensics" (noun) = the use of science in criminal investigation. Very popular thanks to TV shows like CSI.' },
      { word: 'undercover', wordClass: 'adjective', level: 'B2', meaning: 'Done secretly, especially by police officers pretending to be ordinary people.', context: 'Police operations and investigative journalism.', example: 'An undercover police officer spent six months infiltrating the drug gang.', explanation: 'Collocations: "undercover agent/officer/operation/investigation", "go undercover" (= take on a secret identity). Different from "plainclothes" (police not in uniform but not hiding their identity). "Undercover" implies deception for the purpose of investigation.' },
      { word: 'armed', wordClass: 'adjective', level: 'B1', meaning: 'Carrying a weapon, especially a gun.', context: 'Crime reports, military, and security.', example: 'Armed guards are stationed outside the embassy at all times.', explanation: 'Collocations: "armed robbery/forces/conflict/guard", "heavily armed", "armed and dangerous" (police warning). Opposite: "unarmed" (carrying no weapons). "Arms" (noun, plural) = weapons: "arms dealer", "right to bear arms" (US Constitution).' },
      // # ── Adverbs ──
      { word: 'deliberately', wordClass: 'adverb', level: 'B1', meaning: 'Done on purpose; intentionally and with full awareness.', context: 'Determining whether an act was planned or accidental.', example: 'The fire was started deliberately — it was not an accident.', explanation: 'The adjective is "deliberate". Collocations: "deliberately set/started/planned", "act deliberately". Different from "accidentally" (= by mistake) and "inadvertently" (= without realising). "Deliberate" also means careful: "She spoke in a slow, deliberate manner."' },
      { word: 'anonymously', wordClass: 'adverb', level: 'B2', meaning: 'In a way that does not reveal the person\'s name or identity.', context: 'Reporting crimes, giving donations, and online activity.', example: 'The crime was reported anonymously through the tip line.', explanation: 'The adjective is "anonymous" and the noun is "anonymity". Collocations: "report/donate/post anonymously", "remain anonymous", "anonymous tip/source/caller". "Anonymity" is a key concern in online life — some social platforms allow anonymous posting.' },
      { word: 'illegally', wordClass: 'adverb', level: 'B1', meaning: 'In a way that breaks the law; unlawfully.', context: 'Describing actions that violate laws and regulations.', example: 'The car was illegally parked on the double yellow lines.', explanation: 'The adjective is "illegal" (opposite: "legal"). Collocations: "illegally parked/obtained/downloaded", "illegal activity/drug/immigrant". Note: "illegal" as a noun for a person ("an illegal") is considered offensive — say "undocumented immigrant/migrant" instead.' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 23. SOCIAL ISSUES & SOCIETY
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'social-issues',
    name: 'Social Issues & Society',
    description: 'Vocabulary for inequality, diversity, migration, welfare, activism, and civic participation.',
    icon: '🌍',
    entries: [
      // # ── Nouns ──
      { word: 'inequality', wordClass: 'noun', level: 'B2', meaning: 'An unfair difference in size, opportunity, wealth, or status between groups.', context: 'Social policy, economics, and human rights.', example: 'Income inequality has grown significantly over the past two decades.', explanation: 'Collocations: "income/wealth/gender/racial inequality", "social inequality", "reduce/address inequality". The adjective is "unequal": "unequal distribution of wealth". "Equality" is the opposite. Key IELTS Writing Task 2 topic.' },
      { word: 'poverty', wordClass: 'noun', level: 'B1', meaning: 'The state of being extremely poor and lacking basic necessities.', context: 'Social welfare, development, and economic policy.', example: 'Over 700 million people worldwide still live in extreme poverty.', explanation: 'Uncountable. Collocations: "extreme/absolute poverty" (can\'t meet basic needs), "relative poverty" (poor compared to others in your country), "poverty line/threshold" (minimum income level), "child poverty", "lift out of poverty".' },
      { word: 'discrimination', wordClass: 'noun', level: 'B2', meaning: 'The unjust treatment of people based on characteristics like race, gender, or age.', context: 'Employment law, civil rights, and social justice.', example: 'Racial discrimination in hiring practices remains a serious problem.', explanation: 'Collocations: "racial/gender/age discrimination", "face/experience discrimination", "anti-discrimination laws", "positive discrimination" (British) / "affirmative action" (American) = favouring disadvantaged groups. The verb is "discriminate against".' },
      { word: 'prejudice', wordClass: 'noun', level: 'B2', meaning: 'An unreasonable opinion or feeling formed without knowledge or thought.', context: 'Social attitudes, bias, and historical injustice.', example: 'Education is one of the best tools for overcoming prejudice.', explanation: 'Collocations: "racial/cultural prejudice", "deep-rooted prejudice", "prejudice against". Different from "discrimination" — "prejudice" is the attitude, "discrimination" is the action. "Prejudiced" (adjective): "a prejudiced view". "Without prejudice" (legal) = without affecting existing rights.' },
      { word: 'diversity', wordClass: 'noun', level: 'B2', meaning: 'The inclusion of people from different backgrounds, races, genders, and abilities.', context: 'Workplace policies, education, and social progress.', example: 'The company is committed to promoting diversity and inclusion in the workplace.', explanation: 'Collocations: "diversity and inclusion (D&I)", "cultural/ethnic/gender diversity", "diverse workforce/community". The adjective is "diverse": "a diverse team". "Biodiversity" = variety of plant and animal species in an environment.' },
      { word: 'refugee', wordClass: 'noun', level: 'B2', meaning: 'A person who has been forced to leave their country to escape war, persecution, or disaster.', context: 'International politics, humanitarian crises, and migration.', example: 'Millions of refugees have fled the conflict in search of safety.', explanation: 'Different from "migrant" (chooses to move, often for work) and "asylum seeker" (has applied for protection but not yet been granted refugee status). Collocations: "refugee camp/crisis/status", "political refugee". The 1951 Refugee Convention defines their legal rights.' },
      { word: 'welfare', wordClass: 'noun', level: 'B2', meaning: 'Government support for people in need; or general health, happiness, and safety.', context: 'Social policy, benefits, and care systems.', example: 'The welfare system provides financial support to people who are unable to work.', explanation: 'Two meanings: 1) Government benefits: "welfare state" (system where government provides healthcare, education, pensions), "welfare benefits/payments"; 2) General wellbeing: "child welfare", "animal welfare", "the welfare of employees". "On welfare" = receiving government benefits.' },
      { word: 'charity', wordClass: 'noun', level: 'B1', meaning: 'An organisation that raises money to help people in need; or the act of giving help.', context: 'Fundraising, volunteering, and social support.', example: 'The charity provides meals and shelter for homeless people.', explanation: 'Collocations: "charity work/event/shop", "donate to charity", "charity begins at home" (proverb — help those closest to you first), "for charity" (purpose). "Charitable" (adjective): "a charitable donation/organisation". British "charity shops" = American "thrift stores".' },
      { word: 'activism', wordClass: 'noun', level: 'B2', meaning: 'The use of campaigning, protests, or direct action to bring about social or political change.', context: 'Social movements, environmental causes, and political engagement.', example: 'Youth activism on climate change has put pressure on world leaders.', explanation: 'The person is an "activist". Collocations: "social/political/environmental activism", "climate activism", "online activism" (using social media for causes), "activist group/movement". Related: "advocate" (= someone who publicly supports a cause).' },
      { word: 'community', wordClass: 'noun', level: 'A2', meaning: 'A group of people living in the same area or sharing common interests.', context: 'Local government, social bonds, and shared identity.', example: 'The local community came together to clean up the park.', explanation: 'Collocations: "local/online/international community", "community centre/service/spirit", "sense of community", "community leader". Can be geographic ("the Oxford community") or identity-based ("the LGBTQ+ community", "the scientific community").' },
      { word: 'stereotype', wordClass: 'noun', level: 'B2', meaning: 'A widely held but oversimplified and often inaccurate belief about a group of people.', context: 'Media representation, bias, and cultural assumptions.', example: 'We need to challenge gender stereotypes that limit career choices.', explanation: 'Also a verb: "Don\'t stereotype people based on where they come from." Collocations: "cultural/gender/racial stereotype", "break/challenge/reinforce stereotypes", "stereotypical" (adjective). Stereotypes can be positive or negative, but both are problematic because they oversimplify.' },
      { word: 'volunteer', wordClass: 'noun', level: 'B1', meaning: 'A person who offers to do something without being paid.', context: 'Charities, community projects, and disaster relief.', example: 'Over a hundred volunteers helped to distribute food after the flood.', explanation: 'Also a verb: "She volunteered at the hospital every weekend." Collocations: "volunteer work/worker", "volunteer for/at", "voluntary" (adjective — done by choice, not forced), "voluntarily" (adverb). "Voluntary sector" = the part of the economy run by charities and non-profits.' },
      { word: 'census', wordClass: 'noun', level: 'C1', meaning: 'An official count and survey of the population, usually conducted every 10 years.', context: 'Government data collection, demographics, and planning.', example: 'The latest census shows that the country\'s population has grown by 5%.', explanation: 'Plural: "censuses". Collocations: "national census", "census data/results", "conduct/carry out a census". The UK census has been conducted every 10 years since 1801 (except 1941 during WWII). It records population, housing, employment, ethnicity, and more.' },
      // # ── Verbs ──
      { word: 'discriminate', wordClass: 'verb', level: 'B2', verbForms: { v1: 'discriminate', v2: 'discriminated', v3: 'discriminated' }, meaning: 'To treat someone unfairly based on characteristics like race, gender, or age.', context: 'Employment, education, and public services.', example: 'It is illegal to discriminate against employees on the basis of their age.', explanation: 'Collocations: "discriminate against" (= treat unfairly), "discriminate between" (= distinguish — a neutral/positive meaning). "Discriminating" (adjective) = having good judgement: "a discriminating palate/taste". Two very different meanings — context is everything.' },
      { word: 'integrate', wordClass: 'verb', level: 'B2', verbForms: { v1: 'integrate', v2: 'integrated', v3: 'integrated' }, meaning: 'To combine or include people from different groups into a single community or system.', context: 'Immigration, education, and organisational change.', example: 'The programme helps newly arrived families integrate into the local community.', explanation: 'The noun is "integration" (opposite: "segregation"). Collocations: "integrate into society/community", "integrated system/approach", "racial integration". Also technical: "integrate a system" (= combine different parts into one). "Integral" (adjective) = essential part of something.' },
      { word: 'advocate', wordClass: 'verb', level: 'B2', verbForms: { v1: 'advocate', v2: 'advocated', v3: 'advocated' }, meaning: 'To publicly support or recommend a cause or policy.', context: 'Policy debates, activism, and professional recommendations.', example: 'Many health experts advocate banning sugary drink advertising aimed at children.', explanation: 'Stress: verb = AD-voh-kate, noun = AD-voh-kut. An "advocate" (noun) is a person who supports a cause. Collocations: "advocate for change/reform", "strong/passionate advocate", "advocacy" (noun — the act of supporting). In law: "advocate" = a lawyer (especially in Scotland).' },
      { word: 'donate', wordClass: 'verb', level: 'B1', verbForms: { v1: 'donate', v2: 'donated', v3: 'donated' }, meaning: 'To give money, food, blood, or organs to help others without expecting anything in return.', context: 'Charities, blood services, and disaster relief.', example: 'She donates 10% of her salary to children\'s charities every month.', explanation: 'The noun is "donation" and the person is a "donor". Collocations: "donate money/blood/organs/clothes", "generous donation", "anonymous donor", "organ donor" (someone who agrees to give their organs after death).' },
      { word: 'protest', wordClass: 'verb', level: 'B1', verbForms: { v1: 'protest', v2: 'protested', v3: 'protested' }, meaning: 'To express strong disagreement with something through public action.', context: 'Demonstrations, strikes, and civil disobedience.', example: 'Thousands of people protested against the new law in the city centre.', explanation: 'Also a noun: "a peaceful/violent protest". Stress: noun = PRO-test, verb = pro-TEST (British) or PRO-test (American). Collocations: "protest against/about", "protest march/rally", "right to protest", "protester/protestor" (the person).' },
      { word: 'campaign', wordClass: 'verb', level: 'B1', verbForms: { v1: 'campaign', v2: 'campaigned', v3: 'campaigned' }, meaning: 'To work in an organised way towards a particular goal.', context: 'Elections, social causes, and marketing.', example: 'She has campaigned tirelessly for equal pay for women.', explanation: 'Also a noun: "an election/advertising/awareness campaign". Collocations: "campaign for/against", "campaign trail" (the journey of seeking election), "campaign manager", "campaigner" (the person). Can be political, social, or commercial.' },
      { word: 'empower', wordClass: 'verb', level: 'B2', verbForms: { v1: 'empower', v2: 'empowered', v3: 'empowered' }, meaning: 'To give someone the authority, confidence, or means to do something.', context: 'Social justice, education, and leadership development.', example: 'The programme empowers young women to start their own businesses.', explanation: 'The noun is "empowerment". Collocations: "empower people/women/communities", "feel empowered", "empowerment through education/technology". A popular word in modern social discourse — sometimes criticised for overuse. "Disempower" is the opposite.' },
      // # ── Adjectives ──
      { word: 'underprivileged', wordClass: 'adjective', level: 'B2', meaning: 'Not having the same advantages, opportunities, or resources as most people in society.', context: 'Social inequality, education access, and charity work.', example: 'The foundation provides scholarships for students from underprivileged backgrounds.', explanation: 'More diplomatic than "poor" or "disadvantaged". Collocations: "underprivileged children/communities/areas", "underprivileged backgrounds". Opposite: "privileged" (= having special advantages). "Privilege" (noun) = an advantage available only to a particular group.' },
      { word: 'inclusive', wordClass: 'adjective', level: 'B2', meaning: 'Open to everyone regardless of their background, identity, or ability.', context: 'Workplace culture, education, and social policy.', example: 'The school promotes an inclusive environment where every child feels welcome.', explanation: 'Collocations: "inclusive education/workplace/language/society", "diversity and inclusion". The noun is "inclusion" (opposite: "exclusion"). "Inclusive language" = language that doesn\'t exclude any group (e.g., using "they" as a singular pronoun, saying "firefighter" not "fireman").' },
      { word: 'vulnerable', wordClass: 'adjective', level: 'B2', meaning: 'Easily hurt, damaged, or at risk; in need of special protection.', context: 'Social care, health risks, and emotional fragility.', example: 'Elderly people living alone are particularly vulnerable during heatwaves.', explanation: 'Collocations: "vulnerable groups/people/children", "most/highly vulnerable", "vulnerable to" (= at risk of). The noun is "vulnerability". "Emotionally vulnerable" = easily hurt emotionally. Important concept in safeguarding and social care.' },
      { word: 'equitable', wordClass: 'adjective', level: 'C1', meaning: 'Fair and just; giving everyone a reasonable share.', context: 'Policy design, resource distribution, and justice.', example: 'The goal is to ensure equitable access to healthcare for all citizens.', explanation: 'Different from "equal" — "equal" means everyone gets the same, "equitable" means everyone gets what they need (which may be different amounts). Collocations: "equitable distribution/access/treatment", "equitable society". "Equity" (noun) = fairness. A key concept in modern social policy.' },
      { word: 'humanitarian', wordClass: 'adjective', level: 'B2', meaning: 'Concerned with reducing human suffering and improving welfare.', context: 'Disaster relief, international aid, and crisis response.', example: 'The UN launched a humanitarian aid operation to help victims of the earthquake.', explanation: 'Collocations: "humanitarian aid/crisis/relief/organisation", "humanitarian grounds" (for compassionate reasons), "humanitarian law" (protecting civilians in war). "Humanitarian" can also be a noun: "She\'s a well-known humanitarian." Different from "humane" (= showing kindness to animals/people).' },
      // # ── Adverbs ──
      { word: 'disproportionately', wordClass: 'adverb', level: 'C1', meaning: 'To an extent that is too large or too small relative to what is fair or expected.', context: 'Statistical analysis, social inequality, and policy criticism.', example: 'Ethnic minorities are disproportionately affected by unemployment.', explanation: 'The adjective is "disproportionate". Collocations: "disproportionately affected/impacted/represented". Very important in academic writing about inequality. "A disproportionate number/amount" = more than expected. Implies unfairness or imbalance.' },
      { word: 'collectively', wordClass: 'adverb', level: 'B2', meaning: 'Together as a group; as a whole rather than individually.', context: 'Community action, group decisions, and shared responsibility.', example: 'The community collectively raised £50,000 for the new playground.', explanation: 'The adjective is "collective" and the noun is "collective". Collocations: "collectively responsible/known/owned", "collective action/bargaining/memory", "collective noun" (grammar). "Collectively" emphasises togetherness: "We are collectively responsible for climate change."' },
      { word: 'predominantly', wordClass: 'adverb', level: 'B2', meaning: 'Mainly; for the most part.', context: 'Describing the main characteristic of a group or area.', example: 'The neighbourhood is predominantly residential, with very few shops.', explanation: 'The adjective is "predominant" and the verb is "predominate". Collocations: "predominantly male/female/white/rural", "predominantly used/found/located". More formal than "mostly" or "mainly". "The predominant view" = the most common opinion.' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 24. ANIMALS & NATURE
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'animals-nature',
    name: 'Animals & Nature',
    description: 'Vocabulary for wildlife, animal behaviour, habitats, ecosystems, and the natural world.',
    icon: '🦁',
    entries: [
      // # ── Nouns ──
      { word: 'mammal', wordClass: 'noun', level: 'B1', meaning: 'A warm-blooded animal that feeds its young with milk.', context: 'Biology, wildlife documentaries, and animal classification.', example: 'Whales are mammals, not fish — they breathe air and feed their young milk.', explanation: 'Collocations: "marine mammal" (whales, dolphins), "land mammal", "small/large mammals". All mammals share: warm blood, hair/fur, live birth (except monotremes like platypus), milk production. Humans are mammals.' },
      { word: 'reptile', wordClass: 'noun', level: 'B1', meaning: 'A cold-blooded animal with scales that usually lays eggs, such as snakes and lizards.', context: 'Zoology, pet keeping, and nature programmes.', example: 'Crocodiles are reptiles that can live both in water and on land.', explanation: 'Examples: snakes, lizards, crocodiles, turtles, tortoises. "Reptilian" (adjective). Collocations: "pet reptile", "reptile house" (in a zoo). Different from "amphibian" (frogs, newts — live in water AND land, have moist skin, no scales).' },
      { word: 'predator', wordClass: 'noun', level: 'B2', meaning: 'An animal that hunts and kills other animals for food.', context: 'Ecology, food chains, and wildlife behaviour.', example: 'Lions are apex predators — no other animal hunts them.', explanation: '"Apex predator" = top of the food chain. The opposite is "prey" (= an animal that is hunted). "Predatory" (adjective): also used figuratively — "predatory pricing/lending" (unfairly aggressive). The verb is "predate" (formal) or "prey on".' },
      { word: 'prey', wordClass: 'noun', level: 'B2', meaning: 'An animal that is hunted and eaten by another animal.', context: 'Wildlife, ecology, and survival.', example: 'Gazelles are common prey for cheetahs on the African savannah.', explanation: 'Uncountable when general: "The owl is searching for prey." Also a verb: "Cats prey on mice." Collocations: "prey on/upon", "bird of prey" (eagle, hawk, owl), "fall prey to" (= become a victim of — also figurative). "Predator and prey" is the fundamental ecological relationship.' },
      { word: 'species', wordClass: 'noun', level: 'B1', meaning: 'A group of living organisms that can interbreed and produce fertile offspring.', context: 'Biology, conservation, and biodiversity.', example: 'Scientists have discovered a new species of frog in the Amazon rainforest.', explanation: 'Same form singular and plural: "one species", "many species" (NOT "specie" — that means coins). Collocations: "endangered/invasive/native species", "species diversity", "species extinction". There are an estimated 8.7 million species on Earth.' },
      { word: 'breed', wordClass: 'noun', level: 'B1', meaning: 'A particular variety of animal that has been developed by humans through selective breeding.', context: 'Dogs, cats, horses, and animal selection.', example: 'Labrador Retrievers are one of the most popular dog breeds worldwide.', explanation: 'Also a verb: "They breed horses on their farm." Collocations: "dog/cat/horse breed", "pure breed/pedigree" (= only one breed in its ancestry), "crossbreed" (= mix of two breeds). "Breeding" = 1) producing young; 2) good manners: "a person of good breeding" (old-fashioned).' },
      { word: 'flock', wordClass: 'noun', level: 'B1', meaning: 'A group of birds or sheep together.', context: 'Nature observation, farming, and group descriptions.', example: 'A flock of geese flew overhead in a perfect V formation.', explanation: 'Animal group words: "flock" (birds/sheep), "herd" (cattle/elephants), "pack" (wolves/dogs), "swarm" (bees/insects), "school/shoal" (fish), "pride" (lions). Also a verb: "People flocked to the sale" (= arrived in large numbers).' },
      { word: 'habitat', wordClass: 'noun', level: 'B1', meaning: 'The natural home or environment where an animal or plant normally lives.', context: 'Conservation, ecology, and environmental protection.', example: 'Deforestation is destroying the habitats of countless animal species.', explanation: 'Collocations: "natural habitat", "habitat loss/destruction/fragmentation", "wildlife habitat", "habitat conservation". Types: forest, wetland, coral reef, desert, tundra, grassland. "Habitat fragmentation" = breaking large habitats into small isolated pieces.' },
      { word: 'ecosystem', wordClass: 'noun', level: 'B2', meaning: 'A community of living organisms interacting with each other and their environment.', context: 'Environmental science, conservation, and ecology.', example: 'Coral reefs are one of the most diverse ecosystems on Earth.', explanation: 'Collocations: "marine/freshwater/forest ecosystem", "ecosystem services" (benefits nature provides: clean air, water, pollination), "fragile ecosystem", "disrupt/damage an ecosystem". Also used in business: "startup/tech ecosystem" (the interconnected community).' },
      { word: 'extinction', wordClass: 'noun', level: 'B2', meaning: 'The complete disappearance of a species from Earth.', context: 'Conservation, climate change, and evolutionary history.', example: 'The dodo is a famous example of extinction caused by human activity.', explanation: 'Collocations: "face/be threatened with extinction", "mass extinction" (many species dying at once — there have been 5 in Earth\'s history), "extinct" (adjective), "on the brink/verge of extinction". "Extinction Rebellion" = a climate activist group.' },
      { word: 'instinct', wordClass: 'noun', level: 'B2', meaning: 'A natural, inborn pattern of behaviour not learned through experience.', context: 'Animal behaviour, human intuition, and survival.', example: 'Birds have an instinct to migrate south before winter arrives.', explanation: 'Collocations: "natural/survival/maternal instinct", "by instinct" (= naturally, without thinking), "gut instinct" (= intuitive feeling). "Instinctive" (adjective) / "instinctively" (adverb): "She instinctively ducked when the ball flew towards her."' },
      { word: 'offspring', wordClass: 'noun', level: 'B2', meaning: 'The young of an animal or the children of a person.', context: 'Biology, genetics, and reproduction.', example: 'A female elephant carries her offspring for 22 months before giving birth.', explanation: 'Same form singular and plural: "one offspring", "three offspring" (NOT "offsprings"). More formal/scientific than "baby/young/child". Collocations: "produce/raise offspring", "male/female offspring". In genetics: "The offspring inherits genes from both parents."' },
      { word: 'camouflage', wordClass: 'noun', level: 'B2', meaning: 'The way an animal\'s colouring or shape helps it blend in with its surroundings.', context: 'Wildlife adaptation, military, and fashion.', example: 'The chameleon uses camouflage to hide from predators by changing colour.', explanation: 'Also a verb: "The soldiers camouflaged themselves with leaves and mud." Collocations: "natural camouflage", "camouflage pattern/clothing" (military and fashion). "Camo" = informal abbreviation. In nature, camouflage is a survival adaptation.' },
      // # ── Verbs ──
      { word: 'migrate', wordClass: 'verb', level: 'B2', verbForms: { v1: 'migrate', v2: 'migrated', v3: 'migrated' }, meaning: 'To move from one region to another, usually with the seasons.', context: 'Bird movements, fish spawning, and human migration.', example: 'Millions of wildebeest migrate across the Serengeti each year.', explanation: 'The noun is "migration". Collocations: "migrate south/north", "migratory birds/patterns". Also for people: "migrate to another country" (move permanently). "Immigration" = coming into a country; "emigration" = leaving a country. In tech: "migrate data" = transfer to a new system.' },
      { word: 'hibernate', wordClass: 'verb', level: 'B2', verbForms: { v1: 'hibernate', v2: 'hibernated', v3: 'hibernated' }, meaning: 'To spend the winter in a state of deep sleep to conserve energy.', context: 'Animal behaviour, biology, and seasonal patterns.', example: 'Bears hibernate during winter, surviving on fat stored in their bodies.', explanation: 'The noun is "hibernation". Animals that hibernate: bears, hedgehogs, bats, dormice, some frogs. Not all "winter sleepers" truly hibernate — bears actually enter "torpor" (lighter than true hibernation). Figurative: "I just want to hibernate all winter" (= stay home and sleep).' },
      { word: 'hatch', wordClass: 'verb', level: 'B1', verbForms: { v1: 'hatch', v2: 'hatched', v3: 'hatched' }, meaning: 'To emerge from an egg; or to keep an egg warm until the young animal inside comes out.', context: 'Birds, reptiles, insects, and incubation.', example: 'The chicks hatched after 21 days of incubation.', explanation: 'Can be used both ways: "The eggs hatched" (intransitive) / "The hen hatched the eggs" (transitive). Collocations: "hatch a plan/plot" (figurative = secretly develop a scheme), "hatchling" (a newly hatched animal), "Don\'t count your chickens before they hatch" (proverb — don\'t assume success before it happens).' },
      { word: 'graze', wordClass: 'verb', level: 'B2', verbForms: { v1: 'graze', v2: 'grazed', v3: 'grazed' }, meaning: 'To eat grass in a field (of cattle, sheep, etc.).', context: 'Farming, livestock, and pastoral landscapes.', example: 'Sheep were grazing peacefully in the green fields.', explanation: 'Collocations: "grazing land/cattle", "overgrazing" (too many animals eating the grass, causing soil damage). Also means a minor skin injury: "She grazed her knee when she fell." And modern eating: "I tend to graze throughout the day" (= eat small amounts frequently).' },
      { word: 'hunt', wordClass: 'verb', level: 'A2', verbForms: { v1: 'hunt', v2: 'hunted', v3: 'hunted' }, meaning: 'To chase and kill wild animals for food or sport.', context: 'Wildlife, survival, tradition, and conservation debates.', example: 'Wolves hunt in packs, working together to bring down large prey.', explanation: 'Also a noun: "fox hunt", "treasure hunt". The person is a "hunter". Collocations: "hunt for food/sport", "hunting season", "big-game hunting" (hunting large animals — controversial). "Hunt for" also means search: "I\'m hunting for a new flat."' },
      { word: 'stalk', wordClass: 'verb', level: 'B2', verbForms: { v1: 'stalk', v2: 'stalked', v3: 'stalked' }, meaning: 'To follow prey quietly and carefully before attacking.', context: 'Animal hunting behaviour and criminal following.', example: 'The leopard stalked its prey through the tall grass for twenty minutes.', explanation: 'Also means: to follow and harass a person obsessively — a crime called "stalking". A "stalker" = person who stalks someone. Collocations: "stalk prey/victims", "stalking behaviour". The noun "stalk" also means the stem of a plant.' },
      { word: 'roar', wordClass: 'verb', level: 'B1', verbForms: { v1: 'roar', v2: 'roared', v3: 'roared' }, meaning: 'To make a deep, loud, powerful sound (especially lions).', context: 'Animal sounds, engines, and loud laughter.', example: 'The lion roared so loudly that we could hear it from the other side of the park.', explanation: 'Also a noun: "the roar of the crowd/engine/lion". Animal sounds: dogs bark, cats meow/purr, birds chirp/tweet, horses neigh, cows moo, sheep bleat, pigs oink/squeal. "Roar with laughter" = laugh extremely loudly.' },
      { word: 'evolve', wordClass: 'verb', level: 'B2', verbForms: { v1: 'evolve', v2: 'evolved', v3: 'evolved' }, meaning: 'To develop gradually over many generations through natural selection.', context: 'Biology, adaptation, and gradual change.', example: 'Humans evolved from earlier primate species over millions of years.', explanation: 'The noun is "evolution" and the adjective is "evolutionary". Collocations: "evolve over time", "evolve from/into", "evolutionary process/theory/biology". Charles Darwin\'s "On the Origin of Species" (1859) introduced the theory. Also general: "The plan evolved over the weeks" (= gradually changed).' },
      { word: 'adapt', wordClass: 'verb', level: 'B1', verbForms: { v1: 'adapt', v2: 'adapted', v3: 'adapted' }, meaning: 'To change in order to suit different conditions or environments.', context: 'Biology, personal development, and coping with change.', example: 'Desert animals have adapted to survive with very little water.', explanation: 'The noun is "adaptation". Collocations: "adapt to change/circumstances/environment", "well-adapted to", "adaptation of" (a book made into a film). Different from "adopt" (= take on, accept — "adopt a child/approach"). This is a common confusion.' },
      // # ── Adjectives ──
      { word: 'endangered', wordClass: 'adjective', level: 'B2', meaning: 'At serious risk of extinction.', context: 'Conservation, wildlife protection, and environmental campaigns.', example: 'The giant panda is no longer classified as endangered thanks to conservation efforts.', explanation: 'Collocations: "endangered species/animals/habitats", "critically endangered" (= very close to extinction). "IUCN Red List" classifies species: Least Concern → Near Threatened → Vulnerable → Endangered → Critically Endangered → Extinct in the Wild → Extinct.' },
      { word: 'domestic', wordClass: 'adjective', level: 'B1', meaning: 'Kept as a pet or on a farm; not wild.', context: 'Animal types, farming, and home life.', example: 'Cats were first domesticated in the Near East about 10,000 years ago.', explanation: 'Collocations: "domestic animal/pet/cat", "domestic flight" (within the same country), "domestic violence" (abuse within a household). The verb is "domesticate": "Humans domesticated dogs thousands of years ago." Opposite (for animals): "wild" or "feral" (= was domestic but returned to the wild).' },
      { word: 'nocturnal', wordClass: 'adjective', level: 'B2', meaning: 'Active during the night rather than the day.', context: 'Animal behaviour and nature observation.', example: 'Owls are nocturnal birds — they hunt at night and sleep during the day.', explanation: 'Opposite: "diurnal" (active during the day — less commonly used). Collocations: "nocturnal animals/habits/activity". Nocturnal animals include: owls, bats, foxes, hedgehogs, moths. Humorous: "I\'m quite nocturnal — I do my best work after midnight."' },
      { word: 'venomous', wordClass: 'adjective', level: 'C1', meaning: 'Producing venom (poison) that is injected through a bite or sting.', context: 'Snake safety, dangerous animals, and biology.', example: 'The black mamba is one of the most venomous snakes in the world.', explanation: '"Venomous" vs "poisonous": "venomous" = injects poison (snakes bite you); "poisonous" = harmful if you eat/touch it (some frogs are poisonous). This distinction matters in biology. Collocations: "venomous snake/spider/bite/sting", "venom" (noun — the poison itself).' },
      { word: 'carnivorous', wordClass: 'adjective', level: 'B2', meaning: 'Eating meat; feeding on other animals.', context: 'Animal diets and food chain classification.', example: 'Lions are carnivorous animals that rely entirely on hunting for food.', explanation: 'Diet classifications: "carnivore" (eats meat), "herbivore" (eats plants), "omnivore" (eats both). Adjective forms: "carnivorous/herbivorous/omnivorous". Collocations: "carnivorous animal/plant" (yes, some plants eat insects — like Venus flytraps). "Carnivore" is also the noun.' },
      // # ── Adverbs ──
      { word: 'instinctively', wordClass: 'adverb', level: 'B2', meaning: 'In a way that is done naturally without thinking; based on instinct.', context: 'Animal behaviour and intuitive human reactions.', example: 'The deer instinctively froze when it sensed danger nearby.', explanation: 'The adjective is "instinctive": "an instinctive reaction/response." Collocations: "instinctively know/feel/react/understand", "act instinctively". Used for both animals (true instinct) and humans (gut feelings): "I instinctively knew something was wrong."' },
      { word: 'predominantly', wordClass: 'adverb', level: 'B2', meaning: 'Mainly; for the greater part.', context: 'Describing the main type in a group or ecosystem.', example: 'The forest is predominantly made up of oak and beech trees.', explanation: 'Already covered in Social Issues — used here for natural descriptions. Collocations: "predominantly found/located/made up of". A more formal alternative to "mostly" or "mainly". Very useful in academic and descriptive writing.' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 25. COMMUNICATION & LANGUAGE
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'communication',
    name: 'Communication & Language',
    description: 'Vocabulary for speaking, writing, presenting, persuading, and understanding discourse.',
    icon: '💬',
    entries: [
      // # ── Nouns ──
      { word: 'accent', wordClass: 'noun', level: 'A2', meaning: 'A way of pronouncing words that shows which country, region, or social class a person comes from.', context: 'Language learning, identity, and first impressions.', example: 'She speaks English fluently but with a slight French accent.', explanation: 'Different from "dialect" (includes different vocabulary and grammar, not just pronunciation). Collocations: "strong/slight/regional/foreign accent", "speak with an accent", "lose your accent" (= your accent becomes less noticeable over time). "Accentuate" (verb) = to emphasise.' },
      { word: 'dialect', wordClass: 'noun', level: 'B2', meaning: 'A form of a language spoken in a particular region, with its own vocabulary, grammar, and pronunciation.', context: 'Linguistics, regional identity, and language study.', example: 'Scots English is a dialect with its own unique words and grammar patterns.', explanation: 'Different from "accent" (just pronunciation). A dialect has different words and grammar too. Collocations: "regional/local dialect", "speak in dialect", "dialectal differences". "Standard English" is a dialect too — just the one used in official contexts. Every speaker has a dialect.' },
      { word: 'fluency', wordClass: 'noun', level: 'B1', meaning: 'The ability to speak or write a language easily, accurately, and naturally.', context: 'Language learning, job requirements, and communication skills.', example: 'After living in Japan for five years, she achieved fluency in Japanese.', explanation: 'The adjective is "fluent": "She\'s fluent in three languages." Collocations: "achieve/reach fluency", "fluency in English", "speak fluently". In language teaching, "fluency" (speaking smoothly) is often contrasted with "accuracy" (speaking correctly) — both are important.' },
      { word: 'jargon', wordClass: 'noun', level: 'B2', meaning: 'Special words or expressions used by a particular profession or group that are difficult for others to understand.', context: 'Professional communication and plain language initiatives.', example: 'The legal document was full of technical jargon that ordinary people couldn\'t understand.', explanation: 'Uncountable. Usually negative — implies unnecessarily complicated language. Collocations: "technical/legal/medical/business jargon", "full of jargon", "jargon-free" (= written in plain language). "Plain English" movements campaign against jargon in official documents.' },
      { word: 'metaphor', wordClass: 'noun', level: 'B2', meaning: 'A figure of speech that describes something by saying it IS something else.', context: 'Literature, speeches, and everyday language.', example: '"Life is a journey" is a common metaphor.', explanation: 'Different from "simile" (uses "like" or "as": "Life is LIKE a journey"). "Metaphorical" (adjective): "She didn\'t literally mean the office was a zoo — she was being metaphorical." Collocations: "mixed metaphor" (confusing two metaphors: "We\'ll burn that bridge when we come to it").' },
      { word: 'rhetoric', wordClass: 'noun', level: 'C1', meaning: 'The art of effective or persuasive speaking or writing.', context: 'Politics, debate, and academic analysis.', example: 'The politician\'s rhetoric was powerful but lacked substance.', explanation: 'Can be positive (skill of persuasion) or negative (empty words without action). Collocations: "political/empty/powerful rhetoric", "rhetorical question" (a question asked for effect, not expecting an answer: "Is the Pope Catholic?"). "Rhetorical" (adjective).' },
      { word: 'slang', wordClass: 'noun', level: 'B1', meaning: 'Very informal words and expressions used mainly in speech, often by particular groups.', context: 'Casual conversation, youth culture, and language change.', example: 'Every generation has its own slang — my parents don\'t understand half of what I say.', explanation: 'Uncountable. Collocations: "use/speak slang", "street/internet/teenage slang", "slang term/word/expression". Slang is informal and often temporary — many slang words disappear within a generation. Some become standard: "mob", "fun", "clever" were all once considered slang.' },
      { word: 'pronunciation', wordClass: 'noun', level: 'A2', meaning: 'The way in which a word or language is spoken.', context: 'Language learning, dictionaries, and communication clarity.', example: 'Her pronunciation has really improved since she started practising with native speakers.', explanation: 'Common spelling mistake: "pronunciation" (NOT "pronounciation"). The verb is "pronounce." Collocations: "correct/incorrect pronunciation", "pronunciation guide", "mispronounce" (= say wrongly). IPA (International Phonetic Alphabet) is the system used to show pronunciation in dictionaries.' },
      { word: 'gesture', wordClass: 'noun', level: 'B1', meaning: 'A movement of the hands, head, or body to express an idea or feeling.', context: 'Non-verbal communication and body language.', example: 'He made a welcoming gesture, inviting us to sit down.', explanation: 'Also a verb: "She gestured towards the door." Collocations: "hand gesture", "a nice/kind gesture" (= a thoughtful action), "gesture of goodwill" (= a friendly action to improve a relationship). Some gestures mean different things in different cultures — the "thumbs up" is offensive in some countries.' },
      { word: 'tone', wordClass: 'noun', level: 'B1', meaning: 'The quality of someone\'s voice expressing their mood or attitude.', context: 'Conversations, writing, and emotional expression.', example: 'She spoke in a calm tone, but her anger was obvious from her choice of words.', explanation: 'Collocations: "tone of voice", "serious/casual/sarcastic/friendly tone", "set the tone" (= establish the mood), "tone-deaf" (= can\'t distinguish musical pitch, or figuratively — insensitive to a situation). In writing: "the formal/informal tone of the essay".' },
      { word: 'feedback', wordClass: 'noun', level: 'B1', meaning: 'Information or opinions given about someone\'s work or behaviour to help them improve.', context: 'Education, workplace, and product reviews.', example: 'The teacher gave detailed feedback on every student\'s essay.', explanation: 'Uncountable — "some feedback" not "a feedback" or "feedbacks". Collocations: "give/receive/provide feedback", "positive/negative/constructive feedback" (= helpful criticism), "feedback form/loop". "Constructive" feedback suggests improvements rather than just pointing out problems.' },
      // # ── Verbs ──
      { word: 'persuade', wordClass: 'verb', level: 'B1', verbForms: { v1: 'persuade', v2: 'persuaded', v3: 'persuaded' }, meaning: 'To cause someone to do or believe something through reasoning or argument.', context: 'Sales, debates, relationships, and decision-making.', example: 'She finally persuaded him to see a doctor about his persistent cough.', explanation: 'The noun is "persuasion". Collocations: "persuade someone to do something", "powers of persuasion" (= ability to convince people). Different from "convince" — "persuade" leads to ACTION (persuade someone to do), "convince" leads to BELIEF (convince someone that). "Persuasive" (adjective): "a persuasive argument".' },
      { word: 'emphasise', wordClass: 'verb', level: 'B1', verbForms: { v1: 'emphasise', v2: 'emphasised', v3: 'emphasised' }, meaning: 'To give special importance or attention to something.', context: 'Speeches, writing, and making key points clear.', example: 'The report emphasises the need for urgent action on climate change.', explanation: 'British: "emphasise". American: "emphasize". The noun is "emphasis" (plural: "emphases"). Collocations: "emphasise the importance/need/fact", "place/put emphasis on", "with emphasis". In speaking, you emphasise by stressing certain words. "Emphatic" (adjective) = forceful and clear.' },
      { word: 'clarify', wordClass: 'verb', level: 'B2', verbForms: { v1: 'clarify', v2: 'clarified', v3: 'clarified' }, meaning: 'To make something clearer and easier to understand.', context: 'Misunderstandings, official statements, and learning.', example: 'Could you clarify what you mean by "flexible working hours"?', explanation: 'The noun is "clarification". Collocations: "clarify a point/position/statement", "seek/ask for clarification", "I\'d like to clarify" (= let me explain more clearly). Very useful in meetings, emails, and exams: "Could you clarify the question, please?"' },
      { word: 'interrupt', wordClass: 'verb', level: 'B1', verbForms: { v1: 'interrupt', v2: 'interrupted', v3: 'interrupted' }, meaning: 'To stop someone from speaking by saying or doing something.', context: 'Conversations, meetings, and politeness.', example: 'I\'m sorry to interrupt, but there\'s an urgent phone call for you.', explanation: 'The noun is "interruption". Collocations: "interrupt someone", "sorry to interrupt", "without interruption" (= continuously), "constant interruptions". Cultural note: attitudes to interrupting vary — some cultures see it as rude, others see it as engaged conversation.' },
      { word: 'summarise', wordClass: 'verb', level: 'B1', verbForms: { v1: 'summarise', v2: 'summarised', v3: 'summarised' }, meaning: 'To give a brief statement of the main points of something.', context: 'Academic writing, meetings, and news reports.', example: 'Can you summarise the main findings of the report in two sentences?', explanation: 'British: "summarise". American: "summarize". The noun is "summary". Collocations: "to summarise" (= in summary), "summarise the key/main points", "brief/executive summary". An "executive summary" = a short overview at the beginning of a long document for busy readers.' },
      { word: 'exaggerate', wordClass: 'verb', level: 'B1', verbForms: { v1: 'exaggerate', v2: 'exaggerated', v3: 'exaggerated' }, meaning: 'To describe something as larger, better, or worse than it really is.', context: 'Storytelling, arguments, and dramatic effect.', example: 'He always exaggerates — that fish he caught was not "as big as a shark"!', explanation: 'The noun is "exaggeration". Collocations: "grossly/wildly exaggerated", "exaggerate the importance/danger/size". "Without exaggeration" = honestly, truly. "Understate" is the opposite — describe as less than it is. "Hyperbole" (noun) = intentional extreme exaggeration for effect.' },
      { word: 'imply', wordClass: 'verb', level: 'B2', verbForms: { v1: 'imply', v2: 'implied', v3: 'implied' }, meaning: 'To suggest something without saying it directly.', context: 'Indirect communication, subtext, and reading between the lines.', example: 'Are you implying that I\'m not qualified for this position?', explanation: 'The noun is "implication". IMPORTANT distinction: "imply" = the speaker suggests; "infer" = the listener concludes. "She implied she was unhappy" (she suggested it). "I inferred she was unhappy" (I concluded it from clues). Many native speakers confuse these. Collocations: "strongly imply", "implied meaning".' },
      // # ── Adjectives ──
      { word: 'fluent', wordClass: 'adjective', level: 'B1', meaning: 'Able to speak or write a language easily, smoothly, and accurately.', context: 'Language ability, job applications, and communication skills.', example: 'She\'s fluent in English, Spanish, and Mandarin.', explanation: 'Collocations: "fluent in a language", "fluent speaker/reader", "speak fluently" (adverb). CEFR levels: A1-A2 = beginner, B1-B2 = intermediate, C1-C2 = fluent/proficient. You can be "fluent" without being "perfect" — fluency is about smooth communication, not zero mistakes.' },
      { word: 'articulate', wordClass: 'adjective', level: 'C1', meaning: 'Able to express ideas clearly, fluently, and effectively in words.', context: 'Praising someone\'s communication skills.', example: 'She\'s very articulate — she can explain complex ideas in simple terms.', explanation: 'Pronunciation: adjective = ar-TIK-yuh-lut, verb = ar-TIK-yuh-LATE. As a verb: "He struggled to articulate his feelings." Collocations: "articulate speaker/person", "clearly articulated", "well-articulated argument". Very positive — implies intelligence and clarity.' },
      { word: 'concise', wordClass: 'adjective', level: 'B2', meaning: 'Expressing much in few words; brief but comprehensive.', context: 'Writing quality, summaries, and communication skills.', example: 'A good abstract should be clear and concise — no more than 250 words.', explanation: 'A compliment in academic and professional writing. Collocations: "clear and concise", "concise summary/description/explanation". The noun is "conciseness" or "concision". Opposite: "verbose" (= using too many words), "wordy", "long-winded". "Be concise" is common exam advice.' },
      { word: 'ambiguous', wordClass: 'adjective', level: 'B2', meaning: 'Having more than one possible meaning; unclear or open to interpretation.', context: 'Legal contracts, exam questions, and miscommunication.', example: 'The wording of the contract was ambiguous, leading to a dispute over its meaning.', explanation: 'The noun is "ambiguity". Collocations: "ambiguous statement/language/response", "deliberately/unintentionally ambiguous". In law, ambiguous contracts often favour the party who didn\'t write them. Opposite: "unambiguous" (= perfectly clear). "Disambiguate" = to remove ambiguity.' },
      { word: 'eloquent', wordClass: 'adjective', level: 'C1', meaning: 'Speaking or writing in a fluent, persuasive, and moving way.', context: 'Praising speeches, writers, and powerful communication.', example: 'Martin Luther King Jr. was one of the most eloquent speakers in history.', explanation: 'Stronger than "articulate" — "eloquent" implies beauty and emotional power in speech. The noun is "eloquence". Collocations: "eloquent speech/speaker/argument/tribute". "Eloquently" (adverb): "She eloquently defended her position." Reserved for genuinely impressive communication.' },
      // # ── Adverbs ──
      { word: 'explicitly', wordClass: 'adverb', level: 'B2', meaning: 'In a clear, direct way that leaves no room for confusion or doubt.', context: 'Instructions, contracts, and clear communication.', example: 'The rules explicitly state that mobile phones must be turned off during the exam.', explanation: 'The adjective is "explicit" (opposite: "implicit" = suggested but not directly stated). Collocations: "explicitly state/mention/say/forbid", "explicit instructions/content". "Explicit content" in media = containing graphic material (language, violence, sexual content).' },
      { word: 'sarcastically', wordClass: 'adverb', level: 'B2', meaning: 'In a way that uses irony to mock or show contempt.', context: 'Humour, criticism, and tone of voice.', example: '"Oh, what a wonderful idea," she said sarcastically, rolling her eyes.', explanation: 'The adjective is "sarcastic" and the noun is "sarcasm". Sarcasm means saying the OPPOSITE of what you mean: "Nice weather!" (when it\'s raining). Hard to detect in writing without context. Collocations: "sarcastic comment/remark/tone", "dripping with sarcasm". British English is famous for sarcasm.' },
      { word: 'vaguely', wordClass: 'adverb', level: 'B2', meaning: 'In an unclear, imprecise way; slightly or somewhat.', context: 'Unclear communication and partial memories.', example: 'I vaguely remember meeting her at a conference, but I can\'t recall her name.', explanation: 'The adjective is "vague" (opposite: "specific" or "precise"). Collocations: "vaguely remember/familiar/aware", "vague idea/description/answer". "Vague" answers are frustrating: "When will it be ready?" "Soon." "How much will it cost?" "Not too much." These are vague responses.' },
    ],
  },
]
