// # ═══════════════════════════════════════════════════════════════════════════
// # VOCABULARY REFERENCE DATA — Part 2: Additional Fields
// # ═══════════════════════════════════════════════════════════════════════════
// # All content is original and copyright-free.
// # 10 additional fields of life with comprehensive word coverage.

import type { VocabField } from './types'

export const VOCAB_FIELDS_2: VocabField[] = [

  // # ═══════════════════════════════════════════════════════════════════
  // # 11. FOOD & COOKING
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'food-cooking',
    name: 'Food & Cooking',
    description: 'Vocabulary for ingredients, cooking methods, kitchen tools, diets, and dining out.',
    icon: '🍳',
    entries: [
      { word: 'ingredient', wordClass: 'noun', level: 'A2', meaning: 'Any of the foods or substances that are combined to make a particular dish.', context: 'Recipes, grocery shopping, and meal preparation.', example: 'The main ingredients for this soup are onions, potatoes, and cream.', explanation: 'Collocations: "key/main/essential ingredient", "fresh ingredients", "list of ingredients" (on food packaging). Also used figuratively: "Hard work is a key ingredient of success." Plural is almost always used when talking about cooking.' },
      { word: 'recipe', wordClass: 'noun', level: 'A2', meaning: 'A set of instructions for preparing a particular dish, including a list of ingredients.', context: 'Cookbooks, food blogs, and sharing cooking methods.', example: 'This recipe has been in my family for three generations.', explanation: 'Pronunciation: RES-ih-pee (NOT reh-SEEP). Don\'t confuse with "receipt" (proof of purchase). Collocations: "follow a recipe", "traditional/family recipe", "recipe book". Figurative: "a recipe for disaster/success" = a combination likely to produce that result.' },
      { word: 'portion', wordClass: 'noun', level: 'B1', meaning: 'The amount of food served to one person.', context: 'Restaurant menus, nutrition, and health discussions.', example: 'The portions at this restaurant are enormous — I couldn\'t finish mine.', explanation: '"Portion" = one serving of food. "Portion size" = how big the serving is. Collocations: "generous/large/small portion", "portion control" (managing how much you eat), "a portion of chips/rice/salad". Different from "serving" (a measured amount recommended on packaging) though they overlap.' },
      { word: 'cuisine', wordClass: 'noun', level: 'B2', meaning: 'A style of cooking characteristic of a particular country or region.', context: 'Restaurant reviews, food culture, and travel.', example: 'Thai cuisine is famous for balancing sweet, sour, salty, and spicy flavours.', explanation: 'From French — pronounced kwih-ZEEN. More formal/refined than "food" or "cooking". Collocations: "French/Italian/Japanese cuisine", "local cuisine", "haute cuisine" (high-end French cooking), "fusion cuisine" (blending two food traditions). You wouldn\'t say "British cuisine" for fish and chips — "British food" sounds more natural for casual dishes.' },
      { word: 'simmer', wordClass: 'verb', level: 'B1', verbForms: { v1: 'simmer', v2: 'simmered', v3: 'simmered' }, meaning: 'To cook food gently in liquid just below boiling point.', context: 'Following recipes and cooking instructions.', example: 'Reduce the heat and let the sauce simmer for 20 minutes.', explanation: '"Simmer" = small bubbles, gentle cooking. Different from "boil" (large, vigorous bubbles, 100°C). Cooking instruction: "bring to the boil, then reduce to a simmer." Also figurative: "simmering anger/tension" = anger that is present but not yet expressed, building slowly.' },
      { word: 'chop', wordClass: 'verb', level: 'A2', verbForms: { v1: 'chop', v2: 'chopped', v3: 'chopped' }, meaning: 'To cut food into pieces using a knife or sharp tool.', context: 'Preparing vegetables, herbs, and ingredients.', example: 'Finely chop the onions and garlic before adding them to the pan.', explanation: 'Different cutting words: "chop" (rough pieces), "dice" (small cubes), "slice" (thin flat pieces), "mince" (very tiny pieces), "grate" (shred using a grater). Collocations: "finely/roughly chopped", "chop into pieces", "chopping board" (the surface you cut on).' },
      { word: 'grill', wordClass: 'verb', level: 'A2', verbForms: { v1: 'grill', v2: 'grilled', v3: 'grilled' }, meaning: 'To cook food by direct heat from above or below, or on metal bars over a flame.', context: 'Barbecues, restaurants, and healthy cooking.', example: 'We grilled steaks and vegetables on the barbecue last weekend.', explanation: 'British "grill" = cook under heat from above (inside an oven). American "grill" = cook on metal bars over a flame (British call this a "barbecue"). Other cooking methods: "roast" (oven, dry heat), "fry" (pan, with oil), "steam" (over boiling water), "bake" (oven, usually for bread/cakes). Also means to question intensely: "The police grilled the suspect."' },
      { word: 'bland', wordClass: 'adjective', level: 'B1', meaning: 'Lacking strong flavour; tasteless and uninteresting.', context: 'Describing disappointing food or criticising cooking.', example: 'The soup was rather bland — it needed more salt and herbs.', explanation: 'Negative — implies boring food. Opposite: "flavourful", "tasty", "delicious". Related food adjectives: "savoury" (salty, not sweet), "tangy" (sharp, acidic), "rich" (heavy, full of cream/butter), "spicy" (hot, with chilli), "bitter" (like dark chocolate or coffee). Also used figuratively: "a bland personality" = boring and uninteresting.' },
      { word: 'nutritious', wordClass: 'adjective', level: 'B1', meaning: 'Full of nutrients; good for your health and body.', context: 'Health discussions, diet planning, and food marketing.', example: 'A nutritious breakfast gives you energy for the whole morning.', explanation: '"Nutritious" = contains good nutrients (vitamins, minerals, protein). More formal than "healthy food". The noun is "nutrition" (the science of food and health), "nutrient" (a substance that provides nourishment). Collocations: "nutritious meal/diet/food", "nutritional value/information" (on packaging).' },
      { word: 'organic', wordClass: 'adjective', level: 'B1', meaning: 'Produced without artificial chemicals, pesticides, or genetic modification.', context: 'Grocery shopping, farming, and environmental discussions.', example: 'She only buys organic vegetables from the local farmers\' market.', explanation: 'In food: "organic" = grown naturally without synthetic chemicals. Certified by official bodies (Soil Association in UK, USDA Organic in US). Collocations: "organic farming/produce/food", "certified organic", "organic shop/market". In chemistry: "organic chemistry" = chemistry of carbon compounds (completely different meaning).' },
      { word: 'appetising', wordClass: 'adjective', level: 'B2', meaning: 'Looking or smelling attractive and making you want to eat.', context: 'Describing food presentation and first impressions.', example: 'The dish was beautifully presented — very appetising.', explanation: 'British: "appetising", American: "appetizing". Related: "appetite" (desire to eat), "appetiser/appetizer" (small dish before the main course). Opposite: "unappetising" (looks unattractive). Collocations: "appetising aroma/smell", "appetising display". More sophisticated than "yummy" or "looks delicious".' },
      { word: 'thoroughly', wordClass: 'adverb', level: 'B1', meaning: 'Completely and carefully (in cooking: making sure something is fully done).', context: 'Food safety instructions and cooking guidance.', example: 'Make sure the chicken is thoroughly cooked before serving.', explanation: 'In cooking, "thoroughly" is critical for food safety: "thoroughly wash vegetables", "thoroughly cooked" (no pink inside for poultry). Also: "thoroughly mix/stir/blend" = combine completely. General meaning: "I thoroughly enjoyed the meal" (= really, completely enjoyed it).' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 12. SPORTS & FITNESS
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'sports-fitness',
    name: 'Sports & Fitness',
    description: 'Vocabulary for exercise, competition, training, and physical wellbeing.',
    icon: '⚽',
    entries: [
      { word: 'tournament', wordClass: 'noun', level: 'B1', meaning: 'A series of competitive matches leading to an overall winner.', context: 'Organised sports competitions like tennis, football, and chess.', example: 'She won the regional tennis tournament for the third year running.', explanation: 'Different from a "match/game" (single event) or a "league" (season-long, points-based). Collocations: "tournament bracket", "knockout tournament" (lose once and you\'re out), "round-robin tournament" (everyone plays everyone). Also used in gaming: "esports tournament".' },
      { word: 'opponent', wordClass: 'noun', level: 'B1', meaning: 'A person or team you compete against in a sport or contest.', context: 'Describing competitors in sports, debates, and elections.', example: 'Her opponent in the final was the world number one.', explanation: 'In sport: the person or team on the other side. In debates/politics: someone who disagrees. "Opponent" is neutral — "rival" is more personal (implies a long-standing competition). "Adversary" is more formal and serious. Collocations: "face/beat/defeat an opponent", "worthy opponent", "political opponent".' },
      { word: 'stamina', wordClass: 'noun', level: 'B2', meaning: 'The physical or mental ability to sustain effort over a long period.', context: 'Endurance sports, fitness training, and demanding work.', example: 'Marathon runners need incredible stamina to complete the race.', explanation: 'Uncountable — never "a stamina" or "staminas". Collocations: "build/develop stamina", "physical/mental stamina", "lack of stamina". Related: "endurance" (similar, but more about surviving hardship), "resilience" (bouncing back after difficulty). "It takes stamina to..." = it requires sustained effort.' },
      { word: 'sprint', wordClass: 'verb', level: 'B1', verbForms: { v1: 'sprint', v2: 'sprinted', v3: 'sprinted' }, meaning: 'To run at full speed over a short distance.', context: 'Track and field athletics, and any sudden burst of running.', example: 'He sprinted the last 100 metres to cross the finish line first.', explanation: 'Also a noun: "the 100-metre sprint". Speed spectrum: walk → jog → run → sprint. Collocations: "sprint finish", "sprint towards/across/down", "sprinter" (the athlete). In tech/project management: a "sprint" is a short period of focused work (from Agile methodology).' },
      { word: 'stretch', wordClass: 'verb', level: 'A2', verbForms: { v1: 'stretch', v2: 'stretched', v3: 'stretched' }, meaning: 'To extend your body or limbs to full length, especially before or after exercise.', context: 'Warm-ups, cool-downs, and flexibility exercises.', example: 'Always stretch before running to avoid muscle injuries.', explanation: 'Also a noun: "Do some stretches before you start." Physical: "stretch your arms/legs/back". Figurative: "stretch the budget" (make money last), "stretch the truth" (slightly exaggerate), "at a stretch" (barely possible). Collocations: "stretch out", "stretching exercises", "muscle stretch".' },
      { word: 'defeat', wordClass: 'verb', level: 'B1', verbForms: { v1: 'defeat', v2: 'defeated', v3: 'defeated' }, meaning: 'To win against someone in a competition, battle, or argument.', context: 'Sports results, elections, and military contexts.', example: 'Brazil defeated Germany 2-0 in the semi-final.', explanation: 'Also a noun: "a crushing/humiliating defeat" vs "a narrow defeat" (lost by a small margin). Stronger than "beat" — "defeat" implies a more decisive victory. Collocations: "suffer a defeat", "admit defeat" (accept you have lost), "defeat an opponent/team/army". "Undefeated" = never lost.' },
      { word: 'intensive', wordClass: 'adjective', level: 'B2', meaning: 'Involving a lot of effort, activity, or attention concentrated in a short period.', context: 'Training programmes, courses, and medical care.', example: 'The team followed an intensive training programme for six weeks.', explanation: '"Intensive" = concentrated and demanding. Collocations: "intensive training/course/care", "intensive farming" (maximising production from land), "labour-intensive" (requiring a lot of workers), "capital-intensive" (requiring a lot of money). ICU = Intensive Care Unit (hospital). Don\'t confuse with "extensive" (covering a wide area).' },
      { word: 'competitive', wordClass: 'adjective', level: 'B2', meaning: 'Involving or characterised by competition; having a strong desire to win.', context: 'Describing athletes, markets, and personal traits.', example: 'She\'s incredibly competitive — she hates losing at anything.', explanation: 'Two uses: 1) About people: "a competitive person" (wants to win); 2) About markets/prices: "competitive prices" (as good as rivals). The noun is "competition" (the event) and "competitiveness" (the quality). Adverb: "competitively priced". "Competitive edge/advantage" = something that makes you better than rivals.' },
      { word: 'consistently', wordClass: 'adverb', level: 'B2', meaning: 'In a way that stays the same over time; reliably and regularly.', context: 'Evaluating athletic performance and training habits.', example: 'She has consistently improved her personal best times this season.', explanation: 'The adjective is "consistent" (opposite: "inconsistent"). In sport: "consistent performance" = reliable, no big ups and downs. Collocations: "consistently high/strong/good", "consistently perform/deliver/achieve". Different from "constantly" (= all the time, without stopping) — "consistently" = the same quality each time.' },
      { word: 'agile', wordClass: 'adjective', level: 'B2', meaning: 'Able to move quickly and easily with good coordination.', context: 'Describing athletes, dancers, and physical capabilities.', example: 'Gymnasts need to be extremely agile and flexible.', explanation: 'Physical: quick, nimble, well-coordinated. The noun is "agility": "agility training" (exercises to improve quickness). Also used in business: "Agile methodology" (a project management approach using short sprints and adaptability). Collocations: "mentally/physically agile", "agile and flexible".' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 13. ENTERTAINMENT & MEDIA
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'entertainment',
    name: 'Entertainment & Media',
    description: 'Vocabulary for movies, music, TV, social media, gaming, and popular culture.',
    icon: '🎬',
    entries: [
      { word: 'audience', wordClass: 'noun', level: 'B1', meaning: 'The group of people watching, listening to, or reading something.', context: 'Live performances, broadcasts, and content creation.', example: 'The audience gave the performers a standing ovation.', explanation: 'Can be singular or plural: "The audience was silent" (one group) or "The audience were clapping" (individuals). Collocations: "target audience" (intended viewers), "live audience", "audience member", "audience participation", "captive audience" (people who have no choice but to listen).' },
      { word: 'genre', wordClass: 'noun', level: 'B2', meaning: 'A category of art, music, film, or literature with shared characteristics.', context: 'Discussing types of movies, books, or music.', example: 'Horror is my favourite genre, but I also enjoy science fiction.', explanation: 'From French — pronounced ZHON-ruh (not "jen-ree"). Film genres: action, comedy, drama, horror, thriller, romance, sci-fi, documentary. Music genres: pop, rock, jazz, classical, hip-hop, electronic. Collocations: "film/music/literary genre", "genre fiction" (commercial fiction like crime or romance), "cross-genre" (mixing genres).' },
      { word: 'sequel', wordClass: 'noun', level: 'B2', meaning: 'A film, book, or game that continues the story from a previous one.', context: 'Film franchises, book series, and gaming.', example: 'The sequel was even better than the original film.', explanation: '"Sequel" = the next part of the story. "Prequel" = a story set BEFORE the original. "Trilogy" = three connected works. "Franchise" = a series of related products (Marvel franchise). Collocations: "direct sequel" (continues immediately), "long-awaited sequel", "sequel to". A "spin-off" is a new work based on a character from the original.' },
      { word: 'broadcast', wordClass: 'verb', level: 'B2', verbForms: { v1: 'broadcast', v2: 'broadcast', v3: 'broadcast' }, meaning: 'To transmit a programme or information by radio, television, or internet.', context: 'News, live events, and media production.', example: 'The match will be broadcast live on national television.', explanation: 'Note: past tense is "broadcast" (NOT "broadcasted" — though "broadcasted" is sometimes used). Also a noun: "a live broadcast", "a radio broadcast". The person is a "broadcaster" and the company is a "broadcasting corporation" (BBC = British Broadcasting Corporation). Modern use extends to streaming/internet.' },
      { word: 'stream', wordClass: 'verb', level: 'B1', verbForms: { v1: 'stream', v2: 'streamed', v3: 'streamed' }, meaning: 'To watch or listen to media content over the internet without downloading it.', context: 'Online entertainment, music services, and live content.', example: 'Most people stream music now rather than buying physical albums.', explanation: '"Stream" = play content in real time from the internet. "Streaming service" = Netflix, Spotify, Disney+. Different from "download" (save to device). "Livestream" = broadcast live over the internet. Also a noun: "a stream of data/consciousness". The noun "streamer" = someone who broadcasts themselves (gaming, lifestyle).' },
      { word: 'release', wordClass: 'verb', level: 'B1', verbForms: { v1: 'release', v2: 'released', v3: 'released' }, meaning: 'To make a film, song, game, or product available to the public.', context: 'Entertainment industry launches and product availability.', example: 'The band released their new album last Friday.', explanation: 'Also a noun: "the latest release", "a new release", "release date". Collocations: "release a film/album/single/game/statement", "press release" (official announcement to media), "on general release" (available in all cinemas). Also means to set free: "release a prisoner/animal".' },
      { word: 'viral', wordClass: 'adjective', level: 'B2', meaning: 'Spreading rapidly and widely through internet sharing.', context: 'Social media, marketing, and online culture.', example: 'The video went viral overnight, reaching 10 million views.', explanation: 'From "virus" — content that "infects" the internet by spreading person to person. "Go viral" = suddenly become extremely popular online. Collocations: "viral video/post/meme/content", "viral marketing" (marketing designed to be shared). The concept barely existed before social media — now it\'s one of the most important marketing terms.' },
      { word: 'compelling', wordClass: 'adjective', level: 'B2', meaning: 'Very interesting or attractive in a way that holds your attention completely.', context: 'Reviews, recommendations, and critical discussion of media.', example: 'The documentary tells a compelling story about ocean conservation.', explanation: 'Stronger than "interesting" — "compelling" means you can\'t stop watching/reading. Collocations: "compelling story/argument/evidence/reason", "compelling viewing/reading". Also means "forcing": "compelling evidence" = evidence so strong it forces a conclusion. Related: "compel" (verb) = to force.' },
      { word: 'binge-watch', wordClass: 'verb', level: 'B2', verbForms: { v1: 'binge-watch', v2: 'binge-watched', v3: 'binge-watched' }, meaning: 'To watch multiple episodes of a TV series in one sitting.', context: 'Modern TV viewing habits and streaming culture.', example: 'I binge-watched the entire series in one weekend.', explanation: '"Binge" originally meant excessive eating/drinking. Now "binge-watch" is standard vocabulary thanks to streaming services. "Binge-watching" (gerund/noun). Also: "binge-listen" (podcasts), "binge-read" (books). "Binge" alone is still negative: "binge eating/drinking" (doing too much, harmful). "Binge-watching" is usually used neutrally or humorously.' },
      { word: 'subtly', wordClass: 'adverb', level: 'C1', meaning: 'In a way that is not obvious or immediately noticeable; delicately.', context: 'Analysing films, performances, and artistic techniques.', example: 'The director subtly foreshadows the ending through small visual clues.', explanation: 'The "b" is silent: SUH-tlee. The adjective is "subtle" (also silent b). Collocations: "subtly different", "subtly hint/suggest", "subtle nuance/difference/change". Opposite: "blatantly" (obviously). Important in film/literature analysis: "The film subtly critiques consumer culture" — not in your face, but there if you look.' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 14. SHOPPING & FASHION
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'shopping-fashion',
    name: 'Shopping & Fashion',
    description: 'Vocabulary for retail, clothing, style, online shopping, and consumer culture.',
    icon: '🛍️',
    entries: [
      { word: 'bargain', wordClass: 'noun', level: 'B1', meaning: 'Something bought for less than the usual price; a good deal.', context: 'Sales, markets, and negotiating prices.', example: 'I got this jacket for £20 — what a bargain!', explanation: 'Also a verb: "bargain with someone" = negotiate a price (common in markets). Collocations: "a real/absolute bargain", "bargain hunter" (someone who actively looks for deals), "bargain price", "drive a hard bargain" (negotiate aggressively). "Bargain basement" = a section of a shop selling cheap items.' },
      { word: 'receipt', wordClass: 'noun', level: 'A2', meaning: 'A printed record of a purchase showing what was bought and the price paid.', context: 'Shopping, returns, and expense claims.', example: 'Keep the receipt in case you need to return the item.', explanation: 'Pronunciation: rih-SEET (the "p" is silent). Don\'t confuse with "recipe" (cooking instructions). Collocations: "keep/save the receipt", "email/digital receipt", "ask for a receipt", "proof of purchase". For tax/business: "receipt of goods" = confirmation that goods have been received.' },
      { word: 'refund', wordClass: 'noun', level: 'B1', meaning: 'Money returned to a buyer because they are dissatisfied or returning an item.', context: 'Returns, complaints, and consumer rights.', example: 'The shop gave me a full refund when I returned the faulty phone.', explanation: 'Also a verb: "They refunded my money." Stress changes: noun = REE-fund, verb = rih-FUND. Collocations: "full/partial refund", "get/receive/demand a refund", "refund policy", "no refunds" (the item cannot be returned). Different from "exchange" (swap for another item) and "store credit" (credit to spend in the same shop).' },
      { word: 'browse', wordClass: 'verb', level: 'B1', verbForms: { v1: 'browse', v2: 'browsed', v3: 'browsed' }, meaning: 'To look at items casually without intending to buy immediately.', context: 'Window shopping, online shopping, and bookshops.', example: 'I spent an hour browsing in the bookshop but didn\'t buy anything.', explanation: '"Browse" = look casually, no pressure. Different from "shop" (actively looking to buy). In technology: "browse the internet/web" = look at websites (a "browser" is the software: Chrome, Firefox). Collocations: "browse through", "just browsing" (what you say when a shop assistant asks if you need help).' },
      { word: 'purchase', wordClass: 'verb', level: 'B1', verbForms: { v1: 'purchase', v2: 'purchased', v3: 'purchased' }, meaning: 'To buy something, especially something significant or in a formal context.', context: 'Formal buying, contracts, and business transactions.', example: 'Tickets can be purchased online or at the box office.', explanation: 'More formal than "buy" — used in business, legal, and official contexts. Also a noun: "a recent purchase", "make a purchase", "proof of purchase". Collocations: "purchase a ticket/property/product", "purchasing power" (how much your money can buy), "purchase order" (official document to buy goods).' },
      { word: 'affordable', wordClass: 'adjective', level: 'B1', meaning: 'Reasonably priced; not too expensive for most people.', context: 'Discussing prices, housing, and products for different budgets.', example: 'The shop offers fashionable clothes at affordable prices.', explanation: 'More specific than "cheap" (which can suggest low quality). "Affordable" = within most people\'s budget. Collocations: "affordable housing/prices/healthcare", "affordable luxury" (premium feel, reasonable price). Opposite: "unaffordable". The verb is "afford": "Can you afford it?" = Do you have enough money?' },
      { word: 'trendy', wordClass: 'adjective', level: 'B1', meaning: 'Very fashionable and popular at the current time.', context: 'Fashion, lifestyle, and popular culture.', example: 'The neighbourhood has become very trendy, with lots of new cafés and boutiques.', explanation: '"Trendy" = following current fashion/trends. Can be slightly negative (implying superficial): "She only goes to trendy restaurants." More positive alternatives: "stylish" (good taste), "fashionable" (in fashion), "chic" (elegantly stylish). Opposite: "unfashionable", "outdated", "old-fashioned". Noun: "trend" = a general direction of change.' },
      { word: 'durable', wordClass: 'adjective', level: 'B2', meaning: 'Able to last a long time without deteriorating; hard-wearing.', context: 'Product quality, materials, and value for money.', example: 'These boots are made from durable leather — they should last for years.', explanation: 'Focus is on lasting quality, not just being "strong". Collocations: "durable material/product/goods", "durable and lightweight". The noun is "durability": "the durability of the product." In economics: "consumer durables" = goods that last (fridges, cars), opposite of "consumables" (food, cleaning products).' },
      { word: 'excessively', wordClass: 'adverb', level: 'B2', meaning: 'To a greater degree than is normal, necessary, or desirable; too much.', context: 'Criticising overspending, overconsumption, and pricing.', example: 'The restaurant was excessively expensive for what it offered.', explanation: 'Negative — implies something has gone too far. The adjective is "excessive": "excessive prices/charges/force". Collocations: "excessively high/low/expensive", "excessive spending/consumption". Different from "extremely" (which is neutral — just "very") — "excessively" always implies disapproval.' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 15. EMOTIONS & FEELINGS
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'emotions',
    name: 'Emotions & Feelings',
    description: 'Vocabulary for expressing emotional states, moods, and psychological wellbeing.',
    icon: '💭',
    entries: [
      { word: 'anxiety', wordClass: 'noun', level: 'B2', meaning: 'A feeling of worry, nervousness, or unease about something with an uncertain outcome.', context: 'Mental health, exam stress, and daily worries.', example: 'Many students experience anxiety before important exams.', explanation: 'The adjective is "anxious": "I feel anxious about the interview." Different from "fear" (response to a known danger) — "anxiety" is about uncertainty. Collocations: "suffer from/experience anxiety", "anxiety attack/disorder", "separation anxiety" (children afraid of being away from parents). Modern usage has expanded it to everyday nervousness.' },
      { word: 'frustration', wordClass: 'noun', level: 'B1', meaning: 'The feeling of being upset or annoyed because you cannot achieve something.', context: 'Work challenges, learning difficulties, and blocked goals.', example: 'He expressed his frustration at the slow progress of the project.', explanation: 'The adjective is "frustrated" (how you feel) and "frustrating" (what causes the feeling): "I\'m frustrated by this frustrating situation." Don\'t mix them up — "I am frustrating" means YOU are annoying others. Collocations: "express/voice/show frustration", "growing frustration", "out of frustration" (because of being frustrated).' },
      { word: 'gratitude', wordClass: 'noun', level: 'B2', meaning: 'The quality of being thankful; readiness to show appreciation.', context: 'Expressing thanks, positive psychology, and relationships.', example: 'She expressed her deep gratitude to everyone who helped during the crisis.', explanation: '"Gratitude" is more formal and deeper than simply saying "thanks". The adjective is "grateful" (NOT "greatful" — common spelling mistake). Collocations: "express/show gratitude", "deep/sincere gratitude", "a sense of gratitude", "gratitude journal" (writing what you\'re thankful for — a wellbeing practice).' },
      { word: 'overwhelm', wordClass: 'verb', level: 'B2', verbForms: { v1: 'overwhelm', v2: 'overwhelmed', v3: 'overwhelmed' }, meaning: 'To affect someone very strongly, making them unable to cope.', context: 'Emotional reactions, workload, and unexpected situations.', example: 'She was overwhelmed by the kindness of strangers after the flood.', explanation: 'Can be negative (too much stress) or positive (too much emotion): "overwhelmed with work" (negative) vs "overwhelmed with joy" (positive). "Overwhelming" (adjective) = extremely great or strong: "overwhelming evidence/majority/support". Collocations: "feel overwhelmed", "overwhelmed with emotion/work/grief".' },
      { word: 'resent', wordClass: 'verb', level: 'C1', verbForms: { v1: 'resent', v2: 'resented', v3: 'resented' }, meaning: 'To feel bitter or angry about something you consider unfair.', context: 'Workplace injustice, family dynamics, and personal relationships.', example: 'He resented being passed over for promotion despite his experience.', explanation: 'The noun is "resentment" (a lasting feeling of bitterness). Stronger and more lasting than simply being "angry" — resentment builds over time. Common pattern: "resent + -ing": "I resent having to work weekends." "Resentful" (adjective): "She felt resentful towards her colleague."' },
      { word: 'content', wordClass: 'adjective', level: 'B1', meaning: 'In a state of peaceful happiness; satisfied with what you have.', context: 'Life satisfaction, mindfulness, and personal reflection.', example: 'She felt content with her simple life in the countryside.', explanation: 'Pronunciation as adjective: con-TENT (stress on second syllable). Different from "happy" — "content" suggests quiet, calm satisfaction rather than excitement. "Content" with your life = you don\'t need anything more. Collocations: "feel/be content with", "perfectly content", "content to do something" (willing without complaint). The noun "contentment" = the state of being content.' },
      { word: 'devastated', wordClass: 'adjective', level: 'B2', meaning: 'Extremely shocked and upset; emotionally destroyed.', context: 'Reacting to terrible news, loss, or major disappointment.', example: 'The family was devastated by the unexpected loss of their home.', explanation: 'Very strong emotion — much stronger than "upset" or "sad". Use for genuine tragedies, not minor disappointments. The verb is "devastate": "The news devastated her." "Devastating" (adjective for the cause): "devastating news/blow/loss/impact". Collocations: "absolutely/utterly devastated", "emotionally devastated".' },
      { word: 'genuinely', wordClass: 'adverb', level: 'B2', meaning: 'In a truly sincere and honest way; really and authentically.', context: 'Expressing real emotions, distinguishing authentic from fake feelings.', example: 'She was genuinely surprised by the birthday party — she had no idea.', explanation: 'The adjective is "genuine" (real, not fake). "Genuinely" emphasises that an emotion is real, not performed. Collocations: "genuinely happy/sorry/interested/surprised", "genuinely believe". Opposite: "fake", "insincere", "disingenuous". "Are you genuinely interested, or just being polite?" — questions the authenticity of someone\'s feelings.' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 16. WEATHER & SEASONS
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'weather',
    name: 'Weather & Seasons',
    description: 'Vocabulary for weather conditions, climate, seasons, and natural phenomena.',
    icon: '🌦️',
    entries: [
      { word: 'forecast', wordClass: 'noun', level: 'B1', meaning: 'A prediction of future weather conditions based on analysis of data.', context: 'Weather reports, planning outdoor events, and daily decisions.', example: 'The forecast says it will rain all weekend.', explanation: 'Also a verb: "They forecast heavy snow for tomorrow." Past tense: "forecast" (not "forecasted", though this is sometimes used). Collocations: "weather forecast", "five-day forecast", "forecast rain/snow/sunshine". Extended to business: "economic/financial forecast", "sales forecast".' },
      { word: 'drought', wordClass: 'noun', level: 'B2', meaning: 'A prolonged period of abnormally low rainfall leading to water shortage.', context: 'Environmental issues, agriculture, and climate change.', example: 'The worst drought in decades destroyed crops across the region.', explanation: 'Pronunciation: DROWT (rhymes with "out"). Collocations: "severe/prolonged drought", "drought conditions", "drought-resistant crops" (plants that survive with little water). Also figurative: "a goal drought" (a sports team that hasn\'t scored for a long time).' },
      { word: 'breeze', wordClass: 'noun', level: 'A2', meaning: 'A gentle, pleasant wind.', context: 'Describing mild, comfortable weather.', example: 'There was a lovely cool breeze coming off the sea.', explanation: 'Wind scale (gentle to strong): breeze → wind → gale → storm → hurricane. "Breeze" is always gentle and pleasant. Collocations: "gentle/light/cool/warm breeze", "sea breeze" (from the sea to land during the day). Figurative: "It was a breeze!" = "It was very easy!" "Breezy" (adjective) = slightly windy, or casually cheerful.' },
      { word: 'pour', wordClass: 'verb', level: 'A2', verbForms: { v1: 'pour', v2: 'poured', v3: 'poured' }, meaning: 'To rain very heavily.', context: 'Describing heavy rainfall.', example: 'We got soaked — it was absolutely pouring when we left the cinema.', explanation: 'Rain intensity: drizzle (light) → rain → pour (heavy) → downpour (very heavy). "It\'s pouring" or "It\'s pouring down" or "It\'s pouring with rain" — all correct. Idiom: "It never rains but it pours" = when one bad thing happens, many follow. Also literal: "pour a drink" = fill a glass from a container.' },
      { word: 'humid', wordClass: 'adjective', level: 'B1', meaning: 'Having a high level of moisture in the air; muggy and uncomfortable.', context: 'Tropical climates, summer weather, and comfort discussions.', example: 'Bangkok is extremely humid during the rainy season.', explanation: 'The noun is "humidity": "The humidity was 90%." "Humid" is usually negative — it implies discomfort (sticky, sweaty). Compare: "damp" (slightly wet, unpleasant), "moist" (slightly wet, neutral or positive for soil/cake). Collocations: "hot and humid", "humid climate/conditions", "high humidity".' },
      { word: 'overcast', wordClass: 'adjective', level: 'B1', meaning: 'Covered with clouds; dull and grey (of the sky).', context: 'Weather descriptions and daily forecasts.', example: 'The sky was overcast all morning, but the sun came out after lunch.', explanation: 'Sky descriptions from clear to stormy: clear/sunny → partly cloudy → cloudy → overcast → grey/gloomy → dark/threatening. "Overcast" = completely covered with clouds but not necessarily raining. Collocations: "an overcast sky/day", "heavily overcast". It only describes the sky/weather, not moods (use "gloomy" for moods).' },
      { word: 'mild', wordClass: 'adjective', level: 'A2', meaning: 'Not too hot and not too cold; pleasantly moderate (of weather).', context: 'Describing comfortable temperatures and pleasant conditions.', example: 'We\'ve had a very mild winter this year — hardly any frost.', explanation: 'For weather, "mild" always means pleasantly warm for the time of year. A "mild winter" = warmer than usual. A "mild summer" would be unusual to say (you\'d say "cool summer"). Also for food: "mild curry/cheese" = not strong/spicy. And for illness: "a mild case of flu" = not severe.' },
      { word: 'bitterly', wordClass: 'adverb', level: 'B2', meaning: 'Extremely and unpleasantly (used mainly with "cold" and "disappointed").', context: 'Extreme cold weather and strong emotional disappointment.', example: 'It was bitterly cold outside, with temperatures well below zero.', explanation: 'Almost exclusively collocates with "cold" (weather) and "disappointed/regretting" (emotions). "Bitterly cold" = painfully, piercingly cold. "Bitterly disappointed" = deeply and painfully let down. Don\'t use "bitterly" with "hot" — say "unbearably hot" instead. The adjective "bitter" means: 1) a sharp, unpleasant taste; 2) angry and resentful; 3) extremely cold.' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 17. FAMILY & RELATIONSHIPS
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'family',
    name: 'Family & Relationships',
    description: 'Vocabulary for family structures, life events, parenting, and interpersonal bonds.',
    icon: '👨‍👩‍👧‍👦',
    entries: [
      { word: 'sibling', wordClass: 'noun', level: 'B1', meaning: 'A brother or sister.', context: 'Discussing family, forms, and official documents.', example: 'She has three siblings — two brothers and one sister.', explanation: '"Sibling" is gender-neutral and more formal than "brother or sister". Used on official forms and in academic/medical contexts. Collocations: "sibling rivalry" (competition between brothers/sisters), "older/younger sibling", "half-sibling" (share one parent), "step-sibling" (not related by blood, through remarriage).' },
      { word: 'upbringing', wordClass: 'noun', level: 'B2', meaning: 'The way a child is raised and educated by their parents.', context: 'Discussing childhood experiences and how they shaped a person.', example: 'Her strict upbringing gave her strong self-discipline but left her feeling anxious.', explanation: 'From "bring up" (= raise a child). Uncountable — "an upbringing" not "upbringings". Collocations: "strict/liberal/sheltered/religious upbringing", "have a happy/difficult upbringing". In IELTS: "Does a person\'s upbringing determine their personality?" — a common topic.' },
      { word: 'bond', wordClass: 'noun', level: 'B2', meaning: 'A strong feeling of connection or affection between people.', context: 'Close relationships, parent-child attachment, and friendships.', example: 'The bond between the twins is incredibly strong — they seem to know what each other is thinking.', explanation: 'Also a verb: "They bonded over their shared love of music." Collocations: "strong/close/deep bond", "family/emotional bond", "form/create/strengthen a bond", "bonding" (noun — the process of forming a bond): "team bonding activities", "mother-baby bonding". Also means a financial instrument (government bond) and a glue/adhesive.' },
      { word: 'nurture', wordClass: 'verb', level: 'C1', verbForms: { v1: 'nurture', v2: 'nurtured', v3: 'nurtured' }, meaning: 'To care for and encourage the growth and development of someone or something.', context: 'Parenting, education, and developing talent.', example: 'Good parents nurture their children\'s natural curiosity and creativity.', explanation: 'More than just "look after" — "nurture" implies actively helping growth and development. The "nature vs nurture" debate = are we shaped by genes (nature) or environment (nurture)? Also used for non-human things: "nurture a relationship/talent/idea". The adjective is "nurturing": "a nurturing environment/parent".' },
      { word: 'inherit', wordClass: 'verb', level: 'B2', verbForms: { v1: 'inherit', v2: 'inherited', v3: 'inherited' }, meaning: 'To receive money, property, or characteristics from parents or predecessors.', context: 'Family estates, genetics, and traditions.', example: 'She inherited her grandmother\'s house and her mother\'s sense of humour.', explanation: 'Two meanings: 1) Legal: receive after someone dies: "inherit money/property/a title"; 2) Genetic: receive traits from parents: "inherit blue eyes/curly hair". The noun is "inheritance" (what you receive). An "heir" (pronunciation: AIR) is the person who inherits. Collocations: "inherit a fortune", "inherited trait/disease".' },
      { word: 'supportive', wordClass: 'adjective', level: 'B1', meaning: 'Providing encouragement, emotional help, and practical assistance.', context: 'Describing helpful family members, friends, and partners.', example: 'Her parents have always been very supportive of her career choices.', explanation: 'One of the most positive adjectives for describing relationships. Collocations: "supportive family/partner/friend/environment", "emotionally supportive", "be supportive of someone\'s decisions". The verb is "support" and the noun is "support". "I have a great support network" = people who help you.' },
      { word: 'unconditionally', wordClass: 'adverb', level: 'C1', meaning: 'Without any conditions, limitations, or requirements; completely and without reservation.', context: 'Describing parental love, acceptance, and loyalty.', example: 'Parents should love their children unconditionally, regardless of their achievements.', explanation: 'The adjective is "unconditional": "unconditional love/support/surrender". It means there are NO conditions — you don\'t need to earn it or deserve it. Opposite: "conditionally" (with requirements). "Unconditional love" is one of the most discussed concepts in parenting and psychology.' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 18. HOUSING & REAL ESTATE
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'housing',
    name: 'Housing & Real Estate',
    description: 'Vocabulary for renting, buying, describing properties, and neighbourhood features.',
    icon: '🏘️',
    entries: [
      { word: 'tenant', wordClass: 'noun', level: 'B1', meaning: 'A person who rents and occupies a property owned by someone else.', context: 'Rental agreements, property management, and housing rights.', example: 'The tenant signed a 12-month lease for the two-bedroom flat.', explanation: 'The person who owns the property is the "landlord" (male/neutral) or "landlady" (female), though "landlord" is increasingly used for all genders. Collocations: "prospective tenant" (someone applying), "sitting tenant" (already living there), "tenant rights", "tenant agreement". The verb is "rent" (from tenant\'s perspective) or "let" (from landlord\'s perspective).' },
      { word: 'mortgage', wordClass: 'noun', level: 'B2', meaning: 'A long-term loan from a bank used to buy property, secured against the property itself.', context: 'Home buying and property investment.', example: 'They applied for a 30-year mortgage with a fixed interest rate.', explanation: 'From French "mort" (death) + "gage" (pledge). If you don\'t repay, the bank can repossess the property. Collocations: "take out/apply for/pay off a mortgage", "mortgage rate/payment/lender", "fixed-rate mortgage" (interest stays same), "variable-rate mortgage" (interest can change), "mortgage-free" (fully paid off).' },
      { word: 'renovate', wordClass: 'verb', level: 'B2', verbForms: { v1: 'renovate', v2: 'renovated', v3: 'renovated' }, meaning: 'To restore a building to a good condition by repairing and improving it.', context: 'Home improvement, property development, and restoration.', example: 'They bought a Victorian house and spent two years renovating it.', explanation: '"Renovate" = improve and modernise while keeping the original character. Different from "rebuild" (knock down and start again) and "refurbish" (similar but usually less extensive). The noun is "renovation". Collocations: "renovate a house/kitchen/bathroom", "major/minor renovation", "renovation project/costs".' },
      { word: 'detached', wordClass: 'adjective', level: 'B1', meaning: 'Not joined to any other building on any side (of a house).', context: 'Property descriptions and house hunting.', example: 'They live in a four-bedroom detached house with a large garden.', explanation: 'UK property types by attachment: "detached" (standalone), "semi-detached" (joined on one side — "semi"), "terraced" (joined on both sides, in a row), "flat/apartment" (unit in a larger building). Detached houses are typically the most expensive. Also means emotionally distant: "He seemed detached and uninterested."' },
      { word: 'spacious', wordClass: 'adjective', level: 'B1', meaning: 'Having plenty of space; large and roomy.', context: 'Property descriptions, interior design, and comfort.', example: 'The open-plan living area is bright and spacious.', explanation: 'Estate agents\' favourite word. More elegant than "big" or "large" for properties. Implies comfort and good proportions, not just size. Opposite: "cramped" (uncomfortably small), "poky" (British informal for cramped). Collocations: "spacious rooms/apartment/garden", "bright and spacious".' },
      { word: 'conveniently', wordClass: 'adverb', level: 'B1', meaning: 'In a way that is easy to use, suits your needs, or involves little trouble.', context: 'Describing location advantages and accessibility.', example: 'The flat is conveniently located near shops, schools, and public transport.', explanation: 'The adjective is "convenient" (opposite: "inconvenient"). Collocations: "conveniently located/situated/placed", "convenient access/time/location". In property: "conveniently" almost always describes location — near useful amenities. "At your convenience" = whenever suits you (formal).' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 19. TRANSPORT & VEHICLES
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'transport',
    name: 'Transport & Vehicles',
    description: 'Vocabulary for cars, public transport, driving, and getting around.',
    icon: '🚗',
    entries: [
      { word: 'commute', wordClass: 'noun', level: 'B1', meaning: 'The regular journey between home and work.', context: 'Daily travel, work-life balance, and urban planning.', example: 'My daily commute takes about 45 minutes by train.', explanation: 'Also a verb: "I commute to London every day." A "commuter" is someone who commutes. Collocations: "daily commute", "long/short commute", "commuter train/belt" (area around a city where commuters live), "commuting time". "Commutable distance" = close enough to travel to work daily.' },
      { word: 'congestion', wordClass: 'noun', level: 'B2', meaning: 'A state of being overcrowded with traffic, making movement difficult.', context: 'Urban planning, rush hour, and transport policy.', example: 'Traffic congestion in the city centre is worst between 8 and 9 a.m.', explanation: 'Uncountable. Collocations: "traffic congestion", "congestion charge" (fee to drive in busy areas — London has one), "congestion zone", "ease/reduce congestion". Also medical: "nasal congestion" (blocked nose). The adjective is "congested": "congested roads/areas".' },
      { word: 'pedestrian', wordClass: 'noun', level: 'B1', meaning: 'A person walking in a public area, especially near roads.', context: 'Road safety, urban design, and traffic rules.', example: 'Drivers must always give way to pedestrians at zebra crossings.', explanation: 'Also an adjective meaning "ordinary and boring": "a pedestrian performance" (unimaginative). Collocations: "pedestrian crossing/zone/bridge", "pedestrian traffic", "pedestrianised area/street" (closed to vehicles). "Jaywalking" = crossing the road illegally (not at a crossing) — a crime in some countries but not in the UK.' },
      { word: 'accelerate', wordClass: 'verb', level: 'B2', verbForms: { v1: 'accelerate', v2: 'accelerated', v3: 'accelerated' }, meaning: 'To increase speed; to make something happen faster.', context: 'Driving, physics, and describing rapid change.', example: 'The car accelerated from 0 to 100 km/h in just 5 seconds.', explanation: 'The opposite is "decelerate" (slow down) or "brake". The noun is "acceleration": "rapid acceleration", "the car\'s acceleration". The "accelerator" is the pedal you press to go faster (also called "gas pedal" in American English). Figurative: "accelerate growth/progress/change" = make it happen faster.' },
      { word: 'navigate', wordClass: 'verb', level: 'B2', verbForms: { v1: 'navigate', v2: 'navigated', v3: 'navigated' }, meaning: 'To plan and direct the route of a journey; to find your way.', context: 'Driving with GPS, sailing, and finding your way in unfamiliar places.', example: 'She navigated through the narrow streets of the old town using her phone.', explanation: 'Physical: "navigate a route/course/road/river." Digital: "navigate a website" (find your way around it). Figurative: "navigate a difficult situation" (find a way through). The noun is "navigation" — "satellite navigation" (satnav/GPS). A "navigator" is the person who directs the route (in a rally car, on a ship).' },
      { word: 'reliable', wordClass: 'adjective', level: 'B1', meaning: 'Consistently good in quality or performance; able to be trusted.', context: 'Describing transport services, vehicles, and people.', example: 'The bus service is very reliable — it rarely runs late.', explanation: 'Collocations: "reliable service/car/source/information", "highly/extremely reliable". The noun is "reliability": "the reliability of public transport." Opposite: "unreliable." For people: "He\'s very reliable" = you can count on him. Related: "dependable" (similar meaning, slightly more personal/warm).' },
      { word: 'efficiently', wordClass: 'adverb', level: 'B2', meaning: 'In a way that achieves maximum results with minimum waste of time or fuel.', context: 'Evaluating transport systems, driving habits, and fuel consumption.', example: 'Electric cars use energy much more efficiently than petrol engines.', explanation: 'The adjective is "efficient" (opposite: "inefficient"). In transport: "fuel-efficient" (uses less fuel), "energy-efficient", "efficient route" (fastest/shortest). Collocations: "run/operate efficiently", "more efficiently", "efficiently designed". Different from "effectively" (achieving the goal) — "efficiently" focuses on minimal waste.' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 20. ARTS & CULTURE
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'arts-culture',
    name: 'Arts & Culture',
    description: 'Vocabulary for visual arts, music, theatre, museums, and cultural heritage.',
    icon: '🎨',
    entries: [
      { word: 'exhibition', wordClass: 'noun', level: 'B1', meaning: 'A public display of art, objects, or information in a gallery or museum.', context: 'Museums, galleries, and cultural events.', example: 'The museum is hosting an exhibition of modern Japanese art.', explanation: 'British: "exhibition". American: often "exhibit" (same meaning). Collocations: "art/photography/solo/group exhibition", "visiting/travelling exhibition" (moves between venues), "permanent exhibition" (always on display), "host/put on/open an exhibition". Different from a "collection" (items owned by a museum).' },
      { word: 'masterpiece', wordClass: 'noun', level: 'B2', meaning: 'A work of outstanding creative skill, considered the best of its kind.', context: 'Discussing exceptional art, music, literature, or film.', example: 'Many consider "Guernica" by Picasso to be his greatest masterpiece.', explanation: 'Originally meant the best piece made by a craftsman to prove their skill. Now used for any exceptional creative work: a painting, novel, film, song. Collocations: "literary/artistic/cinematic masterpiece", "an absolute masterpiece", "create/produce a masterpiece". Can be used casually: "This cake is a masterpiece!" (exaggeration for humour).' },
      { word: 'heritage', wordClass: 'noun', level: 'B2', meaning: 'Valued traditions, buildings, and culture inherited from previous generations.', context: 'Conservation, tourism, and national identity.', example: 'The old town is a UNESCO World Heritage Site.', explanation: 'Usually uncountable. Collocations: "cultural/national/natural heritage", "World Heritage Site" (UNESCO designation), "heritage building/site/centre", "preserve/protect heritage". Different from "inheritance" (money/property from a deceased relative). "Heritage" is about shared cultural value, not individual possession.' },
      { word: 'portray', wordClass: 'verb', level: 'B2', verbForms: { v1: 'portray', v2: 'portrayed', v3: 'portrayed' }, meaning: 'To represent or describe someone or something in a particular way in art or writing.', context: 'Discussing how characters are shown in films, books, and media.', example: 'The film portrays life in rural India with great sensitivity and realism.', explanation: 'The noun is "portrayal": "a realistic portrayal of poverty." Collocations: "portray someone as..." (represent them as), "portray a character" (act the role), "accurate/sympathetic/negative portrayal". A "portrait" is a painting/photo of a person. "Self-portrait" = artist paints themselves.' },
      { word: 'inspire', wordClass: 'verb', level: 'B1', verbForms: { v1: 'inspire', v2: 'inspired', v3: 'inspired' }, meaning: 'To fill someone with the urge to create, act, or feel something positive.', context: 'Creative motivation, leadership, and artistic influence.', example: 'Her travels through South America inspired her to write a novel.', explanation: 'The noun is "inspiration" (the feeling or the source): "She was my inspiration." "Inspired" (adjective) = brilliant, as if touched by a higher power: "an inspired performance." "Inspiring" = causing inspiration: "an inspiring teacher." Collocations: "inspire someone to do something", "inspired by", "a source of inspiration", "inspirational" (adjective for things that inspire).' },
      { word: 'contemporary', wordClass: 'adjective', level: 'B2', meaning: 'Belonging to the present time; modern. Or: living at the same time as another person or event.', context: 'Art movements, cultural discussions, and historical comparisons.', example: 'The gallery specialises in contemporary art from the last 30 years.', explanation: 'Two meanings: 1) Modern/current: "contemporary art/music/literature" (made now or recently); 2) Of the same period: "Shakespeare and his contemporaries" (people living at the same time). "Contemporary" art typically means post-1945 to now. Don\'t confuse with "modern art" (early-to-mid 20th century: Picasso, Dalí, Pollock).' },
      { word: 'profoundly', wordClass: 'adverb', level: 'C1', meaning: 'In a way that is very great, deep, or intense; to a great depth.', context: 'Describing the deep impact of art, music, or cultural experiences.', example: 'The concert was profoundly moving — several audience members were in tears.', explanation: 'The adjective is "profound" (opposite: "superficial" or "shallow"). Collocations: "profoundly affected/influenced/moved/grateful", "profound impact/effect/change/silence". In academic writing: "This has profound implications for..." Stronger than "deeply" — "profoundly" suggests something life-changing or fundamentally important.' },
    ],
  },
]
