// # ═══════════════════════════════════════════════════════════════════════════
// # VOCABULARY REFERENCE DATA — Part 5: Expansion for Part 2 categories
// # ═══════════════════════════════════════════════════════════════════════════
// # Uses the SAME field IDs as vocabulary-data-2.ts so the merge function
// # in page.tsx combines these entries with the originals (50+ per category).

import type { VocabField } from './types'

export const VOCAB_FIELDS_5: VocabField[] = [

  // # ═══════════════════════════════════════════════════════════════════
  // # 11. FOOD & COOKING — Expansion
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'food-cooking',
    name: 'Food & Cooking',
    description: 'Vocabulary for food preparation, cooking methods, ingredients, and dining.',
    icon: '🍳',
    entries: [
      // # ── Nouns ──
      { word: 'ingredient', wordClass: 'noun', level: 'A2', meaning: 'One of the individual foods or substances used to make a particular dish.', context: 'Recipes and cooking instructions.', example: 'The main ingredients in this soup are tomatoes, onions, and garlic.', explanation: 'Collocations: "key/main/secret ingredient", "ingredient list" (on packaging), "fresh/organic ingredients". Figurative: "Hard work is an essential ingredient of success." Always count: "two ingredients" not "two ingredient".' },
      { word: 'portion', wordClass: 'noun', level: 'B1', meaning: 'The amount of food served to one person; a serving.', context: 'Restaurants, nutrition, and meal planning.', example: 'The restaurant serves generous portions — I couldn\'t finish my meal.', explanation: 'Collocations: "large/small/generous portion", "portion size/control", "five portions of fruit and vegetables a day" (UK health guideline). "Portion control" = managing how much you eat. Also general: "a portion of the profits" (= a share).' },
      { word: 'seasoning', wordClass: 'noun', level: 'B1', meaning: 'Salt, pepper, spices, or herbs added to food to enhance its flavour.', context: 'Cooking techniques and flavour development.', example: 'The dish needs more seasoning — add a pinch of salt and some black pepper.', explanation: 'The verb is "season": "Season the chicken with salt and pepper before roasting." Collocations: "add seasoning", "salt and pepper seasoning", "well-seasoned" (= has enough flavour). Also: "a seasoned professional" (figurative = very experienced).' },
      { word: 'cuisine', wordClass: 'noun', level: 'B1', meaning: 'A style of cooking characteristic of a particular country or region.', context: 'Restaurants and food culture.', example: 'Thai cuisine is known for its balance of sweet, sour, salty, and spicy flavours.', explanation: 'From French — pronunciation: kwih-ZEEN. Collocations: "Italian/Japanese/French cuisine", "fusion cuisine" (= mixing styles from different cultures), "haute cuisine" (= high-quality, elaborate French cooking). More formal than "food" or "cooking".' },
      { word: 'utensil', wordClass: 'noun', level: 'B1', meaning: 'A tool or implement used in the kitchen for preparing or eating food.', context: 'Cooking equipment and kitchen organisation.', example: 'Keep your cooking utensils in the drawer next to the stove.', explanation: 'Examples: spatula, whisk, ladle, tongs, peeler, grater. "Utensils" can also mean "cutlery" (knives, forks, spoons) but usually refers to cooking tools. Collocations: "kitchen/cooking utensils", "wooden/metal/silicone utensils".' },
      { word: 'pastry', wordClass: 'noun', level: 'B1', meaning: 'A dough made from flour, fat, and water, used as a base or covering for baked dishes.', context: 'Baking and desserts.', example: 'She made the pie with homemade pastry instead of the shop-bought kind.', explanation: 'Types: "shortcrust pastry" (crumbly, for pies), "puff pastry" (light, flaky layers), "filo/phyllo pastry" (very thin sheets), "choux pastry" (light, for éclairs). Also means a cake or sweet baked item: "Danish pastry", "pastries" (the display in a bakery).' },
      { word: 'leftovers', wordClass: 'noun', level: 'A2', meaning: 'Food remaining after a meal that has not been eaten.', context: 'Meal planning and reducing food waste.', example: 'We had the leftovers from last night\'s dinner for lunch today.', explanation: 'Always plural: "leftovers" (NOT "a leftover" for food). Collocations: "eat/reheat/freeze the leftovers", "leftover chicken/rice/pasta". An important concept in reducing food waste. "Leftover" can also be an adjective: "leftover paint" (= paint remaining from a project).' },
      { word: 'garnish', wordClass: 'noun', level: 'B2', meaning: 'A decorative item added to food or drink to enhance its appearance.', context: 'Plating food and restaurant presentation.', example: 'The chef added a sprig of parsley as a garnish on top of the soup.', explanation: 'Also a verb: "Garnish the plate with fresh herbs." Common garnishes: parsley, lemon slices, edible flowers, microgreens, mint leaves. Collocations: "as a garnish", "garnish with". In cocktails: "olive garnish", "lime garnish".' },
      // # ── Verbs ──
      { word: 'marinate', wordClass: 'verb', level: 'B2', verbForms: { v1: 'marinate', v2: 'marinated', v3: 'marinated' }, meaning: 'To soak food in a mixture of oil, vinegar, spices, or herbs to add flavour and tenderise it.', context: 'Meat preparation and flavour development.', example: 'Marinate the chicken in soy sauce and ginger for at least two hours before grilling.', explanation: 'The liquid mixture is a "marinade" (noun). Collocations: "marinate overnight/for 2 hours", "marinated chicken/steak/tofu", "in a marinade". Marinating serves two purposes: adds flavour AND tenderises (softens) the meat through the acid in the marinade.' },
      { word: 'simmer', wordClass: 'verb', level: 'B1', verbForms: { v1: 'simmer', v2: 'simmered', v3: 'simmered' }, meaning: 'To cook gently in liquid at just below boiling point, with small bubbles.', context: 'Cooking methods for sauces and soups.', example: 'Let the sauce simmer on low heat for 30 minutes to develop the flavours.', explanation: 'Temperature scale: cold → warm → simmer → boil → rapid boil. Collocations: "simmer on/over low heat", "bring to a simmer", "let it simmer". Figurative: "simmering anger/tension" = anger that is building but not yet expressed. "Simmer down" = calm down.' },
      { word: 'dice', wordClass: 'verb', level: 'B1', verbForms: { v1: 'dice', v2: 'diced', v3: 'diced' }, meaning: 'To cut food into small cube-shaped pieces.', context: 'Food preparation and chopping techniques.', example: 'Dice the onions and peppers into small cubes before adding them to the pan.', explanation: 'Cutting words (from biggest to smallest): "chop" (rough pieces) → "dice" (small cubes) → "mince" (very fine pieces) → "julienne" (thin strips). Also a noun: "a dice/die" (the cube used in games). "No dice" (informal) = no luck, no success.' },
      { word: 'whisk', wordClass: 'verb', level: 'B1', verbForms: { v1: 'whisk', v2: 'whisked', v3: 'whisked' }, meaning: 'To beat eggs, cream, or a mixture quickly with a fork or whisk to add air.', context: 'Baking and sauce preparation.', example: 'Whisk the eggs and sugar together until the mixture is light and fluffy.', explanation: 'Also a noun: "a whisk" (the kitchen tool). Collocations: "whisk eggs/cream/batter", "electric whisk" (= powered whisk). "Whisk away" (figurative) = to take someone somewhere quickly: "We were whisked away to a luxury hotel."' },
      { word: 'drain', wordClass: 'verb', level: 'B1', verbForms: { v1: 'drain', v2: 'drained', v3: 'drained' }, meaning: 'To remove liquid from food, usually by pouring it through a sieve or colander.', context: 'Pasta preparation and vegetable cooking.', example: 'Cook the pasta for 10 minutes, then drain and serve with the sauce.', explanation: 'Also a noun: "the drain" (= the pipe that carries away waste water). Collocations: "drain the pasta/rice/potatoes", "drain on kitchen paper" (to absorb oil). Figurative: "brain drain" (= talented people leaving a country), "a drain on resources" (= using too much).' },
      { word: 'grate', wordClass: 'verb', level: 'B1', verbForms: { v1: 'grate', v2: 'grated', v3: 'grated' }, meaning: 'To shred food into small pieces using a grater.', context: 'Cheese preparation and baking.', example: 'Grate the cheese over the top of the pasta before serving.', explanation: 'The tool is a "grater" or "cheese grater". Collocations: "grate cheese/carrots/ginger", "grated cheese/coconut/lemon zest". Also means to annoy: "His voice really grates on me" (= irritates me). "Grating" (adjective) = annoying: "a grating sound".' },
      { word: 'knead', wordClass: 'verb', level: 'B2', verbForms: { v1: 'knead', v2: 'kneaded', v3: 'kneaded' }, meaning: 'To press and fold dough with your hands to make it smooth and elastic.', context: 'Bread making and baking.', example: 'Knead the bread dough for about 10 minutes until it becomes smooth and elastic.', explanation: 'The "k" is silent — pronounced NEED. Collocations: "knead dough/bread", "knead for X minutes". Kneading develops gluten, which gives bread its stretchy texture. Also: "knead muscles" = massage them with pressing movements (like a cat does with its paws!).' },
      // # ── Adjectives ──
      { word: 'bland', wordClass: 'adjective', level: 'B1', meaning: 'Lacking strong flavour; tasteless and uninteresting.', context: 'Food criticism and flavour assessment.', example: 'The soup was rather bland — it needed more salt and spice.', explanation: 'Negative — implies boring food. Collocations: "bland food/diet/taste". Opposite: "flavourful", "tasty", "seasoned". Also means "dull and uninteresting" generally: "a bland personality" (= boring, not distinctive). "Bland diet" is sometimes prescribed medically (easy-to-digest food).' },
      { word: 'savoury', wordClass: 'adjective', level: 'B1', meaning: 'Having a salty or spicy flavour rather than a sweet one.', context: 'Food categories and taste preferences.', example: 'I prefer savoury snacks like crisps and cheese to sweet ones like chocolate.', explanation: 'British spelling: "savoury". American: "savory". The five basic tastes: sweet, sour, salty, bitter, and umami (savoury). Collocations: "savoury snack/dish/flavour", "sweet or savoury?" (a common question). Japanese "umami" is the closest concept to "savoury".' },
      { word: 'crispy', wordClass: 'adjective', level: 'A2', meaning: 'Having a pleasantly hard, crunchy outer texture.', context: 'Describing cooked food texture.', example: 'The chips were perfectly crispy on the outside and fluffy on the inside.', explanation: 'Similar to "crunchy" but more specific to cooked food. Collocations: "crispy bacon/skin/coating/fries", "golden and crispy". "Crisp" can also be used: "crisp lettuce" (= fresh and firm). British: "a packet of crisps" = American: "a bag of chips".' },
      { word: 'overcooked', wordClass: 'adjective', level: 'A2', meaning: 'Cooked for too long, resulting in a less desirable texture or flavour.', context: 'Cooking mistakes and food quality.', example: 'The steak was overcooked — I asked for medium-rare but it came well done.', explanation: 'Opposite: "undercooked" (= not cooked enough — can be dangerous with meat). "Well done" = fully cooked through; "medium" = pink in the middle; "rare" = mostly red inside. Collocations: "overcooked pasta/vegetables/meat". Overcooked pasta is too soft; Italians call it "scotta" (literally "overcooked").' },
      // # ── Adverbs ──
      { word: 'evenly', wordClass: 'adverb', level: 'B1', meaning: 'In a uniform way; spread or distributed equally.', context: 'Cooking technique and consistency.', example: 'Spread the sauce evenly over the base of the pizza.', explanation: 'The adjective is "even" (opposite: "uneven"). Collocations: "evenly distributed/spread/spaced/cooked", "cook evenly" (= all parts cook at the same rate). "Evenly matched" = two competitors of equal ability. "Even" also means level/flat: "an even surface".' },
      { word: 'generously', wordClass: 'adverb', level: 'B1', meaning: 'In a way that gives or uses more than is strictly necessary; abundantly.', context: 'Cooking and hospitality.', example: 'Season the dish generously with salt and pepper before roasting.', explanation: 'The adjective is "generous": "a generous portion/helping/amount". Collocations: "generously seasoned/topped/filled", "generous with" (= willing to give a lot). In recipes: "generously" means don\'t be stingy — use plenty. Also personality: "She\'s a very generous person."' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 12. SPORTS & FITNESS — Expansion
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'sports-fitness',
    name: 'Sports & Fitness',
    description: 'Vocabulary for exercise, athletics, competition, and physical health.',
    icon: '⚽',
    entries: [
      // # ── Nouns ──
      { word: 'tournament', wordClass: 'noun', level: 'B1', meaning: 'A series of competitive matches or games to determine an overall winner.', context: 'Sports competitions and gaming.', example: 'The tennis tournament attracts the best players from around the world.', explanation: 'Collocations: "enter/win/host a tournament", "knockout tournament" (= lose once, you\'re out), "round-robin tournament" (= everyone plays everyone). Different from "league" (= a season-long competition with a table/standings).' },
      { word: 'referee', wordClass: 'noun', level: 'B1', meaning: 'An official who watches a game and ensures the rules are followed.', context: 'Football, basketball, boxing, and other sports.', example: 'The referee awarded a penalty after the player was fouled in the box.', explanation: 'Also a verb: "She refereed the match." Informal: "ref". Different from "umpire" (cricket, tennis, baseball). Collocations: "the referee\'s decision", "blow the whistle" (referee stopping play). "VAR" (Video Assistant Referee) in football checks decisions using video replay.' },
      { word: 'stamina', wordClass: 'noun', level: 'B2', meaning: 'The ability to sustain physical or mental effort over a long period.', context: 'Endurance sports and fitness training.', example: 'Marathon runners need incredible stamina to run 42 kilometres.', explanation: 'Uncountable. Collocations: "build up/improve/lack stamina", "physical/mental stamina". Different from "strength" (= how powerful you are) — "stamina" is about lasting power, endurance. "Endurance" is a close synonym.' },
      { word: 'opponent', wordClass: 'noun', level: 'B1', meaning: 'A person or team competing against you in a sport or contest.', context: 'Competition and strategic thinking.', example: 'She studied her opponent\'s playing style before the match.', explanation: 'Collocations: "face/beat/defeat your opponent", "worthy/tough/political opponent". Different from "enemy" (= personal hostility) — an "opponent" is simply someone on the other side of a competition. Also politics: "political opponents" = people who disagree on policy.' },
      { word: 'spectator', wordClass: 'noun', level: 'B1', meaning: 'A person who watches a sports event or other show.', context: 'Stadiums, events, and audience descriptions.', example: 'Over 80,000 spectators packed the stadium for the cup final.', explanation: 'Different from "audience" (theatre, concerts) — "spectators" watch sports. Collocations: "spectator sport" (= sport that people enjoy watching), "spectators lined the route" (marathons). "Spectate" (verb) is less common but exists.' },
      { word: 'league', wordClass: 'noun', level: 'B1', meaning: 'A group of teams that compete against each other over a season.', context: 'Organised sports competitions.', example: 'Manchester City topped the Premier League table at the end of the season.', explanation: 'Collocations: "football/baseball league", "league table/standings/match", "top/bottom of the league", "Champions League". Also figurative: "out of my league" (= beyond my level/ability), "in the same league as" (= comparable to).' },
      // # ── Verbs ──
      { word: 'sprint', wordClass: 'verb', level: 'B1', verbForms: { v1: 'sprint', v2: 'sprinted', v3: 'sprinted' }, meaning: 'To run at full speed over a short distance.', context: 'Athletics and short bursts of speed.', example: 'He sprinted the last 100 metres to win the race by a narrow margin.', explanation: 'Also a noun: "the 100-metre sprint". The person is a "sprinter". Collocations: "sprint to the finish", "sprint race/distance", "final sprint". In project management: a "sprint" = a short period of focused work (2-4 weeks in Agile/Scrum methodology).' },
      { word: 'tackle', wordClass: 'verb', level: 'B1', verbForms: { v1: 'tackle', v2: 'tackled', v3: 'tackled' }, meaning: 'To try to take the ball from an opponent in football; to confront a problem.', context: 'Football, rugby, and problem-solving.', example: 'The defender tackled the striker just as he was about to shoot.', explanation: 'Also a noun: "a clean/dirty/sliding tackle". In rugby and American football, tackling involves physically bringing someone to the ground. Figurative: "tackle a problem/issue/challenge" (= address it directly). Collocations: "tackle someone", "tackle a problem head-on".' },
      { word: 'stretch', wordClass: 'verb', level: 'A2', verbForms: { v1: 'stretch', v2: 'stretched', v3: 'stretched' }, meaning: 'To extend the body or a body part to its full length to improve flexibility.', context: 'Warm-up routines and flexibility training.', example: 'Always stretch before and after exercising to prevent muscle injuries.', explanation: 'Also a noun: "do some stretches", "a stretch of road/time". Collocations: "stretch your legs/arms/muscles", "stretching exercises", "have a stretch" (= extend your body). "Stretch" also means to extend: "The queue stretched around the block."' },
      { word: 'qualify', wordClass: 'verb', level: 'B1', verbForms: { v1: 'qualify', v2: 'qualified', v3: 'qualified' }, meaning: 'To reach the standard required to enter a competition or obtain a position.', context: 'Sports tournaments and professional credentials.', example: 'England qualified for the World Cup finals after winning their group.', explanation: 'The noun is "qualification" (both sports and professional credentials). Collocations: "qualify for the finals/World Cup", "qualifying round/match" (= matches to determine who enters the main competition). Also: "qualified teacher/doctor" (= has the necessary qualifications).' },
      { word: 'dribble', wordClass: 'verb', level: 'B1', verbForms: { v1: 'dribble', v2: 'dribbled', v3: 'dribbled' }, meaning: 'To move a ball forward with repeated small kicks or bounces.', context: 'Football and basketball technique.', example: 'Messi dribbled past three defenders before scoring a spectacular goal.', explanation: 'In football: move the ball with your feet; in basketball: bounce the ball while moving. Also means to let liquid flow slowly from the mouth: "The baby dribbled all over his bib." Collocations: "dribble past/around a player", "dribbling skills".' },
      // # ── Adjectives ──
      { word: 'competitive', wordClass: 'adjective', level: 'B1', meaning: 'Having a strong desire to win; involving competition between people.', context: 'Sports psychology and business.', example: 'She\'s extremely competitive — she hates losing at anything, even board games.', explanation: 'The noun is "competition" and the verb is "compete". Collocations: "competitive sport/market/price/advantage", "highly competitive" (= very difficult to win/succeed in), "competitive nature/spirit". Can be positive (driven to succeed) or negative (too focused on winning).' },
      { word: 'exhausting', wordClass: 'adjective', level: 'B1', meaning: 'Making you feel extremely tired and drained of energy.', context: 'Intense exercise and demanding activities.', example: 'The three-hour training session was absolutely exhausting.', explanation: 'Different from "exhausted" (= the person\'s feeling) — "exhausting" describes the ACTIVITY. An exhausting workout makes you exhausted. Collocations: "physically/mentally exhausting", "exhausting day/experience". "Exhaustion" (noun): "She collapsed from exhaustion."' },
      { word: 'amateur', wordClass: 'adjective', level: 'B2', meaning: 'Doing something as a hobby, not as a paid profession.', context: 'Sports classification and skill levels.', example: 'She started as an amateur boxer before turning professional at age 22.', explanation: 'Opposite: "professional". Also a noun: "an amateur". Pronunciation: AM-uh-tur (British) or AM-uh-chur (American). Collocations: "amateur athlete/photographer/dramatics", "amateur hour" (informal = unprofessional performance). Can be negative: "What an amateur mistake!"' },
      // # ── Adverbs ──
      { word: 'consistently', wordClass: 'adverb', level: 'B1', meaning: 'In a way that is the same every time; reliably and steadily.', context: 'Performance evaluation and habit building.', example: 'She has consistently finished in the top three in every race this season.', explanation: 'The adjective is "consistent" (opposite: "inconsistent"). Collocations: "consistently good/high/improve", "perform consistently". In sport, consistency is often more valued than occasional brilliance — "a consistent performer" delivers results reliably.' },
      { word: 'vigorously', wordClass: 'adverb', level: 'B2', meaning: 'In a way that involves strong, energetic physical effort.', context: 'Exercise intensity and enthusiastic action.', example: 'She exercises vigorously for 30 minutes every morning.', explanation: 'The adjective is "vigorous": "vigorous exercise/debate/campaign". Collocations: "exercise/shake/stir vigorously", "vigorous activity". "Moderate vs vigorous exercise": walking = moderate; running = vigorous. Health guidelines recommend at least 75 minutes of vigorous activity per week.' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 13. ENTERTAINMENT — Expansion
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'entertainment',
    name: 'Entertainment & Media',
    description: 'Vocabulary for films, music, TV, games, and leisure activities.',
    icon: '🎬',
    entries: [
      // # ── Nouns ──
      { word: 'soundtrack', wordClass: 'noun', level: 'B1', meaning: 'The music used in a film, TV show, or video game.', context: 'Film production and music appreciation.', example: 'The film\'s soundtrack won an Oscar for Best Original Score.', explanation: 'Collocations: "movie/film soundtrack", "soundtrack album", "original soundtrack (OST)". Different from "score" (= original music composed for the film) — a "soundtrack" can include pre-existing songs. Famous soundtracks: Titanic, Guardians of the Galaxy, Black Panther.' },
      { word: 'sequel', wordClass: 'noun', level: 'B1', meaning: 'A film, book, or game that continues the story of a previous one.', context: 'Film franchises and publishing.', example: 'The sequel was even better than the original — a rare achievement.', explanation: 'Opposite: "prequel" (= set BEFORE the original). Collocations: "release/make a sequel", "sequel to", "direct sequel" (= continues immediately after). A "trilogy" = 3 parts; "franchise" = a series of many films/products (e.g., Marvel, Star Wars).' },
      { word: 'premiere', wordClass: 'noun', level: 'B2', meaning: 'The first public showing or performance of a film, play, or other work.', context: 'Film releases and theatrical events.', example: 'The cast walked the red carpet at the film\'s world premiere in London.', explanation: 'From French — pronunciation: preh-MEER. Also a verb: "The show premieres on Netflix next Friday." Collocations: "world/UK premiere", "premiere screening/night", "red-carpet premiere". A "premiere" is an event; the actual first showing to the public.' },
      { word: 'genre', wordClass: 'noun', level: 'B1', meaning: 'A category of art, music, or literature with particular style or content.', context: 'Classifying entertainment and personal preferences.', example: 'My favourite film genre is science fiction, but I also enjoy thrillers.', explanation: 'From French — pronunciation: ZHON-ruh. Film genres: action, comedy, drama, horror, thriller, romance, sci-fi, documentary, animation. Music genres: pop, rock, jazz, hip-hop, classical, electronic. Collocations: "genre film/fiction/music", "cross-genre" (= mixing genres).' },
      { word: 'episode', wordClass: 'noun', level: 'A2', meaning: 'One individual part of a television series or podcast.', context: 'TV shows, streaming, and podcast consumption.', example: 'I\'ve only watched the first three episodes of the new season so far.', explanation: 'Collocations: "watch/stream/download an episode", "season/series finale" (= the last episode), "episode one/pilot" (= the first episode). "Binge-watch" = watch many episodes in one sitting. Also general: "an episode of depression/violence" (= an occurrence).' },
      { word: 'celebrity', wordClass: 'noun', level: 'B1', meaning: 'A famous person, especially in entertainment, sport, or media.', context: 'Pop culture and public figures.', example: 'The party was attended by several celebrities from the worlds of film and music.', explanation: 'Informal: "celeb". Collocations: "celebrity status/culture/gossip/chef", "celebrity endorsement" (= a famous person promoting a product), "A-list/B-list celebrity" (= levels of fame). "Celebrity" culture has grown enormously with social media — "influencers" are a new type of celebrity.' },
      // # ── Verbs ──
      { word: 'binge', wordClass: 'verb', level: 'B2', verbForms: { v1: 'binge', v2: 'binged', v3: 'binged' }, meaning: 'To consume a large amount of something in a short period, especially TV shows or food.', context: 'Streaming culture and excessive consumption.', example: 'I binged the entire series in one weekend — all ten episodes.', explanation: 'Collocations: "binge-watch" (= watch many episodes back-to-back), "binge-eat/drink" (= consume excessively), "binge on" (= indulge in). Also a noun: "a binge" or "go on a binge". "Binge-watching" became common with Netflix and streaming platforms.' },
      { word: 'audition', wordClass: 'verb', level: 'B2', verbForms: { v1: 'audition', v2: 'auditioned', v3: 'auditioned' }, meaning: 'To perform a short piece to be considered for a role in a film, play, or show.', context: 'Casting and talent selection.', example: 'She auditioned for the lead role and was offered the part the same day.', explanation: 'Also a noun: "go to/attend an audition", "open audition" (= anyone can try), "callback" (= invited back for a second audition). Collocations: "audition for a role/part", "audition tape" (= a recorded audition). TV shows like The X Factor and The Voice are essentially public auditions.' },
      { word: 'stream', wordClass: 'verb', level: 'B1', verbForms: { v1: 'stream', v2: 'streamed', v3: 'streamed' }, meaning: 'To watch or listen to content over the internet without downloading it.', context: 'Digital entertainment and content consumption.', example: 'You can stream the concert live on the band\'s YouTube channel.', explanation: 'Also a noun: "a live stream", "streaming service" (Netflix, Spotify, Disney+). Collocations: "stream music/films/a game", "streaming platform/service", "live-stream" (= broadcast live). Has largely replaced DVDs and physical media for entertainment consumption.' },
      { word: 'captivate', wordClass: 'verb', level: 'B2', verbForms: { v1: 'captivate', v2: 'captivated', v3: 'captivated' }, meaning: 'To attract and hold someone\'s attention completely through charm or interest.', context: 'Describing engaging performances and stories.', example: 'The documentary captivated audiences worldwide with its stunning footage.', explanation: 'The adjective is "captivating": "a captivating performance/story". Collocations: "captivate audiences/readers", "captivated by". Stronger than "interest" or "engage" — implies being completely absorbed. Related: "captive audience" (= people who have no choice but to listen/watch).' },
      // # ── Adjectives ──
      { word: 'gripping', wordClass: 'adjective', level: 'B2', meaning: 'So exciting or interesting that it holds your attention completely.', context: 'Describing books, films, and TV shows.', example: 'The thriller was so gripping that I couldn\'t put the book down until I finished it.', explanation: 'From "grip" (= hold tightly). Collocations: "gripping story/thriller/drama/documentary". Similar: "riveting" (= equally strong), "compelling" (= powerful and persuasive), "page-turner" (= a book you can\'t stop reading). Opposite: "dull", "tedious", "boring".' },
      { word: 'hilarious', wordClass: 'adjective', level: 'B1', meaning: 'Extremely funny; causing great amusement and laughter.', context: 'Comedy and humorous situations.', example: 'The comedian\'s show was absolutely hilarious — we laughed non-stop for an hour.', explanation: 'Stronger than "funny" — "hilarious" means you laugh out loud. Collocations: "absolutely/genuinely hilarious", "hilarious joke/scene/story". "Hilariously" (adverb): "hilariously funny". "Hilarity" (noun): "The incident caused much hilarity." Used for genuine, deep laughter, not just a smile.' },
      { word: 'overrated', wordClass: 'adjective', level: 'B2', meaning: 'Considered to be better or more important than it actually is.', context: 'Opinions on popular culture and shared experiences.', example: 'I think that film is massively overrated — the plot was predictable and the acting was average.', explanation: 'Opposite: "underrated" (= better than people think). "Overrate" (verb): "People overrate that restaurant." Collocations: "massively/hugely overrated", "overrated film/band/tourist attraction". Saying something is "overrated" is a common way to express a contrarian opinion.' },
      // # ── Adverbs ──
      { word: 'critically', wordClass: 'adverb', level: 'B2', meaning: 'According to professional critics; or in a way involving careful judgement.', context: 'Film/book reviews and analytical thinking.', example: 'The film was critically acclaimed but didn\'t perform well at the box office.', explanation: 'The adjective is "critical". Collocations: "critically acclaimed" (= praised by critics), "critically important/ill" (= very important/seriously ill), "think critically" (= analyse carefully). "Critical" has multiple meanings: professional critique, importance, or danger level.' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 14. SHOPPING & FASHION — Expansion
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'shopping-fashion',
    name: 'Shopping & Fashion',
    description: 'Vocabulary for shopping, clothing, style, and consumer culture.',
    icon: '🛍️',
    entries: [
      // # ── Nouns ──
      { word: 'bargain', wordClass: 'noun', level: 'B1', meaning: 'Something bought at a lower price than usual; a good deal.', context: 'Sales shopping and negotiation.', example: 'I got this jacket for half price — what a bargain!', explanation: 'Also a verb: "They bargained over the price." Collocations: "a real/absolute bargain", "bargain hunter" (= someone who looks for deals), "bargain basement" (= the cheapest section of a store). "Into the bargain" (British) = also, in addition: "She got the job, and a pay rise into the bargain."' },
      { word: 'warranty', wordClass: 'noun', level: 'B2', meaning: 'A written guarantee from the manufacturer to repair or replace a product within a specified period.', context: 'Electronics purchases and consumer protection.', example: 'The laptop comes with a two-year warranty covering all manufacturing defects.', explanation: 'Different from "guarantee" (more general promise of quality) — a "warranty" is specifically about repair/replacement. Collocations: "under warranty" (= still within the warranty period), "extended warranty" (= paying extra for longer coverage), "warranty period/claim".' },
      { word: 'brand', wordClass: 'noun', level: 'A2', meaning: 'A type of product made by a particular company under a specific name.', context: 'Consumer choices and marketing.', example: 'Nike is one of the most recognisable brands in the world.', explanation: 'Collocations: "brand name/awareness/loyalty/identity", "own-brand" (British) / "store-brand" (American) = the supermarket\'s own products. "Branding" = creating a distinctive identity. "Brand ambassador" = a person who represents a brand. "Off-brand" = not a well-known brand.' },
      { word: 'textile', wordClass: 'noun', level: 'B2', meaning: 'A type of woven or knitted fabric or cloth.', context: 'Fashion industry and materials.', example: 'The fashion industry is one of the largest consumers of textiles worldwide.', explanation: 'Collocations: "textile industry/factory/production", "textile worker", "sustainable textiles". Common textiles: cotton, silk, wool, linen, polyester, nylon, denim. "Textile recycling" = reusing old clothing and fabric.' },
      { word: 'receipt', wordClass: 'noun', level: 'A2', meaning: 'A written acknowledgement of payment, needed for returns and exchanges.', context: 'Shopping transactions and returns policies.', example: 'You\'ll need the receipt if you want to exchange or return the item.', explanation: 'Silent "p" — pronounced rih-SEET. Collocations: "keep/save the receipt", "gift receipt" (= receipt without the price, for gift returns), "digital/email receipt". Different from "invoice" (= a bill requesting payment). Most stores require the original receipt for refunds.' },
      // # ── Verbs ──
      { word: 'browse', wordClass: 'verb', level: 'B1', verbForms: { v1: 'browse', v2: 'browsed', v3: 'browsed' }, meaning: 'To look casually through items in a shop or on a website without a specific purchase in mind.', context: 'Shopping and internet use.', example: 'I spent an hour browsing the shops but didn\'t buy anything.', explanation: 'A "browser" is both a person who browses AND software for viewing websites (Chrome, Firefox, Safari). Collocations: "browse through", "just browsing" (what you say when a shop assistant asks if you need help), "browse online/the internet".' },
      { word: 'refund', wordClass: 'verb', level: 'B1', verbForms: { v1: 'refund', v2: 'refunded', v3: 'refunded' }, meaning: 'To give back money to a customer, usually because the product was faulty or unsatisfactory.', context: 'Consumer rights and returns.', example: 'They refunded the full amount after the item arrived damaged.', explanation: 'Also a noun: "get/request a refund". Stress: noun = REE-fund, verb = rih-FUND. Collocations: "full/partial refund", "refund policy" (= the store\'s rules about giving money back), "non-refundable" (= money that cannot be returned, e.g., "non-refundable deposit").' },
      { word: 'tailor', wordClass: 'verb', level: 'B2', verbForms: { v1: 'tailor', v2: 'tailored', v3: 'tailored' }, meaning: 'To make or adapt something for a particular purpose or person.', context: 'Custom clothing and personalised services.', example: 'We can tailor the training programme to meet your specific needs.', explanation: 'Also a noun: "a tailor" (= someone who makes or alters clothing). Collocations: "tailor-made/tailored" (= custom-made for you), "tailored suit" (= a suit made to fit you perfectly), "tailor something to someone\'s needs". "Bespoke" (British) = custom-made, especially for clothing.' },
      // # ── Adjectives ──
      { word: 'affordable', wordClass: 'adjective', level: 'B1', meaning: 'Reasonably priced; not too expensive for most people to buy.', context: 'Price discussions and budget shopping.', example: 'The store offers stylish clothing at affordable prices.', explanation: 'Collocations: "affordable housing/prices/options", "more/less affordable". Opposite: "unaffordable". "Affordability" (noun): "housing affordability" = whether people can afford to buy/rent homes. More positive than "cheap" (which can imply low quality).' },
      { word: 'second-hand', wordClass: 'adjective', level: 'A2', meaning: 'Previously owned or used by someone else; not new.', context: 'Sustainable shopping and budget choices.', example: 'I bought a second-hand car that was in excellent condition.', explanation: 'Also written "secondhand". Collocations: "second-hand shop/store" (= charity shop/thrift store), "second-hand car/clothes/books". "Pre-owned" = the same thing but sounds more upscale (used by car dealers). "Second-hand smoke" = inhaling someone else\'s cigarette smoke.' },
      { word: 'trendy', wordClass: 'adjective', level: 'B1', meaning: 'Very fashionable and popular at the current time.', context: 'Fashion trends and popular culture.', example: 'The neighbourhood has become very trendy, with lots of cool cafés and boutiques.', explanation: 'Slightly informal. "A trendsetter" = someone who starts new trends. Collocations: "trendy café/restaurant/neighbourhood/clothes", "trendy area". Can be slightly negative: "She\'s just being trendy" (= following trends without genuine interest). "Trendy" implies temporary popularity.' },
      { word: 'counterfeit', wordClass: 'adjective', level: 'B2', meaning: 'Made as an exact imitation to deceive; fake.', context: 'Consumer protection and brand piracy.', example: 'Customs officers seized thousands of counterfeit designer handbags at the port.', explanation: 'Also a noun and verb: "a counterfeit" (the fake item), "to counterfeit money" (= to make fake money — a crime). Collocations: "counterfeit goods/money/products", "counterfeit market". "Knock-off" (informal) = a cheap copy of a branded item.' },
      // # ── Adverbs ──
      { word: 'impulsively', wordClass: 'adverb', level: 'B2', meaning: 'In a way that is done suddenly without careful thought.', context: 'Shopping behaviour and personality traits.', example: 'She impulsively bought a designer dress that she couldn\'t really afford.', explanation: 'The adjective is "impulsive" and the noun is "impulse". Collocations: "act/buy impulsively", "impulse purchase/buy" (= something bought without planning), "on impulse" (= without thinking). Retailers place small items near the checkout to encourage "impulse buying".' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 15. EMOTIONS & FEELINGS — Expansion
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'emotions',
    name: 'Emotions & Feelings',
    description: 'Vocabulary for expressing emotions, moods, and psychological states.',
    icon: '💭',
    entries: [
      // # ── Nouns ──
      { word: 'anxiety', wordClass: 'noun', level: 'B1', meaning: 'A feeling of worry, nervousness, or unease about something with an uncertain outcome.', context: 'Mental health, exams, and stressful situations.', example: 'She experiences anxiety before exams, which makes it hard for her to concentrate.', explanation: 'The adjective is "anxious". Collocations: "anxiety disorder" (= a clinical condition), "suffer from/experience anxiety", "anxiety attack" (= a sudden episode of intense worry), "separation anxiety" (children\'s fear of being away from parents). Different from "stress" (= pressure) — "anxiety" is specifically about worry.' },
      { word: 'grief', wordClass: 'noun', level: 'B2', meaning: 'Deep sadness caused by loss, especially the death of someone you love.', context: 'Bereavement and emotional processing.', example: 'She was overwhelmed with grief after losing her mother.', explanation: 'Uncountable. "Grieve" (verb): "She\'s still grieving for her husband." "Bereaved" = someone who has recently lost a loved one. Collocations: "overcome with grief", "grief-stricken" (= deeply affected by grief), "stages of grief" (denial, anger, bargaining, depression, acceptance).' },
      { word: 'empathy', wordClass: 'noun', level: 'B2', meaning: 'The ability to understand and share the feelings of another person.', context: 'Emotional intelligence and interpersonal relationships.', example: 'Good leaders show empathy by understanding what their team members are going through.', explanation: 'Different from "sympathy" (= feeling sorry FOR someone) — "empathy" = feeling WITH someone, as if you were in their situation. "Empathise" (verb), "empathetic" or "empathic" (adjective). Collocations: "show/feel/lack empathy", "empathy for someone".' },
      { word: 'resentment', wordClass: 'noun', level: 'B2', meaning: 'A feeling of bitter anger or ill-will towards someone who has treated you unfairly.', context: 'Relationship conflicts and workplace tensions.', example: 'Years of being overlooked for promotion caused deep resentment towards his manager.', explanation: 'The verb is "resent" and the adjective is "resentful". Collocations: "harbour/feel/build resentment", "deep/growing resentment". Different from "anger" (often short-lived) — "resentment" simmers over time. "I resent that remark" = I feel offended by it.' },
      { word: 'contentment', wordClass: 'noun', level: 'B2', meaning: 'A state of peaceful happiness and satisfaction.', context: 'Life satisfaction and mindfulness.', example: 'After years of chasing success, she finally found contentment in a simpler life.', explanation: 'The adjective is "content" or "contented". Collocations: "a sense/feeling of contentment", "find contentment". More quiet and lasting than "happiness" — "contentment" is a calm, deep satisfaction. "Content" (adjective): "I\'m content with what I have" (= satisfied, not needing more).' },
      { word: 'nostalgia', wordClass: 'noun', level: 'B2', meaning: 'A sentimental longing for the past, especially for a period or place with happy associations.', context: 'Memories, ageing, and cultural references.', example: 'Looking at old photos always fills me with nostalgia for my school days.', explanation: 'The adjective is "nostalgic": "I feel nostalgic about my childhood." Collocations: "a sense/wave of nostalgia", "nostalgia for the past", "nostalgia trip" (= revisiting past memories). From Greek "nostos" (return home) + "algos" (pain). Originally a medical term for extreme homesickness.' },
      // # ── Verbs ──
      { word: 'resent', wordClass: 'verb', level: 'B2', verbForms: { v1: 'resent', v2: 'resented', v3: 'resented' }, meaning: 'To feel bitterness or anger towards someone because of their actions or good fortune.', context: 'Interpersonal conflict and unfair treatment.', example: 'She resented being asked to do all the extra work while her colleagues left on time.', explanation: 'The noun is "resentment" and the adjective is "resentful". Collocations: "resent someone/something", "resent being treated unfairly", "bitterly resent". "I resent that" = I take offence. Not to be confused with "re-sent" (= sent again).' },
      { word: 'overwhelm', wordClass: 'verb', level: 'B2', verbForms: { v1: 'overwhelm', v2: 'overwhelmed', v3: 'overwhelmed' }, meaning: 'To affect someone so strongly that they feel unable to cope; to overpower.', context: 'Emotional intensity and excessive demands.', example: 'She was completely overwhelmed by the kindness of strangers after the accident.', explanation: 'The adjective is "overwhelming": "overwhelming majority/support/evidence". Collocations: "feel overwhelmed", "overwhelmed with emotion/work/grief", "overwhelmingly positive/negative". Can be positive (overwhelmed with joy/gratitude) or negative (overwhelmed with stress/work).' },
      { word: 'dread', wordClass: 'verb', level: 'B2', verbForms: { v1: 'dread', v2: 'dreaded', v3: 'dreaded' }, meaning: 'To fear something that is going to happen; to look forward to something with great anxiety.', context: 'Anticipating unpleasant experiences.', example: 'I dread Monday mornings — the thought of going back to work fills me with anxiety.', explanation: 'Also a noun: "a feeling/sense of dread", "filled with dread". Collocations: "dread to think" (= I\'m afraid to imagine), "the dreaded" (= the feared thing: "the dreaded exam results"), "dreadful" (adjective — terrible: "dreadful weather").' },
      { word: 'cherish', wordClass: 'verb', level: 'B2', verbForms: { v1: 'cherish', v2: 'cherished', v3: 'cherished' }, meaning: 'To hold something or someone dear; to value highly and protect lovingly.', context: 'Relationships, memories, and treasured possessions.', example: 'She cherishes the letters her grandmother wrote to her during the war.', explanation: 'Collocations: "cherish memories/moments/a friendship", "cherished possession/memory", "to have and to cherish" (from traditional wedding vows). Implies deep, lasting value — not just "like" but profound appreciation. "Cherished" = greatly valued and protected.' },
      { word: 'suppress', wordClass: 'verb', level: 'B2', verbForms: { v1: 'suppress', v2: 'suppressed', v3: 'suppressed' }, meaning: 'To hold back or prevent the expression of a feeling, reaction, or piece of information.', context: 'Emotional control and censorship.', example: 'He tried to suppress his laughter during the serious meeting.', explanation: 'The noun is "suppression". Collocations: "suppress a smile/laugh/yawn/feeling", "suppress evidence/information" (= hide it), "suppress a rebellion" (= end it by force). Different from "repress" (= push emotions deep into the unconscious — a psychological term). "Suppressed anger" can lead to health problems.' },
      // # ── Adjectives ──
      { word: 'overwhelmed', wordClass: 'adjective', level: 'B2', meaning: 'Completely overcome emotionally; feeling unable to cope.', context: 'Emotional reactions and excessive demands.', example: 'I felt completely overwhelmed on my first day at the new job — there was so much to learn.', explanation: 'Collocations: "feel overwhelmed", "overwhelmed by/with work/emotion/gratitude". Different from "stressed" (= under pressure) — "overwhelmed" = it\'s TOO MUCH, you can\'t handle it. Very common in modern English to describe work/life imbalance.' },
      { word: 'nostalgic', wordClass: 'adjective', level: 'B2', meaning: 'Feeling or inspiring a longing for the past.', context: 'Memories and sentimental reflection.', example: 'The old song made me feel nostalgic for my university days.', explanation: 'Collocations: "feel/get nostalgic", "nostalgic about/for", "a nostalgic look/feeling/trip". Can describe both the person ("I feel nostalgic") and the thing ("a nostalgic song/film"). "Nostalgically" (adverb): "She looked back nostalgically on her childhood."' },
      { word: 'bitter', wordClass: 'adjective', level: 'B1', meaning: 'Feeling angry, hurt, and resentful because of bad experiences or unfair treatment.', context: 'Disappointment and lingering negative feelings.', example: 'He\'s still bitter about being passed over for the promotion.', explanation: 'Multiple meanings: 1) Emotional: "bitter and resentful"; 2) Taste: "bitter coffee" (opposite of sweet); 3) Weather: "bitter cold"; 4) Intense: "bitter rivals/enemies". Collocations: "bitter disappointment/experience/defeat", "to the bitter end" (= until it\'s completely over).' },
      { word: 'ecstatic', wordClass: 'adjective', level: 'B2', meaning: 'Feeling overwhelming happiness or joyful excitement.', context: 'Extreme positive emotions and celebrations.', example: 'She was absolutely ecstatic when she got the job offer from her dream company.', explanation: 'Stronger than "happy" or even "delighted". The noun is "ecstasy": "a feeling of ecstasy." Collocations: "absolutely ecstatic", "ecstatic about/at", "ecstatic fans/crowd/reception". "Ecstasy" is also the name of an illegal drug (MDMA).' },
      { word: 'indifferent', wordClass: 'adjective', level: 'B2', meaning: 'Having no particular interest, care, or concern about something.', context: 'Apathy and lack of emotional engagement.', example: 'He seemed completely indifferent to the result — he didn\'t care whether he won or lost.', explanation: 'The noun is "indifference". Collocations: "indifferent to/about", "completely/totally indifferent", "an air of indifference" (= appearing not to care). Different from "neutral" (= balanced between options) — "indifferent" implies genuine lack of caring.' },
      // # ── Adverbs ──
      { word: 'bitterly', wordClass: 'adverb', level: 'B2', meaning: 'In a way that shows strong negative emotions; extremely (especially cold).', context: 'Intense disappointment and severe cold.', example: 'She cried bitterly when she heard the news. It was bitterly cold outside.', explanation: 'Collocations: "bitterly disappointed/cold/regret", "bitterly opposed to" (= strongly against), "weep/cry bitterly". "Bitterly cold" is a very common weather phrase. "Bitterly" intensifies negative emotions and conditions.' },
      { word: 'genuinely', wordClass: 'adverb', level: 'B1', meaning: 'In a way that is truly sincere and honest; really.', context: 'Expressing authentic feelings and opinions.', example: 'I\'m genuinely happy for you — you really deserve this success.', explanation: 'The adjective is "genuine" (opposite: "fake", "insincere"). Collocations: "genuinely interested/surprised/happy/concerned", "genuine article" (= the real thing, not a copy), "genuine person" (= sincere, not pretending). Useful when you want to emphasise that your feelings are real.' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 16. WEATHER & CLIMATE — Expansion
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'weather',
    name: 'Weather & Climate',
    description: 'Vocabulary for weather conditions, climate patterns, and natural phenomena.',
    icon: '🌦️',
    entries: [
      // # ── Nouns ──
      { word: 'forecast', wordClass: 'noun', level: 'B1', meaning: 'A prediction of future weather conditions based on scientific data.', context: 'Planning activities and travel decisions.', example: 'According to the forecast, it will rain all weekend.', explanation: 'Also a verb: "They forecast heavy rain for tomorrow." Collocations: "weather forecast", "five-day/weekly forecast", "the forecast says/predicts". A "forecaster" or "meteorologist" is the person who predicts the weather. Different from "climate" (= long-term average weather).' },
      { word: 'heatwave', wordClass: 'noun', level: 'B1', meaning: 'A prolonged period of unusually hot weather.', context: 'Summer extremes and climate change.', example: 'The heatwave lasted three weeks, with temperatures exceeding 35°C every day.', explanation: 'Also written "heat wave". Collocations: "severe/prolonged heatwave", "heatwave warning", "during the heatwave". Climate change is making heatwaves more frequent and intense. Opposite: "cold snap" (= a sudden period of very cold weather).' },
      { word: 'blizzard', wordClass: 'noun', level: 'B2', meaning: 'A severe snowstorm with strong winds and reduced visibility.', context: 'Winter extremes and dangerous weather.', example: 'The blizzard brought 50cm of snow and winds gusting to 100 km/h.', explanation: 'More severe than a "snowstorm". Collocations: "caught in a blizzard", "blizzard conditions/warning". A blizzard requires: heavy snow + winds over 56 km/h + visibility under 400m. Figurative: "a blizzard of emails" (= an overwhelming number).' },
      { word: 'humidity', wordClass: 'noun', level: 'B2', meaning: 'The amount of water vapour in the air.', context: 'Tropical climates and comfort levels.', example: 'The humidity in Bangkok can be exhausting — the air feels thick and heavy.', explanation: 'The adjective is "humid": "It\'s very humid today." Collocations: "high/low humidity", "relative humidity" (measured as a percentage), "the heat and humidity". "Humid" weather feels hotter than it is because sweat doesn\'t evaporate easily. "Muggy" = unpleasantly warm and humid.' },
      { word: 'breeze', wordClass: 'noun', level: 'A2', meaning: 'A gentle, pleasant wind.', context: 'Nice weather and comfortable conditions.', example: 'There was a lovely cool breeze coming off the sea.', explanation: 'Collocations: "gentle/cool/warm/sea breeze", "a slight breeze". "Breezy" (adjective) = slightly windy, or casual/carefree: "a breezy attitude". Also informal: "It was a breeze" = it was very easy. Stronger winds: "breeze" → "wind" → "gale" → "storm" → "hurricane".' },
      // # ── Verbs ──
      { word: 'drizzle', wordClass: 'verb', level: 'B1', verbForms: { v1: 'drizzle', v2: 'drizzled', v3: 'drizzled' }, meaning: 'To rain lightly in very fine drops.', context: 'Mild wet weather and cooking (drizzling oil).', example: 'It\'s been drizzling all morning — not proper rain, just fine mist.', explanation: 'Also a noun: "a light drizzle". Rain intensity: drizzle → shower → rain → downpour → torrential rain. Collocations: "light drizzle", "it\'s drizzling". In cooking: "drizzle olive oil over the salad" (= pour a thin stream).' },
      { word: 'pour', wordClass: 'verb', level: 'A2', verbForms: { v1: 'pour', v2: 'poured', v3: 'poured' }, meaning: 'To rain very heavily; also to flow or cause liquid to flow.', context: 'Heavy rain and liquid handling.', example: 'It\'s absolutely pouring outside — you\'ll need an umbrella.', explanation: 'Collocations: "it\'s pouring (with rain)", "pouring rain", "it never rains but it pours" (proverb = problems always come together). Also: "pour a drink/tea/coffee", "pour into/out of". "Pouring down" and "bucketing down" both mean raining extremely heavily.' },
      { word: 'melt', wordClass: 'verb', level: 'A2', verbForms: { v1: 'melt', v2: 'melted', v3: 'melted' }, meaning: 'To change from solid to liquid by heating; for ice or snow to become water.', context: 'Temperature changes and climate impact.', example: 'The snow started to melt as the temperature rose above freezing.', explanation: 'Opposite: "freeze" (liquid → solid). Collocations: "melt ice/snow/chocolate/butter", "melting point" (= temperature at which a solid melts), "melt in your mouth" (= food so tender it dissolves). "Ice caps/glaciers are melting" = a key climate change issue.' },
      { word: 'gust', wordClass: 'verb', level: 'B2', verbForms: { v1: 'gust', v2: 'gusted', v3: 'gusted' }, meaning: 'To blow in sudden, strong bursts.', context: 'Stormy weather and wind descriptions.', example: 'Winds gusted up to 120 km/h during the storm, bringing down trees and power lines.', explanation: 'Also a noun: "a gust of wind". Collocations: "gusting to X mph/km/h", "strong gusts", "gusty winds". Weather forecasts often say: "winds of 40 mph with gusts up to 60 mph" — meaning the wind speed increases in short bursts.' },
      // # ── Adjectives ──
      { word: 'overcast', wordClass: 'adjective', level: 'B1', meaning: 'Covered with clouds; having a grey, cloudy sky.', context: 'Daily weather descriptions.', example: 'The sky was overcast all day, but it never actually rained.', explanation: 'Collocations: "overcast sky/day", "grey and overcast". Different from "cloudy" (some clouds) — "overcast" means the ENTIRE sky is covered. "The sky is overcast" is a common weather report phrase. Opposite: "clear" or "cloudless".' },
      { word: 'scorching', wordClass: 'adjective', level: 'B2', meaning: 'Extremely hot; burning.', context: 'Describing very hot weather or temperatures.', example: 'We stayed indoors during the scorching afternoon heat and went out in the evening.', explanation: 'Collocations: "scorching heat/temperatures/sun", "scorching hot". Temperature adjectives (from cold to hot): freezing → chilly → cool → mild → warm → hot → boiling → scorching. "Scorching" implies uncomfortably, almost painfully hot.' },
      { word: 'torrential', wordClass: 'adjective', level: 'B2', meaning: 'Falling in large amounts with great force (describing rain).', context: 'Extreme rainfall and flood warnings.', example: 'Torrential rain caused widespread flooding across the region.', explanation: 'Almost exclusively used with "rain": "torrential rain/rainfall/downpour". Implies rain so heavy it causes problems (flooding, landslides). "A torrent" (noun) = a powerful, fast-flowing stream. Figurative: "a torrent of abuse/criticism" (= an overwhelming flood of negative words).' },
      { word: 'mild', wordClass: 'adjective', level: 'A2', meaning: 'Neither too hot nor too cold; pleasantly moderate in temperature.', context: 'Describing comfortable weather conditions.', example: 'The winters here are relatively mild — it rarely drops below 5°C.', explanation: 'Collocations: "mild weather/winter/temperature/climate". Also means: "not severe": "mild symptoms/illness" (= not too bad), "mild cheese/curry" (= not strong-flavoured). "Mild-mannered" = gentle and not aggressive. Opposite (for weather): "harsh" or "severe".' },
      // # ── Adverbs ──
      { word: 'intermittently', wordClass: 'adverb', level: 'B2', meaning: 'Stopping and starting at irregular intervals; not continuously.', context: 'Describing on-and-off weather and irregular patterns.', example: 'It rained intermittently throughout the day — sunshine, then rain, then sunshine again.', explanation: 'The adjective is "intermittent": "intermittent rain/showers/signal". Collocations: "intermittently rain/work/appear". More precise than "on and off" or "from time to time" — implies random, unpredictable stops and starts. Very useful in weather descriptions and technical writing.' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 17. FAMILY & RELATIONSHIPS — Expansion
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'family',
    name: 'Family & Relationships',
    description: 'Vocabulary for family structures, relationships, and life stages.',
    icon: '👨‍👩‍👧‍👦',
    entries: [
      // # ── Nouns ──
      { word: 'sibling', wordClass: 'noun', level: 'B1', meaning: 'A brother or sister.', context: 'Family structures and formal descriptions.', example: 'She has three siblings — two brothers and one sister.', explanation: 'Formal/neutral — used when you don\'t want to specify gender. Collocations: "older/younger sibling", "sibling rivalry" (= competition between brothers/sisters), "half-sibling" (= shared one parent), "step-sibling" (= related through a parent\'s new marriage). Medical forms often ask: "Number of siblings?"' },
      { word: 'spouse', wordClass: 'noun', level: 'B2', meaning: 'A husband or wife; a married partner.', context: 'Legal documents and formal contexts.', example: 'Both the applicant and their spouse must provide identification.', explanation: 'Gender-neutral and formal. Used on official forms, in legal documents, and professional contexts. "Partner" is more commonly used in everyday conversation and includes unmarried couples. Collocations: "former spouse" (= ex-husband/wife), "surviving spouse" (= the one who outlives the other).' },
      { word: 'guardian', wordClass: 'noun', level: 'B2', meaning: 'A person legally responsible for caring for a child who is not their own.', context: 'Legal custody and child protection.', example: 'After both parents passed away, the children\'s uncle became their legal guardian.', explanation: 'Collocations: "legal guardian", "appoint a guardian", "parent or guardian" (common on school/medical forms). Different from "foster parent" (= temporary care, often arranged by the state). "Guardianship" = the legal responsibility of being a guardian.' },
      { word: 'upbringing', wordClass: 'noun', level: 'B2', meaning: 'The way a child is cared for, educated, and raised.', context: 'Personal background and development.', example: 'She credits her strict upbringing for her strong work ethic.', explanation: 'Usually singular: "a strict/happy/difficult upbringing". The verb is "bring up": "She was brought up in a small village" (British). Americans say "raise": "She was raised in a small town." Collocations: "religious/privileged/deprived upbringing". Very common in IELTS Speaking Part 2.' },
      { word: 'offspring', wordClass: 'noun', level: 'B2', meaning: 'A person\'s child or children; the young of an animal.', context: 'Formal/scientific descriptions of children.', example: 'The survey asked how many offspring each family had.', explanation: 'Same form singular and plural: "one offspring", "three offspring". More formal/scientific than "children". Collocations: "produce/raise offspring", "male/female offspring". In genetics: "The offspring inherits traits from both parents."' },
      // # ── Verbs ──
      { word: 'bond', wordClass: 'verb', level: 'B2', verbForms: { v1: 'bond', v2: 'bonded', v3: 'bonded' }, meaning: 'To develop a close emotional connection with someone.', context: 'Family relationships, new parents, and team building.', example: 'New mothers often bond with their babies through skin-to-skin contact.', explanation: 'Also a noun: "a strong bond between mother and child". Collocations: "bond with someone", "bonding experience/activity", "parent-child bonding". "Male bonding" = men building friendships through shared activities. "Bond" also means a financial instrument or a promise (as in James Bond\'s licence).' },
      { word: 'nurture', wordClass: 'verb', level: 'B2', verbForms: { v1: 'nurture', v2: 'nurtured', v3: 'nurtured' }, meaning: 'To care for and encourage the growth and development of someone.', context: 'Parenting, education, and talent development.', example: 'Parents need to nurture their children\'s natural curiosity and creativity.', explanation: 'Also a noun: "nature vs nurture" (the famous debate about genetics vs upbringing). Collocations: "nurture talent/relationships/growth", "nurturing environment/parent". "Nurture" implies providing emotional warmth and encouragement, not just physical care. "Nurturing" (adjective) = caring and supportive.' },
      { word: 'resemble', wordClass: 'verb', level: 'B1', verbForms: { v1: 'resemble', v2: 'resembled', v3: 'resembled' }, meaning: 'To look like or be similar to someone or something.', context: 'Family likeness and comparisons.', example: 'She closely resembles her mother — they have the same eyes and smile.', explanation: 'The noun is "resemblance": "There\'s a strong resemblance between the two sisters." Collocations: "closely/strongly resemble", "bear a resemblance to" (= look like). Don\'t use passive: say "She resembles her mother" NOT "She is resembled by her mother."' },
      { word: 'inherit', wordClass: 'verb', level: 'B1', verbForms: { v1: 'inherit', v2: 'inherited', v3: 'inherited' }, meaning: 'To receive something from a family member after they die; to have traits passed down genetically.', context: 'Family wealth and genetic characteristics.', example: 'She inherited her grandmother\'s house, and her father\'s blue eyes.', explanation: 'The noun is "inheritance" (= money/property received after someone\'s death) and "heredity" (= genetic passing of traits). Collocations: "inherit money/property/traits/genes", "inherited condition/disease". "Heir" (noun) = the person who will inherit. "Heritage" = cultural inheritance.' },
      // # ── Adjectives ──
      { word: 'devoted', wordClass: 'adjective', level: 'B2', meaning: 'Very loving and loyal; giving a lot of time and energy to someone.', context: 'Describing committed family members and partners.', example: 'He was a devoted father who always put his children\'s needs first.', explanation: 'Collocations: "devoted husband/wife/parent/fan", "devoted to someone/something". The verb is "devote": "She devoted her life to charity." "Devotion" (noun) = deep love and commitment. Stronger than "loyal" — implies deep emotional investment.' },
      { word: 'estranged', wordClass: 'adjective', level: 'C1', meaning: 'No longer close to someone you were once close to, especially a family member.', context: 'Family conflicts and relationship breakdowns.', example: 'He hadn\'t spoken to his estranged brother in over ten years.', explanation: 'The noun is "estrangement". Collocations: "estranged from", "estranged wife/husband/father/family member". Implies a painful separation, usually due to conflict or disagreement. "Become estranged" = gradually lose contact and closeness due to problems.' },
      { word: 'supportive', wordClass: 'adjective', level: 'B1', meaning: 'Providing emotional help, encouragement, and practical assistance.', context: 'Family dynamics, friendships, and workplace culture.', example: 'My parents have always been incredibly supportive of my career choices.', explanation: 'Collocations: "supportive family/partner/friend/environment", "supportive of someone/something", "emotionally supportive". Very positive. Opposite: "unsupportive". "Support" (noun/verb): "I appreciate your support." "Support network" = the people who help you.' },
      // # ── Adverbs ──
      { word: 'unconditionally', wordClass: 'adverb', level: 'B2', meaning: 'Without any conditions, limits, or requirements.', context: 'Describing absolute love and commitment.', example: 'Parents should love their children unconditionally, regardless of their achievements.', explanation: 'The adjective is "unconditional": "unconditional love/support/surrender". Collocations: "love/accept/support unconditionally". "Unconditional love" = loving someone no matter what they do. One of the most important concepts in parenting and relationship psychology.' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 18. HOUSING & PROPERTY — Expansion
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'housing',
    name: 'Housing & Property',
    description: 'Vocabulary for homes, property, renting, buying, and neighbourhood life.',
    icon: '🏡',
    entries: [
      // # ── Nouns ──
      { word: 'lease', wordClass: 'noun', level: 'B2', meaning: 'A legal contract allowing someone to use a property for a set period in exchange for rent.', context: 'Renting accommodation and commercial property.', example: 'We signed a 12-month lease on the flat, starting from the 1st of September.', explanation: 'Also a verb: "They leased the building to a tech company." Collocations: "sign/renew/break a lease", "lease agreement/term", "short-term/long-term lease". "Break a lease" = end it early (may incur penalties). "Leasehold" = you own the property but not the land it sits on (common in England).' },
      { word: 'deposit', wordClass: 'noun', level: 'B1', meaning: 'A sum of money paid in advance as security or to reserve something.', context: 'Renting, buying, and reservations.', example: 'We paid a £1,000 deposit on the flat, which is returned when we leave.', explanation: 'Types: "rental/security deposit" (returned if no damage), "house deposit" (down payment for buying), "reservation deposit" (to hold a booking). Collocations: "pay/put down a deposit", "deposit scheme" (UK — tenancy deposit protection). Also banking: "make a deposit" (= put money into an account).' },
      { word: 'renovations', wordClass: 'noun', level: 'B2', meaning: 'Repairs, improvements, and updates made to a building.', context: 'Home improvement and property investment.', example: 'The house needs major renovations — the kitchen and bathroom are from the 1970s.', explanation: 'Usually plural. The verb is "renovate". Collocations: "major/minor renovations", "home/building renovations", "renovation project/budget", "under renovation" (= currently being renovated). Different from "repairs" (= fixing what\'s broken) — "renovations" = improving and modernising.' },
      { word: 'neighbourhood', wordClass: 'noun', level: 'A2', meaning: 'The area surrounding a particular place; the local community.', context: 'Describing where you live and community identity.', example: 'It\'s a quiet, family-friendly neighbourhood with good schools nearby.', explanation: 'British: "neighbourhood". American: "neighborhood". Collocations: "residential/quiet/rough neighbourhood", "in the neighbourhood" (= nearby), "neighbourhood watch" (= local residents cooperating to prevent crime). "Neighbour" = someone who lives near you.' },
      { word: 'insulation', wordClass: 'noun', level: 'B2', meaning: 'Material used to prevent heat, cold, or sound from passing through walls, floors, or ceilings.', context: 'Energy efficiency and building standards.', example: 'Installing proper loft insulation can reduce your heating bills by up to 25%.', explanation: 'The verb is "insulate". Collocations: "loft/wall/sound insulation", "thermal insulation", "insulation material". "Well-insulated" = keeps heat in/out effectively. Increasingly important for energy efficiency and reducing carbon emissions. "Double glazing" (= two panes of glass in windows) is a form of insulation.' },
      // # ── Verbs ──
      { word: 'relocate', wordClass: 'verb', level: 'B2', verbForms: { v1: 'relocate', v2: 'relocated', v3: 'relocated' }, meaning: 'To move to a different place to live or work.', context: 'Job transfers and changing homes.', example: 'The company offered to cover all costs if she agreed to relocate to the London office.', explanation: 'The noun is "relocation". Collocations: "relocate to another city/country", "relocation package" (= company benefits for moving), "willing to relocate" (common on job applications). More formal than "move" — implies significant change, often work-related.' },
      { word: 'demolish', wordClass: 'verb', level: 'B2', verbForms: { v1: 'demolish', v2: 'demolished', v3: 'demolished' }, meaning: 'To completely destroy a building or structure.', context: 'Urban development and building replacement.', example: 'The old factory was demolished to make way for a new housing development.', explanation: 'The noun is "demolition". Collocations: "demolish a building/house/wall", "demolition site/crew/work". Also figurative: "She demolished his argument" (= completely disproved it), "He demolished a pizza" (informal = ate it all quickly). "Condemned for demolition" = officially scheduled to be torn down.' },
      { word: 'refurbish', wordClass: 'verb', level: 'B2', verbForms: { v1: 'refurbish', v2: 'refurbished', v3: 'refurbished' }, meaning: 'To renovate and redecorate a building or room to improve its condition.', context: 'Property improvement and restoration.', example: 'The hotel was completely refurbished last year and now looks brand new.', explanation: 'The noun is "refurbishment". Collocations: "recently/completely refurbished", "refurbished flat/office", "undergo refurbishment". Similar to "renovate" but often implies cosmetic improvement rather than structural work. Also: "refurbished phone/laptop" (= returned, repaired, and resold).' },
      // # ── Adjectives ──
      { word: 'detached', wordClass: 'adjective', level: 'B1', meaning: 'Not joined to another building on either side.', context: 'House types and property descriptions.', example: 'They bought a four-bedroom detached house with a large garden.', explanation: 'UK house types: "detached" (stands alone), "semi-detached" (= joined to one other house), "terraced" (= joined in a row of houses), "flat/apartment" (= one level within a building). Collocations: "detached house/property/garage". Also means emotionally distant: "She seemed oddly detached from the situation."' },
      { word: 'run-down', wordClass: 'adjective', level: 'B1', meaning: 'In poor condition due to neglect; not maintained.', context: 'Describing neglected properties and areas.', example: 'The building looked quite run-down — paint was peeling and windows were broken.', explanation: 'Collocations: "run-down building/area/neighbourhood/estate". Implies neglect over time. "Run down" (verb, two words): "He ran down the hill" or "Don\'t run yourself down" (= don\'t criticise yourself). Can describe people too: "I\'m feeling a bit run-down" (= tired and unwell).' },
      { word: 'vacant', wordClass: 'adjective', level: 'B2', meaning: 'Empty; not occupied or being used.', context: 'Property listings and availability.', example: 'There are several vacant flats in the building — shall we view one?', explanation: 'The noun is "vacancy": "No vacancies" (= no rooms/jobs available). Collocations: "vacant property/lot/position", "fall vacant" (= become empty/available). "Vacant" also means blank/empty-looking: "a vacant expression/stare" (= looking at nothing, showing no thought).' },
      // # ── Adverbs ──
      { word: 'conveniently', wordClass: 'adverb', level: 'B1', meaning: 'In a way that fits well with someone\'s needs or plans; without difficulty.', context: 'Location advantages and easy access.', example: 'The flat is conveniently located near the train station and local shops.', explanation: 'The adjective is "convenient" (opposite: "inconvenient"). Collocations: "conveniently located/situated/placed", "convenient for transport/shops". Also slightly negative: "He conveniently forgot to mention the extra costs" (= deliberately forgot because it suited him).' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 19. TRANSPORT — Expansion
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'transport',
    name: 'Transport & Travel',
    description: 'Vocabulary for vehicles, journeys, public transport, and road travel.',
    icon: '🚗',
    entries: [
      // # ── Nouns ──
      { word: 'congestion', wordClass: 'noun', level: 'B2', meaning: 'A state of overcrowding or blocking, especially in traffic.', context: 'Urban traffic problems and road planning.', example: 'Traffic congestion in the city centre can add an hour to your journey.', explanation: 'Collocations: "traffic/road congestion", "congestion charge/zone" (London charges drivers to enter the city centre to reduce traffic), "congestion pricing". Also medical: "nasal congestion" (= blocked nose). "Congested" (adjective): "congested roads/sinuses".' },
      { word: 'junction', wordClass: 'noun', level: 'B1', meaning: 'A point where two or more roads or railway lines meet.', context: 'Driving directions and navigation.', example: 'Turn left at the next junction to get onto the motorway.', explanation: 'British: "junction" (for motorway exits: "Leave at junction 12"). American: "intersection" or "exit". Collocations: "motorway/road/T-junction" (a T-shaped junction), "at/near the junction", "railway junction" (where tracks split). Different from "roundabout" (circular junction).' },
      { word: 'pedestrian', wordClass: 'noun', level: 'B1', meaning: 'A person walking in a road or developed area, especially one on foot.', context: 'Road safety and urban planning.', example: 'Drivers should always give way to pedestrians at zebra crossings.', explanation: 'Collocations: "pedestrian crossing/zone/precinct" (= area only for walkers), "pedestrian safety", "pedestrianised street" (= street closed to vehicles). Also an adjective meaning "dull": "The performance was rather pedestrian" (= unimaginative and boring).' },
      { word: 'motorway', wordClass: 'noun', level: 'A2', meaning: 'A major road designed for fast-moving traffic, with separate lanes for each direction.', context: 'Long-distance driving in the UK.', example: 'The M25 motorway around London is notorious for traffic jams.', explanation: 'British: "motorway" (prefixed with M: M1, M25). American: "highway", "freeway", or "interstate". Collocations: "motorway traffic/service station/junction", "on the motorway", "hard shoulder" (= the emergency lane). "Dual carriageway" = a road with a central barrier (like a motorway but with possible roundabouts).' },
      { word: 'fare', wordClass: 'noun', level: 'A2', meaning: 'The money charged for a journey on public transport.', context: 'Buses, trains, and taxis.', example: 'The bus fare to the city centre is £2.50 for a single ticket.', explanation: 'Collocations: "bus/train/taxi fare", "single/return fare", "fare increase", "off-peak fare" (= cheaper travel outside busy times), "pay the fare". Different from "fee" (= charge for a service) or "fine" (= penalty for breaking a rule). Don\'t confuse with "fair" (= just, or an event).' },
      // # ── Verbs ──
      { word: 'accelerate', wordClass: 'verb', level: 'B2', verbForms: { v1: 'accelerate', v2: 'accelerated', v3: 'accelerated' }, meaning: 'To increase speed; to go faster.', context: 'Driving and the pace of change.', example: 'The car accelerated from 0 to 60 mph in just 4 seconds.', explanation: 'Opposite: "decelerate" or "brake". The noun is "acceleration" (and "accelerator" = the pedal that makes a car go faster). Collocations: "accelerate growth/change/the process" (figurative = speed up). "Acceleration" is measured in 0-60 mph or 0-100 km/h times.' },
      { word: 'overtake', wordClass: 'verb', level: 'B1', verbForms: { v1: 'overtake', v2: 'overtook', v3: 'overtaken' }, meaning: 'To pass another vehicle moving in the same direction.', context: 'Driving rules and road safety.', example: 'Don\'t overtake on a bend — you can\'t see oncoming traffic.', explanation: 'British: "overtake". American: "pass". Collocations: "overtake a car/lorry", "dangerous/safe to overtake", "no overtaking" (= a road sign). Also figurative: "China has overtaken Japan as the world\'s second-largest economy" (= surpassed).' },
      { word: 'detour', wordClass: 'verb', level: 'B2', verbForms: { v1: 'detour', v2: 'detoured', v3: 'detoured' }, meaning: 'To take an alternative route to avoid something, usually roadworks or an obstruction.', context: 'Road closures and travel diversions.', example: 'We had to detour around the flooded road, adding 30 minutes to our journey.', explanation: 'Also a noun: "make/take a detour". British: "diversion" is more commonly used for official road alternatives. Collocations: "detour around/via", "a short/long detour". Figurative: "a detour in my career" (= an unexpected change of direction).' },
      { word: 'refuel', wordClass: 'verb', level: 'B1', verbForms: { v1: 'refuel', v2: 'refuelled', v3: 'refuelled' }, meaning: 'To fill the fuel tank of a vehicle again.', context: 'Long-distance travel and vehicle maintenance.', example: 'We need to stop and refuel — the tank is almost empty.', explanation: 'Collocations: "stop to refuel", "refuel the car/plane". "Refuelling stop" = a planned stop for fuel. Also figurative: "refuel your energy/body" (= rest and eat to regain energy). "Fuel up" is an informal alternative.' },
      // # ── Adjectives ──
      { word: 'congested', wordClass: 'adjective', level: 'B2', meaning: 'Blocked or overcrowded with traffic or people.', context: 'Traffic conditions and busy areas.', example: 'The roads are heavily congested during the morning rush hour.', explanation: 'Collocations: "congested roads/streets/arteries", "heavily/badly congested". Also medical: "congested nose/sinuses" (= blocked). "Decongested" = cleared. "Decongestant" = medicine to unblock your nose.' },
      { word: 'delayed', wordClass: 'adjective', level: 'A2', meaning: 'Arriving or happening later than planned or expected.', context: 'Transport disruptions and schedule changes.', example: 'The 8:15 train is delayed by approximately 20 minutes due to a signal failure.', explanation: 'The noun is "delay". Collocations: "delayed flight/train", "delayed by 30 minutes", "long/short delay", "experience delays". "Without delay" (= immediately), "delayed gratification" (psychology — the ability to wait for a reward).' },
      { word: 'direct', wordClass: 'adjective', level: 'A2', meaning: 'Going straight from one place to another without stopping or changing.', context: 'Routes and transport connections.', example: 'Is there a direct train to Manchester, or do I need to change?', explanation: 'Collocations: "direct flight/train/route/bus", "direct route" (= the shortest/fastest way). "Non-stop" = doesn\'t stop at all; "direct" = might stop but you don\'t need to change vehicle. Also "direct" (adverb): "The flight goes direct to New York."' },
      // # ── Adverbs ──
      { word: 'roughly', wordClass: 'adverb', level: 'B1', meaning: 'Approximately; not exactly.', context: 'Estimating distances, times, and amounts.', example: 'The journey takes roughly two hours by car, depending on traffic.', explanation: 'Collocations: "roughly speaking" (= approximately, in general terms), "roughly equivalent/equal", "roughly X miles/hours/people". More informal than "approximately". Also means "harshly": "He handled the package roughly" (= not gently).' },
    ],
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # 20. ARTS & CULTURE — Expansion
  // # ═══════════════════════════════════════════════════════════════════
  {
    id: 'arts-culture',
    name: 'Arts & Culture',
    description: 'Vocabulary for visual arts, performing arts, literature, and cultural events.',
    icon: '🎨',
    entries: [
      // # ── Nouns ──
      { word: 'exhibition', wordClass: 'noun', level: 'B1', meaning: 'A public display of art, objects, or information in a gallery or museum.', context: 'Museums, galleries, and cultural events.', example: 'The Tate Modern is hosting a major exhibition of Picasso\'s early works.', explanation: 'British: "exhibition". American: often "exhibit" (though both are used). Collocations: "art/photography/permanent/temporary exhibition", "visit/host/open an exhibition", "exhibition space/hall". "On exhibition" = currently being shown.' },
      { word: 'masterpiece', wordClass: 'noun', level: 'B1', meaning: 'A work of outstanding skill, artistry, or workmanship; the greatest work of an artist.', context: 'Art appreciation and cultural discussion.', example: 'The Mona Lisa is widely considered Leonardo da Vinci\'s masterpiece.', explanation: 'Also called "magnum opus" (Latin — a person\'s greatest work). Collocations: "artistic/literary masterpiece", "considered a masterpiece", "create a masterpiece". Also informal: "This cake is an absolute masterpiece!" (= anything done exceptionally well).' },
      { word: 'sculpture', wordClass: 'noun', level: 'B1', meaning: 'A three-dimensional work of art made by carving, moulding, or assembling materials.', context: 'Art forms and museum collections.', example: 'The museum has an impressive collection of ancient Greek sculptures.', explanation: 'The artist is a "sculptor". Collocations: "bronze/marble/stone sculpture", "sculpture gallery/park/exhibition". "Sculpt" (verb): "She sculpted the figure from clay." Materials: stone, marble, bronze, clay, wood, metal, ice (ice sculpture), or modern materials like plastic and wire.' },
      { word: 'mural', wordClass: 'noun', level: 'B2', meaning: 'A large painting or artwork applied directly to a wall or ceiling.', context: 'Street art and architectural decoration.', example: 'The neighbourhood is famous for its colourful murals painted by local artists.', explanation: 'Famous murals: Sistine Chapel ceiling (Michelangelo), Diego Rivera\'s murals in Mexico. Collocations: "wall mural", "paint/commission a mural", "street/community mural". "Muralist" = an artist who paints murals. "Graffiti" is different — usually unauthorised, while murals are typically commissioned.' },
      { word: 'rehearsal', wordClass: 'noun', level: 'B1', meaning: 'A practice session for a performance, play, concert, or ceremony.', context: 'Theatre, music, and event preparation.', example: 'The cast had a full dress rehearsal the night before the opening performance.', explanation: 'The verb is "rehearse". Collocations: "dress rehearsal" (= final practice in full costume), "rehearsal room/space", "in rehearsal" (= currently practising). "Dress rehearsal" also figurative: "a dress rehearsal for the real event" (= a final practice run).' },
      { word: 'patron', wordClass: 'noun', level: 'B2', meaning: 'A person who supports the arts financially; or a regular customer of a business.', context: 'Arts funding and historical sponsorship.', example: 'The Medici family were famous patrons of Renaissance art in Florence.', explanation: 'Two meanings: 1) "Arts patron" = financial supporter; 2) "Patron of a restaurant" = regular customer. Collocations: "patron of the arts", "patron saint" (= a saint believed to protect a particular group or place). "Patronage" (noun) = financial support or regular custom.' },
      // # ── Verbs ──
      { word: 'compose', wordClass: 'verb', level: 'B1', verbForms: { v1: 'compose', v2: 'composed', v3: 'composed' }, meaning: 'To create a piece of music or write a literary work.', context: 'Music creation and creative writing.', example: 'Beethoven composed his most famous symphony while completely deaf.', explanation: 'The person is a "composer" and the work is a "composition". Collocations: "compose music/a symphony/a letter/a poem". Also: "compose yourself" (= calm yourself down), "composed" (adjective — calm: "She remained composed throughout the interview").' },
      { word: 'curate', wordClass: 'verb', level: 'B2', verbForms: { v1: 'curate', v2: 'curated', v3: 'curated' }, meaning: 'To select, organise, and present items for a collection or exhibition.', context: 'Museums, galleries, and content creation.', example: 'She curated an exhibition of contemporary African photography at the gallery.', explanation: 'The person is a "curator" (= the person who manages a museum or gallery\'s collection). Collocations: "curate an exhibition/collection/playlist", "curated content" (= carefully selected content on social media or platforms). Modern use: "a curated feed/playlist" = content hand-picked for quality.' },
      { word: 'portray', wordClass: 'verb', level: 'B2', verbForms: { v1: 'portray', v2: 'portrayed', v3: 'portrayed' }, meaning: 'To depict or represent someone or something in art, writing, or performance.', context: 'Acting, painting, and media representation.', example: 'The film portrays life in Victorian London with remarkable accuracy.', explanation: 'The noun is "portrayal". Collocations: "portray someone as" (= represent them as), "accurate/negative portrayal", "portrait" (noun — a painting or photograph of a person). "Self-portrait" = an artwork of the artist themselves. "The media portrays..." is a common essay phrase.' },
      { word: 'improvise', wordClass: 'verb', level: 'B2', verbForms: { v1: 'improvise', v2: 'improvised', v3: 'improvised' }, meaning: 'To create or perform without preparation, making it up as you go.', context: 'Jazz music, theatre, and problem-solving.', example: 'The jazz musicians improvised a brilliant solo that was different every night.', explanation: 'The noun is "improvisation" (often shortened to "improv" in theatre). Collocations: "improvise a speech/solution/meal", "improvised performance/weapon", "improv comedy" (= comedy created spontaneously). Also practical: "We didn\'t have a screwdriver, so we had to improvise" (= find a creative alternative).' },
      // # ── Adjectives ──
      { word: 'avant-garde', wordClass: 'adjective', level: 'C1', meaning: 'New, experimental, and unconventional, especially in art and culture.', context: 'Art movements and creative innovation.', example: 'The avant-garde theatre production challenged all traditional ideas about storytelling.', explanation: 'From French military term: "advance guard" (soldiers at the front). Also a noun: "the avant-garde" (= the group of artists pushing boundaries). Collocations: "avant-garde art/music/film/fashion", "avant-garde movement". Implies being ahead of its time — may be controversial and not immediately popular.' },
      { word: 'contemporary', wordClass: 'adjective', level: 'B1', meaning: 'Belonging to the present time; modern and current.', context: 'Art classification and cultural description.', example: 'The museum has both classical and contemporary art collections.', explanation: 'Two meanings: 1) "Contemporary art" = art from today; 2) "Contemporaries" = people living at the same time: "Shakespeare and his contemporaries." Collocations: "contemporary art/music/dance/design", "contemporary society". Different from "modern art" (= early-mid 20th century, a specific movement).' },
      { word: 'abstract', wordClass: 'adjective', level: 'B2', meaning: 'Not representing physical objects; based on ideas, shapes, and colours rather than real things.', context: 'Art styles and intellectual concepts.', example: 'Kandinsky was a pioneer of abstract art, using shapes and colours to express emotions.', explanation: 'In art: "abstract art" = doesn\'t try to look like real things (opposite: "figurative" or "representational"). In general: "abstract concept/idea" = theoretical, not concrete. "Abstract" (noun) = a summary of an academic paper. Famous abstract artists: Kandinsky, Mondrian, Rothko.' },
      { word: 'iconic', wordClass: 'adjective', level: 'B2', meaning: 'Widely recognised and well-established as a symbol or representation.', context: 'Cultural significance and brand recognition.', example: 'The Eiffel Tower is one of the most iconic landmarks in the world.', explanation: 'From "icon" (= a symbol or representative image). Collocations: "iconic building/image/moment/brand", "truly/instantly iconic". Modern overuse: almost anything popular is now called "iconic" — but properly, it means something so famous it represents an entire era, place, or concept.' },
      // # ── Adverbs ──
      { word: 'creatively', wordClass: 'adverb', level: 'B1', meaning: 'In a way that involves using imagination and original ideas.', context: 'Art, problem-solving, and innovation.', example: 'The children were encouraged to think creatively and come up with original solutions.', explanation: 'The adjective is "creative" and the noun is "creativity". Collocations: "think/work/express yourself creatively", "creative writing/thinking/industry". "The creative industries" = sectors based on individual creativity: art, design, film, music, advertising, architecture.' },
      { word: 'vividly', wordClass: 'adverb', level: 'B2', meaning: 'In a way that produces clear, strong, and detailed mental images.', context: 'Descriptive writing and clear memories.', example: 'I can still vividly remember the first time I visited Paris as a child.', explanation: 'The adjective is "vivid": "vivid colours/imagination/memory/dream". Collocations: "vividly remember/describe/imagine", "vivid description/account". "Vivid" implies brightness, intensity, and clarity — whether of colours, memories, or imagination. "A vivid imagination" = very active and detailed imagination.' },
    ],
  },
]
