import { sqliteTable, text, integer, index } from 'drizzle-orm/sqlite-core'

// The subscription tiers available in FluentPath.
// 'free' = limited features, 'exam' = mock tests + diagnosis, 'complete' = everything.
export const TIERS = ['free', 'exam', 'complete'] as const
export type Tier = (typeof TIERS)[number]

// Paddle subscription lifecycle states.
// 'none' = never subscribed, 'active' = paying, 'past_due' = payment failed,
// 'cancelled' = subscription ended.
export const SUBSCRIPTION_STATUSES = ['none', 'active', 'past_due', 'cancelled'] as const
export type SubscriptionStatus = (typeof SUBSCRIPTION_STATUSES)[number]

/**
 * FluentPath learner profiles.
 *
 * Separate from NextAuth's `users` table — this holds FluentPath-specific
 * state: current level, subscription tier, Paddle IDs, L1.
 *
 * Linked to NextAuth via email. This separation means switching auth
 * providers later doesn't touch our data, and NextAuth schema changes
 * don't affect our queries.
 */
export const learners = sqliteTable(
  'learners',
  {
    // UUID v4 generated by crypto.randomUUID().
    id: text('id').primaryKey(),

    // Links to NextAuth user. UNIQUE constraint prevents duplicate profiles.
    email: text('email').notNull().unique(),

    // Display name — optional, populated from NextAuth or user input.
    name: text('name'),

    // First language code (ISO 639-1) for L1-aware feedback.
    // e.g. 'my' (Burmese), 'th' (Thai), 'ja' (Japanese).
    l1: text('l1'),

    // Latest CEFR level from placement test. Null until placement is done.
    currentLevel: text('current_level'),

    // Subscription tier: 'free', 'exam', or 'complete'.
    tier: text('tier').notNull().default('free'),

    // Paddle customer ID — null until first interaction with Paddle.
    paddleCustomerId: text('paddle_customer_id'),

    // Active Paddle subscription ID — null if no subscription.
    paddleSubscriptionId: text('paddle_subscription_id'),

    // Subscription lifecycle state.
    subscriptionStatus: text('subscription_status').notNull().default('none'),

    // Epoch ms — when the learner profile was created.
    createdAt: integer('created_at').notNull(),

    // Epoch ms — last update to this profile.
    updatedAt: integer('updated_at').notNull(),
  },
  (t) => ({
    // Tier index for dashboard queries like "how many paying users".
    tierIdx: index('learners_tier_idx').on(t.tier),
  }),
)
