import { describe, it, expect, beforeEach } from 'vitest'
import { makeTestDb } from '../helpers/test-db'
import { buildProfilerInventory } from '@/profiler/build-inventory'
import { upsertNodes } from '@/skill-graph/repository'
import { getItem, getItemVersion } from '@/content/repository'
import { ingestGeneratedItem } from '@/content/ingest'
import type { IngestOptions } from '@/content/ingest'
import type { GenerateItemResult } from '@/generation/generate'
import type { McqItem, ItemReview } from '@/items/types'
import type { Db } from '@/db/client'

const NOW = 1_700_000_000_000
const inventory = buildProfilerInventory()

let db: Db

beforeEach(async () => {
  db = await makeTestDb()
  await upsertNodes(
    db,
    [
      {
        id: 'gram.b1.pp_vs_past',
        type: 'grammar',
        level: 'B1',
        skill: 'general',
        title: 'Present perfect vs past simple',
        description: '',
        metadata: null,
      },
    ],
    NOW,
  )
})

// A good McqItem that passes all deterministic gates.
const GOOD_ITEM: McqItem = {
  id: 'item.gen.1',
  type: 'mcq',
  stem: 'I ______ my keys. I cannot open the door.',
  options: [
    { text: 'have lost', misconception: null },
    { text: 'lost', misconception: 'uses past simple though the result still matters now' },
    { text: 'was losing', misconception: 'treats a completed event as an ongoing action' },
    { text: 'am losing', misconception: 'places a finished event in the present moment' },
  ],
  correctIndex: 0,
  nodeIds: ['gram.b1.pp_vs_past'],
  level: 'B1',
}

const GOOD_REVIEW: ItemReview = { passed: true, issues: [] }

const OPTIONS: IngestOptions = {
  provenance: {
    id: 'prov.generated.gemini-2.0-flash',
    sourceName: 'generated',
    licence: 'original',
    modifications: 'Generated by gemini-2.0-flash',
  },
  inventory,
}

describe('ingestGeneratedItem', () => {
  it('stores and publishes a successful generation result', async () => {
    const result: GenerateItemResult = {
      item: GOOD_ITEM,
      review: GOOD_REVIEW,
      attempts: [{ kind: 'success', item: GOOD_ITEM, review: GOOD_REVIEW }],
    }

    const ingestResult = await ingestGeneratedItem(db, result, OPTIONS, NOW)
    expect(ingestResult.status).toBe('published')

    if (ingestResult.status !== 'published') throw new Error('expected published')

    expect(ingestResult.itemId).toBe('item.gen.1')
    expect(ingestResult.versionId).toBe('item.gen.1@1')

    // Verify the item is in the database and published.
    const item = await getItem(db, 'item.gen.1')
    expect(item?.status).toBe('published')
    expect(item?.currentVersionId).toBe('item.gen.1@1')
    expect(item?.level).toBe('B1')
    expect(item?.type).toBe('mcq')
  })

  it('returns failed when generation produced no item', async () => {
    const result: GenerateItemResult = {
      item: null,
      review: null,
      attempts: [{ kind: 'parse_failure', raw: 'garbage' }],
    }

    const ingestResult = await ingestGeneratedItem(db, result, OPTIONS, NOW)
    expect(ingestResult.status).toBe('failed')
  })

  it('stores the payload in the version', async () => {
    const result: GenerateItemResult = {
      item: GOOD_ITEM,
      review: GOOD_REVIEW,
      attempts: [{ kind: 'success', item: GOOD_ITEM, review: GOOD_REVIEW }],
    }

    await ingestGeneratedItem(db, result, OPTIONS, NOW)

    const version = await getItemVersion(db, 'item.gen.1@1')
    expect(version).not.toBeNull()
    const payload = version!.payload as Record<string, unknown>
    expect(payload.stem).toBe('I ______ my keys. I cannot open the door.')
    expect(payload.correctIndex).toBe(0)
  })

  it('records provenance for generated items', async () => {
    const result: GenerateItemResult = {
      item: GOOD_ITEM,
      review: GOOD_REVIEW,
      attempts: [{ kind: 'success', item: GOOD_ITEM, review: GOOD_REVIEW }],
    }

    await ingestGeneratedItem(db, result, OPTIONS, NOW)

    const version = await getItemVersion(db, 'item.gen.1@1')
    expect(version!.provenanceId).toBe('prov.generated.gemini-2.0-flash')
  })

  it('uses the skill option when provided', async () => {
    const result: GenerateItemResult = {
      item: GOOD_ITEM,
      review: GOOD_REVIEW,
      attempts: [{ kind: 'success', item: GOOD_ITEM, review: GOOD_REVIEW }],
    }

    await ingestGeneratedItem(db, result, { ...OPTIONS, skill: 'reading' }, NOW)

    const item = await getItem(db, 'item.gen.1')
    expect(item?.skill).toBe('reading')
  })

  it('is idempotent on provenance (multiple ingests with same model)', async () => {
    const result1: GenerateItemResult = {
      item: GOOD_ITEM,
      review: GOOD_REVIEW,
      attempts: [{ kind: 'success', item: GOOD_ITEM, review: GOOD_REVIEW }],
    }
    const result2: GenerateItemResult = {
      item: { ...GOOD_ITEM, id: 'item.gen.2' },
      review: GOOD_REVIEW,
      attempts: [{ kind: 'success', item: { ...GOOD_ITEM, id: 'item.gen.2' }, review: GOOD_REVIEW }],
    }

    // Both use the same provenance ID — should not throw.
    await ingestGeneratedItem(db, result1, OPTIONS, NOW)
    await ingestGeneratedItem(db, result2, OPTIONS, NOW + 1000)

    expect((await getItem(db, 'item.gen.1'))?.status).toBe('published')
    expect((await getItem(db, 'item.gen.2'))?.status).toBe('published')
  })
})
