// # Seed content: 60 MCQ items covering A1 through C1.
// # Each item links to at least one skill-graph node from seed-data.ts.
// # Placement starts at B1, so B1 has the most items (15).

// # Item payload shape matches McqOption / item_versions.payload.
interface SeedOption {
  text: string
  misconception: string | null // null = correct answer
}

interface SeedItem {
  id: string
  level: 'A1' | 'A2' | 'B1' | 'B2' | 'C1'
  skill: string
  nodeIds: string[] // references into skill_nodes
  stem: string
  options: SeedOption[]
  correctIndex: number
  difficulty: number // 0–1, lower = easier
}

// # Single provenance record for all original seed content.
export const SEED_PROVENANCE = {
  id: 'prov.original',
  sourceName: 'FluentPath — original content',
  sourceUrl: null,
  licence: 'proprietary',
  licenceUrl: null,
  attributionText: '',
  retrievedAt: null,
  modifications: '',
}

// ─── A1 items (10) ─────────────────────────────────────────────────────

const A1_ITEMS: SeedItem[] = [
  {
    id: 'item.a1.gram.01',
    level: 'A1', skill: 'general',
    nodeIds: ['gram.a1.be_present'],
    stem: 'She ______ a teacher.',
    options: [
      { text: 'is', misconception: null },
      { text: 'are', misconception: 'are is used with you/we/they, not she' },
      { text: 'am', misconception: 'am is only used with I' },
      { text: 'be', misconception: 'be is the infinitive form, not conjugated' },
    ],
    correctIndex: 0,
    difficulty: 0.1,
  },
  {
    id: 'item.a1.gram.02',
    level: 'A1', skill: 'general',
    nodeIds: ['gram.a1.be_present'],
    stem: 'They ______ from Brazil.',
    options: [
      { text: 'is', misconception: 'is is used with he/she/it, not they' },
      { text: 'are', misconception: null },
      { text: 'am', misconception: 'am is only used with I' },
      { text: 'was', misconception: 'was is past tense, the sentence is present' },
    ],
    correctIndex: 1,
    difficulty: 0.1,
  },
  {
    id: 'item.a1.gram.03',
    level: 'A1', skill: 'general',
    nodeIds: ['gram.a1.present_simple'],
    stem: 'He ______ to school every day.',
    options: [
      { text: 'go', misconception: 'go is used with I/you/we/they, not he' },
      { text: 'goes', misconception: null },
      { text: 'going', misconception: 'going is the -ing form, not present simple' },
      { text: 'gone', misconception: 'gone is the past participle, not present simple' },
    ],
    correctIndex: 1,
    difficulty: 0.15,
  },
  {
    id: 'item.a1.gram.04',
    level: 'A1', skill: 'general',
    nodeIds: ['gram.a1.present_simple'],
    stem: 'I ______ coffee in the morning.',
    options: [
      { text: 'drink', misconception: null },
      { text: 'drinks', misconception: 'drinks is third person (he/she), not first person (I)' },
      { text: 'drinking', misconception: 'drinking is the continuous form, the sentence describes a habit' },
      { text: 'drank', misconception: 'drank is past tense, the sentence describes a routine' },
    ],
    correctIndex: 0,
    difficulty: 0.12,
  },
  {
    id: 'item.a1.gram.05',
    level: 'A1', skill: 'general',
    nodeIds: ['gram.a1.can_cant'],
    stem: 'She ______ speak three languages.',
    options: [
      { text: 'can', misconception: null },
      { text: 'cans', misconception: 'can is a modal verb and never takes -s' },
      { text: 'is can', misconception: 'can does not use a form of be before it' },
      { text: 'could to', misconception: 'modal verbs are followed by the bare infinitive without to' },
    ],
    correctIndex: 0,
    difficulty: 0.12,
  },
  {
    id: 'item.a1.gram.06',
    level: 'A1', skill: 'general',
    nodeIds: ['gram.a1.can_cant'],
    stem: 'I ______ swim when I was three years old.',
    options: [
      { text: 'can', misconception: 'can is present tense, but the sentence is about the past' },
      { text: 'can\'t', misconception: 'can\'t is present tense, the sentence is about the past' },
      { text: 'couldn\'t', misconception: null },
      { text: 'don\'t can', misconception: 'can is negated with cannot/can\'t, not with do/don\'t' },
    ],
    correctIndex: 2,
    difficulty: 0.2,
  },
  {
    id: 'item.a1.lex.01',
    level: 'A1', skill: 'general',
    nodeIds: ['lex.a1.everyday_objects'],
    stem: 'Which of these do you use to write?',
    options: [
      { text: 'a pen', misconception: null },
      { text: 'a cup', misconception: 'a cup is for drinking, not writing' },
      { text: 'a chair', misconception: 'a chair is for sitting, not writing' },
      { text: 'a key', misconception: 'a key is for opening locks, not writing' },
    ],
    correctIndex: 0,
    difficulty: 0.05,
  },
  {
    id: 'item.a1.lex.02',
    level: 'A1', skill: 'general',
    nodeIds: ['lex.a1.everyday_objects'],
    stem: '"I need to call my friend." What do you need?',
    options: [
      { text: 'a book', misconception: 'a book is for reading, not calling someone' },
      { text: 'a phone', misconception: null },
      { text: 'a bag', misconception: 'a bag is for carrying things, not calling' },
      { text: 'a clock', misconception: 'a clock shows the time, it is not for calling' },
    ],
    correctIndex: 1,
    difficulty: 0.05,
  },
  {
    id: 'item.a1.read.01',
    level: 'A1', skill: 'reading',
    nodeIds: ['cando.a1.read_signs'],
    stem: 'A sign at the door says "PULL". What should you do?',
    options: [
      { text: 'Push the door', misconception: 'push is the opposite action of pull' },
      { text: 'Pull the door towards you', misconception: null },
      { text: 'Wait for the door to open', misconception: 'the sign tells you what action to take' },
      { text: 'Knock on the door', misconception: 'knocking is not what the sign instructs' },
    ],
    correctIndex: 1,
    difficulty: 0.08,
  },
  {
    id: 'item.a1.read.02',
    level: 'A1', skill: 'reading',
    nodeIds: ['cando.a1.read_signs'],
    stem: 'A café menu says: "Tea — £2.50, Coffee — £3.00". How much is coffee?',
    options: [
      { text: '£2.50', misconception: '£2.50 is the price of tea, not coffee' },
      { text: '£3.00', misconception: null },
      { text: '£5.50', misconception: '£5.50 is the total if you buy both, not the price of coffee' },
      { text: '£2.00', misconception: 'this price is not listed on the menu' },
    ],
    correctIndex: 1,
    difficulty: 0.05,
  },
]

// ─── A2 items (10) ─────────────────────────────────────────────────────

const A2_ITEMS: SeedItem[] = [
  {
    id: 'item.a2.gram.01',
    level: 'A2', skill: 'general',
    nodeIds: ['gram.a2.past_simple'],
    stem: 'Yesterday I ______ to the park with my friends.',
    options: [
      { text: 'go', misconception: 'go is present tense, but yesterday indicates past' },
      { text: 'went', misconception: null },
      { text: 'gone', misconception: 'gone is the past participle, used with have/has' },
      { text: 'going', misconception: 'going is the continuous form, not past simple' },
    ],
    correctIndex: 1,
    difficulty: 0.2,
  },
  {
    id: 'item.a2.gram.02',
    level: 'A2', skill: 'general',
    nodeIds: ['gram.a2.past_simple'],
    stem: 'She ______ a new dress last weekend.',
    options: [
      { text: 'buyed', misconception: 'buy is an irregular verb — buyed does not exist' },
      { text: 'bought', misconception: null },
      { text: 'buys', misconception: 'buys is present tense, but last weekend indicates past' },
      { text: 'buying', misconception: 'buying is the continuous form, not past simple' },
    ],
    correctIndex: 1,
    difficulty: 0.25,
  },
  {
    id: 'item.a2.gram.03',
    level: 'A2', skill: 'general',
    nodeIds: ['gram.a2.past_simple'],
    stem: 'We ______ dinner at 7 o\'clock last night.',
    options: [
      { text: 'have', misconception: 'have is present tense, the sentence is about last night' },
      { text: 'having', misconception: 'having is the continuous form, not past simple' },
      { text: 'had', misconception: null },
      { text: 'has', misconception: 'has is third person present, not past' },
    ],
    correctIndex: 2,
    difficulty: 0.18,
  },
  {
    id: 'item.a2.gram.04',
    level: 'A2', skill: 'general',
    nodeIds: ['gram.a2.future_going_to'],
    stem: 'Look at those clouds! It ______ rain.',
    options: [
      { text: 'will', misconception: 'will is used for decisions and predictions without evidence, not plans based on evidence' },
      { text: 'is going to', misconception: null },
      { text: 'rains', misconception: 'rains is present simple, but this is a future prediction' },
      { text: 'rained', misconception: 'rained is past tense, but the rain hasn\'t happened yet' },
    ],
    correctIndex: 1,
    difficulty: 0.3,
  },
  {
    id: 'item.a2.gram.05',
    level: 'A2', skill: 'general',
    nodeIds: ['gram.a2.future_going_to'],
    stem: 'I ______ study medicine at university next year.',
    options: [
      { text: 'am going to', misconception: null },
      { text: 'going', misconception: 'going to needs the auxiliary am/is/are before it' },
      { text: 'go to', misconception: 'go to is present tense, not a future construction' },
      { text: 'was going to', misconception: 'was going to is past tense, but next year is future' },
    ],
    correctIndex: 0,
    difficulty: 0.25,
  },
  {
    id: 'item.a2.gram.06',
    level: 'A2', skill: 'general',
    nodeIds: ['gram.a2.comparatives'],
    stem: 'This book is ______ than that one.',
    options: [
      { text: 'more interesting', misconception: null },
      { text: 'more interestinger', misconception: 'long adjectives use more, not more + -er (double marking)' },
      { text: 'interestinger', misconception: 'long adjectives form the comparative with more, not -er' },
      { text: 'most interesting', misconception: 'most interesting is the superlative, not the comparative' },
    ],
    correctIndex: 0,
    difficulty: 0.28,
  },
  {
    id: 'item.a2.gram.07',
    level: 'A2', skill: 'general',
    nodeIds: ['gram.a2.comparatives'],
    stem: 'My sister is ______ person in our family.',
    options: [
      { text: 'the tallest', misconception: null },
      { text: 'taller', misconception: 'taller is the comparative, but in our family suggests the superlative' },
      { text: 'the most tall', misconception: 'short adjectives like tall use -est, not most' },
      { text: 'more tall', misconception: 'short adjectives like tall use -er, not more' },
    ],
    correctIndex: 0,
    difficulty: 0.3,
  },
  {
    id: 'item.a2.lex.01',
    level: 'A2', skill: 'general',
    nodeIds: ['lex.a2.travel'],
    stem: 'The plane lands at the ______.',
    options: [
      { text: 'station', misconception: 'station is for trains and buses, not planes' },
      { text: 'airport', misconception: null },
      { text: 'harbour', misconception: 'harbour is for ships and boats, not planes' },
      { text: 'parking', misconception: 'parking is for cars, not where planes land' },
    ],
    correctIndex: 1,
    difficulty: 0.15,
  },
  {
    id: 'item.a2.lex.02',
    level: 'A2', skill: 'general',
    nodeIds: ['lex.a2.travel'],
    stem: 'You need a ______ to travel to another country.',
    options: [
      { text: 'passport', misconception: null },
      { text: 'ticket', misconception: 'a ticket lets you board transport, but you need a passport to enter a country' },
      { text: 'suitcase', misconception: 'a suitcase carries your belongings, it does not allow entry to a country' },
      { text: 'map', misconception: 'a map helps you find places, not enter countries' },
    ],
    correctIndex: 0,
    difficulty: 0.12,
  },
  {
    id: 'item.a2.read.01',
    level: 'A2', skill: 'reading',
    nodeIds: ['cando.a2.read_personal_letter'],
    stem: '"Dear Tom, I arrived in Paris yesterday. The hotel is nice but small. See you next week. — Sara." Where is Sara?',
    options: [
      { text: 'At home', misconception: 'the letter says she arrived in Paris, so she is not at home' },
      { text: 'In Paris', misconception: null },
      { text: 'With Tom', misconception: 'she says see you next week, so she is not with Tom now' },
      { text: 'At the airport', misconception: 'she arrived yesterday and is at the hotel, not still at the airport' },
    ],
    correctIndex: 1,
    difficulty: 0.2,
  },
]

// ─── B1 items (15) — placement starts here ─────────────────────────────

const B1_ITEMS: SeedItem[] = [
  {
    id: 'item.b1.gram.01',
    level: 'B1', skill: 'general',
    nodeIds: ['gram.b1.present_perfect'],
    stem: 'I ______ to Japan twice.',
    options: [
      { text: 'have been', misconception: null },
      { text: 'was', misconception: 'was is past simple, but twice implies unfinished time' },
      { text: 'been', misconception: 'been needs the auxiliary have/has before it' },
      { text: 'go', misconception: 'go is present tense, the sentence describes life experience' },
    ],
    correctIndex: 0,
    difficulty: 0.35,
  },
  {
    id: 'item.b1.gram.02',
    level: 'B1', skill: 'general',
    nodeIds: ['gram.b1.present_perfect'],
    stem: 'She ______ here since 2019.',
    options: [
      { text: 'lives', misconception: 'since 2019 signals a time period, requiring the present perfect' },
      { text: 'has lived', misconception: null },
      { text: 'lived', misconception: 'lived is past simple, but since 2019 implies she still lives here' },
      { text: 'is living', misconception: 'present continuous does not express duration with since' },
    ],
    correctIndex: 1,
    difficulty: 0.38,
  },
  {
    id: 'item.b1.gram.03',
    level: 'B1', skill: 'general',
    nodeIds: ['gram.b1.present_perfect'],
    stem: 'Have you ever ______ sushi?',
    options: [
      { text: 'tried', misconception: null },
      { text: 'try', misconception: 'the present perfect needs the past participle, not the base form' },
      { text: 'trying', misconception: 'trying is the -ing form, not the past participle' },
      { text: 'tries', misconception: 'tries is third person present, not the past participle' },
    ],
    correctIndex: 0,
    difficulty: 0.3,
  },
  {
    id: 'item.b1.gram.04',
    level: 'B1', skill: 'general',
    nodeIds: ['gram.b1.pp_vs_past_simple'],
    stem: 'I ______ this book last summer.',
    options: [
      { text: 'read', misconception: null },
      { text: 'have read', misconception: 'last summer is a finished time, so present perfect cannot be used' },
      { text: 'have readed', misconception: 'read is an irregular verb — readed does not exist' },
      { text: 'was reading', misconception: 'was reading is past continuous, not appropriate for a completed action' },
    ],
    correctIndex: 0,
    difficulty: 0.4,
  },
  {
    id: 'item.b1.gram.05',
    level: 'B1', skill: 'general',
    nodeIds: ['gram.b1.pp_vs_past_simple'],
    stem: '"Have you seen the new film?" — "Yes, I ______ it yesterday."',
    options: [
      { text: 'have seen', misconception: 'yesterday is a finished time, so past simple is required' },
      { text: 'saw', misconception: null },
      { text: 'see', misconception: 'see is present tense, but the action was yesterday' },
      { text: 'seeing', misconception: 'seeing is the -ing form, not past simple' },
    ],
    correctIndex: 1,
    difficulty: 0.42,
  },
  {
    id: 'item.b1.gram.06',
    level: 'B1', skill: 'general',
    nodeIds: ['gram.b1.pp_vs_past_simple'],
    stem: 'I ______ my keys. I can\'t find them anywhere.',
    options: [
      { text: 'lost', misconception: 'lost (past simple) implies it is over — but the keys are still missing' },
      { text: 'have lost', misconception: null },
      { text: 'lose', misconception: 'lose is present tense, but the result is current' },
      { text: 'was losing', misconception: 'was losing is past continuous, not a current result' },
    ],
    correctIndex: 1,
    difficulty: 0.45,
  },
  {
    id: 'item.b1.gram.07',
    level: 'B1', skill: 'general',
    nodeIds: ['gram.b1.modals'],
    stem: 'You ______ see a doctor. That cough sounds bad.',
    options: [
      { text: 'should', misconception: null },
      { text: 'can', misconception: 'can expresses ability, not advice' },
      { text: 'would', misconception: 'would expresses hypothetical situations, not strong advice' },
      { text: 'shall', misconception: 'shall is used mainly for offers or suggestions with I/we' },
    ],
    correctIndex: 0,
    difficulty: 0.35,
  },
  {
    id: 'item.b1.gram.08',
    level: 'B1', skill: 'general',
    nodeIds: ['gram.b1.modals'],
    stem: 'You ______ park here — it\'s a no-parking zone.',
    options: [
      { text: 'mustn\'t', misconception: null },
      { text: 'don\'t have to', misconception: 'don\'t have to means it is not necessary, not that it is prohibited' },
      { text: 'shouldn\'t', misconception: 'shouldn\'t is advice, but a no-parking zone is a rule' },
      { text: 'can', misconception: 'can means you are able to, but it is forbidden here' },
    ],
    correctIndex: 0,
    difficulty: 0.4,
  },
  {
    id: 'item.b1.gram.09',
    level: 'B1', skill: 'general',
    nodeIds: ['gram.b1.modals'],
    stem: 'It ______ rain later — take an umbrella just in case.',
    options: [
      { text: 'must', misconception: 'must expresses certainty, but just in case implies uncertainty' },
      { text: 'might', misconception: null },
      { text: 'will', misconception: 'will expresses certainty, but just in case implies possibility' },
      { text: 'should', misconception: 'should is for advice, but the subject is weather' },
    ],
    correctIndex: 1,
    difficulty: 0.38,
  },
  {
    id: 'item.b1.lex.01',
    level: 'B1', skill: 'general',
    nodeIds: ['lex.b1.work_education'],
    stem: 'After finishing university, she applied for a ______ at a tech company.',
    options: [
      { text: 'position', misconception: null },
      { text: 'place', misconception: 'place can mean location, not typically used for job applications' },
      { text: 'situation', misconception: 'situation means circumstances, not a job role' },
      { text: 'post office', misconception: 'post office is a building, not a job' },
    ],
    correctIndex: 0,
    difficulty: 0.3,
  },
  {
    id: 'item.b1.lex.02',
    level: 'B1', skill: 'general',
    nodeIds: ['lex.b1.work_education'],
    stem: 'The company decided to ______ ten new employees.',
    options: [
      { text: 'fire', misconception: 'fire means to dismiss, the opposite of what the sentence describes' },
      { text: 'hire', misconception: null },
      { text: 'retire', misconception: 'retire means to stop working permanently' },
      { text: 'resign', misconception: 'resign means to voluntarily leave a job' },
    ],
    correctIndex: 1,
    difficulty: 0.28,
  },
  {
    id: 'item.b1.read.01',
    level: 'B1', skill: 'reading',
    nodeIds: ['cando.b1.understand_factual_text'],
    stem: '"The Museum of Modern Art is open Tuesday to Sunday, 10:30 AM to 5:30 PM. Admission is free for children under 16." On which day is the museum closed?',
    options: [
      { text: 'Sunday', misconception: 'the text says Tuesday to Sunday, so Sunday is open' },
      { text: 'Monday', misconception: null },
      { text: 'Saturday', misconception: 'Saturday falls within Tuesday to Sunday, so it is open' },
      { text: 'It is open every day', misconception: 'the text says Tuesday to Sunday, meaning Monday is excluded' },
    ],
    correctIndex: 1,
    difficulty: 0.32,
  },
  {
    id: 'item.b1.read.02',
    level: 'B1', skill: 'reading',
    nodeIds: ['cando.b1.understand_factual_text'],
    stem: '"Global temperatures have risen by 1.1°C since pre-industrial times. Scientists warn that exceeding 1.5°C could cause irreversible damage." What does the text say about 1.5°C?',
    options: [
      { text: 'We have already reached it', misconception: 'the text says 1.1°C so far, not 1.5°C' },
      { text: 'Going beyond it could cause permanent harm', misconception: null },
      { text: 'It is the ideal temperature', misconception: 'the text presents 1.5°C as a dangerous threshold, not an ideal' },
      { text: 'Temperatures will decrease after it', misconception: 'the text says nothing about temperatures decreasing' },
    ],
    correctIndex: 1,
    difficulty: 0.35,
  },
  {
    id: 'item.b1.listen.01',
    level: 'B1', skill: 'listening',
    nodeIds: ['cando.b1.understand_monologue'],
    stem: 'A tour guide says: "The castle was built in 1245 and rebuilt after a fire in 1530. Today it houses a museum of medieval history." When was the castle originally built?',
    options: [
      { text: '1530', misconception: '1530 is when it was rebuilt, not originally built' },
      { text: '1245', misconception: null },
      { text: 'During the medieval period', misconception: 'the text gives a specific year, not just an era' },
      { text: 'The text doesn\'t say', misconception: 'the text clearly states 1245' },
    ],
    correctIndex: 1,
    difficulty: 0.3,
  },
  {
    id: 'item.b1.listen.02',
    level: 'B1', skill: 'listening',
    nodeIds: ['cando.b1.understand_monologue'],
    stem: 'An announcement says: "Due to engineering works, the 9:15 train to Manchester will depart from Platform 7 instead of Platform 3." What has changed?',
    options: [
      { text: 'The departure time', misconception: 'the time stays 9:15, only the platform changed' },
      { text: 'The destination', misconception: 'the destination is still Manchester' },
      { text: 'The platform', misconception: null },
      { text: 'The train has been cancelled', misconception: 'the train is still running, just from a different platform' },
    ],
    correctIndex: 2,
    difficulty: 0.28,
  },
]

// ─── B2 items (15) ─────────────────────────────────────────────────────

const B2_ITEMS: SeedItem[] = [
  {
    id: 'item.b2.gram.01',
    level: 'B2', skill: 'general',
    nodeIds: ['gram.b2.conditionals'],
    stem: 'If I ______ more time, I would learn another language.',
    options: [
      { text: 'have', misconception: 'have is present tense, but the second conditional uses past tense' },
      { text: 'had', misconception: null },
      { text: 'would have', misconception: 'would have belongs in the result clause, not the if clause' },
      { text: 'will have', misconception: 'will have is first conditional, not second conditional' },
    ],
    correctIndex: 1,
    difficulty: 0.5,
  },
  {
    id: 'item.b2.gram.02',
    level: 'B2', skill: 'general',
    nodeIds: ['gram.b2.conditionals'],
    stem: 'If she ______ the bus, she wouldn\'t have been late.',
    options: [
      { text: 'caught', misconception: 'caught is past simple, but the third conditional needs past perfect' },
      { text: 'catches', misconception: 'catches is present tense, not used in third conditional' },
      { text: 'had caught', misconception: null },
      { text: 'would catch', misconception: 'would catch goes in the result clause, not the if clause' },
    ],
    correctIndex: 2,
    difficulty: 0.55,
  },
  {
    id: 'item.b2.gram.03',
    level: 'B2', skill: 'general',
    nodeIds: ['gram.b2.conditionals'],
    stem: 'I wish I ______ at the party last night.',
    options: [
      { text: 'was', misconception: 'was is past simple; wish about the past needs past perfect' },
      { text: 'had been', misconception: null },
      { text: 'were', misconception: 'were is for unreal present/future, not past regret' },
      { text: 'am', misconception: 'am is present tense, but the regret is about last night' },
    ],
    correctIndex: 1,
    difficulty: 0.55,
  },
  {
    id: 'item.b2.gram.04',
    level: 'B2', skill: 'general',
    nodeIds: ['gram.b2.passive'],
    stem: 'The report ______ by the committee last Friday.',
    options: [
      { text: 'approved', misconception: 'approved alone is active voice; the subject (report) received the action' },
      { text: 'was approved', misconception: null },
      { text: 'has approved', misconception: 'has approved is active and present perfect; the sentence is passive past' },
      { text: 'approving', misconception: 'approving is the -ing form, not a passive construction' },
    ],
    correctIndex: 1,
    difficulty: 0.45,
  },
  {
    id: 'item.b2.gram.05',
    level: 'B2', skill: 'general',
    nodeIds: ['gram.b2.passive'],
    stem: 'The new hospital ______ by next year.',
    options: [
      { text: 'will be completed', misconception: null },
      { text: 'will complete', misconception: 'will complete is active, but the hospital is not doing the completing' },
      { text: 'completes', misconception: 'completes is present active, not future passive' },
      { text: 'is completing', misconception: 'is completing is active continuous, the hospital is the object' },
    ],
    correctIndex: 0,
    difficulty: 0.48,
  },
  {
    id: 'item.b2.gram.06',
    level: 'B2', skill: 'general',
    nodeIds: ['gram.b2.passive'],
    stem: 'English ______ in many countries around the world.',
    options: [
      { text: 'speaks', misconception: 'speaks is active third person, but English is the object being spoken' },
      { text: 'is spoken', misconception: null },
      { text: 'speaking', misconception: 'speaking is not a complete verb form' },
      { text: 'has speaking', misconception: 'has speaking is not a valid verb form in English' },
    ],
    correctIndex: 1,
    difficulty: 0.4,
  },
  {
    id: 'item.b2.gram.07',
    level: 'B2', skill: 'general',
    nodeIds: ['gram.b2.reported_speech'],
    stem: 'She said she ______ tired.',
    options: [
      { text: 'is', misconception: 'in reported speech, present tense shifts to past tense' },
      { text: 'was', misconception: null },
      { text: 'be', misconception: 'be is the infinitive, not used in reported speech' },
      { text: 'has been', misconception: 'has been is present perfect, but said triggers tense backshift' },
    ],
    correctIndex: 1,
    difficulty: 0.45,
  },
  {
    id: 'item.b2.gram.08',
    level: 'B2', skill: 'general',
    nodeIds: ['gram.b2.reported_speech'],
    stem: 'He told me he ______ to the meeting the day before.',
    options: [
      { text: 'goes', misconception: 'goes is present tense; reported speech needs tense backshift' },
      { text: 'went', misconception: 'went is past simple, but the day before indicates a further shift' },
      { text: 'had gone', misconception: null },
      { text: 'will go', misconception: 'will go is future, but the event was in the past' },
    ],
    correctIndex: 2,
    difficulty: 0.52,
  },
  {
    id: 'item.b2.gram.09',
    level: 'B2', skill: 'general',
    nodeIds: ['gram.b2.reported_speech'],
    stem: 'The teacher asked the students ______ their homework.',
    options: [
      { text: 'to submit', misconception: null },
      { text: 'submit', misconception: 'ask someone requires the to-infinitive form' },
      { text: 'submitting', misconception: 'ask someone does not take the -ing form' },
      { text: 'that submit', misconception: 'that submit is not grammatically correct after asked' },
    ],
    correctIndex: 0,
    difficulty: 0.48,
  },
  {
    id: 'item.b2.lex.01',
    level: 'B2', skill: 'general',
    nodeIds: ['lex.b2.abstract_concepts'],
    stem: 'The government needs to address the growing ______ between rich and poor.',
    options: [
      { text: 'inequality', misconception: null },
      { text: 'difference', misconception: 'difference is too general; inequality specifically refers to unfair disparity' },
      { text: 'distance', misconception: 'distance refers to physical or emotional space, not social disparity' },
      { text: 'argument', misconception: 'argument means a disagreement, not a gap in wealth' },
    ],
    correctIndex: 0,
    difficulty: 0.42,
  },
  {
    id: 'item.b2.lex.02',
    level: 'B2', skill: 'general',
    nodeIds: ['lex.b2.abstract_concepts'],
    stem: 'The research findings ______ the theory that exercise improves mental health.',
    options: [
      { text: 'contradict', misconception: 'contradict means to oppose, but the sentence implies support' },
      { text: 'support', misconception: null },
      { text: 'ignore', misconception: 'ignore means to pay no attention, which is not what findings do' },
      { text: 'replace', misconception: 'findings do not replace theories, they test them' },
    ],
    correctIndex: 1,
    difficulty: 0.4,
  },
  {
    id: 'item.b2.read.01',
    level: 'B2', skill: 'reading',
    nodeIds: ['cando.b2.understand_argument'],
    stem: '"While some argue that remote work increases productivity, critics point out that it can lead to social isolation and blurred work-life boundaries." What is the critics\' concern?',
    options: [
      { text: 'Remote work is too expensive', misconception: 'cost is not mentioned in the passage' },
      { text: 'It may cause loneliness and unclear separation between work and personal life', misconception: null },
      { text: 'Remote work reduces productivity', misconception: 'the passage says some argue it increases productivity; critics raise different concerns' },
      { text: 'Technology is unreliable', misconception: 'technology reliability is not mentioned in the passage' },
    ],
    correctIndex: 1,
    difficulty: 0.45,
  },
  {
    id: 'item.b2.read.02',
    level: 'B2', skill: 'reading',
    nodeIds: ['cando.b2.understand_argument'],
    stem: '"Proponents of nuclear energy emphasise its low carbon emissions, while opponents highlight the risks of radioactive waste and potential meltdowns." The word "proponents" is closest in meaning to:',
    options: [
      { text: 'Critics', misconception: 'critics are opponents, not proponents' },
      { text: 'Supporters', misconception: null },
      { text: 'Scientists', misconception: 'proponents means supporters, not necessarily scientists' },
      { text: 'Victims', misconception: 'victims are people harmed, unrelated to proponents' },
    ],
    correctIndex: 1,
    difficulty: 0.42,
  },
  {
    id: 'item.b2.listen.01',
    level: 'B2', skill: 'listening',
    nodeIds: ['cando.b2.understand_discussion'],
    stem: 'In a discussion, Speaker A says: "I think universities should be free." Speaker B replies: "That\'s idealistic — who would fund the lecturers and facilities?" What is Speaker B doing?',
    options: [
      { text: 'Agreeing with Speaker A', misconception: 'Speaker B is raising a practical objection, not agreeing' },
      { text: 'Questioning the practicality of the idea', misconception: null },
      { text: 'Changing the topic', misconception: 'Speaker B is responding to the same topic, not changing it' },
      { text: 'Giving an example', misconception: 'Speaker B is raising a counter-question, not giving an example' },
    ],
    correctIndex: 1,
    difficulty: 0.48,
  },
  {
    id: 'item.b2.listen.02',
    level: 'B2', skill: 'listening',
    nodeIds: ['cando.b2.understand_discussion'],
    stem: 'A panellist says: "The data suggests a correlation, but we shouldn\'t confuse correlation with causation." What does the panellist mean?',
    options: [
      { text: 'The data is wrong', misconception: 'the panellist accepts the data but warns against wrong conclusions' },
      { text: 'Two things happening together does not mean one causes the other', misconception: null },
      { text: 'The research should be repeated', misconception: 'the panellist is clarifying interpretation, not requesting new research' },
      { text: 'Causation is more important than correlation', misconception: 'the point is about not confusing the two, not ranking them' },
    ],
    correctIndex: 1,
    difficulty: 0.52,
  },
]

// ─── C1 items (10) ─────────────────────────────────────────────────────

const C1_ITEMS: SeedItem[] = [
  {
    id: 'item.c1.read.01',
    level: 'C1', skill: 'reading',
    nodeIds: ['cando.c1.understand_abstract_text'],
    stem: '"The commodification of education has transformed students into consumers, prioritising employability metrics over intellectual curiosity." The author\'s tone is best described as:',
    options: [
      { text: 'Enthusiastic', misconception: 'the language (commodification, transformed) is negative, not enthusiastic' },
      { text: 'Critical', misconception: null },
      { text: 'Neutral', misconception: 'words like commodification carry a negative connotation, so the tone is not neutral' },
      { text: 'Humorous', misconception: 'there is no humour in this passage' },
    ],
    correctIndex: 1,
    difficulty: 0.6,
  },
  {
    id: 'item.c1.read.02',
    level: 'C1', skill: 'reading',
    nodeIds: ['cando.c1.understand_abstract_text'],
    stem: '"The paradox of choice suggests that an abundance of options can lead to decision paralysis rather than satisfaction." What does "decision paralysis" mean in this context?',
    options: [
      { text: 'Making decisions very quickly', misconception: 'paralysis means inability to act, not speed' },
      { text: 'Being unable to choose because there are too many options', misconception: null },
      { text: 'Feeling satisfied with all options', misconception: 'the passage says it leads to paralysis rather than satisfaction' },
      { text: 'Preferring not to have choices', misconception: 'the passage describes an effect of too many choices, not a preference' },
    ],
    correctIndex: 1,
    difficulty: 0.58,
  },
  {
    id: 'item.c1.read.03',
    level: 'C1', skill: 'reading',
    nodeIds: ['cando.c1.understand_abstract_text'],
    stem: '"Cognitive dissonance — the discomfort of holding contradictory beliefs — often leads individuals to rationalise their behaviour rather than change it." The function of the dashes is to:',
    options: [
      { text: 'Introduce a contrasting idea', misconception: 'the dashes define the term, they do not introduce a contrast' },
      { text: 'Provide a definition of the preceding term', misconception: null },
      { text: 'Signal a change of topic', misconception: 'the content between dashes elaborates on the same concept' },
      { text: 'Add a personal opinion', misconception: 'the definition is factual, not an opinion' },
    ],
    correctIndex: 1,
    difficulty: 0.62,
  },
  {
    id: 'item.c1.listen.01',
    level: 'C1', skill: 'listening',
    nodeIds: ['cando.c1.understand_lecture'],
    stem: 'A professor says: "While Keynesian economics dominated post-war policy, the stagflation of the 1970s fundamentally undermined its prescriptions, paving the way for monetarist approaches." What caused the shift away from Keynesian economics?',
    options: [
      { text: 'The end of World War II', misconception: 'the post-war period is when Keynesian economics was dominant, not when it declined' },
      { text: 'The economic conditions of the 1970s that Keynesian theory could not explain', misconception: null },
      { text: 'The popularity of monetarism in universities', misconception: 'the passage says stagflation paved the way, not academic popularity' },
      { text: 'Government spending cuts', misconception: 'government spending is not mentioned as the cause of the shift' },
    ],
    correctIndex: 1,
    difficulty: 0.65,
  },
  {
    id: 'item.c1.listen.02',
    level: 'C1', skill: 'listening',
    nodeIds: ['cando.c1.understand_lecture'],
    stem: 'A lecturer explains: "Epigenetics challenges the nature-versus-nurture dichotomy by demonstrating that environmental factors can alter gene expression without changing the DNA sequence itself." The main point is that:',
    options: [
      { text: 'DNA can be permanently changed by the environment', misconception: 'the passage says gene expression changes, not the DNA sequence' },
      { text: 'Nature and nurture interact in ways that blur the traditional divide', misconception: null },
      { text: 'Nurture is more important than nature', misconception: 'the passage says the dichotomy is challenged, not that nurture wins' },
      { text: 'Genetics has no influence on behaviour', misconception: 'the passage does not dismiss genetics, it shows interaction' },
    ],
    correctIndex: 1,
    difficulty: 0.68,
  },
  {
    id: 'item.c1.read.04',
    level: 'C1', skill: 'reading',
    nodeIds: ['cando.c1.understand_abstract_text'],
    stem: '"The author\'s argument rests on a false dichotomy: either we embrace unrestricted technological progress or we stagnate. This ignores the possibility of regulated innovation." The critic is accusing the author of:',
    options: [
      { text: 'Presenting only two extreme options when more exist', misconception: null },
      { text: 'Being too optimistic about technology', misconception: 'the criticism is about logical fallacy, not optimism' },
      { text: 'Ignoring scientific evidence', misconception: 'the criticism is about false dichotomy, not lack of evidence' },
      { text: 'Contradicting themselves', misconception: 'the accusation is false dichotomy, not self-contradiction' },
    ],
    correctIndex: 0,
    difficulty: 0.65,
  },
  {
    id: 'item.c1.read.05',
    level: 'C1', skill: 'reading',
    nodeIds: ['cando.c1.understand_abstract_text'],
    stem: '"The ubiquity of smartphones has engendered a culture of perpetual connectivity, eroding the boundaries between public and private spheres." The word "engendered" most closely means:',
    options: [
      { text: 'Prevented', misconception: 'engendered means created, the opposite of prevented' },
      { text: 'Given rise to', misconception: null },
      { text: 'Endangered', misconception: 'endangered means put at risk — it sounds similar but has a different meaning' },
      { text: 'Simplified', misconception: 'simplified means made easier, not created' },
    ],
    correctIndex: 1,
    difficulty: 0.6,
  },
  {
    id: 'item.c1.listen.03',
    level: 'C1', skill: 'listening',
    nodeIds: ['cando.c1.understand_lecture'],
    stem: 'A researcher states: "The replication crisis has prompted a fundamental reassessment of statistical significance thresholds, with some advocating for a shift from p < 0.05 to p < 0.005." The purpose of the proposed change is to:',
    options: [
      { text: 'Make research easier to publish', misconception: 'a stricter threshold makes publication harder, not easier' },
      { text: 'Reduce the likelihood of false positive results', misconception: null },
      { text: 'Eliminate the need for statistics in research', misconception: 'the proposal refines the threshold, not removes statistics' },
      { text: 'Speed up the peer review process', misconception: 'the change is about reliability, not review speed' },
    ],
    correctIndex: 1,
    difficulty: 0.7,
  },
  {
    id: 'item.c1.lex.01',
    level: 'C1', skill: 'general',
    nodeIds: ['lex.b2.abstract_concepts'],
    stem: 'The CEO\'s decision to restructure was met with considerable ______ from employees who feared redundancies.',
    options: [
      { text: 'ambivalence', misconception: 'ambivalence means mixed feelings, but the employees\' reaction is clearly negative' },
      { text: 'trepidation', misconception: null },
      { text: 'indifference', misconception: 'indifference means lack of concern, but the employees clearly cared' },
      { text: 'elation', misconception: 'elation means great happiness, the opposite of fearing redundancies' },
    ],
    correctIndex: 1,
    difficulty: 0.62,
  },
  {
    id: 'item.c1.lex.02',
    level: 'C1', skill: 'general',
    nodeIds: ['lex.b2.abstract_concepts'],
    stem: 'The politician\'s speech was criticised for its ______ — it sounded impressive but said very little of substance.',
    options: [
      { text: 'brevity', misconception: 'brevity means shortness; the criticism is about lack of substance, not length' },
      { text: 'rhetoric', misconception: null },
      { text: 'sincerity', misconception: 'sincerity means genuineness, the opposite of the criticism' },
      { text: 'clarity', misconception: 'clarity means clearness; the criticism is about style over substance' },
    ],
    correctIndex: 1,
    difficulty: 0.6,
  },
]

// ─── Export all items ───────────────────────────────────────────────────

export const SEED_ITEMS: SeedItem[] = [
  ...A1_ITEMS,
  ...A2_ITEMS,
  ...B1_ITEMS,
  ...B2_ITEMS,
  ...C1_ITEMS,
]
