// # ═══════════════════════════════════════════════════════════════════════════
// # PRACTICE BOOST — 60 additional items to deepen adaptive practice.
// # Covers gap-fill, error-correction, and MCQ across A1-C2.
// # Distribution: 10 per level × 6 levels = 60 items.
// # ═══════════════════════════════════════════════════════════════════════════

import type { UnifiedSeedItem } from './run-seed'

export const SEED_PRACTICE_BOOST: UnifiedSeedItem[] = [

  // # ═══════════════════════════════════════════════════════════════════
  // # A1 — 10 items (present simple, articles, prepositions)
  // # ═══════════════════════════════════════════════════════════════════

  { id: 'pb.a1.01', type: 'gap_fill', level: 'A1', skill: 'general',
    nodeIds: ['gram.a1.present_simple'],
    payload: { stem: 'She ___ to school every day.', correctAnswers: ['goes'], explanation: 'Third person (she) + present simple = goes (go + es).', difficulty: 0.15 },
  },
  { id: 'pb.a1.02', type: 'gap_fill', level: 'A1', skill: 'general',
    nodeIds: ['gram.a1.articles'],
    payload: { stem: 'I have ___ cat and ___ dog.', correctAnswers: ['a, a', 'a cat and a dog'], explanation: 'Use "a" before consonant sounds. Both "cat" and "dog" start with consonant sounds.', difficulty: 0.15 },
  },
  { id: 'pb.a1.03', type: 'error_correction', level: 'A1', skill: 'general',
    nodeIds: ['gram.a1.be_present'],
    payload: { sentence: 'He are a teacher.', correctedSentence: 'He is a teacher.', errorWord: 'are', explanation: 'He/she/it + IS (not are). "Are" is for you/we/they.', difficulty: 0.1 },
  },
  { id: 'pb.a1.04', type: 'gap_fill', level: 'A1', skill: 'general',
    nodeIds: ['gram.a1.prepositions_place'],
    payload: { stem: 'The cat is ___ the table.', correctAnswers: ['on', 'under', 'behind', 'next to'], explanation: 'Prepositions of place: on (surface), under (below), behind (back), next to (beside).', difficulty: 0.2 },
  },
  { id: 'pb.a1.05', type: 'gap_fill', level: 'A1', skill: 'general',
    nodeIds: ['gram.a1.present_simple'],
    payload: { stem: 'They ___ not like coffee.', correctAnswers: ['do'], explanation: 'Negative present simple with they/we/I/you: do not (don\'t).', difficulty: 0.15 },
  },
  { id: 'pb.a1.06', type: 'error_correction', level: 'A1', skill: 'general',
    nodeIds: ['gram.a1.present_simple'],
    payload: { sentence: 'She don\'t like pizza.', correctedSentence: 'She doesn\'t like pizza.', errorWord: "don't", explanation: 'She/he/it uses "doesn\'t" (does not), not "don\'t" (do not).', difficulty: 0.2 },
  },
  { id: 'pb.a1.07', type: 'gap_fill', level: 'A1', skill: 'general',
    nodeIds: ['gram.a1.can_cant'],
    payload: { stem: '___ you swim? — Yes, I ___.', correctAnswers: ['Can, can'], explanation: 'Can + subject for questions. Short answer: Yes, I can. / No, I can\'t.', difficulty: 0.15 },
  },
  { id: 'pb.a1.08', type: 'error_correction', level: 'A1', skill: 'general',
    nodeIds: ['gram.a1.articles'],
    payload: { sentence: 'She is a engineer.', correctedSentence: 'She is an engineer.', errorWord: 'a', explanation: 'Use "an" before vowel sounds. "Engineer" starts with an "e" sound.', difficulty: 0.15 },
  },
  { id: 'pb.a1.09', type: 'gap_fill', level: 'A1', skill: 'general',
    nodeIds: ['gram.a1.present_continuous'],
    payload: { stem: 'Look! The children ___ playing in the park.', correctAnswers: ['are'], explanation: 'Present continuous: subject + am/is/are + verb-ing. The children (they) → are.', difficulty: 0.2 },
  },
  { id: 'pb.a1.10', type: 'gap_fill', level: 'A1', skill: 'general',
    nodeIds: ['gram.a1.there_is_are'],
    payload: { stem: 'There ___ three books on the desk.', correctAnswers: ['are'], explanation: 'There is + singular. There are + plural. "Three books" is plural → are.', difficulty: 0.15 },
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # A2 — 10 items (past simple, comparatives, frequency)
  // # ═══════════════════════════════════════════════════════════════════

  { id: 'pb.a2.01', type: 'gap_fill', level: 'A2', skill: 'general',
    nodeIds: ['gram.a2.past_simple_regular'],
    payload: { stem: 'I ___ (visit) my grandmother last weekend.', correctAnswers: ['visited'], explanation: 'Past simple regular: add -ed. Visit → visited.', difficulty: 0.2 },
  },
  { id: 'pb.a2.02', type: 'gap_fill', level: 'A2', skill: 'general',
    nodeIds: ['gram.a2.past_simple_irregular'],
    payload: { stem: 'She ___ (go) to London yesterday.', correctAnswers: ['went'], explanation: 'Go is irregular: go → went → gone.', difficulty: 0.25 },
  },
  { id: 'pb.a2.03', type: 'error_correction', level: 'A2', skill: 'general',
    nodeIds: ['gram.a2.comparatives'],
    payload: { sentence: 'This book is more better than that one.', correctedSentence: 'This book is better than that one.', errorWord: 'more better', explanation: '"Better" is already comparative. Don\'t add "more" — it\'s "better," not "more better."', difficulty: 0.25 },
  },
  { id: 'pb.a2.04', type: 'gap_fill', level: 'A2', skill: 'general',
    nodeIds: ['gram.a2.comparatives'],
    payload: { stem: 'An elephant is ___ (big) than a horse.', correctAnswers: ['bigger'], explanation: 'One-syllable adjectives: add -er. Big → bigger (double the consonant).', difficulty: 0.2 },
  },
  { id: 'pb.a2.05', type: 'gap_fill', level: 'A2', skill: 'general',
    nodeIds: ['gram.a2.superlatives'],
    payload: { stem: 'Tokyo is one of the ___ (large) cities in the world.', correctAnswers: ['largest'], explanation: 'Superlative: the + adjective-est. Large → largest.', difficulty: 0.25 },
  },
  { id: 'pb.a2.06', type: 'error_correction', level: 'A2', skill: 'general',
    nodeIds: ['gram.a2.past_simple_irregular'],
    payload: { sentence: 'I goed to the cinema last night.', correctedSentence: 'I went to the cinema last night.', errorWord: 'goed', explanation: 'Go is irregular. Past simple: went (not goed).', difficulty: 0.2 },
  },
  { id: 'pb.a2.07', type: 'gap_fill', level: 'A2', skill: 'general',
    nodeIds: ['gram.a2.adverbs_frequency'],
    payload: { stem: 'She ___ goes to the gym. (3 times a week)', correctAnswers: ['often', 'usually', 'regularly'], explanation: '3 times a week = often/usually/regularly. Frequency adverbs go before the main verb.', difficulty: 0.25 },
  },
  { id: 'pb.a2.08', type: 'gap_fill', level: 'A2', skill: 'general',
    nodeIds: ['gram.a2.going_to'],
    payload: { stem: 'We ___ going to visit Paris next month.', correctAnswers: ['are'], explanation: 'Going to future: subject + am/is/are + going to + verb. We → are.', difficulty: 0.2 },
  },
  { id: 'pb.a2.09', type: 'error_correction', level: 'A2', skill: 'general',
    nodeIds: ['gram.a2.countable_uncountable'],
    payload: { sentence: 'Can I have some informations about the course?', correctedSentence: 'Can I have some information about the course?', errorWord: 'informations', explanation: '"Information" is uncountable in English — no plural form. Also: advice, furniture, luggage.', difficulty: 0.3 },
  },
  { id: 'pb.a2.10', type: 'gap_fill', level: 'A2', skill: 'general',
    nodeIds: ['gram.a2.present_perfect_experience'],
    payload: { stem: 'Have you ever ___ (be) to Japan?', correctAnswers: ['been'], explanation: 'Present perfect for experience: Have you ever + past participle. Be → been.', difficulty: 0.3 },
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # B1 — 10 items (present perfect, modals, conditionals)
  // # ═══════════════════════════════════════════════════════════════════

  { id: 'pb.b1.01', type: 'gap_fill', level: 'B1', skill: 'general',
    nodeIds: ['gram.b1.present_perfect_since_for'],
    payload: { stem: 'I have lived here ___ 2015.', correctAnswers: ['since'], explanation: 'Since + point in time (2015). For + duration (10 years).', difficulty: 0.3 },
  },
  { id: 'pb.b1.02', type: 'error_correction', level: 'B1', skill: 'general',
    nodeIds: ['gram.b1.present_perfect_since_for'],
    payload: { sentence: 'I have been working here since three years.', correctedSentence: 'I have been working here for three years.', errorWord: 'since', explanation: '"Three years" is a duration → use "for." "Since" needs a point in time (since 2023).', difficulty: 0.35 },
  },
  { id: 'pb.b1.03', type: 'gap_fill', level: 'B1', skill: 'general',
    nodeIds: ['gram.b1.second_conditional'],
    payload: { stem: 'If I ___ (have) more money, I would travel the world.', correctAnswers: ['had'], explanation: 'Second conditional: If + past simple, would + base verb. Imaginary present.', difficulty: 0.35 },
  },
  { id: 'pb.b1.04', type: 'gap_fill', level: 'B1', skill: 'general',
    nodeIds: ['gram.b1.modals_obligation'],
    payload: { stem: 'You ___ wear a seatbelt in a car. It\'s the law.', correctAnswers: ['must', 'have to'], explanation: 'Must/have to for legal obligation. "It\'s the law" = strong obligation.', difficulty: 0.3 },
  },
  { id: 'pb.b1.05', type: 'error_correction', level: 'B1', skill: 'general',
    nodeIds: ['gram.b1.reported_speech'],
    payload: { sentence: 'She said she will come tomorrow.', correctedSentence: 'She said she would come the next day.', errorWord: 'will', explanation: 'Reported speech: will → would, tomorrow → the next day.', difficulty: 0.4 },
  },
  { id: 'pb.b1.06', type: 'gap_fill', level: 'B1', skill: 'general',
    nodeIds: ['gram.b1.passive_present'],
    payload: { stem: 'English ___ spoken in many countries.', correctAnswers: ['is'], explanation: 'Passive voice: subject + is/are + past participle. English (singular) → is.', difficulty: 0.3 },
  },
  { id: 'pb.b1.07', type: 'gap_fill', level: 'B1', skill: 'general',
    nodeIds: ['gram.b1.relative_clauses'],
    payload: { stem: 'That\'s the woman ___ lives next door.', correctAnswers: ['who', 'that'], explanation: 'Who/that for people in defining relative clauses.', difficulty: 0.3 },
  },
  { id: 'pb.b1.08', type: 'error_correction', level: 'B1', skill: 'general',
    nodeIds: ['gram.b1.second_conditional'],
    payload: { sentence: 'If I would be you, I would study harder.', correctedSentence: 'If I were you, I would study harder.', errorWord: 'would be', explanation: '"If I were you" is a fixed expression. Don\'t use "would" in the if-clause of second conditionals.', difficulty: 0.4 },
  },
  { id: 'pb.b1.09', type: 'gap_fill', level: 'B1', skill: 'general',
    nodeIds: ['gram.b1.used_to'],
    payload: { stem: 'I ___ to play football when I was younger, but now I prefer tennis.', correctAnswers: ['used'], explanation: 'Used to + base verb for past habits that no longer happen.', difficulty: 0.3 },
  },
  { id: 'pb.b1.10', type: 'gap_fill', level: 'B1', skill: 'general',
    nodeIds: ['gram.b1.first_conditional'],
    payload: { stem: 'If it ___ (rain) tomorrow, we will stay at home.', correctAnswers: ['rains'], explanation: 'First conditional: If + present simple, will + base verb. Real future possibility.', difficulty: 0.3 },
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # B2 — 10 items (third conditional, wish, mixed modals)
  // # ═══════════════════════════════════════════════════════════════════

  { id: 'pb.b2.01', type: 'gap_fill', level: 'B2', skill: 'general',
    nodeIds: ['gram.b2.third_conditional'],
    payload: { stem: 'If she ___ (study) harder, she would have passed the exam.', correctAnswers: ['had studied'], explanation: 'Third conditional: If + past perfect, would have + past participle. Imaginary past.', difficulty: 0.45 },
  },
  { id: 'pb.b2.02', type: 'gap_fill', level: 'B2', skill: 'general',
    nodeIds: ['gram.b2.wish_regret'],
    payload: { stem: 'I wish I ___ (not/say) that to her yesterday.', correctAnswers: ["hadn't said", 'had not said'], explanation: 'Wish + past perfect for regrets about the past.', difficulty: 0.5 },
  },
  { id: 'pb.b2.03', type: 'error_correction', level: 'B2', skill: 'general',
    nodeIds: ['gram.b2.modals_deduction'],
    payload: { sentence: 'She must to be at home — her car is outside.', correctedSentence: 'She must be at home — her car is outside.', errorWord: 'to', explanation: 'Must + base verb (no "to"). Must be, not must to be.', difficulty: 0.4 },
  },
  { id: 'pb.b2.04', type: 'gap_fill', level: 'B2', skill: 'general',
    nodeIds: ['gram.b2.causative'],
    payload: { stem: 'I need to get my car ___ (repair).', correctAnswers: ['repaired'], explanation: 'Causative: get/have + object + past participle. Someone else does the action.', difficulty: 0.45 },
  },
  { id: 'pb.b2.05', type: 'gap_fill', level: 'B2', skill: 'general',
    nodeIds: ['gram.b2.future_perfect'],
    payload: { stem: 'By next year, I ___ (finish) my degree.', correctAnswers: ['will have finished'], explanation: 'Future perfect: will have + past participle. Completed before a future point.', difficulty: 0.45 },
  },
  { id: 'pb.b2.06', type: 'error_correction', level: 'B2', skill: 'general',
    nodeIds: ['gram.b2.passive_reporting'],
    payload: { sentence: 'It is believed that the economy will improving.', correctedSentence: 'It is believed that the economy will improve.', errorWord: 'improving', explanation: 'Will + base verb (not will + -ing). "Will improve" not "will improving."', difficulty: 0.4 },
  },
  { id: 'pb.b2.07', type: 'gap_fill', level: 'B2', skill: 'general',
    nodeIds: ['gram.b2.mixed_conditional'],
    payload: { stem: 'If I had taken that job, I ___ (live) in New York now.', correctAnswers: ['would be living', 'would live'], explanation: 'Mixed conditional: past condition → present result. If + past perfect, would + base/continuous.', difficulty: 0.55 },
  },
  { id: 'pb.b2.08', type: 'gap_fill', level: 'B2', skill: 'general',
    nodeIds: ['gram.b2.inversion_negative'],
    payload: { stem: 'Not only ___ she talented, but she is also hardworking.', correctAnswers: ['is'], explanation: 'Inversion after "Not only": Not only + auxiliary + subject. "Is she" not "she is."', difficulty: 0.5 },
  },
  { id: 'pb.b2.09', type: 'error_correction', level: 'B2', skill: 'general',
    nodeIds: ['gram.b2.wish_regret'],
    payload: { sentence: 'I wish I can speak Japanese.', correctedSentence: 'I wish I could speak Japanese.', errorWord: 'can', explanation: 'Wish + past simple for present desires. Can → could.', difficulty: 0.4 },
  },
  { id: 'pb.b2.10', type: 'sentence_transform', level: 'B2', skill: 'general',
    nodeIds: ['gram.b2.passive_reporting'],
    payload: { originalSentence: 'People say that the company is losing money.', keyWord: 'said', acceptedAnswers: ['The company is said to be losing money.', 'It is said that the company is losing money.'], explanation: 'Passive reporting: It is said that... / Subject + is said + to...', difficulty: 0.5 },
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # C1 — 10 items (cleft, ellipsis, hedging, nominalisation)
  // # ═══════════════════════════════════════════════════════════════════

  { id: 'pb.c1.01', type: 'sentence_transform', level: 'C1', skill: 'general',
    nodeIds: ['gram.c1.cleft_sentences'],
    payload: { originalSentence: 'The deadline caused the problem.', keyWord: 'what', acceptedAnswers: ['What caused the problem was the deadline.'], explanation: 'What-cleft: What + verb + was/is + focus. Emphasises "the deadline."', difficulty: 0.55 },
  },
  { id: 'pb.c1.02', type: 'gap_fill', level: 'C1', skill: 'general',
    nodeIds: ['gram.c1.nominalisation'],
    payload: { stem: 'The ___ (discover) of penicillin changed medicine forever.', correctAnswers: ['discovery'], explanation: 'Nominalisation: discover (verb) → discovery (noun). Academic style.', difficulty: 0.5 },
  },
  { id: 'pb.c1.03', type: 'error_correction', level: 'C1', skill: 'general',
    nodeIds: ['gram.c1.inversion_formal'],
    payload: { sentence: 'Seldom I have seen such a beautiful sunset.', correctedSentence: 'Seldom have I seen such a beautiful sunset.', errorWord: 'I have', explanation: 'Inversion after seldom/rarely/never: auxiliary + subject. "Have I" not "I have."', difficulty: 0.55 },
  },
  { id: 'pb.c1.04', type: 'gap_fill', level: 'C1', skill: 'general',
    nodeIds: ['gram.c1.hedging'],
    payload: { stem: 'The results ___ (suggest) that further research is needed.', correctAnswers: ['suggest', 'seem to suggest', 'appear to suggest'], explanation: 'Hedging in academic writing: suggest, appear to, seem to. Avoids absolute claims.', difficulty: 0.5 },
  },
  { id: 'pb.c1.05', type: 'sentence_transform', level: 'C1', skill: 'general',
    nodeIds: ['gram.c1.nominalisation'],
    payload: { originalSentence: 'The government decided to invest more in education.', keyWord: 'decision', acceptedAnswers: ['The government\'s decision to invest more in education...', 'The government made the decision to invest more in education.'], explanation: 'Nominalisation: decided → decision. More formal and academic.', difficulty: 0.55 },
  },
  { id: 'pb.c1.06', type: 'gap_fill', level: 'C1', skill: 'general',
    nodeIds: ['gram.c1.subjunctive'],
    payload: { stem: 'The committee recommended that the policy ___ (change).', correctAnswers: ['be changed', 'change'], explanation: 'Subjunctive after recommend/suggest/insist: base form or "be + past participle."', difficulty: 0.6 },
  },
  { id: 'pb.c1.07', type: 'error_correction', level: 'C1', skill: 'general',
    nodeIds: ['gram.c1.ellipsis'],
    payload: { sentence: 'She can play the piano and he can play the piano too.', correctedSentence: 'She can play the piano and he can too.', errorWord: 'play the piano too', explanation: 'Ellipsis: omit repeated words. "He can too" instead of "he can play the piano too."', difficulty: 0.5 },
  },
  { id: 'pb.c1.08', type: 'gap_fill', level: 'C1', skill: 'general',
    nodeIds: ['gram.c1.discourse_markers'],
    payload: { stem: 'The economy is growing; ___, unemployment remains high.', correctAnswers: ['nevertheless', 'nonetheless', 'however'], explanation: 'Concessive discourse markers: nevertheless, nonetheless, however — introduce a contrasting point.', difficulty: 0.5 },
  },
  { id: 'pb.c1.09', type: 'sentence_transform', level: 'C1', skill: 'general',
    nodeIds: ['gram.c1.cleft_sentences'],
    payload: { originalSentence: 'I really need more time.', keyWord: 'all', acceptedAnswers: ['All I need is more time.', 'All I really need is more time.'], explanation: 'All-cleft: All + subject + verb + is/was... Emphasises the single thing needed.', difficulty: 0.55 },
  },
  { id: 'pb.c1.10', type: 'gap_fill', level: 'C1', skill: 'general',
    nodeIds: ['gram.c1.participle_clauses'],
    payload: { stem: '___ (realise) his mistake, he immediately apologised.', correctAnswers: ['Having realised', 'Realising'], explanation: 'Participle clause: Having + past participle (completed action before main clause).', difficulty: 0.55 },
  },

  // # ═══════════════════════════════════════════════════════════════════
  // # C2 — 10 items (register, collocation, prosody, rhetoric)
  // # ═══════════════════════════════════════════════════════════════════

  { id: 'pb.c2.01', type: 'gap_fill', level: 'C2', skill: 'general',
    nodeIds: ['lex.c2.rare_collocations'],
    payload: { stem: 'The government\'s ___ disregard for safety regulations led to the disaster.', correctAnswers: ['flagrant', 'blatant'], explanation: 'Flagrant/blatant + disregard/violation = shockingly obvious wrongdoing.', difficulty: 0.65 },
  },
  { id: 'pb.c2.02', type: 'error_correction', level: 'C2', skill: 'general',
    nodeIds: ['lex.c2.semantic_prosody'],
    payload: { sentence: 'The new policy caused many improvements in the system.', correctedSentence: 'The new policy brought about many improvements in the system.', errorWord: 'caused', explanation: '"Cause" has negative semantic prosody (cause damage, cause problems). Use "bring about" for positive outcomes.', difficulty: 0.7 },
  },
  { id: 'pb.c2.03', type: 'gap_fill', level: 'C2', skill: 'general',
    nodeIds: ['lex.c2.register_triplets'],
    payload: { stem: 'The contract shall ___ on the 31st of December. (formal/legal)', correctAnswers: ['terminate', 'expire'], explanation: 'Legal register: terminate/expire (Latin layer). Not "end" (Anglo-Saxon) or "finish" (French).', difficulty: 0.65 },
  },
  { id: 'pb.c2.04', type: 'sentence_transform', level: 'C2', skill: 'general',
    nodeIds: ['gram.c2.fronting'],
    payload: { originalSentence: 'The impact of climate change was particularly devastating.', keyWord: 'particularly', acceptedAnswers: ['Particularly devastating was the impact of climate change.'], explanation: 'Fronting the complement for rhetorical emphasis. Literary/journalistic style.', difficulty: 0.7 },
  },
  { id: 'pb.c2.05', type: 'gap_fill', level: 'C2', skill: 'general',
    nodeIds: ['lex.c2.rare_collocations'],
    payload: { stem: 'She ___ deep resentment about being passed over for promotion.', correctAnswers: ['harboured', 'harbored'], explanation: 'Harbour resentment = hold secretly with negative connotation. Literary verb + noun collocation.', difficulty: 0.65 },
  },
  { id: 'pb.c2.06', type: 'error_correction', level: 'C2', skill: 'general',
    nodeIds: ['lex.c2.semantic_prosody'],
    payload: { sentence: 'The neighbourhood was rife with community spirit.', correctedSentence: 'The neighbourhood was brimming with community spirit.', errorWord: 'rife', explanation: '"Rife" has negative prosody (rife with corruption, problems). Use "brimming" or "teeming" for positive collocations.', difficulty: 0.7 },
  },
  { id: 'pb.c2.07', type: 'gap_fill', level: 'C2', skill: 'general',
    nodeIds: ['lex.c2.latin_phrases'],
    payload: { stem: 'The plan, ___ imperfect, was the best option available.', correctAnswers: ['albeit'], explanation: 'Albeit = although (formal concessive). Common in academic and literary writing.', difficulty: 0.6 },
  },
  { id: 'pb.c2.08', type: 'sentence_transform', level: 'C2', skill: 'general',
    nodeIds: ['gram.c2.subjunctive_literary'],
    payload: { originalSentence: 'Whether she succeeds or fails, we will support her.', keyWord: 'it', acceptedAnswers: ['Be it success or failure, we will support her.'], explanation: 'Literary subjunctive: "Be it..." = "Whether it is..." Highly formal/rhetorical.', difficulty: 0.75 },
  },
  { id: 'pb.c2.09', type: 'gap_fill', level: 'C2', skill: 'general',
    nodeIds: ['lex.c2.figurative_language'],
    payload: { stem: 'The company\'s announcement was met with a ___ silence from investors.', correctAnswers: ['deafening'], explanation: 'Oxymoron: "deafening silence" — contradictory words creating emphasis on how powerful the silence was.', difficulty: 0.6 },
  },
  { id: 'pb.c2.10', type: 'error_correction', level: 'C2', skill: 'general',
    nodeIds: ['lex.c2.register_triplets'],
    payload: { sentence: 'I hereby facilitate you to understand the situation.', correctedSentence: 'I hereby help you to understand the situation.', errorWord: 'facilitate', explanation: 'Register mismatch: "facilitate" is used for processes/systems, not direct help to a person. "Help" (Anglo-Saxon) is correct for direct interpersonal assistance.', difficulty: 0.7 },
  },
]
