// # PTE Reading Passages — fills the missing reading_passage type for PTE.
// # PTE Academic reading uses academic-style texts (300-500 words) with
// # MCQ and fill-in-the-blank questions. All content is original and
// # copyright-free, covering academic topics at B2-C1 level.

import type { UnifiedSeedItem } from './run-seed'

export const SEED_PTE_READING_PASSAGES: UnifiedSeedItem[] = [
  // # ─── Academic Reading Passages (6) ────────────────────────────────
  {
    id: 'item.pte.rp.01', type: 'reading_passage', level: 'B2', skill: 'reading',
    nodeIds: ['cando.b2.understand_argument', 'strat.pte.time_management'],
    payload: {
      title: 'The Economics of Attention',
      passage: 'In the digital age, economists have increasingly turned their attention to attention itself as a scarce resource. The concept of the "attention economy," first proposed by Herbert Simon in 1971, has gained renewed relevance as technology companies compete for the finite hours of human consciousness.\n\nSimon observed that in an information-rich world, the wealth of information means a dearth of something else: the attention needed to process it. Every notification, headline, and algorithmic recommendation is, in economic terms, a bid for a share of this limited resource. The platforms that capture the most attention — measured in "time on site" or "daily active users" — command the highest advertising revenues.\n\nThis has created what some scholars call a "race to the bottom of the brain stem." Features like infinite scrolling, autoplay, and variable reward schedules are not accidental design choices; they exploit well-understood psychological vulnerabilities to maximise engagement. The result is a digital environment optimised for compulsion rather than satisfaction.\n\nCritics argue that the attention economy imposes significant externalities — costs borne by individuals and society that are not reflected in the market price. These include diminished capacity for sustained focus, increased rates of anxiety and depression among heavy social media users, and the degradation of public discourse as platforms incentivise emotionally charged content over nuanced analysis.\n\nDefenders of the current model contend that users voluntarily exchange their attention for free services — email, search, social networking — and that this represents a fair transaction. However, this argument rests on the assumption of informed consent, which is undermined when the mechanisms of attention capture are deliberately designed to be invisible to the user.',
      questions: [
        { id: 'q1', questionType: 'mcq', text: 'Who first proposed the concept of the "attention economy"?', options: ['Herbert Simon', 'Adam Smith', 'A technology CEO', 'The author of this passage'], correctAnswer: 0, explanation: 'The passage states the concept was "first proposed by Herbert Simon in 1971."' },
        { id: 'q2', questionType: 'mcq', text: 'What does "race to the bottom of the brain stem" suggest?', options: ['Companies are investing in brain research', 'Design features target primitive psychological responses rather than higher cognition', 'Users are becoming more intelligent', 'Brain stem injuries are increasing'], correctAnswer: 1, explanation: 'The phrase refers to exploiting "well-understood psychological vulnerabilities" through features like infinite scrolling and variable rewards.' },
        { id: 'q3', questionType: 'tfng', text: 'The passage suggests that users fully understand how attention-capture mechanisms work.', options: ['True', 'False', 'Not Given'], correctAnswer: 1, explanation: 'The passage says these mechanisms are "deliberately designed to be invisible to the user," undermining informed consent.' },
        { id: 'q4', questionType: 'mcq', text: 'What are "externalities" in this context?', options: ['Features of social media platforms', 'Costs borne by individuals and society not reflected in the market price', 'External hardware devices', 'International trade agreements'], correctAnswer: 1, explanation: 'The passage defines externalities as "costs borne by individuals and society that are not reflected in the market price."' },
      ],
      difficulty: 0.5,
    },
  },
  {
    id: 'item.pte.rp.02', type: 'reading_passage', level: 'B2', skill: 'reading',
    nodeIds: ['cando.b2.understand_argument', 'strat.pte.time_management'],
    payload: {
      title: 'Coral Reef Decline and Restoration',
      passage: 'Coral reefs occupy less than 0.1% of the ocean floor yet support approximately 25% of all marine species, making them among the most biodiverse ecosystems on Earth. However, these vital structures are in precipitous decline. The latest global assessment indicates that 14% of the world\'s coral was lost between 2009 and 2018 — an area larger than all the living coral in Australia.\n\nThe primary driver of coral loss is ocean warming. Corals exist in a narrow temperature range, and when water temperatures exceed their tolerance threshold — typically by just 1-2 degrees Celsius above the seasonal maximum — they expel the symbiotic algae that provide up to 90% of their energy. This process, known as bleaching, leaves the coral white and, if prolonged, leads to starvation and death.\n\nOcean acidification compounds the problem. As the oceans absorb roughly a quarter of atmospheric carbon dioxide, the resulting chemical changes reduce the availability of carbonate ions that corals need to build their calcium carbonate skeletons. Studies project that by 2050, most tropical waters will be too acidic for healthy coral growth.\n\nRestoration efforts are underway but face significant challenges of scale. Coral gardening — growing fragments in underwater nurseries and transplanting them onto degraded reefs — has shown promise in localised areas. More experimental approaches include selective breeding for heat tolerance and assisted gene flow, in which heat-resistant coral populations are introduced to cooler reefs to bolster their genetic resilience.\n\nScientists emphasise, however, that restoration cannot substitute for addressing the root cause. Without significant reductions in greenhouse gas emissions, even the most ambitious restoration programmes will be overwhelmed by the pace of environmental change.',
      questions: [
        { id: 'q1', questionType: 'mcq', text: 'What percentage of marine species do coral reefs support?', options: ['0.1%', '14%', '25%', '90%'], correctAnswer: 2, explanation: 'The passage states reefs "support approximately 25% of all marine species."' },
        { id: 'q2', questionType: 'mcq', text: 'What causes coral bleaching?', options: ['Pollution from ships', 'Water temperatures exceeding the coral\'s tolerance by 1-2°C', 'Overfishing near reefs', 'Lack of sunlight'], correctAnswer: 1, explanation: 'Bleaching occurs when temperatures exceed "their tolerance threshold — typically by just 1-2 degrees Celsius."' },
        { id: 'q3', questionType: 'tfng', text: 'The passage suggests that coral restoration alone can solve the problem.', options: ['True', 'False', 'Not Given'], correctAnswer: 1, explanation: 'Scientists emphasise "restoration cannot substitute for addressing the root cause" of greenhouse gas emissions.' },
        { id: 'q4', questionType: 'mcq', text: 'What is "assisted gene flow"?', options: ['Genetic modification in a laboratory', 'Introducing heat-resistant coral to cooler reefs', 'Using chemicals to strengthen coral skeletons', 'Planting artificial coral structures'], correctAnswer: 1, explanation: 'The passage defines it as introducing "heat-resistant coral populations to cooler reefs to bolster their genetic resilience."' },
      ],
      difficulty: 0.5,
    },
  },
  {
    id: 'item.pte.rp.03', type: 'reading_passage', level: 'B2', skill: 'reading',
    nodeIds: ['cando.b2.understand_argument'],
    payload: {
      title: 'The Psychology of Procrastination',
      passage: 'Procrastination — the voluntary delay of an intended action despite knowing it will lead to negative consequences — affects an estimated 20% of the adult population chronically. Contrary to popular belief, procrastination is not primarily a problem of time management or laziness. Research in behavioural psychology suggests it is fundamentally an emotion regulation problem.\n\nWhen faced with a task that triggers negative emotions — boredom, anxiety, frustration, or self-doubt — the brain seeks immediate relief. Postponing the task provides short-term emotional comfort, even as it creates long-term stress. This pattern is reinforced by what psychologists call "temporal discounting": the tendency to value immediate rewards more highly than future ones. The relief of avoiding a difficult task now feels more compelling than the distant satisfaction of completing it.\n\nThe consequences of chronic procrastination extend beyond missed deadlines. Studies have linked habitual procrastination to higher levels of stress, poorer physical health, lower academic and professional achievement, and even reduced life satisfaction. Paradoxically, procrastinators often report lower levels of wellbeing despite spending more time on leisure activities — the leisure is contaminated by guilt and anxiety about the postponed tasks.\n\nEffective interventions tend to focus not on willpower or motivation but on reducing the emotional barrier to starting. Techniques such as "implementation intentions" — specifying exactly when, where, and how a task will be done — have been shown to reduce procrastination significantly. Similarly, breaking large tasks into small, concrete steps lowers the perceived emotional cost of beginning. The most counterintuitive finding is that self-compassion, rather than self-criticism, is more effective at reducing procrastination, as harsh self-judgement actually increases the negative emotions that drive avoidance.',
      questions: [
        { id: 'q1', questionType: 'mcq', text: 'According to the passage, procrastination is primarily a problem of:', options: ['Time management', 'Laziness', 'Emotion regulation', 'Intelligence'], correctAnswer: 2, explanation: 'The passage states "it is fundamentally an emotion regulation problem."' },
        { id: 'q2', questionType: 'mcq', text: 'What is "temporal discounting"?', options: ['A financial strategy for saving money', 'Valuing immediate rewards more than future ones', 'Losing track of time while working', 'A technique for overcoming procrastination'], correctAnswer: 1, explanation: 'The passage defines it as "the tendency to value immediate rewards more highly than future ones."' },
        { id: 'q3', questionType: 'tfng', text: 'Procrastinators enjoy their leisure time more because they have more of it.', options: ['True', 'False', 'Not Given'], correctAnswer: 1, explanation: 'The passage says "the leisure is contaminated by guilt and anxiety" so they enjoy it less.' },
        { id: 'q4', questionType: 'mcq', text: 'Why is self-compassion more effective than self-criticism for reducing procrastination?', options: ['It makes people forget about their tasks', 'It reduces the negative emotions that drive avoidance', 'It increases motivation through competition', 'It eliminates the need for deadlines'], correctAnswer: 1, explanation: 'The passage says "harsh self-judgement actually increases the negative emotions that drive avoidance."' },
      ],
      difficulty: 0.45,
    },
  },
  {
    id: 'item.pte.rp.04', type: 'reading_passage', level: 'B2', skill: 'reading',
    nodeIds: ['cando.b2.understand_argument'],
    payload: {
      title: 'Renewable Energy Storage',
      passage: 'The rapid expansion of renewable energy sources such as solar and wind power has created an urgent need for effective energy storage solutions. Unlike fossil fuel plants, which can generate electricity on demand, solar panels produce power only when the sun shines and wind turbines only when the wind blows. This intermittency problem means that without adequate storage, renewable energy cannot reliably meet demand at all hours.\n\nLithium-ion batteries currently dominate the storage market, but they face limitations of cost, lifespan, and the environmental impact of mining lithium and cobalt. Researchers are therefore exploring a range of alternative technologies. Flow batteries, which store energy in liquid electrolytes held in external tanks, offer the advantage of easily scalable capacity — simply add more electrolyte. However, they are less energy-dense than lithium-ion batteries, making them unsuitable for applications where space is limited.\n\nPumped hydroelectric storage, which uses surplus electricity to pump water uphill and then releases it through turbines when needed, accounts for over 90% of global grid-scale storage today. The technology is mature and efficient, but it requires specific geographical conditions — two reservoirs at different elevations — that limit where it can be deployed.\n\nPerhaps the most promising emerging technology is green hydrogen. Excess renewable electricity can be used to split water into hydrogen and oxygen through electrolysis. The hydrogen can then be stored indefinitely and converted back to electricity through fuel cells, or used directly as a clean fuel in industrial processes and transportation. The main barrier is cost: green hydrogen currently costs roughly three times as much to produce as hydrogen from natural gas.',
      questions: [
        { id: 'q1', questionType: 'mcq', text: 'What is the "intermittency problem" with renewable energy?', options: ['Renewable energy is too expensive', 'Solar and wind only produce power under certain conditions', 'Batteries lose charge too quickly', 'Power plants break down frequently'], correctAnswer: 1, explanation: 'The passage explains that solar and wind "produce power only when the sun shines" and "only when the wind blows."' },
        { id: 'q2', questionType: 'mcq', text: 'What advantage do flow batteries have over lithium-ion batteries?', options: ['Higher energy density', 'Lower cost', 'Easily scalable capacity', 'Longer lifespan'], correctAnswer: 2, explanation: 'Flow batteries offer "easily scalable capacity — simply add more electrolyte."' },
        { id: 'q3', questionType: 'tfng', text: 'Pumped hydroelectric storage can be built anywhere.', options: ['True', 'False', 'Not Given'], correctAnswer: 1, explanation: 'It "requires specific geographical conditions — two reservoirs at different elevations — that limit where it can be deployed."' },
        { id: 'q4', questionType: 'mcq', text: 'What is the main barrier to green hydrogen adoption?', options: ['It is dangerous to store', 'It produces greenhouse gases', 'It costs about three times more than natural gas hydrogen', 'The technology does not exist yet'], correctAnswer: 2, explanation: 'The main barrier is cost: it "currently costs roughly three times as much to produce as hydrogen from natural gas."' },
      ],
      difficulty: 0.45,
    },
  },
  {
    id: 'item.pte.rp.05', type: 'reading_passage', level: 'B2', skill: 'reading',
    nodeIds: ['cando.b2.understand_argument', 'cando.b2.follow_text_structure'],
    payload: {
      title: 'The Rise of Telemedicine',
      passage: 'Telemedicine — the delivery of healthcare services via digital communication technologies — existed before the pandemic but was used by fewer than 5% of patients in most countries. Within weeks of the first lockdowns, adoption surged to over 40% in some regions, compressing what analysts predicted would be a decade of gradual uptake into a matter of months.\n\nThe benefits are substantial. Patients in rural areas who previously faced multi-hour journeys to see a specialist can now consult via video call. Follow-up appointments for chronic conditions such as diabetes and hypertension — which primarily involve reviewing test results and adjusting medication — can be conducted remotely with no loss of clinical quality. Studies have shown that patient satisfaction with telemedicine consultations is comparable to, and in some cases higher than, in-person visits.\n\nHowever, telemedicine has significant limitations. Physical examination remains impossible remotely; a doctor cannot palpate an abdomen, listen to heart sounds with a stethoscope, or assess a patient\'s gait through a screen. Certain demographics — particularly elderly patients and those in lower socioeconomic groups — may lack the digital literacy or equipment required for video consultations, creating a risk that telemedicine could widen rather than narrow health inequalities.\n\nRegulatory frameworks have struggled to keep pace. Questions around cross-border licensing, data protection, and liability in cases of misdiagnosis remain largely unresolved. The most promising model appears to be hybrid care, in which routine consultations are conducted remotely while initial assessments, complex presentations, and procedures continue in person.',
      questions: [
        { id: 'q1', questionType: 'mcq', text: 'What was the telemedicine adoption rate before the pandemic?', options: ['Over 40%', 'About 20%', 'Fewer than 5%', 'Exactly 10%'], correctAnswer: 2, explanation: 'The passage states it "was used by fewer than 5% of patients in most countries."' },
        { id: 'q2', questionType: 'mcq', text: 'Why might telemedicine widen health inequalities?', options: ['It is more expensive than in-person visits', 'Some demographics lack digital skills or equipment', 'Doctors prefer treating wealthier patients online', 'Medications cannot be prescribed remotely'], correctAnswer: 1, explanation: 'Elderly and lower socioeconomic groups "may lack the digital literacy or equipment required."' },
        { id: 'q3', questionType: 'tfng', text: 'Patient satisfaction with telemedicine is generally lower than with in-person visits.', options: ['True', 'False', 'Not Given'], correctAnswer: 1, explanation: 'Studies show satisfaction is "comparable to, and in some cases higher than, in-person visits."' },
        { id: 'q4', questionType: 'mcq', text: 'What care model does the passage suggest is most promising?', options: ['Fully remote care for all patients', 'Hybrid care combining remote and in-person elements', 'Returning to exclusively in-person care', 'AI-only diagnosis systems'], correctAnswer: 1, explanation: 'The passage concludes that "the most promising model appears to be hybrid care."' },
      ],
      difficulty: 0.4,
    },
  },
  {
    id: 'item.pte.rp.06', type: 'reading_passage', level: 'B2', skill: 'reading',
    nodeIds: ['cando.b2.understand_argument'],
    payload: {
      title: 'Multilingualism and the Brain',
      passage: 'The cognitive effects of speaking multiple languages have been studied extensively over the past two decades, yielding findings that have challenged long-held assumptions. Until the 1960s, bilingualism was widely believed to confuse children and impair cognitive development. This view has been comprehensively overturned.\n\nModern neuroimaging studies reveal that bilingual individuals show increased grey matter density in regions associated with executive function, particularly the dorsolateral prefrontal cortex and the anterior cingulate cortex. These areas are responsible for skills such as switching between tasks, inhibiting irrelevant information, and maintaining focus — collectively known as cognitive control.\n\nThe mechanism appears straightforward: because both languages are active simultaneously in a bilingual brain, the speaker must constantly suppress the non-target language while activating the target one. This continuous exercise of inhibitory control strengthens the neural networks involved, much as regular physical exercise strengthens muscles.\n\nHowever, bilingualism is not without cognitive costs. Bilinguals typically have slightly smaller vocabularies in each individual language compared to monolinguals, and they experience more frequent "tip-of-the-tongue" moments — instances where a word is known but temporarily inaccessible. Some researchers attribute this to the additional competition between two lexicons during word retrieval.\n\nThe practical implications extend beyond individual cognition. Multilingual societies tend to demonstrate greater cognitive flexibility at the population level, and some educators argue that second-language instruction should begin in early childhood, when the brain is most receptive to phonological learning. The critical question is not whether multilingualism benefits the brain — the evidence for this is robust — but how educational systems can best support its development.',
      questions: [
        { id: 'q1', questionType: 'mcq', text: 'What was the common belief about bilingualism before the 1960s?', options: ['It enhanced intelligence', 'It confused children and impaired development', 'It had no effect on cognition', 'It was beneficial for adults only'], correctAnswer: 1, explanation: 'The passage says bilingualism "was widely believed to confuse children and impair cognitive development."' },
        { id: 'q2', questionType: 'mcq', text: 'Why does bilingualism strengthen cognitive control?', options: ['Learning grammar rules improves logic', 'Constant suppression of one language exercises inhibitory control', 'Reading in two scripts increases visual processing', 'Bilingual children attend better schools'], correctAnswer: 1, explanation: 'The speaker must "constantly suppress the non-target language while activating the target one."' },
        { id: 'q3', questionType: 'tfng', text: 'Bilinguals never experience difficulty finding words.', options: ['True', 'False', 'Not Given'], correctAnswer: 1, explanation: 'Bilinguals "experience more frequent tip-of-the-tongue moments."' },
        { id: 'q4', questionType: 'mcq', text: 'According to the passage, the critical question is:', options: ['Whether bilingualism is beneficial', 'How educational systems can best support multilingualism', 'Whether children should learn only one language', 'How to measure grey matter density'], correctAnswer: 1, explanation: 'The final sentence states the question is "how educational systems can best support its development."' },
      ],
      difficulty: 0.45,
    },
  },
]
